In [1]:
# Connet mssql to retrieve hotel data

import pymssql #引入pymssql模块
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import os
import re

def conn():
    connect = pymssql.connect('121.42.61.195', 'test', 'tes@t123456#pwd2018&', 'Broker') #服务器名,账户,密码,数据库名
    if connect:
        print("连接成功!")
    return connect

conn = conn()

cursor = conn.cursor()   #创建一个游标对象,python里的sql语句都要通过cursor来执行
sql = "select planner_id, wedding_id, province, city, hotel, hotel_id from dbo.tb_hotel_wedding_planner_data"

df0 = pd.read_sql(sql,conn)
df=pd.DataFrame(df0)

print (df.head())

cursor.close()   
conn.close()

连接成功!
                             planner_id                            wedding_id  \
0  fe8c2460-0971-4973-8a34-e42019e253d8  c20a17ed-98dc-45fb-b522-65d77753bc78
1  fe8c2460-0971-4973-8a34-e42019e253d8  ca22e2ea-5963-4f14-887a-521ff372f0f0
2  fe8c2460-0971-4973-8a34-e42019e253d8  78bf6ad4-dd9f-4a75-a4c9-191ad8f590fd
3  fe8c2460-0971-4973-8a34-e42019e253d8  20b520d9-c55c-4bb4-ba41-7ef4fb180136
4  fe8c2460-0971-4973-8a34-e42019e253d8  2bc66a9f-2d66-4b31-bb2a-d0301d1db85c

  province city      hotel                              hotel_id
0      重庆市  重庆市  澳维酒店(西南门)  2632b834-759d-4e1b-a8d9-8ef4d7a40aec
1      重庆市  重庆市   重庆凯宾斯基酒店  171b36dc-df60-4a0e-af60-34fb81114819
2      重庆市  重庆市     佳宇英皇酒店  f05449d7-2a6c-4614-b77e-5c7fe8d5226f
3      重庆市  重庆市   双山国际花园酒店  c25e0f1c-4fff-4ec6-bbe1-a2ecb558fd40
4      重庆市  重庆市     银鑫世纪酒店  9ed4e2ad-857f-444b-8f32-75aaf4ecb882

In [2]:
# explore data, and then merge hotel name with province/city name into a new column
print ('unique wedding id: ', df.wedding_id.nunique(dropna=False))
print ('Null wedding id: ', df.wedding_id.isnull().sum())
print ('Non_Null wedding id: ', df.wedding_id.count()) # 非空元素个数
print ('dup wedding id: ', df.wedding_id.duplicated().sum())
#print ('dup wedding id: ', df.wedding_id.value_counts())
print (df.shape)

#df['merged'] = df['province'].map(str) + ' '+ df['city'].map(str)+ ' ' +df['hotel'].map(str)
df['merged'] = df['city'].map(str)+ ' ' +df['hotel'].map(str)
df['merged']  = df['merged'].map(lambda x: x.replace('None', ''))
df['merged']  = df['merged'].map(lambda x: x.strip())


line = "四川省  四川省尚锦翡翠酒店(成都春熙路店)府青路二段24号(近财富又一城,电子科大东校区)"
#line = "重庆市 重庆市 澳维酒店(西南门)"


# input: "四川省  四川省尚锦翡翠酒店(成都春熙路店)府青路二段24号(近财富又一城,电子科大东校区)"
# output: "四川省尚锦翡翠酒店(成都春熙路店)府青路二段24号(近财富又一城,电子科大东校区)"

def removeDupProvinceAndCity(line):
    if line:      
        # remove dup province
        matchObj = re.search( r'(\b.+省\b)', line)
        if matchObj and len(matchObj.groups()) > 0:

            #print ("matchObj.group() :", matchObj)
            print ("province match, matchObj.group(1) : ", matchObj.group(1))
            result = line.find(matchObj.group(1), len(matchObj.group(1)))
            if result != -1:
                line = line[len(matchObj.group(1)):].strip()
        else:
            pass
            #print ("no match!")
            
        # remove dup city    
        matchObj = re.search( r'(\b\w+?市\b)', line)
        if matchObj and len(matchObj.groups()) > 0:

            #print ("matchObj.group() :", matchObj)
            print ("city match, matchObj.group(1) : ", matchObj.group(1))
            result = line.find(matchObj.group(1), len(matchObj.group(1)))
            if result != -1:
                line = line[len(matchObj.group(1)):].strip()
        else:
            pass
            #print ("no match!")
    return line

#removeDupProvinceAndCity(line)
#print ("result ", line)

print (df['merged'].head(10))

df['merged']  = df['merged'].apply(lambda x: removeDupProvinceAndCity(x))
    
print (df['merged'].head(10))

unique wedding id:  17254
Null wedding id:  0
Non_Null wedding id:  17300
dup wedding id:  46
(17300, 6)
0        重庆市 澳维酒店(西南门)
1         重庆市 重庆凯宾斯基酒店
2           重庆市 佳宇英皇酒店
3         重庆市 双山国际花园酒店
4           重庆市 银鑫世纪酒店
5             重庆市 渝州宾馆
6      重庆市 重庆典雅华美达广场酒店
7    重庆市 俏巴渝(爱琴海购物公园店)
8             重庆市 海琴酒店
9    重庆市 维也纳国际酒店(观音桥店)
Name: merged, dtype: object
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  铜仁市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  遵义市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  遵义市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  遵义市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  贵阳市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  遵义市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市

city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  上饶市
city match, matchObj.group(1) :  鹰潭市
city match, matchObj.group(1) :  宜春市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  上饶市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  鹰潭市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  新余市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  吉安市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  吉安市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  吉安市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  九江市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  九江市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  吉安市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  抚州市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  上饶市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  九江市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  上饶市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  宜春市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  九江市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  宜春市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  宜春市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市

city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  宜宾市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广汉市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  骡马市
city match, matchObj.group(1) :  四川省简阳市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  宜宾市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市

city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  宜宾市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  万源市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广元市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  峨眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  长春市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市

city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  四川省成都市都江堰市都江堰市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  四川省德阳市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广元市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  宜宾市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市

city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  骡马市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  巴中市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  雅安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  宜宾市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  简阳市
city match, matchObj.group(1) :  泸州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  德阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  遂宁市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  南充市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  绵阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市

city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  重庆市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  宜春市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  宜春市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  渔市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  合味原渔市
city match, matchObj.group(1) :  南昌市
city match, matchObj.group(1) :  江西省南昌市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  乐山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  四川省成都市邛崃市邛崃市
city match, matchObj.group(1) :  资中市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  广安市
city match, matchObj.group(1) :  达州市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  四川省成都市
city match, matchObj.group(1) :  自贡市
city match, matchObj.group(1) :  西昌市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  都江堰市
city match, matchObj.group(1) :  四川省广汉市
city match, matchObj.group(1) :  四川省成都市彭州市彭州市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  内江市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  眉山市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  成都市
city match, matchObj.group(1) :  资阳市
city match, matchObj.group(1) :  成都市
0        重庆市 澳维酒店(西南门)
1         重庆市 重庆凯宾斯基酒店
2           重庆市 佳宇英皇酒店
3         重庆市 双山国际花园酒店
4           重庆市 银鑫世纪酒店
5             重庆市 渝州宾馆
6      重庆市 重庆典雅华美达广场酒店
7    重庆市 俏巴渝(爱琴海购物公园店)
8             重庆市 海琴酒店
9    重庆市 维也纳国际酒店(观音桥店)
Name: merged, dtype: object

In [3]:
import jieba

def word_segmentation(line):
    if line:
        #print (line)
        cut_words = list(jieba.cut(line))
        line = " ".join(cut_words)

    return line


df['merged_cut']  = df['merged'].apply(lambda x: word_segmentation(x))
   
print (df['merged_cut'].tail())
print (df.head())

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.067 seconds.
Prefix dict has been built succesfully.

17295         鼎 宏大 酒楼 合阳 大道 654 号 附 13 号 宝龙 城市 广场 3 层
17296                                            福寿 镇
17297    友缘 山庄 合阳 城南 津街 街道 花园村 龙眼 井 村民 小组 ( 铜梁 洞 后山 )
17298                          重庆 宝龙 戴斯 大酒店 濮岩路 223 号
17299                          希尔 安江 上城 希尔 安 大道 168 号
Name: merged_cut, dtype: object
                             planner_id                            wedding_id  \
0  fe8c2460-0971-4973-8a34-e42019e253d8  c20a17ed-98dc-45fb-b522-65d77753bc78
1  fe8c2460-0971-4973-8a34-e42019e253d8  ca22e2ea-5963-4f14-887a-521ff372f0f0
2  fe8c2460-0971-4973-8a34-e42019e253d8  78bf6ad4-dd9f-4a75-a4c9-191ad8f590fd
3  fe8c2460-0971-4973-8a34-e42019e253d8  20b520d9-c55c-4bb4-ba41-7ef4fb180136
4  fe8c2460-0971-4973-8a34-e42019e253d8  2bc66a9f-2d66-4b31-bb2a-d0301d1db85c

  province city      hotel                              hotel_id  \
0      重庆市  重庆市  澳维酒店(西南门)  2632b834-759d-4e1b-a8d9-8ef4d7a40aec
1      重庆市  重庆市   重庆凯宾斯基酒店  171b36dc-df60-4a0e-af60-34fb81114819
2      重庆市  重庆市     佳宇英皇酒店  f05449d7-2a6c-4614-b77e-5c7fe8d5226f
3      重庆市  重庆市   双山国际花园酒店  c25e0f1c-4fff-4ec6-bbe1-a2ecb558fd40
4      重庆市  重庆市     银鑫世纪酒店  9ed4e2ad-857f-444b-8f32-75aaf4ecb882

          merged            merged_cut
0  重庆市 澳维酒店(西南门)  重庆市   澳维 酒店 ( 西南 门 )
1   重庆市 重庆凯宾斯基酒店      重庆市   重庆 凯宾斯基 酒店
2     重庆市 佳宇英皇酒店        重庆市   佳宇 英皇 酒店
3   重庆市 双山国际花园酒店      重庆市   双山 国际 花园酒店
4     重庆市 银鑫世纪酒店        重庆市   银鑫 世纪 酒店

In [4]:
def calcTfidfMatrix(document):
    tfidf_model = TfidfVectorizer(token_pattern=r"(?u)\b\w+\b").fit(document)
    #print(tfidf_model.vocabulary_)
    tfidf = tfidf_model.transform(document)

    simi_matrix = (tfidf * tfidf.T).A #similarities matrix of sentences
    #simi_matrix = np.tril(simi_matrix) # only use the lower left part of the matrix
    return simi_matrix

In [22]:
# encoding=utf8  
import numpy as np

hotel_indicator = [u'酒店', u'酒楼', u'饭店', u'宾馆', u'会所', u'会馆', u'食府', u'庄园', u'人家']

def is_in_dict_values(dict, value):
    if not dict:
        return False
    for key, values in dict.items():
        if value in values:
            return True
    return False
    

def save2excel(pd_simi_matrix):
    pd_simi_matrix_g = pd_simi_matrix # full filled matrix
    pd_simi_matrix = pd.DataFrame(np.tril(pd_simi_matrix.values), columns=pd_simi_matrix.index.values.tolist(), index=pd_simi_matrix.index.values.tolist()) # only use the lower left part of the matrix

    col_names = pd_simi_matrix.columns.values.tolist()
    row_names = pd_simi_matrix.index.values.tolist() 
    threshold_low = 0.7
    threshold_high = 0.75

    pd_excel = None
    if os.path.exists("result.csv"):
        pd_excel = pd.read_csv("result.csv", index_col='ID')
        
    pd_simi_matrix_tmp = pd_simi_matrix.where(pd_simi_matrix > threshold_low, 0)
    
    simi_dict = {}

    for col in col_names:
        if not is_in_dict_values(simi_dict, col):
            
            rows_with_large_similarity = [row for row in row_names if pd_simi_matrix_tmp.loc[row, col] > threshold_low]         
            print ("col:", col, "similar rows: ", rows_with_large_similarity)

            data = None
            possible_incomplete_hotelnames2 = []
            possible_incomplete_hotelnames3 = []
            
            if len(rows_with_large_similarity) == 0: # for any hotel name with no charector
                print ("00000000000000000000")
                rows_with_large_similarity.append(col)
                data = pd.DataFrame(df, columns=['planner_id', 'wedding_id', 'hotel', 'hotel_id', 'merged'], index=rows_with_large_similarity)
                possible_incomplete_hotelnames2.append(col)
                print (data.head())
            elif (len(rows_with_large_similarity) == 1): # only one item for the hotel name
                print ("11111111111111111111")
                data = pd.DataFrame(df, columns=['planner_id', 'wedding_id', 'hotel', 'hotel_id', 'merged'], index=rows_with_large_similarity)
                if len(data.loc[col, 'hotel']) <= 4:
                    possible_incomplete_hotelnames2.append(col)
            else:
                simi_dict[col] = rows_with_large_similarity
            
                data = pd.DataFrame(df, columns=['planner_id', 'wedding_id', 'hotel', 'hotel_id', 'merged'], index=rows_with_large_similarity)

                # TODO: 如果名字是 会展，南平会展，这里推荐的是会展，应该改成推荐长名字
                temp_rec_name = data['hotel'].value_counts().idxmax()
                data['recommended_name'] = temp_rec_name
                temp_data = data[data['hotel'] == temp_rec_name]
                idx_most_possible = temp_data.index.tolist()[0]

                # find similarity around idx_most_possible from similarity matrix
                others_simi = [i for i in rows_with_large_similarity if i != idx_most_possible]
                temp_series = pd_simi_matrix_g.loc[others_simi, idx_most_possible]
                if col == 4521:
                    print (temp_series.head(20))

                possible_incomplete_hotelnames = temp_series[temp_series <= threshold_low].index.tolist()
                possible_incomplete_hotelnames2 = [row for row in possible_incomplete_hotelnames
                                                   if (len(data.loc[row, 'hotel']) <= 4 and len(data.loc[row, 'hotel']) < len(temp_rec_name))]


            for row in possible_incomplete_hotelnames2:
                print ("hotelname2", possible_incomplete_hotelnames2)
                if len(data.loc[row, 'hotel']) <= 2:
                    possible_incomplete_hotelnames3.append(row)
                    print ("wrong name!!!!")
                    continue
                    
                tmp_list = [i for i in hotel_indicator if data.loc[row, 'hotel'].find(i)>=0]
                if not any(tmp_list):
                    possible_incomplete_hotelnames3.append(row)
                               
            print ("incomplete name 3, col:", col, "row:", possible_incomplete_hotelnames3)
            
            data['possible_incomplete_hotelnames']= ""

            # if similarity is lower than others, and length is shorter than average, we can assume that's a abnormal hotel name
            data.loc[possible_incomplete_hotelnames3, 'possible_incomplete_hotelnames'] = "yes"

            if pd_excel is None:
                pd_excel = data
            else:
                pd_excel = pd.concat([pd_excel, data])
    
    # de-dup items with same index
    #idx = np.unique(pd_excel.index, return_index=True)[1]
    #pd_excel = pd_excel.iloc[idx]
    
    pd_excel['index_col'] = pd_excel.index
    pd_excel= pd_excel.drop_duplicates(subset=['index_col'], keep='first')
    
    pd_excel.to_csv("result.csv", index_label="ID")
    
    print ("end")

In [23]:
# split the big df to several small ones according to 'Province' columns

uni_values = df.province.unique()
print (uni_values) 
print ('Null  id: ', df.province.isnull().sum())
small_dfs = [df[df.province==i] for i in uni_values if i is not None]
print (len(small_dfs))
print (small_dfs[0].head())

batch_size = 3000

for sml_df in small_dfs:
    steps = sml_df.shape[0]//batch_size
    for step in range(steps+1):
        if step == steps:
            batch_df = sml_df.iloc[step * batch_size:sml_df.shape[0]]
        else:
            batch_df = sml_df.iloc[step * batch_size:(step+1) * batch_size]
        
        simi_matrix = calcTfidfMatrix(batch_df['merged_cut'].tolist())
        pd_simi_matrix = pd.DataFrame(simi_matrix, columns=batch_df.index.values.tolist(), index=batch_df.index.values.tolist())

        save2excel(pd_simi_matrix)

['重庆市' '贵州省' '海南省' '江西省' '四川省' '云南省' None]
Null  id:  67
6
                             planner_id                            wedding_id  \
0  fe8c2460-0971-4973-8a34-e42019e253d8  c20a17ed-98dc-45fb-b522-65d77753bc78
1  fe8c2460-0971-4973-8a34-e42019e253d8  ca22e2ea-5963-4f14-887a-521ff372f0f0
2  fe8c2460-0971-4973-8a34-e42019e253d8  78bf6ad4-dd9f-4a75-a4c9-191ad8f590fd
3  fe8c2460-0971-4973-8a34-e42019e253d8  20b520d9-c55c-4bb4-ba41-7ef4fb180136
4  fe8c2460-0971-4973-8a34-e42019e253d8  2bc66a9f-2d66-4b31-bb2a-d0301d1db85c

  province city      hotel                              hotel_id  \
0      重庆市  重庆市  澳维酒店(西南门)  2632b834-759d-4e1b-a8d9-8ef4d7a40aec
1      重庆市  重庆市   重庆凯宾斯基酒店  171b36dc-df60-4a0e-af60-34fb81114819
2      重庆市  重庆市     佳宇英皇酒店  f05449d7-2a6c-4614-b77e-5c7fe8d5226f
3      重庆市  重庆市   双山国际花园酒店  c25e0f1c-4fff-4ec6-bbe1-a2ecb558fd40
4      重庆市  重庆市     银鑫世纪酒店  9ed4e2ad-857f-444b-8f32-75aaf4ecb882

          merged            merged_cut
0  重庆市 澳维酒店(西南门)  重庆市   澳维 酒店 ( 西南 门 )
1   重庆市 重庆凯宾斯基酒店      重庆市   重庆 凯宾斯基 酒店
2     重庆市 佳宇英皇酒店        重庆市   佳宇 英皇 酒店
3   重庆市 双山国际花园酒店      重庆市   双山 国际 花园酒店
4     重庆市 银鑫世纪酒店        重庆市   银鑫 世纪 酒店
col: 0 similar rows:  [0, 633, 1115]
incomplete name 3, col: 0 row: []
col: 1 similar rows:  [1, 647, 1236, 2370, 2431]
incomplete name 3, col: 1 row: []
col: 2 similar rows:  [2, 87, 94, 185, 279, 422, 452, 468, 585, 686, 791, 899, 974, 1393, 1964, 2168, 2258, 2283, 2296, 2339, 2635, 13567]
incomplete name 3, col: 2 row: []
col: 3 similar rows:  [3, 45, 49, 55, 77, 186, 820, 871, 1103, 1765, 2066, 2366, 2416]
incomplete name 3, col: 3 row: []
col: 4 similar rows:  [4, 46, 48, 71, 73, 108, 198, 201, 286, 317, 318, 335, 354, 411, 414, 426, 568, 622, 934, 1001, 1022, 1133, 1141, 1256, 1335, 1342, 1347, 1475, 1479, 1480, 1498, 1499, 1635, 1831, 1934, 1962, 1970, 2000, 2090, 2205, 2305, 2309, 2341, 2511, 2514, 2521, 2527, 2529, 2567, 13366, 13518, 13538, 13543, 13572]
incomplete name 3, col: 4 row: []
col: 5 similar rows:  [5, 20, 96, 355, 503, 967, 1113, 1121, 1122, 1138, 2429, 2446]
incomplete name 3, col: 5 row: []
col: 6 similar rows:  [6, 239, 337, 1095, 1114, 1125, 1128, 1665, 1668, 2096, 2319]
incomplete name 3, col: 6 row: []
col: 7 similar rows:  [7, 204, 438, 870, 900, 909, 1037, 1836, 2106, 2536, 2554]
incomplete name 3, col: 7 row: []
col: 8 similar rows:  [8]
11111111111111111111
hotelname2 [8]
incomplete name 3, col: 8 row: []
col: 9 similar rows:  [9, 794, 970, 1403]
incomplete name 3, col: 9 row: []
col: 10 similar rows:  [10, 357, 376, 474, 502, 656, 793, 1205, 1266, 1660, 1759, 1834, 2266, 2314, 13491]
incomplete name 3, col: 10 row: []
col: 11 similar rows:  [11, 70, 81, 86, 101, 173, 193, 200, 213, 290, 296, 300, 322, 436, 504, 631, 645, 648, 705, 711, 786, 882, 980, 990, 1041, 1120, 1253, 1257, 1264, 1637, 1639, 1651, 1654, 1816, 1824, 1918, 1968, 1988, 2067, 2093, 2126, 2189, 2334, 2353, 2398, 2512, 2545, 2555, 13517, 13525]
incomplete name 3, col: 11 row: []

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:96: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

col: 12 similar rows:  [12, 993, 1106, 1792, 1798, 2228]
incomplete name 3, col: 12 row: []
col: 13 similar rows:  [13, 27]
incomplete name 3, col: 13 row: []
col: 14 similar rows:  [14, 313, 624, 782, 2371, 2373, 2384, 2492]
incomplete name 3, col: 14 row: []
col: 15 similar rows:  [15, 2288, 2299]
incomplete name 3, col: 15 row: []
col: 16 similar rows:  [16, 38, 145, 393, 635, 637, 642, 673, 1263, 1489, 1856, 1928, 2101, 2400, 13414, 13584]
incomplete name 3, col: 16 row: []
col: 17 similar rows:  [17, 1794, 2602, 13546]
incomplete name 3, col: 17 row: []
col: 18 similar rows:  [18, 118, 266, 302, 706, 933, 1633, 1702, 1774, 1919, 1963, 1981, 2070, 2092, 2215, 2604, 13430, 13532]
incomplete name 3, col: 18 row: []
col: 19 similar rows:  [19, 309, 443, 13474, 13481]
incomplete name 3, col: 19 row: []
col: 21 similar rows:  [21, 297, 427, 463, 595, 743, 865, 987, 1659, 1770, 1786, 2134, 2320, 2523, 13530]
incomplete name 3, col: 21 row: []
col: 22 similar rows:  [22, 413, 664, 1716, 1986, 2076, 13498]
incomplete name 3, col: 22 row: []
col: 23 similar rows:  [23, 152, 495, 559, 563, 687, 936, 1068, 1286, 13519, 13623, 13656]
incomplete name 3, col: 23 row: []
col: 24 similar rows:  [24, 703, 1425, 1540, 1700, 2208, 2603, 13651]
incomplete name 3, col: 24 row: []
col: 25 similar rows:  [25, 112, 623, 652, 663, 1116, 1324, 1494, 2539, 2543]
incomplete name 3, col: 25 row: []
col: 26 similar rows:  [26, 366, 1927]
incomplete name 3, col: 26 row: []
col: 28 similar rows:  [28, 137, 358, 361, 680, 1050, 1079, 1195, 1328, 1363, 2024, 2025, 2148, 2240, 2245, 2447, 2584, 13552, 13586]
incomplete name 3, col: 28 row: []
col: 29 similar rows:  [29, 75, 269, 662]
incomplete name 3, col: 29 row: []
col: 30 similar rows:  [30]
11111111111111111111
hotelname2 [30]
incomplete name 3, col: 30 row: [30]
col: 31 similar rows:  [31, 693, 1061, 1195, 1328]
incomplete name 3, col: 31 row: []
col: 32 similar rows:  [32, 429, 1805, 2292, 2331, 2627]
incomplete name 3, col: 32 row: []
col: 33 similar rows:  [33, 215, 321, 802, 885, 989, 1004, 1477, 2010, 2109, 2162, 2178, 2290, 2310]
incomplete name 3, col: 33 row: []
col: 34 similar rows:  [34, 680, 693, 1061, 1195, 1328, 2148, 2245, 13552]
incomplete name 3, col: 34 row: []
col: 35 similar rows:  [35, 219, 603, 930, 1414, 1789, 2248, 2260, 13391, 13557, 13692]
incomplete name 3, col: 35 row: []
col: 36 similar rows:  [36, 132, 660, 1285, 1357, 1935, 13390, 13547]
incomplete name 3, col: 36 row: []
col: 37 similar rows:  [37, 231, 1411, 13373]
incomplete name 3, col: 37 row: []
col: 39 similar rows:  [39, 785, 1533, 13468, 13477]
incomplete name 3, col: 39 row: []
col: 40 similar rows:  [40, 499, 864, 1032, 1753, 1837, 2203, 2535, 13404]
incomplete name 3, col: 40 row: []
col: 41 similar rows:  [41, 626, 2285]
incomplete name 3, col: 41 row: []
col: 42 similar rows:  [42]
11111111111111111111
hotelname2 [42]
incomplete name 3, col: 42 row: [42]
col: 43 similar rows:  [43, 922, 1255, 1260, 2073, 2143]
incomplete name 3, col: 43 row: []
col: 44 similar rows:  [44, 54, 62, 72, 78, 107]
incomplete name 3, col: 44 row: []
col: 47 similar rows:  [47, 619, 639, 2223]
incomplete name 3, col: 47 row: []
col: 50 similar rows:  [50, 342, 1276, 2230, 2306]
incomplete name 3, col: 50 row: []
col: 51 similar rows:  [51, 308, 646, 856, 881, 883, 1134, 1267, 1434, 1490, 1502, 1682, 1771, 1973, 2264, 2564, 2642]
incomplete name 3, col: 51 row: []
col: 52 similar rows:  [52, 80, 412, 1126, 1251, 1449, 2163, 2303, 2323, 2557]
incomplete name 3, col: 52 row: []
col: 53 similar rows:  [53]
11111111111111111111
incomplete name 3, col: 53 row: []
col: 56 similar rows:  [56, 1840]
incomplete name 3, col: 56 row: []
col: 57 similar rows:  [57]
11111111111111111111
incomplete name 3, col: 57 row: []
col: 58 similar rows:  [58, 102, 809, 844, 1422, 1760]
incomplete name 3, col: 58 row: []
col: 59 similar rows:  [59]
11111111111111111111
incomplete name 3, col: 59 row: []
col: 60 similar rows:  [60, 439, 625, 1021, 1063, 1091, 1104, 1323, 1661, 1971, 2071, 2078, 2083, 2095, 2113, 2119, 2124, 2149, 2301, 2330, 2578]
incomplete name 3, col: 60 row: []
col: 61 similar rows:  [61, 457]
incomplete name 3, col: 61 row: []
col: 63 similar rows:  [63, 148, 449]
incomplete name 3, col: 63 row: []
col: 64 similar rows:  [64]
11111111111111111111
incomplete name 3, col: 64 row: []
col: 65 similar rows:  [65, 319, 451, 583, 630, 978, 1094, 1259, 1506, 1649, 1652, 2004, 2325, 2342, 2345, 2542, 13537, 13580, 13675]
incomplete name 3, col: 65 row: []
col: 66 similar rows:  [66]
11111111111111111111
hotelname2 [66]
incomplete name 3, col: 66 row: [66]
col: 67 similar rows:  [67, 68, 69, 448, 665, 801, 825, 971, 1956, 2003, 2050, 2298, 2553, 13427]
incomplete name 3, col: 67 row: []
col: 74 similar rows:  [74]
11111111111111111111
incomplete name 3, col: 74 row: []
col: 76 similar rows:  [76, 628, 1904, 1945, 2270, 2596, 13418]
incomplete name 3, col: 76 row: []
col: 79 similar rows:  [79, 100, 320, 409, 1109, 1269, 1288, 1405, 1487, 2008, 2291, 2332]
incomplete name 3, col: 79 row: []
col: 82 similar rows:  [82]
11111111111111111111
incomplete name 3, col: 82 row: []
col: 83 similar rows:  [83, 84, 981, 1019, 1845]
incomplete name 3, col: 83 row: []
col: 85 similar rows:  [85, 117, 165, 188, 341, 344, 384, 509, 572, 819, 1003, 1261, 1305, 1564, 1571, 1631, 1697, 1698, 2045, 2582, 2588]
incomplete name 3, col: 85 row: []
col: 88 similar rows:  [88, 651]
incomplete name 3, col: 88 row: []
col: 89 similar rows:  [89, 620, 812, 829, 1117, 1478, 1667, 1903, 2363, 13370]
incomplete name 3, col: 89 row: []
col: 90 similar rows:  [90]
11111111111111111111
incomplete name 3, col: 90 row: []
col: 91 similar rows:  [91]
11111111111111111111
hotelname2 [91]
incomplete name 3, col: 91 row: []
col: 92 similar rows:  [92, 293, 1653, 1993, 2031, 2053, 2137, 13667]
incomplete name 3, col: 92 row: []
col: 93 similar rows:  [93, 121, 876, 1369, 1849, 2087, 2295]
incomplete name 3, col: 93 row: []
col: 95 similar rows:  [95, 258, 327, 419, 492, 543, 679, 721, 740, 1185, 1229, 1655, 1958, 2271, 2347, 2571, 13592]
incomplete name 3, col: 95 row: []
col: 97 similar rows:  [97, 168, 285, 403, 425, 442, 444, 445, 560, 1371, 2410, 2590, 2647]
incomplete name 3, col: 97 row: []
col: 98 similar rows:  [98, 950, 2023, 13513]
incomplete name 3, col: 98 row: []
col: 99 similar rows:  [99, 1054]
incomplete name 3, col: 99 row: []
col: 103 similar rows:  [103]
11111111111111111111
incomplete name 3, col: 103 row: []
col: 104 similar rows:  [104, 1520, 2377]
incomplete name 3, col: 104 row: []
col: 105 similar rows:  [105, 292, 636, 884, 1657]
incomplete name 3, col: 105 row: []
col: 106 similar rows:  [106, 314, 325, 728, 1482, 1563, 1974, 2193, 2286, 2358, 2524]
incomplete name 3, col: 106 row: []
col: 109 similar rows:  [109, 399, 2029]
incomplete name 3, col: 109 row: []
col: 110 similar rows:  [110, 454, 524, 641, 803, 1008, 1090, 1532, 1550, 1645, 1717, 2274, 2317, 2470, 2518, 13605, 13688]
incomplete name 3, col: 110 row: []
col: 111 similar rows:  [111]
11111111111111111111
incomplete name 3, col: 111 row: []
col: 113 similar rows:  [113]
11111111111111111111
incomplete name 3, col: 113 row: []
col: 114 similar rows:  [114]
11111111111111111111
incomplete name 3, col: 114 row: []
col: 115 similar rows:  [115]
11111111111111111111
incomplete name 3, col: 115 row: []
col: 116 similar rows:  [116]
11111111111111111111
incomplete name 3, col: 116 row: []
col: 119 similar rows:  [119, 2181]
incomplete name 3, col: 119 row: []
col: 120 similar rows:  [120]
11111111111111111111
incomplete name 3, col: 120 row: []
col: 122 similar rows:  [122]
11111111111111111111
incomplete name 3, col: 122 row: []
col: 123 similar rows:  [123]
11111111111111111111
incomplete name 3, col: 123 row: []
col: 124 similar rows:  [124, 142, 605, 921, 1861, 1872, 1873, 2131]
incomplete name 3, col: 124 row: []
col: 125 similar rows:  [125, 215, 321, 695, 802, 885, 989, 1004, 1477, 1678, 2109, 2129, 2290, 2310, 2336]
incomplete name 3, col: 125 row: []
col: 126 similar rows:  [126, 2170]
incomplete name 3, col: 126 row: []
col: 127 similar rows:  [127, 764, 13408]
incomplete name 3, col: 127 row: []
col: 128 similar rows:  [128, 1931, 1998, 2128]
incomplete name 3, col: 128 row: []
col: 129 similar rows:  [129, 582, 722, 924, 1584, 1627, 1784, 2190, 13396, 13534]
incomplete name 3, col: 129 row: []

col: 130 similar rows:  [130, 283, 432, 643, 650, 889, 1029, 1505, 1636, 1898, 1987, 2080, 2102, 2127, 2132, 2558, 13680]
incomplete name 3, col: 130 row: []
col: 131 similar rows:  [131]
11111111111111111111
incomplete name 3, col: 131 row: []
col: 133 similar rows:  [133, 688, 927]
incomplete name 3, col: 133 row: []
col: 134 similar rows:  [134]
11111111111111111111
incomplete name 3, col: 134 row: []
col: 135 similar rows:  [135, 471, 591, 783, 965, 973, 1031, 1065, 1129, 1467, 1518, 1641, 1708, 2034, 2035, 2608, 13602]
incomplete name 3, col: 135 row: []
col: 136 similar rows:  [136]
11111111111111111111
incomplete name 3, col: 136 row: []
col: 138 similar rows:  [138, 817, 905, 1787, 2019, 13551]
incomplete name 3, col: 138 row: []
col: 139 similar rows:  [139, 1142]
incomplete name 3, col: 139 row: []
col: 140 similar rows:  [140, 144, 827, 13385]
incomplete name 3, col: 140 row: []
col: 141 similar rows:  [141, 464, 1929, 13564]
incomplete name 3, col: 141 row: []
col: 143 similar rows:  [143, 199, 586, 596, 655, 824, 1766, 2110, 2123, 2544, 2556]
incomplete name 3, col: 143 row: []
col: 146 similar rows:  [146, 2012, 2187, 13553]
incomplete name 3, col: 146 row: []
col: 147 similar rows:  [147]
11111111111111111111
incomplete name 3, col: 147 row: []
col: 149 similar rows:  [149, 1137]
incomplete name 3, col: 149 row: []
col: 150 similar rows:  [150, 523, 1781, 2262, 2489, 2620, 13433]
incomplete name 3, col: 150 row: []
col: 151 similar rows:  [151, 609, 878, 935, 1002, 1077, 2182, 2560, 2566, 2573]
incomplete name 3, col: 151 row: []
col: 153 similar rows:  [153]
11111111111111111111
incomplete name 3, col: 153 row: []
col: 154 similar rows:  [154, 1166, 2478]
incomplete name 3, col: 154 row: []
col: 155 similar rows:  [155]
11111111111111111111
incomplete name 3, col: 155 row: []
col: 156 similar rows:  [156, 460]
incomplete name 3, col: 156 row: []
col: 157 similar rows:  [157, 227, 353, 380, 396, 708, 737, 2043, 2185, 2428, 2610, 13489]
incomplete name 3, col: 157 row: []
col: 158 similar rows:  [158, 922]
incomplete name 3, col: 158 row: []
col: 159 similar rows:  [159, 13476, 13591]
incomplete name 3, col: 159 row: []
col: 160 similar rows:  [160]
11111111111111111111
incomplete name 3, col: 160 row: []
col: 161 similar rows:  [161]
11111111111111111111
incomplete name 3, col: 161 row: []
col: 162 similar rows:  [162]
11111111111111111111
incomplete name 3, col: 162 row: []
col: 163 similar rows:  [163, 1794, 2602, 2644, 13546]
incomplete name 3, col: 163 row: []
col: 164 similar rows:  [164]
11111111111111111111
hotelname2 [164]
incomplete name 3, col: 164 row: [164]
col: 166 similar rows:  [166, 250]
incomplete name 3, col: 166 row: []
col: 167 similar rows:  [167, 2251, 13413]
incomplete name 3, col: 167 row: []
col: 169 similar rows:  [169]
11111111111111111111
incomplete name 3, col: 169 row: []
col: 170 similar rows:  [170]
11111111111111111111
incomplete name 3, col: 170 row: []
col: 171 similar rows:  [171, 545, 2405, 13489]
incomplete name 3, col: 171 row: []
col: 172 similar rows:  [172, 2368]
incomplete name 3, col: 172 row: []
col: 174 similar rows:  [174, 1217, 2064]
incomplete name 3, col: 174 row: []
col: 175 similar rows:  [175, 235, 1703, 1732, 13426]
incomplete name 3, col: 175 row: []
col: 176 similar rows:  [176, 741, 1158, 1187, 13638]
incomplete name 3, col: 176 row: []
col: 177 similar rows:  [177, 221, 275, 822, 947, 969, 1742, 2513]
incomplete name 3, col: 177 row: []
col: 178 similar rows:  [178, 1243, 1811, 1985, 13452, 13485]
incomplete name 3, col: 178 row: []
col: 179 similar rows:  [179, 437, 1372]
incomplete name 3, col: 179 row: []
col: 180 similar rows:  [180, 294, 539, 2282]
incomplete name 3, col: 180 row: []
col: 181 similar rows:  [181, 709, 1622, 1709]
incomplete name 3, col: 181 row: []
col: 182 similar rows:  [182, 1421, 13465, 13528]
incomplete name 3, col: 182 row: []
col: 183 similar rows:  [183]
11111111111111111111
incomplete name 3, col: 183 row: []
col: 184 similar rows:  [184, 194, 1214, 1675, 13414, 13590]
incomplete name 3, col: 184 row: []
col: 187 similar rows:  [187]
11111111111111111111
incomplete name 3, col: 187 row: []
col: 189 similar rows:  [189, 1670]
incomplete name 3, col: 189 row: []
col: 190 similar rows:  [190]
11111111111111111111
hotelname2 [190]
incomplete name 3, col: 190 row: []
col: 191 similar rows:  [191]
11111111111111111111
incomplete name 3, col: 191 row: []
col: 192 similar rows:  [192, 400]
incomplete name 3, col: 192 row: []
col: 195 similar rows:  [195]
11111111111111111111
incomplete name 3, col: 195 row: []
col: 196 similar rows:  [196, 270, 569, 621, 627, 1835, 2279]
incomplete name 3, col: 196 row: []
col: 197 similar rows:  [197, 13697]
incomplete name 3, col: 197 row: []
col: 202 similar rows:  [202, 210, 220, 260, 1271, 2038, 2490]
incomplete name 3, col: 202 row: []
col: 203 similar rows:  [203, 804, 2089]
incomplete name 3, col: 203 row: []
col: 205 similar rows:  [205, 575, 811, 1281, 2541, 13539]
incomplete name 3, col: 205 row: []
col: 206 similar rows:  [206, 2056]
incomplete name 3, col: 206 row: []
col: 207 similar rows:  [207, 253, 271, 750, 1592]
incomplete name 3, col: 207 row: []
col: 208 similar rows:  [208]
11111111111111111111
incomplete name 3, col: 208 row: []
col: 209 similar rows:  [209, 649, 682, 872, 1015, 2297]
incomplete name 3, col: 209 row: []
col: 211 similar rows:  [211]
11111111111111111111
incomplete name 3, col: 211 row: []
col: 212 similar rows:  [212, 1151, 1164, 1474]
incomplete name 3, col: 212 row: []
col: 214 similar rows:  [214, 992, 2343]
incomplete name 3, col: 214 row: []
col: 216 similar rows:  [216, 450, 558, 594, 1275, 1648, 2135, 2186, 2192, 2194, 2568]
incomplete name 3, col: 216 row: []
col: 217 similar rows:  [217]
11111111111111111111
incomplete name 3, col: 217 row: []
col: 218 similar rows:  [218]
11111111111111111111
incomplete name 3, col: 218 row: []
col: 222 similar rows:  [222, 387, 717, 810, 1942, 2239, 2257]
incomplete name 3, col: 222 row: []
col: 223 similar rows:  [223]
11111111111111111111
incomplete name 3, col: 223 row: []
col: 224 similar rows:  [224]
11111111111111111111
incomplete name 3, col: 224 row: []
col: 225 similar rows:  [225, 350, 423, 634, 1486, 1833, 2538, 13674]
incomplete name 3, col: 225 row: []
col: 226 similar rows:  [226]
11111111111111111111
incomplete name 3, col: 226 row: []
col: 228 similar rows:  [228, 732, 1566, 1647, 1729, 1755, 1937, 2601]
incomplete name 3, col: 228 row: []
col: 229 similar rows:  [229]
11111111111111111111
hotelname2 [229]
wrong name!!!!
incomplete name 3, col: 229 row: [229]
col: 230 similar rows:  [230]
11111111111111111111
incomplete name 3, col: 230 row: []
col: 232 similar rows:  [232, 1579]
incomplete name 3, col: 232 row: []
col: 233 similar rows:  [233]
11111111111111111111
hotelname2 [233]
incomplete name 3, col: 233 row: [233]
col: 234 similar rows:  [234, 736, 2060]
incomplete name 3, col: 234 row: []
col: 236 similar rows:  [236, 1038, 1273, 1464, 1823]
incomplete name 3, col: 236 row: []
col: 237 similar rows:  [237, 2344, 2409]
incomplete name 3, col: 237 row: []
col: 238 similar rows:  [238, 520]
incomplete name 3, col: 238 row: []
col: 240 similar rows:  [240, 13544]
incomplete name 3, col: 240 row: []
col: 241 similar rows:  [241]
11111111111111111111
incomplete name 3, col: 241 row: []
col: 242 similar rows:  [242, 375, 949, 1240, 1539, 13378, 13668]
incomplete name 3, col: 242 row: []
col: 243 similar rows:  [243, 493, 666, 1009, 1473, 1555, 1689, 1891, 1994, 2466, 13354, 13615]
incomplete name 3, col: 243 row: []
col: 244 similar rows:  [244, 1083]
incomplete name 3, col: 244 row: []
col: 245 similar rows:  [245, 370, 957, 1632, 1714, 2138, 2218]
incomplete name 3, col: 245 row: []
col: 246 similar rows:  [246, 1609, 1683, 13364]
incomplete name 3, col: 246 row: []
col: 247 similar rows:  [247]
11111111111111111111
incomplete name 3, col: 247 row: []
col: 248 similar rows:  [248, 700, 756, 963, 1148, 2637, 13358]
incomplete name 3, col: 248 row: []
col: 249 similar rows:  [249, 2612]
incomplete name 3, col: 249 row: []
col: 251 similar rows:  [251, 763, 1492, 1820, 13496]
incomplete name 3, col: 251 row: []
col: 252 similar rows:  [252, 1401, 1614]
incomplete name 3, col: 252 row: []
col: 254 similar rows:  [254]
11111111111111111111
incomplete name 3, col: 254 row: []
col: 255 similar rows:  [255]
11111111111111111111
incomplete name 3, col: 255 row: []
col: 256 similar rows:  [256, 548, 937, 2033]
incomplete name 3, col: 256 row: []
col: 257 similar rows:  [257]
11111111111111111111
hotelname2 [257]
incomplete name 3, col: 257 row: [257]

col: 259 similar rows:  [259]
11111111111111111111
incomplete name 3, col: 259 row: []
col: 261 similar rows:  [261, 1591]
incomplete name 3, col: 261 row: []
col: 262 similar rows:  [262, 733]
incomplete name 3, col: 262 row: []
col: 263 similar rows:  [263, 738, 1887, 1943, 2591]
incomplete name 3, col: 263 row: []
col: 264 similar rows:  [264]
11111111111111111111
hotelname2 [264]
incomplete name 3, col: 264 row: []
col: 265 similar rows:  [265, 1882, 13531]
incomplete name 3, col: 265 row: []
col: 267 similar rows:  [267]
11111111111111111111
incomplete name 3, col: 267 row: []
col: 268 similar rows:  [268]
11111111111111111111
incomplete name 3, col: 268 row: []
col: 272 similar rows:  [272, 638, 1896]
incomplete name 3, col: 272 row: []
col: 273 similar rows:  [273, 424]
incomplete name 3, col: 273 row: []
col: 274 similar rows:  [274, 988]
incomplete name 3, col: 274 row: []
col: 276 similar rows:  [276, 351, 417, 573, 1876, 2287, 2313, 2318, 2390, 2561, 2631]
incomplete name 3, col: 276 row: []
col: 277 similar rows:  [277]
11111111111111111111
hotelname2 [277]
incomplete name 3, col: 277 row: [277]
col: 278 similar rows:  [278, 894]
incomplete name 3, col: 278 row: []
col: 280 similar rows:  [280, 1413]
incomplete name 3, col: 280 row: []
col: 281 similar rows:  [281, 430, 470, 777, 898, 1020, 1099, 1167, 2011, 2133, 2532, 2533, 2633]
incomplete name 3, col: 281 row: []
col: 282 similar rows:  [282]
11111111111111111111
incomplete name 3, col: 282 row: []
col: 284 similar rows:  [284]
11111111111111111111
hotelname2 [284]
incomplete name 3, col: 284 row: [284]
col: 287 similar rows:  [287]
11111111111111111111
hotelname2 [287]
incomplete name 3, col: 287 row: [287]
col: 288 similar rows:  [288]
11111111111111111111
incomplete name 3, col: 288 row: []
col: 289 similar rows:  [289, 576, 644, 2058, 2120, 13365]
incomplete name 3, col: 289 row: []
col: 291 similar rows:  [291, 1830, 1916, 1961]
incomplete name 3, col: 291 row: []
col: 295 similar rows:  [295, 311, 2587]
incomplete name 3, col: 295 row: []
col: 298 similar rows:  [298]
11111111111111111111
hotelname2 [298]
incomplete name 3, col: 298 row: []
col: 299 similar rows:  [299, 729, 13486]
incomplete name 3, col: 299 row: []
col: 301 similar rows:  [301]
11111111111111111111
incomplete name 3, col: 301 row: []
col: 303 similar rows:  [303, 1738, 2117]
incomplete name 3, col: 303 row: []
col: 304 similar rows:  [304, 723, 998, 1017, 1443, 1524, 1888, 1913, 1976, 2105, 2108, 2225, 2565, 2600]
incomplete name 3, col: 304 row: []
col: 305 similar rows:  [305]
11111111111111111111
hotelname2 [305]
incomplete name 3, col: 305 row: [305]
col: 306 similar rows:  [306, 2273, 2481]
incomplete name 3, col: 306 row: []
col: 307 similar rows:  [307, 1560, 1920, 1924, 13415, 13571]
incomplete name 3, col: 307 row: []
col: 310 similar rows:  [310]
11111111111111111111
incomplete name 3, col: 310 row: []
col: 312 similar rows:  [312, 2598]
incomplete name 3, col: 312 row: []
col: 315 similar rows:  [315]
11111111111111111111
incomplete name 3, col: 315 row: []
col: 316 similar rows:  [316]
11111111111111111111
incomplete name 3, col: 316 row: []
col: 323 similar rows:  [323, 334, 343, 349, 1500, 2077, 2100, 2321, 2335, 13618]
incomplete name 3, col: 323 row: []
col: 324 similar rows:  [324, 13357]
incomplete name 3, col: 324 row: []
col: 326 similar rows:  [326, 1234]
incomplete name 3, col: 326 row: []
col: 328 similar rows:  [328, 1429, 1611, 2486, 2636, 13495, 13616]
incomplete name 3, col: 328 row: []
col: 329 similar rows:  [329, 352, 2385, 13645]
incomplete name 3, col: 329 row: []
col: 330 similar rows:  [330, 1292]
incomplete name 3, col: 330 row: []
col: 331 similar rows:  [331, 433, 441, 997, 1097, 1110, 1161, 2099, 2307, 2316, 2349, 2389, 2517, 13577, 13625]
incomplete name 3, col: 331 row: []
col: 332 similar rows:  [332]
11111111111111111111
incomplete name 3, col: 332 row: []
col: 333 similar rows:  [333]
11111111111111111111
incomplete name 3, col: 333 row: []
col: 336 similar rows:  [336]
11111111111111111111
incomplete name 3, col: 336 row: []
col: 338 similar rows:  [338]
11111111111111111111
hotelname2 [338]
wrong name!!!!
incomplete name 3, col: 338 row: [338]
col: 339 similar rows:  [339, 1098, 1389, 1839]
incomplete name 3, col: 339 row: []
col: 340 similar rows:  [340, 2074]
incomplete name 3, col: 340 row: []
col: 345 similar rows:  [345]
11111111111111111111
incomplete name 3, col: 345 row: []
col: 346 similar rows:  [346, 790, 807, 1152, 1173, 1254, 1512, 1804, 2042, 2300, 2308, 2369, 2407]
incomplete name 3, col: 346 row: []
col: 347 similar rows:  [347]
11111111111111111111
hotelname2 [347]
incomplete name 3, col: 347 row: [347]
col: 348 similar rows:  [348, 1991]
incomplete name 3, col: 348 row: []
col: 356 similar rows:  [356, 2401]
incomplete name 3, col: 356 row: []
col: 359 similar rows:  [359, 614]
incomplete name 3, col: 359 row: []
col: 360 similar rows:  [360, 431, 1889, 2097, 13673, 13700]
incomplete name 3, col: 360 row: []
col: 362 similar rows:  [362]
11111111111111111111
incomplete name 3, col: 362 row: []
col: 363 similar rows:  [363, 1761, 1762]
incomplete name 3, col: 363 row: []
col: 364 similar rows:  [364, 838, 2164, 13687]
incomplete name 3, col: 364 row: []
col: 365 similar rows:  [365, 1055, 13676]
incomplete name 3, col: 365 row: []
col: 367 similar rows:  [367, 1869, 2156]
incomplete name 3, col: 367 row: []
col: 368 similar rows:  [368, 1197, 1933]
incomplete name 3, col: 368 row: []
col: 369 similar rows:  [369, 386, 1190, 13448]
incomplete name 3, col: 369 row: []
col: 371 similar rows:  [371, 2174]
incomplete name 3, col: 371 row: []
col: 372 similar rows:  [372]
11111111111111111111
incomplete name 3, col: 372 row: []
col: 373 similar rows:  [373]
11111111111111111111
incomplete name 3, col: 373 row: []
col: 374 similar rows:  [374, 2241]
incomplete name 3, col: 374 row: []
col: 377 similar rows:  [377, 1399, 1917, 13375]
incomplete name 3, col: 377 row: []
col: 378 similar rows:  [378]
11111111111111111111
incomplete name 3, col: 378 row: []
col: 379 similar rows:  [379]
11111111111111111111
incomplete name 3, col: 379 row: []
col: 381 similar rows:  [381, 2442]
incomplete name 3, col: 381 row: []
col: 382 similar rows:  [382, 394, 1749, 13363, 13425]
incomplete name 3, col: 382 row: []
col: 383 similar rows:  [383]
11111111111111111111
hotelname2 [383]
incomplete name 3, col: 383 row: [383]
col: 385 similar rows:  [385]
11111111111111111111
incomplete name 3, col: 385 row: []
col: 388 similar rows:  [388, 2485, 2594]
incomplete name 3, col: 388 row: []
col: 389 similar rows:  [389]
11111111111111111111
incomplete name 3, col: 389 row: []
col: 390 similar rows:  [390, 1420, 1553, 1558, 1788, 2217, 13423, 13677]
incomplete name 3, col: 390 row: []
col: 391 similar rows:  [391, 1692, 2367]
incomplete name 3, col: 391 row: []
col: 392 similar rows:  [392]
11111111111111111111
incomplete name 3, col: 392 row: []
col: 395 similar rows:  [395, 859, 1188, 2504, 2619]
incomplete name 3, col: 395 row: []
col: 397 similar rows:  [397, 795, 1390, 13355]
incomplete name 3, col: 397 row: []
col: 398 similar rows:  [398, 479, 860, 1321, 1456, 1546, 1578, 1713]
incomplete name 3, col: 398 row: []
col: 401 similar rows:  [401, 1878]
incomplete name 3, col: 401 row: []
col: 402 similar rows:  [402, 1853]
incomplete name 3, col: 402 row: []
col: 404 similar rows:  [404, 13458, 13600]
incomplete name 3, col: 404 row: []
col: 405 similar rows:  [405]
11111111111111111111
incomplete name 3, col: 405 row: []
col: 406 similar rows:  [406]
11111111111111111111
incomplete name 3, col: 406 row: []
col: 407 similar rows:  [407, 702, 1314, 1515, 1565]
incomplete name 3, col: 407 row: []
col: 408 similar rows:  [408]
11111111111111111111
hotelname2 [408]
incomplete name 3, col: 408 row: [408]
col: 410 similar rows:  [410, 1491, 1503]
incomplete name 3, col: 410 row: []
col: 415 similar rows:  [415, 946, 1302, 1368]
incomplete name 3, col: 415 row: []
col: 416 similar rows:  [416]
11111111111111111111
incomplete name 3, col: 416 row: []
col: 418 similar rows:  [418, 1826, 1838, 2122, 13575]
incomplete name 3, col: 418 row: []
col: 420 similar rows:  [420, 1391]
incomplete name 3, col: 420 row: []
col: 421 similar rows:  [421, 991]
incomplete name 3, col: 421 row: []
col: 428 similar rows:  [428, 469, 1776, 2022]
incomplete name 3, col: 428 row: []
col: 434 similar rows:  [434]
11111111111111111111
incomplete name 3, col: 434 row: []

col: 435 similar rows:  [435, 1280, 2226, 2294, 2322]
incomplete name 3, col: 435 row: []
col: 440 similar rows:  [440, 613, 1360]
incomplete name 3, col: 440 row: []
col: 446 similar rows:  [446, 494, 953, 1543]
incomplete name 3, col: 446 row: []
col: 447 similar rows:  [447, 839, 13683]
incomplete name 3, col: 447 row: []
col: 453 similar rows:  [453, 1983]
incomplete name 3, col: 453 row: []
col: 455 similar rows:  [455]
11111111111111111111
incomplete name 3, col: 455 row: []
col: 456 similar rows:  [456]
11111111111111111111
incomplete name 3, col: 456 row: []
col: 458 similar rows:  [458]
11111111111111111111
incomplete name 3, col: 458 row: []
col: 459 similar rows:  [459, 979, 1472, 1567, 1767, 1846]
incomplete name 3, col: 459 row: []
col: 461 similar rows:  [461, 1130, 2537]
incomplete name 3, col: 461 row: []
col: 462 similar rows:  [462, 1072, 1076, 2160, 2375, 2575]
incomplete name 3, col: 462 row: []
col: 465 similar rows:  [465, 668, 676, 1907, 2576]
incomplete name 3, col: 465 row: []
col: 466 similar rows:  [466, 1250, 1965, 13633]
incomplete name 3, col: 466 row: []
col: 467 similar rows:  [467, 830, 849, 1290, 1301]
incomplete name 3, col: 467 row: []
col: 472 similar rows:  [472, 681, 956, 1006, 1239, 1397, 1545, 2473, 13511]
incomplete name 3, col: 472 row: []
col: 473 similar rows:  [473, 13637]
incomplete name 3, col: 473 row: []
col: 475 similar rows:  [475, 1247, 1876]
hotelname2 [1876]
wrong name!!!!
incomplete name 3, col: 475 row: [1876]
col: 476 similar rows:  [476, 697, 789, 887, 2329]
incomplete name 3, col: 476 row: []
col: 477 similar rows:  [477]
11111111111111111111
hotelname2 [477]
incomplete name 3, col: 477 row: []
col: 478 similar rows:  [478]
11111111111111111111
incomplete name 3, col: 478 row: []
col: 480 similar rows:  [480, 1549, 13596]
incomplete name 3, col: 480 row: []
col: 481 similar rows:  [481, 1884]
incomplete name 3, col: 481 row: []
col: 482 similar rows:  [482]
11111111111111111111
incomplete name 3, col: 482 row: []
col: 483 similar rows:  [483, 1133, 2205]
incomplete name 3, col: 483 row: []
col: 484 similar rows:  [484]
11111111111111111111
incomplete name 3, col: 484 row: []
col: 485 similar rows:  [485, 880, 2046, 13407]
incomplete name 3, col: 485 row: []
col: 486 similar rows:  [486, 2463]
incomplete name 3, col: 486 row: []
col: 487 similar rows:  [487]
11111111111111111111
incomplete name 3, col: 487 row: []
col: 488 similar rows:  [488, 1175, 13487]
incomplete name 3, col: 488 row: []
col: 489 similar rows:  [489, 1217, 1433, 2064]
hotelname2 [1217]
incomplete name 3, col: 489 row: []
col: 490 similar rows:  [490]
11111111111111111111
incomplete name 3, col: 490 row: []
col: 491 similar rows:  [491, 551, 565, 735, 1170, 1235, 1438, 1595, 1720, 2382, 2441, 13479, 13535, 13606]
incomplete name 3, col: 491 row: []
col: 496 similar rows:  [496, 818]
incomplete name 3, col: 496 row: []
col: 497 similar rows:  [497]
11111111111111111111
hotelname2 [497]
incomplete name 3, col: 497 row: [497]
col: 498 similar rows:  [498, 726, 1080, 1081, 1087, 1444, 1552, 1561, 1589, 1669, 1707, 1954, 2255, 2479, 2480, 2494, 13409, 13417]
incomplete name 3, col: 498 row: []
col: 500 similar rows:  [500, 1278, 1572, 1982]
incomplete name 3, col: 500 row: []
col: 501 similar rows:  [501, 2030]
incomplete name 3, col: 501 row: []
col: 505 similar rows:  [505, 765]
incomplete name 3, col: 505 row: []
col: 506 similar rows:  [506]
11111111111111111111
incomplete name 3, col: 506 row: []
col: 507 similar rows:  [507, 521, 643, 650, 733, 748, 889, 1029, 1505, 1636, 1898, 1987, 2036, 2052, 2080, 2102, 2127, 2132, 2381, 2411, 2558, 13680]
hotelname2 [521]
wrong name!!!!
incomplete name 3, col: 507 row: [521]
col: 508 similar rows:  [508]
11111111111111111111
incomplete name 3, col: 508 row: []
col: 510 similar rows:  [510]
11111111111111111111
incomplete name 3, col: 510 row: []
col: 511 similar rows:  [511]
11111111111111111111
incomplete name 3, col: 511 row: []
col: 512 similar rows:  [512, 1926]
incomplete name 3, col: 512 row: []
col: 513 similar rows:  [513, 2214]
incomplete name 3, col: 513 row: []
col: 514 similar rows:  [514]
11111111111111111111
incomplete name 3, col: 514 row: []
col: 515 similar rows:  [515, 1815]
incomplete name 3, col: 515 row: []
col: 516 similar rows:  [516, 2236]
incomplete name 3, col: 516 row: []
col: 517 similar rows:  [517]
11111111111111111111
incomplete name 3, col: 517 row: []
col: 518 similar rows:  [518]
11111111111111111111
incomplete name 3, col: 518 row: []
col: 519 similar rows:  [519]
11111111111111111111
incomplete name 3, col: 519 row: []
col: 522 similar rows:  [522, 708]
incomplete name 3, col: 522 row: []
col: 525 similar rows:  [525, 1162, 2350, 2420]
incomplete name 3, col: 525 row: []
col: 526 similar rows:  [526, 669, 1127, 1168, 1177, 1196, 1232, 1607, 1706, 2455]
incomplete name 3, col: 526 row: []
col: 527 similar rows:  [527]
11111111111111111111
incomplete name 3, col: 527 row: []
col: 528 similar rows:  [528, 1146]
incomplete name 3, col: 528 row: []
col: 529 similar rows:  [529]
11111111111111111111
incomplete name 3, col: 529 row: []
col: 530 similar rows:  [530]
11111111111111111111
incomplete name 3, col: 530 row: []
col: 531 similar rows:  [531, 1468, 2599]
incomplete name 3, col: 531 row: []
col: 532 similar rows:  [532, 1046, 2014, 2157, 2202, 13560]
incomplete name 3, col: 532 row: []
col: 533 similar rows:  [533]
11111111111111111111
incomplete name 3, col: 533 row: []
col: 534 similar rows:  [534]
11111111111111111111
incomplete name 3, col: 534 row: []
col: 535 similar rows:  [535, 556]
incomplete name 3, col: 535 row: []
col: 536 similar rows:  [536]
11111111111111111111
incomplete name 3, col: 536 row: []
col: 537 similar rows:  [537, 1995, 2453]
incomplete name 3, col: 537 row: []
col: 538 similar rows:  [538, 1613]
incomplete name 3, col: 538 row: []
col: 540 similar rows:  [540, 1533, 13477]
incomplete name 3, col: 540 row: []
col: 541 similar rows:  [541]
11111111111111111111
hotelname2 [541]
incomplete name 3, col: 541 row: [541]
col: 542 similar rows:  [542, 1454, 1579]
incomplete name 3, col: 542 row: []
col: 544 similar rows:  [544]
11111111111111111111
hotelname2 [544]
incomplete name 3, col: 544 row: []
col: 546 similar rows:  [546, 761, 1308, 2033]
incomplete name 3, col: 546 row: []
col: 547 similar rows:  [547]
11111111111111111111
incomplete name 3, col: 547 row: []
col: 549 similar rows:  [549, 1326, 1435, 1527, 1579, 1793, 2207, 2393, 13471]
incomplete name 3, col: 549 row: []
col: 550 similar rows:  [550]
11111111111111111111
incomplete name 3, col: 550 row: []
col: 552 similar rows:  [552, 2640, 13507, 13519]
incomplete name 3, col: 552 row: []
col: 553 similar rows:  [553, 760, 1224, 1559]
incomplete name 3, col: 553 row: []
col: 554 similar rows:  [554, 13398]
incomplete name 3, col: 554 row: []
col: 555 similar rows:  [555]
11111111111111111111
incomplete name 3, col: 555 row: []
col: 557 similar rows:  [557]
11111111111111111111
incomplete name 3, col: 557 row: []
col: 561 similar rows:  [561, 13575]
incomplete name 3, col: 561 row: []
col: 562 similar rows:  [562]
11111111111111111111
incomplete name 3, col: 562 row: []
col: 564 similar rows:  [564, 2454, 2462, 2483, 13608]
incomplete name 3, col: 564 row: []
col: 566 similar rows:  [566]
11111111111111111111
incomplete name 3, col: 566 row: []
col: 567 similar rows:  [567, 707, 1210, 2256]
incomplete name 3, col: 567 row: []
col: 570 similar rows:  [570, 2324, 13630]
incomplete name 3, col: 570 row: []
col: 571 similar rows:  [571]
11111111111111111111
incomplete name 3, col: 571 row: []
col: 574 similar rows:  [574, 1969]
incomplete name 3, col: 574 row: []
col: 577 similar rows:  [577, 1583]
incomplete name 3, col: 577 row: []
col: 578 similar rows:  [578]
11111111111111111111
incomplete name 3, col: 578 row: []
col: 579 similar rows:  [579]
11111111111111111111
incomplete name 3, col: 579 row: []
col: 580 similar rows:  [580, 2125]
incomplete name 3, col: 580 row: []
col: 581 similar rows:  [581]
11111111111111111111
incomplete name 3, col: 581 row: []
col: 584 similar rows:  [584, 2540]
incomplete name 3, col: 584 row: []
col: 587 similar rows:  [587, 2151]
incomplete name 3, col: 587 row: []
col: 588 similar rows:  [588, 2563]
incomplete name 3, col: 588 row: []

col: 589 similar rows:  [589]
11111111111111111111
incomplete name 3, col: 589 row: []
col: 590 similar rows:  [590, 806, 1769, 1910]
incomplete name 3, col: 590 row: []
col: 592 similar rows:  [592, 600, 932, 1386, 1866]
incomplete name 3, col: 592 row: []
col: 593 similar rows:  [593, 1507]
incomplete name 3, col: 593 row: []
col: 597 similar rows:  [597, 672, 1318, 2613, 13469, 13541]
incomplete name 3, col: 597 row: []
col: 598 similar rows:  [598]
11111111111111111111
incomplete name 3, col: 598 row: []
col: 599 similar rows:  [599]
11111111111111111111
incomplete name 3, col: 599 row: []
col: 601 similar rows:  [601, 1383]
incomplete name 3, col: 601 row: []
col: 602 similar rows:  [602]
11111111111111111111
incomplete name 3, col: 602 row: []
col: 604 similar rows:  [604, 1056, 1293, 1428, 1513, 2002, 2139, 2549, 13397, 13548]
incomplete name 3, col: 604 row: []
col: 606 similar rows:  [606]
11111111111111111111
incomplete name 3, col: 606 row: []
col: 607 similar rows:  [607, 1084]
incomplete name 3, col: 607 row: []
col: 608 similar rows:  [608, 13684]
incomplete name 3, col: 608 row: []
col: 610 similar rows:  [610]
11111111111111111111
incomplete name 3, col: 610 row: []
col: 611 similar rows:  [611, 689]
incomplete name 3, col: 611 row: []
col: 612 similar rows:  [612]
11111111111111111111
incomplete name 3, col: 612 row: []
col: 615 similar rows:  [615]
11111111111111111111
incomplete name 3, col: 615 row: []
col: 616 similar rows:  [616, 617, 944]
incomplete name 3, col: 616 row: []
col: 618 similar rows:  [618, 653]
incomplete name 3, col: 618 row: []
col: 629 similar rows:  [629]
11111111111111111111
incomplete name 3, col: 629 row: []
col: 632 similar rows:  [632]
11111111111111111111
incomplete name 3, col: 632 row: []
col: 640 similar rows:  [640, 823, 1644, 2414, 2471]
incomplete name 3, col: 640 row: []
col: 654 similar rows:  [654]
11111111111111111111
incomplete name 3, col: 654 row: []
col: 657 similar rows:  [657]
11111111111111111111
incomplete name 3, col: 657 row: []
col: 658 similar rows:  [658, 2534]
incomplete name 3, col: 658 row: []
col: 659 similar rows:  [659, 677]
incomplete name 3, col: 659 row: []
col: 661 similar rows:  [661]
11111111111111111111
incomplete name 3, col: 661 row: []
col: 667 similar rows:  [667, 13540]
incomplete name 3, col: 667 row: []
col: 670 similar rows:  [670, 725, 834, 847, 1385, 1936, 2161]
incomplete name 3, col: 670 row: []
col: 671 similar rows:  [671]
11111111111111111111
hotelname2 [671]
incomplete name 3, col: 671 row: []
col: 674 similar rows:  [674]
11111111111111111111
incomplete name 3, col: 674 row: []
col: 675 similar rows:  [675]
11111111111111111111
incomplete name 3, col: 675 row: []
col: 678 similar rows:  [678, 842]
incomplete name 3, col: 678 row: []
col: 683 similar rows:  [683, 808, 1124, 1681, 1922, 2166]
incomplete name 3, col: 683 row: []
col: 684 similar rows:  [684]
11111111111111111111
incomplete name 3, col: 684 row: []
col: 685 similar rows:  [685]
11111111111111111111
incomplete name 3, col: 685 row: []
col: 690 similar rows:  [690, 729, 1204, 13436, 13486]
incomplete name 3, col: 690 row: []
col: 691 similar rows:  [691]
11111111111111111111
hotelname2 [691]
incomplete name 3, col: 691 row: []
col: 692 similar rows:  [692]
11111111111111111111
hotelname2 [692]
incomplete name 3, col: 692 row: [692]
col: 694 similar rows:  [694]
11111111111111111111
incomplete name 3, col: 694 row: []
col: 696 similar rows:  [696]
11111111111111111111
incomplete name 3, col: 696 row: []
col: 698 similar rows:  [698, 919, 2195, 13472, 13521]
incomplete name 3, col: 698 row: []
col: 699 similar rows:  [699]
11111111111111111111
incomplete name 3, col: 699 row: []
col: 701 similar rows:  [701]
11111111111111111111
incomplete name 3, col: 701 row: []
col: 704 similar rows:  [704, 1297]
incomplete name 3, col: 704 row: []
col: 710 similar rows:  [710, 815]
incomplete name 3, col: 710 row: []
col: 712 similar rows:  [712, 1036, 1207, 2499, 2609]
incomplete name 3, col: 712 row: []
col: 713 similar rows:  [713, 1153, 1446, 1711, 2500]
incomplete name 3, col: 713 row: []
col: 714 similar rows:  [714]
11111111111111111111
incomplete name 3, col: 714 row: []
col: 715 similar rows:  [715]
11111111111111111111
incomplete name 3, col: 715 row: []
col: 716 similar rows:  [716, 1134, 1434, 1682, 2264, 13609]
incomplete name 3, col: 716 row: []
col: 718 similar rows:  [718, 1525, 2048, 2383, 2421, 2434, 13362]
incomplete name 3, col: 718 row: []
col: 719 similar rows:  [719]
11111111111111111111
hotelname2 [719]
incomplete name 3, col: 719 row: []
col: 720 similar rows:  [720, 1643, 1658, 1662, 1932, 2094, 2354, 2546, 13665, 13666]
incomplete name 3, col: 720 row: []
col: 724 similar rows:  [724]
11111111111111111111
hotelname2 [724]
incomplete name 3, col: 724 row: [724]
col: 727 similar rows:  [727, 958]
incomplete name 3, col: 727 row: []
col: 730 similar rows:  [730]
11111111111111111111
hotelname2 [730]
incomplete name 3, col: 730 row: [730]
col: 731 similar rows:  [731]
11111111111111111111
incomplete name 3, col: 731 row: []
col: 734 similar rows:  [734, 2229]
incomplete name 3, col: 734 row: []
col: 739 similar rows:  [739, 1134, 1434, 1682, 2264]
incomplete name 3, col: 739 row: []
col: 742 similar rows:  [742]
11111111111111111111
incomplete name 3, col: 742 row: []
col: 744 similar rows:  [744]
11111111111111111111
incomplete name 3, col: 744 row: []
col: 745 similar rows:  [745, 1333, 1334, 1337, 1345, 1472, 1567, 1819, 2068, 2268, 2356, 2376, 2397, 2422, 2426, 2495, 2621, 13459, 13641]
incomplete name 3, col: 745 row: []
col: 746 similar rows:  [746, 1132, 1303, 2200, 13406]
incomplete name 3, col: 746 row: []
col: 747 similar rows:  [747]
11111111111111111111
incomplete name 3, col: 747 row: []
col: 749 similar rows:  [749, 2121, 13462]
incomplete name 3, col: 749 row: []
col: 751 similar rows:  [751, 1430, 2326]
incomplete name 3, col: 751 row: []
col: 752 similar rows:  [752]
11111111111111111111
hotelname2 [752]
incomplete name 3, col: 752 row: [752]
col: 753 similar rows:  [753, 816, 2337]
incomplete name 3, col: 753 row: []
col: 754 similar rows:  [754]
11111111111111111111
hotelname2 [754]
incomplete name 3, col: 754 row: [754]
col: 755 similar rows:  [755, 1587]
incomplete name 3, col: 755 row: []
col: 757 similar rows:  [757]
11111111111111111111
incomplete name 3, col: 757 row: []
col: 758 similar rows:  [758]
11111111111111111111
incomplete name 3, col: 758 row: []
col: 759 similar rows:  [759, 1451, 2216, 13611]
incomplete name 3, col: 759 row: []
col: 762 similar rows:  [762]
11111111111111111111
incomplete name 3, col: 762 row: []
col: 766 similar rows:  [766]
11111111111111111111
incomplete name 3, col: 766 row: []
col: 767 similar rows:  [767]
11111111111111111111
incomplete name 3, col: 767 row: []
col: 768 similar rows:  [768]
11111111111111111111
hotelname2 [768]
incomplete name 3, col: 768 row: []
col: 769 similar rows:  [769, 2569]
incomplete name 3, col: 769 row: []
col: 770 similar rows:  [770, 1609, 2404]
incomplete name 3, col: 770 row: []
col: 771 similar rows:  [771]
11111111111111111111
incomplete name 3, col: 771 row: []
col: 772 similar rows:  [772]
11111111111111111111
incomplete name 3, col: 772 row: []
col: 773 similar rows:  [773]
11111111111111111111
incomplete name 3, col: 773 row: []
col: 774 similar rows:  [774, 919, 2195, 13472]
incomplete name 3, col: 774 row: []
col: 775 similar rows:  [775]
11111111111111111111
incomplete name 3, col: 775 row: []
col: 776 similar rows:  [776]
11111111111111111111
incomplete name 3, col: 776 row: []
col: 778 similar rows:  [778]
11111111111111111111
incomplete name 3, col: 778 row: []
col: 779 similar rows:  [779, 1950]
incomplete name 3, col: 779 row: []
col: 780 similar rows:  [780]
11111111111111111111
incomplete name 3, col: 780 row: []
col: 781 similar rows:  [781]
11111111111111111111
incomplete name 3, col: 781 row: []
col: 784 similar rows:  [784]
11111111111111111111
incomplete name 3, col: 784 row: []
col: 787 similar rows:  [787, 1624, 13648]
incomplete name 3, col: 787 row: []
col: 788 similar rows:  [788, 2069, 2304]
incomplete name 3, col: 788 row: []
col: 792 similar rows:  [792]
11111111111111111111
incomplete name 3, col: 792 row: []
col: 796 similar rows:  [796, 975, 1509]
incomplete name 3, col: 796 row: []
col: 797 similar rows:  [797]
11111111111111111111
incomplete name 3, col: 797 row: []

col: 798 similar rows:  [798, 805, 1030, 1400, 1843, 13369]
incomplete name 3, col: 798 row: []
col: 799 similar rows:  [799]
11111111111111111111
incomplete name 3, col: 799 row: []
col: 800 similar rows:  [800]
11111111111111111111
incomplete name 3, col: 800 row: []
col: 813 similar rows:  [813]
11111111111111111111
hotelname2 [813]
incomplete name 3, col: 813 row: [813]
col: 814 similar rows:  [814]
11111111111111111111
hotelname2 [814]
incomplete name 3, col: 814 row: [814]
col: 821 similar rows:  [821]
11111111111111111111
incomplete name 3, col: 821 row: []
col: 826 similar rows:  [826, 868]
incomplete name 3, col: 826 row: []
col: 828 similar rows:  [828, 1294, 1379, 1865, 2243, 2357]
incomplete name 3, col: 828 row: []
col: 831 similar rows:  [831, 1010, 1384, 1673, 1871]
incomplete name 3, col: 831 row: []
col: 832 similar rows:  [832]
11111111111111111111
incomplete name 3, col: 832 row: []
col: 833 similar rows:  [833]
11111111111111111111
incomplete name 3, col: 833 row: []
col: 835 similar rows:  [835, 1785, 2027]
incomplete name 3, col: 835 row: []
col: 836 similar rows:  [836, 886, 913, 1418, 1851, 1868]
incomplete name 3, col: 836 row: []
col: 837 similar rows:  [837]
11111111111111111111
incomplete name 3, col: 837 row: []
col: 840 similar rows:  [840]
11111111111111111111
incomplete name 3, col: 840 row: []
col: 841 similar rows:  [841, 1179, 1715]
incomplete name 3, col: 841 row: []
col: 843 similar rows:  [843]
11111111111111111111
incomplete name 3, col: 843 row: []
col: 845 similar rows:  [845]
11111111111111111111
incomplete name 3, col: 845 row: []
col: 846 similar rows:  [846, 1537, 1780, 2175]
incomplete name 3, col: 846 row: []
col: 848 similar rows:  [848]
11111111111111111111
incomplete name 3, col: 848 row: []
col: 850 similar rows:  [850]
11111111111111111111
incomplete name 3, col: 850 row: []
col: 851 similar rows:  [851, 2346]
incomplete name 3, col: 851 row: []
col: 852 similar rows:  [852, 2237]
incomplete name 3, col: 852 row: []
col: 853 similar rows:  [853, 925]
incomplete name 3, col: 853 row: []
col: 854 similar rows:  [854]
11111111111111111111
incomplete name 3, col: 854 row: []
col: 855 similar rows:  [855, 1036, 1139]
incomplete name 3, col: 855 row: []
col: 857 similar rows:  [857, 1590]
incomplete name 3, col: 857 row: []
col: 858 similar rows:  [858, 1159, 2593]
incomplete name 3, col: 858 row: []
col: 861 similar rows:  [861]
11111111111111111111
hotelname2 [861]
incomplete name 3, col: 861 row: [861]
col: 862 similar rows:  [862]
11111111111111111111
incomplete name 3, col: 862 row: []
col: 863 similar rows:  [863, 2180]
incomplete name 3, col: 863 row: []
col: 866 similar rows:  [866, 1213, 13431]
incomplete name 3, col: 866 row: []
col: 867 similar rows:  [867, 1417]
incomplete name 3, col: 867 row: []
col: 869 similar rows:  [869, 2049]
incomplete name 3, col: 869 row: []
col: 873 similar rows:  [873, 982, 1003, 1024, 1025, 1261, 2111, 2234, 13681]
incomplete name 3, col: 873 row: []
col: 874 similar rows:  [874, 1092, 1488, 1573, 2204, 2224, 2276, 13646]
incomplete name 3, col: 874 row: []
col: 875 similar rows:  [875, 2155]
incomplete name 3, col: 875 row: []
col: 877 similar rows:  [877]
11111111111111111111
incomplete name 3, col: 877 row: []
col: 879 similar rows:  [879]
11111111111111111111
incomplete name 3, col: 879 row: []
col: 888 similar rows:  [888]
11111111111111111111
incomplete name 3, col: 888 row: []
col: 890 similar rows:  [890, 897, 1510]
incomplete name 3, col: 890 row: []
col: 891 similar rows:  [891]
11111111111111111111
hotelname2 [891]
incomplete name 3, col: 891 row: [891]
col: 892 similar rows:  [892, 2399]
incomplete name 3, col: 892 row: []
col: 893 similar rows:  [893, 2235]
incomplete name 3, col: 893 row: []
col: 895 similar rows:  [895, 939]
incomplete name 3, col: 895 row: []
col: 896 similar rows:  [896, 1231]
incomplete name 3, col: 896 row: []
col: 901 similar rows:  [901, 1511, 1534, 1685]
incomplete name 3, col: 901 row: []
col: 902 similar rows:  [902, 1373, 1909]
incomplete name 3, col: 902 row: []
col: 903 similar rows:  [903, 1854]
incomplete name 3, col: 903 row: []
col: 904 similar rows:  [904]
11111111111111111111
incomplete name 3, col: 904 row: []
col: 906 similar rows:  [906]
11111111111111111111
incomplete name 3, col: 906 row: []
col: 907 similar rows:  [907]
11111111111111111111
incomplete name 3, col: 907 row: []
col: 908 similar rows:  [908, 1416]
incomplete name 3, col: 908 row: []
col: 910 similar rows:  [910, 918, 1356]
incomplete name 3, col: 910 row: []
col: 911 similar rows:  [911]
11111111111111111111
hotelname2 [911]
incomplete name 3, col: 911 row: [911]
col: 912 similar rows:  [912]
11111111111111111111
incomplete name 3, col: 912 row: []
col: 914 similar rows:  [914]
11111111111111111111
incomplete name 3, col: 914 row: []
col: 915 similar rows:  [915]
11111111111111111111
incomplete name 3, col: 915 row: []
col: 916 similar rows:  [916]
11111111111111111111
incomplete name 3, col: 916 row: []
col: 917 similar rows:  [917, 1887, 1943, 2055, 2591, 13500]
incomplete name 3, col: 917 row: []
col: 920 similar rows:  [920, 1528, 2015]
incomplete name 3, col: 920 row: []
col: 923 similar rows:  [923, 938, 2250]
incomplete name 3, col: 923 row: []
col: 926 similar rows:  [926, 1536]
incomplete name 3, col: 926 row: []
col: 928 similar rows:  [928]
11111111111111111111
incomplete name 3, col: 928 row: []
col: 929 similar rows:  [929]
11111111111111111111
incomplete name 3, col: 929 row: []
col: 931 similar rows:  [931]
11111111111111111111
incomplete name 3, col: 931 row: []
col: 940 similar rows:  [940]
11111111111111111111
hotelname2 [940]
incomplete name 3, col: 940 row: [940]
col: 941 similar rows:  [941]
11111111111111111111
incomplete name 3, col: 941 row: []
col: 942 similar rows:  [942]
11111111111111111111
incomplete name 3, col: 942 row: []
col: 943 similar rows:  [943]
11111111111111111111
hotelname2 [943]
incomplete name 3, col: 943 row: [943]
col: 945 similar rows:  [945]
11111111111111111111
incomplete name 3, col: 945 row: []
col: 948 similar rows:  [948, 958]
incomplete name 3, col: 948 row: []
col: 951 similar rows:  [951, 2379]
incomplete name 3, col: 951 row: []
col: 952 similar rows:  [952, 1074, 1687, 1693, 1739, 1827]
incomplete name 3, col: 952 row: []
col: 954 similar rows:  [954, 1208, 1718, 1722, 2420, 13594]
incomplete name 3, col: 954 row: []
col: 955 similar rows:  [955, 1547]
incomplete name 3, col: 955 row: []
col: 959 similar rows:  [959, 1250, 1965, 2646, 13633]
incomplete name 3, col: 959 row: []
col: 960 similar rows:  [960]
11111111111111111111
incomplete name 3, col: 960 row: []
col: 961 similar rows:  [961, 965, 973, 1065, 1129, 1467, 1641, 1708, 2034, 2035, 2608, 13602]
incomplete name 3, col: 961 row: []
col: 962 similar rows:  [962]
11111111111111111111
incomplete name 3, col: 962 row: []
col: 964 similar rows:  [964]
11111111111111111111
incomplete name 3, col: 964 row: []
col: 966 similar rows:  [966]
11111111111111111111
hotelname2 [966]
wrong name!!!!
incomplete name 3, col: 966 row: [966]
col: 968 similar rows:  [968, 1014, 1906]
incomplete name 3, col: 968 row: []
col: 972 similar rows:  [972, 984, 1504]
incomplete name 3, col: 972 row: []
col: 976 similar rows:  [976, 2641]
incomplete name 3, col: 976 row: []
col: 977 similar rows:  [977, 1462, 1677, 1748, 2079, 13352]
incomplete name 3, col: 977 row: []
col: 983 similar rows:  [983, 1029, 1096, 1505, 1636, 1898, 1987, 2080, 2102, 2127, 2132, 2515, 2558, 13680]
incomplete name 3, col: 983 row: []
col: 985 similar rows:  [985, 1101]
incomplete name 3, col: 985 row: []
col: 986 similar rows:  [986, 1105]
incomplete name 3, col: 986 row: []
col: 994 similar rows:  [994, 1392, 2269, 13696]
incomplete name 3, col: 994 row: []
col: 995 similar rows:  [995]
11111111111111111111
hotelname2 [995]
incomplete name 3, col: 995 row: [995]
col: 996 similar rows:  [996, 1033, 2221]
incomplete name 3, col: 996 row: []
col: 999 similar rows:  [999]
11111111111111111111
incomplete name 3, col: 999 row: []
col: 1000 similar rows:  [1000, 1107]
incomplete name 3, col: 1000 row: []
col: 1005 similar rows:  [1005]
11111111111111111111
incomplete name 3, col: 1005 row: []
col: 1007 similar rows:  [1007, 1377, 1782]
incomplete name 3, col: 1007 row: []

col: 1011 similar rows:  [1011, 1199]
incomplete name 3, col: 1011 row: []
col: 1012 similar rows:  [1012]
11111111111111111111
incomplete name 3, col: 1012 row: []
col: 1013 similar rows:  [1013, 1664, 13429]
incomplete name 3, col: 1013 row: []
col: 1016 similar rows:  [1016]
11111111111111111111
incomplete name 3, col: 1016 row: []
col: 1018 similar rows:  [1018, 1501, 2091]
incomplete name 3, col: 1018 row: []
col: 1023 similar rows:  [1023, 2247]
incomplete name 3, col: 1023 row: []
col: 1026 similar rows:  [1026]
11111111111111111111
incomplete name 3, col: 1026 row: []
col: 1027 similar rows:  [1027]
11111111111111111111
incomplete name 3, col: 1027 row: []
col: 1028 similar rows:  [1028, 1171, 1447, 1599, 1724, 1735, 1912, 2338]
incomplete name 3, col: 1028 row: []
col: 1034 similar rows:  [1034, 1078, 13566]
incomplete name 3, col: 1034 row: []
col: 1035 similar rows:  [1035]
11111111111111111111
incomplete name 3, col: 1035 row: []
col: 1039 similar rows:  [1039]
11111111111111111111
hotelname2 [1039]
incomplete name 3, col: 1039 row: [1039]
col: 1040 similar rows:  [1040, 2159, 2165, 2173, 2177, 2196]
incomplete name 3, col: 1040 row: []
col: 1042 similar rows:  [1042]
11111111111111111111
incomplete name 3, col: 1042 row: []
col: 1043 similar rows:  [1043]
11111111111111111111
incomplete name 3, col: 1043 row: []
col: 1044 similar rows:  [1044]
11111111111111111111
incomplete name 3, col: 1044 row: []
col: 1045 similar rows:  [1045]
11111111111111111111
incomplete name 3, col: 1045 row: []
col: 1047 similar rows:  [1047, 1048, 1299]
incomplete name 3, col: 1047 row: []
col: 1049 similar rows:  [1049]
11111111111111111111
incomplete name 3, col: 1049 row: []
col: 1051 similar rows:  [1051, 1783, 13399]
incomplete name 3, col: 1051 row: []
col: 1052 similar rows:  [1052]
11111111111111111111
incomplete name 3, col: 1052 row: []
col: 1053 similar rows:  [1053, 2580]
incomplete name 3, col: 1053 row: []
col: 1057 similar rows:  [1057, 2337]
incomplete name 3, col: 1057 row: []
col: 1058 similar rows:  [1058]
11111111111111111111
incomplete name 3, col: 1058 row: []
col: 1059 similar rows:  [1059, 1695, 1934, 2352]
incomplete name 3, col: 1059 row: []
col: 1060 similar rows:  [1060]
11111111111111111111
incomplete name 3, col: 1060 row: []
col: 1062 similar rows:  [1062]
11111111111111111111
incomplete name 3, col: 1062 row: []
col: 1064 similar rows:  [1064, 1733, 13383, 13387]
incomplete name 3, col: 1064 row: []
col: 1066 similar rows:  [1066]
11111111111111111111
incomplete name 3, col: 1066 row: []
col: 1067 similar rows:  [1067]
11111111111111111111
incomplete name 3, col: 1067 row: []
col: 1069 similar rows:  [1069]
11111111111111111111
hotelname2 [1069]
wrong name!!!!
incomplete name 3, col: 1069 row: [1069]
col: 1070 similar rows:  [1070, 13562]
incomplete name 3, col: 1070 row: []
col: 1071 similar rows:  [1071]
11111111111111111111
incomplete name 3, col: 1071 row: []
col: 1073 similar rows:  [1073, 13395]
incomplete name 3, col: 1073 row: []
col: 1075 similar rows:  [1075, 2210]
incomplete name 3, col: 1075 row: []
col: 1082 similar rows:  [1082, 1453, 1546]
incomplete name 3, col: 1082 row: []
col: 1085 similar rows:  [1085]
11111111111111111111
incomplete name 3, col: 1085 row: []
col: 1086 similar rows:  [1086]
11111111111111111111
incomplete name 3, col: 1086 row: []
col: 1088 similar rows:  [1088, 1718]
incomplete name 3, col: 1088 row: []
col: 1089 similar rows:  [1089, 13570]
incomplete name 3, col: 1089 row: []
col: 1093 similar rows:  [1093]
11111111111111111111
incomplete name 3, col: 1093 row: []
col: 1100 similar rows:  [1100, 2385, 13645]
incomplete name 3, col: 1100 row: []
col: 1102 similar rows:  [1102]
11111111111111111111
incomplete name 3, col: 1102 row: []
col: 1108 similar rows:  [1108, 1150, 13473]
incomplete name 3, col: 1108 row: []
col: 1111 similar rows:  [1111]
11111111111111111111
incomplete name 3, col: 1111 row: []
col: 1112 similar rows:  [1112, 1188, 1758, 2085, 2504]
incomplete name 3, col: 1112 row: []
col: 1118 similar rows:  [1118, 1258, 1813, 13503, 13654]
incomplete name 3, col: 1118 row: []
col: 1119 similar rows:  [1119, 2440]
incomplete name 3, col: 1119 row: []
col: 1123 similar rows:  [1123, 1514, 2227, 2516]
incomplete name 3, col: 1123 row: []
col: 1131 similar rows:  [1131, 1189, 13514]
incomplete name 3, col: 1131 row: []
col: 1135 similar rows:  [1135]
11111111111111111111
incomplete name 3, col: 1135 row: []
col: 1136 similar rows:  [1136]
11111111111111111111
incomplete name 3, col: 1136 row: []
col: 1140 similar rows:  [1140]
11111111111111111111
hotelname2 [1140]
incomplete name 3, col: 1140 row: [1140]
col: 1143 similar rows:  [1143, 1977, 2136, 2415, 2519]
incomplete name 3, col: 1143 row: []
col: 1144 similar rows:  [1144, 13617]
incomplete name 3, col: 1144 row: []
col: 1145 similar rows:  [1145, 2425]
incomplete name 3, col: 1145 row: []
col: 1147 similar rows:  [1147]
11111111111111111111
incomplete name 3, col: 1147 row: []
col: 1149 similar rows:  [1149, 13510]
incomplete name 3, col: 1149 row: []
col: 1154 similar rows:  [1154, 1560, 2028, 2413, 2497, 13415]
incomplete name 3, col: 1154 row: []
col: 1155 similar rows:  [1155]
11111111111111111111
incomplete name 3, col: 1155 row: []
col: 1156 similar rows:  [1156, 1603, 2379]
incomplete name 3, col: 1156 row: []
col: 1157 similar rows:  [1157]
11111111111111111111
incomplete name 3, col: 1157 row: []
col: 1160 similar rows:  [1160]
11111111111111111111
incomplete name 3, col: 1160 row: []
col: 1163 similar rows:  [1163, 2607]
incomplete name 3, col: 1163 row: []
col: 1165 similar rows:  [1165, 13483]
incomplete name 3, col: 1165 row: []
col: 1169 similar rows:  [1169, 2484, 13655]
incomplete name 3, col: 1169 row: []
col: 1172 similar rows:  [1172]
11111111111111111111
incomplete name 3, col: 1172 row: []
col: 1174 similar rows:  [1174]
11111111111111111111
hotelname2 [1174]
incomplete name 3, col: 1174 row: [1174]
col: 1176 similar rows:  [1176, 1191, 1542, 2632, 13475]
incomplete name 3, col: 1176 row: []
col: 1178 similar rows:  [1178]
11111111111111111111
hotelname2 [1178]
incomplete name 3, col: 1178 row: []
col: 1180 similar rows:  [1180]
11111111111111111111
incomplete name 3, col: 1180 row: []
col: 1181 similar rows:  [1181, 2615, 13613]
incomplete name 3, col: 1181 row: []
col: 1182 similar rows:  [1182]
11111111111111111111
incomplete name 3, col: 1182 row: []
col: 1183 similar rows:  [1183, 2209, 2374, 13629]
incomplete name 3, col: 1183 row: []
col: 1184 similar rows:  [1184]
11111111111111111111
incomplete name 3, col: 1184 row: []
col: 1186 similar rows:  [1186]
11111111111111111111
incomplete name 3, col: 1186 row: []
col: 1192 similar rows:  [1192, 1829]
incomplete name 3, col: 1192 row: []
col: 1193 similar rows:  [1193, 1440]
incomplete name 3, col: 1193 row: []
col: 1194 similar rows:  [1194, 1206]
incomplete name 3, col: 1194 row: []
col: 1198 similar rows:  [1198]
11111111111111111111
incomplete name 3, col: 1198 row: []
col: 1200 similar rows:  [1200, 1382]
incomplete name 3, col: 1200 row: []
col: 1201 similar rows:  [1201]
11111111111111111111
incomplete name 3, col: 1201 row: []
col: 1202 similar rows:  [1202]
11111111111111111111
incomplete name 3, col: 1202 row: []
col: 1203 similar rows:  [1203, 13441]
incomplete name 3, col: 1203 row: []
col: 1209 similar rows:  [1209, 1695]
incomplete name 3, col: 1209 row: []
col: 1211 similar rows:  [1211, 13664]
incomplete name 3, col: 1211 row: []
col: 1212 similar rows:  [1212]
11111111111111111111
incomplete name 3, col: 1212 row: []
col: 1215 similar rows:  [1215]
11111111111111111111
incomplete name 3, col: 1215 row: []
col: 1216 similar rows:  [1216, 1822, 1978, 13627, 13643]
incomplete name 3, col: 1216 row: []
col: 1218 similar rows:  [1218, 1396, 13639]
incomplete name 3, col: 1218 row: []
col: 1219 similar rows:  [1219, 13588]
incomplete name 3, col: 1219 row: []
col: 1220 similar rows:  [1220]
11111111111111111111
incomplete name 3, col: 1220 row: []
col: 1221 similar rows:  [1221]
11111111111111111111
incomplete name 3, col: 1221 row: []
col: 1222 similar rows:  [1222]
11111111111111111111
incomplete name 3, col: 1222 row: []
col: 1223 similar rows:  [1223]
11111111111111111111
incomplete name 3, col: 1223 row: []

col: 1225 similar rows:  [1225, 13581]
incomplete name 3, col: 1225 row: []
col: 1226 similar rows:  [1226, 13419]
incomplete name 3, col: 1226 row: []
col: 1227 similar rows:  [1227]
11111111111111111111
incomplete name 3, col: 1227 row: []
col: 1228 similar rows:  [1228]
11111111111111111111
incomplete name 3, col: 1228 row: []
col: 1230 similar rows:  [1230]
11111111111111111111
incomplete name 3, col: 1230 row: []
col: 1233 similar rows:  [1233]
11111111111111111111
incomplete name 3, col: 1233 row: []
col: 1237 similar rows:  [1237, 1241]
incomplete name 3, col: 1237 row: []
col: 1238 similar rows:  [1238, 2396, 2418, 2449]
incomplete name 3, col: 1238 row: []
col: 1242 similar rows:  [1242]
11111111111111111111
incomplete name 3, col: 1242 row: []
col: 1244 similar rows:  [1244, 2474, 13466]
incomplete name 3, col: 1244 row: []
col: 1245 similar rows:  [1245, 2433, 13636]
incomplete name 3, col: 1245 row: []
col: 1246 similar rows:  [1246]
11111111111111111111
incomplete name 3, col: 1246 row: []
col: 1248 similar rows:  [1248]
11111111111111111111
incomplete name 3, col: 1248 row: []
col: 1249 similar rows:  [1249]
11111111111111111111
incomplete name 3, col: 1249 row: []
col: 1252 similar rows:  [1252]
11111111111111111111
incomplete name 3, col: 1252 row: []
col: 1262 similar rows:  [1262, 2548]
incomplete name 3, col: 1262 row: []
col: 1265 similar rows:  [1265, 1680]
incomplete name 3, col: 1265 row: []
col: 1268 similar rows:  [1268, 1279, 1476]
incomplete name 3, col: 1268 row: []
col: 1270 similar rows:  [1270]
11111111111111111111
hotelname2 [1270]
incomplete name 3, col: 1270 row: [1270]
col: 1272 similar rows:  [1272, 2054, 13439]
incomplete name 3, col: 1272 row: []
col: 1274 similar rows:  [1274]
11111111111111111111
incomplete name 3, col: 1274 row: []
col: 1277 similar rows:  [1277]
11111111111111111111
incomplete name 3, col: 1277 row: []
col: 1282 similar rows:  [1282]
11111111111111111111
incomplete name 3, col: 1282 row: []
col: 1283 similar rows:  [1283, 1367, 2107]
incomplete name 3, col: 1283 row: []
col: 1284 similar rows:  [1284]
11111111111111111111
incomplete name 3, col: 1284 row: []
col: 1287 similar rows:  [1287]
11111111111111111111
incomplete name 3, col: 1287 row: []
col: 1289 similar rows:  [1289, 13356, 13470, 13492]
incomplete name 3, col: 1289 row: []
col: 1291 similar rows:  [1291, 2387]
incomplete name 3, col: 1291 row: []
col: 1295 similar rows:  [1295]
11111111111111111111
incomplete name 3, col: 1295 row: []
col: 1296 similar rows:  [1296]
11111111111111111111
incomplete name 3, col: 1296 row: []
col: 1298 similar rows:  [1298]
11111111111111111111
incomplete name 3, col: 1298 row: []
col: 1300 similar rows:  [1300]
11111111111111111111
incomplete name 3, col: 1300 row: []
col: 1304 similar rows:  [1304]
11111111111111111111
incomplete name 3, col: 1304 row: []
col: 1306 similar rows:  [1306, 2461, 2491, 13642]
incomplete name 3, col: 1306 row: []
col: 1307 similar rows:  [1307]
11111111111111111111
hotelname2 [1307]
incomplete name 3, col: 1307 row: [1307]
col: 1309 similar rows:  [1309]
11111111111111111111
incomplete name 3, col: 1309 row: []
col: 1310 similar rows:  [1310]
11111111111111111111
incomplete name 3, col: 1310 row: []
col: 1311 similar rows:  [1311, 1990, 13542]
incomplete name 3, col: 1311 row: []
col: 1312 similar rows:  [1312]
11111111111111111111
incomplete name 3, col: 1312 row: []
col: 1313 similar rows:  [1313, 1450, 2469]
incomplete name 3, col: 1313 row: []
col: 1315 similar rows:  [1315]
11111111111111111111
incomplete name 3, col: 1315 row: []
col: 1316 similar rows:  [1316]
11111111111111111111
incomplete name 3, col: 1316 row: []
col: 1317 similar rows:  [1317]
11111111111111111111
incomplete name 3, col: 1317 row: []
col: 1319 similar rows:  [1319]
11111111111111111111
hotelname2 [1319]
incomplete name 3, col: 1319 row: [1319]
col: 1320 similar rows:  [1320]
11111111111111111111
incomplete name 3, col: 1320 row: []
col: 1322 similar rows:  [1322]
11111111111111111111
incomplete name 3, col: 1322 row: []
col: 1325 similar rows:  [1325]
11111111111111111111
incomplete name 3, col: 1325 row: []
col: 1327 similar rows:  [1327]
11111111111111111111
incomplete name 3, col: 1327 row: []
col: 1329 similar rows:  [1329, 1330, 1331, 1332, 1336, 1338, 1339, 1340, 1343, 1344, 1346, 1351, 1352, 1354, 2072, 13500]
incomplete name 3, col: 1329 row: []
col: 1341 similar rows:  [1341, 1348, 1350, 2055]
incomplete name 3, col: 1341 row: []
col: 1349 similar rows:  [1349]
11111111111111111111
incomplete name 3, col: 1349 row: []
col: 1353 similar rows:  [1353, 2081, 2550]
incomplete name 3, col: 1353 row: []
col: 1355 similar rows:  [1355, 1676, 1939, 2172]
incomplete name 3, col: 1355 row: []
col: 1358 similar rows:  [1358]
11111111111111111111
incomplete name 3, col: 1358 row: []
col: 1359 similar rows:  [1359]
11111111111111111111
incomplete name 3, col: 1359 row: []
col: 1361 similar rows:  [1361]
11111111111111111111
incomplete name 3, col: 1361 row: []
col: 1362 similar rows:  [1362]
11111111111111111111
incomplete name 3, col: 1362 row: []
col: 1364 similar rows:  [1364]
11111111111111111111
incomplete name 3, col: 1364 row: []
col: 1365 similar rows:  [1365]
11111111111111111111
incomplete name 3, col: 1365 row: []
col: 1366 similar rows:  [1366]
11111111111111111111
incomplete name 3, col: 1366 row: []
col: 1370 similar rows:  [1370, 1822, 1978, 13627, 13643]
incomplete name 3, col: 1370 row: []
col: 1374 similar rows:  [1374]
11111111111111111111
incomplete name 3, col: 1374 row: []
col: 1375 similar rows:  [1375, 1516]
incomplete name 3, col: 1375 row: []
col: 1376 similar rows:  [1376]
11111111111111111111
incomplete name 3, col: 1376 row: []
col: 1378 similar rows:  [1378]
11111111111111111111
incomplete name 3, col: 1378 row: []
col: 1380 similar rows:  [1380]
11111111111111111111
incomplete name 3, col: 1380 row: []
col: 1381 similar rows:  [1381]
11111111111111111111
incomplete name 3, col: 1381 row: []
col: 1387 similar rows:  [1387]
11111111111111111111
incomplete name 3, col: 1387 row: []
col: 1388 similar rows:  [1388]
11111111111111111111
incomplete name 3, col: 1388 row: []
col: 1394 similar rows:  [1394, 1747, 1847, 13368]
incomplete name 3, col: 1394 row: []
col: 1395 similar rows:  [1395]
11111111111111111111
hotelname2 [1395]
incomplete name 3, col: 1395 row: [1395]
col: 1398 similar rows:  [1398]
11111111111111111111
incomplete name 3, col: 1398 row: []
col: 1402 similar rows:  [1402, 1915]
incomplete name 3, col: 1402 row: []
col: 1404 similar rows:  [1404, 1955]
incomplete name 3, col: 1404 row: []
col: 1406 similar rows:  [1406]
11111111111111111111
incomplete name 3, col: 1406 row: []
col: 1407 similar rows:  [1407]
11111111111111111111
incomplete name 3, col: 1407 row: []
col: 1408 similar rows:  [1408]
11111111111111111111
incomplete name 3, col: 1408 row: []
col: 1409 similar rows:  [1409, 1529, 1925]
incomplete name 3, col: 1409 row: []
col: 1410 similar rows:  [1410, 1494, 2539, 2543]
incomplete name 3, col: 1410 row: []
col: 1412 similar rows:  [1412]
11111111111111111111
incomplete name 3, col: 1412 row: []
col: 1415 similar rows:  [1415]
11111111111111111111
incomplete name 3, col: 1415 row: []
col: 1419 similar rows:  [1419]
11111111111111111111
incomplete name 3, col: 1419 row: []
col: 1423 similar rows:  [1423]
11111111111111111111
incomplete name 3, col: 1423 row: []
col: 1424 similar rows:  [1424, 2328]
incomplete name 3, col: 1424 row: []
col: 1426 similar rows:  [1426]
11111111111111111111
incomplete name 3, col: 1426 row: []
col: 1427 similar rows:  [1427, 1710, 1899, 13603]
incomplete name 3, col: 1427 row: []
col: 1431 similar rows:  [1431]
11111111111111111111
incomplete name 3, col: 1431 row: []
col: 1432 similar rows:  [1432]
11111111111111111111
hotelname2 [1432]
incomplete name 3, col: 1432 row: [1432]
col: 1436 similar rows:  [1436]
11111111111111111111
incomplete name 3, col: 1436 row: []
col: 1437 similar rows:  [1437, 1878]
incomplete name 3, col: 1437 row: []
col: 1439 similar rows:  [1439]
11111111111111111111
incomplete name 3, col: 1439 row: []
col: 1441 similar rows:  [1441, 1694, 13412, 13651]
incomplete name 3, col: 1441 row: []
col: 1442 similar rows:  [1442]
11111111111111111111
incomplete name 3, col: 1442 row: []
col: 1445 similar rows:  [1445]
11111111111111111111
incomplete name 3, col: 1445 row: []
col: 1448 similar rows:  [1448]
11111111111111111111
incomplete name 3, col: 1448 row: []
col: 1452 similar rows:  [1452, 1740]
incomplete name 3, col: 1452 row: []
col: 1455 similar rows:  [1455]
11111111111111111111
incomplete name 3, col: 1455 row: []

col: 1457 similar rows:  [1457]
11111111111111111111
incomplete name 3, col: 1457 row: []
col: 1458 similar rows:  [1458]
11111111111111111111
incomplete name 3, col: 1458 row: []
col: 1459 similar rows:  [1459]
11111111111111111111
hotelname2 [1459]
incomplete name 3, col: 1459 row: [1459]
col: 1460 similar rows:  [1460, 2465]
incomplete name 3, col: 1460 row: []
col: 1461 similar rows:  [1461]
11111111111111111111
incomplete name 3, col: 1461 row: []
col: 1463 similar rows:  [1463, 13432]
incomplete name 3, col: 1463 row: []
col: 1465 similar rows:  [1465, 1952]
incomplete name 3, col: 1465 row: []
col: 1466 similar rows:  [1466, 2468]
incomplete name 3, col: 1466 row: []
col: 1469 similar rows:  [1469]
11111111111111111111
incomplete name 3, col: 1469 row: []
col: 1470 similar rows:  [1470]
11111111111111111111
hotelname2 [1470]
incomplete name 3, col: 1470 row: [1470]
col: 1471 similar rows:  [1471]
11111111111111111111
incomplete name 3, col: 1471 row: []
col: 1481 similar rows:  [1481, 1483, 2222]
incomplete name 3, col: 1481 row: []
col: 1484 similar rows:  [1484]
11111111111111111111
incomplete name 3, col: 1484 row: []
col: 1485 similar rows:  [1485, 13690]
incomplete name 3, col: 1485 row: []
col: 1493 similar rows:  [1493]
11111111111111111111
incomplete name 3, col: 1493 row: []
col: 1495 similar rows:  [1495, 13679]
incomplete name 3, col: 1495 row: []
col: 1496 similar rows:  [1496]
11111111111111111111
incomplete name 3, col: 1496 row: []
col: 1497 similar rows:  [1497]
11111111111111111111
hotelname2 [1497]
incomplete name 3, col: 1497 row: [1497]
col: 1508 similar rows:  [1508]
11111111111111111111
incomplete name 3, col: 1508 row: []
col: 1517 similar rows:  [1517]
11111111111111111111
incomplete name 3, col: 1517 row: []
col: 1519 similar rows:  [1519]
11111111111111111111
incomplete name 3, col: 1519 row: []
col: 1521 similar rows:  [1521]
11111111111111111111
incomplete name 3, col: 1521 row: []
col: 1522 similar rows:  [1522, 1778]
incomplete name 3, col: 1522 row: []
col: 1523 similar rows:  [1523]
11111111111111111111
incomplete name 3, col: 1523 row: []
col: 1526 similar rows:  [1526, 2442]
incomplete name 3, col: 1526 row: []
col: 1530 similar rows:  [1530]
11111111111111111111
incomplete name 3, col: 1530 row: []
col: 1531 similar rows:  [1531, 2574]
incomplete name 3, col: 1531 row: []
col: 1535 similar rows:  [1535, 1951]
incomplete name 3, col: 1535 row: []
col: 1538 similar rows:  [1538]
11111111111111111111
incomplete name 3, col: 1538 row: []
col: 1541 similar rows:  [1541]
11111111111111111111
incomplete name 3, col: 1541 row: []
col: 1544 similar rows:  [1544]
11111111111111111111
incomplete name 3, col: 1544 row: []
col: 1548 similar rows:  [1548]
11111111111111111111
incomplete name 3, col: 1548 row: []
col: 1551 similar rows:  [1551]
11111111111111111111
incomplete name 3, col: 1551 row: []
col: 1554 similar rows:  [1554]
11111111111111111111
incomplete name 3, col: 1554 row: []
col: 1556 similar rows:  [1556, 13598]
incomplete name 3, col: 1556 row: []
col: 1557 similar rows:  [1557]
11111111111111111111
incomplete name 3, col: 1557 row: []
col: 1562 similar rows:  [1562]
11111111111111111111
incomplete name 3, col: 1562 row: []
col: 1568 similar rows:  [1568]
11111111111111111111
incomplete name 3, col: 1568 row: []
col: 1569 similar rows:  [1569]
11111111111111111111
incomplete name 3, col: 1569 row: []
col: 1570 similar rows:  [1570, 1600, 2437]
incomplete name 3, col: 1570 row: []
col: 1574 similar rows:  [1574]
11111111111111111111
incomplete name 3, col: 1574 row: []
col: 1575 similar rows:  [1575, 1853]
incomplete name 3, col: 1575 row: []
col: 1576 similar rows:  [1576]
11111111111111111111
hotelname2 [1576]
incomplete name 3, col: 1576 row: [1576]
col: 1577 similar rows:  [1577, 13670]
incomplete name 3, col: 1577 row: []
col: 1580 similar rows:  [1580, 1718]
incomplete name 3, col: 1580 row: []
col: 1581 similar rows:  [1581]
11111111111111111111
hotelname2 [1581]
incomplete name 3, col: 1581 row: [1581]
col: 1582 similar rows:  [1582]
11111111111111111111
hotelname2 [1582]
wrong name!!!!
incomplete name 3, col: 1582 row: [1582]
col: 1585 similar rows:  [1585]
11111111111111111111
incomplete name 3, col: 1585 row: []
col: 1586 similar rows:  [1586]
11111111111111111111
incomplete name 3, col: 1586 row: []
col: 1588 similar rows:  [1588]
11111111111111111111
incomplete name 3, col: 1588 row: []
col: 1593 similar rows:  [1593]
11111111111111111111
incomplete name 3, col: 1593 row: []
col: 1594 similar rows:  [1594]
11111111111111111111
incomplete name 3, col: 1594 row: []
col: 1596 similar rows:  [1596, 13454]
incomplete name 3, col: 1596 row: []
col: 1597 similar rows:  [1597, 2267]
incomplete name 3, col: 1597 row: []
col: 1598 similar rows:  [1598]
11111111111111111111
incomplete name 3, col: 1598 row: []
col: 1601 similar rows:  [1601, 2001, 2006, 2114]
incomplete name 3, col: 1601 row: []
col: 1602 similar rows:  [1602]
11111111111111111111
hotelname2 [1602]
incomplete name 3, col: 1602 row: []
col: 1604 similar rows:  [1604, 2201]
incomplete name 3, col: 1604 row: []
col: 1605 similar rows:  [1605, 1797]
incomplete name 3, col: 1605 row: []
col: 1606 similar rows:  [1606, 1712, 1856, 2030, 2400, 2452, 2618, 13414, 13584]
incomplete name 3, col: 1606 row: []
col: 1608 similar rows:  [1608]
11111111111111111111
hotelname2 [1608]
incomplete name 3, col: 1608 row: [1608]
col: 1610 similar rows:  [1610, 2482]
incomplete name 3, col: 1610 row: []
col: 1612 similar rows:  [1612]
11111111111111111111
incomplete name 3, col: 1612 row: []
col: 1615 similar rows:  [1615]
11111111111111111111
hotelname2 [1615]
incomplete name 3, col: 1615 row: []
col: 1616 similar rows:  [1616]
11111111111111111111
hotelname2 [1616]
incomplete name 3, col: 1616 row: [1616]
col: 1617 similar rows:  [1617]
11111111111111111111
incomplete name 3, col: 1617 row: []
col: 1618 similar rows:  [1618]
11111111111111111111
incomplete name 3, col: 1618 row: []
col: 1619 similar rows:  [1619]
11111111111111111111
incomplete name 3, col: 1619 row: []
col: 1620 similar rows:  [1620]
11111111111111111111
incomplete name 3, col: 1620 row: []
col: 1621 similar rows:  [1621]
11111111111111111111
incomplete name 3, col: 1621 row: []
col: 1623 similar rows:  [1623]
11111111111111111111
incomplete name 3, col: 1623 row: []
col: 1625 similar rows:  [1625, 13672]
incomplete name 3, col: 1625 row: []
col: 1626 similar rows:  [1626]
11111111111111111111
incomplete name 3, col: 1626 row: []
col: 1628 similar rows:  [1628]
11111111111111111111
incomplete name 3, col: 1628 row: []
col: 1629 similar rows:  [1629]
11111111111111111111
incomplete name 3, col: 1629 row: []
col: 1630 similar rows:  [1630]
11111111111111111111
incomplete name 3, col: 1630 row: []
col: 1634 similar rows:  [1634, 2340]
incomplete name 3, col: 1634 row: []
col: 1638 similar rows:  [1638]
11111111111111111111
hotelname2 [1638]
incomplete name 3, col: 1638 row: [1638]
col: 1640 similar rows:  [1640]
11111111111111111111
incomplete name 3, col: 1640 row: []
col: 1642 similar rows:  [1642]
11111111111111111111
hotelname2 [1642]
incomplete name 3, col: 1642 row: [1642]
col: 1646 similar rows:  [1646]
11111111111111111111
incomplete name 3, col: 1646 row: []
col: 1650 similar rows:  [1650, 2617]
incomplete name 3, col: 1650 row: []
col: 1656 similar rows:  [1656]
11111111111111111111
incomplete name 3, col: 1656 row: []
col: 1663 similar rows:  [1663]
11111111111111111111
hotelname2 [1663]
incomplete name 3, col: 1663 row: [1663]
col: 1666 similar rows:  [1666]
11111111111111111111
hotelname2 [1666]
incomplete name 3, col: 1666 row: [1666]
col: 1671 similar rows:  [1671, 1980]
incomplete name 3, col: 1671 row: []
col: 1672 similar rows:  [1672]
11111111111111111111
incomplete name 3, col: 1672 row: []
col: 1674 similar rows:  [1674]
11111111111111111111
hotelname2 [1674]
incomplete name 3, col: 1674 row: [1674]
col: 1679 similar rows:  [1679]
11111111111111111111
hotelname2 [1679]
incomplete name 3, col: 1679 row: []
col: 1684 similar rows:  [1684]
11111111111111111111
incomplete name 3, col: 1684 row: []
col: 1686 similar rows:  [1686, 1940, 13388, 13682]
incomplete name 3, col: 1686 row: []
col: 1688 similar rows:  [1688]
11111111111111111111
hotelname2 [1688]
incomplete name 3, col: 1688 row: [1688]
col: 1690 similar rows:  [1690]
11111111111111111111
incomplete name 3, col: 1690 row: []
col: 1691 similar rows:  [1691]
11111111111111111111
incomplete name 3, col: 1691 row: []
col: 1696 similar rows:  [1696]
11111111111111111111
hotelname2 [1696]
wrong name!!!!
incomplete name 3, col: 1696 row: [1696]

col: 1699 similar rows:  [1699]
11111111111111111111
incomplete name 3, col: 1699 row: []
col: 1701 similar rows:  [1701]
11111111111111111111
hotelname2 [1701]
incomplete name 3, col: 1701 row: [1701]
col: 1704 similar rows:  [1704]
11111111111111111111
hotelname2 [1704]
incomplete name 3, col: 1704 row: [1704]
col: 1705 similar rows:  [1705, 2130, 13612]
incomplete name 3, col: 1705 row: []
col: 1719 similar rows:  [1719, 13491]
incomplete name 3, col: 1719 row: []
col: 1721 similar rows:  [1721, 1724, 1735]
incomplete name 3, col: 1721 row: []
col: 1723 similar rows:  [1723, 1750, 2630, 13519]
incomplete name 3, col: 1723 row: []
col: 1725 similar rows:  [1725]
11111111111111111111
hotelname2 [1725]
incomplete name 3, col: 1725 row: [1725]
col: 1726 similar rows:  [1726]
11111111111111111111
incomplete name 3, col: 1726 row: []
col: 1727 similar rows:  [1727, 13465, 13528]
incomplete name 3, col: 1727 row: []
col: 1728 similar rows:  [1728]
11111111111111111111
incomplete name 3, col: 1728 row: []
col: 1730 similar rows:  [1730]
11111111111111111111
incomplete name 3, col: 1730 row: []
col: 1731 similar rows:  [1731, 2045, 2582, 2588, 2611]
incomplete name 3, col: 1731 row: []
col: 1734 similar rows:  [1734]
11111111111111111111
incomplete name 3, col: 1734 row: []
col: 1736 similar rows:  [1736]
11111111111111111111
incomplete name 3, col: 1736 row: []
col: 1737 similar rows:  [1737]
11111111111111111111
incomplete name 3, col: 1737 row: []
col: 1741 similar rows:  [1741]
11111111111111111111
incomplete name 3, col: 1741 row: []
col: 1743 similar rows:  [1743]
11111111111111111111
incomplete name 3, col: 1743 row: []
col: 1744 similar rows:  []
00000000000000000000
                                planner_id  \
1744  8d82ea4f-f981-4d28-a151-83666edcbc7d

                                wedding_id hotel hotel_id merged
1744  b2042f16-ae37-45fd-8aab-d3f07dbc5d70    、、     None     、、
hotelname2 [1744]
wrong name!!!!
incomplete name 3, col: 1744 row: [1744]
col: 1745 similar rows:  [1745, 2505]
incomplete name 3, col: 1745 row: []
col: 1746 similar rows:  [1746]
11111111111111111111
hotelname2 [1746]
incomplete name 3, col: 1746 row: [1746]
col: 1751 similar rows:  [1751]
11111111111111111111
incomplete name 3, col: 1751 row: []
col: 1752 similar rows:  [1752]
11111111111111111111
incomplete name 3, col: 1752 row: []
col: 1754 similar rows:  [1754]
11111111111111111111
incomplete name 3, col: 1754 row: []
col: 1756 similar rows:  [1756, 1842]
incomplete name 3, col: 1756 row: []
col: 1757 similar rows:  [1757]
11111111111111111111
incomplete name 3, col: 1757 row: []
col: 1763 similar rows:  [1763]
11111111111111111111
incomplete name 3, col: 1763 row: []
col: 1764 similar rows:  [1764]
11111111111111111111
hotelname2 [1764]
incomplete name 3, col: 1764 row: [1764]
col: 1768 similar rows:  [1768, 2179]
incomplete name 3, col: 1768 row: []
col: 1772 similar rows:  [1772]
11111111111111111111
incomplete name 3, col: 1772 row: []
col: 1773 similar rows:  [1773]
11111111111111111111
incomplete name 3, col: 1773 row: []
col: 1775 similar rows:  [1775]
11111111111111111111
hotelname2 [1775]
incomplete name 3, col: 1775 row: [1775]
col: 1777 similar rows:  [1777, 2064]
incomplete name 3, col: 1777 row: []
col: 1779 similar rows:  [1779]
11111111111111111111
incomplete name 3, col: 1779 row: []
col: 1790 similar rows:  [1790]
11111111111111111111
incomplete name 3, col: 1790 row: []
col: 1791 similar rows:  [1791]
11111111111111111111
incomplete name 3, col: 1791 row: []
col: 1795 similar rows:  [1795]
11111111111111111111
hotelname2 [1795]
wrong name!!!!
incomplete name 3, col: 1795 row: [1795]
col: 1796 similar rows:  [1796]
11111111111111111111
incomplete name 3, col: 1796 row: []
col: 1799 similar rows:  [1799, 1800]
incomplete name 3, col: 1799 row: []
col: 1801 similar rows:  [1801]
11111111111111111111
incomplete name 3, col: 1801 row: []
col: 1802 similar rows:  [1802]
11111111111111111111
incomplete name 3, col: 1802 row: []
col: 1803 similar rows:  [1803]
11111111111111111111
incomplete name 3, col: 1803 row: []
col: 1806 similar rows:  [1806]
11111111111111111111
incomplete name 3, col: 1806 row: []
col: 1807 similar rows:  [1807]
11111111111111111111
incomplete name 3, col: 1807 row: []
col: 1808 similar rows:  [1808]
11111111111111111111
incomplete name 3, col: 1808 row: []
col: 1809 similar rows:  [1809, 13406]
incomplete name 3, col: 1809 row: []
col: 1810 similar rows:  [1810]
11111111111111111111
incomplete name 3, col: 1810 row: []
col: 1812 similar rows:  [1812, 1977, 2136, 2415, 2444, 2445, 2519]
hotelname2 [2444, 2445]
hotelname2 [2444, 2445]
incomplete name 3, col: 1812 row: []
col: 1814 similar rows:  [1814]
11111111111111111111
incomplete name 3, col: 1814 row: []
col: 1817 similar rows:  [1817, 2032, 2259, 13628]
incomplete name 3, col: 1817 row: []
col: 1818 similar rows:  [1818]
11111111111111111111
incomplete name 3, col: 1818 row: []
col: 1821 similar rows:  [1821]
11111111111111111111
incomplete name 3, col: 1821 row: []
col: 1825 similar rows:  [1825, 2115]
incomplete name 3, col: 1825 row: []
col: 1828 similar rows:  [1828]
11111111111111111111
hotelname2 [1828]
incomplete name 3, col: 1828 row: []
col: 1832 similar rows:  [1832]
11111111111111111111
incomplete name 3, col: 1832 row: []
col: 1841 similar rows:  [1841]
11111111111111111111
incomplete name 3, col: 1841 row: []
col: 1844 similar rows:  [1844, 2214]
incomplete name 3, col: 1844 row: []
col: 1848 similar rows:  [1848]
11111111111111111111
hotelname2 [1848]
incomplete name 3, col: 1848 row: []
col: 1850 similar rows:  [1850]
11111111111111111111
incomplete name 3, col: 1850 row: []
col: 1852 similar rows:  [1852]
11111111111111111111
incomplete name 3, col: 1852 row: []
col: 1855 similar rows:  [1855]
11111111111111111111
incomplete name 3, col: 1855 row: []
col: 1857 similar rows:  [1857]
11111111111111111111
incomplete name 3, col: 1857 row: []
col: 1858 similar rows:  [1858]
11111111111111111111
incomplete name 3, col: 1858 row: []
col: 1859 similar rows:  [1859]
11111111111111111111
incomplete name 3, col: 1859 row: []
col: 1860 similar rows:  [1860]
11111111111111111111
incomplete name 3, col: 1860 row: []
col: 1862 similar rows:  [1862]
11111111111111111111
incomplete name 3, col: 1862 row: []
col: 1863 similar rows:  [1863]
11111111111111111111
incomplete name 3, col: 1863 row: []
col: 1864 similar rows:  [1864]
11111111111111111111
incomplete name 3, col: 1864 row: []
col: 1867 similar rows:  [1867]
11111111111111111111
incomplete name 3, col: 1867 row: []
col: 1870 similar rows:  [1870]
11111111111111111111
incomplete name 3, col: 1870 row: []
col: 1874 similar rows:  [1874]
11111111111111111111
incomplete name 3, col: 1874 row: []
col: 1875 similar rows:  [1875]
11111111111111111111
incomplete name 3, col: 1875 row: []
col: 1877 similar rows:  [1877]
11111111111111111111
incomplete name 3, col: 1877 row: []
col: 1879 similar rows:  [1879]
11111111111111111111
incomplete name 3, col: 1879 row: []
col: 1880 similar rows:  [1880]
11111111111111111111
incomplete name 3, col: 1880 row: []
col: 1881 similar rows:  [1881]
11111111111111111111
incomplete name 3, col: 1881 row: []
col: 1883 similar rows:  [1883, 2253]
incomplete name 3, col: 1883 row: []
col: 1885 similar rows:  [1885]
11111111111111111111
incomplete name 3, col: 1885 row: []
col: 1886 similar rows:  [1886]
11111111111111111111
incomplete name 3, col: 1886 row: []
col: 1890 similar rows:  [1890, 13458, 13600]
incomplete name 3, col: 1890 row: []
col: 1892 similar rows:  [1892]
11111111111111111111
hotelname2 [1892]
incomplete name 3, col: 1892 row: [1892]
col: 1893 similar rows:  [1893]
11111111111111111111
hotelname2 [1893]
incomplete name 3, col: 1893 row: [1893]
col: 1894 similar rows:  [1894]
11111111111111111111
hotelname2 [1894]
wrong name!!!!
incomplete name 3, col: 1894 row: [1894]
col: 1895 similar rows:  [1895]
11111111111111111111
incomplete name 3, col: 1895 row: []
col: 1897 similar rows:  [1897]
11111111111111111111
incomplete name 3, col: 1897 row: []
col: 1900 similar rows:  [1900]
11111111111111111111
hotelname2 [1900]
incomplete name 3, col: 1900 row: []
col: 1901 similar rows:  [1901]
11111111111111111111
incomplete name 3, col: 1901 row: []
col: 1902 similar rows:  [1902, 13386]
incomplete name 3, col: 1902 row: []

col: 1905 similar rows:  [1905, 13400]
incomplete name 3, col: 1905 row: []
col: 1908 similar rows:  [1908]
11111111111111111111
incomplete name 3, col: 1908 row: []
col: 1911 similar rows:  [1911, 13545]
incomplete name 3, col: 1911 row: []
col: 1914 similar rows:  [1914]
11111111111111111111
incomplete name 3, col: 1914 row: []
col: 1921 similar rows:  [1921]
11111111111111111111
incomplete name 3, col: 1921 row: []
col: 1923 similar rows:  [1923]
11111111111111111111
incomplete name 3, col: 1923 row: []
col: 1930 similar rows:  [1930]
11111111111111111111
incomplete name 3, col: 1930 row: []
col: 1938 similar rows:  [1938, 2009]
incomplete name 3, col: 1938 row: []
col: 1941 similar rows:  [1941]
11111111111111111111
incomplete name 3, col: 1941 row: []
col: 1944 similar rows:  [1944]
11111111111111111111
incomplete name 3, col: 1944 row: []
col: 1946 similar rows:  [1946]
11111111111111111111
incomplete name 3, col: 1946 row: []
col: 1947 similar rows:  [1947]
11111111111111111111
incomplete name 3, col: 1947 row: []
col: 1948 similar rows:  [1948, 2117, 13457]
incomplete name 3, col: 1948 row: []
col: 1949 similar rows:  [1949]
11111111111111111111
incomplete name 3, col: 1949 row: []
col: 1953 similar rows:  [1953]
11111111111111111111
incomplete name 3, col: 1953 row: []
col: 1957 similar rows:  [1957]
11111111111111111111
incomplete name 3, col: 1957 row: []
col: 1959 similar rows:  [1959, 2559]
incomplete name 3, col: 1959 row: []
col: 1960 similar rows:  [1960]
11111111111111111111
incomplete name 3, col: 1960 row: []
col: 1966 similar rows:  [1966]
11111111111111111111
incomplete name 3, col: 1966 row: []
col: 1967 similar rows:  [1967]
11111111111111111111
incomplete name 3, col: 1967 row: []
col: 1972 similar rows:  [1972]
11111111111111111111
incomplete name 3, col: 1972 row: []
col: 1975 similar rows:  [1975]
11111111111111111111
incomplete name 3, col: 1975 row: []
col: 1979 similar rows:  [1979]
11111111111111111111
incomplete name 3, col: 1979 row: []
col: 1984 similar rows:  [1984, 2082, 2084]
incomplete name 3, col: 1984 row: []
col: 1989 similar rows:  [1989]
11111111111111111111
incomplete name 3, col: 1989 row: []
col: 1992 similar rows:  [1992, 2419, 2508]
incomplete name 3, col: 1992 row: []
col: 1996 similar rows:  [1996, 2539, 2543]
incomplete name 3, col: 1996 row: []
col: 1997 similar rows:  [1997]
11111111111111111111
incomplete name 3, col: 1997 row: []
col: 1999 similar rows:  [1999]
11111111111111111111
incomplete name 3, col: 1999 row: []
col: 2005 similar rows:  [2005]
11111111111111111111
incomplete name 3, col: 2005 row: []
col: 2007 similar rows:  [2007]
11111111111111111111
incomplete name 3, col: 2007 row: []
col: 2013 similar rows:  [2013]
11111111111111111111
incomplete name 3, col: 2013 row: []
col: 2016 similar rows:  [2016]
11111111111111111111
incomplete name 3, col: 2016 row: []
col: 2017 similar rows:  [2017]
11111111111111111111
incomplete name 3, col: 2017 row: []
col: 2018 similar rows:  [2018]
11111111111111111111
incomplete name 3, col: 2018 row: []
col: 2020 similar rows:  [2020]
11111111111111111111
incomplete name 3, col: 2020 row: []
col: 2021 similar rows:  [2021]
11111111111111111111
hotelname2 [2021]
incomplete name 3, col: 2021 row: [2021]
col: 2026 similar rows:  [2026]
11111111111111111111
incomplete name 3, col: 2026 row: []
col: 2037 similar rows:  [2037]
11111111111111111111
incomplete name 3, col: 2037 row: []
col: 2039 similar rows:  [2039]
11111111111111111111
incomplete name 3, col: 2039 row: []
col: 2040 similar rows:  [2040]
11111111111111111111
incomplete name 3, col: 2040 row: []
col: 2041 similar rows:  [2041]
11111111111111111111
incomplete name 3, col: 2041 row: []
col: 2044 similar rows:  [2044]
11111111111111111111
hotelname2 [2044]
incomplete name 3, col: 2044 row: [2044]
col: 2047 similar rows:  [2047]
11111111111111111111
incomplete name 3, col: 2047 row: []
col: 2051 similar rows:  [2051]
11111111111111111111
incomplete name 3, col: 2051 row: []
col: 2057 similar rows:  [2057]
11111111111111111111
incomplete name 3, col: 2057 row: []
col: 2059 similar rows:  [2059]
11111111111111111111
incomplete name 3, col: 2059 row: []
col: 2061 similar rows:  [2061]
11111111111111111111
incomplete name 3, col: 2061 row: []
col: 2062 similar rows:  [2062]
11111111111111111111
incomplete name 3, col: 2062 row: []
col: 2063 similar rows:  [2063]
11111111111111111111
incomplete name 3, col: 2063 row: []
col: 2065 similar rows:  [2065]
11111111111111111111
incomplete name 3, col: 2065 row: []
col: 2075 similar rows:  [2075]
11111111111111111111
incomplete name 3, col: 2075 row: []
col: 2086 similar rows:  [2086]
11111111111111111111
incomplete name 3, col: 2086 row: []
col: 2088 similar rows:  [2088]
11111111111111111111
hotelname2 [2088]
incomplete name 3, col: 2088 row: [2088]
col: 2098 similar rows:  [2098]
11111111111111111111
incomplete name 3, col: 2098 row: []
col: 2103 similar rows:  [2103, 13363, 13425]
incomplete name 3, col: 2103 row: []
col: 2104 similar rows:  [2104, 2280]
incomplete name 3, col: 2104 row: []
col: 2112 similar rows:  [2112]
11111111111111111111
incomplete name 3, col: 2112 row: []
col: 2116 similar rows:  [2116]
11111111111111111111
hotelname2 [2116]
incomplete name 3, col: 2116 row: [2116]
col: 2118 similar rows:  [2118]
11111111111111111111
incomplete name 3, col: 2118 row: []
col: 2140 similar rows:  [2140, 13398]
incomplete name 3, col: 2140 row: []
col: 2141 similar rows:  [2141]
11111111111111111111
incomplete name 3, col: 2141 row: []
col: 2142 similar rows:  [2142, 2176, 2372]
incomplete name 3, col: 2142 row: []
col: 2144 similar rows:  [2144]
11111111111111111111
incomplete name 3, col: 2144 row: []
col: 2145 similar rows:  [2145]
11111111111111111111
incomplete name 3, col: 2145 row: []
col: 2146 similar rows:  [2146]
11111111111111111111
incomplete name 3, col: 2146 row: []
col: 2147 similar rows:  [2147]
11111111111111111111
incomplete name 3, col: 2147 row: []
col: 2150 similar rows:  [2150]
11111111111111111111
incomplete name 3, col: 2150 row: []
col: 2152 similar rows:  [2152]
11111111111111111111
incomplete name 3, col: 2152 row: []
col: 2153 similar rows:  [2153, 13379, 13658]
incomplete name 3, col: 2153 row: []
col: 2154 similar rows:  [2154]
11111111111111111111
incomplete name 3, col: 2154 row: []
col: 2158 similar rows:  [2158]
11111111111111111111
incomplete name 3, col: 2158 row: []
col: 2167 similar rows:  [2167]
11111111111111111111
incomplete name 3, col: 2167 row: []
col: 2169 similar rows:  [2169]
11111111111111111111
incomplete name 3, col: 2169 row: []
col: 2171 similar rows:  [2171]
11111111111111111111
incomplete name 3, col: 2171 row: []
col: 2183 similar rows:  [2183]
11111111111111111111
incomplete name 3, col: 2183 row: []
col: 2184 similar rows:  [2184]
11111111111111111111
incomplete name 3, col: 2184 row: []
col: 2188 similar rows:  [2188]
11111111111111111111
incomplete name 3, col: 2188 row: []
col: 2191 similar rows:  [2191]
11111111111111111111
hotelname2 [2191]
incomplete name 3, col: 2191 row: [2191]
col: 2197 similar rows:  [2197, 13522]
incomplete name 3, col: 2197 row: []
col: 2198 similar rows:  [2198]
11111111111111111111
incomplete name 3, col: 2198 row: []
col: 2199 similar rows:  [2199]
11111111111111111111
incomplete name 3, col: 2199 row: []
col: 2206 similar rows:  [2206]
11111111111111111111
hotelname2 [2206]
incomplete name 3, col: 2206 row: [2206]
col: 2211 similar rows:  [2211]
11111111111111111111
hotelname2 [2211]
incomplete name 3, col: 2211 row: [2211]
col: 2212 similar rows:  [2212]
11111111111111111111
incomplete name 3, col: 2212 row: []
col: 2213 similar rows:  [2213]
11111111111111111111
incomplete name 3, col: 2213 row: []
col: 2219 similar rows:  [2219]
11111111111111111111
hotelname2 [2219]
incomplete name 3, col: 2219 row: [2219]
col: 2220 similar rows:  [2220]
11111111111111111111
incomplete name 3, col: 2220 row: []
col: 2231 similar rows:  [2231, 2232]
incomplete name 3, col: 2231 row: []
col: 2233 similar rows:  [2233]
11111111111111111111
incomplete name 3, col: 2233 row: []
col: 2238 similar rows:  [2238]
11111111111111111111
incomplete name 3, col: 2238 row: []
col: 2242 similar rows:  [2242]
11111111111111111111
incomplete name 3, col: 2242 row: []
col: 2244 similar rows:  [2244]
11111111111111111111
incomplete name 3, col: 2244 row: []
col: 2246 similar rows:  [2246]
11111111111111111111
incomplete name 3, col: 2246 row: []
col: 2249 similar rows:  [2249]
11111111111111111111
incomplete name 3, col: 2249 row: []

col: 2252 similar rows:  [2252]
11111111111111111111
incomplete name 3, col: 2252 row: []
col: 2254 similar rows:  [2254]
11111111111111111111
incomplete name 3, col: 2254 row: []
col: 2261 similar rows:  [2261]
11111111111111111111
hotelname2 [2261]
incomplete name 3, col: 2261 row: [2261]
col: 2263 similar rows:  [2263]
11111111111111111111
incomplete name 3, col: 2263 row: []
col: 2265 similar rows:  [2265]
11111111111111111111
incomplete name 3, col: 2265 row: []
col: 2272 similar rows:  [2272]
11111111111111111111
hotelname2 [2272]
incomplete name 3, col: 2272 row: [2272]
col: 2275 similar rows:  [2275]
11111111111111111111
incomplete name 3, col: 2275 row: []
col: 2277 similar rows:  [2277]
11111111111111111111
incomplete name 3, col: 2277 row: []
col: 2278 similar rows:  [2278]
11111111111111111111
incomplete name 3, col: 2278 row: []
col: 2281 similar rows:  [2281]
11111111111111111111
hotelname2 [2281]
incomplete name 3, col: 2281 row: [2281]
col: 2284 similar rows:  [2284]
11111111111111111111
incomplete name 3, col: 2284 row: []
col: 2289 similar rows:  [2289]
11111111111111111111
incomplete name 3, col: 2289 row: []
col: 2293 similar rows:  [2293]
11111111111111111111
incomplete name 3, col: 2293 row: []
col: 2302 similar rows:  [2302, 2311, 2351, 2528]
incomplete name 3, col: 2302 row: []
col: 2312 similar rows:  [2312]
11111111111111111111
incomplete name 3, col: 2312 row: []
col: 2315 similar rows:  [2315]
11111111111111111111
incomplete name 3, col: 2315 row: []
col: 2327 similar rows:  [2327]
11111111111111111111
incomplete name 3, col: 2327 row: []
col: 2333 similar rows:  [2333]
11111111111111111111
incomplete name 3, col: 2333 row: []
col: 2348 similar rows:  [2348, 2406]
incomplete name 3, col: 2348 row: []
col: 2355 similar rows:  [2355]
11111111111111111111
incomplete name 3, col: 2355 row: []
col: 2359 similar rows:  [2359]
11111111111111111111
incomplete name 3, col: 2359 row: []
col: 2360 similar rows:  [2360]
11111111111111111111
incomplete name 3, col: 2360 row: []
col: 2361 similar rows:  [2361]
11111111111111111111
incomplete name 3, col: 2361 row: []
col: 2362 similar rows:  [2362]
11111111111111111111
incomplete name 3, col: 2362 row: []
col: 2364 similar rows:  [2364]
11111111111111111111
incomplete name 3, col: 2364 row: []
col: 2365 similar rows:  [2365]
11111111111111111111
hotelname2 [2365]
incomplete name 3, col: 2365 row: [2365]
col: 2378 similar rows:  [2378]
11111111111111111111
hotelname2 [2378]
incomplete name 3, col: 2378 row: [2378]
col: 2380 similar rows:  [2380]
11111111111111111111
hotelname2 [2380]
incomplete name 3, col: 2380 row: [2380]
col: 2386 similar rows:  [2386]
11111111111111111111
hotelname2 [2386]
incomplete name 3, col: 2386 row: [2386]
col: 2388 similar rows:  [2388]
11111111111111111111
incomplete name 3, col: 2388 row: []
col: 2391 similar rows:  [2391]
11111111111111111111
incomplete name 3, col: 2391 row: []
col: 2392 similar rows:  [2392, 13518, 13572]
incomplete name 3, col: 2392 row: []
col: 2394 similar rows:  [2394]
11111111111111111111
incomplete name 3, col: 2394 row: []
col: 2395 similar rows:  [2395]
11111111111111111111
incomplete name 3, col: 2395 row: []
col: 2402 similar rows:  [2402, 2426, 2621, 13641]
incomplete name 3, col: 2402 row: []
col: 2403 similar rows:  [2403, 13614]
incomplete name 3, col: 2403 row: []
col: 2408 similar rows:  [2408]
11111111111111111111
incomplete name 3, col: 2408 row: []
col: 2412 similar rows:  [2412]
11111111111111111111
incomplete name 3, col: 2412 row: []
col: 2417 similar rows:  [2417]
11111111111111111111
incomplete name 3, col: 2417 row: []
col: 2423 similar rows:  [2423]
11111111111111111111
incomplete name 3, col: 2423 row: []
col: 2424 similar rows:  [2424]
11111111111111111111
hotelname2 [2424]
incomplete name 3, col: 2424 row: [2424]
col: 2427 similar rows:  [2427]
11111111111111111111
incomplete name 3, col: 2427 row: []
col: 2430 similar rows:  [2430, 13635]
incomplete name 3, col: 2430 row: []
col: 2432 similar rows:  [2432]
11111111111111111111
incomplete name 3, col: 2432 row: []
col: 2435 similar rows:  [2435]
11111111111111111111
incomplete name 3, col: 2435 row: []
col: 2436 similar rows:  [2436]
11111111111111111111
incomplete name 3, col: 2436 row: []
col: 2438 similar rows:  [2438]
11111111111111111111
incomplete name 3, col: 2438 row: []
col: 2439 similar rows:  [2439]
11111111111111111111
incomplete name 3, col: 2439 row: []
col: 2443 similar rows:  [2443]
11111111111111111111
incomplete name 3, col: 2443 row: []
col: 2448 similar rows:  [2448]
11111111111111111111
incomplete name 3, col: 2448 row: []
col: 2450 similar rows:  [2450]
11111111111111111111
incomplete name 3, col: 2450 row: []
col: 2451 similar rows:  [2451]
11111111111111111111
incomplete name 3, col: 2451 row: []
col: 2456 similar rows:  [2456]
11111111111111111111
incomplete name 3, col: 2456 row: []
col: 2457 similar rows:  [2457]
11111111111111111111
incomplete name 3, col: 2457 row: []
col: 2458 similar rows:  [2458, 13648]
incomplete name 3, col: 2458 row: []
col: 2459 similar rows:  [2459]
11111111111111111111
incomplete name 3, col: 2459 row: []
col: 2460 similar rows:  [2460, 2475]
incomplete name 3, col: 2460 row: []
col: 2464 similar rows:  [2464]
11111111111111111111
incomplete name 3, col: 2464 row: []
col: 2467 similar rows:  [2467]
11111111111111111111
incomplete name 3, col: 2467 row: []
col: 2472 similar rows:  [2472, 13367]
incomplete name 3, col: 2472 row: []
col: 2476 similar rows:  [2476]
11111111111111111111
incomplete name 3, col: 2476 row: []
col: 2477 similar rows:  [2477]
11111111111111111111
hotelname2 [2477]
incomplete name 3, col: 2477 row: [2477]
col: 2487 similar rows:  [2487]
11111111111111111111
incomplete name 3, col: 2487 row: []
col: 2488 similar rows:  [2488]
11111111111111111111
incomplete name 3, col: 2488 row: []
col: 2493 similar rows:  [2493]
11111111111111111111
incomplete name 3, col: 2493 row: []
col: 2496 similar rows:  [2496, 13661]
incomplete name 3, col: 2496 row: []
col: 2498 similar rows:  [2498]
11111111111111111111
incomplete name 3, col: 2498 row: []
col: 2501 similar rows:  [2501]
11111111111111111111
incomplete name 3, col: 2501 row: []
col: 2502 similar rows:  [2502]
11111111111111111111
incomplete name 3, col: 2502 row: []
col: 2503 similar rows:  [2503]
11111111111111111111
incomplete name 3, col: 2503 row: []
col: 2506 similar rows:  [2506]
11111111111111111111
incomplete name 3, col: 2506 row: []
col: 2507 similar rows:  [2507]
11111111111111111111
incomplete name 3, col: 2507 row: []
col: 2509 similar rows:  [2509]
11111111111111111111
incomplete name 3, col: 2509 row: []
col: 2510 similar rows:  [2510]
11111111111111111111
incomplete name 3, col: 2510 row: []
col: 2520 similar rows:  [2520]
11111111111111111111
incomplete name 3, col: 2520 row: []
col: 2522 similar rows:  [2522]
11111111111111111111
incomplete name 3, col: 2522 row: []
col: 2525 similar rows:  [2525, 2526]
incomplete name 3, col: 2525 row: []
col: 2530 similar rows:  [2530]
11111111111111111111
incomplete name 3, col: 2530 row: []
col: 2531 similar rows:  [2531]
11111111111111111111
incomplete name 3, col: 2531 row: []
col: 2547 similar rows:  [2547]
11111111111111111111
incomplete name 3, col: 2547 row: []
col: 2551 similar rows:  [2551]
11111111111111111111
incomplete name 3, col: 2551 row: []
col: 2552 similar rows:  [2552]
11111111111111111111
incomplete name 3, col: 2552 row: []
col: 2562 similar rows:  [2562]
11111111111111111111
incomplete name 3, col: 2562 row: []
col: 2570 similar rows:  [2570]
11111111111111111111
incomplete name 3, col: 2570 row: []
col: 2572 similar rows:  [2572]
11111111111111111111
incomplete name 3, col: 2572 row: []
col: 2577 similar rows:  [2577, 13558]
incomplete name 3, col: 2577 row: []
col: 2579 similar rows:  [2579]
11111111111111111111
incomplete name 3, col: 2579 row: []
col: 2581 similar rows:  [2581]
11111111111111111111
incomplete name 3, col: 2581 row: []
col: 2583 similar rows:  [2583]
11111111111111111111
incomplete name 3, col: 2583 row: []
col: 2585 similar rows:  [2585]
11111111111111111111
incomplete name 3, col: 2585 row: []
col: 2586 similar rows:  [2586]
11111111111111111111
incomplete name 3, col: 2586 row: []
col: 2589 similar rows:  [2589]
11111111111111111111
incomplete name 3, col: 2589 row: []
col: 2592 similar rows:  [2592]
11111111111111111111
incomplete name 3, col: 2592 row: []
col: 2595 similar rows:  [2595]
11111111111111111111
hotelname2 [2595]
incomplete name 3, col: 2595 row: [2595]
col: 2597 similar rows:  [2597, 13460]
incomplete name 3, col: 2597 row: []
col: 2605 similar rows:  [2605]
11111111111111111111
incomplete name 3, col: 2605 row: []

col: 2606 similar rows:  [2606]
11111111111111111111
incomplete name 3, col: 2606 row: []
col: 2614 similar rows:  [2614, 13410, 13453]
incomplete name 3, col: 2614 row: []
col: 2616 similar rows:  [2616]
11111111111111111111
hotelname2 [2616]
incomplete name 3, col: 2616 row: []
col: 2622 similar rows:  [2622]
11111111111111111111
incomplete name 3, col: 2622 row: []
col: 2623 similar rows:  [2623]
11111111111111111111
incomplete name 3, col: 2623 row: []
col: 2624 similar rows:  [2624]
11111111111111111111
incomplete name 3, col: 2624 row: []
col: 2625 similar rows:  [2625]
11111111111111111111
incomplete name 3, col: 2625 row: []
col: 2626 similar rows:  [2626]
11111111111111111111
incomplete name 3, col: 2626 row: []
col: 2628 similar rows:  [2628]
11111111111111111111
incomplete name 3, col: 2628 row: []
col: 2629 similar rows:  [2629, 13646]
incomplete name 3, col: 2629 row: []
col: 2634 similar rows:  [2634]
11111111111111111111
incomplete name 3, col: 2634 row: []
col: 2638 similar rows:  [2638]
11111111111111111111
hotelname2 [2638]
incomplete name 3, col: 2638 row: []
col: 2639 similar rows:  [2639]
11111111111111111111
incomplete name 3, col: 2639 row: []
col: 2643 similar rows:  [2643]
11111111111111111111
incomplete name 3, col: 2643 row: []
col: 2645 similar rows:  [2645, 13646]
incomplete name 3, col: 2645 row: []
col: 13349 similar rows:  [13349]
11111111111111111111
incomplete name 3, col: 13349 row: []
col: 13350 similar rows:  [13350]
11111111111111111111
incomplete name 3, col: 13350 row: []
col: 13351 similar rows:  [13351]
11111111111111111111
incomplete name 3, col: 13351 row: []
col: 13353 similar rows:  [13353]
11111111111111111111
incomplete name 3, col: 13353 row: []
col: 13359 similar rows:  [13359]
11111111111111111111
incomplete name 3, col: 13359 row: []
col: 13360 similar rows:  [13360]
11111111111111111111
hotelname2 [13360]
incomplete name 3, col: 13360 row: [13360]
col: 13361 similar rows:  [13361]
11111111111111111111
hotelname2 [13361]
incomplete name 3, col: 13361 row: []
col: 13371 similar rows:  [13371]
11111111111111111111
hotelname2 [13371]
incomplete name 3, col: 13371 row: [13371]
col: 13372 similar rows:  [13372]
11111111111111111111
hotelname2 [13372]
incomplete name 3, col: 13372 row: [13372]
col: 13374 similar rows:  [13374]
11111111111111111111
incomplete name 3, col: 13374 row: []
col: 13376 similar rows:  [13376]
11111111111111111111
hotelname2 [13376]
incomplete name 3, col: 13376 row: [13376]
col: 13377 similar rows:  [13377]
11111111111111111111
incomplete name 3, col: 13377 row: []
col: 13380 similar rows:  [13380]
11111111111111111111
incomplete name 3, col: 13380 row: []
col: 13381 similar rows:  [13381]
11111111111111111111
incomplete name 3, col: 13381 row: []
col: 13382 similar rows:  [13382]
11111111111111111111
incomplete name 3, col: 13382 row: []
col: 13384 similar rows:  [13384]
11111111111111111111
incomplete name 3, col: 13384 row: []
col: 13389 similar rows:  [13389]
11111111111111111111
incomplete name 3, col: 13389 row: []
col: 13392 similar rows:  [13392]
11111111111111111111
incomplete name 3, col: 13392 row: []
col: 13393 similar rows:  [13393]
11111111111111111111
incomplete name 3, col: 13393 row: []
col: 13394 similar rows:  [13394, 13608]
incomplete name 3, col: 13394 row: []
col: 13401 similar rows:  [13401]
11111111111111111111
incomplete name 3, col: 13401 row: []
col: 13402 similar rows:  [13402]
11111111111111111111
incomplete name 3, col: 13402 row: []
col: 13403 similar rows:  [13403]
11111111111111111111
incomplete name 3, col: 13403 row: []
col: 13405 similar rows:  [13405]
11111111111111111111
incomplete name 3, col: 13405 row: []
col: 13411 similar rows:  [13411]
11111111111111111111
incomplete name 3, col: 13411 row: []
col: 13416 similar rows:  [13416]
11111111111111111111
incomplete name 3, col: 13416 row: []
col: 13420 similar rows:  [13420]
11111111111111111111
hotelname2 [13420]
incomplete name 3, col: 13420 row: [13420]
col: 13421 similar rows:  [13421]
11111111111111111111
incomplete name 3, col: 13421 row: []
col: 13422 similar rows:  [13422]
11111111111111111111
incomplete name 3, col: 13422 row: []
col: 13424 similar rows:  [13424]
11111111111111111111
incomplete name 3, col: 13424 row: []
col: 13428 similar rows:  [13428]
11111111111111111111
incomplete name 3, col: 13428 row: []
col: 13434 similar rows:  [13434]
11111111111111111111
incomplete name 3, col: 13434 row: []
col: 13435 similar rows:  [13435]
11111111111111111111
incomplete name 3, col: 13435 row: []
col: 13437 similar rows:  [13437]
11111111111111111111
incomplete name 3, col: 13437 row: []
col: 13438 similar rows:  [13438]
11111111111111111111
incomplete name 3, col: 13438 row: []
col: 13440 similar rows:  [13440]
11111111111111111111
incomplete name 3, col: 13440 row: []
col: 13442 similar rows:  [13442]
11111111111111111111
incomplete name 3, col: 13442 row: []
col: 13443 similar rows:  [13443]
11111111111111111111
incomplete name 3, col: 13443 row: []
col: 13444 similar rows:  [13444]
11111111111111111111
incomplete name 3, col: 13444 row: []
col: 13445 similar rows:  [13445]
11111111111111111111
incomplete name 3, col: 13445 row: []
col: 13446 similar rows:  [13446]
11111111111111111111
incomplete name 3, col: 13446 row: []
col: 13447 similar rows:  [13447]
11111111111111111111
incomplete name 3, col: 13447 row: []
col: 13449 similar rows:  [13449]
11111111111111111111
incomplete name 3, col: 13449 row: []
col: 13450 similar rows:  [13450]
11111111111111111111
incomplete name 3, col: 13450 row: []
col: 13451 similar rows:  [13451]
11111111111111111111
incomplete name 3, col: 13451 row: []
col: 13455 similar rows:  [13455]
11111111111111111111
incomplete name 3, col: 13455 row: []
col: 13456 similar rows:  [13456]
11111111111111111111
incomplete name 3, col: 13456 row: []
col: 13461 similar rows:  [13461]
11111111111111111111
incomplete name 3, col: 13461 row: []
col: 13463 similar rows:  [13463]
11111111111111111111
incomplete name 3, col: 13463 row: []
col: 13464 similar rows:  [13464]
11111111111111111111
hotelname2 [13464]
incomplete name 3, col: 13464 row: [13464]
col: 13467 similar rows:  [13467]
11111111111111111111
incomplete name 3, col: 13467 row: []
col: 13478 similar rows:  [13478]
11111111111111111111
incomplete name 3, col: 13478 row: []
col: 13480 similar rows:  [13480, 13670]
incomplete name 3, col: 13480 row: []
col: 13482 similar rows:  [13482]
11111111111111111111
incomplete name 3, col: 13482 row: []
col: 13484 similar rows:  [13484]
11111111111111111111
hotelname2 [13484]
incomplete name 3, col: 13484 row: [13484]
col: 13488 similar rows:  [13488]
11111111111111111111
hotelname2 [13488]
incomplete name 3, col: 13488 row: [13488]
col: 13490 similar rows:  [13490]
11111111111111111111
hotelname2 [13490]
incomplete name 3, col: 13490 row: [13490]
col: 13493 similar rows:  [13493]
11111111111111111111
incomplete name 3, col: 13493 row: []
col: 13494 similar rows:  [13494]
11111111111111111111
hotelname2 [13494]
incomplete name 3, col: 13494 row: [13494]
col: 13497 similar rows:  [13497]
11111111111111111111
incomplete name 3, col: 13497 row: []
col: 13499 similar rows:  [13499]
11111111111111111111
incomplete name 3, col: 13499 row: []
col: 13501 similar rows:  [13501]
11111111111111111111
incomplete name 3, col: 13501 row: []
col: 13502 similar rows:  [13502]
11111111111111111111
incomplete name 3, col: 13502 row: []
col: 13504 similar rows:  [13504]
11111111111111111111
incomplete name 3, col: 13504 row: []
col: 13505 similar rows:  [13505]
11111111111111111111
incomplete name 3, col: 13505 row: []
col: 13506 similar rows:  [13506]
11111111111111111111
incomplete name 3, col: 13506 row: []
col: 13508 similar rows:  [13508]
11111111111111111111
hotelname2 [13508]
incomplete name 3, col: 13508 row: [13508]
col: 13509 similar rows:  [13509]
11111111111111111111
hotelname2 [13509]
incomplete name 3, col: 13509 row: [13509]
col: 13512 similar rows:  [13512, 13536]
incomplete name 3, col: 13512 row: []
col: 13515 similar rows:  [13515]
11111111111111111111
incomplete name 3, col: 13515 row: []
col: 13516 similar rows:  [13516]
11111111111111111111
incomplete name 3, col: 13516 row: []
col: 13520 similar rows:  [13520]
11111111111111111111
incomplete name 3, col: 13520 row: []
col: 13523 similar rows:  [13523]
11111111111111111111
incomplete name 3, col: 13523 row: []

col: 13524 similar rows:  [13524]
11111111111111111111
incomplete name 3, col: 13524 row: []
col: 13526 similar rows:  [13526]
11111111111111111111
incomplete name 3, col: 13526 row: []
col: 13527 similar rows:  [13527]
11111111111111111111
incomplete name 3, col: 13527 row: []
col: 13529 similar rows:  [13529]
11111111111111111111
incomplete name 3, col: 13529 row: []
col: 13533 similar rows:  [13533]
11111111111111111111
incomplete name 3, col: 13533 row: []
col: 13549 similar rows:  [13549]
11111111111111111111
incomplete name 3, col: 13549 row: []
col: 13550 similar rows:  [13550]
11111111111111111111
incomplete name 3, col: 13550 row: []
col: 13554 similar rows:  [13554]
11111111111111111111
incomplete name 3, col: 13554 row: []
col: 13555 similar rows:  [13555]
11111111111111111111
incomplete name 3, col: 13555 row: []
col: 13556 similar rows:  [13556]
11111111111111111111
incomplete name 3, col: 13556 row: []
col: 13559 similar rows:  [13559]
11111111111111111111
incomplete name 3, col: 13559 row: []
col: 13561 similar rows:  [13561]
11111111111111111111
incomplete name 3, col: 13561 row: []
col: 13563 similar rows:  [13563]
11111111111111111111
incomplete name 3, col: 13563 row: []
col: 13565 similar rows:  [13565]
11111111111111111111
incomplete name 3, col: 13565 row: []
col: 13568 similar rows:  [13568]
11111111111111111111
incomplete name 3, col: 13568 row: []
col: 13569 similar rows:  [13569, 13582, 13594]
incomplete name 3, col: 13569 row: []
col: 13573 similar rows:  [13573]
11111111111111111111
incomplete name 3, col: 13573 row: []
col: 13574 similar rows:  [13574]
11111111111111111111
incomplete name 3, col: 13574 row: []
col: 13576 similar rows:  [13576]
11111111111111111111
incomplete name 3, col: 13576 row: []
col: 13578 similar rows:  [13578]
11111111111111111111
hotelname2 [13578]
incomplete name 3, col: 13578 row: [13578]
col: 13579 similar rows:  [13579]
11111111111111111111
incomplete name 3, col: 13579 row: []
col: 13583 similar rows:  [13583]
11111111111111111111
incomplete name 3, col: 13583 row: []
col: 13585 similar rows:  [13585]
11111111111111111111
hotelname2 [13585]
incomplete name 3, col: 13585 row: [13585]
col: 13587 similar rows:  [13587]
11111111111111111111
incomplete name 3, col: 13587 row: []
col: 13589 similar rows:  [13589]
11111111111111111111
incomplete name 3, col: 13589 row: []
col: 13593 similar rows:  [13593]
11111111111111111111
incomplete name 3, col: 13593 row: []
col: 13595 similar rows:  [13595]
11111111111111111111
incomplete name 3, col: 13595 row: []
col: 13597 similar rows:  [13597]
11111111111111111111
incomplete name 3, col: 13597 row: []
col: 13599 similar rows:  [13599]
11111111111111111111
incomplete name 3, col: 13599 row: []
col: 13601 similar rows:  [13601]
11111111111111111111
hotelname2 [13601]
incomplete name 3, col: 13601 row: []
col: 13604 similar rows:  [13604]
11111111111111111111
incomplete name 3, col: 13604 row: []
col: 13607 similar rows:  [13607]
11111111111111111111
incomplete name 3, col: 13607 row: []
col: 13610 similar rows:  [13610]
11111111111111111111
incomplete name 3, col: 13610 row: []
col: 13619 similar rows:  [13619]
11111111111111111111
incomplete name 3, col: 13619 row: []
col: 13620 similar rows:  [13620]
11111111111111111111
incomplete name 3, col: 13620 row: []
col: 13621 similar rows:  [13621]
11111111111111111111
incomplete name 3, col: 13621 row: []
col: 13622 similar rows:  [13622]
11111111111111111111
incomplete name 3, col: 13622 row: []
col: 13624 similar rows:  [13624]
11111111111111111111
incomplete name 3, col: 13624 row: []
col: 13626 similar rows:  [13626]
11111111111111111111
incomplete name 3, col: 13626 row: []
col: 13631 similar rows:  [13631]
11111111111111111111
incomplete name 3, col: 13631 row: []
col: 13632 similar rows:  [13632]
11111111111111111111
incomplete name 3, col: 13632 row: []
col: 13634 similar rows:  [13634]
11111111111111111111
incomplete name 3, col: 13634 row: []
col: 13640 similar rows:  [13640]
11111111111111111111
incomplete name 3, col: 13640 row: []
col: 13644 similar rows:  [13644]
11111111111111111111
incomplete name 3, col: 13644 row: []
col: 13647 similar rows:  [13647]
11111111111111111111
incomplete name 3, col: 13647 row: []
col: 13649 similar rows:  [13649]
11111111111111111111
incomplete name 3, col: 13649 row: []
col: 13650 similar rows:  [13650]
11111111111111111111
incomplete name 3, col: 13650 row: []
col: 13652 similar rows:  [13652]
11111111111111111111
hotelname2 [13652]
incomplete name 3, col: 13652 row: []
col: 13653 similar rows:  [13653]
11111111111111111111
hotelname2 [13653]
incomplete name 3, col: 13653 row: []
col: 13657 similar rows:  [13657]
11111111111111111111
incomplete name 3, col: 13657 row: []
col: 13659 similar rows:  [13659]
11111111111111111111
hotelname2 [13659]
incomplete name 3, col: 13659 row: [13659]
col: 13660 similar rows:  [13660]
11111111111111111111
hotelname2 [13660]
wrong name!!!!
incomplete name 3, col: 13660 row: [13660]
col: 13662 similar rows:  [13662]
11111111111111111111
hotelname2 [13662]
incomplete name 3, col: 13662 row: [13662]
col: 13663 similar rows:  [13663]
11111111111111111111
incomplete name 3, col: 13663 row: []
col: 13669 similar rows:  [13669]
11111111111111111111
incomplete name 3, col: 13669 row: []
col: 13671 similar rows:  [13671]
11111111111111111111
incomplete name 3, col: 13671 row: []
col: 13678 similar rows:  [13678]
11111111111111111111
incomplete name 3, col: 13678 row: []
col: 13685 similar rows:  [13685]
11111111111111111111
incomplete name 3, col: 13685 row: []
col: 13686 similar rows:  [13686]
11111111111111111111
incomplete name 3, col: 13686 row: []
col: 13689 similar rows:  [13689, 13693]
incomplete name 3, col: 13689 row: []
col: 13691 similar rows:  [13691]
11111111111111111111
incomplete name 3, col: 13691 row: []
col: 13694 similar rows:  [13694]
11111111111111111111
incomplete name 3, col: 13694 row: []
col: 13695 similar rows:  [13695]
11111111111111111111
incomplete name 3, col: 13695 row: []
col: 13698 similar rows:  [13698]
11111111111111111111
hotelname2 [13698]
incomplete name 3, col: 13698 row: []
col: 13699 similar rows:  [13699]
11111111111111111111
incomplete name 3, col: 13699 row: []
end
col: 13701 similar rows:  [13701]
11111111111111111111
incomplete name 3, col: 13701 row: []
col: 13702 similar rows:  [13702]
11111111111111111111
incomplete name 3, col: 13702 row: []
col: 13703 similar rows:  [13703]
11111111111111111111
incomplete name 3, col: 13703 row: []
col: 13704 similar rows:  [13704]
11111111111111111111
hotelname2 [13704]
incomplete name 3, col: 13704 row: []
col: 13705 similar rows:  [13705, 14026]
incomplete name 3, col: 13705 row: []
col: 13706 similar rows:  [13706]
11111111111111111111
incomplete name 3, col: 13706 row: []
col: 13707 similar rows:  [13707, 13969, 13980, 14066, 14346, 14378, 14569]
incomplete name 3, col: 13707 row: []
col: 13708 similar rows:  [13708]
11111111111111111111
incomplete name 3, col: 13708 row: []
col: 13709 similar rows:  [13709, 14212]
incomplete name 3, col: 13709 row: []
col: 13710 similar rows:  [13710]
11111111111111111111
incomplete name 3, col: 13710 row: []
col: 13711 similar rows:  [13711, 13779, 14591]
incomplete name 3, col: 13711 row: []
col: 13712 similar rows:  [13712]
11111111111111111111
incomplete name 3, col: 13712 row: []
col: 13713 similar rows:  [13713, 14077]
incomplete name 3, col: 13713 row: []
col: 13714 similar rows:  [13714]
11111111111111111111
hotelname2 [13714]
incomplete name 3, col: 13714 row: []
col: 13715 similar rows:  [13715]
11111111111111111111
incomplete name 3, col: 13715 row: []
col: 13716 similar rows:  [13716]
11111111111111111111
incomplete name 3, col: 13716 row: []
col: 13717 similar rows:  [13717, 13770, 13879, 13880, 13914, 13921, 13977, 14045, 14078, 14293, 14351, 14352, 14409, 14567, 14587]
incomplete name 3, col: 13717 row: []
col: 13718 similar rows:  [13718, 13804, 14540, 14744]
incomplete name 3, col: 13718 row: []
col: 13719 similar rows:  [13719]
11111111111111111111
incomplete name 3, col: 13719 row: []
col: 13720 similar rows:  [13720, 14423, 14471]
incomplete name 3, col: 13720 row: []
col: 13721 similar rows:  [13721]
11111111111111111111
hotelname2 [13721]
incomplete name 3, col: 13721 row: [13721]
col: 13722 similar rows:  [13722]
11111111111111111111
incomplete name 3, col: 13722 row: []
col: 13723 similar rows:  [13723, 14114, 14161, 14711]
incomplete name 3, col: 13723 row: []
col: 13724 similar rows:  [13724]
11111111111111111111
incomplete name 3, col: 13724 row: []

col: 13725 similar rows:  [13725]
11111111111111111111
incomplete name 3, col: 13725 row: []
col: 13726 similar rows:  [13726, 14395]
incomplete name 3, col: 13726 row: []
col: 13727 similar rows:  [13727, 14302, 14324, 14357, 14398, 14529, 14712, 14728, 14754]
incomplete name 3, col: 13727 row: []
col: 13728 similar rows:  [13728]
11111111111111111111
incomplete name 3, col: 13728 row: []
col: 13729 similar rows:  [13729]
11111111111111111111
hotelname2 [13729]
incomplete name 3, col: 13729 row: []
col: 13730 similar rows:  [13730, 13763, 13846]
incomplete name 3, col: 13730 row: []
col: 13731 similar rows:  [13731, 14052]
incomplete name 3, col: 13731 row: []
col: 13732 similar rows:  [13732, 13748, 13767, 14300, 14401]
incomplete name 3, col: 13732 row: []
col: 13733 similar rows:  [13733, 14154]
incomplete name 3, col: 13733 row: []
col: 13734 similar rows:  [13734]
11111111111111111111
incomplete name 3, col: 13734 row: []
col: 13735 similar rows:  [13735, 13820, 14145, 14325]
incomplete name 3, col: 13735 row: []
col: 13736 similar rows:  [13736, 13968]
incomplete name 3, col: 13736 row: []
col: 13737 similar rows:  [13737, 13739, 13807, 13818, 14612, 14618]
incomplete name 3, col: 13737 row: []
col: 13738 similar rows:  [13738]
11111111111111111111
incomplete name 3, col: 13738 row: []
col: 13740 similar rows:  [13740, 13956, 13975, 14003, 14148, 14476, 14785]
incomplete name 3, col: 13740 row: []
col: 13741 similar rows:  [13741]
11111111111111111111
hotelname2 [13741]
incomplete name 3, col: 13741 row: [13741]
col: 13742 similar rows:  [13742]
11111111111111111111
incomplete name 3, col: 13742 row: []
col: 13743 similar rows:  [13743, 14174]
incomplete name 3, col: 13743 row: []
col: 13744 similar rows:  [13744, 14158]
incomplete name 3, col: 13744 row: []
col: 13745 similar rows:  [13745]
11111111111111111111
incomplete name 3, col: 13745 row: []
col: 13746 similar rows:  [13746]
11111111111111111111
incomplete name 3, col: 13746 row: []
col: 13747 similar rows:  [13747, 14246]
incomplete name 3, col: 13747 row: []
col: 13749 similar rows:  [13749, 14284, 14447]
incomplete name 3, col: 13749 row: []
col: 13750 similar rows:  [13750, 14146, 14314, 14465]
incomplete name 3, col: 13750 row: []
col: 13751 similar rows:  [13751, 13960, 14043, 14101]
incomplete name 3, col: 13751 row: []
col: 13752 similar rows:  [13752, 14626]
incomplete name 3, col: 13752 row: []
col: 13753 similar rows:  [13753, 14606]
incomplete name 3, col: 13753 row: []
col: 13754 similar rows:  [13754]
11111111111111111111
hotelname2 [13754]
incomplete name 3, col: 13754 row: []
col: 13755 similar rows:  [13755, 13842, 13906, 14001, 14206, 14254, 14301, 14468]
incomplete name 3, col: 13755 row: []
col: 13756 similar rows:  [13756]
11111111111111111111
incomplete name 3, col: 13756 row: []
col: 13757 similar rows:  [13757]
11111111111111111111
hotelname2 [13757]
incomplete name 3, col: 13757 row: []
col: 13758 similar rows:  [13758]
11111111111111111111
incomplete name 3, col: 13758 row: []
col: 13759 similar rows:  [13759]
11111111111111111111
incomplete name 3, col: 13759 row: []
col: 13760 similar rows:  [13760]
11111111111111111111
incomplete name 3, col: 13760 row: []
col: 13761 similar rows:  [13761]
11111111111111111111
hotelname2 [13761]
incomplete name 3, col: 13761 row: []
col: 13762 similar rows:  [13762, 14579, 14585, 14660, 14674, 14727]
incomplete name 3, col: 13762 row: []
col: 13764 similar rows:  [13764]
11111111111111111111
incomplete name 3, col: 13764 row: []
col: 13765 similar rows:  [13765, 13966, 14067, 14457]
incomplete name 3, col: 13765 row: []
col: 13766 similar rows:  [13766]
11111111111111111111
hotelname2 [13766]
incomplete name 3, col: 13766 row: [13766]
col: 13768 similar rows:  [13768, 13783, 13878, 14278]
incomplete name 3, col: 13768 row: []
col: 13769 similar rows:  [13769, 14208, 14565]
incomplete name 3, col: 13769 row: []
col: 13771 similar rows:  [13771, 14383]
incomplete name 3, col: 13771 row: []
col: 13772 similar rows:  [13772, 14198]
incomplete name 3, col: 13772 row: []
col: 13773 similar rows:  [13773]
11111111111111111111
incomplete name 3, col: 13773 row: []
col: 13774 similar rows:  [13774, 13830, 14023, 14182, 14582]
incomplete name 3, col: 13774 row: []
col: 13775 similar rows:  [13775, 14096, 14534]
incomplete name 3, col: 13775 row: []
col: 13776 similar rows:  [13776, 14054]
incomplete name 3, col: 13776 row: []
col: 13777 similar rows:  [13777]
11111111111111111111
incomplete name 3, col: 13777 row: []
col: 13778 similar rows:  [13778, 13983, 14017, 14055, 14432, 14741]
incomplete name 3, col: 13778 row: []
col: 13780 similar rows:  [13780, 14600]
incomplete name 3, col: 13780 row: []
col: 13781 similar rows:  [13781, 13990, 14127, 14141, 14249]
incomplete name 3, col: 13781 row: []
col: 13782 similar rows:  [13782, 14568, 14600, 14607]
incomplete name 3, col: 13782 row: []
col: 13784 similar rows:  [13784, 14704]
incomplete name 3, col: 13784 row: []
col: 13785 similar rows:  [13785, 14215]
incomplete name 3, col: 13785 row: []
col: 13786 similar rows:  [13786]
11111111111111111111
incomplete name 3, col: 13786 row: []
col: 13787 similar rows:  [13787, 14634]
incomplete name 3, col: 13787 row: []
col: 13788 similar rows:  [13788, 13885, 14289]
incomplete name 3, col: 13788 row: []
col: 13789 similar rows:  [13789]
11111111111111111111
incomplete name 3, col: 13789 row: []
col: 13790 similar rows:  [13790, 14133, 14283, 14466, 14631]
incomplete name 3, col: 13790 row: []
col: 13791 similar rows:  [13791]
11111111111111111111
hotelname2 [13791]
incomplete name 3, col: 13791 row: []
col: 13792 similar rows:  [13792, 14326, 14420]
incomplete name 3, col: 13792 row: []
col: 13793 similar rows:  [13793]
11111111111111111111
incomplete name 3, col: 13793 row: []
col: 13794 similar rows:  [13794, 13881, 13887, 13941, 14120, 14125, 14190, 14223, 14441, 14459]
incomplete name 3, col: 13794 row: []
col: 13795 similar rows:  [13795, 13840, 14009, 14053, 14142, 14224, 14361, 14392, 14492, 14596]
incomplete name 3, col: 13795 row: []
col: 13796 similar rows:  [13796, 13907, 13967, 13970, 13985, 14015, 14107, 14112, 14134]
incomplete name 3, col: 13796 row: []
col: 13797 similar rows:  [13797]
11111111111111111111
hotelname2 [13797]
incomplete name 3, col: 13797 row: [13797]
col: 13798 similar rows:  [13798, 14749]
incomplete name 3, col: 13798 row: []
col: 13799 similar rows:  [13799, 14057, 14184, 14313, 14389, 14487, 14706, 14778]
incomplete name 3, col: 13799 row: []
col: 13800 similar rows:  [13800]
11111111111111111111
incomplete name 3, col: 13800 row: []
col: 13801 similar rows:  [13801]
11111111111111111111
incomplete name 3, col: 13801 row: []
col: 13802 similar rows:  [13802, 13855]
incomplete name 3, col: 13802 row: []
col: 13803 similar rows:  [13803]
11111111111111111111
incomplete name 3, col: 13803 row: []
col: 13805 similar rows:  [13805, 14153, 14304]
incomplete name 3, col: 13805 row: []
col: 13806 similar rows:  [13806, 14267, 14599]
incomplete name 3, col: 13806 row: []
col: 13808 similar rows:  [13808]
11111111111111111111
incomplete name 3, col: 13808 row: []
col: 13809 similar rows:  [13809, 13829, 13838, 13882, 14135, 14204, 14394]
incomplete name 3, col: 13809 row: []
col: 13810 similar rows:  [13810]
11111111111111111111
incomplete name 3, col: 13810 row: []
col: 13811 similar rows:  [13811]
11111111111111111111
incomplete name 3, col: 13811 row: []
col: 13812 similar rows:  [13812]
11111111111111111111
hotelname2 [13812]
incomplete name 3, col: 13812 row: []
col: 13813 similar rows:  [13813, 14012, 14216, 14270, 14298, 14400]
incomplete name 3, col: 13813 row: []
col: 13814 similar rows:  [13814]
11111111111111111111
incomplete name 3, col: 13814 row: []
col: 13815 similar rows:  [13815]
11111111111111111111
incomplete name 3, col: 13815 row: []
col: 13816 similar rows:  [13816, 13971]
incomplete name 3, col: 13816 row: []
col: 13817 similar rows:  [13817]
11111111111111111111
incomplete name 3, col: 13817 row: []
col: 13819 similar rows:  [13819]
11111111111111111111
incomplete name 3, col: 13819 row: []
col: 13821 similar rows:  [13821]
11111111111111111111
incomplete name 3, col: 13821 row: []
col: 13822 similar rows:  [13822, 13939]
incomplete name 3, col: 13822 row: []
col: 13823 similar rows:  [13823, 14482, 14657]
incomplete name 3, col: 13823 row: []
col: 13824 similar rows:  [13824]
11111111111111111111
incomplete name 3, col: 13824 row: []
col: 13825 similar rows:  [13825]
11111111111111111111
hotelname2 [13825]
incomplete name 3, col: 13825 row: []
col: 13826 similar rows:  [13826]
11111111111111111111
incomplete name 3, col: 13826 row: []
col: 13827 similar rows:  [13827, 14118, 14201, 14220]
incomplete name 3, col: 13827 row: []
col: 13828 similar rows:  [13828, 14407, 14617]
incomplete name 3, col: 13828 row: []
col: 13831 similar rows:  [13831, 14008, 14745]
incomplete name 3, col: 13831 row: []
col: 13832 similar rows:  [13832]
11111111111111111111
incomplete name 3, col: 13832 row: []

col: 13833 similar rows:  [13833, 14514, 14517, 14532]
incomplete name 3, col: 13833 row: []
col: 13834 similar rows:  [13834, 13954, 13957, 14344, 14376]
incomplete name 3, col: 13834 row: []
col: 13835 similar rows:  [13835]
11111111111111111111
incomplete name 3, col: 13835 row: []
col: 13836 similar rows:  [13836]
11111111111111111111
hotelname2 [13836]
incomplete name 3, col: 13836 row: []
col: 13837 similar rows:  [13837, 14070, 14402]
incomplete name 3, col: 13837 row: []
col: 13839 similar rows:  [13839, 14405]
incomplete name 3, col: 13839 row: []
col: 13841 similar rows:  [13841]
11111111111111111111
incomplete name 3, col: 13841 row: []
col: 13843 similar rows:  [13843]
11111111111111111111
incomplete name 3, col: 13843 row: []
col: 13844 similar rows:  [13844]
11111111111111111111
incomplete name 3, col: 13844 row: []
col: 13845 similar rows:  [13845]
11111111111111111111
incomplete name 3, col: 13845 row: []
col: 13847 similar rows:  [13847]
11111111111111111111
incomplete name 3, col: 13847 row: []
col: 13848 similar rows:  [13848]
11111111111111111111
incomplete name 3, col: 13848 row: []
col: 13849 similar rows:  [13849, 14661]
incomplete name 3, col: 13849 row: []
col: 13850 similar rows:  [13850, 14254]
incomplete name 3, col: 13850 row: []
col: 13851 similar rows:  [13851]
11111111111111111111
incomplete name 3, col: 13851 row: []
col: 13852 similar rows:  [13852, 13954, 13957, 14344, 14761]
incomplete name 3, col: 13852 row: []
col: 13853 similar rows:  [13853, 13910]
incomplete name 3, col: 13853 row: []
col: 13854 similar rows:  [13854, 14524]
incomplete name 3, col: 13854 row: []
col: 13856 similar rows:  [13856]
11111111111111111111
hotelname2 [13856]
incomplete name 3, col: 13856 row: [13856]
col: 13857 similar rows:  [13857]
11111111111111111111
hotelname2 [13857]
incomplete name 3, col: 13857 row: [13857]
col: 13858 similar rows:  [13858]
11111111111111111111
incomplete name 3, col: 13858 row: []
col: 13859 similar rows:  [13859]
11111111111111111111
hotelname2 [13859]
incomplete name 3, col: 13859 row: [13859]
col: 13860 similar rows:  [13860, 14719]
incomplete name 3, col: 13860 row: []
col: 13861 similar rows:  [13861]
11111111111111111111
incomplete name 3, col: 13861 row: []
col: 13862 similar rows:  [13862]
11111111111111111111
incomplete name 3, col: 13862 row: []
col: 13863 similar rows:  [13863]
11111111111111111111
incomplete name 3, col: 13863 row: []
col: 13864 similar rows:  [13864, 13898]
incomplete name 3, col: 13864 row: []
col: 13865 similar rows:  [13865]
11111111111111111111
incomplete name 3, col: 13865 row: []
col: 13866 similar rows:  [13866]
11111111111111111111
incomplete name 3, col: 13866 row: []
col: 13867 similar rows:  [13867, 13966, 14067, 14457]
incomplete name 3, col: 13867 row: []
col: 13868 similar rows:  [13868, 14044]
incomplete name 3, col: 13868 row: []
col: 13869 similar rows:  [13869]
11111111111111111111
incomplete name 3, col: 13869 row: []
col: 13870 similar rows:  [13870, 13873, 13888, 13996, 14034, 14155, 14296]
incomplete name 3, col: 13870 row: []
col: 13871 similar rows:  [13871]
11111111111111111111
incomplete name 3, col: 13871 row: []
col: 13872 similar rows:  [13872, 14064, 14308, 14540, 14608, 14645]
incomplete name 3, col: 13872 row: []
col: 13874 similar rows:  [13874]
11111111111111111111
incomplete name 3, col: 13874 row: []
col: 13875 similar rows:  [13875]
11111111111111111111
incomplete name 3, col: 13875 row: []
col: 13876 similar rows:  [13876]
11111111111111111111
incomplete name 3, col: 13876 row: []
col: 13877 similar rows:  [13877]
11111111111111111111
incomplete name 3, col: 13877 row: []
col: 13883 similar rows:  [13883]
11111111111111111111
hotelname2 [13883]
incomplete name 3, col: 13883 row: [13883]
col: 13884 similar rows:  [13884]
11111111111111111111
incomplete name 3, col: 13884 row: []
col: 13886 similar rows:  [13886, 14577]
incomplete name 3, col: 13886 row: []
col: 13889 similar rows:  [13889]
11111111111111111111
incomplete name 3, col: 13889 row: []
col: 13890 similar rows:  [13890, 14089, 14264, 14347]
incomplete name 3, col: 13890 row: []
col: 13891 similar rows:  [13891, 14397]
incomplete name 3, col: 13891 row: []
col: 13892 similar rows:  [13892]
11111111111111111111
incomplete name 3, col: 13892 row: []
col: 13893 similar rows:  [13893, 13944, 14451]
incomplete name 3, col: 13893 row: []
col: 13894 similar rows:  [13894]
11111111111111111111
incomplete name 3, col: 13894 row: []
col: 13895 similar rows:  [13895, 13952, 14452]
incomplete name 3, col: 13895 row: []
col: 13896 similar rows:  [13896]
11111111111111111111
incomplete name 3, col: 13896 row: []
col: 13897 similar rows:  [13897]
11111111111111111111
incomplete name 3, col: 13897 row: []
col: 13899 similar rows:  [13899]
11111111111111111111
hotelname2 [13899]
incomplete name 3, col: 13899 row: [13899]
col: 13900 similar rows:  [13900]
11111111111111111111
incomplete name 3, col: 13900 row: []
col: 13901 similar rows:  [13901]
11111111111111111111
incomplete name 3, col: 13901 row: []
col: 13902 similar rows:  [13902, 14091, 14255, 14259]
incomplete name 3, col: 13902 row: []
col: 13903 similar rows:  [13903, 14443]
incomplete name 3, col: 13903 row: []
col: 13904 similar rows:  [13904]
11111111111111111111
incomplete name 3, col: 13904 row: []
col: 13905 similar rows:  [13905]
11111111111111111111
incomplete name 3, col: 13905 row: []
col: 13908 similar rows:  [13908]
11111111111111111111
incomplete name 3, col: 13908 row: []
col: 13909 similar rows:  [13909, 13917]
incomplete name 3, col: 13909 row: []
col: 13911 similar rows:  [13911, 13922]
incomplete name 3, col: 13911 row: []
col: 13912 similar rows:  [13912, 14139]
incomplete name 3, col: 13912 row: []
col: 13913 similar rows:  [13913, 13935]
incomplete name 3, col: 13913 row: []
col: 13915 similar rows:  [13915]
11111111111111111111
incomplete name 3, col: 13915 row: []
col: 13916 similar rows:  [13916]
11111111111111111111
hotelname2 [13916]
incomplete name 3, col: 13916 row: [13916]
col: 13918 similar rows:  [13918, 13924, 14574]
incomplete name 3, col: 13918 row: []
col: 13919 similar rows:  [13919, 14188, 14573]
incomplete name 3, col: 13919 row: []
col: 13920 similar rows:  [13920, 14194, 14199, 14559]
incomplete name 3, col: 13920 row: []
col: 13923 similar rows:  [13923]
11111111111111111111
incomplete name 3, col: 13923 row: []
col: 13925 similar rows:  [13925]
11111111111111111111
incomplete name 3, col: 13925 row: []
col: 13926 similar rows:  [13926]
11111111111111111111
incomplete name 3, col: 13926 row: []
col: 13927 similar rows:  [13927]
11111111111111111111
incomplete name 3, col: 13927 row: []
col: 13928 similar rows:  [13928, 13958, 14013, 14130, 14279, 14305, 14504]
incomplete name 3, col: 13928 row: []
col: 13929 similar rows:  [13929, 14229]
incomplete name 3, col: 13929 row: []
col: 13930 similar rows:  [13930]
11111111111111111111
incomplete name 3, col: 13930 row: []
col: 13931 similar rows:  [13931]
11111111111111111111
incomplete name 3, col: 13931 row: []
col: 13932 similar rows:  [13932]
11111111111111111111
incomplete name 3, col: 13932 row: []
col: 13933 similar rows:  [13933, 14222, 14506, 14512, 14691, 14696]
incomplete name 3, col: 13933 row: []
col: 13934 similar rows:  [13934]
11111111111111111111
incomplete name 3, col: 13934 row: []
col: 13936 similar rows:  [13936]
11111111111111111111
incomplete name 3, col: 13936 row: []
col: 13937 similar rows:  [13937]
11111111111111111111
incomplete name 3, col: 13937 row: []
col: 13938 similar rows:  [13938]
11111111111111111111
incomplete name 3, col: 13938 row: []
col: 13940 similar rows:  [13940]
11111111111111111111
incomplete name 3, col: 13940 row: []
col: 13942 similar rows:  [13942, 14651]
incomplete name 3, col: 13942 row: []
col: 13943 similar rows:  [13943]
11111111111111111111
incomplete name 3, col: 13943 row: []
col: 13945 similar rows:  [13945]
11111111111111111111
incomplete name 3, col: 13945 row: []
col: 13946 similar rows:  [13946]
11111111111111111111
incomplete name 3, col: 13946 row: []
col: 13947 similar rows:  [13947]
11111111111111111111
incomplete name 3, col: 13947 row: []
col: 13948 similar rows:  [13948]
11111111111111111111
incomplete name 3, col: 13948 row: []
col: 13949 similar rows:  [13949]
11111111111111111111
incomplete name 3, col: 13949 row: []
col: 13950 similar rows:  [13950]
11111111111111111111
hotelname2 [13950]
incomplete name 3, col: 13950 row: [13950]
col: 13951 similar rows:  [13951]
11111111111111111111
hotelname2 [13951]
incomplete name 3, col: 13951 row: []
col: 13953 similar rows:  [13953, 14590]
incomplete name 3, col: 13953 row: []
col: 13955 similar rows:  [13955, 14018, 14021]
incomplete name 3, col: 13955 row: []
col: 13959 similar rows:  [13959]
11111111111111111111
hotelname2 [13959]
incomplete name 3, col: 13959 row: []

col: 13961 similar rows:  [13961]
11111111111111111111
incomplete name 3, col: 13961 row: []
col: 13962 similar rows:  [13962]
11111111111111111111
incomplete name 3, col: 13962 row: []
col: 13963 similar rows:  [13963, 14152]
incomplete name 3, col: 13963 row: []
col: 13964 similar rows:  [13964, 14029, 14635]
incomplete name 3, col: 13964 row: []
col: 13965 similar rows:  [13965, 14489]
incomplete name 3, col: 13965 row: []
col: 13972 similar rows:  [13972]
11111111111111111111
hotelname2 [13972]
incomplete name 3, col: 13972 row: [13972]
col: 13973 similar rows:  [13973, 14632]
incomplete name 3, col: 13973 row: []
col: 13974 similar rows:  [13974]
11111111111111111111
incomplete name 3, col: 13974 row: []
col: 13976 similar rows:  [13976, 13984, 14588]
incomplete name 3, col: 13976 row: []
col: 13978 similar rows:  [13978]
11111111111111111111
incomplete name 3, col: 13978 row: []
col: 13979 similar rows:  [13979]
11111111111111111111
incomplete name 3, col: 13979 row: []
col: 13981 similar rows:  [13981]
11111111111111111111
incomplete name 3, col: 13981 row: []
col: 13982 similar rows:  [13982, 14126]
incomplete name 3, col: 13982 row: []
col: 13986 similar rows:  [13986, 14470]
incomplete name 3, col: 13986 row: []
col: 13987 similar rows:  [13987, 14433]
incomplete name 3, col: 13987 row: []
col: 13988 similar rows:  [13988, 14558]
incomplete name 3, col: 13988 row: []
col: 13989 similar rows:  [13989]
11111111111111111111
incomplete name 3, col: 13989 row: []
col: 13991 similar rows:  [13991]
11111111111111111111
incomplete name 3, col: 13991 row: []
col: 13992 similar rows:  [13992]
11111111111111111111
incomplete name 3, col: 13992 row: []
col: 13993 similar rows:  [13993, 14764]
incomplete name 3, col: 13993 row: []
col: 13994 similar rows:  [13994]
11111111111111111111
incomplete name 3, col: 13994 row: []
col: 13995 similar rows:  [13995]
11111111111111111111
incomplete name 3, col: 13995 row: []
col: 13997 similar rows:  [13997, 14463]
incomplete name 3, col: 13997 row: []
col: 13998 similar rows:  [13998, 14443]
incomplete name 3, col: 13998 row: []
col: 13999 similar rows:  [13999]
11111111111111111111
incomplete name 3, col: 13999 row: []
col: 14000 similar rows:  [14000]
11111111111111111111
hotelname2 [14000]
incomplete name 3, col: 14000 row: [14000]
col: 14002 similar rows:  [14002]
11111111111111111111
incomplete name 3, col: 14002 row: []
col: 14004 similar rows:  [14004, 14051]
incomplete name 3, col: 14004 row: []
col: 14005 similar rows:  [14005, 14152]
incomplete name 3, col: 14005 row: []
col: 14006 similar rows:  [14006]
11111111111111111111
incomplete name 3, col: 14006 row: []
col: 14007 similar rows:  [14007]
11111111111111111111
incomplete name 3, col: 14007 row: []
col: 14010 similar rows:  [14010]
11111111111111111111
incomplete name 3, col: 14010 row: []
col: 14011 similar rows:  [14011]
11111111111111111111
incomplete name 3, col: 14011 row: []
col: 14014 similar rows:  [14014]
11111111111111111111
incomplete name 3, col: 14014 row: []
col: 14016 similar rows:  [14016]
11111111111111111111
incomplete name 3, col: 14016 row: []
col: 14019 similar rows:  [14019, 14110]
incomplete name 3, col: 14019 row: []
col: 14020 similar rows:  [14020]
11111111111111111111
incomplete name 3, col: 14020 row: []
col: 14022 similar rows:  [14022, 14095]
incomplete name 3, col: 14022 row: []
col: 14024 similar rows:  [14024]
11111111111111111111
incomplete name 3, col: 14024 row: []
col: 14025 similar rows:  [14025, 14381]
incomplete name 3, col: 14025 row: []
col: 14027 similar rows:  [14027]
11111111111111111111
incomplete name 3, col: 14027 row: []
col: 14028 similar rows:  [14028]
11111111111111111111
incomplete name 3, col: 14028 row: []
col: 14030 similar rows:  [14030]
11111111111111111111
incomplete name 3, col: 14030 row: []
col: 14031 similar rows:  [14031]
11111111111111111111
incomplete name 3, col: 14031 row: []
col: 14032 similar rows:  [14032]
11111111111111111111
incomplete name 3, col: 14032 row: []
col: 14033 similar rows:  [14033]
11111111111111111111
hotelname2 [14033]
incomplete name 3, col: 14033 row: [14033]
col: 14035 similar rows:  [14035, 14103]
incomplete name 3, col: 14035 row: []
col: 14036 similar rows:  [14036]
11111111111111111111
incomplete name 3, col: 14036 row: []
col: 14037 similar rows:  [14037]
11111111111111111111
hotelname2 [14037]
incomplete name 3, col: 14037 row: [14037]
col: 14038 similar rows:  [14038, 14406, 14776]
incomplete name 3, col: 14038 row: []
col: 14039 similar rows:  [14039]
11111111111111111111
incomplete name 3, col: 14039 row: []
col: 14040 similar rows:  [14040, 14279]
incomplete name 3, col: 14040 row: []
col: 14041 similar rows:  [14041]
11111111111111111111
incomplete name 3, col: 14041 row: []
col: 14042 similar rows:  [14042]
11111111111111111111
incomplete name 3, col: 14042 row: []
col: 14046 similar rows:  [14046, 14435]
incomplete name 3, col: 14046 row: []
col: 14047 similar rows:  [14047, 14578]
incomplete name 3, col: 14047 row: []
col: 14048 similar rows:  [14048]
11111111111111111111
incomplete name 3, col: 14048 row: []
col: 14049 similar rows:  [14049]
11111111111111111111
incomplete name 3, col: 14049 row: []
col: 14050 similar rows:  [14050]
11111111111111111111
hotelname2 [14050]
incomplete name 3, col: 14050 row: [14050]
col: 14056 similar rows:  [14056, 14624]
incomplete name 3, col: 14056 row: []
col: 14058 similar rows:  [14058]
11111111111111111111
incomplete name 3, col: 14058 row: []
col: 14059 similar rows:  [14059]
11111111111111111111
hotelname2 [14059]
incomplete name 3, col: 14059 row: []
col: 14060 similar rows:  [14060]
11111111111111111111
incomplete name 3, col: 14060 row: []
col: 14061 similar rows:  [14061, 14068, 14571, 14605]
incomplete name 3, col: 14061 row: []
col: 14062 similar rows:  [14062]
11111111111111111111
incomplete name 3, col: 14062 row: []
col: 14063 similar rows:  [14063, 14330]
incomplete name 3, col: 14063 row: []
col: 14065 similar rows:  [14065]
11111111111111111111
incomplete name 3, col: 14065 row: []
col: 14069 similar rows:  [14069]
11111111111111111111
incomplete name 3, col: 14069 row: []
col: 14071 similar rows:  [14071]
11111111111111111111
incomplete name 3, col: 14071 row: []
col: 14072 similar rows:  [14072, 14486]
incomplete name 3, col: 14072 row: []
col: 14073 similar rows:  [14073]
11111111111111111111
incomplete name 3, col: 14073 row: []
col: 14074 similar rows:  [14074]
11111111111111111111
hotelname2 [14074]
incomplete name 3, col: 14074 row: []
col: 14075 similar rows:  [14075, 14088, 14117, 14400, 14592]
hotelname2 [14400]
incomplete name 3, col: 14075 row: [14400]
col: 14076 similar rows:  [14076]
11111111111111111111
incomplete name 3, col: 14076 row: []
col: 14079 similar rows:  [14079]
11111111111111111111
incomplete name 3, col: 14079 row: []
col: 14080 similar rows:  [14080]
11111111111111111111
incomplete name 3, col: 14080 row: []
col: 14081 similar rows:  [14081, 14129]
incomplete name 3, col: 14081 row: []
col: 14082 similar rows:  [14082]
11111111111111111111
incomplete name 3, col: 14082 row: []
col: 14083 similar rows:  [14083]
11111111111111111111
incomplete name 3, col: 14083 row: []
col: 14084 similar rows:  [14084, 14163, 14713, 14717]
incomplete name 3, col: 14084 row: []
col: 14085 similar rows:  [14085]
11111111111111111111
incomplete name 3, col: 14085 row: []
col: 14086 similar rows:  [14086]
11111111111111111111
incomplete name 3, col: 14086 row: []
col: 14087 similar rows:  [14087]
11111111111111111111
incomplete name 3, col: 14087 row: []
col: 14090 similar rows:  [14090]
11111111111111111111
incomplete name 3, col: 14090 row: []
col: 14092 similar rows:  [14092, 14498]
incomplete name 3, col: 14092 row: []
col: 14093 similar rows:  [14093]
11111111111111111111
incomplete name 3, col: 14093 row: []
col: 14094 similar rows:  [14094]
11111111111111111111
incomplete name 3, col: 14094 row: []
col: 14097 similar rows:  [14097]
11111111111111111111
incomplete name 3, col: 14097 row: []
col: 14098 similar rows:  [14098]
11111111111111111111
incomplete name 3, col: 14098 row: []
col: 14099 similar rows:  [14099]
11111111111111111111
incomplete name 3, col: 14099 row: []
col: 14100 similar rows:  [14100]
11111111111111111111
incomplete name 3, col: 14100 row: []
col: 14102 similar rows:  [14102]
11111111111111111111
incomplete name 3, col: 14102 row: []
col: 14104 similar rows:  [14104, 14783]
incomplete name 3, col: 14104 row: []
col: 14105 similar rows:  [14105, 14745]
incomplete name 3, col: 14105 row: []

col: 14106 similar rows:  [14106, 14654, 14716]
incomplete name 3, col: 14106 row: []
col: 14108 similar rows:  [14108, 14342, 14354]
incomplete name 3, col: 14108 row: []
col: 14109 similar rows:  [14109]
11111111111111111111
incomplete name 3, col: 14109 row: []
col: 14111 similar rows:  [14111, 14765]
incomplete name 3, col: 14111 row: []
col: 14113 similar rows:  [14113]
11111111111111111111
incomplete name 3, col: 14113 row: []
col: 14115 similar rows:  [14115]
11111111111111111111
incomplete name 3, col: 14115 row: []
col: 14116 similar rows:  [14116]
11111111111111111111
incomplete name 3, col: 14116 row: []
col: 14119 similar rows:  [14119, 14151, 14387, 14552]
hotelname2 [14387]
incomplete name 3, col: 14119 row: [14387]
col: 14121 similar rows:  [14121, 14556, 14572, 14586]
incomplete name 3, col: 14121 row: []
col: 14122 similar rows:  [14122]
11111111111111111111
incomplete name 3, col: 14122 row: []
col: 14123 similar rows:  [14123, 14550]
incomplete name 3, col: 14123 row: []
col: 14124 similar rows:  [14124]
11111111111111111111
incomplete name 3, col: 14124 row: []
col: 14128 similar rows:  [14128, 14592]
incomplete name 3, col: 14128 row: []
col: 14131 similar rows:  [14131]
11111111111111111111
incomplete name 3, col: 14131 row: []
col: 14132 similar rows:  [14132]
11111111111111111111
incomplete name 3, col: 14132 row: []
col: 14136 similar rows:  [14136, 14166, 14417, 14522, 14742]
incomplete name 3, col: 14136 row: []
col: 14137 similar rows:  [14137]
11111111111111111111
incomplete name 3, col: 14137 row: []
col: 14138 similar rows:  [14138]
11111111111111111111
incomplete name 3, col: 14138 row: []
col: 14140 similar rows:  [14140]
11111111111111111111
incomplete name 3, col: 14140 row: []
col: 14143 similar rows:  [14143]
11111111111111111111
incomplete name 3, col: 14143 row: []
col: 14144 similar rows:  [14144]
11111111111111111111
incomplete name 3, col: 14144 row: []
col: 14147 similar rows:  [14147, 14432, 14741]
incomplete name 3, col: 14147 row: []
col: 14149 similar rows:  [14149, 14432, 14741]
incomplete name 3, col: 14149 row: []
col: 14150 similar rows:  [14150]
11111111111111111111
hotelname2 [14150]
incomplete name 3, col: 14150 row: [14150]
col: 14156 similar rows:  [14156]
11111111111111111111
incomplete name 3, col: 14156 row: []
col: 14157 similar rows:  [14157]
11111111111111111111
incomplete name 3, col: 14157 row: []
col: 14159 similar rows:  [14159]
11111111111111111111
incomplete name 3, col: 14159 row: []
col: 14160 similar rows:  [14160]
11111111111111111111
incomplete name 3, col: 14160 row: []
col: 14162 similar rows:  [14162]
11111111111111111111
incomplete name 3, col: 14162 row: []
col: 14164 similar rows:  [14164]
11111111111111111111
hotelname2 [14164]
incomplete name 3, col: 14164 row: [14164]
col: 14165 similar rows:  [14165]
11111111111111111111
incomplete name 3, col: 14165 row: []
col: 14167 similar rows:  [14167]
11111111111111111111
incomplete name 3, col: 14167 row: []
col: 14168 similar rows:  [14168]
11111111111111111111
incomplete name 3, col: 14168 row: []
col: 14169 similar rows:  [14169, 14234]
incomplete name 3, col: 14169 row: []
col: 14170 similar rows:  [14170]
11111111111111111111
incomplete name 3, col: 14170 row: []
col: 14171 similar rows:  [14171]
11111111111111111111
incomplete name 3, col: 14171 row: []
col: 14172 similar rows:  [14172]
11111111111111111111
incomplete name 3, col: 14172 row: []
col: 14173 similar rows:  [14173]
11111111111111111111
hotelname2 [14173]
incomplete name 3, col: 14173 row: []
col: 14175 similar rows:  [14175, 14321, 14424, 14715]
incomplete name 3, col: 14175 row: []
col: 14176 similar rows:  [14176]
11111111111111111111
hotelname2 [14176]
incomplete name 3, col: 14176 row: [14176]
col: 14177 similar rows:  [14177]
11111111111111111111
hotelname2 [14177]
incomplete name 3, col: 14177 row: [14177]
col: 14178 similar rows:  [14178]
11111111111111111111
incomplete name 3, col: 14178 row: []
col: 14179 similar rows:  [14179]
11111111111111111111
incomplete name 3, col: 14179 row: []
col: 14180 similar rows:  [14180]
11111111111111111111
hotelname2 [14180]
incomplete name 3, col: 14180 row: []
col: 14181 similar rows:  [14181]
11111111111111111111
incomplete name 3, col: 14181 row: []
col: 14183 similar rows:  [14183, 14253]
incomplete name 3, col: 14183 row: []
col: 14185 similar rows:  [14185, 14310, 14725, 14735]
incomplete name 3, col: 14185 row: []
col: 14186 similar rows:  [14186]
11111111111111111111
incomplete name 3, col: 14186 row: []
col: 14187 similar rows:  [14187]
11111111111111111111
incomplete name 3, col: 14187 row: []
col: 14189 similar rows:  [14189]
11111111111111111111
incomplete name 3, col: 14189 row: []
col: 14191 similar rows:  [14191]
11111111111111111111
incomplete name 3, col: 14191 row: []
col: 14192 similar rows:  [14192]
11111111111111111111
incomplete name 3, col: 14192 row: []
col: 14193 similar rows:  [14193]
11111111111111111111
incomplete name 3, col: 14193 row: []
col: 14195 similar rows:  [14195, 14253]
incomplete name 3, col: 14195 row: []
col: 14196 similar rows:  [14196]
11111111111111111111
hotelname2 [14196]
incomplete name 3, col: 14196 row: []
col: 14197 similar rows:  [14197]
11111111111111111111
hotelname2 [14197]
incomplete name 3, col: 14197 row: [14197]
col: 14200 similar rows:  [14200]
11111111111111111111
incomplete name 3, col: 14200 row: []
col: 14202 similar rows:  [14202]
11111111111111111111
incomplete name 3, col: 14202 row: []
col: 14203 similar rows:  [14203, 14215]
incomplete name 3, col: 14203 row: []
col: 14205 similar rows:  [14205, 14400]
incomplete name 3, col: 14205 row: []
col: 14207 similar rows:  [14207]
11111111111111111111
incomplete name 3, col: 14207 row: []
col: 14209 similar rows:  [14209, 14421]
incomplete name 3, col: 14209 row: []
col: 14210 similar rows:  [14210]
11111111111111111111
incomplete name 3, col: 14210 row: []
col: 14211 similar rows:  [14211, 14595]
incomplete name 3, col: 14211 row: []
col: 14213 similar rows:  [14213, 14665]
incomplete name 3, col: 14213 row: []
col: 14214 similar rows:  [14214]
11111111111111111111
incomplete name 3, col: 14214 row: []
col: 14217 similar rows:  [14217]
11111111111111111111
hotelname2 [14217]
incomplete name 3, col: 14217 row: [14217]
col: 14218 similar rows:  [14218]
11111111111111111111
incomplete name 3, col: 14218 row: []
col: 14219 similar rows:  [14219]
11111111111111111111
incomplete name 3, col: 14219 row: []
col: 14221 similar rows:  [14221]
11111111111111111111
incomplete name 3, col: 14221 row: []
col: 14225 similar rows:  [14225]
11111111111111111111
incomplete name 3, col: 14225 row: []
col: 14226 similar rows:  [14226, 14359]
incomplete name 3, col: 14226 row: []
col: 14227 similar rows:  [14227]
11111111111111111111
incomplete name 3, col: 14227 row: []
col: 14228 similar rows:  [14228]
11111111111111111111
incomplete name 3, col: 14228 row: []
col: 14230 similar rows:  [14230]
11111111111111111111
incomplete name 3, col: 14230 row: []
col: 14231 similar rows:  [14231, 14574]
incomplete name 3, col: 14231 row: []
col: 14232 similar rows:  [14232]
11111111111111111111
incomplete name 3, col: 14232 row: []
col: 14233 similar rows:  [14233]
11111111111111111111
incomplete name 3, col: 14233 row: []
col: 14235 similar rows:  [14235]
11111111111111111111
incomplete name 3, col: 14235 row: []
col: 14236 similar rows:  [14236]
11111111111111111111
hotelname2 [14236]
incomplete name 3, col: 14236 row: []
col: 14237 similar rows:  [14237, 14595]
incomplete name 3, col: 14237 row: []
col: 14238 similar rows:  [14238]
11111111111111111111
incomplete name 3, col: 14238 row: []
col: 14239 similar rows:  [14239]
11111111111111111111
incomplete name 3, col: 14239 row: []
col: 14240 similar rows:  [14240]
11111111111111111111
incomplete name 3, col: 14240 row: []
col: 14241 similar rows:  [14241]
11111111111111111111
incomplete name 3, col: 14241 row: []
col: 14242 similar rows:  [14242]
11111111111111111111
incomplete name 3, col: 14242 row: []
col: 14243 similar rows:  [14243, 14358]
incomplete name 3, col: 14243 row: []
col: 14244 similar rows:  [14244]
11111111111111111111
incomplete name 3, col: 14244 row: []

col: 14245 similar rows:  [14245]
11111111111111111111
incomplete name 3, col: 14245 row: []
col: 14247 similar rows:  [14247]
11111111111111111111
incomplete name 3, col: 14247 row: []
col: 14248 similar rows:  [14248]
11111111111111111111
incomplete name 3, col: 14248 row: []
col: 14250 similar rows:  [14250]
11111111111111111111
incomplete name 3, col: 14250 row: []
col: 14251 similar rows:  [14251, 14595]
incomplete name 3, col: 14251 row: []
col: 14252 similar rows:  [14252]
11111111111111111111
incomplete name 3, col: 14252 row: []
col: 14256 similar rows:  [14256]
11111111111111111111
incomplete name 3, col: 14256 row: []
col: 14257 similar rows:  [14257]
11111111111111111111
incomplete name 3, col: 14257 row: []
col: 14258 similar rows:  [14258]
11111111111111111111
incomplete name 3, col: 14258 row: []
col: 14260 similar rows:  [14260]
11111111111111111111
hotelname2 [14260]
incomplete name 3, col: 14260 row: [14260]
col: 14261 similar rows:  [14261]
11111111111111111111
incomplete name 3, col: 14261 row: []
col: 14262 similar rows:  [14262, 14670]
incomplete name 3, col: 14262 row: []
col: 14263 similar rows:  [14263]
11111111111111111111
hotelname2 [14263]
wrong name!!!!
incomplete name 3, col: 14263 row: [14263]
col: 14265 similar rows:  [14265, 14563, 14590]
incomplete name 3, col: 14265 row: []
col: 14266 similar rows:  [14266]
11111111111111111111
hotelname2 [14266]
incomplete name 3, col: 14266 row: [14266]
col: 14268 similar rows:  [14268, 14387]
incomplete name 3, col: 14268 row: []
col: 14269 similar rows:  [14269]
11111111111111111111
incomplete name 3, col: 14269 row: []
col: 14271 similar rows:  [14271]
11111111111111111111
incomplete name 3, col: 14271 row: []
col: 14272 similar rows:  [14272, 14703]
incomplete name 3, col: 14272 row: []
col: 14273 similar rows:  [14273]
11111111111111111111
hotelname2 [14273]
incomplete name 3, col: 14273 row: [14273]
col: 14274 similar rows:  [14274, 14410]
incomplete name 3, col: 14274 row: []
col: 14275 similar rows:  [14275]
11111111111111111111
incomplete name 3, col: 14275 row: []
col: 14276 similar rows:  [14276]
11111111111111111111
hotelname2 [14276]
incomplete name 3, col: 14276 row: [14276]
col: 14277 similar rows:  [14277]
11111111111111111111
incomplete name 3, col: 14277 row: []
col: 14280 similar rows:  [14280, 14583]
incomplete name 3, col: 14280 row: []
col: 14281 similar rows:  [14281]
11111111111111111111
incomplete name 3, col: 14281 row: []
col: 14282 similar rows:  [14282]
11111111111111111111
incomplete name 3, col: 14282 row: []
col: 14285 similar rows:  [14285, 14353]
incomplete name 3, col: 14285 row: []
col: 14286 similar rows:  [14286]
11111111111111111111
incomplete name 3, col: 14286 row: []
col: 14287 similar rows:  [14287]
11111111111111111111
incomplete name 3, col: 14287 row: []
col: 14288 similar rows:  [14288, 14443]
incomplete name 3, col: 14288 row: []
col: 14290 similar rows:  [14290]
11111111111111111111
hotelname2 [14290]
wrong name!!!!
incomplete name 3, col: 14290 row: [14290]
col: 14291 similar rows:  [14291, 14559]
incomplete name 3, col: 14291 row: []
col: 14292 similar rows:  [14292]
11111111111111111111
incomplete name 3, col: 14292 row: []
col: 14294 similar rows:  [14294]
11111111111111111111
incomplete name 3, col: 14294 row: []
col: 14295 similar rows:  [14295]
11111111111111111111
hotelname2 [14295]
incomplete name 3, col: 14295 row: []
col: 14297 similar rows:  [14297, 14341, 14786]
incomplete name 3, col: 14297 row: []
col: 14299 similar rows:  [14299]
11111111111111111111
incomplete name 3, col: 14299 row: []
col: 14303 similar rows:  [14303]
11111111111111111111
incomplete name 3, col: 14303 row: []
col: 14306 similar rows:  [14306]
11111111111111111111
incomplete name 3, col: 14306 row: []
col: 14307 similar rows:  [14307]
11111111111111111111
incomplete name 3, col: 14307 row: []
col: 14309 similar rows:  [14309]
11111111111111111111
incomplete name 3, col: 14309 row: []
col: 14311 similar rows:  [14311, 14315, 14622]
incomplete name 3, col: 14311 row: []
col: 14312 similar rows:  [14312]
11111111111111111111
incomplete name 3, col: 14312 row: []
col: 14316 similar rows:  [14316]
11111111111111111111
incomplete name 3, col: 14316 row: []
col: 14317 similar rows:  [14317]
11111111111111111111
incomplete name 3, col: 14317 row: []
col: 14318 similar rows:  [14318]
11111111111111111111
incomplete name 3, col: 14318 row: []
col: 14319 similar rows:  [14319]
11111111111111111111
incomplete name 3, col: 14319 row: []
col: 14320 similar rows:  [14320, 14659]
incomplete name 3, col: 14320 row: []
col: 14322 similar rows:  [14322]
11111111111111111111
incomplete name 3, col: 14322 row: []
col: 14323 similar rows:  [14323]
11111111111111111111
incomplete name 3, col: 14323 row: []
col: 14327 similar rows:  [14327]
11111111111111111111
incomplete name 3, col: 14327 row: []
col: 14328 similar rows:  [14328]
11111111111111111111
incomplete name 3, col: 14328 row: []
col: 14329 similar rows:  [14329]
11111111111111111111
hotelname2 [14329]
incomplete name 3, col: 14329 row: [14329]
col: 14331 similar rows:  [14331]
11111111111111111111
incomplete name 3, col: 14331 row: []
col: 14332 similar rows:  [14332]
11111111111111111111
incomplete name 3, col: 14332 row: []
col: 14333 similar rows:  [14333]
11111111111111111111
incomplete name 3, col: 14333 row: []
col: 14334 similar rows:  [14334]
11111111111111111111
incomplete name 3, col: 14334 row: []
col: 14335 similar rows:  [14335]
11111111111111111111
incomplete name 3, col: 14335 row: []
col: 14336 similar rows:  [14336]
11111111111111111111
incomplete name 3, col: 14336 row: []
col: 14337 similar rows:  [14337, 14468]
incomplete name 3, col: 14337 row: []
col: 14338 similar rows:  [14338, 14549]
incomplete name 3, col: 14338 row: []
col: 14339 similar rows:  [14339]
11111111111111111111
incomplete name 3, col: 14339 row: []
col: 14340 similar rows:  [14340]
11111111111111111111
hotelname2 [14340]
incomplete name 3, col: 14340 row: []
col: 14343 similar rows:  [14343]
11111111111111111111
incomplete name 3, col: 14343 row: []
col: 14345 similar rows:  [14345]
11111111111111111111
incomplete name 3, col: 14345 row: []
col: 14348 similar rows:  [14348]
11111111111111111111
hotelname2 [14348]
incomplete name 3, col: 14348 row: [14348]
col: 14349 similar rows:  [14349]
11111111111111111111
incomplete name 3, col: 14349 row: []
col: 14350 similar rows:  [14350]
11111111111111111111
incomplete name 3, col: 14350 row: []
col: 14355 similar rows:  [14355]
11111111111111111111
hotelname2 [14355]
incomplete name 3, col: 14355 row: [14355]
col: 14356 similar rows:  [14356]
11111111111111111111
incomplete name 3, col: 14356 row: []
col: 14360 similar rows:  [14360]
11111111111111111111
incomplete name 3, col: 14360 row: []
col: 14362 similar rows:  [14362]
11111111111111111111
incomplete name 3, col: 14362 row: []
col: 14363 similar rows:  [14363]
11111111111111111111
hotelname2 [14363]
incomplete name 3, col: 14363 row: []
col: 14364 similar rows:  [14364]
11111111111111111111
incomplete name 3, col: 14364 row: []
col: 14365 similar rows:  [14365]
11111111111111111111
incomplete name 3, col: 14365 row: []
col: 14366 similar rows:  [14366]
11111111111111111111
incomplete name 3, col: 14366 row: []
col: 14367 similar rows:  [14367, 14647]
incomplete name 3, col: 14367 row: []
col: 14368 similar rows:  [14368]
11111111111111111111
incomplete name 3, col: 14368 row: []
col: 14369 similar rows:  [14369]
11111111111111111111
incomplete name 3, col: 14369 row: []
col: 14370 similar rows:  [14370]
11111111111111111111
incomplete name 3, col: 14370 row: []
col: 14371 similar rows:  [14371]
11111111111111111111
incomplete name 3, col: 14371 row: []
col: 14372 similar rows:  [14372]
11111111111111111111
incomplete name 3, col: 14372 row: []
col: 14373 similar rows:  [14373, 14414, 14426]
incomplete name 3, col: 14373 row: []
col: 14374 similar rows:  [14374]
11111111111111111111
incomplete name 3, col: 14374 row: []
col: 14375 similar rows:  [14375]
11111111111111111111
incomplete name 3, col: 14375 row: []
col: 14377 similar rows:  [14377]
11111111111111111111
incomplete name 3, col: 14377 row: []
col: 14379 similar rows:  [14379]
11111111111111111111
hotelname2 [14379]
wrong name!!!!
incomplete name 3, col: 14379 row: [14379]
col: 14380 similar rows:  [14380, 14646]
incomplete name 3, col: 14380 row: []
col: 14382 similar rows:  [14382]
11111111111111111111
incomplete name 3, col: 14382 row: []
col: 14384 similar rows:  [14384]
11111111111111111111
hotelname2 [14384]
incomplete name 3, col: 14384 row: []
col: 14385 similar rows:  [14385]
11111111111111111111
incomplete name 3, col: 14385 row: []
col: 14386 similar rows:  [14386]
11111111111111111111
hotelname2 [14386]
incomplete name 3, col: 14386 row: [14386]
col: 14388 similar rows:  [14388, 14553]
incomplete name 3, col: 14388 row: []
col: 14390 similar rows:  [14390]
11111111111111111111
hotelname2 [14390]
incomplete name 3, col: 14390 row: [14390]
col: 14391 similar rows:  [14391]
11111111111111111111
incomplete name 3, col: 14391 row: []
col: 14393 similar rows:  [14393]
11111111111111111111
incomplete name 3, col: 14393 row: []
col: 14396 similar rows:  [14396]
11111111111111111111
incomplete name 3, col: 14396 row: []
col: 14399 similar rows:  [14399]
11111111111111111111
incomplete name 3, col: 14399 row: []
col: 14403 similar rows:  [14403]
11111111111111111111
incomplete name 3, col: 14403 row: []

col: 14404 similar rows:  [14404]
11111111111111111111
hotelname2 [14404]
incomplete name 3, col: 14404 row: [14404]
col: 14408 similar rows:  [14408]
11111111111111111111
incomplete name 3, col: 14408 row: []
col: 14411 similar rows:  [14411]
11111111111111111111
incomplete name 3, col: 14411 row: []
col: 14412 similar rows:  [14412]
11111111111111111111
incomplete name 3, col: 14412 row: []
col: 14413 similar rows:  [14413]
11111111111111111111
incomplete name 3, col: 14413 row: []
col: 14415 similar rows:  [14415, 14464]
incomplete name 3, col: 14415 row: []
col: 14416 similar rows:  [14416]
11111111111111111111
hotelname2 [14416]
wrong name!!!!
incomplete name 3, col: 14416 row: [14416]
col: 14418 similar rows:  [14418, 14610]
incomplete name 3, col: 14418 row: []
col: 14419 similar rows:  [14419]
11111111111111111111
incomplete name 3, col: 14419 row: []
col: 14422 similar rows:  [14422]
11111111111111111111
incomplete name 3, col: 14422 row: []
col: 14425 similar rows:  [14425]
11111111111111111111
incomplete name 3, col: 14425 row: []
col: 14427 similar rows:  [14427]
11111111111111111111
incomplete name 3, col: 14427 row: []
col: 14428 similar rows:  [14428]
11111111111111111111
incomplete name 3, col: 14428 row: []
col: 14429 similar rows:  [14429]
11111111111111111111
incomplete name 3, col: 14429 row: []
col: 14430 similar rows:  [14430]
11111111111111111111
incomplete name 3, col: 14430 row: []
col: 14431 similar rows:  [14431]
11111111111111111111
incomplete name 3, col: 14431 row: []
col: 14434 similar rows:  [14434]
11111111111111111111
incomplete name 3, col: 14434 row: []
col: 14436 similar rows:  [14436]
11111111111111111111
incomplete name 3, col: 14436 row: []
col: 14437 similar rows:  [14437]
11111111111111111111
incomplete name 3, col: 14437 row: []
col: 14438 similar rows:  [14438]
11111111111111111111
incomplete name 3, col: 14438 row: []
col: 14439 similar rows:  [14439]
11111111111111111111
incomplete name 3, col: 14439 row: []
col: 14440 similar rows:  [14440]
11111111111111111111
incomplete name 3, col: 14440 row: []
col: 14442 similar rows:  [14442]
11111111111111111111
incomplete name 3, col: 14442 row: []
col: 14444 similar rows:  [14444, 14446]
incomplete name 3, col: 14444 row: []
col: 14445 similar rows:  [14445]
11111111111111111111
incomplete name 3, col: 14445 row: []
col: 14448 similar rows:  [14448]
11111111111111111111
incomplete name 3, col: 14448 row: []
col: 14449 similar rows:  [14449, 14603]
incomplete name 3, col: 14449 row: []
col: 14450 similar rows:  [14450, 14612]
incomplete name 3, col: 14450 row: []
col: 14453 similar rows:  [14453]
11111111111111111111
incomplete name 3, col: 14453 row: []
col: 14454 similar rows:  [14454]
11111111111111111111
incomplete name 3, col: 14454 row: []
col: 14455 similar rows:  [14455]
11111111111111111111
incomplete name 3, col: 14455 row: []
col: 14456 similar rows:  [14456, 14667]
incomplete name 3, col: 14456 row: []
col: 14458 similar rows:  [14458]
11111111111111111111
incomplete name 3, col: 14458 row: []
col: 14460 similar rows:  [14460]
11111111111111111111
incomplete name 3, col: 14460 row: []
col: 14461 similar rows:  [14461]
11111111111111111111
incomplete name 3, col: 14461 row: []
col: 14462 similar rows:  [14462]
11111111111111111111
incomplete name 3, col: 14462 row: []
col: 14467 similar rows:  [14467, 14475]
incomplete name 3, col: 14467 row: []
col: 14469 similar rows:  [14469]
11111111111111111111
incomplete name 3, col: 14469 row: []
col: 14472 similar rows:  [14472]
11111111111111111111
hotelname2 [14472]
incomplete name 3, col: 14472 row: []
col: 14473 similar rows:  [14473]
11111111111111111111
incomplete name 3, col: 14473 row: []
col: 14474 similar rows:  [14474]
11111111111111111111
incomplete name 3, col: 14474 row: []
col: 14477 similar rows:  [14477]
11111111111111111111
incomplete name 3, col: 14477 row: []
col: 14478 similar rows:  [14478]
11111111111111111111
incomplete name 3, col: 14478 row: []
col: 14479 similar rows:  [14479]
11111111111111111111
incomplete name 3, col: 14479 row: []
col: 14480 similar rows:  [14480]
11111111111111111111
incomplete name 3, col: 14480 row: []
col: 14481 similar rows:  [14481]
11111111111111111111
incomplete name 3, col: 14481 row: []
col: 14483 similar rows:  [14483]
11111111111111111111
hotelname2 [14483]
incomplete name 3, col: 14483 row: [14483]
col: 14484 similar rows:  [14484]
11111111111111111111
incomplete name 3, col: 14484 row: []
col: 14485 similar rows:  [14485]
11111111111111111111
incomplete name 3, col: 14485 row: []
col: 14488 similar rows:  [14488]
11111111111111111111
incomplete name 3, col: 14488 row: []
col: 14490 similar rows:  [14490]
11111111111111111111
hotelname2 [14490]
incomplete name 3, col: 14490 row: []
col: 14491 similar rows:  [14491]
11111111111111111111
incomplete name 3, col: 14491 row: []
col: 14493 similar rows:  [14493]
11111111111111111111
incomplete name 3, col: 14493 row: []
col: 14494 similar rows:  [14494]
11111111111111111111
incomplete name 3, col: 14494 row: []
col: 14495 similar rows:  [14495]
11111111111111111111
incomplete name 3, col: 14495 row: []
col: 14496 similar rows:  [14496]
11111111111111111111
incomplete name 3, col: 14496 row: []
col: 14497 similar rows:  [14497]
11111111111111111111
incomplete name 3, col: 14497 row: []
col: 14499 similar rows:  [14499]
11111111111111111111
incomplete name 3, col: 14499 row: []
col: 14500 similar rows:  [14500]
11111111111111111111
incomplete name 3, col: 14500 row: []
col: 14501 similar rows:  [14501]
11111111111111111111
incomplete name 3, col: 14501 row: []
col: 14502 similar rows:  [14502]
11111111111111111111
incomplete name 3, col: 14502 row: []
col: 14503 similar rows:  [14503]
11111111111111111111
incomplete name 3, col: 14503 row: []
col: 14505 similar rows:  [14505]
11111111111111111111
incomplete name 3, col: 14505 row: []
col: 14507 similar rows:  [14507, 14508, 14510]
incomplete name 3, col: 14507 row: []
col: 14509 similar rows:  [14509, 14513, 14677, 14681, 14697, 14698]
incomplete name 3, col: 14509 row: []
col: 14511 similar rows:  [14511]
11111111111111111111
incomplete name 3, col: 14511 row: []
col: 14515 similar rows:  [14515]
11111111111111111111
incomplete name 3, col: 14515 row: []
col: 14516 similar rows:  [14516]
11111111111111111111
incomplete name 3, col: 14516 row: []
col: 14518 similar rows:  [14518]
11111111111111111111
incomplete name 3, col: 14518 row: []
col: 14519 similar rows:  [14519, 14694]
incomplete name 3, col: 14519 row: []
col: 14520 similar rows:  [14520]
11111111111111111111
hotelname2 [14520]
incomplete name 3, col: 14520 row: [14520]
col: 14521 similar rows:  [14521]
11111111111111111111
incomplete name 3, col: 14521 row: []
col: 14523 similar rows:  [14523]
11111111111111111111
hotelname2 [14523]
incomplete name 3, col: 14523 row: [14523]
col: 14525 similar rows:  [14525]
11111111111111111111
incomplete name 3, col: 14525 row: []
col: 14526 similar rows:  [14526]
11111111111111111111
incomplete name 3, col: 14526 row: []
col: 14527 similar rows:  [14527]
11111111111111111111
incomplete name 3, col: 14527 row: []
col: 14528 similar rows:  [14528]
11111111111111111111
incomplete name 3, col: 14528 row: []
col: 14530 similar rows:  [14530]
11111111111111111111
incomplete name 3, col: 14530 row: []
col: 14531 similar rows:  [14531]
11111111111111111111
incomplete name 3, col: 14531 row: []
col: 14533 similar rows:  [14533]
11111111111111111111
hotelname2 [14533]
incomplete name 3, col: 14533 row: [14533]
col: 14535 similar rows:  [14535]
11111111111111111111
incomplete name 3, col: 14535 row: []
col: 14536 similar rows:  [14536]
11111111111111111111
incomplete name 3, col: 14536 row: []
col: 14537 similar rows:  [14537]
11111111111111111111
incomplete name 3, col: 14537 row: []
col: 14538 similar rows:  []
00000000000000000000
                                 planner_id  \
14538  1961c5b5-0f16-40c4-9b30-4708f370224a

                                 wedding_id hotel hotel_id merged
14538  a2ac786d-3d9f-4bef-b488-21086ccd4ead     。     None      。
hotelname2 [14538]
wrong name!!!!
incomplete name 3, col: 14538 row: [14538]
col: 14539 similar rows:  [14539]
11111111111111111111
incomplete name 3, col: 14539 row: []
col: 14541 similar rows:  [14541]
11111111111111111111
incomplete name 3, col: 14541 row: []

col: 14542 similar rows:  [14542, 14760]
incomplete name 3, col: 14542 row: []
col: 14543 similar rows:  [14543]
11111111111111111111
incomplete name 3, col: 14543 row: []
col: 14544 similar rows:  [14544]
11111111111111111111
incomplete name 3, col: 14544 row: []
col: 14545 similar rows:  [14545]
11111111111111111111
incomplete name 3, col: 14545 row: []
col: 14546 similar rows:  [14546]
11111111111111111111
incomplete name 3, col: 14546 row: []
col: 14547 similar rows:  [14547]
11111111111111111111
incomplete name 3, col: 14547 row: []
col: 14548 similar rows:  [14548]
11111111111111111111
incomplete name 3, col: 14548 row: []
col: 14551 similar rows:  [14551]
11111111111111111111
incomplete name 3, col: 14551 row: []
col: 14554 similar rows:  [14554, 14782]
incomplete name 3, col: 14554 row: []
col: 14555 similar rows:  [14555]
11111111111111111111
incomplete name 3, col: 14555 row: []
col: 14557 similar rows:  [14557]
11111111111111111111
incomplete name 3, col: 14557 row: []
col: 14560 similar rows:  [14560]
11111111111111111111
incomplete name 3, col: 14560 row: []
col: 14561 similar rows:  [14561, 14639]
incomplete name 3, col: 14561 row: []
col: 14562 similar rows:  [14562]
11111111111111111111
incomplete name 3, col: 14562 row: []
col: 14564 similar rows:  [14564, 14762]
incomplete name 3, col: 14564 row: []
col: 14566 similar rows:  [14566]
11111111111111111111
incomplete name 3, col: 14566 row: []
col: 14570 similar rows:  [14570]
11111111111111111111
incomplete name 3, col: 14570 row: []
col: 14575 similar rows:  [14575]
11111111111111111111
hotelname2 [14575]
wrong name!!!!
incomplete name 3, col: 14575 row: [14575]
col: 14576 similar rows:  [14576]
11111111111111111111
incomplete name 3, col: 14576 row: []
col: 14580 similar rows:  [14580]
11111111111111111111
hotelname2 [14580]
incomplete name 3, col: 14580 row: [14580]
col: 14581 similar rows:  [14581]
11111111111111111111
incomplete name 3, col: 14581 row: []
col: 14584 similar rows:  [14584]
11111111111111111111
hotelname2 [14584]
incomplete name 3, col: 14584 row: [14584]
col: 14589 similar rows:  [14589]
11111111111111111111
hotelname2 [14589]
incomplete name 3, col: 14589 row: [14589]
col: 14593 similar rows:  [14593]
11111111111111111111
hotelname2 [14593]
wrong name!!!!
incomplete name 3, col: 14593 row: [14593]
col: 14594 similar rows:  [14594]
11111111111111111111
incomplete name 3, col: 14594 row: []
col: 14597 similar rows:  [14597]
11111111111111111111
incomplete name 3, col: 14597 row: []
col: 14598 similar rows:  [14598]
11111111111111111111
incomplete name 3, col: 14598 row: []
col: 14601 similar rows:  [14601]
11111111111111111111
incomplete name 3, col: 14601 row: []
col: 14602 similar rows:  [14602]
11111111111111111111
incomplete name 3, col: 14602 row: []
col: 14604 similar rows:  [14604]
11111111111111111111
hotelname2 [14604]
incomplete name 3, col: 14604 row: [14604]
col: 14609 similar rows:  [14609, 14654, 14716]
incomplete name 3, col: 14609 row: []
col: 14611 similar rows:  [14611]
11111111111111111111
incomplete name 3, col: 14611 row: []
col: 14613 similar rows:  [14613]
11111111111111111111
incomplete name 3, col: 14613 row: []
col: 14614 similar rows:  [14614]
11111111111111111111
incomplete name 3, col: 14614 row: []
col: 14615 similar rows:  [14615]
11111111111111111111
incomplete name 3, col: 14615 row: []
col: 14616 similar rows:  [14616]
11111111111111111111
incomplete name 3, col: 14616 row: []
col: 14619 similar rows:  [14619]
11111111111111111111
incomplete name 3, col: 14619 row: []
col: 14620 similar rows:  [14620]
11111111111111111111
incomplete name 3, col: 14620 row: []
col: 14621 similar rows:  [14621]
11111111111111111111
incomplete name 3, col: 14621 row: []
col: 14623 similar rows:  [14623]
11111111111111111111
incomplete name 3, col: 14623 row: []
col: 14625 similar rows:  [14625, 14648, 14744]
incomplete name 3, col: 14625 row: []
col: 14627 similar rows:  [14627]
11111111111111111111
hotelname2 [14627]
incomplete name 3, col: 14627 row: [14627]
col: 14628 similar rows:  [14628]
11111111111111111111
incomplete name 3, col: 14628 row: []
col: 14629 similar rows:  [14629]
11111111111111111111
incomplete name 3, col: 14629 row: []
col: 14630 similar rows:  [14630]
11111111111111111111
incomplete name 3, col: 14630 row: []
col: 14633 similar rows:  [14633]
11111111111111111111
hotelname2 [14633]
incomplete name 3, col: 14633 row: [14633]
col: 14636 similar rows:  [14636]
11111111111111111111
incomplete name 3, col: 14636 row: []
col: 14637 similar rows:  [14637]
11111111111111111111
hotelname2 [14637]
wrong name!!!!
incomplete name 3, col: 14637 row: [14637]
col: 14638 similar rows:  [14638]
11111111111111111111
incomplete name 3, col: 14638 row: []
col: 14640 similar rows:  [14640]
11111111111111111111
incomplete name 3, col: 14640 row: []
col: 14641 similar rows:  [14641]
11111111111111111111
incomplete name 3, col: 14641 row: []
col: 14642 similar rows:  [14642]
11111111111111111111
hotelname2 [14642]
incomplete name 3, col: 14642 row: [14642]
col: 14643 similar rows:  [14643]
11111111111111111111
incomplete name 3, col: 14643 row: []
col: 14644 similar rows:  [14644]
11111111111111111111
incomplete name 3, col: 14644 row: []
col: 14649 similar rows:  [14649]
11111111111111111111
incomplete name 3, col: 14649 row: []
col: 14650 similar rows:  [14650]
11111111111111111111
incomplete name 3, col: 14650 row: []
col: 14652 similar rows:  [14652, 14707]
incomplete name 3, col: 14652 row: []
col: 14653 similar rows:  [14653]
11111111111111111111
incomplete name 3, col: 14653 row: []
col: 14655 similar rows:  [14655]
11111111111111111111
incomplete name 3, col: 14655 row: []
col: 14656 similar rows:  [14656]
11111111111111111111
incomplete name 3, col: 14656 row: []
col: 14658 similar rows:  [14658]
11111111111111111111
hotelname2 [14658]
incomplete name 3, col: 14658 row: [14658]
col: 14662 similar rows:  [14662]
11111111111111111111
incomplete name 3, col: 14662 row: []
col: 14663 similar rows:  [14663]
11111111111111111111
hotelname2 [14663]
incomplete name 3, col: 14663 row: []
col: 14664 similar rows:  [14664]
11111111111111111111
incomplete name 3, col: 14664 row: []
col: 14666 similar rows:  [14666]
11111111111111111111
hotelname2 [14666]
wrong name!!!!
incomplete name 3, col: 14666 row: [14666]
col: 14668 similar rows:  [14668]
11111111111111111111
incomplete name 3, col: 14668 row: []
col: 14669 similar rows:  [14669]
11111111111111111111
incomplete name 3, col: 14669 row: []
col: 14671 similar rows:  [14671]
11111111111111111111
hotelname2 [14671]
incomplete name 3, col: 14671 row: []
col: 14672 similar rows:  [14672]
11111111111111111111
incomplete name 3, col: 14672 row: []
col: 14673 similar rows:  [14673, 14679, 14693]
incomplete name 3, col: 14673 row: []
col: 14675 similar rows:  [14675]
11111111111111111111
incomplete name 3, col: 14675 row: []
col: 14676 similar rows:  [14676]
11111111111111111111
incomplete name 3, col: 14676 row: []
col: 14678 similar rows:  [14678]
11111111111111111111
incomplete name 3, col: 14678 row: []
col: 14680 similar rows:  [14680, 14695]
incomplete name 3, col: 14680 row: []
col: 14682 similar rows:  [14682]
11111111111111111111
hotelname2 [14682]
incomplete name 3, col: 14682 row: [14682]
col: 14683 similar rows:  [14683, 14684]
incomplete name 3, col: 14683 row: []
col: 14685 similar rows:  [14685]
11111111111111111111
incomplete name 3, col: 14685 row: []
col: 14686 similar rows:  [14686]
11111111111111111111
incomplete name 3, col: 14686 row: []
col: 14687 similar rows:  [14687]
11111111111111111111
incomplete name 3, col: 14687 row: []
col: 14688 similar rows:  [14688]
11111111111111111111
incomplete name 3, col: 14688 row: []
col: 14689 similar rows:  [14689]
11111111111111111111
incomplete name 3, col: 14689 row: []
col: 14690 similar rows:  [14690]
11111111111111111111
incomplete name 3, col: 14690 row: []
col: 14692 similar rows:  [14692]
11111111111111111111
incomplete name 3, col: 14692 row: []
col: 14699 similar rows:  [14699]
11111111111111111111
incomplete name 3, col: 14699 row: []
col: 14700 similar rows:  [14700]
11111111111111111111
incomplete name 3, col: 14700 row: []
col: 14701 similar rows:  [14701]
11111111111111111111
hotelname2 [14701]
incomplete name 3, col: 14701 row: [14701]
col: 14702 similar rows:  [14702]
11111111111111111111
incomplete name 3, col: 14702 row: []
col: 14705 similar rows:  [14705]
11111111111111111111
incomplete name 3, col: 14705 row: []
col: 14708 similar rows:  [14708]
11111111111111111111
incomplete name 3, col: 14708 row: []
col: 14709 similar rows:  [14709]
11111111111111111111
incomplete name 3, col: 14709 row: []
col: 14710 similar rows:  [14710]
11111111111111111111
hotelname2 [14710]
incomplete name 3, col: 14710 row: [14710]
col: 14714 similar rows:  [14714]
11111111111111111111
incomplete name 3, col: 14714 row: []

col: 14718 similar rows:  [14718]
11111111111111111111
hotelname2 [14718]
incomplete name 3, col: 14718 row: []
col: 14720 similar rows:  [14720]
11111111111111111111
incomplete name 3, col: 14720 row: []
col: 14721 similar rows:  [14721]
11111111111111111111
incomplete name 3, col: 14721 row: []
col: 14722 similar rows:  [14722]
11111111111111111111
incomplete name 3, col: 14722 row: []
col: 14723 similar rows:  [14723]
11111111111111111111
hotelname2 [14723]
incomplete name 3, col: 14723 row: [14723]
col: 14724 similar rows:  [14724]
11111111111111111111
incomplete name 3, col: 14724 row: []
col: 14726 similar rows:  [14726]
11111111111111111111
incomplete name 3, col: 14726 row: []
col: 14729 similar rows:  [14729]
11111111111111111111
incomplete name 3, col: 14729 row: []
col: 14730 similar rows:  [14730]
11111111111111111111
incomplete name 3, col: 14730 row: []
col: 14731 similar rows:  [14731]
11111111111111111111
incomplete name 3, col: 14731 row: []
col: 14732 similar rows:  [14732]
11111111111111111111
incomplete name 3, col: 14732 row: []
col: 14733 similar rows:  [14733]
11111111111111111111
incomplete name 3, col: 14733 row: []
col: 14734 similar rows:  [14734]
11111111111111111111
incomplete name 3, col: 14734 row: []
col: 14736 similar rows:  [14736]
11111111111111111111
incomplete name 3, col: 14736 row: []
col: 14737 similar rows:  [14737]
11111111111111111111
hotelname2 [14737]
incomplete name 3, col: 14737 row: [14737]
col: 14738 similar rows:  [14738]
11111111111111111111
hotelname2 [14738]
incomplete name 3, col: 14738 row: [14738]
col: 14739 similar rows:  [14739]
11111111111111111111
hotelname2 [14739]
incomplete name 3, col: 14739 row: [14739]
col: 14740 similar rows:  [14740]
11111111111111111111
incomplete name 3, col: 14740 row: []
col: 14743 similar rows:  [14743, 14758, 14774]
incomplete name 3, col: 14743 row: []
col: 14746 similar rows:  [14746]
11111111111111111111
incomplete name 3, col: 14746 row: []
col: 14747 similar rows:  [14747]
11111111111111111111
incomplete name 3, col: 14747 row: []
col: 14748 similar rows:  [14748]
11111111111111111111
incomplete name 3, col: 14748 row: []
col: 14750 similar rows:  [14750, 14781]
incomplete name 3, col: 14750 row: []
col: 14751 similar rows:  [14751]
11111111111111111111
incomplete name 3, col: 14751 row: []
col: 14752 similar rows:  [14752]
11111111111111111111
incomplete name 3, col: 14752 row: []
col: 14753 similar rows:  [14753]
11111111111111111111
incomplete name 3, col: 14753 row: []
col: 14755 similar rows:  [14755]
11111111111111111111
hotelname2 [14755]
incomplete name 3, col: 14755 row: []
col: 14756 similar rows:  [14756]
11111111111111111111
incomplete name 3, col: 14756 row: []
col: 14757 similar rows:  [14757]
11111111111111111111
incomplete name 3, col: 14757 row: []
col: 14759 similar rows:  [14759]
11111111111111111111
incomplete name 3, col: 14759 row: []
col: 14763 similar rows:  [14763]
11111111111111111111
incomplete name 3, col: 14763 row: []
col: 14766 similar rows:  [14766]
11111111111111111111
hotelname2 [14766]
incomplete name 3, col: 14766 row: []
col: 14767 similar rows:  [14767]
11111111111111111111
incomplete name 3, col: 14767 row: []
col: 14768 similar rows:  [14768]
11111111111111111111
incomplete name 3, col: 14768 row: []
col: 14769 similar rows:  [14769]
11111111111111111111
hotelname2 [14769]
incomplete name 3, col: 14769 row: [14769]
col: 14770 similar rows:  [14770]
11111111111111111111
incomplete name 3, col: 14770 row: []
col: 14771 similar rows:  [14771]
11111111111111111111
incomplete name 3, col: 14771 row: []
col: 14772 similar rows:  [14772]
11111111111111111111
incomplete name 3, col: 14772 row: []
col: 14773 similar rows:  [14773]
11111111111111111111
incomplete name 3, col: 14773 row: []
col: 14775 similar rows:  [14775]
11111111111111111111
incomplete name 3, col: 14775 row: []
col: 14777 similar rows:  [14777]
11111111111111111111
incomplete name 3, col: 14777 row: []
col: 14779 similar rows:  [14779]
11111111111111111111
incomplete name 3, col: 14779 row: []
col: 14780 similar rows:  [14780]
11111111111111111111
incomplete name 3, col: 14780 row: []
col: 14784 similar rows:  [14784]
11111111111111111111
incomplete name 3, col: 14784 row: []
col: 14787 similar rows:  [14787]
11111111111111111111
incomplete name 3, col: 14787 row: []
end
col: 2648 similar rows:  [2648]
11111111111111111111
hotelname2 [2648]
incomplete name 3, col: 2648 row: [2648]
col: 14788 similar rows:  [14788]
11111111111111111111
incomplete name 3, col: 14788 row: []
end
col: 2649 similar rows:  [2649]
11111111111111111111
incomplete name 3, col: 2649 row: []
end
col: 2650 similar rows:  [2650, 2754, 2875, 3130, 3245, 3248, 3475, 3820, 15036, 15044]
incomplete name 3, col: 2650 row: []
col: 2651 similar rows:  [2651, 2800, 2821, 2833, 2836, 2846, 2857, 2890, 2932, 2945, 3048, 3085, 3086, 3106, 3259, 3261, 3268, 3275, 3299, 3454, 3456, 3472, 3525, 3538, 3548, 3555, 3599, 3830, 4146, 14820, 14945, 15018, 15019, 15033, 15034, 15074, 15077, 15203]
incomplete name 3, col: 2651 row: []
col: 2652 similar rows:  [2652, 2678, 2686, 2698, 2704, 2714, 2736, 2787, 2792, 2795, 2796, 2812, 2815, 2819, 2823, 2839, 2841, 2848, 2876, 2887, 2891, 2907, 2910, 2939, 2943, 2971, 2990, 3030, 3045, 3049, 3104, 3119, 3172, 3205, 3280, 3350, 3358, 3492, 3498, 3500, 3530, 3539, 3549, 3550, 3559, 3568, 3571, 3580, 3582, 3600, 3720, 3729, 3731, 3789, 3814, 3816, 3858, 3908, 3924, 3940, 4137, 14849, 14913, 15187]
incomplete name 3, col: 2652 row: []
col: 2653 similar rows:  [2653, 2904, 3293, 3303, 3558, 14962, 15097]
incomplete name 3, col: 2653 row: []
col: 2654 similar rows:  [2654]
11111111111111111111
hotelname2 [2654]
incomplete name 3, col: 2654 row: [2654]
col: 2655 similar rows:  [2655]
11111111111111111111
incomplete name 3, col: 2655 row: []
col: 2656 similar rows:  [2656, 2668, 2672, 2685, 2702, 2719, 2731, 2785, 2843, 2851, 2853, 2861, 2863, 2867, 2916, 2923, 2928, 2951, 2960, 2963, 2967, 2968, 2969, 2980, 2987, 3008, 3017, 3043, 3067, 3079, 3099, 3109, 3113, 3123, 3126, 3142, 3145, 3150, 3154, 3185, 3196, 3201, 3263, 3266, 3302, 3344, 3409, 3462, 3463, 3470, 3477, 3478, 3523, 3554, 3563, 3583, 3594, 3603, 3641, 3676, 3683, 3685, 3693, 3714, 3769, 3796, 3818, 3841, 3898, 3939, 3965, 4011, 4128, 4133, 4167, 4193, 14813, 14818, 14993, 15003, 15126, 15181, 15200, 15214, 15229]
incomplete name 3, col: 2656 row: []
col: 2657 similar rows:  [2657, 2671, 2838, 2894, 2897, 2914, 2915, 2921, 2940, 2956, 3098, 3148, 3158, 3208, 3251, 3338, 3508, 3537, 3597, 3608, 3713, 3840, 4046]
incomplete name 3, col: 2657 row: []
col: 2658 similar rows:  [2658, 2713, 2728, 2746, 3032, 3152, 3197, 3200, 3207, 3209, 3502, 3520, 3534, 3540, 3636, 3665, 3726, 3905, 3933, 3945, 4115, 14894, 15042, 15100, 15151]
incomplete name 3, col: 2658 row: []
col: 2659 similar rows:  [2659, 2695, 2799, 2880, 2918, 2953, 2962, 3133, 3257, 3273, 3277, 3300, 3309, 3394, 3476, 3481, 3490, 3529, 3551, 14825, 15035, 15049, 15176]
incomplete name 3, col: 2659 row: []
col: 2660 similar rows:  [2660, 2691, 2789, 2794, 3040, 3116, 3132, 3153, 3169, 3170, 3177, 3188, 3507, 3519, 3585, 3609, 3821, 4118, 4139, 14953, 15213]
incomplete name 3, col: 2660 row: []
col: 2661 similar rows:  [2661, 2694, 2798, 2856, 2942, 3050, 3066, 3091, 3304, 3460, 3471, 3532, 3547, 3560, 3576, 3598, 3923, 15135]
incomplete name 3, col: 2661 row: []
col: 2662 similar rows:  [2662, 2829, 2896, 3103, 3171, 3211, 3246, 3249, 3267, 3288, 3295, 3466, 3828, 3917, 3946]
incomplete name 3, col: 2662 row: []
col: 2663 similar rows:  [2663, 2683, 2696, 2750, 2826, 2831, 2835, 2895, 2911, 2966, 2970, 3124, 3157, 3453, 3461, 3621, 3712, 3718, 3854, 3931, 3932, 3978, 4006, 4017, 4105]
incomplete name 3, col: 2663 row: []
col: 2664 similar rows:  [2664, 2810, 3108, 3111, 3212, 3276, 3648, 3742, 3829, 3911, 3922, 4058, 4097, 14902]
incomplete name 3, col: 2664 row: []
col: 2665 similar rows:  [2665]
11111111111111111111
incomplete name 3, col: 2665 row: []
col: 2666 similar rows:  [2666, 3732, 3825]
incomplete name 3, col: 2666 row: []
col: 2667 similar rows:  [2667, 2680, 2682, 2786, 2814, 2817, 2845, 2852, 3136, 3255, 3260, 3271, 3272, 3451, 3455, 3483, 3528, 3543, 3569, 3570, 3710, 3822, 3957]
incomplete name 3, col: 2667 row: []
col: 2669 similar rows:  [2669]
11111111111111111111
incomplete name 3, col: 2669 row: []
col: 2670 similar rows:  [2670, 2925, 3838]
incomplete name 3, col: 2670 row: []
col: 2673 similar rows:  [2673]
11111111111111111111
incomplete name 3, col: 2673 row: []

col: 2674 similar rows:  [2674, 2909, 3198, 3330, 3505, 3724, 3730, 3735, 3761, 3839, 3919, 4120, 4127]
incomplete name 3, col: 2674 row: []
col: 2675 similar rows:  [2675, 2935, 3084, 3129, 3146, 3488, 3493, 3575, 3844, 3862, 3872, 3883, 3944, 3952, 3992, 4026, 4140, 4141, 4190, 14804, 14840, 14970, 15094, 15140, 15178]
incomplete name 3, col: 2675 row: []
col: 2676 similar rows:  [2676, 2687, 2705, 2807, 2809, 2822, 2855, 2900, 3131, 3292, 3484, 3518, 3522, 3535, 3546, 3557, 3574, 3579, 3591, 3593, 3596, 3650, 3815, 3826, 3877]
incomplete name 3, col: 2676 row: []
col: 2677 similar rows:  [2677]
11111111111111111111
hotelname2 [2677]
incomplete name 3, col: 2677 row: []
col: 2679 similar rows:  [2679]
11111111111111111111
incomplete name 3, col: 2679 row: []
col: 2681 similar rows:  [2681, 2825, 3014, 3039, 3149, 3317, 3321, 3391, 3444, 3586, 3690, 3910, 3921, 3935, 4028, 14809, 14857, 15121]
incomplete name 3, col: 2681 row: []
col: 2684 similar rows:  [2684, 2692, 3184]
incomplete name 3, col: 2684 row: []
col: 2688 similar rows:  [2688, 3000]
incomplete name 3, col: 2688 row: []
col: 2689 similar rows:  [2689, 3178, 3206, 3237, 3855, 3859, 3893, 4020, 4024, 4048, 4070, 4197, 4219, 14892, 14933, 14941, 14997, 15079, 15085]
incomplete name 3, col: 2689 row: []
col: 2690 similar rows:  [2690, 2703, 2816, 2885, 2899, 2941, 3258, 3265, 3286, 3467, 3473, 3566, 3926, 4042]
incomplete name 3, col: 2690 row: []
col: 2693 similar rows:  [2693]
11111111111111111111
incomplete name 3, col: 2693 row: []
col: 2697 similar rows:  [2697, 2847, 3284, 3364, 3486, 3842]
incomplete name 3, col: 2697 row: []
col: 2699 similar rows:  [2699, 2721, 2760, 2763, 2827, 2828, 2830, 2832, 2938, 2973, 2974, 2976, 3107, 3120, 3161, 3193, 3199, 3254, 3256, 3279, 3293, 3297, 3303, 3485, 3489, 3527, 3531, 3544, 3602, 3604, 3610, 3846, 4119, 14803, 14962, 15031, 15097]
incomplete name 3, col: 2699 row: []
col: 2700 similar rows:  [2700, 2801, 3741]
incomplete name 3, col: 2700 row: []
col: 2701 similar rows:  [2701]
11111111111111111111
incomplete name 3, col: 2701 row: []
col: 2706 similar rows:  [2706, 2811, 2818, 2854, 2884, 2903, 2913, 2948, 2949, 2995, 3033, 3059, 3095, 3140, 3147, 3306, 3378, 3465, 3468, 3487, 3513, 3545, 3567, 3577, 3605, 3613, 3625, 3698, 3705, 3843, 3888, 3909, 4045, 14861, 14938, 14961, 14985, 15043, 15045, 15047, 15165, 15172, 15225]
incomplete name 3, col: 2706 row: []
col: 2707 similar rows:  [2707, 2718, 2740, 2743, 2761, 2930, 2944, 3069, 3075, 3089, 3166, 3174, 3202, 3220, 3294, 3336, 3340, 3341, 3351, 3356, 3504, 3552, 3553, 3561, 3562, 3581, 3643, 3657, 3711, 3722, 3728, 3734, 3836, 3849, 3850, 3930, 3936, 4130, 4208, 14888, 14957, 15152, 15231, 15254]
incomplete name 3, col: 2707 row: []
col: 2708 similar rows:  [2708, 2985, 4061, 4145, 15007]
incomplete name 3, col: 2708 row: []
col: 2709 similar rows:  [2709, 2722, 2749, 2793, 2927, 2937, 2954, 2996, 3021, 3057, 3071, 3134, 3141, 3175, 3269, 3366, 3368, 3379, 3439, 3491, 3495, 3541, 3578, 3584, 3589, 3612, 3632, 3684, 3687, 3708, 3783, 3792, 3794, 3804, 3835, 3852, 3885, 3927, 4116, 14939, 15002, 15038, 15096, 15101, 15173, 15212, 15217, 15224, 15245]
incomplete name 3, col: 2709 row: []
col: 2710 similar rows:  [2710, 3889, 14882, 14911, 15183]
incomplete name 3, col: 2710 row: []
col: 2711 similar rows:  [2711, 3441, 3766, 15054, 15107, 15147]
incomplete name 3, col: 2711 row: []
col: 2712 similar rows:  [2712]
11111111111111111111
incomplete name 3, col: 2712 row: []
col: 2715 similar rows:  [2715, 3756, 4158, 15066, 15258]
incomplete name 3, col: 2715 row: []
col: 2716 similar rows:  [2716, 2830, 3107, 3293, 3303, 3527, 3846, 4119, 14962, 14965, 15097]
incomplete name 3, col: 2716 row: []
col: 2717 similar rows:  [2717]
11111111111111111111
incomplete name 3, col: 2717 row: []
col: 2720 similar rows:  [2720]
11111111111111111111
incomplete name 3, col: 2720 row: []
col: 2723 similar rows:  [2723, 2990, 3030, 3497, 3643, 3657, 3809, 14793, 14947, 15037, 15166]
incomplete name 3, col: 2723 row: []
col: 2724 similar rows:  [2724, 3044, 3323, 14980, 15210]
incomplete name 3, col: 2724 row: []
col: 2725 similar rows:  [2725, 3651, 14942]
incomplete name 3, col: 2725 row: []
col: 2726 similar rows:  [2726, 3002]
incomplete name 3, col: 2726 row: []
col: 2727 similar rows:  [2727]
11111111111111111111
incomplete name 3, col: 2727 row: []
col: 2729 similar rows:  [2729, 3056, 15237]
incomplete name 3, col: 2729 row: []
col: 2730 similar rows:  [2730, 2759, 2765, 2775, 3019, 3024, 3070, 3082, 3233, 3422, 3981, 3995, 4182, 4186, 14856, 14900, 14959, 14960, 14967, 14976, 15091, 15116, 15155, 15198]
incomplete name 3, col: 2730 row: []
col: 2732 similar rows:  [2732, 3406, 3643, 3657, 14855]
incomplete name 3, col: 2732 row: []
col: 2733 similar rows:  [2733, 14915]
incomplete name 3, col: 2733 row: []
col: 2734 similar rows:  [2734, 2837, 2893, 2905, 2908, 2975, 3042, 3144, 3155, 3162, 3163, 3179, 3194, 3204, 3216, 3333, 3334, 3361, 3413, 3686, 3697, 3778, 3892, 3986, 4010, 4018, 4131, 4195, 4217, 14817, 14845, 15009, 15220, 15228, 15236]
incomplete name 3, col: 2734 row: []
col: 2735 similar rows:  [2735, 2808, 2844, 2898, 3025, 3047, 3127, 3181, 3335, 3345, 3572, 3606, 3824, 3833, 3956, 4019, 4122, 4200, 14835, 14936, 15103, 15134]
incomplete name 3, col: 2735 row: []
col: 2737 similar rows:  [2737, 3427]
incomplete name 3, col: 2737 row: []
col: 2738 similar rows:  [2738, 2741, 2742, 2803, 2834, 3203, 3319, 3376, 3443, 3446, 3631, 3750, 3860, 14886, 14895, 14924, 15093, 15169, 15170, 15209]
incomplete name 3, col: 2738 row: []
col: 2739 similar rows:  [2739, 2779, 3706, 3958, 4073, 4199, 14875, 14893, 14899, 15016, 15027, 15123, 15125, 15149]
incomplete name 3, col: 2739 row: []
col: 2744 similar rows:  [2744, 3101, 3183, 3226, 3229, 3301, 3464, 3592, 3678, 3694, 3955, 3971, 4036, 4055, 4150, 14872, 15020, 15102, 15113, 15199, 15221, 15230]
incomplete name 3, col: 2744 row: []
col: 2745 similar rows:  [2745, 3077, 3797, 4039, 4076, 15137]
incomplete name 3, col: 2745 row: []
col: 2747 similar rows:  [2747]
11111111111111111111
incomplete name 3, col: 2747 row: []
col: 2748 similar rows:  [2748]
11111111111111111111
hotelname2 [2748]
incomplete name 3, col: 2748 row: [2748]
col: 2751 similar rows:  [2751, 3777, 4034, 15099, 15106]
incomplete name 3, col: 2751 row: []
col: 2752 similar rows:  [2752, 3225]
incomplete name 3, col: 2752 row: []
col: 2753 similar rows:  [2753, 15259]
incomplete name 3, col: 2753 row: []
col: 2755 similar rows:  [2755]
11111111111111111111
incomplete name 3, col: 2755 row: []
col: 2756 similar rows:  [2756, 3222, 14844]
incomplete name 3, col: 2756 row: []
col: 2757 similar rows:  [2757]
11111111111111111111
incomplete name 3, col: 2757 row: []
col: 2758 similar rows:  [2758]
11111111111111111111
incomplete name 3, col: 2758 row: []
col: 2762 similar rows:  [2762, 3950, 4093]
incomplete name 3, col: 2762 row: []
col: 2764 similar rows:  [2764, 14802]
incomplete name 3, col: 2764 row: []
col: 2766 similar rows:  [2766, 4094]
incomplete name 3, col: 2766 row: []
col: 2767 similar rows:  [2767]
11111111111111111111
incomplete name 3, col: 2767 row: []
col: 2768 similar rows:  [2768, 2776]
incomplete name 3, col: 2768 row: []
col: 2769 similar rows:  [2769]
11111111111111111111
incomplete name 3, col: 2769 row: []
col: 2770 similar rows:  [2770]
11111111111111111111
incomplete name 3, col: 2770 row: []
col: 2771 similar rows:  [2771, 15001]
incomplete name 3, col: 2771 row: []
col: 2772 similar rows:  [2772]
11111111111111111111
incomplete name 3, col: 2772 row: []
col: 2773 similar rows:  [2773]
11111111111111111111
incomplete name 3, col: 2773 row: []
col: 2774 similar rows:  [2774]
11111111111111111111
incomplete name 3, col: 2774 row: []
col: 2777 similar rows:  [2777, 15241]
incomplete name 3, col: 2777 row: []
col: 2778 similar rows:  [2778, 15228, 15239]
incomplete name 3, col: 2778 row: []
col: 2780 similar rows:  [2780]
11111111111111111111
incomplete name 3, col: 2780 row: []
col: 2781 similar rows:  [2781, 2972, 15118]
hotelname2 [15118]
incomplete name 3, col: 2781 row: [15118]
col: 2782 similar rows:  [2782, 2791, 2929, 3448, 3634, 3827, 3997, 4123, 4191, 14912, 15008]
incomplete name 3, col: 2782 row: []
col: 2783 similar rows:  [2783]
11111111111111111111
incomplete name 3, col: 2783 row: []
col: 2784 similar rows:  [2784]
11111111111111111111
incomplete name 3, col: 2784 row: []

col: 2788 similar rows:  [2788]
11111111111111111111
incomplete name 3, col: 2788 row: []
col: 2790 similar rows:  [2790, 2813, 2842, 3176, 3321, 3444, 3573, 3587, 3845, 4032]
incomplete name 3, col: 2790 row: []
col: 2797 similar rows:  [2797]
11111111111111111111
incomplete name 3, col: 2797 row: []
col: 2802 similar rows:  [2802]
11111111111111111111
incomplete name 3, col: 2802 row: []
col: 2804 similar rows:  [2804, 2922, 3074, 3159, 3363, 3857, 3959, 14978, 15196]
incomplete name 3, col: 2804 row: []
col: 2805 similar rows:  [2805, 3156, 3369, 3374, 3834, 3906, 3974, 4008, 4090, 4203]
incomplete name 3, col: 2805 row: []
col: 2806 similar rows:  [2806]
11111111111111111111
hotelname2 [2806]
incomplete name 3, col: 2806 row: [2806]
col: 2820 similar rows:  [2820]
11111111111111111111
incomplete name 3, col: 2820 row: []
col: 2824 similar rows:  [2824]
11111111111111111111
incomplete name 3, col: 2824 row: []
col: 2840 similar rows:  [2840, 2892, 3097]
incomplete name 3, col: 2840 row: []
col: 2849 similar rows:  [2849, 2978, 3315]
incomplete name 3, col: 2849 row: []
col: 2850 similar rows:  [2850, 14843]
incomplete name 3, col: 2850 row: []
col: 2858 similar rows:  [2858, 2859, 3217, 3218, 4166]
incomplete name 3, col: 2858 row: []
col: 2860 similar rows:  [2860, 3040, 15213]
incomplete name 3, col: 2860 row: []
col: 2862 similar rows:  [2862]
11111111111111111111
incomplete name 3, col: 2862 row: []
col: 2864 similar rows:  [2864]
11111111111111111111
incomplete name 3, col: 2864 row: []
col: 2865 similar rows:  [2865, 3015, 3870, 14922]
incomplete name 3, col: 2865 row: []
col: 2866 similar rows:  [2866, 3373, 3619, 3655, 4153, 4168, 14811, 14826, 15059]
incomplete name 3, col: 2866 row: []
col: 2868 similar rows:  [2868, 2988, 3857]
incomplete name 3, col: 2868 row: []
col: 2869 similar rows:  [2869]
11111111111111111111
incomplete name 3, col: 2869 row: []
col: 2870 similar rows:  [2870, 3932, 3978, 4006, 4017, 4105]
incomplete name 3, col: 2870 row: []
col: 2871 similar rows:  [2871, 2959]
incomplete name 3, col: 2871 row: []
col: 2872 similar rows:  [2872]
11111111111111111111
hotelname2 [2872]
wrong name!!!!
incomplete name 3, col: 2872 row: [2872]
col: 2873 similar rows:  [2873]
11111111111111111111
incomplete name 3, col: 2873 row: []
col: 2874 similar rows:  [2874, 3044, 3323, 3988, 14980, 15210]
incomplete name 3, col: 2874 row: []
col: 2877 similar rows:  [2877, 3005, 3011, 3659, 3664, 4174, 4176, 4178, 14868, 15086]
incomplete name 3, col: 2877 row: []
col: 2878 similar rows:  [2878]
11111111111111111111
incomplete name 3, col: 2878 row: []
col: 2879 similar rows:  [2879, 3018, 3186, 3382, 3386, 3390, 3595, 3670, 3953, 3963, 4005, 14806, 14889, 14943, 15071, 15195]
incomplete name 3, col: 2879 row: []
col: 2881 similar rows:  [2881]
11111111111111111111
incomplete name 3, col: 2881 row: []
col: 2882 similar rows:  [2882, 3808, 4016, 4207, 4213, 14904, 14981, 15073, 15177, 15227]
incomplete name 3, col: 2882 row: []
col: 2883 similar rows:  [2883, 3028, 3105, 3630, 3915, 4205, 14952, 15011]
incomplete name 3, col: 2883 row: []
col: 2886 similar rows:  [2886]
11111111111111111111
incomplete name 3, col: 2886 row: []
col: 2888 similar rows:  [2888, 3031, 3034, 3418, 3442, 3509, 3765, 3791, 3802]
incomplete name 3, col: 2888 row: []
col: 2889 similar rows:  [2889, 2964, 3062, 3093, 3135, 3614, 3688, 3699, 3899, 4001, 15184]
incomplete name 3, col: 2889 row: []
col: 2901 similar rows:  [2901, 2917, 3117, 3139, 3357, 3715, 3740, 3889, 3929, 14882, 15183]
incomplete name 3, col: 2901 row: []
col: 2902 similar rows:  [2902, 2931, 2955, 3100, 3447, 3717, 3832, 3928, 3938, 4086, 14863, 15057, 15215]
incomplete name 3, col: 2902 row: []
col: 2906 similar rows:  [2906]
11111111111111111111
incomplete name 3, col: 2906 row: []
col: 2912 similar rows:  [2912, 3241]
incomplete name 3, col: 2912 row: []
col: 2919 similar rows:  [2919, 3274, 3281, 3313, 3601, 3642, 3682, 3879, 3904, 14897, 14964, 15171, 15257]
incomplete name 3, col: 2919 row: []
col: 2920 similar rows:  [2920, 3354, 3367, 3700, 14848]
incomplete name 3, col: 2920 row: []
col: 2924 similar rows:  [2924]
11111111111111111111
incomplete name 3, col: 2924 row: []
col: 2926 similar rows:  [2926]
11111111111111111111
incomplete name 3, col: 2926 row: []
col: 2933 similar rows:  [2933, 2986, 3041, 3053, 3058, 3061, 3173, 3312, 3349, 3512, 3565, 3653, 3884, 4154, 4155, 14795, 14918, 14919]
incomplete name 3, col: 2933 row: []
col: 2934 similar rows:  [2934, 3006, 3110, 3168, 3213, 3868, 3873, 4056, 4117, 14879]
incomplete name 3, col: 2934 row: []
col: 2936 similar rows:  [2936, 3151, 3848, 3882, 14870]
incomplete name 3, col: 2936 row: []
col: 2946 similar rows:  [2946]
11111111111111111111
incomplete name 3, col: 2946 row: []
col: 2947 similar rows:  [2947]
11111111111111111111
incomplete name 3, col: 2947 row: []
col: 2950 similar rows:  [2950, 3296, 3667]
incomplete name 3, col: 2950 row: []
col: 2952 similar rows:  [2952, 3287, 3393, 3736, 3751, 3864, 14851]
incomplete name 3, col: 2952 row: []
col: 2957 similar rows:  [2957, 3887]
incomplete name 3, col: 2957 row: []
col: 2958 similar rows:  [2958, 4111, 15153]
incomplete name 3, col: 2958 row: []
col: 2961 similar rows:  [2961]
11111111111111111111
incomplete name 3, col: 2961 row: []
col: 2965 similar rows:  [2965, 3195, 4007, 4087, 4125, 14891]
incomplete name 3, col: 2965 row: []
col: 2977 similar rows:  [2977, 3283]
incomplete name 3, col: 2977 row: []
col: 2979 similar rows:  [2979]
11111111111111111111
incomplete name 3, col: 2979 row: []
col: 2981 similar rows:  [2981, 3332, 3343, 3362, 3656, 3703, 3782, 3982, 4094, 4096, 4101, 4177, 14838, 14990, 15205]
incomplete name 3, col: 2981 row: []
col: 2982 similar rows:  [2982, 2992, 3851, 4138, 4162, 4165, 4172, 14917, 15060, 15068]
incomplete name 3, col: 2982 row: []
col: 2983 similar rows:  [2983, 3016, 3381]
incomplete name 3, col: 2983 row: []
col: 2984 similar rows:  [2984, 3410]
incomplete name 3, col: 2984 row: []
col: 2989 similar rows:  [2989, 3385]
incomplete name 3, col: 2989 row: []
col: 2991 similar rows:  [2991]
11111111111111111111
incomplete name 3, col: 2991 row: []
col: 2993 similar rows:  [2993, 3424, 3432, 3516, 3707, 3727, 3795, 3812, 4109, 4171, 4204, 14928, 15104, 15185]
incomplete name 3, col: 2993 row: []
col: 2994 similar rows:  [2994, 3321, 3444]
incomplete name 3, col: 2994 row: []
col: 2997 similar rows:  [2997, 3285]
incomplete name 3, col: 2997 row: []
col: 2998 similar rows:  [2998]
11111111111111111111
incomplete name 3, col: 2998 row: []
col: 2999 similar rows:  [2999]
11111111111111111111
hotelname2 [2999]
wrong name!!!!
incomplete name 3, col: 2999 row: [2999]
col: 3001 similar rows:  [3001, 3007, 3282, 3640, 3749, 3752, 14819, 14931]
incomplete name 3, col: 3001 row: []
col: 3003 similar rows:  [3003, 3384, 3407, 4164]
incomplete name 3, col: 3003 row: []
col: 3004 similar rows:  [3004, 3897, 4202, 14951]
incomplete name 3, col: 3004 row: []
col: 3009 similar rows:  [3009]
11111111111111111111
incomplete name 3, col: 3009 row: []
col: 3010 similar rows:  [3010, 4163]
incomplete name 3, col: 3010 row: []
col: 3012 similar rows:  [3012]
11111111111111111111
incomplete name 3, col: 3012 row: []
col: 3013 similar rows:  [3013]
11111111111111111111
incomplete name 3, col: 3013 row: []
col: 3020 similar rows:  [3020, 3291, 3891, 14937, 15004, 15006]
incomplete name 3, col: 3020 row: []
col: 3022 similar rows:  [3022, 3045, 3220, 3294, 3498, 3976, 4208, 15152, 15231]
incomplete name 3, col: 3022 row: []
col: 3023 similar rows:  [3023, 3951, 15098, 15194]
incomplete name 3, col: 3023 row: []
col: 3026 similar rows:  [3026, 3474, 3790, 4031, 4099, 4214, 14812, 14905, 14946, 15017, 15148]
incomplete name 3, col: 3026 row: []
col: 3027 similar rows:  [3027, 3038, 3073, 3114, 3125, 3137, 3253, 3278, 3337, 3339, 3377, 3420, 3459, 3623, 3723, 3755, 3947, 4047, 14934, 15084]
incomplete name 3, col: 3027 row: []
col: 3029 similar rows:  [3029]
11111111111111111111
incomplete name 3, col: 3029 row: []
col: 3035 similar rows:  [3035, 3414, 4079, 4194]
incomplete name 3, col: 3035 row: []
col: 3036 similar rows:  [3036, 3767]
incomplete name 3, col: 3036 row: []
col: 3037 similar rows:  [3037, 4112]
incomplete name 3, col: 3037 row: []

col: 3046 similar rows:  [3046]
11111111111111111111
incomplete name 3, col: 3046 row: []
col: 3051 similar rows:  [3051, 3771, 4149]
incomplete name 3, col: 3051 row: []
col: 3052 similar rows:  [3052, 3128, 3191, 3342, 3426, 3607, 3772, 4000, 4003, 4077, 4179, 4196, 14830, 14877, 14991, 15000, 15010, 15108]
incomplete name 3, col: 3052 row: []
col: 3054 similar rows:  [3054, 14885, 14984]
incomplete name 3, col: 3054 row: []
col: 3055 similar rows:  [3055]
11111111111111111111
hotelname2 [3055]
wrong name!!!!
incomplete name 3, col: 3055 row: [3055]
col: 3060 similar rows:  [3060]
11111111111111111111
incomplete name 3, col: 3060 row: []
col: 3063 similar rows:  [3063]
11111111111111111111
incomplete name 3, col: 3063 row: []
col: 3064 similar rows:  [3064, 3616, 3644, 3785, 3896, 3918, 3920]
incomplete name 3, col: 3064 row: []
col: 3065 similar rows:  [3065]
11111111111111111111
incomplete name 3, col: 3065 row: []
col: 3068 similar rows:  [3068]
11111111111111111111
hotelname2 [3068]
wrong name!!!!
incomplete name 3, col: 3068 row: [3068]
col: 3072 similar rows:  [3072, 3798]
incomplete name 3, col: 3072 row: []
col: 3076 similar rows:  [3076, 3096, 4102, 15013, 15030]
incomplete name 3, col: 3076 row: []
col: 3078 similar rows:  [3078]
11111111111111111111
incomplete name 3, col: 3078 row: []
col: 3080 similar rows:  [3080, 3709, 15012, 15226]
incomplete name 3, col: 3080 row: []
col: 3081 similar rows:  [3081, 15138]
incomplete name 3, col: 3081 row: []
col: 3083 similar rows:  [3083]
11111111111111111111
incomplete name 3, col: 3083 row: []
col: 3087 similar rows:  [3087, 3235, 14906]
incomplete name 3, col: 3087 row: []
col: 3088 similar rows:  [3088]
11111111111111111111
incomplete name 3, col: 3088 row: []
col: 3090 similar rows:  [3090, 3721]
incomplete name 3, col: 3090 row: []
col: 3092 similar rows:  [3092, 3235, 14906]
incomplete name 3, col: 3092 row: []
col: 3094 similar rows:  [3094, 3976, 15232]
incomplete name 3, col: 3094 row: []
col: 3102 similar rows:  [3102, 3115, 4160]
incomplete name 3, col: 3102 row: []
col: 3112 similar rows:  [3112, 3352]
incomplete name 3, col: 3112 row: []
col: 3118 similar rows:  [3118, 3180, 4025]
incomplete name 3, col: 3118 row: []
col: 3121 similar rows:  [3121, 3564]
incomplete name 3, col: 3121 row: []
col: 3122 similar rows:  [3122]
11111111111111111111
incomplete name 3, col: 3122 row: []
col: 3138 similar rows:  [3138, 3681, 3738, 3878, 4085, 4103, 14878, 14948, 14975, 15022, 15131, 15192]
incomplete name 3, col: 3138 row: []
col: 3143 similar rows:  [3143, 3966]
incomplete name 3, col: 3143 row: []
col: 3160 similar rows:  [3160, 3725, 3943]
incomplete name 3, col: 3160 row: []
col: 3164 similar rows:  [3164, 3889, 14882]
incomplete name 3, col: 3164 row: []
col: 3165 similar rows:  [3165, 3210, 3331, 3347, 3758, 3837, 14860, 15114]
incomplete name 3, col: 3165 row: []
col: 3167 similar rows:  [3167]
11111111111111111111
incomplete name 3, col: 3167 row: []
col: 3182 similar rows:  [3182]
11111111111111111111
incomplete name 3, col: 3182 row: []
col: 3187 similar rows:  [3187]
11111111111111111111
hotelname2 [3187]
incomplete name 3, col: 3187 row: [3187]
col: 3189 similar rows:  [3189, 3300, 3394]
incomplete name 3, col: 3189 row: []
col: 3190 similar rows:  [3190, 3440]
incomplete name 3, col: 3190 row: []
col: 3192 similar rows:  [3192, 3297, 14803, 15031]
incomplete name 3, col: 3192 row: []
col: 3214 similar rows:  [3214]
11111111111111111111
hotelname2 [3214]
incomplete name 3, col: 3214 row: [3214]
col: 3215 similar rows:  [3215, 4022]
incomplete name 3, col: 3215 row: []
col: 3219 similar rows:  [3219, 3626, 3661, 3737, 14927, 15067]
incomplete name 3, col: 3219 row: []
col: 3221 similar rows:  [3221, 3903, 14935]
incomplete name 3, col: 3221 row: []
col: 3223 similar rows:  [3223]
11111111111111111111
incomplete name 3, col: 3223 row: []
col: 3224 similar rows:  [3224, 15122]
incomplete name 3, col: 3224 row: []
col: 3227 similar rows:  [3227]
11111111111111111111
hotelname2 [3227]
incomplete name 3, col: 3227 row: [3227]
col: 3228 similar rows:  [3228]
11111111111111111111
incomplete name 3, col: 3228 row: []
col: 3230 similar rows:  [3230]
11111111111111111111
incomplete name 3, col: 3230 row: []
col: 3231 similar rows:  [3231, 3234]
incomplete name 3, col: 3231 row: []
col: 3232 similar rows:  [3232, 3438, 4212, 4225, 14966, 15144]
incomplete name 3, col: 3232 row: []
col: 3236 similar rows:  [3236, 3811]
incomplete name 3, col: 3236 row: []
col: 3238 similar rows:  [3238, 14903]
incomplete name 3, col: 3238 row: []
col: 3239 similar rows:  [3239]
11111111111111111111
incomplete name 3, col: 3239 row: []
col: 3240 similar rows:  [3240]
11111111111111111111
incomplete name 3, col: 3240 row: []
col: 3242 similar rows:  [3242, 14999]
incomplete name 3, col: 3242 row: []
col: 3243 similar rows:  [3243]
11111111111111111111
incomplete name 3, col: 3243 row: []
col: 3244 similar rows:  [3244, 4075]
incomplete name 3, col: 3244 row: []
col: 3247 similar rows:  [3247]
11111111111111111111
hotelname2 [3247]
incomplete name 3, col: 3247 row: [3247]
col: 3250 similar rows:  [3250, 3252, 3817]
incomplete name 3, col: 3250 row: []
col: 3262 similar rows:  [3262]
11111111111111111111
incomplete name 3, col: 3262 row: []
col: 3264 similar rows:  [3264, 3934, 14925]
incomplete name 3, col: 3264 row: []
col: 3270 similar rows:  [3270]
11111111111111111111
incomplete name 3, col: 3270 row: []
col: 3289 similar rows:  [3289, 3658, 3960, 4064, 14827]
incomplete name 3, col: 3289 row: []
col: 3290 similar rows:  [3290]
11111111111111111111
incomplete name 3, col: 3290 row: []
col: 3298 similar rows:  [3298, 3889, 3941, 14853, 14882, 14956, 15216]
incomplete name 3, col: 3298 row: []
col: 3305 similar rows:  [3305, 4021]
incomplete name 3, col: 3305 row: []
col: 3307 similar rows:  [3307, 3310]
incomplete name 3, col: 3307 row: []
col: 3308 similar rows:  [3308, 3990, 14958, 14963, 15204]
hotelname2 [15204]
wrong name!!!!
incomplete name 3, col: 3308 row: [15204]
col: 3311 similar rows:  [3311, 15242]
incomplete name 3, col: 3311 row: []
col: 3314 similar rows:  [3314]
11111111111111111111
incomplete name 3, col: 3314 row: []
col: 3316 similar rows:  [3316]
11111111111111111111
incomplete name 3, col: 3316 row: []
col: 3318 similar rows:  [3318]
11111111111111111111
incomplete name 3, col: 3318 row: []
col: 3320 similar rows:  [3320]
11111111111111111111
incomplete name 3, col: 3320 row: []
col: 3322 similar rows:  [3322, 3932, 3978]
incomplete name 3, col: 3322 row: []
col: 3324 similar rows:  [3324]
11111111111111111111
incomplete name 3, col: 3324 row: []
col: 3325 similar rows:  [3325]
11111111111111111111
incomplete name 3, col: 3325 row: []
col: 3326 similar rows:  [3326]
11111111111111111111
hotelname2 [3326]
incomplete name 3, col: 3326 row: [3326]
col: 3327 similar rows:  [3327]
11111111111111111111
hotelname2 [3327]
incomplete name 3, col: 3327 row: [3327]
col: 3328 similar rows:  [3328]
11111111111111111111
incomplete name 3, col: 3328 row: []
col: 3329 similar rows:  [3329]
11111111111111111111
incomplete name 3, col: 3329 row: []
col: 3346 similar rows:  [3346]
11111111111111111111
hotelname2 [3346]
incomplete name 3, col: 3346 row: [3346]
col: 3348 similar rows:  [3348]
11111111111111111111
hotelname2 [3348]
wrong name!!!!
incomplete name 3, col: 3348 row: [3348]
col: 3353 similar rows:  [3353, 3359, 3856, 3907]
incomplete name 3, col: 3353 row: []
col: 3355 similar rows:  [3355]
11111111111111111111
incomplete name 3, col: 3355 row: []
col: 3360 similar rows:  [3360, 4060, 4144, 14885]
incomplete name 3, col: 3360 row: []
col: 3365 similar rows:  [3365, 3989, 15095]
hotelname2 [15095]
incomplete name 3, col: 3365 row: [15095]
col: 3370 similar rows:  [3370]
11111111111111111111
hotelname2 [3370]
incomplete name 3, col: 3370 row: [3370]
col: 3371 similar rows:  [3371]
11111111111111111111
incomplete name 3, col: 3371 row: []
col: 3372 similar rows:  [3372, 3408, 3639, 3744, 3747, 4018, 4131, 4173, 14926, 15236]
incomplete name 3, col: 3372 row: []
col: 3375 similar rows:  [3375, 4227]
incomplete name 3, col: 3375 row: []
col: 3380 similar rows:  [3380]
11111111111111111111
incomplete name 3, col: 3380 row: []
col: 3383 similar rows:  [3383]
11111111111111111111
incomplete name 3, col: 3383 row: []
col: 3387 similar rows:  [3387, 3652, 3758, 14860, 15114]
incomplete name 3, col: 3387 row: []
col: 3388 similar rows:  [3388]
11111111111111111111
incomplete name 3, col: 3388 row: []
col: 3389 similar rows:  [3389, 4041, 14871]
incomplete name 3, col: 3389 row: []
col: 3392 similar rows:  [3392, 14866]
incomplete name 3, col: 3392 row: []

col: 3395 similar rows:  [3395]
11111111111111111111
incomplete name 3, col: 3395 row: []
col: 3396 similar rows:  [3396, 3436, 14949, 15182]
incomplete name 3, col: 3396 row: []
col: 3397 similar rows:  [3397, 3399]
incomplete name 3, col: 3397 row: []
col: 3398 similar rows:  [3398]
11111111111111111111
incomplete name 3, col: 3398 row: []
col: 3400 similar rows:  [3400, 3758, 14860, 15114]
incomplete name 3, col: 3400 row: []
col: 3401 similar rows:  [3401]
11111111111111111111
incomplete name 3, col: 3401 row: []
col: 3402 similar rows:  [3402]
11111111111111111111
incomplete name 3, col: 3402 row: []
col: 3403 similar rows:  [3403, 15062]
incomplete name 3, col: 3403 row: []
col: 3404 similar rows:  [3404]
11111111111111111111
incomplete name 3, col: 3404 row: []
col: 3405 similar rows:  [3405, 4156]
incomplete name 3, col: 3405 row: []
col: 3411 similar rows:  [3411]
11111111111111111111
incomplete name 3, col: 3411 row: []
col: 3412 similar rows:  [3412, 14953, 15213]
incomplete name 3, col: 3412 row: []
col: 3415 similar rows:  [3415, 3695, 4226, 14910, 15202]
incomplete name 3, col: 3415 row: []
col: 3416 similar rows:  [3416, 14940]
incomplete name 3, col: 3416 row: []
col: 3417 similar rows:  [3417]
11111111111111111111
incomplete name 3, col: 3417 row: []
col: 3419 similar rows:  [3419, 3434, 3901, 4082, 4084, 4198, 14879, 15056, 15175]
incomplete name 3, col: 3419 row: []
col: 3421 similar rows:  [3421, 3900, 3954, 3975, 15201, 15246]
incomplete name 3, col: 3421 row: []
col: 3423 similar rows:  [3423]
11111111111111111111
hotelname2 [3423]
wrong name!!!!
incomplete name 3, col: 3423 row: [3423]
col: 3425 similar rows:  [3425, 14901]
incomplete name 3, col: 3425 row: []
col: 3428 similar rows:  [3428, 14879]
incomplete name 3, col: 3428 row: []
col: 3429 similar rows:  [3429, 3748, 3775, 4188, 4223, 15109, 15139, 15143]
incomplete name 3, col: 3429 row: []
col: 3430 similar rows:  [3430]
11111111111111111111
incomplete name 3, col: 3430 row: []
col: 3431 similar rows:  [3431]
11111111111111111111
incomplete name 3, col: 3431 row: []
col: 3433 similar rows:  [3433]
11111111111111111111
incomplete name 3, col: 3433 row: []
col: 3435 similar rows:  [3435]
11111111111111111111
incomplete name 3, col: 3435 row: []
col: 3437 similar rows:  [3437]
11111111111111111111
incomplete name 3, col: 3437 row: []
col: 3445 similar rows:  [3445]
11111111111111111111
incomplete name 3, col: 3445 row: []
col: 3449 similar rows:  [3449, 15150]
incomplete name 3, col: 3449 row: []
col: 3450 similar rows:  [3450]
11111111111111111111
incomplete name 3, col: 3450 row: []
col: 3452 similar rows:  [3452]
11111111111111111111
incomplete name 3, col: 3452 row: []
col: 3457 similar rows:  [3457]
11111111111111111111
incomplete name 3, col: 3457 row: []
col: 3458 similar rows:  [3458, 3719]
incomplete name 3, col: 3458 row: []
col: 3469 similar rows:  [3469]
11111111111111111111
incomplete name 3, col: 3469 row: []
col: 3479 similar rows:  [3479]
11111111111111111111
hotelname2 [3479]
incomplete name 3, col: 3479 row: []
col: 3480 similar rows:  [3480]
11111111111111111111
incomplete name 3, col: 3480 row: []
col: 3482 similar rows:  [3482, 3628, 3641, 3746, 3768, 4167, 14818, 14834]
incomplete name 3, col: 3482 row: []
col: 3494 similar rows:  [3494]
11111111111111111111
incomplete name 3, col: 3494 row: []
col: 3496 similar rows:  [3496]
11111111111111111111
incomplete name 3, col: 3496 row: []
col: 3499 similar rows:  [3499]
11111111111111111111
incomplete name 3, col: 3499 row: []
col: 3501 similar rows:  [3501]
11111111111111111111
incomplete name 3, col: 3501 row: []
col: 3503 similar rows:  [3503]
11111111111111111111
hotelname2 [3503]
incomplete name 3, col: 3503 row: [3503]
col: 3506 similar rows:  [3506]
11111111111111111111
incomplete name 3, col: 3506 row: []
col: 3510 similar rows:  [3510, 4129]
incomplete name 3, col: 3510 row: []
col: 3511 similar rows:  [3511, 15222]
incomplete name 3, col: 3511 row: []
col: 3514 similar rows:  [3514, 4035, 14914]
incomplete name 3, col: 3514 row: []
col: 3515 similar rows:  [3515]
11111111111111111111
hotelname2 [3515]
incomplete name 3, col: 3515 row: [3515]
col: 3517 similar rows:  [3517, 3788, 3968, 3999, 15188, 15211]
incomplete name 3, col: 3517 row: []
col: 3521 similar rows:  [3521]
11111111111111111111
hotelname2 [3521]
incomplete name 3, col: 3521 row: [3521]
col: 3524 similar rows:  [3524]
11111111111111111111
incomplete name 3, col: 3524 row: []
col: 3526 similar rows:  [3526]
11111111111111111111
incomplete name 3, col: 3526 row: []
col: 3533 similar rows:  [3533, 4015]
incomplete name 3, col: 3533 row: []
col: 3536 similar rows:  [3536]
11111111111111111111
incomplete name 3, col: 3536 row: []
col: 3542 similar rows:  [3542]
11111111111111111111
incomplete name 3, col: 3542 row: []
col: 3556 similar rows:  [3556]
11111111111111111111
incomplete name 3, col: 3556 row: []
col: 3588 similar rows:  [3588]
11111111111111111111
incomplete name 3, col: 3588 row: []
col: 3590 similar rows:  [3590, 3707, 3727, 3795, 3812, 4040, 4109, 4204, 15104, 15185]
incomplete name 3, col: 3590 row: []
col: 3611 similar rows:  [3611]
11111111111111111111
incomplete name 3, col: 3611 row: []
col: 3615 similar rows:  [3615]
11111111111111111111
hotelname2 [3615]
incomplete name 3, col: 3615 row: [3615]
col: 3617 similar rows:  [3617]
11111111111111111111
incomplete name 3, col: 3617 row: []
col: 3618 similar rows:  [3618]
11111111111111111111
incomplete name 3, col: 3618 row: []
col: 3620 similar rows:  [3620, 3760]
incomplete name 3, col: 3620 row: []
col: 3622 similar rows:  [3622, 4170]
incomplete name 3, col: 3622 row: []
col: 3624 similar rows:  [3624]
11111111111111111111
incomplete name 3, col: 3624 row: []
col: 3627 similar rows:  [3627, 15087]
incomplete name 3, col: 3627 row: []
col: 3629 similar rows:  [3629]
11111111111111111111
incomplete name 3, col: 3629 row: []
col: 3633 similar rows:  [3633, 4036, 4050, 4068]
incomplete name 3, col: 3633 row: []
col: 3635 similar rows:  [3635, 3869]
incomplete name 3, col: 3635 row: []
col: 3637 similar rows:  [3637]
11111111111111111111
incomplete name 3, col: 3637 row: []
col: 3638 similar rows:  [3638]
11111111111111111111
incomplete name 3, col: 3638 row: []
col: 3645 similar rows:  [3645, 3881]
incomplete name 3, col: 3645 row: []
col: 3646 similar rows:  [3646]
11111111111111111111
incomplete name 3, col: 3646 row: []
col: 3647 similar rows:  [3647]
11111111111111111111
incomplete name 3, col: 3647 row: []
col: 3649 similar rows:  [3649, 3957]
incomplete name 3, col: 3649 row: []
col: 3654 similar rows:  [3654, 3861, 4049]
incomplete name 3, col: 3654 row: []
col: 3660 similar rows:  [3660]
11111111111111111111
incomplete name 3, col: 3660 row: []
col: 3662 similar rows:  [3662]
11111111111111111111
incomplete name 3, col: 3662 row: []
col: 3663 similar rows:  [3663, 3745, 14921]
incomplete name 3, col: 3663 row: []
col: 3666 similar rows:  [3666]
11111111111111111111
hotelname2 [3666]
incomplete name 3, col: 3666 row: [3666]
col: 3668 similar rows:  [3668]
11111111111111111111
incomplete name 3, col: 3668 row: []
col: 3669 similar rows:  [3669]
11111111111111111111
incomplete name 3, col: 3669 row: []
col: 3671 similar rows:  [3671]
11111111111111111111
incomplete name 3, col: 3671 row: []
col: 3672 similar rows:  [3672, 14837, 15127]
incomplete name 3, col: 3672 row: []
col: 3673 similar rows:  [3673, 3675]
incomplete name 3, col: 3673 row: []
col: 3674 similar rows:  [3674]
11111111111111111111
incomplete name 3, col: 3674 row: []
col: 3677 similar rows:  [3677, 3704, 15025]
incomplete name 3, col: 3677 row: []
col: 3679 similar rows:  [3679, 3692, 3984]
incomplete name 3, col: 3679 row: []
col: 3680 similar rows:  [3680]
11111111111111111111
incomplete name 3, col: 3680 row: []
col: 3689 similar rows:  [3689]
11111111111111111111
incomplete name 3, col: 3689 row: []
col: 3691 similar rows:  [3691]
11111111111111111111
incomplete name 3, col: 3691 row: []
col: 3696 similar rows:  [3696]
11111111111111111111
incomplete name 3, col: 3696 row: []
col: 3701 similar rows:  [3701, 15253]
incomplete name 3, col: 3701 row: []
col: 3702 similar rows:  [3702, 15120]
incomplete name 3, col: 3702 row: []
col: 3716 similar rows:  [3716]
11111111111111111111
hotelname2 [3716]
incomplete name 3, col: 3716 row: []
col: 3733 similar rows:  [3733, 4001]
incomplete name 3, col: 3733 row: []
col: 3739 similar rows:  [3739]
11111111111111111111
hotelname2 [3739]
incomplete name 3, col: 3739 row: [3739]
col: 3743 similar rows:  [3743, 3865]
incomplete name 3, col: 3743 row: []
col: 3753 similar rows:  [3753]
11111111111111111111
incomplete name 3, col: 3753 row: []
col: 3754 similar rows:  [3754]
11111111111111111111
incomplete name 3, col: 3754 row: []
col: 3757 similar rows:  [3757, 14798]
incomplete name 3, col: 3757 row: []

col: 3759 similar rows:  [3759]
11111111111111111111
incomplete name 3, col: 3759 row: []
col: 3762 similar rows:  [3762]
11111111111111111111
incomplete name 3, col: 3762 row: []
col: 3763 similar rows:  [3763]
11111111111111111111
incomplete name 3, col: 3763 row: []
col: 3764 similar rows:  [3764, 3970, 15206]
incomplete name 3, col: 3764 row: []
col: 3770 similar rows:  [3770]
11111111111111111111
incomplete name 3, col: 3770 row: []
col: 3773 similar rows:  [3773]
11111111111111111111
hotelname2 [3773]
incomplete name 3, col: 3773 row: [3773]
col: 3774 similar rows:  [3774, 3793, 3796, 3898, 3965, 4011, 4193, 14813, 14993, 15003, 15126, 15200, 15229]
incomplete name 3, col: 3774 row: []
col: 3776 similar rows:  [3776]
11111111111111111111
hotelname2 [3776]
incomplete name 3, col: 3776 row: [3776]
col: 3779 similar rows:  [3779, 3889, 14882]
incomplete name 3, col: 3779 row: []
col: 3780 similar rows:  [3780]
11111111111111111111
incomplete name 3, col: 3780 row: []
col: 3781 similar rows:  [3781, 3957]
incomplete name 3, col: 3781 row: []
col: 3784 similar rows:  [3784, 14954]
incomplete name 3, col: 3784 row: []
col: 3786 similar rows:  [3786, 15133]
incomplete name 3, col: 3786 row: []
col: 3787 similar rows:  [3787]
11111111111111111111
hotelname2 [3787]
incomplete name 3, col: 3787 row: []
col: 3799 similar rows:  [3799]
11111111111111111111
incomplete name 3, col: 3799 row: []
col: 3800 similar rows:  [3800]
11111111111111111111
incomplete name 3, col: 3800 row: []
col: 3801 similar rows:  [3801]
11111111111111111111
incomplete name 3, col: 3801 row: []
col: 3803 similar rows:  [3803, 3985, 4009]
incomplete name 3, col: 3803 row: []
col: 3805 similar rows:  [3805, 15025]
incomplete name 3, col: 3805 row: []
col: 3806 similar rows:  [3806]
11111111111111111111
incomplete name 3, col: 3806 row: []
col: 3807 similar rows:  [3807]
11111111111111111111
incomplete name 3, col: 3807 row: []
col: 3810 similar rows:  [3810]
11111111111111111111
incomplete name 3, col: 3810 row: []
col: 3813 similar rows:  [3813]
11111111111111111111
incomplete name 3, col: 3813 row: []
col: 3819 similar rows:  [3819]
11111111111111111111
incomplete name 3, col: 3819 row: []
col: 3823 similar rows:  [3823]
11111111111111111111
incomplete name 3, col: 3823 row: []
col: 3831 similar rows:  [3831, 4029, 4030]
incomplete name 3, col: 3831 row: []
col: 3847 similar rows:  [3847]
11111111111111111111
incomplete name 3, col: 3847 row: []
col: 3853 similar rows:  [3853, 4167, 14818]
incomplete name 3, col: 3853 row: []
col: 3863 similar rows:  [3863, 3866, 3880]
incomplete name 3, col: 3863 row: []
col: 3867 similar rows:  [3867]
11111111111111111111
incomplete name 3, col: 3867 row: []
col: 3871 similar rows:  [3871, 4189]
incomplete name 3, col: 3871 row: []
col: 3874 similar rows:  [3874, 3886, 4142]
incomplete name 3, col: 3874 row: []
col: 3875 similar rows:  [3875, 4134]
incomplete name 3, col: 3875 row: []
col: 3876 similar rows:  [3876, 14920]
incomplete name 3, col: 3876 row: []
col: 3890 similar rows:  [3890]
11111111111111111111
incomplete name 3, col: 3890 row: []
col: 3894 similar rows:  [3894]
11111111111111111111
incomplete name 3, col: 3894 row: []
col: 3895 similar rows:  [3895, 15255]
incomplete name 3, col: 3895 row: []
col: 3902 similar rows:  [3902]
11111111111111111111
incomplete name 3, col: 3902 row: []
col: 3912 similar rows:  [3912]
11111111111111111111
hotelname2 [3912]
incomplete name 3, col: 3912 row: []
col: 3913 similar rows:  [3913]
11111111111111111111
incomplete name 3, col: 3913 row: []
col: 3914 similar rows:  [3914]
11111111111111111111
incomplete name 3, col: 3914 row: []
col: 3916 similar rows:  [3916]
11111111111111111111
incomplete name 3, col: 3916 row: []
col: 3925 similar rows:  [3925]
11111111111111111111
hotelname2 [3925]
incomplete name 3, col: 3925 row: [3925]
col: 3937 similar rows:  [3937]
11111111111111111111
incomplete name 3, col: 3937 row: []
col: 3942 similar rows:  [3942]
11111111111111111111
incomplete name 3, col: 3942 row: []
col: 3948 similar rows:  [3948, 4147]
incomplete name 3, col: 3948 row: []
col: 3949 similar rows:  [3949]
11111111111111111111
hotelname2 [3949]
incomplete name 3, col: 3949 row: [3949]
col: 3961 similar rows:  [3961]
11111111111111111111
incomplete name 3, col: 3961 row: []
col: 3962 similar rows:  [3962]
11111111111111111111
incomplete name 3, col: 3962 row: []
col: 3964 similar rows:  [3964]
11111111111111111111
incomplete name 3, col: 3964 row: []
col: 3967 similar rows:  [3967, 4192]
incomplete name 3, col: 3967 row: []
col: 3969 similar rows:  [3969]
11111111111111111111
incomplete name 3, col: 3969 row: []
col: 3972 similar rows:  [3972, 14901]
incomplete name 3, col: 3972 row: []
col: 3973 similar rows:  [3973]
11111111111111111111
incomplete name 3, col: 3973 row: []
col: 3977 similar rows:  [3977, 3992, 4190, 14804, 14970, 15094, 15140, 15178]
incomplete name 3, col: 3977 row: []
col: 3979 similar rows:  [3979, 3994, 4014, 4113, 14890, 15014, 15029, 15089, 15105]
incomplete name 3, col: 3979 row: []
col: 3980 similar rows:  [3980]
11111111111111111111
incomplete name 3, col: 3980 row: []
col: 3983 similar rows:  [3983, 14907, 15204]
hotelname2 [15204]
wrong name!!!!
incomplete name 3, col: 3983 row: [15204]
col: 3987 similar rows:  [3987]
11111111111111111111
incomplete name 3, col: 3987 row: []
col: 3991 similar rows:  [3991, 14837]
incomplete name 3, col: 3991 row: []
col: 3993 similar rows:  [3993, 15024]
incomplete name 3, col: 3993 row: []
col: 3996 similar rows:  [3996]
11111111111111111111
incomplete name 3, col: 3996 row: []
col: 3998 similar rows:  [3998]
11111111111111111111
hotelname2 [3998]
incomplete name 3, col: 3998 row: [3998]
col: 4002 similar rows:  [4002, 14882]
incomplete name 3, col: 4002 row: []
col: 4004 similar rows:  [4004]
11111111111111111111
hotelname2 [4004]
incomplete name 3, col: 4004 row: [4004]
col: 4012 similar rows:  [4012]
11111111111111111111
incomplete name 3, col: 4012 row: []
col: 4013 similar rows:  [4013]
11111111111111111111
incomplete name 3, col: 4013 row: []
col: 4023 similar rows:  [4023]
11111111111111111111
incomplete name 3, col: 4023 row: []
col: 4027 similar rows:  [4027]
11111111111111111111
incomplete name 3, col: 4027 row: []
col: 4033 similar rows:  [4033]
11111111111111111111
incomplete name 3, col: 4033 row: []
col: 4037 similar rows:  [4037]
11111111111111111111
hotelname2 [4037]
incomplete name 3, col: 4037 row: [4037]
col: 4038 similar rows:  [4038]
11111111111111111111
incomplete name 3, col: 4038 row: []
col: 4043 similar rows:  [4043]
11111111111111111111
incomplete name 3, col: 4043 row: []
col: 4044 similar rows:  [4044, 14930, 15120]
incomplete name 3, col: 4044 row: []
col: 4051 similar rows:  [4051]
11111111111111111111
incomplete name 3, col: 4051 row: []
col: 4052 similar rows:  [4052]
11111111111111111111
incomplete name 3, col: 4052 row: []
col: 4053 similar rows:  [4053]
11111111111111111111
incomplete name 3, col: 4053 row: []
col: 4054 similar rows:  [4054]
11111111111111111111
incomplete name 3, col: 4054 row: []
col: 4057 similar rows:  [4057]
11111111111111111111
incomplete name 3, col: 4057 row: []
col: 4059 similar rows:  [4059]
11111111111111111111
incomplete name 3, col: 4059 row: []
col: 4062 similar rows:  [4062]
11111111111111111111
incomplete name 3, col: 4062 row: []
col: 4063 similar rows:  [4063]
11111111111111111111
incomplete name 3, col: 4063 row: []
col: 4065 similar rows:  [4065]
11111111111111111111
incomplete name 3, col: 4065 row: []
col: 4066 similar rows:  [4066]
11111111111111111111
incomplete name 3, col: 4066 row: []
col: 4067 similar rows:  [4067]
11111111111111111111
incomplete name 3, col: 4067 row: []
col: 4069 similar rows:  [4069]
11111111111111111111
incomplete name 3, col: 4069 row: []
col: 4071 similar rows:  [4071, 14955, 15190]
incomplete name 3, col: 4071 row: []
col: 4072 similar rows:  [4072]
11111111111111111111
incomplete name 3, col: 4072 row: []
col: 4074 similar rows:  [4074, 4151]
incomplete name 3, col: 4074 row: []
col: 4078 similar rows:  [4078]
11111111111111111111
incomplete name 3, col: 4078 row: []
col: 4080 similar rows:  [4080]
11111111111111111111
hotelname2 [4080]
incomplete name 3, col: 4080 row: [4080]
col: 4081 similar rows:  [4081]
11111111111111111111
incomplete name 3, col: 4081 row: []
col: 4083 similar rows:  [4083]
11111111111111111111
incomplete name 3, col: 4083 row: []
col: 4088 similar rows:  [4088]
11111111111111111111
incomplete name 3, col: 4088 row: []
col: 4089 similar rows:  [4089, 15092, 15122]
incomplete name 3, col: 4089 row: []
col: 4091 similar rows:  [4091]
11111111111111111111
hotelname2 [4091]
incomplete name 3, col: 4091 row: [4091]
col: 4092 similar rows:  [4092]
11111111111111111111
incomplete name 3, col: 4092 row: []
col: 4095 similar rows:  [4095]
11111111111111111111
incomplete name 3, col: 4095 row: []

col: 4098 similar rows:  [4098]
11111111111111111111
incomplete name 3, col: 4098 row: []
col: 4100 similar rows:  [4100]
11111111111111111111
incomplete name 3, col: 4100 row: []
col: 4104 similar rows:  [4104]
11111111111111111111
incomplete name 3, col: 4104 row: []
col: 4106 similar rows:  [4106]
11111111111111111111
incomplete name 3, col: 4106 row: []
col: 4107 similar rows:  [4107]
11111111111111111111
incomplete name 3, col: 4107 row: []
col: 4108 similar rows:  [4108]
11111111111111111111
incomplete name 3, col: 4108 row: []
col: 4110 similar rows:  [4110]
11111111111111111111
incomplete name 3, col: 4110 row: []
col: 4114 similar rows:  [4114]
11111111111111111111
incomplete name 3, col: 4114 row: []
col: 4121 similar rows:  [4121]
11111111111111111111
hotelname2 [4121]
incomplete name 3, col: 4121 row: [4121]
col: 4124 similar rows:  [4124]
11111111111111111111
incomplete name 3, col: 4124 row: []
col: 4126 similar rows:  [4126]
11111111111111111111
incomplete name 3, col: 4126 row: []
col: 4132 similar rows:  [4132]
11111111111111111111
incomplete name 3, col: 4132 row: []
col: 4135 similar rows:  [4135]
11111111111111111111
incomplete name 3, col: 4135 row: []
col: 4136 similar rows:  [4136]
11111111111111111111
hotelname2 [4136]
wrong name!!!!
incomplete name 3, col: 4136 row: [4136]
col: 4143 similar rows:  [4143]
11111111111111111111
incomplete name 3, col: 4143 row: []
col: 4148 similar rows:  [4148]
11111111111111111111
incomplete name 3, col: 4148 row: []
col: 4152 similar rows:  [4152, 4180]
incomplete name 3, col: 4152 row: []
col: 4157 similar rows:  [4157, 15065]
incomplete name 3, col: 4157 row: []
col: 4159 similar rows:  [4159]
11111111111111111111
incomplete name 3, col: 4159 row: []
col: 4161 similar rows:  [4161]
11111111111111111111
incomplete name 3, col: 4161 row: []
col: 4169 similar rows:  [4169]
11111111111111111111
incomplete name 3, col: 4169 row: []
col: 4175 similar rows:  [4175, 15115]
incomplete name 3, col: 4175 row: []
col: 4181 similar rows:  [4181]
11111111111111111111
incomplete name 3, col: 4181 row: []
col: 4183 similar rows:  [4183, 15191]
incomplete name 3, col: 4183 row: []
col: 4184 similar rows:  [4184]
11111111111111111111
incomplete name 3, col: 4184 row: []
col: 4185 similar rows:  [4185]
11111111111111111111
incomplete name 3, col: 4185 row: []
col: 4187 similar rows:  [4187]
11111111111111111111
incomplete name 3, col: 4187 row: []
col: 4201 similar rows:  [4201]
11111111111111111111
incomplete name 3, col: 4201 row: []
col: 4206 similar rows:  [4206]
11111111111111111111
incomplete name 3, col: 4206 row: []
col: 4209 similar rows:  [4209]
11111111111111111111
incomplete name 3, col: 4209 row: []
col: 4210 similar rows:  [4210]
11111111111111111111
incomplete name 3, col: 4210 row: []
col: 4211 similar rows:  [4211, 15189]
incomplete name 3, col: 4211 row: []
col: 4215 similar rows:  [4215]
11111111111111111111
hotelname2 [4215]
incomplete name 3, col: 4215 row: [4215]
col: 4216 similar rows:  [4216]
11111111111111111111
incomplete name 3, col: 4216 row: []
col: 4218 similar rows:  [4218, 15046]
incomplete name 3, col: 4218 row: []
col: 4220 similar rows:  [4220]
11111111111111111111
incomplete name 3, col: 4220 row: []
col: 4221 similar rows:  [4221, 14797]
incomplete name 3, col: 4221 row: []
col: 4222 similar rows:  [4222]
11111111111111111111
incomplete name 3, col: 4222 row: []
col: 4224 similar rows:  [4224]
11111111111111111111
incomplete name 3, col: 4224 row: []
col: 14789 similar rows:  [14789]
11111111111111111111
incomplete name 3, col: 14789 row: []
col: 14790 similar rows:  [14790]
11111111111111111111
incomplete name 3, col: 14790 row: []
col: 14791 similar rows:  [14791]
11111111111111111111
incomplete name 3, col: 14791 row: []
col: 14792 similar rows:  [14792]
11111111111111111111
incomplete name 3, col: 14792 row: []
col: 14794 similar rows:  [14794]
11111111111111111111
incomplete name 3, col: 14794 row: []
col: 14796 similar rows:  [14796]
11111111111111111111
incomplete name 3, col: 14796 row: []
col: 14799 similar rows:  [14799]
11111111111111111111
incomplete name 3, col: 14799 row: []
col: 14800 similar rows:  [14800]
11111111111111111111
incomplete name 3, col: 14800 row: []
col: 14801 similar rows:  [14801]
11111111111111111111
incomplete name 3, col: 14801 row: []
col: 14805 similar rows:  [14805]
11111111111111111111
incomplete name 3, col: 14805 row: []
col: 14807 similar rows:  [14807]
11111111111111111111
incomplete name 3, col: 14807 row: []
col: 14808 similar rows:  [14808]
11111111111111111111
incomplete name 3, col: 14808 row: []
col: 14810 similar rows:  [14810]
11111111111111111111
incomplete name 3, col: 14810 row: []
col: 14814 similar rows:  [14814]
11111111111111111111
hotelname2 [14814]
incomplete name 3, col: 14814 row: [14814]
col: 14815 similar rows:  [14815]
11111111111111111111
incomplete name 3, col: 14815 row: []
col: 14816 similar rows:  [14816]
11111111111111111111
incomplete name 3, col: 14816 row: []
col: 14821 similar rows:  [14821]
11111111111111111111
incomplete name 3, col: 14821 row: []
col: 14822 similar rows:  [14822]
11111111111111111111
incomplete name 3, col: 14822 row: []
col: 14823 similar rows:  [14823]
11111111111111111111
incomplete name 3, col: 14823 row: []
col: 14824 similar rows:  [14824]
11111111111111111111
incomplete name 3, col: 14824 row: []
col: 14828 similar rows:  [14828]
11111111111111111111
incomplete name 3, col: 14828 row: []
col: 14829 similar rows:  [14829]
11111111111111111111
incomplete name 3, col: 14829 row: []
col: 14831 similar rows:  [14831]
11111111111111111111
incomplete name 3, col: 14831 row: []
col: 14832 similar rows:  [14832]
11111111111111111111
incomplete name 3, col: 14832 row: []
col: 14833 similar rows:  [14833]
11111111111111111111
incomplete name 3, col: 14833 row: []
col: 14836 similar rows:  [14836]
11111111111111111111
incomplete name 3, col: 14836 row: []
col: 14839 similar rows:  [14839]
11111111111111111111
incomplete name 3, col: 14839 row: []
col: 14841 similar rows:  [14841]
11111111111111111111
incomplete name 3, col: 14841 row: []
col: 14842 similar rows:  [14842]
11111111111111111111
incomplete name 3, col: 14842 row: []
col: 14846 similar rows:  [14846]
11111111111111111111
hotelname2 [14846]
incomplete name 3, col: 14846 row: [14846]
col: 14847 similar rows:  [14847, 14970, 15094, 15140, 15178]
incomplete name 3, col: 14847 row: []
col: 14850 similar rows:  [14850]
11111111111111111111
hotelname2 [14850]
incomplete name 3, col: 14850 row: [14850]
col: 14852 similar rows:  [14852, 14905, 14946, 15017, 15112, 15148]
incomplete name 3, col: 14852 row: []
col: 14854 similar rows:  [14854, 15117]
incomplete name 3, col: 14854 row: []
col: 14858 similar rows:  [14858]
11111111111111111111
incomplete name 3, col: 14858 row: []
col: 14859 similar rows:  [14859, 15061]
incomplete name 3, col: 14859 row: []
col: 14862 similar rows:  [14862]
11111111111111111111
incomplete name 3, col: 14862 row: []
col: 14864 similar rows:  [14864]
11111111111111111111
incomplete name 3, col: 14864 row: []
col: 14865 similar rows:  [14865]
11111111111111111111
incomplete name 3, col: 14865 row: []
col: 14867 similar rows:  [14867]
11111111111111111111
incomplete name 3, col: 14867 row: []
col: 14869 similar rows:  [14869]
11111111111111111111
incomplete name 3, col: 14869 row: []
col: 14873 similar rows:  [14873]
11111111111111111111
incomplete name 3, col: 14873 row: []
col: 14874 similar rows:  [14874]
11111111111111111111
incomplete name 3, col: 14874 row: []
col: 14876 similar rows:  [14876]
11111111111111111111
hotelname2 [14876]
wrong name!!!!
incomplete name 3, col: 14876 row: [14876]
col: 14880 similar rows:  [14880]
11111111111111111111
hotelname2 [14880]
incomplete name 3, col: 14880 row: [14880]
col: 14881 similar rows:  [14881]
11111111111111111111
incomplete name 3, col: 14881 row: []
col: 14883 similar rows:  [14883, 14968, 14979, 14982, 15180]
incomplete name 3, col: 14883 row: []
col: 14884 similar rows:  [14884]
11111111111111111111
incomplete name 3, col: 14884 row: []
col: 14887 similar rows:  [14887]
11111111111111111111
incomplete name 3, col: 14887 row: []
col: 14896 similar rows:  [14896]
11111111111111111111
incomplete name 3, col: 14896 row: []

col: 14898 similar rows:  [14898]
11111111111111111111
incomplete name 3, col: 14898 row: []
col: 14908 similar rows:  [14908]
11111111111111111111
incomplete name 3, col: 14908 row: []
col: 14909 similar rows:  [14909]
11111111111111111111
incomplete name 3, col: 14909 row: []
col: 14916 similar rows:  [14916]
11111111111111111111
incomplete name 3, col: 14916 row: []
col: 14923 similar rows:  [14923]
11111111111111111111
incomplete name 3, col: 14923 row: []
col: 14929 similar rows:  [14929]
11111111111111111111
incomplete name 3, col: 14929 row: []
col: 14932 similar rows:  [14932]
11111111111111111111
incomplete name 3, col: 14932 row: []
col: 14944 similar rows:  [14944]
11111111111111111111
incomplete name 3, col: 14944 row: []
col: 14950 similar rows:  [14950]
11111111111111111111
incomplete name 3, col: 14950 row: []
col: 14969 similar rows:  [14969]
11111111111111111111
incomplete name 3, col: 14969 row: []
col: 14971 similar rows:  [14971]
11111111111111111111
incomplete name 3, col: 14971 row: []
col: 14972 similar rows:  [14972]
11111111111111111111
incomplete name 3, col: 14972 row: []
col: 14973 similar rows:  [14973]
11111111111111111111
incomplete name 3, col: 14973 row: []
col: 14974 similar rows:  [14974]
11111111111111111111
hotelname2 [14974]
incomplete name 3, col: 14974 row: []
col: 14977 similar rows:  [14977]
11111111111111111111
incomplete name 3, col: 14977 row: []
col: 14983 similar rows:  [14983]
11111111111111111111
incomplete name 3, col: 14983 row: []
col: 14986 similar rows:  [14986]
11111111111111111111
incomplete name 3, col: 14986 row: []
col: 14987 similar rows:  [14987]
11111111111111111111
incomplete name 3, col: 14987 row: []
col: 14988 similar rows:  [14988]
11111111111111111111
incomplete name 3, col: 14988 row: []
col: 14989 similar rows:  [14989]
11111111111111111111
incomplete name 3, col: 14989 row: []
col: 14992 similar rows:  [14992]
11111111111111111111
hotelname2 [14992]
incomplete name 3, col: 14992 row: [14992]
col: 14994 similar rows:  [14994]
11111111111111111111
incomplete name 3, col: 14994 row: []
col: 14995 similar rows:  [14995]
11111111111111111111
incomplete name 3, col: 14995 row: []
col: 14996 similar rows:  [14996]
11111111111111111111
incomplete name 3, col: 14996 row: []
col: 14998 similar rows:  [14998]
11111111111111111111
incomplete name 3, col: 14998 row: []
col: 15005 similar rows:  [15005]
11111111111111111111
incomplete name 3, col: 15005 row: []
col: 15015 similar rows:  [15015, 15211]
incomplete name 3, col: 15015 row: []
col: 15021 similar rows:  [15021]
11111111111111111111
incomplete name 3, col: 15021 row: []
col: 15023 similar rows:  [15023]
11111111111111111111
incomplete name 3, col: 15023 row: []
col: 15026 similar rows:  [15026]
11111111111111111111
incomplete name 3, col: 15026 row: []
col: 15028 similar rows:  [15028]
11111111111111111111
incomplete name 3, col: 15028 row: []
col: 15032 similar rows:  [15032]
11111111111111111111
incomplete name 3, col: 15032 row: []
col: 15039 similar rows:  [15039]
11111111111111111111
incomplete name 3, col: 15039 row: []
col: 15040 similar rows:  [15040]
11111111111111111111
incomplete name 3, col: 15040 row: []
col: 15041 similar rows:  [15041]
11111111111111111111
incomplete name 3, col: 15041 row: []
col: 15048 similar rows:  [15048]
11111111111111111111
incomplete name 3, col: 15048 row: []
col: 15050 similar rows:  [15050]
11111111111111111111
incomplete name 3, col: 15050 row: []
col: 15051 similar rows:  [15051]
11111111111111111111
incomplete name 3, col: 15051 row: []
col: 15052 similar rows:  [15052]
11111111111111111111
incomplete name 3, col: 15052 row: []
col: 15053 similar rows:  [15053, 15161]
incomplete name 3, col: 15053 row: []
col: 15055 similar rows:  [15055]
11111111111111111111
incomplete name 3, col: 15055 row: []
col: 15058 similar rows:  [15058]
11111111111111111111
hotelname2 [15058]
incomplete name 3, col: 15058 row: [15058]
col: 15063 similar rows:  [15063]
11111111111111111111
incomplete name 3, col: 15063 row: []
col: 15064 similar rows:  [15064]
11111111111111111111
incomplete name 3, col: 15064 row: []
col: 15069 similar rows:  [15069]
11111111111111111111
incomplete name 3, col: 15069 row: []
col: 15070 similar rows:  [15070]
11111111111111111111
incomplete name 3, col: 15070 row: []
col: 15072 similar rows:  [15072]
11111111111111111111
incomplete name 3, col: 15072 row: []
col: 15075 similar rows:  [15075]
11111111111111111111
incomplete name 3, col: 15075 row: []
col: 15076 similar rows:  [15076]
11111111111111111111
incomplete name 3, col: 15076 row: []
col: 15078 similar rows:  [15078]
11111111111111111111
incomplete name 3, col: 15078 row: []
col: 15080 similar rows:  [15080]
11111111111111111111
incomplete name 3, col: 15080 row: []
col: 15081 similar rows:  [15081]
11111111111111111111
incomplete name 3, col: 15081 row: []
col: 15082 similar rows:  [15082]
11111111111111111111
incomplete name 3, col: 15082 row: []
col: 15083 similar rows:  [15083]
11111111111111111111
incomplete name 3, col: 15083 row: []
col: 15088 similar rows:  [15088]
11111111111111111111
incomplete name 3, col: 15088 row: []
col: 15090 similar rows:  [15090]
11111111111111111111
incomplete name 3, col: 15090 row: []
col: 15110 similar rows:  [15110]
11111111111111111111
incomplete name 3, col: 15110 row: []
col: 15111 similar rows:  [15111]
11111111111111111111
incomplete name 3, col: 15111 row: []
col: 15119 similar rows:  [15119]
11111111111111111111
incomplete name 3, col: 15119 row: []
col: 15124 similar rows:  [15124]
11111111111111111111
hotelname2 [15124]
wrong name!!!!
incomplete name 3, col: 15124 row: [15124]
col: 15128 similar rows:  [15128]
11111111111111111111
incomplete name 3, col: 15128 row: []
col: 15129 similar rows:  [15129]
11111111111111111111
incomplete name 3, col: 15129 row: []
col: 15130 similar rows:  [15130]
11111111111111111111
incomplete name 3, col: 15130 row: []
col: 15132 similar rows:  [15132]
11111111111111111111
incomplete name 3, col: 15132 row: []
col: 15136 similar rows:  [15136]
11111111111111111111
hotelname2 [15136]
incomplete name 3, col: 15136 row: [15136]
col: 15141 similar rows:  [15141]
11111111111111111111
incomplete name 3, col: 15141 row: []
col: 15142 similar rows:  [15142]
11111111111111111111
incomplete name 3, col: 15142 row: []
col: 15145 similar rows:  [15145]
11111111111111111111
incomplete name 3, col: 15145 row: []
col: 15146 similar rows:  [15146]
11111111111111111111
incomplete name 3, col: 15146 row: []
col: 15154 similar rows:  [15154]
11111111111111111111
incomplete name 3, col: 15154 row: []
col: 15156 similar rows:  [15156]
11111111111111111111
incomplete name 3, col: 15156 row: []
col: 15157 similar rows:  [15157]
11111111111111111111
incomplete name 3, col: 15157 row: []
col: 15158 similar rows:  [15158, 15159, 15247, 15248]
incomplete name 3, col: 15158 row: []
col: 15160 similar rows:  [15160]
11111111111111111111
incomplete name 3, col: 15160 row: []
col: 15162 similar rows:  [15162]
11111111111111111111
incomplete name 3, col: 15162 row: []
col: 15163 similar rows:  [15163]
11111111111111111111
incomplete name 3, col: 15163 row: []
col: 15164 similar rows:  [15164]
11111111111111111111
incomplete name 3, col: 15164 row: []
col: 15167 similar rows:  [15167]
11111111111111111111
incomplete name 3, col: 15167 row: []
col: 15168 similar rows:  [15168]
11111111111111111111
incomplete name 3, col: 15168 row: []
col: 15174 similar rows:  [15174]
11111111111111111111
incomplete name 3, col: 15174 row: []
col: 15179 similar rows:  [15179]
11111111111111111111
incomplete name 3, col: 15179 row: []
col: 15186 similar rows:  [15186]
11111111111111111111
incomplete name 3, col: 15186 row: []
col: 15193 similar rows:  [15193]
11111111111111111111
incomplete name 3, col: 15193 row: []
col: 15197 similar rows:  [15197]
11111111111111111111
incomplete name 3, col: 15197 row: []
col: 15207 similar rows:  [15207]
11111111111111111111
incomplete name 3, col: 15207 row: []
col: 15208 similar rows:  [15208]
11111111111111111111
incomplete name 3, col: 15208 row: []
col: 15218 similar rows:  [15218]
11111111111111111111
incomplete name 3, col: 15218 row: []
col: 15219 similar rows:  [15219]
11111111111111111111
hotelname2 [15219]
incomplete name 3, col: 15219 row: [15219]

col: 15223 similar rows:  [15223]
11111111111111111111
incomplete name 3, col: 15223 row: []
col: 15233 similar rows:  [15233]
11111111111111111111
hotelname2 [15233]
incomplete name 3, col: 15233 row: [15233]
col: 15234 similar rows:  [15234]
11111111111111111111
incomplete name 3, col: 15234 row: []
col: 15235 similar rows:  [15235]
11111111111111111111
incomplete name 3, col: 15235 row: []
col: 15238 similar rows:  [15238]
11111111111111111111
incomplete name 3, col: 15238 row: []
col: 15240 similar rows:  [15240]
11111111111111111111
incomplete name 3, col: 15240 row: []
col: 15243 similar rows:  [15243]
11111111111111111111
incomplete name 3, col: 15243 row: []
col: 15244 similar rows:  [15244]
11111111111111111111
incomplete name 3, col: 15244 row: []
col: 15249 similar rows:  [15249]
11111111111111111111
incomplete name 3, col: 15249 row: []
col: 15250 similar rows:  [15250]
11111111111111111111
incomplete name 3, col: 15250 row: []
col: 15251 similar rows:  [15251]
11111111111111111111
incomplete name 3, col: 15251 row: []
col: 15252 similar rows:  [15252]
11111111111111111111
incomplete name 3, col: 15252 row: []
col: 15256 similar rows:  [15256]
11111111111111111111
incomplete name 3, col: 15256 row: []
end
col: 4228 similar rows:  [4228]
11111111111111111111
hotelname2 [4228]
incomplete name 3, col: 4228 row: []
col: 4229 similar rows:  [4229, 6041, 6990]
incomplete name 3, col: 4229 row: []
col: 4230 similar rows:  [4230]
11111111111111111111
hotelname2 [4230]
wrong name!!!!
incomplete name 3, col: 4230 row: [4230]
col: 4231 similar rows:  [4231, 4398, 4414, 4568, 4580, 5222, 6883, 7007]
incomplete name 3, col: 4231 row: []
col: 4232 similar rows:  [4232, 4243, 4270, 4454, 4535, 4829, 5071, 5168, 5172, 5228, 5246, 5247, 5357, 5383, 5414, 5631, 5690, 5819, 5824, 6081, 6533, 6706, 6848, 7061, 7067, 7133]
incomplete name 3, col: 4232 row: []
col: 4233 similar rows:  [4233, 4237, 4282, 4908, 5549, 5636, 5952, 6193]
incomplete name 3, col: 4233 row: []
col: 4234 similar rows:  [4234, 4345, 4517, 4924, 5088, 5223, 5260, 5617, 5630, 5861, 6711, 6715]
incomplete name 3, col: 4234 row: []
col: 4235 similar rows:  [4235]
11111111111111111111
incomplete name 3, col: 4235 row: []
col: 4236 similar rows:  [4236, 4296, 4301, 4850, 5007, 5277, 5420, 5608, 5833, 6281, 6962]
incomplete name 3, col: 4236 row: []
col: 4238 similar rows:  [4238, 5070, 5865, 6430, 6698, 6705, 6855]
incomplete name 3, col: 4238 row: []
col: 4239 similar rows:  [4239, 5119, 5846, 6176, 6492, 6723]
incomplete name 3, col: 4239 row: []
col: 4240 similar rows:  [4240]
11111111111111111111
incomplete name 3, col: 4240 row: []
col: 4241 similar rows:  [4241, 4248, 4544, 7161]
incomplete name 3, col: 4241 row: []
col: 4242 similar rows:  [4242]
11111111111111111111
incomplete name 3, col: 4242 row: []
col: 4244 similar rows:  [4244, 4315, 4412, 5965, 6915]
incomplete name 3, col: 4244 row: []
col: 4245 similar rows:  [4245, 4883]
incomplete name 3, col: 4245 row: []
col: 4246 similar rows:  [4246, 5402, 6214, 6374]
incomplete name 3, col: 4246 row: []
col: 4247 similar rows:  [4247, 4293, 4304, 4354, 4439, 4604, 4886, 5014, 5282, 5446, 5463, 5469, 5498, 5639, 5665, 5680, 5837, 5839, 5872, 5884, 5888, 5960, 6084, 6192, 6263, 6377, 6403, 6426, 6462, 6798, 6886, 7148]
incomplete name 3, col: 4247 row: []
col: 4249 similar rows:  [4249, 4415, 4560, 4936, 5166, 5311, 5331, 5554, 5725, 5789, 6345, 6842, 7198]
incomplete name 3, col: 4249 row: []
col: 4250 similar rows:  [4250, 5827]
incomplete name 3, col: 4250 row: []
col: 4251 similar rows:  [4251, 4425, 5048, 5115, 5183, 5619, 5910, 6106, 6181, 6461, 6521, 6557, 6596, 6787]
incomplete name 3, col: 4251 row: []
col: 4252 similar rows:  [4252, 5729, 5812, 5983]
incomplete name 3, col: 4252 row: []
col: 4253 similar rows:  [4253]
11111111111111111111
incomplete name 3, col: 4253 row: []
col: 4254 similar rows:  [4254, 5031, 5926, 5948, 6726, 6832]
incomplete name 3, col: 4254 row: []
col: 4255 similar rows:  [4255, 4386, 4889, 5041, 5699, 5843, 6191, 6456, 6708]
incomplete name 3, col: 4255 row: []
col: 4256 similar rows:  [4256, 4379, 4457, 5038, 5148, 5248, 5249, 5252, 5261, 5271, 5390, 5399, 5603, 5909, 5927, 5932, 5935, 6066, 6433, 6523, 6686, 6845, 6852, 7118, 7140, 7207]
incomplete name 3, col: 4256 row: []
col: 4257 similar rows:  [4257, 4260, 4321, 4477, 4518, 5611, 5638, 6366]
incomplete name 3, col: 4257 row: []
col: 4258 similar rows:  [4258, 6003, 6102, 6103, 6390, 6637, 7074]
hotelname2 [6637]
incomplete name 3, col: 4258 row: [6637]
col: 4259 similar rows:  [4259, 4374, 4401, 4539, 4751, 4922, 5721, 6920, 7017, 7178]
incomplete name 3, col: 4259 row: []
col: 4261 similar rows:  [4261, 4470, 4837, 5380, 5392, 5834]
incomplete name 3, col: 4261 row: []
col: 4262 similar rows:  [4262, 5103, 5123, 5126, 5360, 5375, 5449, 5545, 5616]
incomplete name 3, col: 4262 row: []
col: 4263 similar rows:  [4263, 4690, 5364, 5581, 5939, 5995, 6140, 6356, 6586, 6666, 6672, 6682, 6776, 6917]
incomplete name 3, col: 4263 row: []
col: 4264 similar rows:  [4264, 4497, 5501, 5740, 6113, 6138, 6168, 6421, 6895, 7011]
incomplete name 3, col: 4264 row: []
col: 4265 similar rows:  [4265, 4325, 4713, 4943, 5743, 5870, 6052, 6073, 6361, 6556, 6615, 6773, 6959, 6972]
incomplete name 3, col: 4265 row: []
col: 4266 similar rows:  [4266, 5294, 5661, 6820, 6918, 7030]
incomplete name 3, col: 4266 row: []
col: 4267 similar rows:  [4267]
11111111111111111111
incomplete name 3, col: 4267 row: []
col: 4268 similar rows:  [4268, 5035, 5606, 5657, 6062, 6277, 7037]
incomplete name 3, col: 4268 row: []
col: 4269 similar rows:  [4269]
11111111111111111111
incomplete name 3, col: 4269 row: []
col: 4271 similar rows:  [4271]
11111111111111111111
incomplete name 3, col: 4271 row: []
col: 4272 similar rows:  [4272, 4330, 4487, 4707, 5047, 5577, 5706, 5962, 6083, 6190, 6211, 6228, 6235, 6298, 6471, 6597, 6612, 6978]
incomplete name 3, col: 4272 row: []
col: 4273 similar rows:  [4273]
11111111111111111111
incomplete name 3, col: 4273 row: []
col: 4274 similar rows:  [4274]
11111111111111111111
hotelname2 [4274]
incomplete name 3, col: 4274 row: []
col: 4275 similar rows:  [4275]
11111111111111111111
incomplete name 3, col: 4275 row: []
col: 4276 similar rows:  [4276, 6772]
incomplete name 3, col: 4276 row: []
col: 4277 similar rows:  [4277]
11111111111111111111
incomplete name 3, col: 4277 row: []
col: 4278 similar rows:  [4278, 4313, 4475, 4502, 4645, 5019, 5057, 5677, 6424, 6778, 6812, 7068]
incomplete name 3, col: 4278 row: []
col: 4279 similar rows:  [4279, 5163, 5504, 5634, 6446]
incomplete name 3, col: 4279 row: []
col: 4280 similar rows:  [4280, 6501]
incomplete name 3, col: 4280 row: []
col: 4281 similar rows:  [4281, 4333, 4907, 5072, 5487, 6152, 6375, 6440, 6482, 7190]
incomplete name 3, col: 4281 row: []
col: 4283 similar rows:  [4283, 6542]
incomplete name 3, col: 4283 row: []
col: 4284 similar rows:  [4284, 4449, 5017, 5065, 5219]
incomplete name 3, col: 4284 row: []
col: 4285 similar rows:  [4285, 4442, 6043]
incomplete name 3, col: 4285 row: []
col: 4286 similar rows:  [4286, 5806]
incomplete name 3, col: 4286 row: []
col: 4287 similar rows:  [4287]
11111111111111111111
incomplete name 3, col: 4287 row: []
col: 4288 similar rows:  [4288, 5836, 6414]
incomplete name 3, col: 4288 row: []
col: 4289 similar rows:  [4289, 5589, 5928, 5959, 6337, 6449, 6681, 6718, 7057]
incomplete name 3, col: 4289 row: []
col: 4290 similar rows:  [4290, 5018, 5116, 6805]
incomplete name 3, col: 4290 row: []
col: 4291 similar rows:  [4291, 5011, 7199]
incomplete name 3, col: 4291 row: []
col: 4292 similar rows:  [4292, 5430]
incomplete name 3, col: 4292 row: []
col: 4294 similar rows:  [4294, 5002, 5046, 6713]
incomplete name 3, col: 4294 row: []
col: 4295 similar rows:  [4295]
11111111111111111111
hotelname2 [4295]
incomplete name 3, col: 4295 row: []
col: 4297 similar rows:  [4297, 5903, 5922, 6201, 6890]
incomplete name 3, col: 4297 row: []
col: 4298 similar rows:  [4298, 4342, 4724]
hotelname2 [4342]
incomplete name 3, col: 4298 row: [4342]
col: 4299 similar rows:  [4299]
11111111111111111111
hotelname2 [4299]
incomplete name 3, col: 4299 row: []
col: 4300 similar rows:  [4300]
11111111111111111111
incomplete name 3, col: 4300 row: []
col: 4302 similar rows:  [4302, 7125]
incomplete name 3, col: 4302 row: []
col: 4303 similar rows:  [4303, 4505, 5043, 5400, 6826, 6857, 7114]
incomplete name 3, col: 4303 row: []
col: 4305 similar rows:  [4305, 5161, 5412, 5478, 6830]
hotelname2 [5478]
incomplete name 3, col: 4305 row: []
col: 4306 similar rows:  [4306, 5436]
incomplete name 3, col: 4306 row: []
col: 4307 similar rows:  [4307, 4820, 5085, 5106, 5209, 5234, 5238, 5275, 5337, 5668, 5705, 5707, 5934]
incomplete name 3, col: 4307 row: []

col: 4308 similar rows:  [4308, 4515, 5090, 5342, 5382, 5840, 6797, 6967, 7095]
incomplete name 3, col: 4308 row: []
col: 4309 similar rows:  [4309, 4533, 5039, 5641, 5841, 6255, 6853]
incomplete name 3, col: 4309 row: []
col: 4310 similar rows:  [4310, 5060, 5095, 5663, 6204, 6675]
incomplete name 3, col: 4310 row: []
col: 4311 similar rows:  [4311, 4540, 4771, 5348, 5868, 6352, 6558, 7122]
incomplete name 3, col: 4311 row: []
col: 4312 similar rows:  [4312]
11111111111111111111
incomplete name 3, col: 4312 row: []
col: 4314 similar rows:  [4314]
11111111111111111111
incomplete name 3, col: 4314 row: []
col: 4316 similar rows:  [4316, 5134, 6199, 6950]
incomplete name 3, col: 4316 row: []
col: 4317 similar rows:  [4317, 4395, 4453, 4542, 4691, 4693, 4822, 4892, 5009, 5061, 5206, 5353, 5607, 5670, 5688, 5875, 6380, 6774, 6807, 6813, 6841, 7023, 7040, 7076]
incomplete name 3, col: 4317 row: []
col: 4318 similar rows:  [4318]
11111111111111111111
incomplete name 3, col: 4318 row: []
col: 4319 similar rows:  [4319]
11111111111111111111
incomplete name 3, col: 4319 row: []
col: 4320 similar rows:  [4320, 5274, 6829, 7132]
incomplete name 3, col: 4320 row: []
col: 4322 similar rows:  [4322, 6684]
incomplete name 3, col: 4322 row: []
col: 4323 similar rows:  [4323, 4443, 4634, 4726, 4894, 5293, 5448, 5681, 5719, 5826, 6353, 6923, 7137]
incomplete name 3, col: 4323 row: []
col: 4324 similar rows:  [4324]
11111111111111111111
incomplete name 3, col: 4324 row: []
col: 4326 similar rows:  [4326, 4607, 4897, 5475, 5898, 5953, 6359, 6653, 6900, 7151]
incomplete name 3, col: 4326 row: []
col: 4327 similar rows:  [4327, 6101, 6980]
incomplete name 3, col: 4327 row: []
col: 4328 similar rows:  [4328, 4902, 5120, 5426, 6580, 6777]
incomplete name 3, col: 4328 row: []
col: 4329 similar rows:  [4329, 4728, 4782, 4843, 5158, 5215, 5324, 5471, 5483, 5694, 5787, 5912, 5916, 6171, 6212, 6538, 6592, 6703, 6964, 6979, 6992, 7159, 7189]
incomplete name 3, col: 4329 row: []
col: 4331 similar rows:  [4331, 4347, 4514, 4799, 4800, 4819, 4847, 4959, 4960, 5227, 5671, 5686, 5700, 5890, 6246, 6369, 6744, 6874, 6935, 6969, 7065]
incomplete name 3, col: 4331 row: []
col: 4332 similar rows:  [4332, 5714, 5878, 7187]
incomplete name 3, col: 4332 row: []
col: 4334 similar rows:  [4334, 4644, 5377]
incomplete name 3, col: 4334 row: []
col: 4335 similar rows:  [4335, 5008, 5620, 5637, 6504]
incomplete name 3, col: 4335 row: []
col: 4336 similar rows:  [4336, 4531, 5107, 5372, 5395, 5646, 5911, 6582, 6676, 6688, 6770]
incomplete name 3, col: 4336 row: []
col: 4337 similar rows:  [4337, 6991]
incomplete name 3, col: 4337 row: []
col: 4338 similar rows:  [4338]
11111111111111111111
incomplete name 3, col: 4338 row: []
col: 4339 similar rows:  [4339, 4370, 4403, 4495, 4605, 5811, 6028, 6070, 6350, 6944, 6963, 7047]
incomplete name 3, col: 4339 row: []
col: 4340 similar rows:  [4340, 4541]
incomplete name 3, col: 4340 row: []
col: 4341 similar rows:  [4341]
11111111111111111111
incomplete name 3, col: 4341 row: []
col: 4343 similar rows:  [4343]
11111111111111111111
incomplete name 3, col: 4343 row: []
col: 4344 similar rows:  [4344, 4640, 6881, 6892, 6906]
incomplete name 3, col: 4344 row: []
col: 4346 similar rows:  [4346, 5179]
incomplete name 3, col: 4346 row: []
col: 4348 similar rows:  [4348, 4349, 4419, 4424, 5273]
incomplete name 3, col: 4348 row: []
col: 4350 similar rows:  [4350, 4400]
incomplete name 3, col: 4350 row: []
col: 4351 similar rows:  [4351]
11111111111111111111
hotelname2 [4351]
incomplete name 3, col: 4351 row: []
col: 4352 similar rows:  [4352]
11111111111111111111
hotelname2 [4352]
incomplete name 3, col: 4352 row: [4352]
col: 4353 similar rows:  [4353, 6286]
incomplete name 3, col: 4353 row: []
col: 4355 similar rows:  [4355, 4428, 5070, 5121, 5241, 5262, 5410, 5563, 5583, 5623, 6531, 6667, 6705, 6859, 6934, 7117, 7155]
incomplete name 3, col: 4355 row: []
col: 4356 similar rows:  [4356, 4388, 4582, 4753, 5133, 5299, 5482, 5938, 6301, 6468, 6484, 6599, 7026, 7075]
incomplete name 3, col: 4356 row: []
col: 4357 similar rows:  [4357, 6491, 6539]
incomplete name 3, col: 4357 row: []
col: 4358 similar rows:  [4358, 6031]
incomplete name 3, col: 4358 row: []
col: 4359 similar rows:  [4359]
11111111111111111111
incomplete name 3, col: 4359 row: []
col: 4360 similar rows:  [4360]
11111111111111111111
incomplete name 3, col: 4360 row: []
col: 4361 similar rows:  [4361]
11111111111111111111
hotelname2 [4361]
incomplete name 3, col: 4361 row: [4361]
col: 4362 similar rows:  [4362, 5280, 5465, 5918, 6139, 6257]
incomplete name 3, col: 4362 row: []
col: 4363 similar rows:  [4363, 5776]
incomplete name 3, col: 4363 row: []
col: 4364 similar rows:  [4364]
11111111111111111111
incomplete name 3, col: 4364 row: []
col: 4365 similar rows:  [4365]
11111111111111111111
incomplete name 3, col: 4365 row: []
col: 4366 similar rows:  [4366]
11111111111111111111
incomplete name 3, col: 4366 row: []
col: 4367 similar rows:  [4367, 4754, 7215]
incomplete name 3, col: 4367 row: []
col: 4368 similar rows:  [4368]
11111111111111111111
incomplete name 3, col: 4368 row: []
col: 4369 similar rows:  [4369]
11111111111111111111
incomplete name 3, col: 4369 row: []
col: 4371 similar rows:  [4371]
11111111111111111111
incomplete name 3, col: 4371 row: []
col: 4372 similar rows:  [4372]
11111111111111111111
incomplete name 3, col: 4372 row: []
col: 4373 similar rows:  [4373]
11111111111111111111
incomplete name 3, col: 4373 row: []
col: 4375 similar rows:  [4375, 4577]
incomplete name 3, col: 4375 row: []
col: 4376 similar rows:  [4376]
11111111111111111111
incomplete name 3, col: 4376 row: []
col: 4377 similar rows:  [4377]
11111111111111111111
incomplete name 3, col: 4377 row: []
col: 4378 similar rows:  [4378, 5101, 5585, 6469, 6903]
incomplete name 3, col: 4378 row: []
col: 4380 similar rows:  [4380, 6477]
incomplete name 3, col: 4380 row: []
col: 4381 similar rows:  [4381]
11111111111111111111
incomplete name 3, col: 4381 row: []
col: 4382 similar rows:  [4382]
11111111111111111111
incomplete name 3, col: 4382 row: []
col: 4383 similar rows:  [4383, 4489, 6076]
incomplete name 3, col: 4383 row: []
col: 4384 similar rows:  [4384]
11111111111111111111
incomplete name 3, col: 4384 row: []
col: 4385 similar rows:  [4385]
11111111111111111111
incomplete name 3, col: 4385 row: []
col: 4387 similar rows:  [4387]
11111111111111111111
incomplete name 3, col: 4387 row: []
col: 4389 similar rows:  [4389]
11111111111111111111
incomplete name 3, col: 4389 row: []
col: 4390 similar rows:  [4390, 5182, 6129, 6451, 6453, 6584]
incomplete name 3, col: 4390 row: []
col: 4391 similar rows:  [4391]
11111111111111111111
incomplete name 3, col: 4391 row: []
col: 4392 similar rows:  [4392]
11111111111111111111
hotelname2 [4392]
incomplete name 3, col: 4392 row: [4392]
col: 4393 similar rows:  [4393]
11111111111111111111
hotelname2 [4393]
wrong name!!!!
incomplete name 3, col: 4393 row: [4393]
col: 4394 similar rows:  [4394, 4588, 5284, 5401, 5493, 5784, 6063, 6077, 6131, 6223, 6225, 6241, 6594, 7003, 7108, 7116, 7157, 7172]
incomplete name 3, col: 4394 row: []
col: 4396 similar rows:  [4396]
11111111111111111111
hotelname2 [4396]
incomplete name 3, col: 4396 row: [4396]
col: 4397 similar rows:  [4397, 6731, 7029]
incomplete name 3, col: 4397 row: []
col: 4399 similar rows:  [4399, 4942, 7010, 7088, 7115]
incomplete name 3, col: 4399 row: []
col: 4402 similar rows:  [4402, 4855, 4870, 5141, 5338, 5339, 5378, 5389, 5702, 5703, 5708, 5762, 6142, 6200, 6240, 6264, 6503, 6613, 6868, 7064, 7086, 7106, 7180]
incomplete name 3, col: 4402 row: []
col: 4404 similar rows:  [4404, 6187, 6588]
incomplete name 3, col: 4404 row: []
col: 4405 similar rows:  [4405, 5182, 6129, 6584]
incomplete name 3, col: 4405 row: []
col: 4406 similar rows:  [4406]
11111111111111111111
hotelname2 [4406]
incomplete name 3, col: 4406 row: [4406]
col: 4407 similar rows:  [4407, 4556, 4561, 4612, 5495, 5567, 6161, 6262]
incomplete name 3, col: 4407 row: []
col: 4408 similar rows:  [4408, 4420, 4749, 5594, 5794, 5998, 6741]
incomplete name 3, col: 4408 row: []
col: 4409 similar rows:  [4409, 4679, 4688, 4702, 5351, 5387, 5429, 5852, 6057, 6233, 7028, 7082]
incomplete name 3, col: 4409 row: []
col: 4410 similar rows:  [4410, 4458, 4915, 5044, 5208, 5233, 5629, 6809, 7085]
incomplete name 3, col: 4410 row: []
col: 4411 similar rows:  [4411]
11111111111111111111
incomplete name 3, col: 4411 row: []

col: 4413 similar rows:  [4413, 7219]
incomplete name 3, col: 4413 row: []
col: 4416 similar rows:  [4416, 5421, 5720, 5851]
incomplete name 3, col: 4416 row: []
col: 4417 similar rows:  [4417]
11111111111111111111
incomplete name 3, col: 4417 row: []
col: 4418 similar rows:  [4418]
11111111111111111111
incomplete name 3, col: 4418 row: []
col: 4421 similar rows:  [4421, 6630, 7041]
incomplete name 3, col: 4421 row: []
col: 4422 similar rows:  [4422, 5101, 5585, 5930, 6469, 6753, 6903]
incomplete name 3, col: 4422 row: []
col: 4423 similar rows:  [4423, 6438, 6570, 6996]
incomplete name 3, col: 4423 row: []
col: 4426 similar rows:  [4426, 4587]
incomplete name 3, col: 4426 row: []
col: 4427 similar rows:  [4427]
11111111111111111111
incomplete name 3, col: 4427 row: []
col: 4429 similar rows:  [4429]
11111111111111111111
incomplete name 3, col: 4429 row: []
col: 4430 similar rows:  [4430, 4436]
incomplete name 3, col: 4430 row: []
col: 4431 similar rows:  [4431]
11111111111111111111
incomplete name 3, col: 4431 row: []
col: 4432 similar rows:  [4432, 6276]
incomplete name 3, col: 4432 row: []
col: 4433 similar rows:  [4433, 6602]
incomplete name 3, col: 4433 row: []
col: 4434 similar rows:  [4434]
11111111111111111111
incomplete name 3, col: 4434 row: []
col: 4435 similar rows:  [4435, 5812, 5983, 6275, 6603]
incomplete name 3, col: 4435 row: []
col: 4437 similar rows:  [4437]
11111111111111111111
incomplete name 3, col: 4437 row: []
col: 4438 similar rows:  [4438]
11111111111111111111
incomplete name 3, col: 4438 row: []
col: 4440 similar rows:  [4440, 5192, 5943, 6338, 7005]
incomplete name 3, col: 4440 row: []
col: 4441 similar rows:  [4441]
11111111111111111111
incomplete name 3, col: 4441 row: []
col: 4444 similar rows:  [4444, 4480, 5790, 6033, 6755]
incomplete name 3, col: 4444 row: []
col: 4445 similar rows:  [4445, 7101]
incomplete name 3, col: 4445 row: []
col: 4446 similar rows:  [4446, 4720, 5213, 5535, 5895, 6024, 6189, 6351, 6427, 6481, 7164]
incomplete name 3, col: 4446 row: []
col: 4447 similar rows:  [4447, 5013, 5084, 5086, 5110, 5632, 5913, 6668, 6808]
incomplete name 3, col: 4447 row: []
col: 4448 similar rows:  [4448, 4664]
incomplete name 3, col: 4448 row: []
col: 4450 similar rows:  [4450]
11111111111111111111
incomplete name 3, col: 4450 row: []
col: 4451 similar rows:  [4451, 4504, 5411, 6689]
incomplete name 3, col: 4451 row: []
col: 4452 similar rows:  [4452, 5652, 6693, 6735]
incomplete name 3, col: 4452 row: []
col: 4455 similar rows:  [4455]
11111111111111111111
hotelname2 [4455]
incomplete name 3, col: 4455 row: [4455]
col: 4456 similar rows:  [4456]
11111111111111111111
hotelname2 [4456]
incomplete name 3, col: 4456 row: []
col: 4459 similar rows:  [4459, 5590, 5848, 6292, 6372, 6513, 6948]
incomplete name 3, col: 4459 row: []
col: 4460 similar rows:  [4460]
11111111111111111111
incomplete name 3, col: 4460 row: []
col: 4461 similar rows:  [4461, 4486, 4830, 4839, 5658, 5756, 6784]
incomplete name 3, col: 4461 row: []
col: 4462 similar rows:  [4462, 5020, 5243, 5415, 5419, 5552, 5622, 5766, 6064, 6669, 6670, 6714]
incomplete name 3, col: 4462 row: []
col: 4463 similar rows:  [4463, 5816, 6465]
incomplete name 3, col: 4463 row: []
col: 4464 similar rows:  [4464]
11111111111111111111
incomplete name 3, col: 4464 row: []
col: 4465 similar rows:  [4465, 4784, 4938, 4983, 4984, 5188, 5645, 5669, 5730, 5751, 6065, 6520, 6617]
incomplete name 3, col: 4465 row: []
col: 4466 similar rows:  [4466, 6150, 7093]
incomplete name 3, col: 4466 row: []
col: 4467 similar rows:  [4467]
11111111111111111111
incomplete name 3, col: 4467 row: []
col: 4468 similar rows:  [4468, 5124, 6816]
incomplete name 3, col: 4468 row: []
col: 4469 similar rows:  [4469]
11111111111111111111
hotelname2 [4469]
incomplete name 3, col: 4469 row: [4469]
col: 4471 similar rows:  [4471]
11111111111111111111
incomplete name 3, col: 4471 row: []
col: 4472 similar rows:  [4472, 5662, 6719, 7096]
incomplete name 3, col: 4472 row: []
col: 4473 similar rows:  [4473, 4696, 4997, 5633, 5922, 6782, 6890]
incomplete name 3, col: 4473 row: []
col: 4474 similar rows:  [4474, 5439, 6419]
incomplete name 3, col: 4474 row: []
col: 4476 similar rows:  [4476, 4921, 5767, 7000]
incomplete name 3, col: 4476 row: []
col: 4478 similar rows:  [4478]
11111111111111111111
incomplete name 3, col: 4478 row: []
col: 4479 similar rows:  [4479, 4488, 4523, 4609, 4700, 5278, 5625, 5666, 5744, 6466, 6507, 6574, 6601]
incomplete name 3, col: 4479 row: []
col: 4481 similar rows:  [4481, 5173, 5224, 5333, 5368, 6370]
incomplete name 3, col: 4481 row: []
col: 4482 similar rows:  [4482, 4823, 4863]
incomplete name 3, col: 4482 row: []
col: 4483 similar rows:  [4483, 6371, 6516]
incomplete name 3, col: 4483 row: []
col: 4484 similar rows:  [4484, 4817, 5012, 5076, 6335, 6493]
incomplete name 3, col: 4484 row: []
col: 4485 similar rows:  [4485, 4492, 4875]
incomplete name 3, col: 4485 row: []
col: 4490 similar rows:  [4490, 5055, 5815, 5820]
incomplete name 3, col: 4490 row: []
col: 4491 similar rows:  [4491, 5062, 6786]
incomplete name 3, col: 4491 row: []
col: 4493 similar rows:  [4493]
11111111111111111111
hotelname2 [4493]
incomplete name 3, col: 4493 row: [4493]
col: 4494 similar rows:  [4494]
11111111111111111111
hotelname2 [4494]
incomplete name 3, col: 4494 row: []
col: 4496 similar rows:  [4496]
11111111111111111111
hotelname2 [4496]
incomplete name 3, col: 4496 row: []
col: 4498 similar rows:  [4498]
11111111111111111111
hotelname2 [4498]
incomplete name 3, col: 4498 row: [4498]
col: 4499 similar rows:  [4499, 5026, 5125, 5210, 5230, 5723, 5864]
incomplete name 3, col: 4499 row: []
col: 4500 similar rows:  [4500]
11111111111111111111
incomplete name 3, col: 4500 row: []
col: 4501 similar rows:  [4501, 6341]
incomplete name 3, col: 4501 row: []
col: 4503 similar rows:  [4503, 6529, 6549, 6690]
incomplete name 3, col: 4503 row: []
col: 4506 similar rows:  [4506]
11111111111111111111
incomplete name 3, col: 4506 row: []
col: 4507 similar rows:  [4507, 5745]
incomplete name 3, col: 4507 row: []
col: 4508 similar rows:  [4508, 6404]
incomplete name 3, col: 4508 row: []
col: 4509 similar rows:  [4509, 4887, 5180, 5359, 5386, 5539, 6728, 6891, 6946]
incomplete name 3, col: 4509 row: []
col: 4510 similar rows:  [4510, 4677]
incomplete name 3, col: 4510 row: []
col: 4511 similar rows:  [4511, 5022]
incomplete name 3, col: 4511 row: []
col: 4512 similar rows:  [4512, 4834, 5025, 5451, 5675, 5914, 6483, 7220]
incomplete name 3, col: 4512 row: []
col: 4513 similar rows:  [4513]
11111111111111111111
incomplete name 3, col: 4513 row: []
col: 4516 similar rows:  [4516, 5053, 6055]
incomplete name 3, col: 4516 row: []
col: 4519 similar rows:  [4519, 5924, 6910]
incomplete name 3, col: 4519 row: []
col: 4520 similar rows:  [4520, 4848, 5153, 5207, 6439, 6511, 6954]
incomplete name 3, col: 4520 row: []
col: 4521 similar rows:  [4521, 5024, 5033, 5178, 5968, 6691, 6824]
5024    1.000000
5033    1.000000
5178    0.793638
5968    0.883331
6691    1.000000
6824    0.901837
Name: 4521, dtype: float64
incomplete name 3, col: 4521 row: []
col: 4522 similar rows:  [4522, 4714, 4862, 6112, 6984]
incomplete name 3, col: 4522 row: []
col: 4524 similar rows:  [4524]
11111111111111111111
incomplete name 3, col: 4524 row: []
col: 4525 similar rows:  [4525, 4706, 4716, 5363, 5689, 5829, 6218, 6459, 6869, 7092, 7111, 7134]
incomplete name 3, col: 4525 row: []
col: 4526 similar rows:  [4526, 4880, 5132]
incomplete name 3, col: 4526 row: []
col: 4527 similar rows:  [4527, 4970, 5458]
incomplete name 3, col: 4527 row: []
col: 4528 similar rows:  [4528]
11111111111111111111
incomplete name 3, col: 4528 row: []
col: 4529 similar rows:  [4529]
11111111111111111111
incomplete name 3, col: 4529 row: []
col: 4530 similar rows:  [4530, 6090]
incomplete name 3, col: 4530 row: []
col: 4532 similar rows:  [4532]
11111111111111111111
incomplete name 3, col: 4532 row: []
col: 4534 similar rows:  [4534]
11111111111111111111
incomplete name 3, col: 4534 row: []
col: 4536 similar rows:  [4536]
11111111111111111111
incomplete name 3, col: 4536 row: []
col: 4537 similar rows:  [4537]
11111111111111111111
incomplete name 3, col: 4537 row: []

col: 4538 similar rows:  [4538]
11111111111111111111
incomplete name 3, col: 4538 row: []
col: 4543 similar rows:  [4543, 4812]
incomplete name 3, col: 4543 row: []
col: 4545 similar rows:  [4545]
11111111111111111111
incomplete name 3, col: 4545 row: []
col: 4546 similar rows:  [4546]
11111111111111111111
incomplete name 3, col: 4546 row: []
col: 4547 similar rows:  [4547]
11111111111111111111
incomplete name 3, col: 4547 row: []
col: 4548 similar rows:  [4548]
11111111111111111111
incomplete name 3, col: 4548 row: []
col: 4549 similar rows:  [4549, 5148, 5248, 5252, 5909, 6172, 6523, 6845, 6852, 7025]
incomplete name 3, col: 4549 row: []
col: 4550 similar rows:  [4550]
11111111111111111111
hotelname2 [4550]
incomplete name 3, col: 4550 row: [4550]
col: 4551 similar rows:  [4551]
11111111111111111111
incomplete name 3, col: 4551 row: []
col: 4552 similar rows:  [4552, 5231, 6822]
incomplete name 3, col: 4552 row: []
col: 4553 similar rows:  [4553]
11111111111111111111
incomplete name 3, col: 4553 row: []
col: 4554 similar rows:  [4554, 6354]
incomplete name 3, col: 4554 row: []
col: 4555 similar rows:  [4555, 5937]
incomplete name 3, col: 4555 row: []
col: 4557 similar rows:  [4557, 4558, 5571]
incomplete name 3, col: 4557 row: []
col: 4559 similar rows:  [4559]
11111111111111111111
hotelname2 [4559]
incomplete name 3, col: 4559 row: []
col: 4562 similar rows:  [4562]
11111111111111111111
incomplete name 3, col: 4562 row: []
col: 4563 similar rows:  [4563, 6683, 7001]
hotelname2 [7001]
incomplete name 3, col: 4563 row: []
col: 4564 similar rows:  [4564, 4569, 5398, 5966, 6069, 6157, 6470, 6498, 6811, 6815, 6873, 7054, 7185]
incomplete name 3, col: 4564 row: []
col: 4565 similar rows:  [4565]
11111111111111111111
incomplete name 3, col: 4565 row: []
col: 4566 similar rows:  [4566]
11111111111111111111
incomplete name 3, col: 4566 row: []
col: 4567 similar rows:  [4567, 4717, 5437, 6050, 6058]
incomplete name 3, col: 4567 row: []
col: 4570 similar rows:  [4570, 5877, 6158, 6365]
incomplete name 3, col: 4570 row: []
col: 4571 similar rows:  [4571, 5053, 6055]
incomplete name 3, col: 4571 row: []
col: 4572 similar rows:  [4572, 4581, 4691, 4693, 4892, 4900, 5009, 5061, 5206, 5350, 5353, 5422, 5458, 5607, 5688, 5875, 5974, 6380, 6632, 6774, 6807, 6823, 6851, 6890, 7040, 7076]
incomplete name 3, col: 4572 row: []
col: 4573 similar rows:  [4573]
11111111111111111111
incomplete name 3, col: 4573 row: []
col: 4574 similar rows:  [4574]
11111111111111111111
incomplete name 3, col: 4574 row: []
col: 4575 similar rows:  [4575, 5029, 5286, 5405, 5907, 6495, 6677, 6814]
incomplete name 3, col: 4575 row: []
col: 4576 similar rows:  [4576, 4579]
incomplete name 3, col: 4576 row: []
col: 4578 similar rows:  [4578, 5255]
incomplete name 3, col: 4578 row: []
col: 4583 similar rows:  [4583, 4730, 5562, 6540]
incomplete name 3, col: 4583 row: []
col: 4584 similar rows:  [4584, 6758]
incomplete name 3, col: 4584 row: []
col: 4585 similar rows:  [4585, 4735, 5612, 5683, 6701]
incomplete name 3, col: 4585 row: []
col: 4586 similar rows:  [4586]
11111111111111111111
hotelname2 [4586]
incomplete name 3, col: 4586 row: []
col: 4589 similar rows:  [4589, 4601, 4636, 6122]
incomplete name 3, col: 4589 row: []
col: 4590 similar rows:  [4590, 4642, 6863]
incomplete name 3, col: 4590 row: []
col: 4591 similar rows:  [4591, 4711, 5704, 6134, 6279, 6565]
incomplete name 3, col: 4591 row: []
col: 4592 similar rows:  [4592, 4595, 6636]
incomplete name 3, col: 4592 row: []
col: 4593 similar rows:  [4593, 6132, 6303]
incomplete name 3, col: 4593 row: []
col: 4594 similar rows:  [4594]
11111111111111111111
hotelname2 [4594]
incomplete name 3, col: 4594 row: []
col: 4596 similar rows:  [4596, 4635, 4926, 5140, 5276, 5283, 5298, 5329, 5949, 6116, 6148, 6266, 6870, 6872, 6878, 7133, 7139, 7176, 7210]
incomplete name 3, col: 4596 row: []
col: 4597 similar rows:  [4597, 5515]
incomplete name 3, col: 4597 row: []
col: 4598 similar rows:  [4598]
11111111111111111111
incomplete name 3, col: 4598 row: []
col: 4599 similar rows:  [4599, 4659]
incomplete name 3, col: 4599 row: []
col: 4600 similar rows:  [4600, 4692, 4698, 5250, 5394, 5614, 6435, 7202]
incomplete name 3, col: 4600 row: []
col: 4602 similar rows:  [4602]
11111111111111111111
incomplete name 3, col: 4602 row: []
col: 4603 similar rows:  [4603]
11111111111111111111
hotelname2 [4603]
incomplete name 3, col: 4603 row: []
col: 4606 similar rows:  [4606, 5966]
incomplete name 3, col: 4606 row: []
col: 4608 similar rows:  [4608]
11111111111111111111
hotelname2 [4608]
incomplete name 3, col: 4608 row: []
col: 4610 similar rows:  [4610, 6276]
incomplete name 3, col: 4610 row: []
col: 4611 similar rows:  [4611]
11111111111111111111
incomplete name 3, col: 4611 row: []
col: 4613 similar rows:  [4613, 4842, 5576]
incomplete name 3, col: 4613 row: []
col: 4614 similar rows:  [4614, 6417]
incomplete name 3, col: 4614 row: []
col: 4615 similar rows:  [4615]
11111111111111111111
incomplete name 3, col: 4615 row: []
col: 4616 similar rows:  [4616]
11111111111111111111
hotelname2 [4616]
incomplete name 3, col: 4616 row: []
col: 4617 similar rows:  [4617]
11111111111111111111
incomplete name 3, col: 4617 row: []
col: 4618 similar rows:  [4618, 4619, 4620, 4621]
incomplete name 3, col: 4618 row: []
col: 4622 similar rows:  [4622]
11111111111111111111
incomplete name 3, col: 4622 row: []
col: 4623 similar rows:  [4623]
11111111111111111111
incomplete name 3, col: 4623 row: []
col: 4624 similar rows:  [4624]
11111111111111111111
incomplete name 3, col: 4624 row: []
col: 4625 similar rows:  [4625, 4738, 5176]
incomplete name 3, col: 4625 row: []
col: 4626 similar rows:  [4626]
11111111111111111111
incomplete name 3, col: 4626 row: []
col: 4627 similar rows:  [4627]
11111111111111111111
incomplete name 3, col: 4627 row: []
col: 4628 similar rows:  [4628]
11111111111111111111
incomplete name 3, col: 4628 row: []
col: 4629 similar rows:  [4629]
11111111111111111111
incomplete name 3, col: 4629 row: []
col: 4630 similar rows:  [4630]
11111111111111111111
incomplete name 3, col: 4630 row: []
col: 4631 similar rows:  [4631, 6207]
incomplete name 3, col: 4631 row: []
col: 4632 similar rows:  [4632]
11111111111111111111
incomplete name 3, col: 4632 row: []
col: 4633 similar rows:  [4633]
11111111111111111111
incomplete name 3, col: 4633 row: []
col: 4637 similar rows:  [4637]
11111111111111111111
incomplete name 3, col: 4637 row: []
col: 4638 similar rows:  [4638, 5966]
incomplete name 3, col: 4638 row: []
col: 4639 similar rows:  [4639]
11111111111111111111
incomplete name 3, col: 4639 row: []
col: 4641 similar rows:  [4641]
11111111111111111111
incomplete name 3, col: 4641 row: []
col: 4643 similar rows:  [4643]
11111111111111111111
hotelname2 [4643]
incomplete name 3, col: 4643 row: [4643]
col: 4646 similar rows:  [4646]
11111111111111111111
incomplete name 3, col: 4646 row: []
col: 4647 similar rows:  [4647]
11111111111111111111
incomplete name 3, col: 4647 row: []
col: 4648 similar rows:  [4648]
11111111111111111111
incomplete name 3, col: 4648 row: []
col: 4649 similar rows:  [4649]
11111111111111111111
incomplete name 3, col: 4649 row: []
col: 4650 similar rows:  [4650, 5936]
incomplete name 3, col: 4650 row: []
col: 4651 similar rows:  [4651]
11111111111111111111
incomplete name 3, col: 4651 row: []
col: 4652 similar rows:  [4652, 6639]
incomplete name 3, col: 4652 row: []
col: 4653 similar rows:  [4653]
11111111111111111111
incomplete name 3, col: 4653 row: []
col: 4654 similar rows:  [4654]
11111111111111111111
incomplete name 3, col: 4654 row: []
col: 4655 similar rows:  [4655]
11111111111111111111
incomplete name 3, col: 4655 row: []
col: 4656 similar rows:  [4656]
11111111111111111111
incomplete name 3, col: 4656 row: []
col: 4657 similar rows:  [4657, 6354]
incomplete name 3, col: 4657 row: []
col: 4658 similar rows:  [4658]
11111111111111111111
incomplete name 3, col: 4658 row: []
col: 4660 similar rows:  [4660]
11111111111111111111
incomplete name 3, col: 4660 row: []
col: 4661 similar rows:  [4661]
11111111111111111111
incomplete name 3, col: 4661 row: []
col: 4662 similar rows:  [4662]
11111111111111111111
incomplete name 3, col: 4662 row: []
col: 4663 similar rows:  [4663]
11111111111111111111
incomplete name 3, col: 4663 row: []
col: 4665 similar rows:  [4665, 4920, 5310]
incomplete name 3, col: 4665 row: []
col: 4666 similar rows:  [4666]
11111111111111111111
incomplete name 3, col: 4666 row: []

col: 4667 similar rows:  [4667]
11111111111111111111
incomplete name 3, col: 4667 row: []
col: 4668 similar rows:  [4668, 7197]
incomplete name 3, col: 4668 row: []
col: 4669 similar rows:  [4669]
11111111111111111111
incomplete name 3, col: 4669 row: []
col: 4670 similar rows:  [4670]
11111111111111111111
hotelname2 [4670]
incomplete name 3, col: 4670 row: [4670]
col: 4671 similar rows:  [4671]
11111111111111111111
incomplete name 3, col: 4671 row: []
col: 4672 similar rows:  [4672]
11111111111111111111
incomplete name 3, col: 4672 row: []
col: 4673 similar rows:  [4673, 4833]
incomplete name 3, col: 4673 row: []
col: 4674 similar rows:  [4674]
11111111111111111111
incomplete name 3, col: 4674 row: []
col: 4675 similar rows:  [4675]
11111111111111111111
incomplete name 3, col: 4675 row: []
col: 4676 similar rows:  [4676]
11111111111111111111
incomplete name 3, col: 4676 row: []
col: 4678 similar rows:  [4678, 6625]
incomplete name 3, col: 4678 row: []
col: 4680 similar rows:  [4680]
11111111111111111111
incomplete name 3, col: 4680 row: []
col: 4681 similar rows:  [4681]
11111111111111111111
incomplete name 3, col: 4681 row: []
col: 4682 similar rows:  [4682]
11111111111111111111
hotelname2 [4682]
incomplete name 3, col: 4682 row: []
col: 4683 similar rows:  [4683]
11111111111111111111
incomplete name 3, col: 4683 row: []
col: 4684 similar rows:  [4684]
11111111111111111111
incomplete name 3, col: 4684 row: []
col: 4685 similar rows:  [4685]
11111111111111111111
incomplete name 3, col: 4685 row: []
col: 4686 similar rows:  [4686]
11111111111111111111
incomplete name 3, col: 4686 row: []
col: 4687 similar rows:  [4687, 6804]
incomplete name 3, col: 4687 row: []
col: 4689 similar rows:  [4689, 4763, 5264, 5786, 5849, 6631, 6783, 7160]
incomplete name 3, col: 4689 row: []
col: 4694 similar rows:  [4694, 6452]
incomplete name 3, col: 4694 row: []
col: 4695 similar rows:  [4695, 5792]
incomplete name 3, col: 4695 row: []
col: 4697 similar rows:  [4697, 5793, 6367, 6986, 7166]
incomplete name 3, col: 4697 row: []
col: 4699 similar rows:  [4699, 5384, 5715, 6347, 6479, 6497, 6577, 6606]
incomplete name 3, col: 4699 row: []
col: 4701 similar rows:  [4701]
11111111111111111111
hotelname2 [4701]
incomplete name 3, col: 4701 row: [4701]
col: 4703 similar rows:  [4703, 5184, 6953]
incomplete name 3, col: 4703 row: []
col: 4704 similar rows:  [4704, 4826, 5343, 5428, 5454, 5610, 5698, 5726, 6067, 6145, 6205, 6485, 6534, 6955, 7079, 7094, 7211]
incomplete name 3, col: 4704 row: []
col: 4705 similar rows:  [4705]
11111111111111111111
incomplete name 3, col: 4705 row: []
col: 4708 similar rows:  [4708, 5052, 5109, 5122, 5150, 5196, 5202, 5253, 5507, 5757, 5856, 5860, 6441, 6554, 6678, 7071]
incomplete name 3, col: 4708 row: []
col: 4709 similar rows:  [4709]
11111111111111111111
incomplete name 3, col: 4709 row: []
col: 4710 similar rows:  [4710]
11111111111111111111
incomplete name 3, col: 4710 row: []
col: 4712 similar rows:  [4712, 6056]
incomplete name 3, col: 4712 row: []
col: 4715 similar rows:  [4715, 6905]
incomplete name 3, col: 4715 row: []
col: 4718 similar rows:  [4718]
11111111111111111111
incomplete name 3, col: 4718 row: []
col: 4719 similar rows:  [4719, 5162, 5777]
incomplete name 3, col: 4719 row: []
col: 4721 similar rows:  [4721]
11111111111111111111
incomplete name 3, col: 4721 row: []
col: 4722 similar rows:  [4722]
11111111111111111111
incomplete name 3, col: 4722 row: []
col: 4723 similar rows:  [4723, 4815, 4856, 5127, 5216, 5543, 5779, 5873, 5921, 5944, 5958, 6295, 6568, 7014, 7016, 7056, 7063, 7069, 7135, 7136, 7162]
incomplete name 3, col: 4723 row: []
col: 4725 similar rows:  [4725, 4879, 5773]
incomplete name 3, col: 4725 row: []
col: 4727 similar rows:  [4727]
11111111111111111111
hotelname2 [4727]
incomplete name 3, col: 4727 row: [4727]
col: 4729 similar rows:  [4729, 5458]
incomplete name 3, col: 4729 row: []
col: 4731 similar rows:  [4731, 4927]
incomplete name 3, col: 4731 row: []
col: 4732 similar rows:  [4732, 5805, 6464, 6487, 6671, 6905, 7070]
incomplete name 3, col: 4732 row: []
col: 4733 similar rows:  [4733, 5105, 6202, 6844]
incomplete name 3, col: 4733 row: []
col: 4734 similar rows:  [4734, 5503, 6579, 6951]
incomplete name 3, col: 4734 row: []
col: 4736 similar rows:  [4736]
11111111111111111111
incomplete name 3, col: 4736 row: []
col: 4737 similar rows:  [4737]
11111111111111111111
incomplete name 3, col: 4737 row: []
col: 4739 similar rows:  [4739]
11111111111111111111
hotelname2 [4739]
incomplete name 3, col: 4739 row: []
col: 4740 similar rows:  [4740, 5211, 5221, 5237, 5312, 5464, 6722]
incomplete name 3, col: 4740 row: []
col: 4741 similar rows:  [4741, 6552, 6894, 7179]
incomplete name 3, col: 4741 row: []
col: 4742 similar rows:  [4742]
11111111111111111111
incomplete name 3, col: 4742 row: []
col: 4743 similar rows:  [4743]
11111111111111111111
incomplete name 3, col: 4743 row: []
col: 4744 similar rows:  [4744, 6123]
incomplete name 3, col: 4744 row: []
col: 4745 similar rows:  [4745]
11111111111111111111
incomplete name 3, col: 4745 row: []
col: 4746 similar rows:  [4746, 6626]
incomplete name 3, col: 4746 row: []
col: 4747 similar rows:  [4747]
11111111111111111111
hotelname2 [4747]
incomplete name 3, col: 4747 row: [4747]
col: 4748 similar rows:  [4748, 4766]
incomplete name 3, col: 4748 row: []
col: 4750 similar rows:  [4750]
11111111111111111111
incomplete name 3, col: 4750 row: []
col: 4752 similar rows:  [4752, 5479, 5499, 5651, 5855, 6458, 6522, 6646, 6673, 7055]
incomplete name 3, col: 4752 row: []
col: 4755 similar rows:  [4755, 5270, 5999, 6260]
incomplete name 3, col: 4755 row: []
col: 4756 similar rows:  [4756]
11111111111111111111
incomplete name 3, col: 4756 row: []
col: 4757 similar rows:  [4757]
11111111111111111111
incomplete name 3, col: 4757 row: []
col: 4758 similar rows:  [4758, 5992]
incomplete name 3, col: 4758 row: []
col: 4759 similar rows:  [4759]
11111111111111111111
incomplete name 3, col: 4759 row: []
col: 4760 similar rows:  [4760]
11111111111111111111
incomplete name 3, col: 4760 row: []
col: 4761 similar rows:  [4761]
11111111111111111111
incomplete name 3, col: 4761 row: []
col: 4762 similar rows:  [4762]
11111111111111111111
incomplete name 3, col: 4762 row: []
col: 4764 similar rows:  [4764]
11111111111111111111
incomplete name 3, col: 4764 row: []
col: 4765 similar rows:  [4765, 4957, 4965, 4974]
incomplete name 3, col: 4765 row: []
col: 4767 similar rows:  [4767]
11111111111111111111
incomplete name 3, col: 4767 row: []
col: 4768 similar rows:  [4768, 6364]
incomplete name 3, col: 4768 row: []
col: 4769 similar rows:  [4769]
11111111111111111111
incomplete name 3, col: 4769 row: []
col: 4770 similar rows:  [4770, 5204]
incomplete name 3, col: 4770 row: []
col: 4772 similar rows:  [4772, 4778, 5450, 5530, 6343]
incomplete name 3, col: 4772 row: []
col: 4773 similar rows:  [4773, 4774]
incomplete name 3, col: 4773 row: []
col: 4775 similar rows:  [4775, 5112, 6396, 6454, 6621]
incomplete name 3, col: 4775 row: []
col: 4776 similar rows:  [4776, 5595, 6203, 6322, 6595, 6604, 7058, 7100, 7156]
incomplete name 3, col: 4776 row: []
col: 4777 similar rows:  [4777]
11111111111111111111
incomplete name 3, col: 4777 row: []
col: 4779 similar rows:  [4779]
11111111111111111111
incomplete name 3, col: 4779 row: []
col: 4780 similar rows:  [4780]
11111111111111111111
incomplete name 3, col: 4780 row: []
col: 4781 similar rows:  [4781, 4788, 4797, 5514, 5529, 5986]
incomplete name 3, col: 4781 row: []
col: 4783 similar rows:  [4783]
11111111111111111111
incomplete name 3, col: 4783 row: []
col: 4785 similar rows:  [4785, 5098]
incomplete name 3, col: 4785 row: []
col: 4786 similar rows:  [4786, 5272, 5904, 5955, 6008, 6619, 6738, 6765, 7142]
incomplete name 3, col: 4786 row: []
col: 4787 similar rows:  [4787]
11111111111111111111
incomplete name 3, col: 4787 row: []
col: 4789 similar rows:  [4789]
11111111111111111111
incomplete name 3, col: 4789 row: []
col: 4790 similar rows:  [4790]
11111111111111111111
incomplete name 3, col: 4790 row: []
col: 4791 similar rows:  [4791]
11111111111111111111
incomplete name 3, col: 4791 row: []
col: 4792 similar rows:  [4792]
11111111111111111111
incomplete name 3, col: 4792 row: []
col: 4793 similar rows:  [4793]
11111111111111111111
incomplete name 3, col: 4793 row: []

col: 4794 similar rows:  [4794]
11111111111111111111
incomplete name 3, col: 4794 row: []
col: 4795 similar rows:  [4795]
11111111111111111111
hotelname2 [4795]
incomplete name 3, col: 4795 row: [4795]
col: 4796 similar rows:  [4796, 4950]
incomplete name 3, col: 4796 row: []
col: 4798 similar rows:  [4798, 5488, 5796, 5917, 6153, 6605, 7226]
incomplete name 3, col: 4798 row: []
col: 4801 similar rows:  [4801]
11111111111111111111
incomplete name 3, col: 4801 row: []
col: 4802 similar rows:  [4802]
11111111111111111111
incomplete name 3, col: 4802 row: []
col: 4803 similar rows:  [4803]
11111111111111111111
incomplete name 3, col: 4803 row: []
col: 4804 similar rows:  [4804, 4963]
incomplete name 3, col: 4804 row: []
col: 4805 similar rows:  [4805]
11111111111111111111
incomplete name 3, col: 4805 row: []
col: 4806 similar rows:  [4806, 4861, 6126, 6229, 6362, 6378, 6486]
incomplete name 3, col: 4806 row: []
col: 4807 similar rows:  [4807]
11111111111111111111
incomplete name 3, col: 4807 row: []
col: 4808 similar rows:  [4808, 5929, 7034]
incomplete name 3, col: 4808 row: []
col: 4809 similar rows:  [4809]
11111111111111111111
incomplete name 3, col: 4809 row: []
col: 4810 similar rows:  [4810]
11111111111111111111
incomplete name 3, col: 4810 row: []
col: 4811 similar rows:  [4811, 5556]
incomplete name 3, col: 4811 row: []
col: 4813 similar rows:  [4813]
11111111111111111111
incomplete name 3, col: 4813 row: []
col: 4814 similar rows:  [4814]
11111111111111111111
incomplete name 3, col: 4814 row: []
col: 4816 similar rows:  [4816, 5000, 5034, 6383]
incomplete name 3, col: 4816 row: []
col: 4818 similar rows:  [4818, 6236, 6463]
incomplete name 3, col: 4818 row: []
col: 4821 similar rows:  [4821]
11111111111111111111
incomplete name 3, col: 4821 row: []
col: 4824 similar rows:  [4824, 5091, 5104, 6386]
incomplete name 3, col: 4824 row: []
col: 4825 similar rows:  [4825]
11111111111111111111
incomplete name 3, col: 4825 row: []
col: 4827 similar rows:  [4827, 5346]
incomplete name 3, col: 4827 row: []
col: 4828 similar rows:  [4828, 4845]
incomplete name 3, col: 4828 row: []
col: 4831 similar rows:  [4831]
11111111111111111111
incomplete name 3, col: 4831 row: []
col: 4832 similar rows:  [4832, 5336, 6194, 6195, 6243, 6976]
incomplete name 3, col: 4832 row: []
col: 4835 similar rows:  [4835]
11111111111111111111
hotelname2 [4835]
incomplete name 3, col: 4835 row: [4835]
col: 4836 similar rows:  [4836, 5001, 5063, 5628, 5876, 6901]
incomplete name 3, col: 4836 row: []
col: 4838 similar rows:  [4838, 5647, 5648, 5679]
incomplete name 3, col: 4838 row: []
col: 4840 similar rows:  [4840, 5580, 6300]
incomplete name 3, col: 4840 row: []
col: 4841 similar rows:  [4841, 4912, 5096, 5886]
incomplete name 3, col: 4841 row: []
col: 4844 similar rows:  [4844, 6656]
incomplete name 3, col: 4844 row: []
col: 4846 similar rows:  [4846]
11111111111111111111
incomplete name 3, col: 4846 row: []
col: 4849 similar rows:  [4849, 5900]
incomplete name 3, col: 4849 row: []
col: 4851 similar rows:  [4851, 6789]
incomplete name 3, col: 4851 row: []
col: 4852 similar rows:  [4852, 5170, 5739]
incomplete name 3, col: 4852 row: []
col: 4853 similar rows:  [4853]
11111111111111111111
incomplete name 3, col: 4853 row: []
col: 4854 similar rows:  [4854]
11111111111111111111
incomplete name 3, col: 4854 row: []
col: 4857 similar rows:  [4857]
11111111111111111111
incomplete name 3, col: 4857 row: []
col: 4858 similar rows:  [4858, 6098]
incomplete name 3, col: 4858 row: []
col: 4859 similar rows:  [4859]
11111111111111111111
incomplete name 3, col: 4859 row: []
col: 4860 similar rows:  [4860, 5078, 6616, 6629]
incomplete name 3, col: 4860 row: []
col: 4864 similar rows:  [4864]
11111111111111111111
incomplete name 3, col: 4864 row: []
col: 4865 similar rows:  [4865, 5850, 5866, 5889]
incomplete name 3, col: 4865 row: []
col: 4866 similar rows:  [4866]
11111111111111111111
incomplete name 3, col: 4866 row: []
col: 4867 similar rows:  [4867]
11111111111111111111
incomplete name 3, col: 4867 row: []
col: 4868 similar rows:  [4868]
11111111111111111111
incomplete name 3, col: 4868 row: []
col: 4869 similar rows:  [4869]
11111111111111111111
incomplete name 3, col: 4869 row: []
col: 4871 similar rows:  [4871]
11111111111111111111
incomplete name 3, col: 4871 row: []
col: 4872 similar rows:  [4872]
11111111111111111111
incomplete name 3, col: 4872 row: []
col: 4873 similar rows:  [4873]
11111111111111111111
incomplete name 3, col: 4873 row: []
col: 4874 similar rows:  [4874, 5058, 6162, 6442, 6679]
incomplete name 3, col: 4874 row: []
col: 4876 similar rows:  [4876]
11111111111111111111
incomplete name 3, col: 4876 row: []
col: 4877 similar rows:  [4877]
11111111111111111111
incomplete name 3, col: 4877 row: []
col: 4878 similar rows:  [4878, 6401, 6408, 6528, 6559]
incomplete name 3, col: 4878 row: []
col: 4881 similar rows:  [4881]
11111111111111111111
incomplete name 3, col: 4881 row: []
col: 4882 similar rows:  [4882, 5135, 5388, 6636]
incomplete name 3, col: 4882 row: []
col: 4884 similar rows:  [4884]
11111111111111111111
hotelname2 [4884]
incomplete name 3, col: 4884 row: [4884]
col: 4885 similar rows:  [4885, 4937, 5613, 5687, 5880, 5891, 5976, 6737, 6932, 7119]
incomplete name 3, col: 4885 row: []
col: 4888 similar rows:  [4888]
11111111111111111111
incomplete name 3, col: 4888 row: []
col: 4890 similar rows:  [4890]
11111111111111111111
incomplete name 3, col: 4890 row: []
col: 4891 similar rows:  [4891, 5064, 5602, 6685, 6725]
incomplete name 3, col: 4891 row: []
col: 4893 similar rows:  [4893, 5050, 5199, 5205, 5842, 6460]
incomplete name 3, col: 4893 row: []
col: 4895 similar rows:  [4895]
11111111111111111111
incomplete name 3, col: 4895 row: []
col: 4896 similar rows:  [4896, 5059, 6519, 6751]
incomplete name 3, col: 4896 row: []
col: 4898 similar rows:  [4898]
11111111111111111111
incomplete name 3, col: 4898 row: []
col: 4899 similar rows:  [4899]
11111111111111111111
incomplete name 3, col: 4899 row: []
col: 4901 similar rows:  [4901, 6080, 6327, 6634, 7087]
incomplete name 3, col: 4901 row: []
col: 4903 similar rows:  [4903, 6958]
incomplete name 3, col: 4903 row: []
col: 4904 similar rows:  [4904, 5170, 5739, 5989]
incomplete name 3, col: 4904 row: []
col: 4905 similar rows:  [4905, 5259]
incomplete name 3, col: 4905 row: []
col: 4906 similar rows:  [4906]
11111111111111111111
hotelname2 [4906]
incomplete name 3, col: 4906 row: [4906]
col: 4909 similar rows:  [4909, 6856, 6916]
incomplete name 3, col: 4909 row: []
col: 4910 similar rows:  [4910]
11111111111111111111
incomplete name 3, col: 4910 row: []
col: 4911 similar rows:  [4911, 5551]
incomplete name 3, col: 4911 row: []
col: 4913 similar rows:  [4913, 5301, 5314, 6197, 6536, 6635, 7097]
incomplete name 3, col: 4913 row: []
col: 4914 similar rows:  [4914]
11111111111111111111
hotelname2 [4914]
incomplete name 3, col: 4914 row: [4914]
col: 4916 similar rows:  [4916]
11111111111111111111
hotelname2 [4916]
incomplete name 3, col: 4916 row: []
col: 4917 similar rows:  [4917]
11111111111111111111
hotelname2 [4917]
incomplete name 3, col: 4917 row: []
col: 4918 similar rows:  [4918, 6317]
incomplete name 3, col: 4918 row: []
col: 4919 similar rows:  [4919]
11111111111111111111
incomplete name 3, col: 4919 row: []
col: 4923 similar rows:  [4923, 5093, 5484]
incomplete name 3, col: 4923 row: []
col: 4925 similar rows:  [4925]
11111111111111111111
incomplete name 3, col: 4925 row: []
col: 4928 similar rows:  [4928]
11111111111111111111
incomplete name 3, col: 4928 row: []
col: 4929 similar rows:  [4929]
11111111111111111111
incomplete name 3, col: 4929 row: []
col: 4930 similar rows:  [4930]
11111111111111111111
incomplete name 3, col: 4930 row: []
col: 4931 similar rows:  [4931]
11111111111111111111
incomplete name 3, col: 4931 row: []
col: 4932 similar rows:  [4932]
11111111111111111111
incomplete name 3, col: 4932 row: []
col: 4933 similar rows:  [4933, 4934]
incomplete name 3, col: 4933 row: []
col: 4935 similar rows:  [4935]
11111111111111111111
incomplete name 3, col: 4935 row: []
col: 4939 similar rows:  [4939]
11111111111111111111
incomplete name 3, col: 4939 row: []
col: 4940 similar rows:  [4940, 5481, 6660]
incomplete name 3, col: 4940 row: []
col: 4941 similar rows:  [4941]
11111111111111111111
hotelname2 [4941]
incomplete name 3, col: 4941 row: [4941]
col: 4944 similar rows:  [4944]
11111111111111111111
incomplete name 3, col: 4944 row: []
col: 4945 similar rows:  [4945]
11111111111111111111
incomplete name 3, col: 4945 row: []
col: 4946 similar rows:  [4946, 4947]
incomplete name 3, col: 4946 row: []
col: 4948 similar rows:  [4948, 6384, 6434, 6450, 6752]
incomplete name 3, col: 4948 row: []

col: 4949 similar rows:  [4949]
11111111111111111111
incomplete name 3, col: 4949 row: []
col: 4951 similar rows:  [4951]
11111111111111111111
incomplete name 3, col: 4951 row: []
col: 4952 similar rows:  [4952, 5318, 5470, 6018]
incomplete name 3, col: 4952 row: []
col: 4953 similar rows:  [4953]
11111111111111111111
incomplete name 3, col: 4953 row: []
col: 4954 similar rows:  [4954]
11111111111111111111
incomplete name 3, col: 4954 row: []
col: 4955 similar rows:  [4955]
11111111111111111111
incomplete name 3, col: 4955 row: []
col: 4956 similar rows:  [4956]
11111111111111111111
hotelname2 [4956]
wrong name!!!!
incomplete name 3, col: 4956 row: [4956]
col: 4958 similar rows:  [4958]
11111111111111111111
incomplete name 3, col: 4958 row: []
col: 4961 similar rows:  [4961]
11111111111111111111
incomplete name 3, col: 4961 row: []
col: 4962 similar rows:  [4962]
11111111111111111111
incomplete name 3, col: 4962 row: []
col: 4964 similar rows:  [4964]
11111111111111111111
incomplete name 3, col: 4964 row: []
col: 4966 similar rows:  [4966]
11111111111111111111
hotelname2 [4966]
incomplete name 3, col: 4966 row: [4966]
col: 4967 similar rows:  [4967, 5598]
incomplete name 3, col: 4967 row: []
col: 4968 similar rows:  [4968]
11111111111111111111
incomplete name 3, col: 4968 row: []
col: 4969 similar rows:  [4969]
11111111111111111111
incomplete name 3, col: 4969 row: []
col: 4971 similar rows:  [4971]
11111111111111111111
incomplete name 3, col: 4971 row: []
col: 4972 similar rows:  [4972]
11111111111111111111
incomplete name 3, col: 4972 row: []
col: 4973 similar rows:  [4973, 5500]
incomplete name 3, col: 4973 row: []
col: 4975 similar rows:  [4975]
11111111111111111111
incomplete name 3, col: 4975 row: []
col: 4976 similar rows:  [4976]
11111111111111111111
hotelname2 [4976]
incomplete name 3, col: 4976 row: [4976]
col: 4977 similar rows:  [4977]
11111111111111111111
incomplete name 3, col: 4977 row: []
col: 4978 similar rows:  [4978]
11111111111111111111
hotelname2 [4978]
incomplete name 3, col: 4978 row: [4978]
col: 4979 similar rows:  [4979]
11111111111111111111
incomplete name 3, col: 4979 row: []
col: 4980 similar rows:  [4980]
11111111111111111111
incomplete name 3, col: 4980 row: []
col: 4981 similar rows:  [4981, 6467]
incomplete name 3, col: 4981 row: []
col: 4982 similar rows:  [4982]
11111111111111111111
incomplete name 3, col: 4982 row: []
col: 4985 similar rows:  [4985, 7227]
incomplete name 3, col: 4985 row: []
col: 4986 similar rows:  [4986]
11111111111111111111
incomplete name 3, col: 4986 row: []
col: 4987 similar rows:  [4987]
11111111111111111111
incomplete name 3, col: 4987 row: []
col: 4988 similar rows:  [4988]
11111111111111111111
incomplete name 3, col: 4988 row: []
col: 4989 similar rows:  [4989, 4990]
incomplete name 3, col: 4989 row: []
col: 4991 similar rows:  [4991]
11111111111111111111
incomplete name 3, col: 4991 row: []
col: 4992 similar rows:  [4992, 5443]
incomplete name 3, col: 4992 row: []
col: 4993 similar rows:  [4993]
11111111111111111111
hotelname2 [4993]
incomplete name 3, col: 4993 row: []
col: 4994 similar rows:  [4994, 5040, 5073, 5615, 5655, 5731, 6059, 6259, 6489, 6793]
incomplete name 3, col: 4994 row: []
col: 4995 similar rows:  [4995]
11111111111111111111
hotelname2 [4995]
incomplete name 3, col: 4995 row: [4995]
col: 4996 similar rows:  [4996, 6966]
incomplete name 3, col: 4996 row: []
col: 4998 similar rows:  [4998]
11111111111111111111
incomplete name 3, col: 4998 row: []
col: 4999 similar rows:  [4999, 5016, 5225, 6790]
incomplete name 3, col: 4999 row: []
col: 5003 similar rows:  [5003]
11111111111111111111
incomplete name 3, col: 5003 row: []
col: 5004 similar rows:  [5004, 5831, 6437, 6802]
incomplete name 3, col: 5004 row: []
col: 5005 similar rows:  [5005]
11111111111111111111
incomplete name 3, col: 5005 row: []
col: 5006 similar rows:  [5006, 6801, 6818]
incomplete name 3, col: 5006 row: []
col: 5010 similar rows:  [5010, 5036, 5099, 5290, 6344, 6379, 6472]
incomplete name 3, col: 5010 row: []
col: 5015 similar rows:  [5015]
11111111111111111111
incomplete name 3, col: 5015 row: []
col: 5021 similar rows:  [5021, 5037, 5830, 6448, 6943]
incomplete name 3, col: 5021 row: []
col: 5023 similar rows:  [5023, 5045]
incomplete name 3, col: 5023 row: []
col: 5027 similar rows:  [5027]
11111111111111111111
hotelname2 [5027]
incomplete name 3, col: 5027 row: [5027]
col: 5028 similar rows:  [5028]
11111111111111111111
incomplete name 3, col: 5028 row: []
col: 5030 similar rows:  [5030, 7053]
incomplete name 3, col: 5030 row: []
col: 5032 similar rows:  [5032]
11111111111111111111
incomplete name 3, col: 5032 row: []
col: 5042 similar rows:  [5042, 5853, 6817]
incomplete name 3, col: 5042 row: []
col: 5049 similar rows:  [5049]
11111111111111111111
incomplete name 3, col: 5049 row: []
col: 5051 similar rows:  [5051, 6042]
incomplete name 3, col: 5051 row: []
col: 5054 similar rows:  [5054]
11111111111111111111
hotelname2 [5054]
incomplete name 3, col: 5054 row: [5054]
col: 5056 similar rows:  [5056]
11111111111111111111
incomplete name 3, col: 5056 row: []
col: 5066 similar rows:  [5066]
11111111111111111111
hotelname2 [5066]
incomplete name 3, col: 5066 row: [5066]
col: 5067 similar rows:  [5067, 6320]
incomplete name 3, col: 5067 row: []
col: 5068 similar rows:  [5068, 5080, 5152, 5239, 6268, 6702]
incomplete name 3, col: 5068 row: []
col: 5069 similar rows:  [5069]
11111111111111111111
incomplete name 3, col: 5069 row: []
col: 5074 similar rows:  [5074, 6947]
incomplete name 3, col: 5074 row: []
col: 5075 similar rows:  [5075]
11111111111111111111
incomplete name 3, col: 5075 row: []
col: 5077 similar rows:  [5077]
11111111111111111111
incomplete name 3, col: 5077 row: []
col: 5079 similar rows:  [5079, 5951, 6405]
incomplete name 3, col: 5079 row: []
col: 5081 similar rows:  [5081]
11111111111111111111
incomplete name 3, col: 5081 row: []
col: 5082 similar rows:  [5082]
11111111111111111111
incomplete name 3, col: 5082 row: []
col: 5083 similar rows:  [5083]
11111111111111111111
incomplete name 3, col: 5083 row: []
col: 5087 similar rows:  [5087]
11111111111111111111
incomplete name 3, col: 5087 row: []
col: 5089 similar rows:  [5089]
11111111111111111111
incomplete name 3, col: 5089 row: []
col: 5092 similar rows:  [5092]
11111111111111111111
incomplete name 3, col: 5092 row: []
col: 5094 similar rows:  [5094]
11111111111111111111
incomplete name 3, col: 5094 row: []
col: 5097 similar rows:  [5097, 5344]
incomplete name 3, col: 5097 row: []
col: 5100 similar rows:  [5100]
11111111111111111111
incomplete name 3, col: 5100 row: []
col: 5102 similar rows:  [5102]
11111111111111111111
incomplete name 3, col: 5102 row: []
col: 5108 similar rows:  [5108, 6428, 7143]
incomplete name 3, col: 5108 row: []
col: 5111 similar rows:  [5111, 5442]
incomplete name 3, col: 5111 row: []
col: 5113 similar rows:  [5113]
11111111111111111111
incomplete name 3, col: 5113 row: []
col: 5114 similar rows:  [5114, 5717, 6961]
incomplete name 3, col: 5114 row: []
col: 5117 similar rows:  [5117]
11111111111111111111
incomplete name 3, col: 5117 row: []
col: 5118 similar rows:  [5118]
11111111111111111111
incomplete name 3, col: 5118 row: []
col: 5128 similar rows:  [5128]
11111111111111111111
incomplete name 3, col: 5128 row: []
col: 5129 similar rows:  [5129, 5203, 5432]
incomplete name 3, col: 5129 row: []
col: 5130 similar rows:  [5130]
11111111111111111111
incomplete name 3, col: 5130 row: []
col: 5131 similar rows:  [5131]
11111111111111111111
incomplete name 3, col: 5131 row: []
col: 5136 similar rows:  [5136]
11111111111111111111
incomplete name 3, col: 5136 row: []
col: 5137 similar rows:  [5137]
11111111111111111111
incomplete name 3, col: 5137 row: []
col: 5138 similar rows:  [5138]
11111111111111111111
incomplete name 3, col: 5138 row: []
col: 5139 similar rows:  [5139]
11111111111111111111
incomplete name 3, col: 5139 row: []
col: 5142 similar rows:  [5142, 5967, 6176]
incomplete name 3, col: 5142 row: []
col: 5143 similar rows:  [5143]
11111111111111111111
incomplete name 3, col: 5143 row: []
col: 5144 similar rows:  [5144]
11111111111111111111
hotelname2 [5144]
incomplete name 3, col: 5144 row: [5144]
col: 5145 similar rows:  [5145, 6248, 6834]
incomplete name 3, col: 5145 row: []
col: 5146 similar rows:  [5146]
11111111111111111111
incomplete name 3, col: 5146 row: []
col: 5147 similar rows:  [5147]
11111111111111111111
incomplete name 3, col: 5147 row: []

col: 5149 similar rows:  [5149]
11111111111111111111
incomplete name 3, col: 5149 row: []
col: 5151 similar rows:  [5151, 5899]
incomplete name 3, col: 5151 row: []
col: 5154 similar rows:  [5154, 6515]
incomplete name 3, col: 5154 row: []
col: 5155 similar rows:  [5155, 6543, 6847]
incomplete name 3, col: 5155 row: []
col: 5156 similar rows:  [5156]
11111111111111111111
incomplete name 3, col: 5156 row: []
col: 5157 similar rows:  [5157, 6464, 6487, 6671, 6905, 7070]
incomplete name 3, col: 5157 row: []
col: 5159 similar rows:  [5159, 5379, 5735, 5750, 5835, 5847, 5980, 6393, 6398, 7158, 7167]
incomplete name 3, col: 5159 row: []
col: 5160 similar rows:  [5160, 6397]
incomplete name 3, col: 5160 row: []
col: 5164 similar rows:  [5164]
11111111111111111111
incomplete name 3, col: 5164 row: []
col: 5165 similar rows:  [5165]
11111111111111111111
incomplete name 3, col: 5165 row: []
col: 5167 similar rows:  [5167]
11111111111111111111
incomplete name 3, col: 5167 row: []
col: 5169 similar rows:  [5169, 6731, 7029]
incomplete name 3, col: 5169 row: []
col: 5171 similar rows:  [5171]
11111111111111111111
hotelname2 [5171]
wrong name!!!!
incomplete name 3, col: 5171 row: [5171]
col: 5174 similar rows:  [5174]
11111111111111111111
incomplete name 3, col: 5174 row: []
col: 5175 similar rows:  [5175]
11111111111111111111
incomplete name 3, col: 5175 row: []
col: 5177 similar rows:  [5177]
11111111111111111111
incomplete name 3, col: 5177 row: []
col: 5181 similar rows:  [5181]
11111111111111111111
hotelname2 [5181]
incomplete name 3, col: 5181 row: [5181]
col: 5185 similar rows:  [5185]
11111111111111111111
incomplete name 3, col: 5185 row: []
col: 5186 similar rows:  [5186, 6432, 6860]
incomplete name 3, col: 5186 row: []
col: 5187 similar rows:  [5187, 5635, 6358]
incomplete name 3, col: 5187 row: []
col: 5189 similar rows:  [5189]
11111111111111111111
incomplete name 3, col: 5189 row: []
col: 5190 similar rows:  [5190]
11111111111111111111
hotelname2 [5190]
incomplete name 3, col: 5190 row: []
col: 5191 similar rows:  [5191]
11111111111111111111
incomplete name 3, col: 5191 row: []
col: 5193 similar rows:  [5193]
11111111111111111111
incomplete name 3, col: 5193 row: []
col: 5194 similar rows:  [5194]
11111111111111111111
incomplete name 3, col: 5194 row: []
col: 5195 similar rows:  [5195]
11111111111111111111
incomplete name 3, col: 5195 row: []
col: 5197 similar rows:  [5197]
11111111111111111111
incomplete name 3, col: 5197 row: []
col: 5198 similar rows:  [5198]
11111111111111111111
hotelname2 [5198]
incomplete name 3, col: 5198 row: [5198]
col: 5200 similar rows:  [5200]
11111111111111111111
incomplete name 3, col: 5200 row: []
col: 5201 similar rows:  [5201, 5321]
incomplete name 3, col: 5201 row: []
col: 5212 similar rows:  [5212, 5214, 5396, 6694, 7090]
incomplete name 3, col: 5212 row: []
col: 5217 similar rows:  [5217, 7078]
incomplete name 3, col: 5217 row: []
col: 5218 similar rows:  [5218]
11111111111111111111
incomplete name 3, col: 5218 row: []
col: 5220 similar rows:  [5220]
11111111111111111111
incomplete name 3, col: 5220 row: []
col: 5226 similar rows:  [5226, 5366]
incomplete name 3, col: 5226 row: []
col: 5229 similar rows:  [5229, 5604, 6700, 7083]
incomplete name 3, col: 5229 row: []
col: 5232 similar rows:  [5232]
11111111111111111111
incomplete name 3, col: 5232 row: []
col: 5235 similar rows:  [5235, 6846]
incomplete name 3, col: 5235 row: []
col: 5236 similar rows:  [5236, 5262, 6531, 6859]
incomplete name 3, col: 5236 row: []
col: 5240 similar rows:  [5240, 5956]
incomplete name 3, col: 5240 row: []
col: 5242 similar rows:  [5242, 6591, 6821]
incomplete name 3, col: 5242 row: []
col: 5244 similar rows:  [5244]
11111111111111111111
incomplete name 3, col: 5244 row: []
col: 5245 similar rows:  [5245]
11111111111111111111
incomplete name 3, col: 5245 row: []
col: 5251 similar rows:  [5251, 5315, 5323, 6898, 6904]
incomplete name 3, col: 5251 row: []
col: 5254 similar rows:  [5254]
11111111111111111111
incomplete name 3, col: 5254 row: []
col: 5256 similar rows:  [5256]
11111111111111111111
incomplete name 3, col: 5256 row: []
col: 5257 similar rows:  [5257]
11111111111111111111
hotelname2 [5257]
wrong name!!!!
incomplete name 3, col: 5257 row: [5257]
col: 5258 similar rows:  [5258]
11111111111111111111
incomplete name 3, col: 5258 row: []
col: 5263 similar rows:  [5263]
11111111111111111111
incomplete name 3, col: 5263 row: []
col: 5265 similar rows:  [5265, 5672]
incomplete name 3, col: 5265 row: []
col: 5266 similar rows:  [5266]
11111111111111111111
hotelname2 [5266]
incomplete name 3, col: 5266 row: [5266]
col: 5267 similar rows:  [5267, 5294]
incomplete name 3, col: 5267 row: []
col: 5268 similar rows:  [5268, 6927]
incomplete name 3, col: 5268 row: []
col: 5269 similar rows:  [5269, 6918]
incomplete name 3, col: 5269 row: []
col: 5279 similar rows:  [5279]
11111111111111111111
incomplete name 3, col: 5279 row: []
col: 5281 similar rows:  [5281, 5293, 5448, 5681, 5719, 5826, 6353, 7137]
incomplete name 3, col: 5281 row: []
col: 5285 similar rows:  [5285, 5496]
incomplete name 3, col: 5285 row: []
col: 5287 similar rows:  [5287, 6877]
incomplete name 3, col: 5287 row: []
col: 5288 similar rows:  [5288]
11111111111111111111
incomplete name 3, col: 5288 row: []
col: 5289 similar rows:  [5289, 5322, 6255]
incomplete name 3, col: 5289 row: []
col: 5291 similar rows:  [5291]
11111111111111111111
incomplete name 3, col: 5291 row: []
col: 5292 similar rows:  [5292]
11111111111111111111
incomplete name 3, col: 5292 row: []
col: 5295 similar rows:  [5295]
11111111111111111111
incomplete name 3, col: 5295 row: []
col: 5296 similar rows:  [5296]
11111111111111111111
incomplete name 3, col: 5296 row: []
col: 5297 similar rows:  [5297]
11111111111111111111
incomplete name 3, col: 5297 row: []
col: 5300 similar rows:  [5300, 6563]
incomplete name 3, col: 5300 row: []
col: 5302 similar rows:  [5302, 5315, 6898]
incomplete name 3, col: 5302 row: []
col: 5303 similar rows:  [5303]
11111111111111111111
incomplete name 3, col: 5303 row: []
col: 5304 similar rows:  [5304]
11111111111111111111
incomplete name 3, col: 5304 row: []
col: 5305 similar rows:  [5305, 5306]
incomplete name 3, col: 5305 row: []
col: 5307 similar rows:  [5307]
11111111111111111111
incomplete name 3, col: 5307 row: []
col: 5308 similar rows:  [5308]
11111111111111111111
incomplete name 3, col: 5308 row: []
col: 5309 similar rows:  [5309]
11111111111111111111
hotelname2 [5309]
wrong name!!!!
incomplete name 3, col: 5309 row: [5309]
col: 5313 similar rows:  [5313]
11111111111111111111
incomplete name 3, col: 5313 row: []
col: 5316 similar rows:  [5316]
11111111111111111111
incomplete name 3, col: 5316 row: []
col: 5317 similar rows:  [5317, 7186]
incomplete name 3, col: 5317 row: []
col: 5319 similar rows:  [5319]
11111111111111111111
incomplete name 3, col: 5319 row: []
col: 5320 similar rows:  [5320, 6320]
incomplete name 3, col: 5320 row: []
col: 5325 similar rows:  [5325]
11111111111111111111
incomplete name 3, col: 5325 row: []
col: 5326 similar rows:  [5326]
11111111111111111111
incomplete name 3, col: 5326 row: []
col: 5327 similar rows:  [5327, 6312, 6727]
incomplete name 3, col: 5327 row: []
col: 5328 similar rows:  [5328]
11111111111111111111
incomplete name 3, col: 5328 row: []
col: 5330 similar rows:  [5330]
11111111111111111111
incomplete name 3, col: 5330 row: []
col: 5332 similar rows:  [5332]
11111111111111111111
incomplete name 3, col: 5332 row: []
col: 5334 similar rows:  [5334]
11111111111111111111
incomplete name 3, col: 5334 row: []
col: 5335 similar rows:  [5335]
11111111111111111111
incomplete name 3, col: 5335 row: []
col: 5340 similar rows:  [5340, 5512, 6800, 6974]
incomplete name 3, col: 5340 row: []
col: 5341 similar rows:  [5341]
11111111111111111111
incomplete name 3, col: 5341 row: []
col: 5345 similar rows:  [5345]
11111111111111111111
incomplete name 3, col: 5345 row: []
col: 5347 similar rows:  [5347]
11111111111111111111
hotelname2 [5347]
incomplete name 3, col: 5347 row: [5347]
col: 5349 similar rows:  [5349, 6237]
incomplete name 3, col: 5349 row: []
col: 5352 similar rows:  [5352]
11111111111111111111
incomplete name 3, col: 5352 row: []
col: 5354 similar rows:  [5354]
11111111111111111111
incomplete name 3, col: 5354 row: []
col: 5355 similar rows:  [5355, 6425]
incomplete name 3, col: 5355 row: []
col: 5356 similar rows:  [5356]
11111111111111111111
hotelname2 [5356]
incomplete name 3, col: 5356 row: [5356]

col: 5358 similar rows:  [5358, 6326]
incomplete name 3, col: 5358 row: []
col: 5361 similar rows:  [5361, 5393, 5618, 6221, 6837]
incomplete name 3, col: 5361 row: []
col: 5362 similar rows:  [5362]
11111111111111111111
incomplete name 3, col: 5362 row: []
col: 5365 similar rows:  [5365]
11111111111111111111
incomplete name 3, col: 5365 row: []
col: 5367 similar rows:  [5367, 6071, 6527, 6925, 7004, 7203]
incomplete name 3, col: 5367 row: []
col: 5369 similar rows:  [5369]
11111111111111111111
incomplete name 3, col: 5369 row: []
col: 5370 similar rows:  [5370]
11111111111111111111
hotelname2 [5370]
incomplete name 3, col: 5370 row: [5370]
col: 5371 similar rows:  [5371, 5489]
incomplete name 3, col: 5371 row: []
col: 5373 similar rows:  [5373, 6611, 6649]
incomplete name 3, col: 5373 row: []
col: 5374 similar rows:  [5374]
11111111111111111111
incomplete name 3, col: 5374 row: []
col: 5376 similar rows:  [5376]
11111111111111111111
incomplete name 3, col: 5376 row: []
col: 5381 similar rows:  [5381]
11111111111111111111
incomplete name 3, col: 5381 row: []
col: 5385 similar rows:  [5385]
11111111111111111111
hotelname2 [5385]
incomplete name 3, col: 5385 row: [5385]
col: 5391 similar rows:  [5391]
11111111111111111111
incomplete name 3, col: 5391 row: []
col: 5397 similar rows:  [5397, 6707, 6716]
incomplete name 3, col: 5397 row: []
col: 5403 similar rows:  [5403]
11111111111111111111
incomplete name 3, col: 5403 row: []
col: 5404 similar rows:  [5404]
11111111111111111111
incomplete name 3, col: 5404 row: []
col: 5406 similar rows:  [5406]
11111111111111111111
incomplete name 3, col: 5406 row: []
col: 5407 similar rows:  [5407, 6376, 6970, 7195]
incomplete name 3, col: 5407 row: []
col: 5408 similar rows:  [5408]
11111111111111111111
hotelname2 [5408]
wrong name!!!!
incomplete name 3, col: 5408 row: [5408]
col: 5409 similar rows:  [5409, 6687, 6712, 6732, 7072]
incomplete name 3, col: 5409 row: []
col: 5413 similar rows:  [5413, 5971, 6124, 6912]
incomplete name 3, col: 5413 row: []
col: 5416 similar rows:  [5416]
11111111111111111111
incomplete name 3, col: 5416 row: []
col: 5417 similar rows:  [5417]
11111111111111111111
incomplete name 3, col: 5417 row: []
col: 5418 similar rows:  [5418]
11111111111111111111
incomplete name 3, col: 5418 row: []
col: 5423 similar rows:  [5423]
11111111111111111111
incomplete name 3, col: 5423 row: []
col: 5424 similar rows:  [5424]
11111111111111111111
incomplete name 3, col: 5424 row: []
col: 5425 similar rows:  [5425, 5882]
incomplete name 3, col: 5425 row: []
col: 5427 similar rows:  [5427]
11111111111111111111
incomplete name 3, col: 5427 row: []
col: 5431 similar rows:  [5431]
11111111111111111111
incomplete name 3, col: 5431 row: []
col: 5433 similar rows:  [5433]
11111111111111111111
incomplete name 3, col: 5433 row: []
col: 5434 similar rows:  [5434]
11111111111111111111
incomplete name 3, col: 5434 row: []
col: 5435 similar rows:  [5435]
11111111111111111111
incomplete name 3, col: 5435 row: []
col: 5438 similar rows:  [5438]
11111111111111111111
incomplete name 3, col: 5438 row: []
col: 5440 similar rows:  [5440]
11111111111111111111
incomplete name 3, col: 5440 row: []
col: 5441 similar rows:  [5441]
11111111111111111111
incomplete name 3, col: 5441 row: []
col: 5444 similar rows:  [5444]
11111111111111111111
incomplete name 3, col: 5444 row: []
col: 5445 similar rows:  [5445]
11111111111111111111
incomplete name 3, col: 5445 row: []
col: 5447 similar rows:  [5447]
11111111111111111111
incomplete name 3, col: 5447 row: []
col: 5452 similar rows:  [5452]
11111111111111111111
incomplete name 3, col: 5452 row: []
col: 5453 similar rows:  [5453]
11111111111111111111
incomplete name 3, col: 5453 row: []
col: 5455 similar rows:  [5455]
11111111111111111111
incomplete name 3, col: 5455 row: []
col: 5456 similar rows:  [5456, 6074]
incomplete name 3, col: 5456 row: []
col: 5457 similar rows:  [5457]
11111111111111111111
incomplete name 3, col: 5457 row: []
col: 5459 similar rows:  [5459]
11111111111111111111
incomplete name 3, col: 5459 row: []
col: 5460 similar rows:  [5460, 6165, 6624]
incomplete name 3, col: 5460 row: []
col: 5461 similar rows:  [5461]
11111111111111111111
incomplete name 3, col: 5461 row: []
col: 5462 similar rows:  [5462]
11111111111111111111
hotelname2 [5462]
incomplete name 3, col: 5462 row: [5462]
col: 5466 similar rows:  [5466, 6135]
incomplete name 3, col: 5466 row: []
col: 5467 similar rows:  [5467]
11111111111111111111
incomplete name 3, col: 5467 row: []
col: 5468 similar rows:  [5468]
11111111111111111111
incomplete name 3, col: 5468 row: []
col: 5472 similar rows:  [5472]
11111111111111111111
incomplete name 3, col: 5472 row: []
col: 5473 similar rows:  [5473]
11111111111111111111
incomplete name 3, col: 5473 row: []
col: 5474 similar rows:  [5474]
11111111111111111111
hotelname2 [5474]
incomplete name 3, col: 5474 row: [5474]
col: 5476 similar rows:  [5476]
11111111111111111111
hotelname2 [5476]
incomplete name 3, col: 5476 row: [5476]
col: 5477 similar rows:  [5477, 6342]
incomplete name 3, col: 5477 row: []
col: 5480 similar rows:  [5480]
11111111111111111111
incomplete name 3, col: 5480 row: []
col: 5485 similar rows:  [5485]
11111111111111111111
incomplete name 3, col: 5485 row: []
col: 5486 similar rows:  [5486]
11111111111111111111
incomplete name 3, col: 5486 row: []
col: 5490 similar rows:  [5490]
11111111111111111111
hotelname2 [5490]
incomplete name 3, col: 5490 row: [5490]
col: 5491 similar rows:  [5491]
11111111111111111111
incomplete name 3, col: 5491 row: []
col: 5492 similar rows:  [5492]
11111111111111111111
hotelname2 [5492]
incomplete name 3, col: 5492 row: []
col: 5494 similar rows:  [5494]
11111111111111111111
incomplete name 3, col: 5494 row: []
col: 5497 similar rows:  [5497, 5913]
incomplete name 3, col: 5497 row: []
col: 5502 similar rows:  [5502]
11111111111111111111
incomplete name 3, col: 5502 row: []
col: 5505 similar rows:  [5505]
11111111111111111111
incomplete name 3, col: 5505 row: []
col: 5506 similar rows:  [5506]
11111111111111111111
incomplete name 3, col: 5506 row: []
col: 5508 similar rows:  [5508]
11111111111111111111
incomplete name 3, col: 5508 row: []
col: 5509 similar rows:  [5509]
11111111111111111111
incomplete name 3, col: 5509 row: []
col: 5510 similar rows:  [5510]
11111111111111111111
incomplete name 3, col: 5510 row: []
col: 5511 similar rows:  [5511]
11111111111111111111
incomplete name 3, col: 5511 row: []
col: 5513 similar rows:  [5513, 6582, 7018]
incomplete name 3, col: 5513 row: []
col: 5516 similar rows:  [5516, 7204]
incomplete name 3, col: 5516 row: []
col: 5517 similar rows:  [5517]
11111111111111111111
incomplete name 3, col: 5517 row: []
col: 5518 similar rows:  [5518]
11111111111111111111
incomplete name 3, col: 5518 row: []
col: 5519 similar rows:  [5519]
11111111111111111111
incomplete name 3, col: 5519 row: []
col: 5520 similar rows:  [5520]
11111111111111111111
incomplete name 3, col: 5520 row: []
col: 5521 similar rows:  [5521]
11111111111111111111
incomplete name 3, col: 5521 row: []
col: 5522 similar rows:  [5522, 7174, 7225]
incomplete name 3, col: 5522 row: []
col: 5523 similar rows:  [5523]
11111111111111111111
incomplete name 3, col: 5523 row: []
col: 5524 similar rows:  [5524, 6311]
incomplete name 3, col: 5524 row: []
col: 5525 similar rows:  [5525, 5939, 6140, 6917]
incomplete name 3, col: 5525 row: []
col: 5526 similar rows:  [5526, 6898]
incomplete name 3, col: 5526 row: []
col: 5527 similar rows:  [5527, 5737]
incomplete name 3, col: 5527 row: []
col: 5528 similar rows:  [5528, 6780]
incomplete name 3, col: 5528 row: []
col: 5531 similar rows:  [5531]
11111111111111111111
incomplete name 3, col: 5531 row: []
col: 5532 similar rows:  [5532]
11111111111111111111
incomplete name 3, col: 5532 row: []
col: 5533 similar rows:  [5533, 6017, 6455]
incomplete name 3, col: 5533 row: []
col: 5534 similar rows:  [5534, 5818, 6447]
incomplete name 3, col: 5534 row: []
col: 5536 similar rows:  [5536, 6909]
incomplete name 3, col: 5536 row: []
col: 5537 similar rows:  [5537]
11111111111111111111
incomplete name 3, col: 5537 row: []
col: 5538 similar rows:  [5538]
11111111111111111111
incomplete name 3, col: 5538 row: []
col: 5540 similar rows:  [5540]
11111111111111111111
incomplete name 3, col: 5540 row: []

col: 5541 similar rows:  [5541, 6422]
incomplete name 3, col: 5541 row: []
col: 5542 similar rows:  [5542]
11111111111111111111
incomplete name 3, col: 5542 row: []
col: 5544 similar rows:  [5544]
11111111111111111111
incomplete name 3, col: 5544 row: []
col: 5546 similar rows:  [5546]
11111111111111111111
incomplete name 3, col: 5546 row: []
col: 5547 similar rows:  [5547]
11111111111111111111
incomplete name 3, col: 5547 row: []
col: 5548 similar rows:  [5548]
11111111111111111111
incomplete name 3, col: 5548 row: []
col: 5550 similar rows:  [5550]
11111111111111111111
incomplete name 3, col: 5550 row: []
col: 5553 similar rows:  [5553, 5736, 6476, 7021]
incomplete name 3, col: 5553 row: []
col: 5555 similar rows:  [5555, 5918, 6139, 6257]
incomplete name 3, col: 5555 row: []
col: 5557 similar rows:  [5557, 5649, 5799, 6937, 7145]
incomplete name 3, col: 5557 row: []
col: 5558 similar rows:  [5558]
11111111111111111111
incomplete name 3, col: 5558 row: []
col: 5559 similar rows:  [5559]
11111111111111111111
incomplete name 3, col: 5559 row: []
col: 5560 similar rows:  [5560]
11111111111111111111
incomplete name 3, col: 5560 row: []
col: 5561 similar rows:  [5561, 7160]
incomplete name 3, col: 5561 row: []
col: 5564 similar rows:  [5564, 7223]
incomplete name 3, col: 5564 row: []
col: 5565 similar rows:  [5565]
11111111111111111111
incomplete name 3, col: 5565 row: []
col: 5566 similar rows:  [5566]
11111111111111111111
incomplete name 3, col: 5566 row: []
col: 5568 similar rows:  [5568]
11111111111111111111
incomplete name 3, col: 5568 row: []
col: 5569 similar rows:  [5569]
11111111111111111111
hotelname2 [5569]
incomplete name 3, col: 5569 row: [5569]
col: 5570 similar rows:  [5570]
11111111111111111111
incomplete name 3, col: 5570 row: []
col: 5572 similar rows:  [5572, 5689, 5829, 6218, 6459, 6869, 7092, 7111, 7134]
incomplete name 3, col: 5572 row: []
col: 5573 similar rows:  [5573]
11111111111111111111
incomplete name 3, col: 5573 row: []
col: 5574 similar rows:  [5574]
11111111111111111111
incomplete name 3, col: 5574 row: []
col: 5575 similar rows:  [5575]
11111111111111111111
incomplete name 3, col: 5575 row: []
col: 5578 similar rows:  [5578]
11111111111111111111
incomplete name 3, col: 5578 row: []
col: 5579 similar rows:  [5579]
11111111111111111111
incomplete name 3, col: 5579 row: []
col: 5582 similar rows:  [5582]
11111111111111111111
incomplete name 3, col: 5582 row: []
col: 5584 similar rows:  [5584]
11111111111111111111
incomplete name 3, col: 5584 row: []
col: 5586 similar rows:  [5586]
11111111111111111111
incomplete name 3, col: 5586 row: []
col: 5587 similar rows:  [5587]
11111111111111111111
incomplete name 3, col: 5587 row: []
col: 5588 similar rows:  [5588]
11111111111111111111
incomplete name 3, col: 5588 row: []
col: 5591 similar rows:  [5591, 7102]
incomplete name 3, col: 5591 row: []
col: 5592 similar rows:  [5592]
11111111111111111111
incomplete name 3, col: 5592 row: []
col: 5593 similar rows:  [5593]
11111111111111111111
incomplete name 3, col: 5593 row: []
col: 5596 similar rows:  [5596, 5929, 6316, 7034]
incomplete name 3, col: 5596 row: []
col: 5597 similar rows:  [5597]
11111111111111111111
hotelname2 [5597]
incomplete name 3, col: 5597 row: [5597]
col: 5599 similar rows:  [5599]
11111111111111111111
incomplete name 3, col: 5599 row: []
col: 5600 similar rows:  [5600]
11111111111111111111
hotelname2 [5600]
incomplete name 3, col: 5600 row: [5600]
col: 5601 similar rows:  [5601]
11111111111111111111
incomplete name 3, col: 5601 row: []
col: 5605 similar rows:  [5605, 6709, 6730]
incomplete name 3, col: 5605 row: []
col: 5609 similar rows:  [5609, 5621, 5653]
incomplete name 3, col: 5609 row: []
col: 5624 similar rows:  [5624, 5871]
incomplete name 3, col: 5624 row: []
col: 5626 similar rows:  [5626]
11111111111111111111
hotelname2 [5626]
incomplete name 3, col: 5626 row: [5626]
col: 5627 similar rows:  [5627]
11111111111111111111
incomplete name 3, col: 5627 row: []
col: 5640 similar rows:  [5640]
11111111111111111111
incomplete name 3, col: 5640 row: []
col: 5642 similar rows:  [5642]
11111111111111111111
incomplete name 3, col: 5642 row: []
col: 5643 similar rows:  [5643]
11111111111111111111
incomplete name 3, col: 5643 row: []
col: 5644 similar rows:  [5644, 6508]
incomplete name 3, col: 5644 row: []
col: 5650 similar rows:  [5650, 5676, 6692, 6717, 6914]
incomplete name 3, col: 5650 row: []
col: 5654 similar rows:  [5654]
11111111111111111111
incomplete name 3, col: 5654 row: []
col: 5656 similar rows:  [5656]
11111111111111111111
hotelname2 [5656]
incomplete name 3, col: 5656 row: [5656]
col: 5659 similar rows:  [5659]
11111111111111111111
incomplete name 3, col: 5659 row: []
col: 5660 similar rows:  [5660, 5942]
incomplete name 3, col: 5660 row: []
col: 5664 similar rows:  [5664, 6940, 6973]
incomplete name 3, col: 5664 row: []
col: 5667 similar rows:  [5667]
11111111111111111111
incomplete name 3, col: 5667 row: []
col: 5673 similar rows:  [5673]
11111111111111111111
incomplete name 3, col: 5673 row: []
col: 5674 similar rows:  [5674]
11111111111111111111
incomplete name 3, col: 5674 row: []
col: 5678 similar rows:  [5678]
11111111111111111111
incomplete name 3, col: 5678 row: []
col: 5682 similar rows:  [5682, 6394]
incomplete name 3, col: 5682 row: []
col: 5684 similar rows:  [5684]
11111111111111111111
incomplete name 3, col: 5684 row: []
col: 5685 similar rows:  [5685]
11111111111111111111
incomplete name 3, col: 5685 row: []
col: 5691 similar rows:  [5691, 6530]
incomplete name 3, col: 5691 row: []
col: 5692 similar rows:  [5692, 5746, 5919]
incomplete name 3, col: 5692 row: []
col: 5693 similar rows:  [5693]
11111111111111111111
incomplete name 3, col: 5693 row: []
col: 5695 similar rows:  [5695]
11111111111111111111
incomplete name 3, col: 5695 row: []
col: 5696 similar rows:  [5696]
11111111111111111111
incomplete name 3, col: 5696 row: []
col: 5697 similar rows:  [5697]
11111111111111111111
incomplete name 3, col: 5697 row: []
col: 5701 similar rows:  [5701, 6799]
incomplete name 3, col: 5701 row: []
col: 5709 similar rows:  [5709, 5752]
incomplete name 3, col: 5709 row: []
col: 5710 similar rows:  [5710, 6567]
incomplete name 3, col: 5710 row: []
col: 5711 similar rows:  [5711]
11111111111111111111
hotelname2 [5711]
incomplete name 3, col: 5711 row: [5711]
col: 5712 similar rows:  [5712, 5915, 6762]
incomplete name 3, col: 5712 row: []
col: 5713 similar rows:  [5713, 6833]
incomplete name 3, col: 5713 row: []
col: 5716 similar rows:  [5716, 5964, 6985]
incomplete name 3, col: 5716 row: []
col: 5718 similar rows:  [5718]
11111111111111111111
hotelname2 [5718]
incomplete name 3, col: 5718 row: [5718]
col: 5722 similar rows:  [5722]
11111111111111111111
incomplete name 3, col: 5722 row: []
col: 5724 similar rows:  [5724]
11111111111111111111
incomplete name 3, col: 5724 row: []
col: 5727 similar rows:  [5727]
11111111111111111111
hotelname2 [5727]
incomplete name 3, col: 5727 row: []
col: 5728 similar rows:  [5728]
11111111111111111111
incomplete name 3, col: 5728 row: []
col: 5732 similar rows:  [5732]
11111111111111111111
incomplete name 3, col: 5732 row: []
col: 5733 similar rows:  [5733]
11111111111111111111
hotelname2 [5733]
wrong name!!!!
incomplete name 3, col: 5733 row: [5733]
col: 5734 similar rows:  [5734]
11111111111111111111
incomplete name 3, col: 5734 row: []
col: 5738 similar rows:  [5738, 6525, 6729]
incomplete name 3, col: 5738 row: []
col: 5741 similar rows:  [5741]
11111111111111111111
incomplete name 3, col: 5741 row: []
col: 5742 similar rows:  [5742]
11111111111111111111
incomplete name 3, col: 5742 row: []
col: 5747 similar rows:  [5747]
11111111111111111111
incomplete name 3, col: 5747 row: []
col: 5748 similar rows:  [5748]
11111111111111111111
incomplete name 3, col: 5748 row: []
col: 5749 similar rows:  [5749]
11111111111111111111
incomplete name 3, col: 5749 row: []
col: 5753 similar rows:  [5753]
11111111111111111111
incomplete name 3, col: 5753 row: []
col: 5754 similar rows:  [5754]
11111111111111111111
incomplete name 3, col: 5754 row: []
col: 5755 similar rows:  [5755]
11111111111111111111
hotelname2 [5755]
incomplete name 3, col: 5755 row: [5755]
col: 5758 similar rows:  [5758]
11111111111111111111
incomplete name 3, col: 5758 row: []
col: 5759 similar rows:  [5759]
11111111111111111111
incomplete name 3, col: 5759 row: []
col: 5760 similar rows:  [5760]
11111111111111111111
incomplete name 3, col: 5760 row: []

col: 5761 similar rows:  [5761]
11111111111111111111
incomplete name 3, col: 5761 row: []
col: 5763 similar rows:  [5763]
11111111111111111111
incomplete name 3, col: 5763 row: []
col: 5764 similar rows:  [5764]
11111111111111111111
incomplete name 3, col: 5764 row: []
col: 5765 similar rows:  [5765]
11111111111111111111
incomplete name 3, col: 5765 row: []
col: 5768 similar rows:  [5768]
11111111111111111111
incomplete name 3, col: 5768 row: []
col: 5769 similar rows:  [5769, 5775]
incomplete name 3, col: 5769 row: []
col: 5770 similar rows:  [5770]
11111111111111111111
incomplete name 3, col: 5770 row: []
col: 5771 similar rows:  [5771]
11111111111111111111
incomplete name 3, col: 5771 row: []
col: 5772 similar rows:  [5772, 6517]
incomplete name 3, col: 5772 row: []
col: 5774 similar rows:  [5774]
11111111111111111111
incomplete name 3, col: 5774 row: []
col: 5778 similar rows:  [5778, 5785, 6254]
incomplete name 3, col: 5778 row: []
col: 5780 similar rows:  [5780]
11111111111111111111
incomplete name 3, col: 5780 row: []
col: 5781 similar rows:  [5781, 5863, 6537]
incomplete name 3, col: 5781 row: []
col: 5782 similar rows:  [5782]
11111111111111111111
incomplete name 3, col: 5782 row: []
col: 5783 similar rows:  [5783]
11111111111111111111
incomplete name 3, col: 5783 row: []
col: 5788 similar rows:  [5788]
11111111111111111111
hotelname2 [5788]
wrong name!!!!
incomplete name 3, col: 5788 row: [5788]
col: 5791 similar rows:  [5791]
11111111111111111111
incomplete name 3, col: 5791 row: []
col: 5795 similar rows:  [5795]
11111111111111111111
incomplete name 3, col: 5795 row: []
col: 5797 similar rows:  [5797]
11111111111111111111
hotelname2 [5797]
incomplete name 3, col: 5797 row: [5797]
col: 5798 similar rows:  [5798]
11111111111111111111
incomplete name 3, col: 5798 row: []
col: 5800 similar rows:  [5800, 6364]
incomplete name 3, col: 5800 row: []
col: 5801 similar rows:  [5801]
11111111111111111111
hotelname2 [5801]
wrong name!!!!
incomplete name 3, col: 5801 row: [5801]
col: 5802 similar rows:  [5802]
11111111111111111111
hotelname2 [5802]
wrong name!!!!
incomplete name 3, col: 5802 row: [5802]
col: 5803 similar rows:  [5803, 6399]
incomplete name 3, col: 5803 row: []
col: 5804 similar rows:  [5804]
11111111111111111111
hotelname2 [5804]
incomplete name 3, col: 5804 row: [5804]
col: 5807 similar rows:  [5807]
11111111111111111111
incomplete name 3, col: 5807 row: []
col: 5808 similar rows:  [5808]
11111111111111111111
incomplete name 3, col: 5808 row: []
col: 5809 similar rows:  [5809]
11111111111111111111
incomplete name 3, col: 5809 row: []
col: 5810 similar rows:  [5810]
11111111111111111111
incomplete name 3, col: 5810 row: []
col: 5813 similar rows:  [5813]
11111111111111111111
hotelname2 [5813]
incomplete name 3, col: 5813 row: [5813]
col: 5814 similar rows:  [5814]
11111111111111111111
incomplete name 3, col: 5814 row: []
col: 5817 similar rows:  [5817]
11111111111111111111
incomplete name 3, col: 5817 row: []
col: 5821 similar rows:  [5821]
11111111111111111111
hotelname2 [5821]
incomplete name 3, col: 5821 row: []
col: 5822 similar rows:  [5822]
11111111111111111111
incomplete name 3, col: 5822 row: []
col: 5823 similar rows:  [5823]
11111111111111111111
hotelname2 [5823]
wrong name!!!!
incomplete name 3, col: 5823 row: [5823]
col: 5825 similar rows:  [5825, 6803]
incomplete name 3, col: 5825 row: []
col: 5828 similar rows:  [5828]
11111111111111111111
hotelname2 [5828]
incomplete name 3, col: 5828 row: [5828]
col: 5832 similar rows:  [5832]
11111111111111111111
incomplete name 3, col: 5832 row: []
col: 5838 similar rows:  [5838]
11111111111111111111
incomplete name 3, col: 5838 row: []
col: 5844 similar rows:  [5844]
11111111111111111111
incomplete name 3, col: 5844 row: []
col: 5845 similar rows:  [5845]
11111111111111111111
incomplete name 3, col: 5845 row: []
col: 5854 similar rows:  [5854]
11111111111111111111
hotelname2 [5854]
incomplete name 3, col: 5854 row: [5854]
col: 5857 similar rows:  [5857, 6574]
incomplete name 3, col: 5857 row: []
col: 5858 similar rows:  [5858]
11111111111111111111
incomplete name 3, col: 5858 row: []
col: 5859 similar rows:  [5859, 6827]
incomplete name 3, col: 5859 row: []
col: 5862 similar rows:  [5862]
11111111111111111111
incomplete name 3, col: 5862 row: []
col: 5867 similar rows:  [5867]
11111111111111111111
incomplete name 3, col: 5867 row: []
col: 5869 similar rows:  [5869]
11111111111111111111
incomplete name 3, col: 5869 row: []
col: 5874 similar rows:  [5874]
11111111111111111111
incomplete name 3, col: 5874 row: []
col: 5879 similar rows:  [5879]
11111111111111111111
incomplete name 3, col: 5879 row: []
col: 5881 similar rows:  [5881]
11111111111111111111
incomplete name 3, col: 5881 row: []
col: 5883 similar rows:  [5883]
11111111111111111111
hotelname2 [5883]
incomplete name 3, col: 5883 row: [5883]
col: 5885 similar rows:  [5885]
11111111111111111111
incomplete name 3, col: 5885 row: []
col: 5887 similar rows:  [5887, 6219]
incomplete name 3, col: 5887 row: []
col: 5892 similar rows:  [5892, 6346, 7214]
incomplete name 3, col: 5892 row: []
col: 5893 similar rows:  [5893]
11111111111111111111
incomplete name 3, col: 5893 row: []
col: 5894 similar rows:  [5894]
11111111111111111111
incomplete name 3, col: 5894 row: []
col: 5896 similar rows:  [5896]
11111111111111111111
incomplete name 3, col: 5896 row: []
col: 5897 similar rows:  [5897]
11111111111111111111
incomplete name 3, col: 5897 row: []
col: 5901 similar rows:  [5901, 6114]
incomplete name 3, col: 5901 row: []
col: 5902 similar rows:  [5902]
11111111111111111111
incomplete name 3, col: 5902 row: []
col: 5905 similar rows:  [5905]
11111111111111111111
incomplete name 3, col: 5905 row: []
col: 5906 similar rows:  [5906]
11111111111111111111
incomplete name 3, col: 5906 row: []
col: 5908 similar rows:  [5908]
11111111111111111111
incomplete name 3, col: 5908 row: []
col: 5920 similar rows:  [5920, 6785, 6936]
incomplete name 3, col: 5920 row: []
col: 5923 similar rows:  [5923]
11111111111111111111
incomplete name 3, col: 5923 row: []
col: 5925 similar rows:  [5925]
11111111111111111111
incomplete name 3, col: 5925 row: []
col: 5931 similar rows:  [5931]
11111111111111111111
incomplete name 3, col: 5931 row: []
col: 5933 similar rows:  [5933, 5964, 7141]
incomplete name 3, col: 5933 row: []
col: 5940 similar rows:  [5940, 6875]
incomplete name 3, col: 5940 row: []
col: 5941 similar rows:  [5941]
11111111111111111111
incomplete name 3, col: 5941 row: []
col: 5945 similar rows:  [5945]
11111111111111111111
hotelname2 [5945]
incomplete name 3, col: 5945 row: [5945]
col: 5946 similar rows:  [5946]
11111111111111111111
incomplete name 3, col: 5946 row: []
col: 5947 similar rows:  [5947]
11111111111111111111
incomplete name 3, col: 5947 row: []
col: 5950 similar rows:  [5950, 6645, 6871]
incomplete name 3, col: 5950 row: []
col: 5954 similar rows:  [5954]
11111111111111111111
incomplete name 3, col: 5954 row: []
col: 5957 similar rows:  [5957]
11111111111111111111
hotelname2 [5957]
incomplete name 3, col: 5957 row: [5957]
col: 5961 similar rows:  [5961]
11111111111111111111
incomplete name 3, col: 5961 row: []
col: 5963 similar rows:  [5963, 6876]
incomplete name 3, col: 5963 row: []
col: 5969 similar rows:  [5969]
11111111111111111111
incomplete name 3, col: 5969 row: []
col: 5970 similar rows:  [5970]
11111111111111111111
incomplete name 3, col: 5970 row: []
col: 5972 similar rows:  [5972]
11111111111111111111
hotelname2 [5972]
incomplete name 3, col: 5972 row: [5972]
col: 5973 similar rows:  [5973]
11111111111111111111
incomplete name 3, col: 5973 row: []
col: 5975 similar rows:  [5975]
11111111111111111111
incomplete name 3, col: 5975 row: []
col: 5977 similar rows:  [5977]
11111111111111111111
incomplete name 3, col: 5977 row: []
col: 5978 similar rows:  [5978]
11111111111111111111
incomplete name 3, col: 5978 row: []
col: 5979 similar rows:  [5979]
11111111111111111111
incomplete name 3, col: 5979 row: []
col: 5981 similar rows:  [5981]
11111111111111111111
incomplete name 3, col: 5981 row: []
col: 5982 similar rows:  [5982]
11111111111111111111
incomplete name 3, col: 5982 row: []
col: 5984 similar rows:  [5984]
11111111111111111111
incomplete name 3, col: 5984 row: []

col: 5985 similar rows:  [5985]
11111111111111111111
incomplete name 3, col: 5985 row: []
col: 5987 similar rows:  [5987, 7107]
incomplete name 3, col: 5987 row: []
col: 5988 similar rows:  [5988, 6744]
incomplete name 3, col: 5988 row: []
col: 5990 similar rows:  [5990, 6836, 6850]
incomplete name 3, col: 5990 row: []
col: 5991 similar rows:  [5991]
11111111111111111111
incomplete name 3, col: 5991 row: []
col: 5993 similar rows:  [5993]
11111111111111111111
incomplete name 3, col: 5993 row: []
col: 5994 similar rows:  [5994]
11111111111111111111
incomplete name 3, col: 5994 row: []
col: 5996 similar rows:  [5996]
11111111111111111111
incomplete name 3, col: 5996 row: []
col: 5997 similar rows:  [5997]
11111111111111111111
incomplete name 3, col: 5997 row: []
col: 6000 similar rows:  [6000, 7044]
incomplete name 3, col: 6000 row: []
col: 6001 similar rows:  [6001]
11111111111111111111
incomplete name 3, col: 6001 row: []
col: 6002 similar rows:  [6002]
11111111111111111111
incomplete name 3, col: 6002 row: []
col: 6004 similar rows:  [6004]
11111111111111111111
incomplete name 3, col: 6004 row: []
col: 6005 similar rows:  [6005]
11111111111111111111
incomplete name 3, col: 6005 row: []
col: 6006 similar rows:  [6006]
11111111111111111111
incomplete name 3, col: 6006 row: []
col: 6007 similar rows:  [6007]
11111111111111111111
hotelname2 [6007]
incomplete name 3, col: 6007 row: [6007]
col: 6009 similar rows:  [6009, 6547]
incomplete name 3, col: 6009 row: []
col: 6010 similar rows:  [6010, 6545, 7217]
incomplete name 3, col: 6010 row: []
col: 6011 similar rows:  [6011]
11111111111111111111
hotelname2 [6011]
incomplete name 3, col: 6011 row: [6011]
col: 6012 similar rows:  [6012]
11111111111111111111
incomplete name 3, col: 6012 row: []
col: 6013 similar rows:  [6013]
11111111111111111111
incomplete name 3, col: 6013 row: []
col: 6014 similar rows:  [6014]
11111111111111111111
incomplete name 3, col: 6014 row: []
col: 6015 similar rows:  [6015]
11111111111111111111
incomplete name 3, col: 6015 row: []
col: 6016 similar rows:  [6016]
11111111111111111111
incomplete name 3, col: 6016 row: []
col: 6019 similar rows:  [6019]
11111111111111111111
incomplete name 3, col: 6019 row: []
col: 6020 similar rows:  [6020]
11111111111111111111
incomplete name 3, col: 6020 row: []
col: 6021 similar rows:  [6021]
11111111111111111111
hotelname2 [6021]
incomplete name 3, col: 6021 row: [6021]
col: 6022 similar rows:  [6022]
11111111111111111111
incomplete name 3, col: 6022 row: []
col: 6023 similar rows:  [6023]
11111111111111111111
incomplete name 3, col: 6023 row: []
col: 6025 similar rows:  [6025]
11111111111111111111
incomplete name 3, col: 6025 row: []
col: 6026 similar rows:  [6026]
11111111111111111111
hotelname2 [6026]
incomplete name 3, col: 6026 row: []
col: 6027 similar rows:  [6027]
11111111111111111111
incomplete name 3, col: 6027 row: []
col: 6029 similar rows:  [6029]
11111111111111111111
incomplete name 3, col: 6029 row: []
col: 6030 similar rows:  [6030]
11111111111111111111
incomplete name 3, col: 6030 row: []
col: 6032 similar rows:  [6032]
11111111111111111111
incomplete name 3, col: 6032 row: []
col: 6034 similar rows:  [6034]
11111111111111111111
incomplete name 3, col: 6034 row: []
col: 6035 similar rows:  [6035]
11111111111111111111
incomplete name 3, col: 6035 row: []
col: 6036 similar rows:  [6036]
11111111111111111111
incomplete name 3, col: 6036 row: []
col: 6037 similar rows:  [6037, 7222]
incomplete name 3, col: 6037 row: []
col: 6038 similar rows:  [6038, 6307]
incomplete name 3, col: 6038 row: []
col: 6039 similar rows:  [6039]
11111111111111111111
incomplete name 3, col: 6039 row: []
col: 6040 similar rows:  [6040]
11111111111111111111
incomplete name 3, col: 6040 row: []
col: 6044 similar rows:  [6044, 6791, 7205, 7212]
incomplete name 3, col: 6044 row: []
col: 6045 similar rows:  [6045]
11111111111111111111
incomplete name 3, col: 6045 row: []
col: 6046 similar rows:  [6046]
11111111111111111111
incomplete name 3, col: 6046 row: []
col: 6047 similar rows:  [6047]
11111111111111111111
incomplete name 3, col: 6047 row: []
col: 6048 similar rows:  [6048, 6109]
incomplete name 3, col: 6048 row: []
col: 6049 similar rows:  [6049]
11111111111111111111
incomplete name 3, col: 6049 row: []
col: 6051 similar rows:  [6051]
11111111111111111111
hotelname2 [6051]
incomplete name 3, col: 6051 row: [6051]
col: 6053 similar rows:  [6053]
11111111111111111111
incomplete name 3, col: 6053 row: []
col: 6054 similar rows:  [6054, 6099, 6164, 6174]
incomplete name 3, col: 6054 row: []
col: 6060 similar rows:  [6060]
11111111111111111111
incomplete name 3, col: 6060 row: []
col: 6061 similar rows:  [6061]
11111111111111111111
incomplete name 3, col: 6061 row: []
col: 6068 similar rows:  [6068, 7099]
incomplete name 3, col: 6068 row: []
col: 6072 similar rows:  [6072]
11111111111111111111
incomplete name 3, col: 6072 row: []
col: 6075 similar rows:  [6075]
11111111111111111111
incomplete name 3, col: 6075 row: []
col: 6078 similar rows:  [6078]
11111111111111111111
incomplete name 3, col: 6078 row: []
col: 6079 similar rows:  [6079]
11111111111111111111
hotelname2 [6079]
incomplete name 3, col: 6079 row: []
col: 6082 similar rows:  [6082]
11111111111111111111
incomplete name 3, col: 6082 row: []
col: 6085 similar rows:  [6085]
11111111111111111111
incomplete name 3, col: 6085 row: []
col: 6086 similar rows:  [6086, 6120, 6388]
incomplete name 3, col: 6086 row: []
col: 6087 similar rows:  [6087, 6316, 7034]
incomplete name 3, col: 6087 row: []
col: 6088 similar rows:  [6088, 6093, 6993, 7187]
incomplete name 3, col: 6088 row: []
col: 6089 similar rows:  [6089]
11111111111111111111
incomplete name 3, col: 6089 row: []
col: 6091 similar rows:  [6091]
11111111111111111111
incomplete name 3, col: 6091 row: []
col: 6092 similar rows:  [6092]
11111111111111111111
incomplete name 3, col: 6092 row: []
col: 6094 similar rows:  [6094, 7129]
incomplete name 3, col: 6094 row: []
col: 6095 similar rows:  [6095]
11111111111111111111
incomplete name 3, col: 6095 row: []
col: 6096 similar rows:  [6096]
11111111111111111111
incomplete name 3, col: 6096 row: []
col: 6097 similar rows:  [6097]
11111111111111111111
incomplete name 3, col: 6097 row: []
col: 6100 similar rows:  [6100]
11111111111111111111
incomplete name 3, col: 6100 row: []
col: 6104 similar rows:  [6104]
11111111111111111111
incomplete name 3, col: 6104 row: []
col: 6105 similar rows:  [6105]
11111111111111111111
incomplete name 3, col: 6105 row: []
col: 6107 similar rows:  [6107]
11111111111111111111
incomplete name 3, col: 6107 row: []
col: 6108 similar rows:  [6108]
11111111111111111111
incomplete name 3, col: 6108 row: []
col: 6110 similar rows:  [6110, 6144]
incomplete name 3, col: 6110 row: []
col: 6111 similar rows:  [6111]
11111111111111111111
hotelname2 [6111]
incomplete name 3, col: 6111 row: [6111]
col: 6115 similar rows:  [6115]
11111111111111111111
incomplete name 3, col: 6115 row: []
col: 6117 similar rows:  [6117, 7171]
incomplete name 3, col: 6117 row: []
col: 6118 similar rows:  [6118, 6340]
incomplete name 3, col: 6118 row: []
col: 6119 similar rows:  [6119]
11111111111111111111
incomplete name 3, col: 6119 row: []
col: 6121 similar rows:  [6121]
11111111111111111111
incomplete name 3, col: 6121 row: []
col: 6125 similar rows:  [6125]
11111111111111111111
incomplete name 3, col: 6125 row: []
col: 6127 similar rows:  [6127, 6184, 6650, 7221]
incomplete name 3, col: 6127 row: []
col: 6128 similar rows:  [6128]
11111111111111111111
incomplete name 3, col: 6128 row: []
col: 6130 similar rows:  [6130]
11111111111111111111
incomplete name 3, col: 6130 row: []
col: 6133 similar rows:  [6133]
11111111111111111111
incomplete name 3, col: 6133 row: []
col: 6136 similar rows:  [6136]
11111111111111111111
incomplete name 3, col: 6136 row: []
col: 6137 similar rows:  [6137]
11111111111111111111
hotelname2 [6137]
incomplete name 3, col: 6137 row: []
col: 6141 similar rows:  [6141]
11111111111111111111
hotelname2 [6141]
incomplete name 3, col: 6141 row: []
col: 6143 similar rows:  [6143]
11111111111111111111
incomplete name 3, col: 6143 row: []
col: 6146 similar rows:  [6146, 6603]
incomplete name 3, col: 6146 row: []
col: 6147 similar rows:  [6147]
11111111111111111111
incomplete name 3, col: 6147 row: []

col: 6149 similar rows:  [6149]
11111111111111111111
incomplete name 3, col: 6149 row: []
col: 6151 similar rows:  [6151]
11111111111111111111
hotelname2 [6151]
incomplete name 3, col: 6151 row: []
col: 6154 similar rows:  [6154, 6173]
incomplete name 3, col: 6154 row: []
col: 6155 similar rows:  [6155]
11111111111111111111
incomplete name 3, col: 6155 row: []
col: 6156 similar rows:  [6156]
11111111111111111111
incomplete name 3, col: 6156 row: []
col: 6159 similar rows:  [6159]
11111111111111111111
incomplete name 3, col: 6159 row: []
col: 6160 similar rows:  [6160, 6348]
incomplete name 3, col: 6160 row: []
col: 6163 similar rows:  [6163]
11111111111111111111
incomplete name 3, col: 6163 row: []
col: 6166 similar rows:  [6166]
11111111111111111111
hotelname2 [6166]
incomplete name 3, col: 6166 row: [6166]
col: 6167 similar rows:  [6167]
11111111111111111111
incomplete name 3, col: 6167 row: []
col: 6169 similar rows:  [6169, 6170]
incomplete name 3, col: 6169 row: []
col: 6175 similar rows:  [6175]
11111111111111111111
incomplete name 3, col: 6175 row: []
col: 6177 similar rows:  [6177]
11111111111111111111
incomplete name 3, col: 6177 row: []
col: 6178 similar rows:  [6178, 6360]
incomplete name 3, col: 6178 row: []
col: 6179 similar rows:  [6179]
11111111111111111111
incomplete name 3, col: 6179 row: []
col: 6180 similar rows:  [6180]
11111111111111111111
incomplete name 3, col: 6180 row: []
col: 6182 similar rows:  [6182]
11111111111111111111
incomplete name 3, col: 6182 row: []
col: 6183 similar rows:  [6183]
11111111111111111111
incomplete name 3, col: 6183 row: []
col: 6185 similar rows:  [6185]
11111111111111111111
hotelname2 [6185]
incomplete name 3, col: 6185 row: []
col: 6186 similar rows:  [6186]
11111111111111111111
hotelname2 [6186]
incomplete name 3, col: 6186 row: [6186]
col: 6188 similar rows:  [6188]
11111111111111111111
incomplete name 3, col: 6188 row: []
col: 6196 similar rows:  [6196]
11111111111111111111
incomplete name 3, col: 6196 row: []
col: 6198 similar rows:  [6198, 6217, 6831]
incomplete name 3, col: 6198 row: []
col: 6206 similar rows:  [6206]
11111111111111111111
hotelname2 [6206]
incomplete name 3, col: 6206 row: [6206]
col: 6208 similar rows:  [6208, 6284]
incomplete name 3, col: 6208 row: []
col: 6209 similar rows:  [6209]
11111111111111111111
incomplete name 3, col: 6209 row: []
col: 6210 similar rows:  [6210]
11111111111111111111
hotelname2 [6210]
incomplete name 3, col: 6210 row: [6210]
col: 6213 similar rows:  [6213, 7033]
incomplete name 3, col: 6213 row: []
col: 6215 similar rows:  [6215]
11111111111111111111
incomplete name 3, col: 6215 row: []
col: 6216 similar rows:  [6216]
11111111111111111111
incomplete name 3, col: 6216 row: []
col: 6220 similar rows:  [6220]
11111111111111111111
incomplete name 3, col: 6220 row: []
col: 6222 similar rows:  [6222, 6251]
incomplete name 3, col: 6222 row: []
col: 6224 similar rows:  [6224]
11111111111111111111
incomplete name 3, col: 6224 row: []
col: 6226 similar rows:  [6226]
11111111111111111111
incomplete name 3, col: 6226 row: []
col: 6227 similar rows:  [6227]
11111111111111111111
hotelname2 [6227]
incomplete name 3, col: 6227 row: [6227]
col: 6230 similar rows:  [6230, 6474]
incomplete name 3, col: 6230 row: []
col: 6231 similar rows:  [6231]
11111111111111111111
hotelname2 [6231]
incomplete name 3, col: 6231 row: [6231]
col: 6232 similar rows:  [6232]
11111111111111111111
incomplete name 3, col: 6232 row: []
col: 6234 similar rows:  [6234]
11111111111111111111
incomplete name 3, col: 6234 row: []
col: 6238 similar rows:  [6238]
11111111111111111111
incomplete name 3, col: 6238 row: []
col: 6239 similar rows:  [6239]
11111111111111111111
incomplete name 3, col: 6239 row: []
col: 6242 similar rows:  [6242]
11111111111111111111
incomplete name 3, col: 6242 row: []
col: 6244 similar rows:  [6244]
11111111111111111111
incomplete name 3, col: 6244 row: []
col: 6245 similar rows:  [6245, 6518]
incomplete name 3, col: 6245 row: []
col: 6247 similar rows:  [6247]
11111111111111111111
incomplete name 3, col: 6247 row: []
col: 6249 similar rows:  [6249]
11111111111111111111
incomplete name 3, col: 6249 row: []
col: 6250 similar rows:  [6250]
11111111111111111111
incomplete name 3, col: 6250 row: []
col: 6252 similar rows:  [6252]
11111111111111111111
incomplete name 3, col: 6252 row: []
col: 6253 similar rows:  [6253, 6372]
incomplete name 3, col: 6253 row: []
col: 6256 similar rows:  [6256, 6862]
incomplete name 3, col: 6256 row: []
col: 6258 similar rows:  [6258]
11111111111111111111
incomplete name 3, col: 6258 row: []
col: 6261 similar rows:  [6261]
11111111111111111111
hotelname2 [6261]
incomplete name 3, col: 6261 row: [6261]
col: 6265 similar rows:  [6265]
11111111111111111111
hotelname2 [6265]
incomplete name 3, col: 6265 row: [6265]
col: 6267 similar rows:  [6267, 7097]
incomplete name 3, col: 6267 row: []
col: 6269 similar rows:  [6269]
11111111111111111111
incomplete name 3, col: 6269 row: []
col: 6270 similar rows:  [6270]
11111111111111111111
hotelname2 [6270]
incomplete name 3, col: 6270 row: []
col: 6271 similar rows:  [6271]
11111111111111111111
hotelname2 [6271]
incomplete name 3, col: 6271 row: [6271]
col: 6272 similar rows:  [6272]
11111111111111111111
incomplete name 3, col: 6272 row: []
col: 6273 similar rows:  [6273]
11111111111111111111
hotelname2 [6273]
incomplete name 3, col: 6273 row: [6273]
col: 6274 similar rows:  [6274, 6609]
incomplete name 3, col: 6274 row: []
col: 6278 similar rows:  [6278]
11111111111111111111
hotelname2 [6278]
incomplete name 3, col: 6278 row: [6278]
col: 6280 similar rows:  [6280]
11111111111111111111
incomplete name 3, col: 6280 row: []
col: 6282 similar rows:  [6282, 6627, 6913, 7130]
incomplete name 3, col: 6282 row: []
col: 6283 similar rows:  [6283]
11111111111111111111
hotelname2 [6283]
incomplete name 3, col: 6283 row: [6283]
col: 6285 similar rows:  [6285]
11111111111111111111
incomplete name 3, col: 6285 row: []
col: 6287 similar rows:  [6287]
11111111111111111111
incomplete name 3, col: 6287 row: []
col: 6288 similar rows:  [6288]
11111111111111111111
incomplete name 3, col: 6288 row: []
col: 6289 similar rows:  [6289]
11111111111111111111
incomplete name 3, col: 6289 row: []
col: 6290 similar rows:  [6290]
11111111111111111111
incomplete name 3, col: 6290 row: []
col: 6291 similar rows:  [6291]
11111111111111111111
hotelname2 [6291]
wrong name!!!!
incomplete name 3, col: 6291 row: [6291]
col: 6293 similar rows:  [6293]
11111111111111111111
incomplete name 3, col: 6293 row: []
col: 6294 similar rows:  [6294]
11111111111111111111
incomplete name 3, col: 6294 row: []
col: 6296 similar rows:  [6296]
11111111111111111111
hotelname2 [6296]
incomplete name 3, col: 6296 row: [6296]
col: 6297 similar rows:  [6297]
11111111111111111111
incomplete name 3, col: 6297 row: []
col: 6299 similar rows:  [6299]
11111111111111111111
hotelname2 [6299]
incomplete name 3, col: 6299 row: []
col: 6302 similar rows:  [6302]
11111111111111111111
hotelname2 [6302]
incomplete name 3, col: 6302 row: []
col: 6304 similar rows:  [6304]
11111111111111111111
hotelname2 [6304]
incomplete name 3, col: 6304 row: [6304]
col: 6305 similar rows:  [6305]
11111111111111111111
incomplete name 3, col: 6305 row: []
col: 6306 similar rows:  [6306, 6330]
incomplete name 3, col: 6306 row: []
col: 6308 similar rows:  [6308]
11111111111111111111
incomplete name 3, col: 6308 row: []
col: 6309 similar rows:  [6309]
11111111111111111111
incomplete name 3, col: 6309 row: []
col: 6310 similar rows:  [6310]
11111111111111111111
incomplete name 3, col: 6310 row: []
col: 6313 similar rows:  [6313]
11111111111111111111
incomplete name 3, col: 6313 row: []
col: 6314 similar rows:  [6314]
11111111111111111111
incomplete name 3, col: 6314 row: []
col: 6315 similar rows:  [6315]
11111111111111111111
incomplete name 3, col: 6315 row: []
col: 6318 similar rows:  [6318]
11111111111111111111
incomplete name 3, col: 6318 row: []
col: 6319 similar rows:  [6319]
11111111111111111111
incomplete name 3, col: 6319 row: []
col: 6321 similar rows:  [6321]
11111111111111111111
incomplete name 3, col: 6321 row: []
col: 6323 similar rows:  [6323]
11111111111111111111
hotelname2 [6323]
incomplete name 3, col: 6323 row: [6323]

col: 6324 similar rows:  [6324]
11111111111111111111
incomplete name 3, col: 6324 row: []
col: 6325 similar rows:  [6325]
11111111111111111111
incomplete name 3, col: 6325 row: []
col: 6328 similar rows:  [6328]
11111111111111111111
incomplete name 3, col: 6328 row: []
col: 6329 similar rows:  [6329]
11111111111111111111
incomplete name 3, col: 6329 row: []
col: 6331 similar rows:  [6331]
11111111111111111111
hotelname2 [6331]
incomplete name 3, col: 6331 row: [6331]
col: 6332 similar rows:  [6332]
11111111111111111111
incomplete name 3, col: 6332 row: []
col: 6333 similar rows:  [6333]
11111111111111111111
hotelname2 [6333]
incomplete name 3, col: 6333 row: [6333]
col: 6334 similar rows:  [6334]
11111111111111111111
incomplete name 3, col: 6334 row: []
col: 6336 similar rows:  [6336]
11111111111111111111
hotelname2 [6336]
incomplete name 3, col: 6336 row: [6336]
col: 6339 similar rows:  [6339]
11111111111111111111
incomplete name 3, col: 6339 row: []
col: 6349 similar rows:  [6349, 6457, 6961]
incomplete name 3, col: 6349 row: []
col: 6355 similar rows:  [6355]
11111111111111111111
incomplete name 3, col: 6355 row: []
col: 6357 similar rows:  [6357]
11111111111111111111
incomplete name 3, col: 6357 row: []
col: 6363 similar rows:  [6363]
11111111111111111111
incomplete name 3, col: 6363 row: []
col: 6368 similar rows:  [6368, 6582]
incomplete name 3, col: 6368 row: []
col: 6373 similar rows:  [6373]
11111111111111111111
incomplete name 3, col: 6373 row: []
col: 6381 similar rows:  [6381]
11111111111111111111
incomplete name 3, col: 6381 row: []
col: 6382 similar rows:  [6382]
11111111111111111111
incomplete name 3, col: 6382 row: []
col: 6385 similar rows:  [6385]
11111111111111111111
hotelname2 [6385]
incomplete name 3, col: 6385 row: [6385]
col: 6387 similar rows:  [6387]
11111111111111111111
hotelname2 [6387]
incomplete name 3, col: 6387 row: [6387]
col: 6389 similar rows:  [6389]
11111111111111111111
incomplete name 3, col: 6389 row: []
col: 6391 similar rows:  [6391]
11111111111111111111
incomplete name 3, col: 6391 row: []
col: 6392 similar rows:  [6392]
11111111111111111111
incomplete name 3, col: 6392 row: []
col: 6395 similar rows:  [6395]
11111111111111111111
incomplete name 3, col: 6395 row: []
col: 6400 similar rows:  [6400]
11111111111111111111
incomplete name 3, col: 6400 row: []
col: 6402 similar rows:  [6402]
11111111111111111111
incomplete name 3, col: 6402 row: []
col: 6406 similar rows:  [6406]
11111111111111111111
incomplete name 3, col: 6406 row: []
col: 6407 similar rows:  [6407]
11111111111111111111
incomplete name 3, col: 6407 row: []
col: 6409 similar rows:  [6409]
11111111111111111111
incomplete name 3, col: 6409 row: []
col: 6410 similar rows:  [6410]
11111111111111111111
incomplete name 3, col: 6410 row: []
col: 6411 similar rows:  [6411, 7080]
incomplete name 3, col: 6411 row: []
col: 6412 similar rows:  [6412]
11111111111111111111
incomplete name 3, col: 6412 row: []
col: 6413 similar rows:  [6413]
11111111111111111111
incomplete name 3, col: 6413 row: []
col: 6415 similar rows:  [6415]
11111111111111111111
incomplete name 3, col: 6415 row: []
col: 6416 similar rows:  [6416]
11111111111111111111
incomplete name 3, col: 6416 row: []
col: 6418 similar rows:  [6418]
11111111111111111111
incomplete name 3, col: 6418 row: []
col: 6420 similar rows:  [6420]
11111111111111111111
incomplete name 3, col: 6420 row: []
col: 6423 similar rows:  [6423]
11111111111111111111
incomplete name 3, col: 6423 row: []
col: 6429 similar rows:  [6429]
11111111111111111111
incomplete name 3, col: 6429 row: []
col: 6431 similar rows:  [6431]
11111111111111111111
hotelname2 [6431]
incomplete name 3, col: 6431 row: [6431]
col: 6436 similar rows:  [6436]
11111111111111111111
hotelname2 [6436]
incomplete name 3, col: 6436 row: [6436]
col: 6443 similar rows:  [6443, 7035]
incomplete name 3, col: 6443 row: []
col: 6444 similar rows:  [6444, 6674, 6720]
incomplete name 3, col: 6444 row: []
col: 6445 similar rows:  [6445]
11111111111111111111
incomplete name 3, col: 6445 row: []
col: 6473 similar rows:  [6473, 6490]
incomplete name 3, col: 6473 row: []
col: 6475 similar rows:  [6475]
11111111111111111111
incomplete name 3, col: 6475 row: []
col: 6478 similar rows:  [6478]
11111111111111111111
incomplete name 3, col: 6478 row: []
col: 6480 similar rows:  [6480]
11111111111111111111
incomplete name 3, col: 6480 row: []
col: 6488 similar rows:  [6488]
11111111111111111111
hotelname2 [6488]
incomplete name 3, col: 6488 row: [6488]
col: 6494 similar rows:  [6494, 6631]
incomplete name 3, col: 6494 row: []
col: 6496 similar rows:  [6496]
11111111111111111111
incomplete name 3, col: 6496 row: []
col: 6499 similar rows:  [6499, 6639, 6647, 6858]
incomplete name 3, col: 6499 row: []
col: 6500 similar rows:  [6500]
11111111111111111111
incomplete name 3, col: 6500 row: []
col: 6502 similar rows:  [6502]
11111111111111111111
incomplete name 3, col: 6502 row: []
col: 6505 similar rows:  [6505]
11111111111111111111
hotelname2 [6505]
incomplete name 3, col: 6505 row: []
col: 6506 similar rows:  [6506]
11111111111111111111
incomplete name 3, col: 6506 row: []
col: 6509 similar rows:  [6509, 6593, 7015, 7081, 7121, 7126, 7168]
incomplete name 3, col: 6509 row: []
col: 6510 similar rows:  [6510]
11111111111111111111
incomplete name 3, col: 6510 row: []
col: 6512 similar rows:  [6512]
11111111111111111111
incomplete name 3, col: 6512 row: []
col: 6514 similar rows:  [6514, 6841]
incomplete name 3, col: 6514 row: []
col: 6524 similar rows:  [6524]
11111111111111111111
incomplete name 3, col: 6524 row: []
col: 6526 similar rows:  [6526]
11111111111111111111
hotelname2 [6526]
incomplete name 3, col: 6526 row: []
col: 6532 similar rows:  [6532]
11111111111111111111
incomplete name 3, col: 6532 row: []
col: 6535 similar rows:  [6535]
11111111111111111111
incomplete name 3, col: 6535 row: []
col: 6541 similar rows:  [6541]
11111111111111111111
incomplete name 3, col: 6541 row: []
col: 6544 similar rows:  [6544]
11111111111111111111
incomplete name 3, col: 6544 row: []
col: 6546 similar rows:  [6546]
11111111111111111111
incomplete name 3, col: 6546 row: []
col: 6548 similar rows:  [6548]
11111111111111111111
incomplete name 3, col: 6548 row: []
col: 6550 similar rows:  [6550]
11111111111111111111
incomplete name 3, col: 6550 row: []
col: 6551 similar rows:  [6551]
11111111111111111111
incomplete name 3, col: 6551 row: []
col: 6553 similar rows:  [6553]
11111111111111111111
incomplete name 3, col: 6553 row: []
col: 6555 similar rows:  [6555]
11111111111111111111
incomplete name 3, col: 6555 row: []
col: 6560 similar rows:  [6560]
11111111111111111111
incomplete name 3, col: 6560 row: []
col: 6561 similar rows:  [6561]
11111111111111111111
hotelname2 [6561]
incomplete name 3, col: 6561 row: [6561]
col: 6562 similar rows:  [6562]
11111111111111111111
incomplete name 3, col: 6562 row: []
col: 6564 similar rows:  [6564]
11111111111111111111
incomplete name 3, col: 6564 row: []
col: 6566 similar rows:  [6566]
11111111111111111111
incomplete name 3, col: 6566 row: []
col: 6569 similar rows:  [6569]
11111111111111111111
incomplete name 3, col: 6569 row: []
col: 6571 similar rows:  [6571]
11111111111111111111
incomplete name 3, col: 6571 row: []
col: 6572 similar rows:  [6572]
11111111111111111111
incomplete name 3, col: 6572 row: []
col: 6573 similar rows:  [6573]
11111111111111111111
incomplete name 3, col: 6573 row: []
col: 6575 similar rows:  [6575]
11111111111111111111
incomplete name 3, col: 6575 row: []
col: 6576 similar rows:  [6576]
11111111111111111111
incomplete name 3, col: 6576 row: []
col: 6578 similar rows:  [6578]
11111111111111111111
incomplete name 3, col: 6578 row: []
col: 6581 similar rows:  [6581]
11111111111111111111
hotelname2 [6581]
incomplete name 3, col: 6581 row: [6581]
col: 6583 similar rows:  [6583]
11111111111111111111
incomplete name 3, col: 6583 row: []
col: 6585 similar rows:  [6585]
11111111111111111111
incomplete name 3, col: 6585 row: []
col: 6587 similar rows:  [6587]
11111111111111111111
incomplete name 3, col: 6587 row: []
col: 6589 similar rows:  [6589]
11111111111111111111
incomplete name 3, col: 6589 row: []
col: 6590 similar rows:  [6590]
11111111111111111111
incomplete name 3, col: 6590 row: []
col: 6598 similar rows:  [6598]
11111111111111111111
incomplete name 3, col: 6598 row: []
col: 6600 similar rows:  [6600]
11111111111111111111
incomplete name 3, col: 6600 row: []
col: 6607 similar rows:  [6607]
11111111111111111111
hotelname2 [6607]
incomplete name 3, col: 6607 row: [6607]
col: 6608 similar rows:  [6608, 6620, 6640, 6658, 6942, 7002, 7089]
incomplete name 3, col: 6608 row: []
col: 6610 similar rows:  [6610]
11111111111111111111
hotelname2 [6610]
incomplete name 3, col: 6610 row: [6610]

col: 6614 similar rows:  [6614, 6917]
incomplete name 3, col: 6614 row: []
col: 6618 similar rows:  [6618]
11111111111111111111
incomplete name 3, col: 6618 row: []
col: 6622 similar rows:  [6622]
11111111111111111111
incomplete name 3, col: 6622 row: []
col: 6623 similar rows:  [6623]
11111111111111111111
incomplete name 3, col: 6623 row: []
col: 6628 similar rows:  [6628]
11111111111111111111
incomplete name 3, col: 6628 row: []
col: 6633 similar rows:  [6633]
11111111111111111111
incomplete name 3, col: 6633 row: []
col: 6638 similar rows:  [6638]
11111111111111111111
incomplete name 3, col: 6638 row: []
col: 6641 similar rows:  [6641]
11111111111111111111
incomplete name 3, col: 6641 row: []
col: 6642 similar rows:  [6642, 7016, 7056, 7063, 7069, 7162]
incomplete name 3, col: 6642 row: []
col: 6643 similar rows:  [6643]
11111111111111111111
incomplete name 3, col: 6643 row: []
col: 6644 similar rows:  [6644]
11111111111111111111
incomplete name 3, col: 6644 row: []
col: 6648 similar rows:  [6648]
11111111111111111111
incomplete name 3, col: 6648 row: []
col: 6651 similar rows:  [6651]
11111111111111111111
incomplete name 3, col: 6651 row: []
col: 6652 similar rows:  [6652]
11111111111111111111
incomplete name 3, col: 6652 row: []
col: 6654 similar rows:  [6654, 7144]
incomplete name 3, col: 6654 row: []
col: 6655 similar rows:  [6655]
11111111111111111111
incomplete name 3, col: 6655 row: []
col: 6657 similar rows:  [6657, 7144]
incomplete name 3, col: 6657 row: []
col: 6659 similar rows:  [6659]
11111111111111111111
incomplete name 3, col: 6659 row: []
col: 6661 similar rows:  [6661]
11111111111111111111
incomplete name 3, col: 6661 row: []
col: 6662 similar rows:  [6662]
11111111111111111111
incomplete name 3, col: 6662 row: []
col: 6663 similar rows:  [6663]
11111111111111111111
incomplete name 3, col: 6663 row: []
col: 6664 similar rows:  [6664]
11111111111111111111
incomplete name 3, col: 6664 row: []
col: 6665 similar rows:  [6665]
11111111111111111111
incomplete name 3, col: 6665 row: []
col: 6680 similar rows:  [6680, 7062]
incomplete name 3, col: 6680 row: []
col: 6695 similar rows:  [6695]
11111111111111111111
incomplete name 3, col: 6695 row: []
col: 6696 similar rows:  [6696, 6734]
incomplete name 3, col: 6696 row: []
col: 6697 similar rows:  [6697, 6704, 6710]
incomplete name 3, col: 6697 row: []
col: 6699 similar rows:  [6699]
11111111111111111111
incomplete name 3, col: 6699 row: []
col: 6721 similar rows:  [6721]
11111111111111111111
incomplete name 3, col: 6721 row: []
col: 6724 similar rows:  [6724, 7013]
incomplete name 3, col: 6724 row: []
col: 6733 similar rows:  [6733]
11111111111111111111
hotelname2 [6733]
incomplete name 3, col: 6733 row: [6733]
col: 6736 similar rows:  [6736]
11111111111111111111
hotelname2 [6736]
incomplete name 3, col: 6736 row: []
col: 6739 similar rows:  [6739]
11111111111111111111
incomplete name 3, col: 6739 row: []
col: 6740 similar rows:  [6740]
11111111111111111111
incomplete name 3, col: 6740 row: []
col: 6742 similar rows:  [6742]
11111111111111111111
incomplete name 3, col: 6742 row: []
col: 6743 similar rows:  [6743]
11111111111111111111
incomplete name 3, col: 6743 row: []
col: 6745 similar rows:  [6745]
11111111111111111111
hotelname2 [6745]
incomplete name 3, col: 6745 row: []
col: 6746 similar rows:  [6746]
11111111111111111111
incomplete name 3, col: 6746 row: []
col: 6747 similar rows:  [6747]
11111111111111111111
incomplete name 3, col: 6747 row: []
col: 6748 similar rows:  [6748]
11111111111111111111
incomplete name 3, col: 6748 row: []
col: 6749 similar rows:  [6749]
11111111111111111111
hotelname2 [6749]
incomplete name 3, col: 6749 row: [6749]
col: 6750 similar rows:  [6750]
11111111111111111111
incomplete name 3, col: 6750 row: []
col: 6754 similar rows:  [6754]
11111111111111111111
incomplete name 3, col: 6754 row: []
col: 6756 similar rows:  [6756]
11111111111111111111
incomplete name 3, col: 6756 row: []
col: 6757 similar rows:  [6757]
11111111111111111111
incomplete name 3, col: 6757 row: []
col: 6759 similar rows:  [6759, 6961]
incomplete name 3, col: 6759 row: []
col: 6760 similar rows:  [6760]
11111111111111111111
incomplete name 3, col: 6760 row: []
col: 6761 similar rows:  [6761]
11111111111111111111
incomplete name 3, col: 6761 row: []
col: 6763 similar rows:  [6763]
11111111111111111111
hotelname2 [6763]
incomplete name 3, col: 6763 row: []
col: 6764 similar rows:  [6764]
11111111111111111111
incomplete name 3, col: 6764 row: []
col: 6766 similar rows:  [6766]
11111111111111111111
incomplete name 3, col: 6766 row: []
col: 6767 similar rows:  [6767]
11111111111111111111
incomplete name 3, col: 6767 row: []
col: 6768 similar rows:  [6768]
11111111111111111111
incomplete name 3, col: 6768 row: []
col: 6769 similar rows:  [6769]
11111111111111111111
hotelname2 [6769]
wrong name!!!!
incomplete name 3, col: 6769 row: [6769]
col: 6771 similar rows:  [6771]
11111111111111111111
incomplete name 3, col: 6771 row: []
col: 6775 similar rows:  [6775]
11111111111111111111
incomplete name 3, col: 6775 row: []
col: 6779 similar rows:  [6779]
11111111111111111111
incomplete name 3, col: 6779 row: []
col: 6781 similar rows:  [6781]
11111111111111111111
incomplete name 3, col: 6781 row: []
col: 6788 similar rows:  [6788]
11111111111111111111
hotelname2 [6788]
incomplete name 3, col: 6788 row: [6788]
col: 6792 similar rows:  [6792]
11111111111111111111
hotelname2 [6792]
incomplete name 3, col: 6792 row: [6792]
col: 6794 similar rows:  [6794]
11111111111111111111
incomplete name 3, col: 6794 row: []
col: 6795 similar rows:  [6795]
11111111111111111111
incomplete name 3, col: 6795 row: []
col: 6796 similar rows:  [6796]
11111111111111111111
incomplete name 3, col: 6796 row: []
col: 6806 similar rows:  [6806, 6889, 6907]
incomplete name 3, col: 6806 row: []
col: 6810 similar rows:  [6810]
11111111111111111111
incomplete name 3, col: 6810 row: []
col: 6819 similar rows:  [6819]
11111111111111111111
incomplete name 3, col: 6819 row: []
col: 6825 similar rows:  [6825]
11111111111111111111
incomplete name 3, col: 6825 row: []
col: 6828 similar rows:  [6828]
11111111111111111111
incomplete name 3, col: 6828 row: []
col: 6835 similar rows:  [6835]
11111111111111111111
incomplete name 3, col: 6835 row: []
col: 6838 similar rows:  [6838]
11111111111111111111
incomplete name 3, col: 6838 row: []
col: 6839 similar rows:  [6839, 6864]
incomplete name 3, col: 6839 row: []
col: 6840 similar rows:  [6840]
11111111111111111111
incomplete name 3, col: 6840 row: []
col: 6843 similar rows:  [6843]
11111111111111111111
incomplete name 3, col: 6843 row: []
col: 6849 similar rows:  [6849]
11111111111111111111
incomplete name 3, col: 6849 row: []
col: 6854 similar rows:  [6854]
11111111111111111111
incomplete name 3, col: 6854 row: []
col: 6861 similar rows:  [6861]
11111111111111111111
incomplete name 3, col: 6861 row: []
col: 6865 similar rows:  [6865]
11111111111111111111
hotelname2 [6865]
incomplete name 3, col: 6865 row: [6865]
col: 6866 similar rows:  [6866]
11111111111111111111
incomplete name 3, col: 6866 row: []
col: 6867 similar rows:  [6867]
11111111111111111111
hotelname2 [6867]
incomplete name 3, col: 6867 row: [6867]
col: 6879 similar rows:  [6879]
11111111111111111111
incomplete name 3, col: 6879 row: []
col: 6880 similar rows:  [6880]
11111111111111111111
hotelname2 [6880]
incomplete name 3, col: 6880 row: [6880]
col: 6882 similar rows:  [6882, 6889, 6907]
incomplete name 3, col: 6882 row: []
col: 6884 similar rows:  [6884, 6902]
incomplete name 3, col: 6884 row: []
col: 6885 similar rows:  [6885]
11111111111111111111
incomplete name 3, col: 6885 row: []
col: 6887 similar rows:  [6887]
11111111111111111111
incomplete name 3, col: 6887 row: []
col: 6888 similar rows:  [6888]
11111111111111111111
incomplete name 3, col: 6888 row: []
col: 6893 similar rows:  [6893]
11111111111111111111
incomplete name 3, col: 6893 row: []
col: 6896 similar rows:  [6896]
11111111111111111111
incomplete name 3, col: 6896 row: []
col: 6897 similar rows:  [6897]
11111111111111111111
incomplete name 3, col: 6897 row: []
col: 6899 similar rows:  [6899]
11111111111111111111
incomplete name 3, col: 6899 row: []
col: 6908 similar rows:  [6908]
11111111111111111111
incomplete name 3, col: 6908 row: []
col: 6911 similar rows:  [6911]
11111111111111111111
hotelname2 [6911]
incomplete name 3, col: 6911 row: [6911]
col: 6919 similar rows:  [6919]
11111111111111111111
incomplete name 3, col: 6919 row: []
col: 6921 similar rows:  [6921]
11111111111111111111
incomplete name 3, col: 6921 row: []
col: 6922 similar rows:  [6922, 7092, 7111, 7134]
incomplete name 3, col: 6922 row: []

col: 6924 similar rows:  [6924]
11111111111111111111
incomplete name 3, col: 6924 row: []
col: 6926 similar rows:  [6926]
11111111111111111111
incomplete name 3, col: 6926 row: []
col: 6928 similar rows:  [6928]
11111111111111111111
incomplete name 3, col: 6928 row: []
col: 6929 similar rows:  [6929]
11111111111111111111
incomplete name 3, col: 6929 row: []
col: 6930 similar rows:  [6930]
11111111111111111111
incomplete name 3, col: 6930 row: []
col: 6931 similar rows:  [6931]
11111111111111111111
hotelname2 [6931]
incomplete name 3, col: 6931 row: [6931]
col: 6933 similar rows:  [6933]
11111111111111111111
incomplete name 3, col: 6933 row: []
col: 6938 similar rows:  [6938]
11111111111111111111
incomplete name 3, col: 6938 row: []
col: 6939 similar rows:  [6939]
11111111111111111111
incomplete name 3, col: 6939 row: []
col: 6941 similar rows:  [6941]
11111111111111111111
incomplete name 3, col: 6941 row: []
col: 6945 similar rows:  [6945]
11111111111111111111
hotelname2 [6945]
incomplete name 3, col: 6945 row: []
col: 6949 similar rows:  [6949]
11111111111111111111
incomplete name 3, col: 6949 row: []
col: 6952 similar rows:  [6952]
11111111111111111111
incomplete name 3, col: 6952 row: []
col: 6956 similar rows:  [6956]
11111111111111111111
hotelname2 [6956]
incomplete name 3, col: 6956 row: [6956]
col: 6957 similar rows:  [6957]
11111111111111111111
incomplete name 3, col: 6957 row: []
col: 6960 similar rows:  [6960]
11111111111111111111
incomplete name 3, col: 6960 row: []
col: 6965 similar rows:  [6965]
11111111111111111111
hotelname2 [6965]
incomplete name 3, col: 6965 row: [6965]
col: 6968 similar rows:  [6968, 7182]
incomplete name 3, col: 6968 row: []
col: 6971 similar rows:  [6971]
11111111111111111111
incomplete name 3, col: 6971 row: []
col: 6975 similar rows:  [6975]
11111111111111111111
incomplete name 3, col: 6975 row: []
col: 6977 similar rows:  [6977]
11111111111111111111
incomplete name 3, col: 6977 row: []
col: 6981 similar rows:  [6981]
11111111111111111111
incomplete name 3, col: 6981 row: []
col: 6982 similar rows:  [6982]
11111111111111111111
incomplete name 3, col: 6982 row: []
col: 6983 similar rows:  [6983]
11111111111111111111
incomplete name 3, col: 6983 row: []
col: 6987 similar rows:  [6987]
11111111111111111111
incomplete name 3, col: 6987 row: []
col: 6988 similar rows:  [6988]
11111111111111111111
incomplete name 3, col: 6988 row: []
col: 6989 similar rows:  [6989]
11111111111111111111
incomplete name 3, col: 6989 row: []
col: 6994 similar rows:  [6994]
11111111111111111111
incomplete name 3, col: 6994 row: []
col: 6995 similar rows:  [6995]
11111111111111111111
incomplete name 3, col: 6995 row: []
col: 6997 similar rows:  [6997]
11111111111111111111
incomplete name 3, col: 6997 row: []
col: 6998 similar rows:  [6998]
11111111111111111111
incomplete name 3, col: 6998 row: []
col: 6999 similar rows:  [6999]
11111111111111111111
incomplete name 3, col: 6999 row: []
col: 7006 similar rows:  [7006]
11111111111111111111
incomplete name 3, col: 7006 row: []
col: 7008 similar rows:  [7008]
11111111111111111111
incomplete name 3, col: 7008 row: []
col: 7009 similar rows:  [7009]
11111111111111111111
incomplete name 3, col: 7009 row: []
col: 7012 similar rows:  [7012]
11111111111111111111
hotelname2 [7012]
incomplete name 3, col: 7012 row: []
col: 7019 similar rows:  [7019]
11111111111111111111
incomplete name 3, col: 7019 row: []
col: 7020 similar rows:  [7020]
11111111111111111111
hotelname2 [7020]
incomplete name 3, col: 7020 row: []
col: 7022 similar rows:  [7022]
11111111111111111111
hotelname2 [7022]
incomplete name 3, col: 7022 row: [7022]
col: 7024 similar rows:  [7024]
11111111111111111111
hotelname2 [7024]
incomplete name 3, col: 7024 row: []
col: 7027 similar rows:  [7027]
11111111111111111111
hotelname2 [7027]
incomplete name 3, col: 7027 row: []
col: 7031 similar rows:  [7031]
11111111111111111111
hotelname2 [7031]
incomplete name 3, col: 7031 row: [7031]
col: 7032 similar rows:  [7032]
11111111111111111111
incomplete name 3, col: 7032 row: []
col: 7036 similar rows:  [7036]
11111111111111111111
incomplete name 3, col: 7036 row: []
col: 7038 similar rows:  [7038]
11111111111111111111
incomplete name 3, col: 7038 row: []
col: 7039 similar rows:  [7039]
11111111111111111111
incomplete name 3, col: 7039 row: []
col: 7042 similar rows:  [7042]
11111111111111111111
incomplete name 3, col: 7042 row: []
col: 7043 similar rows:  [7043]
11111111111111111111
incomplete name 3, col: 7043 row: []
col: 7045 similar rows:  [7045]
11111111111111111111
hotelname2 [7045]
incomplete name 3, col: 7045 row: []
col: 7046 similar rows:  [7046]
11111111111111111111
incomplete name 3, col: 7046 row: []
col: 7048 similar rows:  [7048]
11111111111111111111
incomplete name 3, col: 7048 row: []
col: 7049 similar rows:  [7049]
11111111111111111111
hotelname2 [7049]
incomplete name 3, col: 7049 row: [7049]
col: 7050 similar rows:  [7050]
11111111111111111111
hotelname2 [7050]
wrong name!!!!
incomplete name 3, col: 7050 row: [7050]
col: 7051 similar rows:  [7051]
11111111111111111111
incomplete name 3, col: 7051 row: []
col: 7052 similar rows:  [7052]
11111111111111111111
hotelname2 [7052]
incomplete name 3, col: 7052 row: [7052]
col: 7059 similar rows:  [7059]
11111111111111111111
hotelname2 [7059]
incomplete name 3, col: 7059 row: [7059]
col: 7060 similar rows:  [7060]
11111111111111111111
hotelname2 [7060]
incomplete name 3, col: 7060 row: [7060]
col: 7066 similar rows:  [7066]
11111111111111111111
hotelname2 [7066]
incomplete name 3, col: 7066 row: [7066]
col: 7073 similar rows:  [7073]
11111111111111111111
hotelname2 [7073]
incomplete name 3, col: 7073 row: [7073]
col: 7077 similar rows:  [7077]
11111111111111111111
incomplete name 3, col: 7077 row: []
col: 7084 similar rows:  [7084]
11111111111111111111
incomplete name 3, col: 7084 row: []
col: 7091 similar rows:  [7091]
11111111111111111111
incomplete name 3, col: 7091 row: []
col: 7098 similar rows:  [7098]
11111111111111111111
hotelname2 [7098]
incomplete name 3, col: 7098 row: [7098]
col: 7103 similar rows:  [7103, 7184]
incomplete name 3, col: 7103 row: []
col: 7104 similar rows:  [7104]
11111111111111111111
incomplete name 3, col: 7104 row: []
col: 7105 similar rows:  [7105]
11111111111111111111
incomplete name 3, col: 7105 row: []
col: 7109 similar rows:  [7109]
11111111111111111111
incomplete name 3, col: 7109 row: []
col: 7110 similar rows:  [7110]
11111111111111111111
hotelname2 [7110]
incomplete name 3, col: 7110 row: [7110]
col: 7112 similar rows:  [7112]
11111111111111111111
incomplete name 3, col: 7112 row: []
col: 7113 similar rows:  [7113]
11111111111111111111
incomplete name 3, col: 7113 row: []
col: 7120 similar rows:  [7120]
11111111111111111111
incomplete name 3, col: 7120 row: []
col: 7123 similar rows:  [7123]
11111111111111111111
incomplete name 3, col: 7123 row: []
col: 7124 similar rows:  [7124]
11111111111111111111
hotelname2 [7124]
incomplete name 3, col: 7124 row: []
col: 7127 similar rows:  [7127]
11111111111111111111
incomplete name 3, col: 7127 row: []
col: 7128 similar rows:  [7128]
11111111111111111111
incomplete name 3, col: 7128 row: []
col: 7131 similar rows:  [7131]
11111111111111111111
incomplete name 3, col: 7131 row: []
col: 7138 similar rows:  [7138]
11111111111111111111
incomplete name 3, col: 7138 row: []
col: 7146 similar rows:  [7146]
11111111111111111111
hotelname2 [7146]
incomplete name 3, col: 7146 row: [7146]
col: 7147 similar rows:  [7147]
11111111111111111111
incomplete name 3, col: 7147 row: []
col: 7149 similar rows:  [7149, 7217]
incomplete name 3, col: 7149 row: []
col: 7150 similar rows:  [7150]
11111111111111111111
incomplete name 3, col: 7150 row: []
col: 7152 similar rows:  [7152]
11111111111111111111
hotelname2 [7152]
wrong name!!!!
incomplete name 3, col: 7152 row: [7152]
col: 7153 similar rows:  [7153]
11111111111111111111
hotelname2 [7153]
incomplete name 3, col: 7153 row: [7153]
col: 7154 similar rows:  [7154]
11111111111111111111
hotelname2 [7154]
incomplete name 3, col: 7154 row: [7154]
col: 7163 similar rows:  [7163]
11111111111111111111
incomplete name 3, col: 7163 row: []
col: 7165 similar rows:  [7165]
11111111111111111111
incomplete name 3, col: 7165 row: []
col: 7169 similar rows:  [7169]
11111111111111111111
hotelname2 [7169]
incomplete name 3, col: 7169 row: []
col: 7170 similar rows:  [7170]
11111111111111111111
incomplete name 3, col: 7170 row: []
col: 7173 similar rows:  [7173]
11111111111111111111
incomplete name 3, col: 7173 row: []

col: 7175 similar rows:  [7175]
11111111111111111111
incomplete name 3, col: 7175 row: []
col: 7177 similar rows:  [7177]
11111111111111111111
incomplete name 3, col: 7177 row: []
col: 7181 similar rows:  [7181]
11111111111111111111
incomplete name 3, col: 7181 row: []
col: 7183 similar rows:  [7183]
11111111111111111111
incomplete name 3, col: 7183 row: []
col: 7188 similar rows:  [7188]
11111111111111111111
incomplete name 3, col: 7188 row: []
col: 7191 similar rows:  [7191]
11111111111111111111
incomplete name 3, col: 7191 row: []
col: 7192 similar rows:  [7192]
11111111111111111111
hotelname2 [7192]
wrong name!!!!
incomplete name 3, col: 7192 row: [7192]
col: 7193 similar rows:  [7193]
11111111111111111111
incomplete name 3, col: 7193 row: []
col: 7194 similar rows:  [7194]
11111111111111111111
incomplete name 3, col: 7194 row: []
col: 7196 similar rows:  [7196, 7216]
incomplete name 3, col: 7196 row: []
col: 7200 similar rows:  [7200]
11111111111111111111
incomplete name 3, col: 7200 row: []
col: 7201 similar rows:  [7201]
11111111111111111111
incomplete name 3, col: 7201 row: []
col: 7206 similar rows:  [7206]
11111111111111111111
incomplete name 3, col: 7206 row: []
col: 7208 similar rows:  [7208]
11111111111111111111
incomplete name 3, col: 7208 row: []
col: 7209 similar rows:  [7209]
11111111111111111111
incomplete name 3, col: 7209 row: []
col: 7213 similar rows:  [7213]
11111111111111111111
incomplete name 3, col: 7213 row: []
col: 7218 similar rows:  [7218]
11111111111111111111
incomplete name 3, col: 7218 row: []
col: 7224 similar rows:  [7224]
11111111111111111111
incomplete name 3, col: 7224 row: []
end
col: 7228 similar rows:  [7228, 7808, 9088, 9763]
incomplete name 3, col: 7228 row: []
col: 7229 similar rows:  [7229, 7399, 7406, 7426, 7454, 7455, 7528, 7672, 7675, 7716, 7720, 7834, 8100, 8122, 8151, 8213, 8215, 8445, 8922, 9881, 10208]
incomplete name 3, col: 7229 row: []
col: 7230 similar rows:  [7230]
11111111111111111111
incomplete name 3, col: 7230 row: []
col: 7231 similar rows:  [7231, 7548, 7786, 8126, 8131, 8210, 8939, 9345, 9442, 9516, 9534, 9752, 9918, 9921, 9930]
incomplete name 3, col: 7231 row: []
col: 7232 similar rows:  [7232]
11111111111111111111
incomplete name 3, col: 7232 row: []
col: 7233 similar rows:  [7233]
11111111111111111111
incomplete name 3, col: 7233 row: []
col: 7234 similar rows:  [7234, 7257, 8189]
incomplete name 3, col: 7234 row: []
col: 7235 similar rows:  [7235, 7573, 7850, 7915, 7963, 8078, 8120, 8415, 8547, 8638, 8671, 8674, 8931, 9000, 9071, 9427, 9780, 9917, 9946, 9997, 10070, 10076]
incomplete name 3, col: 7235 row: []
col: 7236 similar rows:  [7236]
11111111111111111111
incomplete name 3, col: 7236 row: []
col: 7237 similar rows:  [7237]
11111111111111111111
incomplete name 3, col: 7237 row: []
col: 7238 similar rows:  [7238, 8166]
incomplete name 3, col: 7238 row: []
col: 7239 similar rows:  [7239, 7336, 8375]
incomplete name 3, col: 7239 row: []
col: 7240 similar rows:  [7240]
11111111111111111111
incomplete name 3, col: 7240 row: []
col: 7241 similar rows:  [7241]
11111111111111111111
incomplete name 3, col: 7241 row: []
col: 7242 similar rows:  [7242, 7459, 9508]
incomplete name 3, col: 7242 row: []
col: 7243 similar rows:  [7243]
11111111111111111111
incomplete name 3, col: 7243 row: []
col: 7244 similar rows:  [7244]
11111111111111111111
incomplete name 3, col: 7244 row: []
col: 7245 similar rows:  [7245, 7987, 8027, 8497, 8930, 9062, 9166, 9245, 9563, 10171]
incomplete name 3, col: 7245 row: []
col: 7246 similar rows:  [7246]
11111111111111111111
hotelname2 [7246]
wrong name!!!!
incomplete name 3, col: 7246 row: [7246]
col: 7247 similar rows:  [7247]
11111111111111111111
incomplete name 3, col: 7247 row: []
col: 7248 similar rows:  [7248, 8773]
incomplete name 3, col: 7248 row: []
col: 7249 similar rows:  [7249]
11111111111111111111
incomplete name 3, col: 7249 row: []
col: 7250 similar rows:  [7250, 7308, 7309, 8116, 8655, 8986, 9542, 10149]
incomplete name 3, col: 7250 row: []
col: 7251 similar rows:  [7251, 7353, 7410, 7439, 7696, 8159, 9826, 10051, 10122, 10157]
incomplete name 3, col: 7251 row: []
col: 7252 similar rows:  [7252]
11111111111111111111
incomplete name 3, col: 7252 row: []
col: 7253 similar rows:  [7253]
11111111111111111111
incomplete name 3, col: 7253 row: []
col: 7254 similar rows:  [7254]
11111111111111111111
incomplete name 3, col: 7254 row: []
col: 7255 similar rows:  [7255, 9504]
incomplete name 3, col: 7255 row: []
col: 7256 similar rows:  [7256]
11111111111111111111
incomplete name 3, col: 7256 row: []
col: 7258 similar rows:  [7258, 7551, 7739, 8268, 8541, 8618, 8942]
incomplete name 3, col: 7258 row: []
col: 7259 similar rows:  [7259, 9645]
incomplete name 3, col: 7259 row: []
col: 7260 similar rows:  [7260, 7889, 7891, 8003, 8647, 9129, 9159, 9810, 9971]
incomplete name 3, col: 7260 row: []
col: 7261 similar rows:  [7261, 9310]
incomplete name 3, col: 7261 row: []
col: 7262 similar rows:  [7262, 8037, 8916]
incomplete name 3, col: 7262 row: []
col: 7263 similar rows:  [7263, 8007, 8309]
incomplete name 3, col: 7263 row: []
col: 7264 similar rows:  [7264]
11111111111111111111
incomplete name 3, col: 7264 row: []
col: 7265 similar rows:  [7265, 7642, 7950, 8495, 8599, 9263, 10154]
incomplete name 3, col: 7265 row: []
col: 7266 similar rows:  [7266]
11111111111111111111
incomplete name 3, col: 7266 row: []
col: 7267 similar rows:  [7267]
11111111111111111111
hotelname2 [7267]
incomplete name 3, col: 7267 row: [7267]
col: 7268 similar rows:  [7268, 8368, 8380, 8555, 8735, 8744, 8945, 9400, 9429, 9719]
incomplete name 3, col: 7268 row: []
col: 7269 similar rows:  [7269, 7998, 8800]
incomplete name 3, col: 7269 row: []
col: 7270 similar rows:  [7270]
11111111111111111111
incomplete name 3, col: 7270 row: []
col: 7271 similar rows:  [7271]
11111111111111111111
hotelname2 [7271]
incomplete name 3, col: 7271 row: [7271]
col: 7272 similar rows:  [7272, 9816, 10027]
incomplete name 3, col: 7272 row: []
col: 7273 similar rows:  [7273, 8517, 8934, 9107]
incomplete name 3, col: 7273 row: []
col: 7274 similar rows:  [7274, 9497, 10134]
incomplete name 3, col: 7274 row: []
col: 7275 similar rows:  [7275, 8511, 9034, 9836, 9844]
incomplete name 3, col: 7275 row: []
col: 7276 similar rows:  [7276]
11111111111111111111
hotelname2 [7276]
wrong name!!!!
incomplete name 3, col: 7276 row: [7276]
col: 7277 similar rows:  [7277]
11111111111111111111
incomplete name 3, col: 7277 row: []
col: 7278 similar rows:  [7278, 7298, 7872, 8844, 8877, 10162, 10169]
incomplete name 3, col: 7278 row: []
col: 7279 similar rows:  [7279, 7419, 7482, 7566, 7764, 7947, 8269, 8498, 8567, 8650, 8651, 8719, 8943, 8987, 9117, 9138, 9236, 9344, 9540]
incomplete name 3, col: 7279 row: []
col: 7280 similar rows:  [7280, 8814, 9187]
incomplete name 3, col: 7280 row: []
col: 7281 similar rows:  [7281]
11111111111111111111
incomplete name 3, col: 7281 row: []
col: 7282 similar rows:  [7282, 7447, 7674, 8134, 8388, 8516, 8795, 9507, 9879, 10111, 10143]
incomplete name 3, col: 7282 row: []
col: 7283 similar rows:  [7283, 7844, 8036, 8058, 9185, 10078]
incomplete name 3, col: 7283 row: []
col: 7284 similar rows:  [7284, 9950]
incomplete name 3, col: 7284 row: []
col: 7285 similar rows:  [7285]
11111111111111111111
incomplete name 3, col: 7285 row: []
col: 7286 similar rows:  [7286, 7311, 8433, 9814, 10016]
incomplete name 3, col: 7286 row: []
col: 7287 similar rows:  [7287, 7431, 7448, 7507, 7690, 7749, 7827, 8407, 8452, 8565, 8690, 8927, 9393, 9501, 9787, 9873, 10012, 10055, 10103, 10113, 10176]
incomplete name 3, col: 7287 row: []
col: 7288 similar rows:  [7288, 8273, 9134, 9317, 9611, 10021, 10052]
incomplete name 3, col: 7288 row: []
col: 7289 similar rows:  [7289, 7712, 7754, 7857, 8267, 8283, 8455, 8473, 8761, 8860, 8935, 8941, 9588, 9961, 10034, 10191]
incomplete name 3, col: 7289 row: []
col: 7290 similar rows:  [7290, 7293, 7302, 7367, 7391, 7768, 7775, 7782, 7789, 8723, 8883, 8976, 8983, 8994, 9002, 9051, 9487, 9574, 9792, 9793, 9806, 10146, 10188]
incomplete name 3, col: 7290 row: []
col: 7291 similar rows:  [7291, 7896, 8026, 8721, 8905]
incomplete name 3, col: 7291 row: []
col: 7292 similar rows:  [7292, 7881, 7890, 8016, 8770, 8900, 8915, 8969, 8970, 8979, 9086, 9201, 9498, 9595, 9773, 9781, 9852]
incomplete name 3, col: 7292 row: []
col: 7294 similar rows:  [7294, 7385, 7972, 9022, 9320]
incomplete name 3, col: 7294 row: []
col: 7295 similar rows:  [7295, 7324, 8033, 9335, 9363, 9854]
incomplete name 3, col: 7295 row: []
col: 7296 similar rows:  [7296, 8499]
incomplete name 3, col: 7296 row: []
col: 7297 similar rows:  [7297]
11111111111111111111
incomplete name 3, col: 7297 row: []
col: 7299 similar rows:  [7299]
11111111111111111111
incomplete name 3, col: 7299 row: []
col: 7300 similar rows:  [7300, 8997, 8999]
incomplete name 3, col: 7300 row: []

col: 7301 similar rows:  [7301]
11111111111111111111
incomplete name 3, col: 7301 row: []
col: 7303 similar rows:  [7303, 9192]
incomplete name 3, col: 7303 row: []
col: 7304 similar rows:  [7304, 7317, 7832]
incomplete name 3, col: 7304 row: []
col: 7305 similar rows:  [7305, 8291, 8695]
incomplete name 3, col: 7305 row: []
col: 7306 similar rows:  [7306]
11111111111111111111
incomplete name 3, col: 7306 row: []
col: 7307 similar rows:  [7307, 7497]
incomplete name 3, col: 7307 row: []
col: 7310 similar rows:  [7310, 7881, 7890, 8016, 8770, 8900, 8915, 8969, 8970, 8979, 9086, 9214, 9498, 9595, 9773, 9781, 9852]
incomplete name 3, col: 7310 row: []
col: 7312 similar rows:  [7312, 8797, 8958, 9079, 9762, 9900, 9907, 10202]
incomplete name 3, col: 7312 row: []
col: 7313 similar rows:  [7313, 9153, 9597, 9851]
incomplete name 3, col: 7313 row: []
col: 7314 similar rows:  [7314, 8235, 8238, 8474, 9769]
incomplete name 3, col: 7314 row: []
col: 7315 similar rows:  [7315, 7723, 7870, 8132, 8168, 8512, 8717, 8820, 8831, 8834, 8870, 8880, 9203, 9240, 9728, 10193]
incomplete name 3, col: 7315 row: []
col: 7316 similar rows:  [7316]
11111111111111111111
hotelname2 [7316]
wrong name!!!!
incomplete name 3, col: 7316 row: [7316]
col: 7318 similar rows:  [7318]
11111111111111111111
hotelname2 [7318]
incomplete name 3, col: 7318 row: []
col: 7319 similar rows:  [7319, 7580, 7792, 8542, 8708, 8737, 9253]
incomplete name 3, col: 7319 row: []
col: 7320 similar rows:  [7320]
11111111111111111111
incomplete name 3, col: 7320 row: []
col: 7321 similar rows:  [7321, 7617, 8324, 8351, 8467, 9642]
incomplete name 3, col: 7321 row: []
col: 7322 similar rows:  [7322]
11111111111111111111
incomplete name 3, col: 7322 row: []
col: 7323 similar rows:  [7323, 8195, 8350, 8767, 8811, 9242, 9252, 9416, 9494, 9495]
incomplete name 3, col: 7323 row: []
col: 7325 similar rows:  [7325, 8562, 8902, 9040]
incomplete name 3, col: 7325 row: []
col: 7326 similar rows:  [7326]
11111111111111111111
incomplete name 3, col: 7326 row: []
col: 7327 similar rows:  [7327, 7493, 8193, 8275, 8789, 9295, 9307, 9328, 9329, 9334, 9359, 9389, 9410, 9422, 9433, 9884]
incomplete name 3, col: 7327 row: []
col: 7328 similar rows:  [7328, 8780, 9054, 9659, 9705]
incomplete name 3, col: 7328 row: []
col: 7329 similar rows:  [7329, 8031, 8133, 9142, 9169]
incomplete name 3, col: 7329 row: []
col: 7330 similar rows:  [7330]
11111111111111111111
incomplete name 3, col: 7330 row: []
col: 7331 similar rows:  [7331, 7916, 9172, 9294, 9308, 9321, 9322, 9348, 9382, 9486, 9741, 9758, 9778, 9809]
incomplete name 3, col: 7331 row: []
col: 7332 similar rows:  [7332, 7638, 8062, 9145]
incomplete name 3, col: 7332 row: []
col: 7333 similar rows:  [7333, 7766, 7881, 7890, 8016, 8770, 8900, 8915, 8969, 8970, 8979, 9023, 9086, 9214, 9498, 9595, 9773, 9781, 9852]
incomplete name 3, col: 7333 row: []
col: 7334 similar rows:  [7334]
11111111111111111111
incomplete name 3, col: 7334 row: []
col: 7335 similar rows:  [7335]
11111111111111111111
incomplete name 3, col: 7335 row: []
col: 7337 similar rows:  [7337, 7683, 7776, 7853, 7952, 7955, 8025, 8194, 8361, 8810, 8815, 8949, 9078, 9090, 9421, 9484, 9742, 9947]
incomplete name 3, col: 7337 row: []
col: 7338 similar rows:  [7338]
11111111111111111111
incomplete name 3, col: 7338 row: []
col: 7339 similar rows:  [7339]
11111111111111111111
incomplete name 3, col: 7339 row: []
col: 7340 similar rows:  [7340, 7518, 7718, 8160, 10049]
incomplete name 3, col: 7340 row: []
col: 7341 similar rows:  [7341]
11111111111111111111
hotelname2 [7341]
incomplete name 3, col: 7341 row: [7341]
col: 7342 similar rows:  [7342, 8903, 9249, 9254]
incomplete name 3, col: 7342 row: []
col: 7343 similar rows:  [7343, 8177, 8411]
incomplete name 3, col: 7343 row: []
col: 7344 similar rows:  [7344]
11111111111111111111
incomplete name 3, col: 7344 row: []
col: 7345 similar rows:  [7345, 7350, 7574, 7663, 7682, 7974, 8301, 9991]
incomplete name 3, col: 7345 row: []
col: 7346 similar rows:  [7346, 8672]
incomplete name 3, col: 7346 row: []
col: 7347 similar rows:  [7347, 8012, 8021, 8886]
incomplete name 3, col: 7347 row: []
col: 7348 similar rows:  [7348, 9817]
incomplete name 3, col: 7348 row: []
col: 7349 similar rows:  [7349, 8430, 10119]
incomplete name 3, col: 7349 row: []
col: 7351 similar rows:  [7351]
11111111111111111111
incomplete name 3, col: 7351 row: []
col: 7352 similar rows:  [7352]
11111111111111111111
incomplete name 3, col: 7352 row: []
col: 7354 similar rows:  [7354, 7418, 7441, 8127, 8218, 8661, 9197, 9502, 9517, 9827]
incomplete name 3, col: 7354 row: []
col: 7355 similar rows:  [7355, 9020, 9042, 9913]
incomplete name 3, col: 7355 row: []
col: 7356 similar rows:  [7356, 7744, 8423, 8694]
incomplete name 3, col: 7356 row: []
col: 7357 similar rows:  [7357]
11111111111111111111
incomplete name 3, col: 7357 row: []
col: 7358 similar rows:  [7358]
11111111111111111111
incomplete name 3, col: 7358 row: []
col: 7359 similar rows:  [7359, 7377, 7793, 7802, 7836, 8143, 8464, 8682, 9306, 9842, 10023, 10067]
incomplete name 3, col: 7359 row: []
col: 7360 similar rows:  [7360, 7827, 8452, 10176]
incomplete name 3, col: 7360 row: []
col: 7361 similar rows:  [7361]
11111111111111111111
incomplete name 3, col: 7361 row: []
col: 7362 similar rows:  [7362]
11111111111111111111
incomplete name 3, col: 7362 row: []
col: 7363 similar rows:  [7363, 7561, 8453, 8645, 8722, 9418, 9493, 9550, 9872, 10063]
incomplete name 3, col: 7363 row: []
col: 7364 similar rows:  [7364, 8846]
incomplete name 3, col: 7364 row: []
col: 7365 similar rows:  [7365, 7657, 8799, 9417]
incomplete name 3, col: 7365 row: []
col: 7366 similar rows:  [7366, 10095]
incomplete name 3, col: 7366 row: []
col: 7368 similar rows:  [7368, 7416, 7605, 7673, 7742, 7753, 7779, 7981, 8111, 8197, 8290, 8488, 8589, 8696, 8779, 8825, 9182, 9323, 9513, 9576, 9606, 9864, 10074, 10132]
incomplete name 3, col: 7368 row: []
col: 7369 similar rows:  [7369, 8198]
incomplete name 3, col: 7369 row: []
col: 7370 similar rows:  [7370]
11111111111111111111
incomplete name 3, col: 7370 row: []
col: 7371 similar rows:  [7371, 7627, 8182, 8207, 8247, 9523, 9536]
incomplete name 3, col: 7371 row: []
col: 7372 similar rows:  [7372, 7596, 7608, 8559, 9288]
incomplete name 3, col: 7372 row: []
col: 7373 similar rows:  [7373]
11111111111111111111
incomplete name 3, col: 7373 row: []
col: 7374 similar rows:  [7374, 7523, 7534, 7582, 7707, 7790, 7803, 9028, 9357, 9496, 9596, 9786, 10118]
incomplete name 3, col: 7374 row: []
col: 7375 similar rows:  [7375, 8526]
incomplete name 3, col: 7375 row: []
col: 7376 similar rows:  [7376]
11111111111111111111
incomplete name 3, col: 7376 row: []
col: 7378 similar rows:  [7378]
11111111111111111111
incomplete name 3, col: 7378 row: []
col: 7379 similar rows:  [7379]
11111111111111111111
incomplete name 3, col: 7379 row: []
col: 7380 similar rows:  [7380, 7442, 7679]
incomplete name 3, col: 7380 row: []
col: 7381 similar rows:  [7381, 9089]
incomplete name 3, col: 7381 row: []
col: 7382 similar rows:  [7382, 7540, 7800, 8588, 9666]
incomplete name 3, col: 7382 row: []
col: 7383 similar rows:  [7383, 8216, 10152]
incomplete name 3, col: 7383 row: []
col: 7384 similar rows:  [7384]
11111111111111111111
incomplete name 3, col: 7384 row: []
col: 7386 similar rows:  [7386]
11111111111111111111
hotelname2 [7386]
incomplete name 3, col: 7386 row: [7386]
col: 7387 similar rows:  [7387, 8060, 8933, 9405, 9853]
incomplete name 3, col: 7387 row: []
col: 7388 similar rows:  [7388, 7681, 7979, 8095, 8261, 9084, 9104]
incomplete name 3, col: 7388 row: []
col: 7389 similar rows:  [7389]
11111111111111111111
hotelname2 [7389]
incomplete name 3, col: 7389 row: []
col: 7390 similar rows:  [7390]
11111111111111111111
hotelname2 [7390]
incomplete name 3, col: 7390 row: []
col: 7392 similar rows:  [7392]
11111111111111111111
incomplete name 3, col: 7392 row: []
col: 7393 similar rows:  [7393]
11111111111111111111
incomplete name 3, col: 7393 row: []
col: 7394 similar rows:  [7394, 9430]
incomplete name 3, col: 7394 row: []
col: 7395 similar rows:  [7395]
11111111111111111111
incomplete name 3, col: 7395 row: []
col: 7396 similar rows:  [7396, 7397, 7444, 7463, 7533, 7713, 7757, 8098, 8176, 8204, 8337, 8745, 9478, 9760, 10010, 10025, 10040, 10107, 10205]
incomplete name 3, col: 7396 row: []

col: 7398 similar rows:  [7398, 9069, 9368]
incomplete name 3, col: 7398 row: []
col: 7400 similar rows:  [7400, 9790]
incomplete name 3, col: 7400 row: []
col: 7401 similar rows:  [7401, 8390]
incomplete name 3, col: 7401 row: []
col: 7402 similar rows:  [7402]
11111111111111111111
incomplete name 3, col: 7402 row: []
col: 7403 similar rows:  [7403, 9733]
incomplete name 3, col: 7403 row: []
col: 7404 similar rows:  [7404]
11111111111111111111
hotelname2 [7404]
incomplete name 3, col: 7404 row: [7404]
col: 7405 similar rows:  [7405]
11111111111111111111
hotelname2 [7405]
incomplete name 3, col: 7405 row: []
col: 7407 similar rows:  [7407, 7901, 7958, 10081, 10092]
incomplete name 3, col: 7407 row: []
col: 7408 similar rows:  [7408, 8316, 8859, 9785, 9920]
incomplete name 3, col: 7408 row: []
col: 7409 similar rows:  [7409, 7685, 7686, 7879, 8278, 9757, 9866]
incomplete name 3, col: 7409 row: []
col: 7411 similar rows:  [7411, 9115]
incomplete name 3, col: 7411 row: []
col: 7412 similar rows:  [7412]
11111111111111111111
incomplete name 3, col: 7412 row: []
col: 7413 similar rows:  [7413]
11111111111111111111
hotelname2 [7413]
incomplete name 3, col: 7413 row: [7413]
col: 7414 similar rows:  [7414]
11111111111111111111
incomplete name 3, col: 7414 row: []
col: 7415 similar rows:  [7415, 10011]
incomplete name 3, col: 7415 row: []
col: 7417 similar rows:  [7417, 7484, 7851, 9301, 10007, 10104, 10145]
incomplete name 3, col: 7417 row: []
col: 7420 similar rows:  [7420, 7432]
incomplete name 3, col: 7420 row: []
col: 7421 similar rows:  [7421, 7451, 9468]
incomplete name 3, col: 7421 row: []
col: 7422 similar rows:  [7422, 7658, 8108]
incomplete name 3, col: 7422 row: []
col: 7423 similar rows:  [7423, 8294, 8730, 10152]
incomplete name 3, col: 7423 row: []
col: 7424 similar rows:  [7424]
11111111111111111111
incomplete name 3, col: 7424 row: []
col: 7425 similar rows:  [7425, 7667, 7809, 8115, 8307, 9914, 10108, 10203]
hotelname2 [7809, 9914]
hotelname2 [7809, 9914]
incomplete name 3, col: 7425 row: [7809, 9914]
col: 7427 similar rows:  [7427, 7429, 7469, 7708, 8950]
incomplete name 3, col: 7427 row: []
col: 7428 similar rows:  [7428]
11111111111111111111
incomplete name 3, col: 7428 row: []
col: 7430 similar rows:  [7430, 7549, 7555, 7886, 8034, 8920, 8965, 9063, 9463, 10039, 10131]
incomplete name 3, col: 7430 row: []
col: 7433 similar rows:  [7433, 7659, 10045]
incomplete name 3, col: 7433 row: []
col: 7434 similar rows:  [7434, 7449, 7499, 8104, 8490, 10014]
incomplete name 3, col: 7434 row: []
col: 7435 similar rows:  [7435]
11111111111111111111
incomplete name 3, col: 7435 row: []
col: 7436 similar rows:  [7436]
11111111111111111111
incomplete name 3, col: 7436 row: []
col: 7437 similar rows:  [7437]
11111111111111111111
incomplete name 3, col: 7437 row: []
col: 7438 similar rows:  [7438, 8416]
incomplete name 3, col: 7438 row: []
col: 7440 similar rows:  [7440, 7443, 7481, 8861, 9598, 10098]
incomplete name 3, col: 7440 row: []
col: 7445 similar rows:  [7445]
11111111111111111111
incomplete name 3, col: 7445 row: []
col: 7446 similar rows:  [7446, 7911, 8946]
incomplete name 3, col: 7446 row: []
col: 7450 similar rows:  [7450]
11111111111111111111
incomplete name 3, col: 7450 row: []
col: 7452 similar rows:  [7452, 8296, 9156, 9476]
incomplete name 3, col: 7452 row: []
col: 7453 similar rows:  [7453, 7479]
incomplete name 3, col: 7453 row: []
col: 7456 similar rows:  [7456, 7520, 7705, 9010, 9339, 9964]
incomplete name 3, col: 7456 row: []
col: 7457 similar rows:  [7457, 8676, 10073, 10121]
incomplete name 3, col: 7457 row: []
col: 7458 similar rows:  [7458]
11111111111111111111
hotelname2 [7458]
wrong name!!!!
incomplete name 3, col: 7458 row: [7458]
col: 7460 similar rows:  [7460]
11111111111111111111
incomplete name 3, col: 7460 row: []
col: 7461 similar rows:  [7461, 8015, 8129]
incomplete name 3, col: 7461 row: []
col: 7462 similar rows:  [7462]
11111111111111111111
hotelname2 [7462]
wrong name!!!!
incomplete name 3, col: 7462 row: [7462]
col: 7464 similar rows:  [7464]
11111111111111111111
incomplete name 3, col: 7464 row: []
col: 7465 similar rows:  [7465]
11111111111111111111
incomplete name 3, col: 7465 row: []
col: 7466 similar rows:  [7466]
11111111111111111111
incomplete name 3, col: 7466 row: []
col: 7467 similar rows:  [7467, 9183, 9527]
incomplete name 3, col: 7467 row: []
col: 7468 similar rows:  [7468, 7621, 7841, 8173, 9407]
incomplete name 3, col: 7468 row: []
col: 7470 similar rows:  [7470, 8128, 9025]
incomplete name 3, col: 7470 row: []
col: 7471 similar rows:  [7471, 7994]
incomplete name 3, col: 7471 row: []
col: 7472 similar rows:  [7472]
11111111111111111111
incomplete name 3, col: 7472 row: []
col: 7473 similar rows:  [7473, 7486, 7656, 7758, 7781, 7795, 7806, 7854, 7876, 7907, 8274, 8394, 8481, 8529, 9150, 9882, 10097, 10124, 10151]
incomplete name 3, col: 7473 row: []
col: 7474 similar rows:  [7474]
11111111111111111111
incomplete name 3, col: 7474 row: []
col: 7475 similar rows:  [7475, 9144]
incomplete name 3, col: 7475 row: []
col: 7476 similar rows:  [7476, 7697, 8179, 8539, 8924, 8998, 9004, 9608, 9623, 10109]
incomplete name 3, col: 7476 row: []
col: 7477 similar rows:  [7477]
11111111111111111111
incomplete name 3, col: 7477 row: []
col: 7478 similar rows:  [7478]
11111111111111111111
incomplete name 3, col: 7478 row: []
col: 7480 similar rows:  [7480]
11111111111111111111
incomplete name 3, col: 7480 row: []
col: 7483 similar rows:  [7483, 9524, 10053, 10084]
incomplete name 3, col: 7483 row: []
col: 7485 similar rows:  [7485, 7677, 7759, 7939, 8097, 8099, 8318, 8399, 8448, 8663, 8753, 8824, 9053, 9627, 9751, 10002, 10054, 10086, 10190, 10195, 10201]
incomplete name 3, col: 7485 row: []
col: 7487 similar rows:  [7487]
11111111111111111111
hotelname2 [7487]
incomplete name 3, col: 7487 row: [7487]
col: 7488 similar rows:  [7488]
11111111111111111111
incomplete name 3, col: 7488 row: []
col: 7489 similar rows:  [7489, 7609, 7676, 7710, 7813, 7960, 7993, 8114, 8224, 8284, 8493, 8628, 8646, 8653, 8664, 9067, 9072, 9191, 9587, 9612, 9767, 9824, 9941, 9949, 10115]
incomplete name 3, col: 7489 row: []
col: 7490 similar rows:  [7490]
11111111111111111111
hotelname2 [7490]
incomplete name 3, col: 7490 row: [7490]
col: 7491 similar rows:  [7491, 9139, 9889]
incomplete name 3, col: 7491 row: []
col: 7492 similar rows:  [7492]
11111111111111111111
incomplete name 3, col: 7492 row: []
col: 7494 similar rows:  [7494]
11111111111111111111
incomplete name 3, col: 7494 row: []
col: 7495 similar rows:  [7495]
11111111111111111111
hotelname2 [7495]
incomplete name 3, col: 7495 row: [7495]
col: 7496 similar rows:  [7496]
11111111111111111111
hotelname2 [7496]
incomplete name 3, col: 7496 row: [7496]
col: 7498 similar rows:  [7498]
11111111111111111111
incomplete name 3, col: 7498 row: []
col: 7500 similar rows:  [7500, 7730, 8982, 9622]
incomplete name 3, col: 7500 row: []
col: 7501 similar rows:  [7501, 9855]
incomplete name 3, col: 7501 row: []
col: 7502 similar rows:  [7502, 8583, 10031]
incomplete name 3, col: 7502 row: []
col: 7503 similar rows:  [7503, 9080]
incomplete name 3, col: 7503 row: []
col: 7504 similar rows:  [7504]
11111111111111111111
incomplete name 3, col: 7504 row: []
col: 7505 similar rows:  [7505]
11111111111111111111
hotelname2 [7505]
incomplete name 3, col: 7505 row: [7505]
col: 7506 similar rows:  [7506]
11111111111111111111
incomplete name 3, col: 7506 row: []
col: 7508 similar rows:  [7508]
11111111111111111111
incomplete name 3, col: 7508 row: []
col: 7509 similar rows:  [7509]
11111111111111111111
incomplete name 3, col: 7509 row: []
col: 7510 similar rows:  [7510]
11111111111111111111
incomplete name 3, col: 7510 row: []
col: 7511 similar rows:  [7511]
11111111111111111111
incomplete name 3, col: 7511 row: []
col: 7512 similar rows:  [7512]
11111111111111111111
incomplete name 3, col: 7512 row: []
col: 7513 similar rows:  [7513]
11111111111111111111
incomplete name 3, col: 7513 row: []
col: 7514 similar rows:  [7514]
11111111111111111111
incomplete name 3, col: 7514 row: []
col: 7515 similar rows:  [7515]
11111111111111111111
incomplete name 3, col: 7515 row: []
col: 7516 similar rows:  [7516, 8989, 9511, 9969]
incomplete name 3, col: 7516 row: []
col: 7517 similar rows:  [7517, 7571, 7644, 7826, 8199, 8550, 8921, 8971, 9066, 9319, 9589, 9607, 9625, 9639, 10042, 10102]
hotelname2 [10042]
incomplete name 3, col: 7517 row: [10042]

col: 7519 similar rows:  [7519]
11111111111111111111
incomplete name 3, col: 7519 row: []
col: 7521 similar rows:  [7521]
11111111111111111111
incomplete name 3, col: 7521 row: []
col: 7522 similar rows:  [7522, 9782, 9904, 9967]
incomplete name 3, col: 7522 row: []
col: 7524 similar rows:  [7524]
11111111111111111111
incomplete name 3, col: 7524 row: []
col: 7525 similar rows:  [7525]
11111111111111111111
hotelname2 [7525]
wrong name!!!!
incomplete name 3, col: 7525 row: [7525]
col: 7526 similar rows:  [7526]
11111111111111111111
incomplete name 3, col: 7526 row: []
col: 7527 similar rows:  [7527, 9131]
incomplete name 3, col: 7527 row: []
col: 7529 similar rows:  [7529]
11111111111111111111
incomplete name 3, col: 7529 row: []
col: 7530 similar rows:  [7530]
11111111111111111111
hotelname2 [7530]
incomplete name 3, col: 7530 row: [7530]
col: 7531 similar rows:  [7531, 7586, 7759, 7903, 7939, 8318, 8753, 10190, 10201]
incomplete name 3, col: 7531 row: []
col: 7532 similar rows:  [7532]
11111111111111111111
incomplete name 3, col: 7532 row: []
col: 7535 similar rows:  [7535, 7835, 8418, 8821, 9223, 9250]
incomplete name 3, col: 7535 row: []
col: 7536 similar rows:  [7536]
11111111111111111111
hotelname2 [7536]
incomplete name 3, col: 7536 row: []
col: 7537 similar rows:  [7537, 8752, 9225]
incomplete name 3, col: 7537 row: []
col: 7538 similar rows:  [7538]
11111111111111111111
incomplete name 3, col: 7538 row: []
col: 7539 similar rows:  [7539]
11111111111111111111
incomplete name 3, col: 7539 row: []
col: 7541 similar rows:  [7541, 9579]
incomplete name 3, col: 7541 row: []
col: 7542 similar rows:  [7542]
11111111111111111111
hotelname2 [7542]
incomplete name 3, col: 7542 row: [7542]
col: 7543 similar rows:  [7543, 8594]
incomplete name 3, col: 7543 row: []
col: 7544 similar rows:  [7544]
11111111111111111111
hotelname2 [7544]
incomplete name 3, col: 7544 row: []
col: 7545 similar rows:  [7545]
11111111111111111111
hotelname2 [7545]
incomplete name 3, col: 7545 row: [7545]
col: 7546 similar rows:  [7546, 7838, 8174, 9178, 10159]
incomplete name 3, col: 7546 row: []
col: 7547 similar rows:  [7547]
11111111111111111111
hotelname2 [7547]
incomplete name 3, col: 7547 row: [7547]
col: 7550 similar rows:  [7550, 10001]
incomplete name 3, col: 7550 row: []
col: 7552 similar rows:  [7552]
11111111111111111111
incomplete name 3, col: 7552 row: []
col: 7553 similar rows:  [7553, 7801, 7909]
incomplete name 3, col: 7553 row: []
col: 7554 similar rows:  [7554]
11111111111111111111
incomplete name 3, col: 7554 row: []
col: 7556 similar rows:  [7556, 7559, 8106, 8448, 8514, 9053, 10195]
incomplete name 3, col: 7556 row: []
col: 7557 similar rows:  [7557]
11111111111111111111
hotelname2 [7557]
incomplete name 3, col: 7557 row: []
col: 7558 similar rows:  [7558, 7897, 8142, 8461, 8470, 8758]
incomplete name 3, col: 7558 row: []
col: 7560 similar rows:  [7560]
11111111111111111111
incomplete name 3, col: 7560 row: []
col: 7562 similar rows:  [7562, 7585, 7691, 7740, 7780, 8042, 8220, 8326, 8667, 8855, 9026, 9770, 9776, 9868, 10032, 10123, 10128, 10175, 10179, 10197]
incomplete name 3, col: 7562 row: []
col: 7563 similar rows:  [7563, 8395, 9160, 9261, 9942]
incomplete name 3, col: 7563 row: []
col: 7564 similar rows:  [7564, 7615, 7914, 8162, 9260, 9445]
incomplete name 3, col: 7564 row: []
col: 7565 similar rows:  [7565]
11111111111111111111
incomplete name 3, col: 7565 row: []
col: 7567 similar rows:  [7567]
11111111111111111111
incomplete name 3, col: 7567 row: []
col: 7568 similar rows:  [7568]
11111111111111111111
incomplete name 3, col: 7568 row: []
col: 7569 similar rows:  [7569, 7604, 7860]
incomplete name 3, col: 7569 row: []
col: 7570 similar rows:  [7570]
11111111111111111111
incomplete name 3, col: 7570 row: []
col: 7572 similar rows:  [7572, 8332]
incomplete name 3, col: 7572 row: []
col: 7575 similar rows:  [7575]
11111111111111111111
hotelname2 [7575]
incomplete name 3, col: 7575 row: [7575]
col: 7576 similar rows:  [7576, 8116, 8655, 8986, 9542, 10149]
incomplete name 3, col: 7576 row: []
col: 7577 similar rows:  [7577]
11111111111111111111
hotelname2 [7577]
incomplete name 3, col: 7577 row: [7577]
col: 7578 similar rows:  [7578, 8006, 8076]
incomplete name 3, col: 7578 row: []
col: 7579 similar rows:  [7579, 9992]
incomplete name 3, col: 7579 row: []
col: 7581 similar rows:  [7581]
11111111111111111111
incomplete name 3, col: 7581 row: []
col: 7583 similar rows:  [7583]
11111111111111111111
incomplete name 3, col: 7583 row: []
col: 7584 similar rows:  [7584, 8666, 9251]
incomplete name 3, col: 7584 row: []
col: 7587 similar rows:  [7587]
11111111111111111111
incomplete name 3, col: 7587 row: []
col: 7588 similar rows:  [7588, 9684]
incomplete name 3, col: 7588 row: []
col: 7589 similar rows:  [7589]
11111111111111111111
incomplete name 3, col: 7589 row: []
col: 7590 similar rows:  [7590, 9878]
incomplete name 3, col: 7590 row: []
col: 7591 similar rows:  [7591]
11111111111111111111
incomplete name 3, col: 7591 row: []
col: 7592 similar rows:  [7592]
11111111111111111111
incomplete name 3, col: 7592 row: []
col: 7593 similar rows:  [7593]
11111111111111111111
incomplete name 3, col: 7593 row: []
col: 7594 similar rows:  [7594]
11111111111111111111
incomplete name 3, col: 7594 row: []
col: 7595 similar rows:  [7595]
11111111111111111111
incomplete name 3, col: 7595 row: []
col: 7597 similar rows:  [7597, 7770, 8008, 8019, 8032, 8372, 8817, 8853, 8856, 8951, 9164, 9743, 9764]
incomplete name 3, col: 7597 row: []
col: 7598 similar rows:  [7598]
11111111111111111111
incomplete name 3, col: 7598 row: []
col: 7599 similar rows:  [7599]
11111111111111111111
incomplete name 3, col: 7599 row: []
col: 7600 similar rows:  [7600, 7735, 8018, 9111, 9112, 9113, 9224]
incomplete name 3, col: 7600 row: []
col: 7601 similar rows:  [7601, 7666, 8265, 8391, 8688, 9106, 10005]
incomplete name 3, col: 7601 row: []
col: 7602 similar rows:  [7602, 8363, 8546, 9544]
incomplete name 3, col: 7602 row: []
col: 7603 similar rows:  [7603, 7644, 7826, 8199, 8550, 8893, 8921, 8971, 9003, 9066, 9319, 9589, 9607, 9625, 9639, 10102]
incomplete name 3, col: 7603 row: []
col: 7606 similar rows:  [7606]
11111111111111111111
incomplete name 3, col: 7606 row: []
col: 7607 similar rows:  [7607, 8340]
incomplete name 3, col: 7607 row: []
col: 7610 similar rows:  [7610, 8652, 8775, 9343, 9355, 9749]
incomplete name 3, col: 7610 row: []
col: 7611 similar rows:  [7611]
11111111111111111111
incomplete name 3, col: 7611 row: []
col: 7612 similar rows:  [7612]
11111111111111111111
incomplete name 3, col: 7612 row: []
col: 7613 similar rows:  [7613]
11111111111111111111
incomplete name 3, col: 7613 row: []
col: 7614 similar rows:  [7614]
11111111111111111111
hotelname2 [7614]
incomplete name 3, col: 7614 row: [7614]
col: 7616 similar rows:  [7616]
11111111111111111111
incomplete name 3, col: 7616 row: []
col: 7618 similar rows:  [7618]
11111111111111111111
incomplete name 3, col: 7618 row: []
col: 7619 similar rows:  [7619]
11111111111111111111
incomplete name 3, col: 7619 row: []
col: 7620 similar rows:  [7620]
11111111111111111111
incomplete name 3, col: 7620 row: []
col: 7622 similar rows:  [7622]
11111111111111111111
incomplete name 3, col: 7622 row: []
col: 7623 similar rows:  [7623]
11111111111111111111
incomplete name 3, col: 7623 row: []
col: 7624 similar rows:  [7624, 8502, 8596, 9454]
incomplete name 3, col: 7624 row: []
col: 7625 similar rows:  [7625, 7668, 8535, 9857]
incomplete name 3, col: 7625 row: []
col: 7626 similar rows:  [7626, 7847]
incomplete name 3, col: 7626 row: []
col: 7628 similar rows:  [7628, 8244, 8570, 8571, 8581, 8584, 9293]
incomplete name 3, col: 7628 row: []
col: 7629 similar rows:  [7629]
11111111111111111111
incomplete name 3, col: 7629 row: []
col: 7630 similar rows:  [7630, 7714, 8469, 8519, 9772, 9885]
incomplete name 3, col: 7630 row: []
col: 7631 similar rows:  [7631]
11111111111111111111
incomplete name 3, col: 7631 row: []
col: 7632 similar rows:  [7632, 9231]
incomplete name 3, col: 7632 row: []
col: 7633 similar rows:  [7633, 8460]
incomplete name 3, col: 7633 row: []
col: 7634 similar rows:  [7634]
11111111111111111111
incomplete name 3, col: 7634 row: []
col: 7635 similar rows:  [7635, 7645]
incomplete name 3, col: 7635 row: []
col: 7636 similar rows:  [7636]
11111111111111111111
incomplete name 3, col: 7636 row: []
col: 7637 similar rows:  [7637, 7852, 7855, 7932, 8732, 8867, 8901, 9701, 9715, 9734, 10192, 10214, 10223]
incomplete name 3, col: 7637 row: []
col: 7639 similar rows:  [7639, 7726, 7762, 7769, 7814, 8001, 8047, 8869, 9326, 9441, 9451, 10207]
incomplete name 3, col: 7639 row: []

col: 7640 similar rows:  [7640]
11111111111111111111
incomplete name 3, col: 7640 row: []
col: 7641 similar rows:  [7641]
11111111111111111111
incomplete name 3, col: 7641 row: []
col: 7643 similar rows:  [7643, 8368, 8380, 8555, 8735, 8744, 8768, 9400, 9429, 9719]
incomplete name 3, col: 7643 row: []
col: 7646 similar rows:  [7646]
11111111111111111111
hotelname2 [7646]
incomplete name 3, col: 7646 row: [7646]
col: 7647 similar rows:  [7647]
11111111111111111111
incomplete name 3, col: 7647 row: []
col: 7648 similar rows:  [7648]
11111111111111111111
incomplete name 3, col: 7648 row: []
col: 7649 similar rows:  [7649]
11111111111111111111
incomplete name 3, col: 7649 row: []
col: 7650 similar rows:  [7650, 7715, 9234, 9279, 9558]
incomplete name 3, col: 7650 row: []
col: 7651 similar rows:  [7651]
11111111111111111111
incomplete name 3, col: 7651 row: []
col: 7652 similar rows:  [7652]
11111111111111111111
hotelname2 [7652]
incomplete name 3, col: 7652 row: []
col: 7653 similar rows:  [7653, 7858, 8082, 8524, 8918, 9373, 9584, 9774, 9797]
incomplete name 3, col: 7653 row: []
col: 7654 similar rows:  [7654]
11111111111111111111
incomplete name 3, col: 7654 row: []
col: 7655 similar rows:  [7655, 7678, 8230, 8603, 9064, 9070, 9146, 10065]
incomplete name 3, col: 7655 row: []
col: 7660 similar rows:  [7660, 7821]
incomplete name 3, col: 7660 row: []
col: 7661 similar rows:  [7661, 8991]
incomplete name 3, col: 7661 row: []
col: 7662 similar rows:  [7662, 7698]
incomplete name 3, col: 7662 row: []
col: 7664 similar rows:  [7664, 8656, 9634]
incomplete name 3, col: 7664 row: []
col: 7665 similar rows:  [7665]
11111111111111111111
incomplete name 3, col: 7665 row: []
col: 7669 similar rows:  [7669, 7965, 8321, 8878, 8944, 9189, 9358, 9479, 9509, 9512]
incomplete name 3, col: 7669 row: []
col: 7670 similar rows:  [7670]
11111111111111111111
incomplete name 3, col: 7670 row: []
col: 7671 similar rows:  [7671]
11111111111111111111
incomplete name 3, col: 7671 row: []
col: 7680 similar rows:  [7680, 8447]
incomplete name 3, col: 7680 row: []
col: 7684 similar rows:  [7684, 7692]
incomplete name 3, col: 7684 row: []
col: 7687 similar rows:  [7687, 7988, 8080, 8083, 8460, 9366, 10120]
incomplete name 3, col: 7687 row: []
col: 7688 similar rows:  [7688, 9068]
incomplete name 3, col: 7688 row: []
col: 7689 similar rows:  [7689, 8264, 8912, 9863]
incomplete name 3, col: 7689 row: []
col: 7693 similar rows:  [7693, 7852, 7855, 7932, 8732, 8867, 8901, 9701, 9734, 10192, 10214, 10223]
incomplete name 3, col: 7693 row: []
col: 7694 similar rows:  [7694, 8243]
incomplete name 3, col: 7694 row: []
col: 7695 similar rows:  [7695]
11111111111111111111
incomplete name 3, col: 7695 row: []
col: 7699 similar rows:  [7699, 8281, 10085]
incomplete name 3, col: 7699 row: []
col: 7700 similar rows:  [7700, 10008]
incomplete name 3, col: 7700 row: []
col: 7701 similar rows:  [7701, 7771, 8392]
incomplete name 3, col: 7701 row: []
col: 7702 similar rows:  [7702]
11111111111111111111
incomplete name 3, col: 7702 row: []
col: 7703 similar rows:  [7703, 7820, 8249, 8609, 9049, 9227, 9332]
incomplete name 3, col: 7703 row: []
col: 7704 similar rows:  [7704, 9050]
incomplete name 3, col: 7704 row: []
col: 7706 similar rows:  [7706]
11111111111111111111
incomplete name 3, col: 7706 row: []
col: 7709 similar rows:  [7709, 8109, 9342, 9381]
incomplete name 3, col: 7709 row: []
col: 7711 similar rows:  [7711, 8627, 8683]
incomplete name 3, col: 7711 row: []
col: 7717 similar rows:  [7717, 8305, 8471]
incomplete name 3, col: 7717 row: []
col: 7719 similar rows:  [7719]
11111111111111111111
incomplete name 3, col: 7719 row: []
col: 7721 similar rows:  [7721, 10158]
incomplete name 3, col: 7721 row: []
col: 7722 similar rows:  [7722]
11111111111111111111
incomplete name 3, col: 7722 row: []
col: 7724 similar rows:  [7724, 7882, 7983, 8085, 8343, 8858, 8882, 9105, 9165, 9404, 10043]
incomplete name 3, col: 7724 row: []
col: 7725 similar rows:  [7725, 9362, 9600]
incomplete name 3, col: 7725 row: []
col: 7727 similar rows:  [7727]
11111111111111111111
incomplete name 3, col: 7727 row: []
col: 7728 similar rows:  [7728]
11111111111111111111
incomplete name 3, col: 7728 row: []
col: 7729 similar rows:  [7729, 8214]
incomplete name 3, col: 7729 row: []
col: 7731 similar rows:  [7731]
11111111111111111111
incomplete name 3, col: 7731 row: []
col: 7732 similar rows:  [7732]
11111111111111111111
incomplete name 3, col: 7732 row: []
col: 7733 similar rows:  [7733]
11111111111111111111
incomplete name 3, col: 7733 row: []
col: 7734 similar rows:  [7734, 9785]
incomplete name 3, col: 7734 row: []
col: 7736 similar rows:  [7736]
11111111111111111111
incomplete name 3, col: 7736 row: []
col: 7737 similar rows:  [7737, 9076]
incomplete name 3, col: 7737 row: []
col: 7738 similar rows:  [7738, 8024, 8139, 8414, 8641, 8765, 9779]
incomplete name 3, col: 7738 row: []
col: 7741 similar rows:  [7741]
11111111111111111111
incomplete name 3, col: 7741 row: []
col: 7743 similar rows:  [7743, 7941, 8200, 8446, 8577, 8725, 9489, 9581, 9754, 9995, 10156]
incomplete name 3, col: 7743 row: []
col: 7745 similar rows:  [7745]
11111111111111111111
incomplete name 3, col: 7745 row: []
col: 7746 similar rows:  [7746, 7935, 7986, 7991, 10158]
incomplete name 3, col: 7746 row: []
col: 7747 similar rows:  [7747, 8702]
incomplete name 3, col: 7747 row: []
col: 7748 similar rows:  [7748, 8272, 8441, 8801, 8840, 9766]
hotelname2 [8801, 9766]
hotelname2 [8801, 9766]
incomplete name 3, col: 7748 row: []
col: 7750 similar rows:  [7750]
11111111111111111111
incomplete name 3, col: 7750 row: []
col: 7751 similar rows:  [7751, 8642, 8706, 9580, 9594, 9748]
incomplete name 3, col: 7751 row: []
col: 7752 similar rows:  [7752, 7810, 8686, 9519]
incomplete name 3, col: 7752 row: []
col: 7755 similar rows:  [7755]
11111111111111111111
incomplete name 3, col: 7755 row: []
col: 7756 similar rows:  [7756]
11111111111111111111
hotelname2 [7756]
wrong name!!!!
incomplete name 3, col: 7756 row: [7756]
col: 7760 similar rows:  [7760]
11111111111111111111
incomplete name 3, col: 7760 row: []
col: 7761 similar rows:  [7761, 8566]
incomplete name 3, col: 7761 row: []
col: 7763 similar rows:  [7763, 7787, 8242, 8460, 8544, 8685, 9366, 9730, 9835, 10194]
incomplete name 3, col: 7763 row: []
col: 7765 similar rows:  [7765]
11111111111111111111
hotelname2 [7765]
incomplete name 3, col: 7765 row: [7765]
col: 7767 similar rows:  [7767, 9683]
incomplete name 3, col: 7767 row: []
col: 7772 similar rows:  [7772, 7812]
incomplete name 3, col: 7772 row: []
col: 7773 similar rows:  [7773, 7925, 8408, 8501, 8516, 8554, 9044, 9215, 9569, 10153, 10187]
incomplete name 3, col: 7773 row: []
col: 7774 similar rows:  [7774, 8231, 8530, 9667, 10227]
incomplete name 3, col: 7774 row: []
col: 7777 similar rows:  [7777]
11111111111111111111
incomplete name 3, col: 7777 row: []
col: 7778 similar rows:  [7778, 7885, 8491, 8947, 9968]
hotelname2 [7885]
incomplete name 3, col: 7778 row: [7885]
col: 7783 similar rows:  [7783, 9567]
incomplete name 3, col: 7783 row: []
col: 7784 similar rows:  [7784]
11111111111111111111
incomplete name 3, col: 7784 row: []
col: 7785 similar rows:  [7785]
11111111111111111111
incomplete name 3, col: 7785 row: []
col: 7788 similar rows:  [7788]
11111111111111111111
incomplete name 3, col: 7788 row: []
col: 7791 similar rows:  [7791, 8048, 8184, 8615, 8894, 8937, 8973, 9116, 9137, 9170, 9208]
incomplete name 3, col: 7791 row: []
col: 7794 similar rows:  [7794]
11111111111111111111
incomplete name 3, col: 7794 row: []
col: 7796 similar rows:  [7796, 7832, 7861, 8166, 9204, 9222]
incomplete name 3, col: 7796 row: []
col: 7797 similar rows:  [7797, 9118]
incomplete name 3, col: 7797 row: []
col: 7798 similar rows:  [7798]
11111111111111111111
hotelname2 [7798]
incomplete name 3, col: 7798 row: [7798]
col: 7799 similar rows:  [7799, 7882, 7983, 8343, 8858, 8882, 9105, 9165, 9404, 9715, 10043]
incomplete name 3, col: 7799 row: []
col: 7804 similar rows:  [7804, 8454, 9894, 9915]
incomplete name 3, col: 7804 row: []
col: 7805 similar rows:  [7805, 7874, 8336, 8710, 8968, 9098, 9924, 9948]
incomplete name 3, col: 7805 row: []
col: 7807 similar rows:  [7807]
11111111111111111111
incomplete name 3, col: 7807 row: []
col: 7811 similar rows:  [7811, 9043]
incomplete name 3, col: 7811 row: []
col: 7815 similar rows:  [7815]
11111111111111111111
incomplete name 3, col: 7815 row: []
col: 7816 similar rows:  [7816, 9552]
incomplete name 3, col: 7816 row: []

col: 7817 similar rows:  [7817]
11111111111111111111
incomplete name 3, col: 7817 row: []
col: 7818 similar rows:  [7818, 7967, 7995, 7999, 8804, 8805, 8890, 8913, 8932, 9017, 9149, 9392, 9541, 10200]
incomplete name 3, col: 7818 row: []
col: 7819 similar rows:  [7819]
11111111111111111111
incomplete name 3, col: 7819 row: []
col: 7822 similar rows:  [7822, 7949, 8572]
incomplete name 3, col: 7822 row: []
col: 7823 similar rows:  [7823, 8167]
incomplete name 3, col: 7823 row: []
col: 7824 similar rows:  [7824]
11111111111111111111
incomplete name 3, col: 7824 row: []
col: 7825 similar rows:  [7825]
11111111111111111111
incomplete name 3, col: 7825 row: []
col: 7828 similar rows:  [7828]
11111111111111111111
incomplete name 3, col: 7828 row: []
col: 7829 similar rows:  [7829, 9246]
incomplete name 3, col: 7829 row: []
col: 7830 similar rows:  [7830, 8242, 8544, 9730, 10194]
incomplete name 3, col: 7830 row: []
col: 7831 similar rows:  [7831, 8171, 8601]
incomplete name 3, col: 7831 row: []
col: 7833 similar rows:  [7833]
11111111111111111111
incomplete name 3, col: 7833 row: []
col: 7837 similar rows:  [7837, 8117]
incomplete name 3, col: 7837 row: []
col: 7839 similar rows:  [7839, 9464]
incomplete name 3, col: 7839 row: []
col: 7840 similar rows:  [7840, 9184]
incomplete name 3, col: 7840 row: []
col: 7842 similar rows:  [7842]
11111111111111111111
incomplete name 3, col: 7842 row: []
col: 7843 similar rows:  [7843, 8342, 9274, 9554]
incomplete name 3, col: 7843 row: []
col: 7845 similar rows:  [7845]
11111111111111111111
incomplete name 3, col: 7845 row: []
col: 7846 similar rows:  [7846, 7871, 8595]
incomplete name 3, col: 7846 row: []
col: 7848 similar rows:  [7848]
11111111111111111111
incomplete name 3, col: 7848 row: []
col: 7849 similar rows:  [7849]
11111111111111111111
incomplete name 3, col: 7849 row: []
col: 7856 similar rows:  [7856]
11111111111111111111
incomplete name 3, col: 7856 row: []
col: 7859 similar rows:  [7859, 9644]
incomplete name 3, col: 7859 row: []
col: 7862 similar rows:  [7862]
11111111111111111111
hotelname2 [7862]
wrong name!!!!
incomplete name 3, col: 7862 row: [7862]
col: 7863 similar rows:  [7863]
11111111111111111111
incomplete name 3, col: 7863 row: []
col: 7864 similar rows:  [7864]
11111111111111111111
incomplete name 3, col: 7864 row: []
col: 7865 similar rows:  [7865]
11111111111111111111
hotelname2 [7865]
incomplete name 3, col: 7865 row: [7865]
col: 7866 similar rows:  [7866, 8312, 8613, 9375, 9679, 9747, 9756]
hotelname2 [9679]
incomplete name 3, col: 7866 row: [9679]
col: 7867 similar rows:  [7867, 7926, 8024, 8130, 8325, 8327, 8641, 8765, 8772, 9779]
incomplete name 3, col: 7867 row: []
col: 7868 similar rows:  [7868, 7943, 8352, 8697, 8959, 10116]
incomplete name 3, col: 7868 row: []
col: 7869 similar rows:  [7869]
11111111111111111111
incomplete name 3, col: 7869 row: []
col: 7873 similar rows:  [7873]
11111111111111111111
incomplete name 3, col: 7873 row: []
col: 7875 similar rows:  [7875, 9750]
incomplete name 3, col: 7875 row: []
col: 7877 similar rows:  [7877]
11111111111111111111
hotelname2 [7877]
incomplete name 3, col: 7877 row: []
col: 7878 similar rows:  [7878, 10088]
incomplete name 3, col: 7878 row: []
col: 7880 similar rows:  [7880, 8923]
incomplete name 3, col: 7880 row: []
col: 7883 similar rows:  [7883]
11111111111111111111
incomplete name 3, col: 7883 row: []
col: 7884 similar rows:  [7884, 8141, 8295, 8403, 8492, 8563, 8598, 8827, 8895, 10130, 10220]
incomplete name 3, col: 7884 row: []
col: 7887 similar rows:  [7887, 8344, 8868, 8914, 8948, 9327]
incomplete name 3, col: 7887 row: []
col: 7888 similar rows:  [7888, 8424, 8833]
incomplete name 3, col: 7888 row: []
col: 7892 similar rows:  [7892]
11111111111111111111
hotelname2 [7892]
incomplete name 3, col: 7892 row: []
col: 7893 similar rows:  [7893, 8292]
incomplete name 3, col: 7893 row: []
col: 7894 similar rows:  [7894, 9353]
incomplete name 3, col: 7894 row: []
col: 7895 similar rows:  [7895, 8356]
incomplete name 3, col: 7895 row: []
col: 7898 similar rows:  [7898]
11111111111111111111
hotelname2 [7898]
incomplete name 3, col: 7898 row: [7898]
col: 7899 similar rows:  [7899]
11111111111111111111
hotelname2 [7899]
incomplete name 3, col: 7899 row: [7899]
col: 7900 similar rows:  [7900]
11111111111111111111
incomplete name 3, col: 7900 row: []
col: 7902 similar rows:  [7902, 8456]
incomplete name 3, col: 7902 row: []
col: 7904 similar rows:  [7904, 8192, 9229, 9537]
hotelname2 [9537]
wrong name!!!!
incomplete name 3, col: 7904 row: [9537]
col: 7905 similar rows:  [7905, 8527]
incomplete name 3, col: 7905 row: []
col: 7906 similar rows:  [7906]
11111111111111111111
hotelname2 [7906]
incomplete name 3, col: 7906 row: [7906]
col: 7908 similar rows:  [7908]
11111111111111111111
incomplete name 3, col: 7908 row: []
col: 7910 similar rows:  [7910, 8315, 9539]
incomplete name 3, col: 7910 row: []
col: 7912 similar rows:  [7912, 8389, 8782]
incomplete name 3, col: 7912 row: []
col: 7913 similar rows:  [7913]
11111111111111111111
hotelname2 [7913]
incomplete name 3, col: 7913 row: [7913]
col: 7917 similar rows:  [7917]
11111111111111111111
incomplete name 3, col: 7917 row: []
col: 7918 similar rows:  [7918, 8766, 9543, 9688, 9974]
incomplete name 3, col: 7918 row: []
col: 7919 similar rows:  [7919]
11111111111111111111
incomplete name 3, col: 7919 row: []
col: 7920 similar rows:  [7920]
11111111111111111111
hotelname2 [7920]
incomplete name 3, col: 7920 row: []
col: 7921 similar rows:  [7921, 8996]
incomplete name 3, col: 7921 row: []
col: 7922 similar rows:  [7922, 8721, 8905]
incomplete name 3, col: 7922 row: []
col: 7923 similar rows:  [7923, 8843, 8963, 9037, 9096, 9865, 9871, 9975]
incomplete name 3, col: 7923 row: []
col: 7924 similar rows:  [7924]
11111111111111111111
hotelname2 [7924]
incomplete name 3, col: 7924 row: [7924]
col: 7927 similar rows:  [7927]
11111111111111111111
incomplete name 3, col: 7927 row: []
col: 7928 similar rows:  [7928, 9423]
incomplete name 3, col: 7928 row: []
col: 7929 similar rows:  [7929]
11111111111111111111
incomplete name 3, col: 7929 row: []
col: 7930 similar rows:  [7930]
11111111111111111111
incomplete name 3, col: 7930 row: []
col: 7931 similar rows:  [7931, 8794]
incomplete name 3, col: 7931 row: []
col: 7933 similar rows:  [7933, 8262, 9490, 9999]
incomplete name 3, col: 7933 row: []
col: 7934 similar rows:  [7934]
11111111111111111111
hotelname2 [7934]
incomplete name 3, col: 7934 row: [7934]
col: 7936 similar rows:  [7936]
11111111111111111111
incomplete name 3, col: 7936 row: []
col: 7937 similar rows:  [7937]
11111111111111111111
hotelname2 [7937]
wrong name!!!!
incomplete name 3, col: 7937 row: [7937]
col: 7938 similar rows:  [7938]
11111111111111111111
hotelname2 [7938]
incomplete name 3, col: 7938 row: [7938]
col: 7940 similar rows:  [7940, 7948, 8208, 8452, 10176]
incomplete name 3, col: 7940 row: []
col: 7942 similar rows:  [7942]
11111111111111111111
incomplete name 3, col: 7942 row: []
col: 7944 similar rows:  [7944]
11111111111111111111
hotelname2 [7944]
incomplete name 3, col: 7944 row: [7944]
col: 7945 similar rows:  [7945]
11111111111111111111
incomplete name 3, col: 7945 row: []
col: 7946 similar rows:  [7946]
11111111111111111111
incomplete name 3, col: 7946 row: []
col: 7951 similar rows:  [7951]
11111111111111111111
hotelname2 [7951]
incomplete name 3, col: 7951 row: [7951]
col: 7953 similar rows:  [7953]
11111111111111111111
incomplete name 3, col: 7953 row: []
col: 7954 similar rows:  [7954]
11111111111111111111
hotelname2 [7954]
incomplete name 3, col: 7954 row: []
col: 7956 similar rows:  [7956]
11111111111111111111
incomplete name 3, col: 7956 row: []
col: 7957 similar rows:  [7957, 8260, 9804]
incomplete name 3, col: 7957 row: []
col: 7959 similar rows:  [7959, 8059]
incomplete name 3, col: 7959 row: []
col: 7961 similar rows:  [7961, 8053, 9102, 9176]
incomplete name 3, col: 7961 row: []
col: 7962 similar rows:  [7962]
11111111111111111111
incomplete name 3, col: 7962 row: []
col: 7964 similar rows:  [7964, 7990, 8055, 8438]
incomplete name 3, col: 7964 row: []
col: 7966 similar rows:  [7966, 8634, 9491, 9506]
incomplete name 3, col: 7966 row: []
col: 7968 similar rows:  [7968]
11111111111111111111
incomplete name 3, col: 7968 row: []
col: 7969 similar rows:  [7969, 7984]
incomplete name 3, col: 7969 row: []
col: 7970 similar rows:  [7970]
11111111111111111111
incomplete name 3, col: 7970 row: []
col: 7971 similar rows:  [7971, 8330]
incomplete name 3, col: 7971 row: []
col: 7973 similar rows:  [7973]
11111111111111111111
incomplete name 3, col: 7973 row: []

col: 7975 similar rows:  [7975, 9805]
incomplete name 3, col: 7975 row: []
col: 7976 similar rows:  [7976]
11111111111111111111
incomplete name 3, col: 7976 row: []
col: 7977 similar rows:  [7977]
11111111111111111111
hotelname2 [7977]
incomplete name 3, col: 7977 row: []
col: 7978 similar rows:  [7978, 8854, 9800]
incomplete name 3, col: 7978 row: []
col: 7980 similar rows:  [7980]
11111111111111111111
incomplete name 3, col: 7980 row: []
col: 7982 similar rows:  [7982]
11111111111111111111
incomplete name 3, col: 7982 row: []
col: 7985 similar rows:  [7985]
11111111111111111111
incomplete name 3, col: 7985 row: []
col: 7989 similar rows:  [7989, 9582]
incomplete name 3, col: 7989 row: []
col: 7992 similar rows:  [7992]
11111111111111111111
incomplete name 3, col: 7992 row: []
col: 7996 similar rows:  [7996]
11111111111111111111
incomplete name 3, col: 7996 row: []
col: 7997 similar rows:  [7997]
11111111111111111111
hotelname2 [7997]
incomplete name 3, col: 7997 row: [7997]
col: 8000 similar rows:  [8000, 8035, 8045]
incomplete name 3, col: 8000 row: []
col: 8002 similar rows:  [8002, 8802]
incomplete name 3, col: 8002 row: []
col: 8004 similar rows:  [8004]
11111111111111111111
hotelname2 [8004]
wrong name!!!!
incomplete name 3, col: 8004 row: [8004]
col: 8005 similar rows:  [8005, 8266]
incomplete name 3, col: 8005 row: []
col: 8009 similar rows:  [8009]
11111111111111111111
incomplete name 3, col: 8009 row: []
col: 8010 similar rows:  [8010, 9303]
incomplete name 3, col: 8010 row: []
col: 8011 similar rows:  [8011, 9966]
incomplete name 3, col: 8011 row: []
col: 8013 similar rows:  [8013, 9031, 9480, 9664]
incomplete name 3, col: 8013 row: []
col: 8014 similar rows:  [8014, 8063]
incomplete name 3, col: 8014 row: []
col: 8017 similar rows:  [8017, 8081, 8967, 8977]
incomplete name 3, col: 8017 row: []
col: 8020 similar rows:  [8020, 9333, 9777, 10185]
incomplete name 3, col: 8020 row: []
col: 8022 similar rows:  [8022]
11111111111111111111
hotelname2 [8022]
incomplete name 3, col: 8022 row: [8022]
col: 8023 similar rows:  [8023, 8237, 9449]
incomplete name 3, col: 8023 row: []
col: 8028 similar rows:  [8028, 8961]
incomplete name 3, col: 8028 row: []
col: 8029 similar rows:  [8029]
11111111111111111111
incomplete name 3, col: 8029 row: []
col: 8030 similar rows:  [8030]
11111111111111111111
hotelname2 [8030]
incomplete name 3, col: 8030 row: []
col: 8038 similar rows:  [8038]
11111111111111111111
hotelname2 [8038]
incomplete name 3, col: 8038 row: [8038]
col: 8039 similar rows:  [8039]
11111111111111111111
incomplete name 3, col: 8039 row: []
col: 8040 similar rows:  [8040, 8068, 8660, 8698, 9349]
incomplete name 3, col: 8040 row: []
col: 8041 similar rows:  [8041, 8277, 9110]
incomplete name 3, col: 8041 row: []
col: 8043 similar rows:  [8043, 8640, 9482]
incomplete name 3, col: 8043 row: []
col: 8044 similar rows:  [8044]
11111111111111111111
incomplete name 3, col: 8044 row: []
col: 8046 similar rows:  [8046]
11111111111111111111
incomplete name 3, col: 8046 row: []
col: 8049 similar rows:  [8049]
11111111111111111111
incomplete name 3, col: 8049 row: []
col: 8050 similar rows:  [8050, 9957]
incomplete name 3, col: 8050 row: []
col: 8051 similar rows:  [8051, 8975, 9465, 9472, 9912]
incomplete name 3, col: 8051 row: []
col: 8052 similar rows:  [8052]
11111111111111111111
incomplete name 3, col: 8052 row: []
col: 8054 similar rows:  [8054]
11111111111111111111
hotelname2 [8054]
wrong name!!!!
incomplete name 3, col: 8054 row: [8054]
col: 8056 similar rows:  [8056, 8153, 8169, 8217, 8319, 8465, 8887, 9055]
incomplete name 3, col: 8056 row: []
col: 8057 similar rows:  [8057, 8504, 8864, 8897, 8910, 9109, 9395, 9500, 9657]
incomplete name 3, col: 8057 row: []
col: 8061 similar rows:  [8061]
11111111111111111111
incomplete name 3, col: 8061 row: []
col: 8064 similar rows:  [8064]
11111111111111111111
incomplete name 3, col: 8064 row: []
col: 8065 similar rows:  [8065]
11111111111111111111
hotelname2 [8065]
incomplete name 3, col: 8065 row: [8065]
col: 8066 similar rows:  [8066]
11111111111111111111
incomplete name 3, col: 8066 row: []
col: 8067 similar rows:  [8067]
11111111111111111111
incomplete name 3, col: 8067 row: []
col: 8069 similar rows:  [8069, 8863, 9092, 10211]
incomplete name 3, col: 8069 row: []
col: 8070 similar rows:  [8070]
11111111111111111111
incomplete name 3, col: 8070 row: []
col: 8071 similar rows:  [8071]
11111111111111111111
incomplete name 3, col: 8071 row: []
col: 8072 similar rows:  [8072, 8451]
incomplete name 3, col: 8072 row: []
col: 8073 similar rows:  [8073]
11111111111111111111
incomplete name 3, col: 8073 row: []
col: 8074 similar rows:  [8074]
11111111111111111111
incomplete name 3, col: 8074 row: []
col: 8075 similar rows:  [8075]
11111111111111111111
incomplete name 3, col: 8075 row: []
col: 8077 similar rows:  [8077]
11111111111111111111
incomplete name 3, col: 8077 row: []
col: 8079 similar rows:  [8079]
11111111111111111111
incomplete name 3, col: 8079 row: []
col: 8084 similar rows:  [8084, 9811]
incomplete name 3, col: 8084 row: []
col: 8086 similar rows:  [8086, 8263, 9046, 9635, 9753]
incomplete name 3, col: 8086 row: []
col: 8087 similar rows:  [8087]
11111111111111111111
incomplete name 3, col: 8087 row: []
col: 8088 similar rows:  [8088]
11111111111111111111
incomplete name 3, col: 8088 row: []
col: 8089 similar rows:  [8089]
11111111111111111111
incomplete name 3, col: 8089 row: []
col: 8090 similar rows:  [8090]
11111111111111111111
incomplete name 3, col: 8090 row: []
col: 8091 similar rows:  [8091]
11111111111111111111
incomplete name 3, col: 8091 row: []
col: 8092 similar rows:  [8092]
11111111111111111111
incomplete name 3, col: 8092 row: []
col: 8093 similar rows:  [8093]
11111111111111111111
incomplete name 3, col: 8093 row: []
col: 8094 similar rows:  [8094]
11111111111111111111
incomplete name 3, col: 8094 row: []
col: 8096 similar rows:  [8096]
11111111111111111111
incomplete name 3, col: 8096 row: []
col: 8101 similar rows:  [8101, 9082]
incomplete name 3, col: 8101 row: []
col: 8102 similar rows:  [8102]
11111111111111111111
incomplete name 3, col: 8102 row: []
col: 8103 similar rows:  [8103]
11111111111111111111
incomplete name 3, col: 8103 row: []
col: 8105 similar rows:  [8105, 8548, 8738, 9833, 9988, 10144, 10170]
incomplete name 3, col: 8105 row: []
col: 8107 similar rows:  [8107]
11111111111111111111
incomplete name 3, col: 8107 row: []
col: 8110 similar rows:  [8110, 9499]
incomplete name 3, col: 8110 row: []
col: 8112 similar rows:  [8112, 8876]
incomplete name 3, col: 8112 row: []
col: 8113 similar rows:  [8113]
11111111111111111111
incomplete name 3, col: 8113 row: []
col: 8118 similar rows:  [8118]
11111111111111111111
incomplete name 3, col: 8118 row: []
col: 8119 similar rows:  [8119]
11111111111111111111
incomplete name 3, col: 8119 row: []
col: 8121 similar rows:  [8121, 8288, 8293, 8684, 9560, 9847]
incomplete name 3, col: 8121 row: []
col: 8123 similar rows:  [8123]
11111111111111111111
incomplete name 3, col: 8123 row: []
col: 8124 similar rows:  [8124, 8178, 8304, 9880, 9892]
incomplete name 3, col: 8124 row: []
col: 8125 similar rows:  [8125, 9893]
incomplete name 3, col: 8125 row: []
col: 8135 similar rows:  [8135]
11111111111111111111
incomplete name 3, col: 8135 row: []
col: 8136 similar rows:  [8136, 9218, 9529]
incomplete name 3, col: 8136 row: []
col: 8137 similar rows:  [8137, 8434]
incomplete name 3, col: 8137 row: []
col: 8138 similar rows:  [8138, 9200, 9388, 9789, 10050]
incomplete name 3, col: 8138 row: []
col: 8140 similar rows:  [8140]
11111111111111111111
incomplete name 3, col: 8140 row: []
col: 8144 similar rows:  [8144, 9210]
incomplete name 3, col: 8144 row: []
col: 8145 similar rows:  [8145]
11111111111111111111
incomplete name 3, col: 8145 row: []
col: 8146 similar rows:  [8146, 9875, 10041]
incomplete name 3, col: 8146 row: []
col: 8147 similar rows:  [8147]
11111111111111111111
incomplete name 3, col: 8147 row: []
col: 8148 similar rows:  [8148]
11111111111111111111
incomplete name 3, col: 8148 row: []
col: 8149 similar rows:  [8149, 9180]
incomplete name 3, col: 8149 row: []
col: 8150 similar rows:  [8150, 9568]
incomplete name 3, col: 8150 row: []

col: 8152 similar rows:  [8152, 10204]
incomplete name 3, col: 8152 row: []
col: 8154 similar rows:  [8154, 9615]
incomplete name 3, col: 8154 row: []
col: 8155 similar rows:  [8155]
11111111111111111111
incomplete name 3, col: 8155 row: []
col: 8156 similar rows:  [8156, 8595, 9296]
incomplete name 3, col: 8156 row: []
col: 8157 similar rows:  [8157]
11111111111111111111
incomplete name 3, col: 8157 row: []
col: 8158 similar rows:  [8158, 8202, 8314, 8479, 8520, 9061, 9143, 9377, 9435]
incomplete name 3, col: 8158 row: []
col: 8161 similar rows:  [8161, 10037, 10062, 10114]
incomplete name 3, col: 8161 row: []
col: 8163 similar rows:  [8163]
11111111111111111111
incomplete name 3, col: 8163 row: []
col: 8164 similar rows:  [8164]
11111111111111111111
incomplete name 3, col: 8164 row: []
col: 8165 similar rows:  [8165]
11111111111111111111
hotelname2 [8165]
incomplete name 3, col: 8165 row: []
col: 8170 similar rows:  [8170]
11111111111111111111
incomplete name 3, col: 8170 row: []
col: 8172 similar rows:  [8172, 8192, 8198, 9537]
incomplete name 3, col: 8172 row: []
col: 8175 similar rows:  [8175, 9546]
incomplete name 3, col: 8175 row: []
col: 8180 similar rows:  [8180, 9707]
incomplete name 3, col: 8180 row: []
col: 8181 similar rows:  [8181]
11111111111111111111
incomplete name 3, col: 8181 row: []
col: 8183 similar rows:  [8183, 9038, 10042]
incomplete name 3, col: 8183 row: []
col: 8185 similar rows:  [8185, 8193, 8789, 9389, 9410]
incomplete name 3, col: 8185 row: []
col: 8186 similar rows:  [8186]
11111111111111111111
incomplete name 3, col: 8186 row: []
col: 8187 similar rows:  [8187]
11111111111111111111
incomplete name 3, col: 8187 row: []
col: 8188 similar rows:  [8188, 9535]
incomplete name 3, col: 8188 row: []
col: 8190 similar rows:  [8190]
11111111111111111111
incomplete name 3, col: 8190 row: []
col: 8191 similar rows:  [8191]
11111111111111111111
incomplete name 3, col: 8191 row: []
col: 8196 similar rows:  [8196]
11111111111111111111
incomplete name 3, col: 8196 row: []
col: 8201 similar rows:  [8201]
11111111111111111111
incomplete name 3, col: 8201 row: []
col: 8203 similar rows:  [8203]
11111111111111111111
incomplete name 3, col: 8203 row: []
col: 8205 similar rows:  [8205]
11111111111111111111
incomplete name 3, col: 8205 row: []
col: 8206 similar rows:  [8206, 8768]
incomplete name 3, col: 8206 row: []
col: 8209 similar rows:  [8209, 8620, 8835, 9077, 9617]
incomplete name 3, col: 8209 row: []
col: 8211 similar rows:  [8211]
11111111111111111111
hotelname2 [8211]
incomplete name 3, col: 8211 row: [8211]
col: 8212 similar rows:  [8212, 9567]
incomplete name 3, col: 8212 row: []
col: 8219 similar rows:  [8219]
11111111111111111111
incomplete name 3, col: 8219 row: []
col: 8221 similar rows:  [8221, 8317, 8988]
incomplete name 3, col: 8221 row: []
col: 8222 similar rows:  [8222]
11111111111111111111
incomplete name 3, col: 8222 row: []
col: 8223 similar rows:  [8223, 8252, 8793]
incomplete name 3, col: 8223 row: []
col: 8225 similar rows:  [8225, 9282, 9291, 9840]
incomplete name 3, col: 8225 row: []
col: 8226 similar rows:  [8226]
11111111111111111111
hotelname2 [8226]
incomplete name 3, col: 8226 row: [8226]
col: 8227 similar rows:  [8227]
11111111111111111111
incomplete name 3, col: 8227 row: []
col: 8228 similar rows:  [8228]
11111111111111111111
incomplete name 3, col: 8228 row: []
col: 8229 similar rows:  [8229, 9653, 10160]
incomplete name 3, col: 8229 row: []
col: 8232 similar rows:  [8232]
11111111111111111111
incomplete name 3, col: 8232 row: []
col: 8233 similar rows:  [8233]
11111111111111111111
incomplete name 3, col: 8233 row: []
col: 8234 similar rows:  [8234]
11111111111111111111
hotelname2 [8234]
incomplete name 3, col: 8234 row: [8234]
col: 8236 similar rows:  [8236]
11111111111111111111
incomplete name 3, col: 8236 row: []
col: 8239 similar rows:  [8239, 9626]
incomplete name 3, col: 8239 row: []
col: 8240 similar rows:  [8240]
11111111111111111111
hotelname2 [8240]
incomplete name 3, col: 8240 row: [8240]
col: 8241 similar rows:  [8241]
11111111111111111111
incomplete name 3, col: 8241 row: []
col: 8245 similar rows:  [8245]
11111111111111111111
incomplete name 3, col: 8245 row: []
col: 8246 similar rows:  [8246]
11111111111111111111
incomplete name 3, col: 8246 row: []
col: 8248 similar rows:  [8248]
11111111111111111111
hotelname2 [8248]
incomplete name 3, col: 8248 row: [8248]
col: 8250 similar rows:  [8250]
11111111111111111111
incomplete name 3, col: 8250 row: []
col: 8251 similar rows:  [8251]
11111111111111111111
incomplete name 3, col: 8251 row: []
col: 8253 similar rows:  [8253]
11111111111111111111
incomplete name 3, col: 8253 row: []
col: 8254 similar rows:  [8254, 9960]
incomplete name 3, col: 8254 row: []
col: 8255 similar rows:  [8255]
11111111111111111111
incomplete name 3, col: 8255 row: []
col: 8256 similar rows:  [8256]
11111111111111111111
incomplete name 3, col: 8256 row: []
col: 8257 similar rows:  [8257]
11111111111111111111
incomplete name 3, col: 8257 row: []
col: 8258 similar rows:  [8258]
11111111111111111111
hotelname2 [8258]
wrong name!!!!
incomplete name 3, col: 8258 row: [8258]
col: 8259 similar rows:  [8259]
11111111111111111111
incomplete name 3, col: 8259 row: []
col: 8270 similar rows:  [8270]
11111111111111111111
incomplete name 3, col: 8270 row: []
col: 8271 similar rows:  [8271, 8444, 9567]
incomplete name 3, col: 8271 row: []
col: 8276 similar rows:  [8276]
11111111111111111111
incomplete name 3, col: 8276 row: []
col: 8279 similar rows:  [8279, 8483, 8669, 9018, 9993, 9994, 10004, 10015, 10018, 10072, 10077, 10189, 10212]
incomplete name 3, col: 8279 row: []
col: 8280 similar rows:  [8280, 8648]
incomplete name 3, col: 8280 row: []
col: 8282 similar rows:  [8282]
11111111111111111111
incomplete name 3, col: 8282 row: []
col: 8285 similar rows:  [8285]
11111111111111111111
incomplete name 3, col: 8285 row: []
col: 8286 similar rows:  [8286, 9019]
incomplete name 3, col: 8286 row: []
col: 8287 similar rows:  [8287]
11111111111111111111
incomplete name 3, col: 8287 row: []
col: 8289 similar rows:  [8289]
11111111111111111111
incomplete name 3, col: 8289 row: []
col: 8297 similar rows:  [8297, 8497, 8823, 8930, 8993, 9062, 10171]
incomplete name 3, col: 8297 row: []
col: 8298 similar rows:  [8298]
11111111111111111111
incomplete name 3, col: 8298 row: []
col: 8299 similar rows:  [8299]
11111111111111111111
incomplete name 3, col: 8299 row: []
col: 8300 similar rows:  [8300]
11111111111111111111
incomplete name 3, col: 8300 row: []
col: 8302 similar rows:  [8302]
11111111111111111111
incomplete name 3, col: 8302 row: []
col: 8303 similar rows:  [8303]
11111111111111111111
incomplete name 3, col: 8303 row: []
col: 8306 similar rows:  [8306]
11111111111111111111
incomplete name 3, col: 8306 row: []
col: 8308 similar rows:  [8308, 9415]
incomplete name 3, col: 8308 row: []
col: 8310 similar rows:  [8310]
11111111111111111111
incomplete name 3, col: 8310 row: []
col: 8311 similar rows:  [8311]
11111111111111111111
incomplete name 3, col: 8311 row: []
col: 8313 similar rows:  [8313]
11111111111111111111
incomplete name 3, col: 8313 row: []
col: 8320 similar rows:  [8320]
11111111111111111111
incomplete name 3, col: 8320 row: []
col: 8322 similar rows:  [8322]
11111111111111111111
incomplete name 3, col: 8322 row: []
col: 8323 similar rows:  [8323]
11111111111111111111
incomplete name 3, col: 8323 row: []
col: 8328 similar rows:  [8328, 8339]
incomplete name 3, col: 8328 row: []
col: 8329 similar rows:  [8329, 8783, 9692, 9727, 9812]
incomplete name 3, col: 8329 row: []
col: 8331 similar rows:  [8331, 8373, 8801, 9431, 9686, 9766]
incomplete name 3, col: 8331 row: []
col: 8333 similar rows:  [8333]
11111111111111111111
hotelname2 [8333]
incomplete name 3, col: 8333 row: [8333]
col: 8334 similar rows:  [8334, 9174, 10020]
incomplete name 3, col: 8334 row: []
col: 8335 similar rows:  [8335, 9255]
incomplete name 3, col: 8335 row: []
col: 8338 similar rows:  [8338, 9034, 9844]
incomplete name 3, col: 8338 row: []
col: 8341 similar rows:  [8341, 8791]
incomplete name 3, col: 8341 row: []
col: 8345 similar rows:  [8345]
11111111111111111111
incomplete name 3, col: 8345 row: []

col: 8346 similar rows:  [8346, 8348]
incomplete name 3, col: 8346 row: []
col: 8347 similar rows:  [8347]
11111111111111111111
incomplete name 3, col: 8347 row: []
col: 8349 similar rows:  [8349]
11111111111111111111
hotelname2 [8349]
incomplete name 3, col: 8349 row: [8349]
col: 8353 similar rows:  [8353]
11111111111111111111
incomplete name 3, col: 8353 row: []
col: 8354 similar rows:  [8354]
11111111111111111111
hotelname2 [8354]
incomplete name 3, col: 8354 row: []
col: 8355 similar rows:  [8355]
11111111111111111111
incomplete name 3, col: 8355 row: []
col: 8357 similar rows:  [8357]
11111111111111111111
incomplete name 3, col: 8357 row: []
col: 8358 similar rows:  [8358]
11111111111111111111
incomplete name 3, col: 8358 row: []
col: 8359 similar rows:  [8359]
11111111111111111111
hotelname2 [8359]
incomplete name 3, col: 8359 row: []
col: 8360 similar rows:  [8360, 8474, 8510]
incomplete name 3, col: 8360 row: []
col: 8362 similar rows:  [8362, 8369, 9661]
incomplete name 3, col: 8362 row: []
col: 8364 similar rows:  [8364]
11111111111111111111
incomplete name 3, col: 8364 row: []
col: 8365 similar rows:  [8365]
11111111111111111111
incomplete name 3, col: 8365 row: []
col: 8366 similar rows:  [8366, 8853]
incomplete name 3, col: 8366 row: []
col: 8367 similar rows:  [8367]
11111111111111111111
incomplete name 3, col: 8367 row: []
col: 8370 similar rows:  [8370, 8586, 9233]
incomplete name 3, col: 8370 row: []
col: 8371 similar rows:  [8371]
11111111111111111111
incomplete name 3, col: 8371 row: []
col: 8374 similar rows:  [8374]
11111111111111111111
incomplete name 3, col: 8374 row: []
col: 8376 similar rows:  [8376, 9309]
incomplete name 3, col: 8376 row: []
col: 8377 similar rows:  [8377, 8534]
incomplete name 3, col: 8377 row: []
col: 8378 similar rows:  [8378, 8739, 9120, 10215]
incomplete name 3, col: 8378 row: []
col: 8379 similar rows:  [8379]
11111111111111111111
incomplete name 3, col: 8379 row: []
col: 8381 similar rows:  [8381, 9041, 9384, 9583]
incomplete name 3, col: 8381 row: []
col: 8382 similar rows:  [8382]
11111111111111111111
incomplete name 3, col: 8382 row: []
col: 8383 similar rows:  [8383]
11111111111111111111
incomplete name 3, col: 8383 row: []
col: 8384 similar rows:  [8384]
11111111111111111111
hotelname2 [8384]
incomplete name 3, col: 8384 row: []
col: 8385 similar rows:  [8385, 8639]
incomplete name 3, col: 8385 row: []
col: 8386 similar rows:  [8386, 8728, 8899, 9056, 9140, 9425, 9473]
incomplete name 3, col: 8386 row: []
col: 8387 similar rows:  [8387, 9878]
incomplete name 3, col: 8387 row: []
col: 8393 similar rows:  [8393, 8655, 8986, 9196, 9542, 10094, 10149]
incomplete name 3, col: 8393 row: []
col: 8396 similar rows:  [8396, 8700]
incomplete name 3, col: 8396 row: []
col: 8397 similar rows:  [8397]
11111111111111111111
incomplete name 3, col: 8397 row: []
col: 8398 similar rows:  [8398]
11111111111111111111
incomplete name 3, col: 8398 row: []
col: 8400 similar rows:  [8400]
11111111111111111111
incomplete name 3, col: 8400 row: []
col: 8401 similar rows:  [8401, 8402, 8782]
incomplete name 3, col: 8401 row: []
col: 8404 similar rows:  [8404]
11111111111111111111
hotelname2 [8404]
incomplete name 3, col: 8404 row: [8404]
col: 8405 similar rows:  [8405]
11111111111111111111
incomplete name 3, col: 8405 row: []
col: 8406 similar rows:  [8406]
11111111111111111111
incomplete name 3, col: 8406 row: []
col: 8409 similar rows:  [8409, 8982]
incomplete name 3, col: 8409 row: []
col: 8410 similar rows:  [8410]
11111111111111111111
incomplete name 3, col: 8410 row: []
col: 8412 similar rows:  [8412]
11111111111111111111
incomplete name 3, col: 8412 row: []
col: 8413 similar rows:  [8413, 9336]
incomplete name 3, col: 8413 row: []
col: 8417 similar rows:  [8417]
11111111111111111111
incomplete name 3, col: 8417 row: []
col: 8419 similar rows:  [8419, 8504, 8864, 8897, 8910, 9109, 9205, 9395, 9500, 9613, 9657]
incomplete name 3, col: 8419 row: []
col: 8420 similar rows:  [8420, 8687, 9015, 9488, 9585]
incomplete name 3, col: 8420 row: []
col: 8421 similar rows:  [8421, 8681, 9157, 9378, 9675, 10147]
incomplete name 3, col: 8421 row: []
col: 8422 similar rows:  [8422, 8437, 9510]
incomplete name 3, col: 8422 row: []
col: 8425 similar rows:  [8425, 9296, 9646]
incomplete name 3, col: 8425 row: []
col: 8426 similar rows:  [8426, 9084, 9104]
incomplete name 3, col: 8426 row: []
col: 8427 similar rows:  [8427]
11111111111111111111
incomplete name 3, col: 8427 row: []
col: 8428 similar rows:  [8428]
11111111111111111111
incomplete name 3, col: 8428 row: []
col: 8429 similar rows:  [8429, 8477, 8549, 9420, 9525, 9819]
incomplete name 3, col: 8429 row: []
col: 8431 similar rows:  [8431]
11111111111111111111
incomplete name 3, col: 8431 row: []
col: 8432 similar rows:  [8432, 9447]
incomplete name 3, col: 8432 row: []
col: 8435 similar rows:  [8435]
11111111111111111111
incomplete name 3, col: 8435 row: []
col: 8436 similar rows:  [8436]
11111111111111111111
incomplete name 3, col: 8436 row: []
col: 8439 similar rows:  [8439]
11111111111111111111
incomplete name 3, col: 8439 row: []
col: 8440 similar rows:  [8440]
11111111111111111111
incomplete name 3, col: 8440 row: []
col: 8442 similar rows:  [8442]
11111111111111111111
incomplete name 3, col: 8442 row: []
col: 8443 similar rows:  [8443]
11111111111111111111
incomplete name 3, col: 8443 row: []
col: 8449 similar rows:  [8449, 8718]
incomplete name 3, col: 8449 row: []
col: 8450 similar rows:  [8450]
11111111111111111111
incomplete name 3, col: 8450 row: []
col: 8457 similar rows:  [8457]
11111111111111111111
incomplete name 3, col: 8457 row: []
col: 8458 similar rows:  [8458]
11111111111111111111
incomplete name 3, col: 8458 row: []
col: 8459 similar rows:  [8459]
11111111111111111111
incomplete name 3, col: 8459 row: []
col: 8462 similar rows:  [8462, 8760, 10189]
incomplete name 3, col: 8462 row: []
col: 8463 similar rows:  [8463, 8486, 8712]
incomplete name 3, col: 8463 row: []
col: 8466 similar rows:  [8466, 9469, 9682]
incomplete name 3, col: 8466 row: []
col: 8468 similar rows:  [8468]
11111111111111111111
incomplete name 3, col: 8468 row: []
col: 8472 similar rows:  [8472]
11111111111111111111
incomplete name 3, col: 8472 row: []
col: 8475 similar rows:  [8475, 8540, 9841]
incomplete name 3, col: 8475 row: []
col: 8476 similar rows:  [8476]
11111111111111111111
incomplete name 3, col: 8476 row: []
col: 8478 similar rows:  [8478, 8734, 9831]
incomplete name 3, col: 8478 row: []
col: 8480 similar rows:  [8480]
11111111111111111111
hotelname2 [8480]
wrong name!!!!
incomplete name 3, col: 8480 row: [8480]
col: 8482 similar rows:  [8482]
11111111111111111111
incomplete name 3, col: 8482 row: []
col: 8484 similar rows:  [8484]
11111111111111111111
incomplete name 3, col: 8484 row: []
col: 8485 similar rows:  [8485, 8808]
incomplete name 3, col: 8485 row: []
col: 8487 similar rows:  [8487]
11111111111111111111
hotelname2 [8487]
incomplete name 3, col: 8487 row: [8487]
col: 8489 similar rows:  [8489, 10189]
incomplete name 3, col: 8489 row: []
col: 8494 similar rows:  [8494, 10110]
incomplete name 3, col: 8494 row: []
col: 8496 similar rows:  [8496]
11111111111111111111
incomplete name 3, col: 8496 row: []
col: 8500 similar rows:  [8500]
11111111111111111111
incomplete name 3, col: 8500 row: []
col: 8503 similar rows:  [8503]
11111111111111111111
incomplete name 3, col: 8503 row: []
col: 8505 similar rows:  [8505]
11111111111111111111
incomplete name 3, col: 8505 row: []
col: 8506 similar rows:  [8506]
11111111111111111111
hotelname2 [8506]
incomplete name 3, col: 8506 row: []
col: 8507 similar rows:  [8507]
11111111111111111111
hotelname2 [8507]
incomplete name 3, col: 8507 row: []
col: 8508 similar rows:  [8508, 10217]
incomplete name 3, col: 8508 row: []
col: 8509 similar rows:  [8509]
11111111111111111111
hotelname2 [8509]
incomplete name 3, col: 8509 row: [8509]
col: 8513 similar rows:  [8513]
11111111111111111111
incomplete name 3, col: 8513 row: []
col: 8515 similar rows:  [8515]
11111111111111111111
hotelname2 [8515]
incomplete name 3, col: 8515 row: []
col: 8518 similar rows:  [8518]
11111111111111111111
incomplete name 3, col: 8518 row: []
col: 8521 similar rows:  [8521, 9119]
incomplete name 3, col: 8521 row: []
col: 8522 similar rows:  [8522]
11111111111111111111
incomplete name 3, col: 8522 row: []

col: 8523 similar rows:  [8523]
11111111111111111111
incomplete name 3, col: 8523 row: []
col: 8525 similar rows:  [8525]
11111111111111111111
incomplete name 3, col: 8525 row: []
col: 8528 similar rows:  [8528]
11111111111111111111
incomplete name 3, col: 8528 row: []
col: 8531 similar rows:  [8531]
11111111111111111111
hotelname2 [8531]
incomplete name 3, col: 8531 row: [8531]
col: 8532 similar rows:  [8532]
11111111111111111111
incomplete name 3, col: 8532 row: []
col: 8533 similar rows:  [8533]
11111111111111111111
incomplete name 3, col: 8533 row: []
col: 8536 similar rows:  [8536]
11111111111111111111
incomplete name 3, col: 8536 row: []
col: 8537 similar rows:  [8537, 9523]
incomplete name 3, col: 8537 row: []
col: 8538 similar rows:  [8538, 8610]
incomplete name 3, col: 8538 row: []
col: 8543 similar rows:  [8543]
11111111111111111111
incomplete name 3, col: 8543 row: []
col: 8545 similar rows:  [8545]
11111111111111111111
incomplete name 3, col: 8545 row: []
col: 8551 similar rows:  [8551, 8552]
incomplete name 3, col: 8551 row: []
col: 8553 similar rows:  [8553]
11111111111111111111
incomplete name 3, col: 8553 row: []
col: 8556 similar rows:  [8556]
11111111111111111111
incomplete name 3, col: 8556 row: []
col: 8557 similar rows:  [8557]
11111111111111111111
incomplete name 3, col: 8557 row: []
col: 8558 similar rows:  [8558]
11111111111111111111
incomplete name 3, col: 8558 row: []
col: 8560 similar rows:  [8560]
11111111111111111111
incomplete name 3, col: 8560 row: []
col: 8561 similar rows:  [8561, 9391, 9437]
incomplete name 3, col: 8561 row: []
col: 8564 similar rows:  [8564, 9271]
incomplete name 3, col: 8564 row: []
col: 8568 similar rows:  [8568]
11111111111111111111
hotelname2 [8568]
incomplete name 3, col: 8568 row: []
col: 8569 similar rows:  [8569]
11111111111111111111
incomplete name 3, col: 8569 row: []
col: 8573 similar rows:  [8573]
11111111111111111111
incomplete name 3, col: 8573 row: []
col: 8574 similar rows:  [8574]
11111111111111111111
incomplete name 3, col: 8574 row: []
col: 8575 similar rows:  [8575, 8692, 8809, 10172]
incomplete name 3, col: 8575 row: []
col: 8576 similar rows:  [8576]
11111111111111111111
incomplete name 3, col: 8576 row: []
col: 8578 similar rows:  [8578]
11111111111111111111
hotelname2 [8578]
incomplete name 3, col: 8578 row: [8578]
col: 8579 similar rows:  [8579]
11111111111111111111
incomplete name 3, col: 8579 row: []
col: 8580 similar rows:  [8580]
11111111111111111111
incomplete name 3, col: 8580 row: []
col: 8582 similar rows:  [8582]
11111111111111111111
hotelname2 [8582]
incomplete name 3, col: 8582 row: [8582]
col: 8585 similar rows:  [8585]
11111111111111111111
incomplete name 3, col: 8585 row: []
col: 8587 similar rows:  [8587]
11111111111111111111
incomplete name 3, col: 8587 row: []
col: 8590 similar rows:  [8590]
11111111111111111111
incomplete name 3, col: 8590 row: []
col: 8591 similar rows:  [8591]
11111111111111111111
incomplete name 3, col: 8591 row: []
col: 8592 similar rows:  [8592]
11111111111111111111
hotelname2 [8592]
wrong name!!!!
incomplete name 3, col: 8592 row: [8592]
col: 8593 similar rows:  [8593]
11111111111111111111
incomplete name 3, col: 8593 row: []
col: 8597 similar rows:  [8597]
11111111111111111111
hotelname2 [8597]
wrong name!!!!
incomplete name 3, col: 8597 row: [8597]
col: 8600 similar rows:  [8600]
11111111111111111111
incomplete name 3, col: 8600 row: []
col: 8602 similar rows:  [8602]
11111111111111111111
incomplete name 3, col: 8602 row: []
col: 8604 similar rows:  [8604, 9528]
incomplete name 3, col: 8604 row: []
col: 8605 similar rows:  [8605]
11111111111111111111
incomplete name 3, col: 8605 row: []
col: 8606 similar rows:  [8606]
11111111111111111111
incomplete name 3, col: 8606 row: []
col: 8607 similar rows:  [8607]
11111111111111111111
hotelname2 [8607]
incomplete name 3, col: 8607 row: [8607]
col: 8608 similar rows:  [8608]
11111111111111111111
incomplete name 3, col: 8608 row: []
col: 8611 similar rows:  [8611]
11111111111111111111
incomplete name 3, col: 8611 row: []
col: 8612 similar rows:  [8612]
11111111111111111111
incomplete name 3, col: 8612 row: []
col: 8614 similar rows:  [8614, 8721, 8905, 9114, 9414, 9557]
hotelname2 [8721, 8905]
hotelname2 [8721, 8905]
incomplete name 3, col: 8614 row: [8721, 8905]
col: 8616 similar rows:  [8616]
11111111111111111111
incomplete name 3, col: 8616 row: []
col: 8617 similar rows:  [8617]
11111111111111111111
incomplete name 3, col: 8617 row: []
col: 8619 similar rows:  [8619]
11111111111111111111
incomplete name 3, col: 8619 row: []
col: 8621 similar rows:  [8621]
11111111111111111111
incomplete name 3, col: 8621 row: []
col: 8622 similar rows:  [8622]
11111111111111111111
hotelname2 [8622]
incomplete name 3, col: 8622 row: []
col: 8623 similar rows:  [8623]
11111111111111111111
incomplete name 3, col: 8623 row: []
col: 8624 similar rows:  [8624]
11111111111111111111
incomplete name 3, col: 8624 row: []
col: 8625 similar rows:  [8625]
11111111111111111111
incomplete name 3, col: 8625 row: []
col: 8626 similar rows:  [8626]
11111111111111111111
incomplete name 3, col: 8626 row: []
col: 8629 similar rows:  [8629, 8714]
incomplete name 3, col: 8629 row: []
col: 8630 similar rows:  [8630]
11111111111111111111
incomplete name 3, col: 8630 row: []
col: 8631 similar rows:  [8631, 8798]
incomplete name 3, col: 8631 row: []
col: 8632 similar rows:  [8632, 9551]
incomplete name 3, col: 8632 row: []
col: 8633 similar rows:  [8633]
11111111111111111111
incomplete name 3, col: 8633 row: []
col: 8635 similar rows:  [8635]
11111111111111111111
incomplete name 3, col: 8635 row: []
col: 8636 similar rows:  [8636]
11111111111111111111
incomplete name 3, col: 8636 row: []
col: 8637 similar rows:  [8637]
11111111111111111111
hotelname2 [8637]
incomplete name 3, col: 8637 row: [8637]
col: 8643 similar rows:  [8643, 9158, 9181, 10066]
incomplete name 3, col: 8643 row: []
col: 8644 similar rows:  [8644, 9867]
incomplete name 3, col: 8644 row: []
col: 8649 similar rows:  [8649, 10017]
incomplete name 3, col: 8649 row: []
col: 8654 similar rows:  [8654]
11111111111111111111
incomplete name 3, col: 8654 row: []
col: 8657 similar rows:  [8657]
11111111111111111111
incomplete name 3, col: 8657 row: []
col: 8658 similar rows:  [8658]
11111111111111111111
hotelname2 [8658]
wrong name!!!!
incomplete name 3, col: 8658 row: [8658]
col: 8659 similar rows:  [8659]
11111111111111111111
incomplete name 3, col: 8659 row: []
col: 8662 similar rows:  [8662]
11111111111111111111
incomplete name 3, col: 8662 row: []
col: 8665 similar rows:  [8665]
11111111111111111111
incomplete name 3, col: 8665 row: []
col: 8668 similar rows:  [8668, 9655]
incomplete name 3, col: 8668 row: []
col: 8670 similar rows:  [8670]
11111111111111111111
incomplete name 3, col: 8670 row: []
col: 8673 similar rows:  [8673]
11111111111111111111
incomplete name 3, col: 8673 row: []
col: 8675 similar rows:  [8675]
11111111111111111111
incomplete name 3, col: 8675 row: []
col: 8677 similar rows:  [8677, 8724, 9593]
incomplete name 3, col: 8677 row: []
col: 8678 similar rows:  [8678]
11111111111111111111
incomplete name 3, col: 8678 row: []
col: 8679 similar rows:  [8679]
11111111111111111111
incomplete name 3, col: 8679 row: []
col: 8680 similar rows:  [8680, 8850, 9601]
incomplete name 3, col: 8680 row: []
col: 8689 similar rows:  [8689, 9367]
incomplete name 3, col: 8689 row: []
col: 8691 similar rows:  [8691]
11111111111111111111
incomplete name 3, col: 8691 row: []
col: 8693 similar rows:  [8693]
11111111111111111111
incomplete name 3, col: 8693 row: []
col: 8699 similar rows:  [8699, 9447]
incomplete name 3, col: 8699 row: []
col: 8701 similar rows:  [8701]
11111111111111111111
incomplete name 3, col: 8701 row: []
col: 8703 similar rows:  [8703, 9424]
incomplete name 3, col: 8703 row: []
col: 8704 similar rows:  [8704]
11111111111111111111
incomplete name 3, col: 8704 row: []
col: 8705 similar rows:  [8705]
11111111111111111111
incomplete name 3, col: 8705 row: []
col: 8707 similar rows:  [8707, 10219]
incomplete name 3, col: 8707 row: []
col: 8709 similar rows:  [8709]
11111111111111111111
incomplete name 3, col: 8709 row: []
col: 8711 similar rows:  [8711]
11111111111111111111
hotelname2 [8711]
incomplete name 3, col: 8711 row: [8711]
col: 8713 similar rows:  [8713, 9088, 9763]
incomplete name 3, col: 8713 row: []

col: 8715 similar rows:  [8715]
11111111111111111111
incomplete name 3, col: 8715 row: []
col: 8716 similar rows:  [8716]
11111111111111111111
hotelname2 [8716]
incomplete name 3, col: 8716 row: [8716]
col: 8720 similar rows:  [8720]
11111111111111111111
incomplete name 3, col: 8720 row: []
col: 8726 similar rows:  [8726]
11111111111111111111
incomplete name 3, col: 8726 row: []
col: 8727 similar rows:  [8727]
11111111111111111111
incomplete name 3, col: 8727 row: []
col: 8729 similar rows:  [8729]
11111111111111111111
incomplete name 3, col: 8729 row: []
col: 8731 similar rows:  [8731, 9432, 9678]
incomplete name 3, col: 8731 row: []
col: 8733 similar rows:  [8733]
11111111111111111111
hotelname2 [8733]
incomplete name 3, col: 8733 row: []
col: 8736 similar rows:  [8736]
11111111111111111111
incomplete name 3, col: 8736 row: []
col: 8740 similar rows:  [8740, 9911]
incomplete name 3, col: 8740 row: []
col: 8741 similar rows:  [8741]
11111111111111111111
incomplete name 3, col: 8741 row: []
col: 8742 similar rows:  [8742, 9910]
incomplete name 3, col: 8742 row: []
col: 8743 similar rows:  [8743, 8912]
incomplete name 3, col: 8743 row: []
col: 8746 similar rows:  [8746]
11111111111111111111
incomplete name 3, col: 8746 row: []
col: 8747 similar rows:  [8747, 9081]
incomplete name 3, col: 8747 row: []
col: 8748 similar rows:  [8748, 9712]
incomplete name 3, col: 8748 row: []
col: 8749 similar rows:  [8749]
11111111111111111111
incomplete name 3, col: 8749 row: []
col: 8750 similar rows:  [8750]
11111111111111111111
incomplete name 3, col: 8750 row: []
col: 8751 similar rows:  [8751]
11111111111111111111
incomplete name 3, col: 8751 row: []
col: 8754 similar rows:  [8754]
11111111111111111111
incomplete name 3, col: 8754 row: []
col: 8755 similar rows:  [8755, 9275]
incomplete name 3, col: 8755 row: []
col: 8756 similar rows:  [8756]
11111111111111111111
incomplete name 3, col: 8756 row: []
col: 8757 similar rows:  [8757]
11111111111111111111
incomplete name 3, col: 8757 row: []
col: 8759 similar rows:  [8759]
11111111111111111111
incomplete name 3, col: 8759 row: []
col: 8762 similar rows:  [8762]
11111111111111111111
incomplete name 3, col: 8762 row: []
col: 8763 similar rows:  [8763, 9909]
incomplete name 3, col: 8763 row: []
col: 8764 similar rows:  [8764]
11111111111111111111
incomplete name 3, col: 8764 row: []
col: 8769 similar rows:  [8769]
11111111111111111111
incomplete name 3, col: 8769 row: []
col: 8771 similar rows:  [8771]
11111111111111111111
incomplete name 3, col: 8771 row: []
col: 8774 similar rows:  [8774, 8885]
incomplete name 3, col: 8774 row: []
col: 8776 similar rows:  [8776]
11111111111111111111
incomplete name 3, col: 8776 row: []
col: 8777 similar rows:  [8777, 9848]
incomplete name 3, col: 8777 row: []
col: 8778 similar rows:  [8778, 9575]
incomplete name 3, col: 8778 row: []
col: 8781 similar rows:  [8781]
11111111111111111111
incomplete name 3, col: 8781 row: []
col: 8784 similar rows:  [8784, 9313]
incomplete name 3, col: 8784 row: []
col: 8785 similar rows:  [8785]
11111111111111111111
incomplete name 3, col: 8785 row: []
col: 8786 similar rows:  [8786]
11111111111111111111
incomplete name 3, col: 8786 row: []
col: 8787 similar rows:  [8787]
11111111111111111111
incomplete name 3, col: 8787 row: []
col: 8788 similar rows:  [8788]
11111111111111111111
incomplete name 3, col: 8788 row: []
col: 8790 similar rows:  [8790]
11111111111111111111
incomplete name 3, col: 8790 row: []
col: 8792 similar rows:  [8792]
11111111111111111111
incomplete name 3, col: 8792 row: []
col: 8796 similar rows:  [8796]
11111111111111111111
hotelname2 [8796]
incomplete name 3, col: 8796 row: [8796]
col: 8803 similar rows:  [8803, 9073, 9963]
incomplete name 3, col: 8803 row: []
col: 8806 similar rows:  [8806]
11111111111111111111
hotelname2 [8806]
incomplete name 3, col: 8806 row: [8806]
col: 8807 similar rows:  [8807]
11111111111111111111
incomplete name 3, col: 8807 row: []
col: 8812 similar rows:  [8812]
11111111111111111111
incomplete name 3, col: 8812 row: []
col: 8813 similar rows:  [8813, 8894, 8937, 8973, 9116, 9137, 9170, 9195, 9630]
incomplete name 3, col: 8813 row: []
col: 8816 similar rows:  [8816]
11111111111111111111
incomplete name 3, col: 8816 row: []
col: 8818 similar rows:  [8818]
11111111111111111111
incomplete name 3, col: 8818 row: []
col: 8819 similar rows:  [8819]
11111111111111111111
incomplete name 3, col: 8819 row: []
col: 8822 similar rows:  [8822]
11111111111111111111
incomplete name 3, col: 8822 row: []
col: 8826 similar rows:  [8826, 9631]
incomplete name 3, col: 8826 row: []
col: 8828 similar rows:  [8828]
11111111111111111111
hotelname2 [8828]
incomplete name 3, col: 8828 row: [8828]
col: 8829 similar rows:  [8829]
11111111111111111111
hotelname2 [8829]
incomplete name 3, col: 8829 row: [8829]
col: 8830 similar rows:  [8830]
11111111111111111111
incomplete name 3, col: 8830 row: []
col: 8832 similar rows:  [8832]
11111111111111111111
incomplete name 3, col: 8832 row: []
col: 8836 similar rows:  [8836, 9370]
incomplete name 3, col: 8836 row: []
col: 8837 similar rows:  [8837]
11111111111111111111
incomplete name 3, col: 8837 row: []
col: 8838 similar rows:  [8838]
11111111111111111111
incomplete name 3, col: 8838 row: []
col: 8839 similar rows:  [8839]
11111111111111111111
incomplete name 3, col: 8839 row: []
col: 8841 similar rows:  [8841]
11111111111111111111
incomplete name 3, col: 8841 row: []
col: 8842 similar rows:  [8842]
11111111111111111111
incomplete name 3, col: 8842 row: []
col: 8845 similar rows:  [8845]
11111111111111111111
incomplete name 3, col: 8845 row: []
col: 8847 similar rows:  [8847]
11111111111111111111
incomplete name 3, col: 8847 row: []
col: 8848 similar rows:  [8848]
11111111111111111111
incomplete name 3, col: 8848 row: []
col: 8849 similar rows:  [8849]
11111111111111111111
incomplete name 3, col: 8849 row: []
col: 8851 similar rows:  [8851, 9663, 10048]
incomplete name 3, col: 8851 row: []
col: 8852 similar rows:  [8852]
11111111111111111111
incomplete name 3, col: 8852 row: []
col: 8857 similar rows:  [8857, 9856]
incomplete name 3, col: 8857 row: []
col: 8862 similar rows:  [8862, 9304]
incomplete name 3, col: 8862 row: []
col: 8865 similar rows:  [8865]
11111111111111111111
incomplete name 3, col: 8865 row: []
col: 8866 similar rows:  [8866]
11111111111111111111
incomplete name 3, col: 8866 row: []
col: 8871 similar rows:  [8871]
11111111111111111111
incomplete name 3, col: 8871 row: []
col: 8872 similar rows:  [8872, 9151]
incomplete name 3, col: 8872 row: []
col: 8873 similar rows:  [8873]
11111111111111111111
incomplete name 3, col: 8873 row: []
col: 8874 similar rows:  [8874]
11111111111111111111
incomplete name 3, col: 8874 row: []
col: 8875 similar rows:  [8875]
11111111111111111111
hotelname2 [8875]
incomplete name 3, col: 8875 row: []
col: 8879 similar rows:  [8879]
11111111111111111111
hotelname2 [8879]
incomplete name 3, col: 8879 row: [8879]
col: 8881 similar rows:  [8881, 8893, 9003]
incomplete name 3, col: 8881 row: []
col: 8884 similar rows:  [8884]
11111111111111111111
incomplete name 3, col: 8884 row: []
col: 8888 similar rows:  [8888]
11111111111111111111
incomplete name 3, col: 8888 row: []
col: 8889 similar rows:  [8889]
11111111111111111111
incomplete name 3, col: 8889 row: []
col: 8891 similar rows:  [8891]
11111111111111111111
incomplete name 3, col: 8891 row: []
col: 8892 similar rows:  [8892]
11111111111111111111
incomplete name 3, col: 8892 row: []
col: 8896 similar rows:  [8896]
11111111111111111111
hotelname2 [8896]
incomplete name 3, col: 8896 row: [8896]
col: 8898 similar rows:  [8898, 9795]
incomplete name 3, col: 8898 row: []
col: 8904 similar rows:  [8904]
11111111111111111111
incomplete name 3, col: 8904 row: []
col: 8906 similar rows:  [8906]
11111111111111111111
incomplete name 3, col: 8906 row: []
col: 8907 similar rows:  [8907, 9960]
incomplete name 3, col: 8907 row: []
col: 8908 similar rows:  [8908]
11111111111111111111
hotelname2 [8908]
incomplete name 3, col: 8908 row: [8908]
col: 8909 similar rows:  [8909, 9001, 9545, 9977]
incomplete name 3, col: 8909 row: []
col: 8911 similar rows:  [8911]
11111111111111111111
hotelname2 [8911]
incomplete name 3, col: 8911 row: []
col: 8917 similar rows:  [8917]
11111111111111111111
incomplete name 3, col: 8917 row: []
col: 8919 similar rows:  [8919, 9996]
incomplete name 3, col: 8919 row: []
col: 8925 similar rows:  [8925]
11111111111111111111
incomplete name 3, col: 8925 row: []
col: 8926 similar rows:  [8926, 9297]
incomplete name 3, col: 8926 row: []

col: 8928 similar rows:  [8928]
11111111111111111111
hotelname2 [8928]
incomplete name 3, col: 8928 row: [8928]
col: 8929 similar rows:  [8929]
11111111111111111111
hotelname2 [8929]
incomplete name 3, col: 8929 row: [8929]
col: 8936 similar rows:  [8936, 9366, 10120]
incomplete name 3, col: 8936 row: []
col: 8938 similar rows:  [8938, 8966, 9298]
incomplete name 3, col: 8938 row: []
col: 8940 similar rows:  [8940]
11111111111111111111
incomplete name 3, col: 8940 row: []
col: 8952 similar rows:  [8952]
11111111111111111111
incomplete name 3, col: 8952 row: []
col: 8953 similar rows:  [8953, 9305, 9330, 9481, 9577]
incomplete name 3, col: 8953 row: []
col: 8954 similar rows:  [8954]
11111111111111111111
incomplete name 3, col: 8954 row: []
col: 8955 similar rows:  [8955, 9030, 9896, 9945]
incomplete name 3, col: 8955 row: []
col: 8956 similar rows:  [8956, 10022, 10068, 10082]
incomplete name 3, col: 8956 row: []
col: 8957 similar rows:  [8957, 9775]
incomplete name 3, col: 8957 row: []
col: 8960 similar rows:  [8960]
11111111111111111111
incomplete name 3, col: 8960 row: []
col: 8962 similar rows:  [8962]
11111111111111111111
incomplete name 3, col: 8962 row: []
col: 8964 similar rows:  [8964]
11111111111111111111
incomplete name 3, col: 8964 row: []
col: 8972 similar rows:  [8972]
11111111111111111111
incomplete name 3, col: 8972 row: []
col: 8974 similar rows:  [8974]
11111111111111111111
incomplete name 3, col: 8974 row: []
col: 8978 similar rows:  [8978, 9123]
incomplete name 3, col: 8978 row: []
col: 8980 similar rows:  [8980]
11111111111111111111
incomplete name 3, col: 8980 row: []
col: 8981 similar rows:  [8981]
11111111111111111111
incomplete name 3, col: 8981 row: []
col: 8984 similar rows:  [8984, 9033]
incomplete name 3, col: 8984 row: []
col: 8985 similar rows:  [8985, 9958]
incomplete name 3, col: 8985 row: []
col: 8990 similar rows:  [8990]
11111111111111111111
hotelname2 [8990]
incomplete name 3, col: 8990 row: []
col: 8992 similar rows:  [8992]
11111111111111111111
incomplete name 3, col: 8992 row: []
col: 8995 similar rows:  [8995]
11111111111111111111
incomplete name 3, col: 8995 row: []
col: 9005 similar rows:  [9005]
11111111111111111111
incomplete name 3, col: 9005 row: []
col: 9006 similar rows:  [9006, 9087]
incomplete name 3, col: 9006 row: []
col: 9007 similar rows:  [9007]
11111111111111111111
incomplete name 3, col: 9007 row: []
col: 9008 similar rows:  [9008]
11111111111111111111
incomplete name 3, col: 9008 row: []
col: 9009 similar rows:  [9009]
11111111111111111111
incomplete name 3, col: 9009 row: []
col: 9011 similar rows:  [9011, 9690]
incomplete name 3, col: 9011 row: []
col: 9012 similar rows:  [9012, 9640]
incomplete name 3, col: 9012 row: []
col: 9013 similar rows:  [9013]
11111111111111111111
incomplete name 3, col: 9013 row: []
col: 9014 similar rows:  [9014]
11111111111111111111
incomplete name 3, col: 9014 row: []
col: 9016 similar rows:  [9016]
11111111111111111111
incomplete name 3, col: 9016 row: []
col: 9021 similar rows:  [9021]
11111111111111111111
incomplete name 3, col: 9021 row: []
col: 9024 similar rows:  [9024]
11111111111111111111
incomplete name 3, col: 9024 row: []
col: 9027 similar rows:  [9027]
11111111111111111111
incomplete name 3, col: 9027 row: []
col: 9029 similar rows:  [9029]
11111111111111111111
incomplete name 3, col: 9029 row: []
col: 9032 similar rows:  [9032, 9173, 9759]
incomplete name 3, col: 9032 row: []
col: 9035 similar rows:  [9035, 9933]
incomplete name 3, col: 9035 row: []
col: 9036 similar rows:  [9036]
11111111111111111111
incomplete name 3, col: 9036 row: []
col: 9039 similar rows:  [9039, 9701, 9734, 10192, 10214, 10223]
incomplete name 3, col: 9039 row: []
col: 9045 similar rows:  [9045]
11111111111111111111
incomplete name 3, col: 9045 row: []
col: 9047 similar rows:  [9047]
11111111111111111111
incomplete name 3, col: 9047 row: []
col: 9048 similar rows:  [9048]
11111111111111111111
hotelname2 [9048]
incomplete name 3, col: 9048 row: [9048]
col: 9052 similar rows:  [9052]
11111111111111111111
incomplete name 3, col: 9052 row: []
col: 9057 similar rows:  [9057]
11111111111111111111
incomplete name 3, col: 9057 row: []
col: 9058 similar rows:  [9058, 10037, 10062]
incomplete name 3, col: 9058 row: []
col: 9059 similar rows:  [9059]
11111111111111111111
incomplete name 3, col: 9059 row: []
col: 9060 similar rows:  [9060]
11111111111111111111
incomplete name 3, col: 9060 row: []
col: 9065 similar rows:  [9065]
11111111111111111111
incomplete name 3, col: 9065 row: []
col: 9074 similar rows:  [9074]
11111111111111111111
hotelname2 [9074]
incomplete name 3, col: 9074 row: [9074]
col: 9075 similar rows:  [9075]
11111111111111111111
incomplete name 3, col: 9075 row: []
col: 9083 similar rows:  [9083]
11111111111111111111
incomplete name 3, col: 9083 row: []
col: 9085 similar rows:  [9085, 9768]
incomplete name 3, col: 9085 row: []
col: 9091 similar rows:  [9091]
11111111111111111111
hotelname2 [9091]
incomplete name 3, col: 9091 row: [9091]
col: 9093 similar rows:  [9093]
11111111111111111111
incomplete name 3, col: 9093 row: []
col: 9094 similar rows:  [9094]
11111111111111111111
incomplete name 3, col: 9094 row: []
col: 9095 similar rows:  [9095, 9599, 9870]
incomplete name 3, col: 9095 row: []
col: 9097 similar rows:  [9097]
11111111111111111111
incomplete name 3, col: 9097 row: []
col: 9099 similar rows:  [9099]
11111111111111111111
incomplete name 3, col: 9099 row: []
col: 9100 similar rows:  [9100]
11111111111111111111
hotelname2 [9100]
incomplete name 3, col: 9100 row: [9100]
col: 9101 similar rows:  [9101]
11111111111111111111
incomplete name 3, col: 9101 row: []
col: 9103 similar rows:  [9103, 9413, 10133]
incomplete name 3, col: 9103 row: []
col: 9108 similar rows:  [9108]
11111111111111111111
incomplete name 3, col: 9108 row: []
col: 9121 similar rows:  [9121, 9618]
incomplete name 3, col: 9121 row: []
col: 9122 similar rows:  [9122]
11111111111111111111
incomplete name 3, col: 9122 row: []
col: 9124 similar rows:  [9124]
11111111111111111111
incomplete name 3, col: 9124 row: []
col: 9125 similar rows:  [9125]
11111111111111111111
incomplete name 3, col: 9125 row: []
col: 9126 similar rows:  [9126]
11111111111111111111
incomplete name 3, col: 9126 row: []
col: 9127 similar rows:  [9127]
11111111111111111111
hotelname2 [9127]
incomplete name 3, col: 9127 row: [9127]
col: 9128 similar rows:  [9128]
11111111111111111111
incomplete name 3, col: 9128 row: []
col: 9130 similar rows:  [9130, 9925]
incomplete name 3, col: 9130 row: []
col: 9132 similar rows:  [9132]
11111111111111111111
incomplete name 3, col: 9132 row: []
col: 9133 similar rows:  [9133, 9883]
incomplete name 3, col: 9133 row: []
col: 9135 similar rows:  [9135]
11111111111111111111
incomplete name 3, col: 9135 row: []
col: 9136 similar rows:  [9136]
11111111111111111111
incomplete name 3, col: 9136 row: []
col: 9141 similar rows:  [9141]
11111111111111111111
hotelname2 [9141]
incomplete name 3, col: 9141 row: [9141]
col: 9147 similar rows:  [9147]
11111111111111111111
hotelname2 [9147]
incomplete name 3, col: 9147 row: [9147]
col: 9148 similar rows:  [9148, 9956]
incomplete name 3, col: 9148 row: []
col: 9152 similar rows:  [9152, 9178, 9394]
incomplete name 3, col: 9152 row: []
col: 9154 similar rows:  [9154]
11111111111111111111
hotelname2 [9154]
incomplete name 3, col: 9154 row: [9154]
col: 9155 similar rows:  [9155]
11111111111111111111
incomplete name 3, col: 9155 row: []
col: 9161 similar rows:  [9161]
11111111111111111111
incomplete name 3, col: 9161 row: []
col: 9162 similar rows:  [9162, 9604]
incomplete name 3, col: 9162 row: []
col: 9163 similar rows:  [9163]
11111111111111111111
incomplete name 3, col: 9163 row: []
col: 9167 similar rows:  [9167]
11111111111111111111
incomplete name 3, col: 9167 row: []
col: 9168 similar rows:  [9168]
11111111111111111111
incomplete name 3, col: 9168 row: []
col: 9171 similar rows:  [9171]
11111111111111111111
incomplete name 3, col: 9171 row: []
col: 9175 similar rows:  [9175]
11111111111111111111
incomplete name 3, col: 9175 row: []
col: 9177 similar rows:  [9177]
11111111111111111111
incomplete name 3, col: 9177 row: []
col: 9179 similar rows:  [9179]
11111111111111111111
incomplete name 3, col: 9179 row: []
col: 9186 similar rows:  [9186]
11111111111111111111
incomplete name 3, col: 9186 row: []

col: 9188 similar rows:  [9188]
11111111111111111111
incomplete name 3, col: 9188 row: []
col: 9190 similar rows:  [9190, 9193]
incomplete name 3, col: 9190 row: []
col: 9194 similar rows:  [9194]
11111111111111111111
incomplete name 3, col: 9194 row: []
col: 9198 similar rows:  [9198, 9209, 9211, 9226, 9230, 9266, 9726, 9846, 9891, 9895, 10090, 10165]
incomplete name 3, col: 9198 row: []
col: 9199 similar rows:  [9199]
11111111111111111111
incomplete name 3, col: 9199 row: []
col: 9202 similar rows:  [9202]
11111111111111111111
incomplete name 3, col: 9202 row: []
col: 9206 similar rows:  [9206]
11111111111111111111
incomplete name 3, col: 9206 row: []
col: 9207 similar rows:  [9207]
11111111111111111111
incomplete name 3, col: 9207 row: []
col: 9212 similar rows:  [9212]
11111111111111111111
hotelname2 [9212]
incomplete name 3, col: 9212 row: [9212]
col: 9213 similar rows:  [9213]
11111111111111111111
incomplete name 3, col: 9213 row: []
col: 9216 similar rows:  [9216, 9266]
incomplete name 3, col: 9216 row: []
col: 9217 similar rows:  [9217]
11111111111111111111
incomplete name 3, col: 9217 row: []
col: 9219 similar rows:  [9219]
11111111111111111111
hotelname2 [9219]
wrong name!!!!
incomplete name 3, col: 9219 row: [9219]
col: 9220 similar rows:  [9220]
11111111111111111111
incomplete name 3, col: 9220 row: []
col: 9221 similar rows:  [9221]
11111111111111111111
incomplete name 3, col: 9221 row: []
col: 9228 similar rows:  [9228]
11111111111111111111
incomplete name 3, col: 9228 row: []
col: 9232 similar rows:  [9232]
11111111111111111111
incomplete name 3, col: 9232 row: []
col: 9235 similar rows:  [9235, 9266]
incomplete name 3, col: 9235 row: []
col: 9237 similar rows:  [9237]
11111111111111111111
incomplete name 3, col: 9237 row: []
col: 9238 similar rows:  [9238]
11111111111111111111
incomplete name 3, col: 9238 row: []
col: 9239 similar rows:  [9239]
11111111111111111111
hotelname2 [9239]
incomplete name 3, col: 9239 row: [9239]
col: 9241 similar rows:  [9241]
11111111111111111111
incomplete name 3, col: 9241 row: []
col: 9243 similar rows:  [9243]
11111111111111111111
incomplete name 3, col: 9243 row: []
col: 9244 similar rows:  [9244]
11111111111111111111
incomplete name 3, col: 9244 row: []
col: 9247 similar rows:  [9247]
11111111111111111111
incomplete name 3, col: 9247 row: []
col: 9248 similar rows:  [9248]
11111111111111111111
incomplete name 3, col: 9248 row: []
col: 9256 similar rows:  [9256]
11111111111111111111
incomplete name 3, col: 9256 row: []
col: 9257 similar rows:  [9257]
11111111111111111111
incomplete name 3, col: 9257 row: []
col: 9258 similar rows:  [9258]
11111111111111111111
incomplete name 3, col: 9258 row: []
col: 9259 similar rows:  [9259]
11111111111111111111
incomplete name 3, col: 9259 row: []
col: 9262 similar rows:  [9262]
11111111111111111111
incomplete name 3, col: 9262 row: []
col: 9264 similar rows:  [9264]
11111111111111111111
incomplete name 3, col: 9264 row: []
col: 9265 similar rows:  [9265]
11111111111111111111
incomplete name 3, col: 9265 row: []
col: 9267 similar rows:  [9267]
11111111111111111111
incomplete name 3, col: 9267 row: []
col: 9268 similar rows:  [9268]
11111111111111111111
incomplete name 3, col: 9268 row: []
col: 9269 similar rows:  [9269]
11111111111111111111
incomplete name 3, col: 9269 row: []
col: 9270 similar rows:  [9270]
11111111111111111111
hotelname2 [9270]
incomplete name 3, col: 9270 row: [9270]
col: 9272 similar rows:  [9272]
11111111111111111111
incomplete name 3, col: 9272 row: []
col: 9273 similar rows:  [9273]
11111111111111111111
incomplete name 3, col: 9273 row: []
col: 9276 similar rows:  [9276]
11111111111111111111
incomplete name 3, col: 9276 row: []
col: 9277 similar rows:  [9277]
11111111111111111111
incomplete name 3, col: 9277 row: []
col: 9278 similar rows:  [9278]
11111111111111111111
incomplete name 3, col: 9278 row: []
col: 9280 similar rows:  [9280]
11111111111111111111
incomplete name 3, col: 9280 row: []
col: 9281 similar rows:  [9281]
11111111111111111111
incomplete name 3, col: 9281 row: []
col: 9283 similar rows:  [9283]
11111111111111111111
incomplete name 3, col: 9283 row: []
col: 9284 similar rows:  [9284]
11111111111111111111
incomplete name 3, col: 9284 row: []
col: 9285 similar rows:  [9285]
11111111111111111111
incomplete name 3, col: 9285 row: []
col: 9286 similar rows:  [9286]
11111111111111111111
incomplete name 3, col: 9286 row: []
col: 9287 similar rows:  [9287]
11111111111111111111
incomplete name 3, col: 9287 row: []
col: 9289 similar rows:  [9289]
11111111111111111111
incomplete name 3, col: 9289 row: []
col: 9290 similar rows:  [9290, 9718]
incomplete name 3, col: 9290 row: []
col: 9292 similar rows:  [9292]
11111111111111111111
hotelname2 [9292]
incomplete name 3, col: 9292 row: [9292]
col: 9299 similar rows:  [9299]
11111111111111111111
incomplete name 3, col: 9299 row: []
col: 9300 similar rows:  [9300]
11111111111111111111
hotelname2 [9300]
incomplete name 3, col: 9300 row: [9300]
col: 9302 similar rows:  [9302]
11111111111111111111
incomplete name 3, col: 9302 row: []
col: 9311 similar rows:  [9311, 9432]
incomplete name 3, col: 9311 row: []
col: 9312 similar rows:  [9312]
11111111111111111111
incomplete name 3, col: 9312 row: []
col: 9314 similar rows:  [9314, 9315, 9316, 9337, 9351]
incomplete name 3, col: 9314 row: []
col: 9318 similar rows:  [9318]
11111111111111111111
incomplete name 3, col: 9318 row: []
col: 9324 similar rows:  [9324, 9796, 9877]
incomplete name 3, col: 9324 row: []
col: 9325 similar rows:  [9325]
11111111111111111111
incomplete name 3, col: 9325 row: []
col: 9331 similar rows:  [9331]
11111111111111111111
incomplete name 3, col: 9331 row: []
col: 9338 similar rows:  [9338]
11111111111111111111
incomplete name 3, col: 9338 row: []
col: 9340 similar rows:  [9340]
11111111111111111111
incomplete name 3, col: 9340 row: []
col: 9341 similar rows:  [9341]
11111111111111111111
incomplete name 3, col: 9341 row: []
col: 9346 similar rows:  [9346]
11111111111111111111
incomplete name 3, col: 9346 row: []
col: 9347 similar rows:  [9347]
11111111111111111111
incomplete name 3, col: 9347 row: []
col: 9350 similar rows:  [9350]
11111111111111111111
incomplete name 3, col: 9350 row: []
col: 9352 similar rows:  [9352]
11111111111111111111
incomplete name 3, col: 9352 row: []
col: 9354 similar rows:  [9354]
11111111111111111111
incomplete name 3, col: 9354 row: []
col: 9356 similar rows:  [9356]
11111111111111111111
incomplete name 3, col: 9356 row: []
col: 9360 similar rows:  [9360]
11111111111111111111
incomplete name 3, col: 9360 row: []
col: 9361 similar rows:  [9361]
11111111111111111111
incomplete name 3, col: 9361 row: []
col: 9364 similar rows:  [9364, 9555]
incomplete name 3, col: 9364 row: []
col: 9365 similar rows:  [9365]
11111111111111111111
incomplete name 3, col: 9365 row: []
col: 9369 similar rows:  [9369]
11111111111111111111
incomplete name 3, col: 9369 row: []
col: 9371 similar rows:  [9371]
11111111111111111111
incomplete name 3, col: 9371 row: []
col: 9372 similar rows:  [9372, 9743, 9764]
incomplete name 3, col: 9372 row: []
col: 9374 similar rows:  [9374]
11111111111111111111
incomplete name 3, col: 9374 row: []
col: 9376 similar rows:  [9376]
11111111111111111111
incomplete name 3, col: 9376 row: []
col: 9379 similar rows:  [9379]
11111111111111111111
incomplete name 3, col: 9379 row: []
col: 9380 similar rows:  [9380]
11111111111111111111
incomplete name 3, col: 9380 row: []
col: 9383 similar rows:  [9383, 10191]
incomplete name 3, col: 9383 row: []
col: 9385 similar rows:  [9385]
11111111111111111111
incomplete name 3, col: 9385 row: []
col: 9386 similar rows:  [9386]
11111111111111111111
incomplete name 3, col: 9386 row: []
col: 9387 similar rows:  [9387]
11111111111111111111
incomplete name 3, col: 9387 row: []
col: 9390 similar rows:  [9390]
11111111111111111111
incomplete name 3, col: 9390 row: []
col: 9396 similar rows:  [9396, 9647, 10131]
incomplete name 3, col: 9396 row: []
col: 9397 similar rows:  [9397]
11111111111111111111
hotelname2 [9397]
incomplete name 3, col: 9397 row: [9397]
col: 9398 similar rows:  [9398]
11111111111111111111
incomplete name 3, col: 9398 row: []
col: 9399 similar rows:  [9399]
11111111111111111111
incomplete name 3, col: 9399 row: []
col: 9401 similar rows:  [9401]
11111111111111111111
incomplete name 3, col: 9401 row: []
col: 9402 similar rows:  [9402]
11111111111111111111
incomplete name 3, col: 9402 row: []
col: 9403 similar rows:  [9403]
11111111111111111111
incomplete name 3, col: 9403 row: []

col: 9406 similar rows:  [9406]
11111111111111111111
incomplete name 3, col: 9406 row: []
col: 9408 similar rows:  [9408]
11111111111111111111
hotelname2 [9408]
incomplete name 3, col: 9408 row: [9408]
col: 9409 similar rows:  [9409]
11111111111111111111
incomplete name 3, col: 9409 row: []
col: 9411 similar rows:  [9411, 9771]
incomplete name 3, col: 9411 row: []
col: 9412 similar rows:  [9412]
11111111111111111111
hotelname2 [9412]
incomplete name 3, col: 9412 row: [9412]
col: 9419 similar rows:  [9419]
11111111111111111111
incomplete name 3, col: 9419 row: []
col: 9426 similar rows:  [9426]
11111111111111111111
incomplete name 3, col: 9426 row: []
col: 9428 similar rows:  [9428]
11111111111111111111
incomplete name 3, col: 9428 row: []
col: 9434 similar rows:  [9434]
11111111111111111111
hotelname2 [9434]
wrong name!!!!
incomplete name 3, col: 9434 row: [9434]
col: 9436 similar rows:  [9436]
11111111111111111111
incomplete name 3, col: 9436 row: []
col: 9438 similar rows:  [9438]
11111111111111111111
incomplete name 3, col: 9438 row: []
col: 9439 similar rows:  [9439]
11111111111111111111
incomplete name 3, col: 9439 row: []
col: 9440 similar rows:  [9440]
11111111111111111111
hotelname2 [9440]
incomplete name 3, col: 9440 row: [9440]
col: 9443 similar rows:  [9443]
11111111111111111111
incomplete name 3, col: 9443 row: []
col: 9444 similar rows:  [9444]
11111111111111111111
incomplete name 3, col: 9444 row: []
col: 9446 similar rows:  [9446]
11111111111111111111
hotelname2 [9446]
incomplete name 3, col: 9446 row: [9446]
col: 9448 similar rows:  [9448]
11111111111111111111
incomplete name 3, col: 9448 row: []
col: 9450 similar rows:  [9450]
11111111111111111111
hotelname2 [9450]
incomplete name 3, col: 9450 row: [9450]
col: 9452 similar rows:  [9452]
11111111111111111111
incomplete name 3, col: 9452 row: []
col: 9453 similar rows:  [9453]
11111111111111111111
incomplete name 3, col: 9453 row: []
col: 9455 similar rows:  [9455]
11111111111111111111
incomplete name 3, col: 9455 row: []
col: 9456 similar rows:  [9456]
11111111111111111111
incomplete name 3, col: 9456 row: []
col: 9457 similar rows:  [9457]
11111111111111111111
incomplete name 3, col: 9457 row: []
col: 9458 similar rows:  [9458]
11111111111111111111
incomplete name 3, col: 9458 row: []
col: 9459 similar rows:  [9459]
11111111111111111111
incomplete name 3, col: 9459 row: []
col: 9460 similar rows:  [9460]
11111111111111111111
incomplete name 3, col: 9460 row: []
col: 9461 similar rows:  [9461]
11111111111111111111
incomplete name 3, col: 9461 row: []
col: 9462 similar rows:  [9462]
11111111111111111111
hotelname2 [9462]
wrong name!!!!
incomplete name 3, col: 9462 row: [9462]
col: 9466 similar rows:  [9466]
11111111111111111111
incomplete name 3, col: 9466 row: []
col: 9467 similar rows:  [9467, 9695]
incomplete name 3, col: 9467 row: []
col: 9470 similar rows:  [9470]
11111111111111111111
hotelname2 [9470]
incomplete name 3, col: 9470 row: [9470]
col: 9471 similar rows:  [9471]
11111111111111111111
incomplete name 3, col: 9471 row: []
col: 9474 similar rows:  [9474]
11111111111111111111
incomplete name 3, col: 9474 row: []
col: 9475 similar rows:  [9475]
11111111111111111111
incomplete name 3, col: 9475 row: []
col: 9477 similar rows:  [9477]
11111111111111111111
incomplete name 3, col: 9477 row: []
col: 9483 similar rows:  [9483]
11111111111111111111
incomplete name 3, col: 9483 row: []
col: 9485 similar rows:  [9485]
11111111111111111111
incomplete name 3, col: 9485 row: []
col: 9492 similar rows:  [9492]
11111111111111111111
incomplete name 3, col: 9492 row: []
col: 9503 similar rows:  [9503]
11111111111111111111
incomplete name 3, col: 9503 row: []
col: 9505 similar rows:  [9505, 10182]
incomplete name 3, col: 9505 row: []
col: 9514 similar rows:  [9514, 10116]
incomplete name 3, col: 9514 row: []
col: 9515 similar rows:  [9515]
11111111111111111111
incomplete name 3, col: 9515 row: []
col: 9518 similar rows:  [9518, 9957]
incomplete name 3, col: 9518 row: []
col: 9520 similar rows:  [9520, 10136]
incomplete name 3, col: 9520 row: []
col: 9521 similar rows:  [9521]
11111111111111111111
incomplete name 3, col: 9521 row: []
col: 9522 similar rows:  [9522, 10138]
incomplete name 3, col: 9522 row: []
col: 9526 similar rows:  [9526]
11111111111111111111
incomplete name 3, col: 9526 row: []
col: 9530 similar rows:  [9530]
11111111111111111111
hotelname2 [9530]
incomplete name 3, col: 9530 row: [9530]
col: 9531 similar rows:  [9531]
11111111111111111111
hotelname2 [9531]
incomplete name 3, col: 9531 row: [9531]
col: 9532 similar rows:  [9532]
11111111111111111111
incomplete name 3, col: 9532 row: []
col: 9533 similar rows:  [9533]
11111111111111111111
incomplete name 3, col: 9533 row: []
col: 9538 similar rows:  [9538]
11111111111111111111
hotelname2 [9538]
incomplete name 3, col: 9538 row: [9538]
col: 9547 similar rows:  [9547]
11111111111111111111
incomplete name 3, col: 9547 row: []
col: 9548 similar rows:  [9548]
11111111111111111111
hotelname2 [9548]
incomplete name 3, col: 9548 row: [9548]
col: 9549 similar rows:  [9549]
11111111111111111111
incomplete name 3, col: 9549 row: []
col: 9553 similar rows:  [9553]
11111111111111111111
incomplete name 3, col: 9553 row: []
col: 9556 similar rows:  [9556]
11111111111111111111
incomplete name 3, col: 9556 row: []
col: 9559 similar rows:  [9559]
11111111111111111111
incomplete name 3, col: 9559 row: []
col: 9561 similar rows:  [9561]
11111111111111111111
incomplete name 3, col: 9561 row: []
col: 9562 similar rows:  [9562, 10186]
incomplete name 3, col: 9562 row: []
col: 9564 similar rows:  [9564]
11111111111111111111
incomplete name 3, col: 9564 row: []
col: 9565 similar rows:  [9565]
11111111111111111111
incomplete name 3, col: 9565 row: []
col: 9566 similar rows:  [9566]
11111111111111111111
incomplete name 3, col: 9566 row: []
col: 9570 similar rows:  [9570, 10128]
incomplete name 3, col: 9570 row: []
col: 9571 similar rows:  [9571]
11111111111111111111
incomplete name 3, col: 9571 row: []
col: 9572 similar rows:  [9572, 9876]
incomplete name 3, col: 9572 row: []
col: 9573 similar rows:  [9573]
11111111111111111111
incomplete name 3, col: 9573 row: []
col: 9578 similar rows:  [9578]
11111111111111111111
hotelname2 [9578]
incomplete name 3, col: 9578 row: [9578]
col: 9586 similar rows:  [9586]
11111111111111111111
incomplete name 3, col: 9586 row: []
col: 9590 similar rows:  [9590]
11111111111111111111
hotelname2 [9590]
incomplete name 3, col: 9590 row: [9590]
col: 9591 similar rows:  [9591]
11111111111111111111
incomplete name 3, col: 9591 row: []
col: 9592 similar rows:  [9592]
11111111111111111111
incomplete name 3, col: 9592 row: []
col: 9602 similar rows:  [9602, 9637, 9940, 9953]
incomplete name 3, col: 9602 row: []
col: 9603 similar rows:  [9603, 9720, 9962]
incomplete name 3, col: 9603 row: []
col: 9605 similar rows:  [9605]
11111111111111111111
incomplete name 3, col: 9605 row: []
col: 9609 similar rows:  [9609]
11111111111111111111
hotelname2 [9609]
incomplete name 3, col: 9609 row: [9609]
col: 9610 similar rows:  [9610, 9784]
incomplete name 3, col: 9610 row: []
col: 9614 similar rows:  [9614]
11111111111111111111
hotelname2 [9614]
incomplete name 3, col: 9614 row: [9614]
col: 9616 similar rows:  [9616, 9890]
incomplete name 3, col: 9616 row: []
col: 9619 similar rows:  [9619]
11111111111111111111
hotelname2 [9619]
wrong name!!!!
incomplete name 3, col: 9619 row: [9619]
col: 9620 similar rows:  [9620]
11111111111111111111
incomplete name 3, col: 9620 row: []
col: 9621 similar rows:  [9621]
11111111111111111111
incomplete name 3, col: 9621 row: []
col: 9624 similar rows:  [9624]
11111111111111111111
incomplete name 3, col: 9624 row: []
col: 9628 similar rows:  [9628]
11111111111111111111
incomplete name 3, col: 9628 row: []
col: 9629 similar rows:  [9629]
11111111111111111111
incomplete name 3, col: 9629 row: []
col: 9632 similar rows:  [9632]
11111111111111111111
incomplete name 3, col: 9632 row: []
col: 9633 similar rows:  [9633]
11111111111111111111
incomplete name 3, col: 9633 row: []
col: 9636 similar rows:  [9636]
11111111111111111111
incomplete name 3, col: 9636 row: []
col: 9638 similar rows:  [9638]
11111111111111111111
incomplete name 3, col: 9638 row: []
col: 9641 similar rows:  [9641]
11111111111111111111
incomplete name 3, col: 9641 row: []
col: 9643 similar rows:  [9643]
11111111111111111111
incomplete name 3, col: 9643 row: []
col: 9648 similar rows:  [9648]
11111111111111111111
incomplete name 3, col: 9648 row: []
col: 9649 similar rows:  [9649]
11111111111111111111
incomplete name 3, col: 9649 row: []
col: 9650 similar rows:  [9650]
11111111111111111111
incomplete name 3, col: 9650 row: []
col: 9651 similar rows:  [9651]
11111111111111111111
incomplete name 3, col: 9651 row: []

col: 9652 similar rows:  [9652]
11111111111111111111
incomplete name 3, col: 9652 row: []
col: 9654 similar rows:  [9654]
11111111111111111111
incomplete name 3, col: 9654 row: []
col: 9656 similar rows:  [9656]
11111111111111111111
incomplete name 3, col: 9656 row: []
col: 9658 similar rows:  [9658]
11111111111111111111
incomplete name 3, col: 9658 row: []
col: 9660 similar rows:  [9660]
11111111111111111111
incomplete name 3, col: 9660 row: []
col: 9662 similar rows:  [9662]
11111111111111111111
incomplete name 3, col: 9662 row: []
col: 9665 similar rows:  [9665]
11111111111111111111
incomplete name 3, col: 9665 row: []
col: 9668 similar rows:  [9668]
11111111111111111111
hotelname2 [9668]
incomplete name 3, col: 9668 row: []
col: 9669 similar rows:  [9669, 10000]
incomplete name 3, col: 9669 row: []
col: 9670 similar rows:  [9670]
11111111111111111111
incomplete name 3, col: 9670 row: []
col: 9671 similar rows:  [9671]
11111111111111111111
incomplete name 3, col: 9671 row: []
col: 9672 similar rows:  [9672]
11111111111111111111
incomplete name 3, col: 9672 row: []
col: 9673 similar rows:  [9673]
11111111111111111111
incomplete name 3, col: 9673 row: []
col: 9674 similar rows:  [9674]
11111111111111111111
incomplete name 3, col: 9674 row: []
col: 9676 similar rows:  [9676]
11111111111111111111
hotelname2 [9676]
incomplete name 3, col: 9676 row: []
col: 9677 similar rows:  [9677]
11111111111111111111
incomplete name 3, col: 9677 row: []
col: 9680 similar rows:  [9680]
11111111111111111111
incomplete name 3, col: 9680 row: []
col: 9681 similar rows:  [9681]
11111111111111111111
incomplete name 3, col: 9681 row: []
col: 9685 similar rows:  [9685, 10196]
incomplete name 3, col: 9685 row: []
col: 9687 similar rows:  [9687]
11111111111111111111
incomplete name 3, col: 9687 row: []
col: 9689 similar rows:  [9689]
11111111111111111111
incomplete name 3, col: 9689 row: []
col: 9691 similar rows:  [9691]
11111111111111111111
incomplete name 3, col: 9691 row: []
col: 9693 similar rows:  [9693]
11111111111111111111
incomplete name 3, col: 9693 row: []
col: 9694 similar rows:  [9694]
11111111111111111111
incomplete name 3, col: 9694 row: []
col: 9696 similar rows:  [9696]
11111111111111111111
incomplete name 3, col: 9696 row: []
col: 9697 similar rows:  [9697, 10177]
incomplete name 3, col: 9697 row: []
col: 9698 similar rows:  [9698]
11111111111111111111
incomplete name 3, col: 9698 row: []
col: 9699 similar rows:  [9699]
11111111111111111111
hotelname2 [9699]
wrong name!!!!
incomplete name 3, col: 9699 row: [9699]
col: 9700 similar rows:  [9700]
11111111111111111111
incomplete name 3, col: 9700 row: []
col: 9702 similar rows:  [9702]
11111111111111111111
incomplete name 3, col: 9702 row: []
col: 9703 similar rows:  [9703, 9704]
incomplete name 3, col: 9703 row: []
col: 9706 similar rows:  [9706]
11111111111111111111
incomplete name 3, col: 9706 row: []
col: 9708 similar rows:  [9708]
11111111111111111111
incomplete name 3, col: 9708 row: []
col: 9709 similar rows:  [9709]
11111111111111111111
incomplete name 3, col: 9709 row: []
col: 9710 similar rows:  [9710]
11111111111111111111
hotelname2 [9710]
incomplete name 3, col: 9710 row: [9710]
col: 9711 similar rows:  [9711]
11111111111111111111
incomplete name 3, col: 9711 row: []
col: 9713 similar rows:  [9713]
11111111111111111111
incomplete name 3, col: 9713 row: []
col: 9714 similar rows:  [9714]
11111111111111111111
incomplete name 3, col: 9714 row: []
col: 9716 similar rows:  [9716]
11111111111111111111
incomplete name 3, col: 9716 row: []
col: 9717 similar rows:  [9717]
11111111111111111111
incomplete name 3, col: 9717 row: []
col: 9721 similar rows:  [9721]
11111111111111111111
incomplete name 3, col: 9721 row: []
col: 9722 similar rows:  [9722]
11111111111111111111
incomplete name 3, col: 9722 row: []
col: 9723 similar rows:  [9723]
11111111111111111111
incomplete name 3, col: 9723 row: []
col: 9724 similar rows:  [9724]
11111111111111111111
incomplete name 3, col: 9724 row: []
col: 9725 similar rows:  [9725]
11111111111111111111
incomplete name 3, col: 9725 row: []
col: 9729 similar rows:  [9729]
11111111111111111111
incomplete name 3, col: 9729 row: []
col: 9731 similar rows:  [9731]
11111111111111111111
incomplete name 3, col: 9731 row: []
col: 9732 similar rows:  [9732]
11111111111111111111
hotelname2 [9732]
incomplete name 3, col: 9732 row: [9732]
col: 9735 similar rows:  [9735]
11111111111111111111
incomplete name 3, col: 9735 row: []
col: 9736 similar rows:  [9736]
11111111111111111111
incomplete name 3, col: 9736 row: []
col: 9737 similar rows:  [9737]
11111111111111111111
incomplete name 3, col: 9737 row: []
col: 9738 similar rows:  [9738]
11111111111111111111
incomplete name 3, col: 9738 row: []
col: 9739 similar rows:  [9739]
11111111111111111111
hotelname2 [9739]
incomplete name 3, col: 9739 row: [9739]
col: 9740 similar rows:  [9740]
11111111111111111111
incomplete name 3, col: 9740 row: []
col: 9744 similar rows:  [9744]
11111111111111111111
incomplete name 3, col: 9744 row: []
col: 9745 similar rows:  [9745]
11111111111111111111
incomplete name 3, col: 9745 row: []
col: 9746 similar rows:  [9746]
11111111111111111111
incomplete name 3, col: 9746 row: []
col: 9755 similar rows:  [9755]
11111111111111111111
hotelname2 [9755]
incomplete name 3, col: 9755 row: [9755]
col: 9761 similar rows:  [9761]
11111111111111111111
incomplete name 3, col: 9761 row: []
col: 9765 similar rows:  [9765]
11111111111111111111
incomplete name 3, col: 9765 row: []
col: 9783 similar rows:  [9783]
11111111111111111111
incomplete name 3, col: 9783 row: []
col: 9788 similar rows:  [9788]
11111111111111111111
incomplete name 3, col: 9788 row: []
col: 9791 similar rows:  [9791]
11111111111111111111
incomplete name 3, col: 9791 row: []
col: 9794 similar rows:  [9794]
11111111111111111111
incomplete name 3, col: 9794 row: []
col: 9798 similar rows:  [9798]
11111111111111111111
incomplete name 3, col: 9798 row: []
col: 9799 similar rows:  [9799]
11111111111111111111
incomplete name 3, col: 9799 row: []
col: 9801 similar rows:  [9801]
11111111111111111111
incomplete name 3, col: 9801 row: []
col: 9802 similar rows:  [9802, 10003, 10061]
incomplete name 3, col: 9802 row: []
col: 9803 similar rows:  [9803, 9973]
incomplete name 3, col: 9803 row: []
col: 9807 similar rows:  [9807, 9808, 10006]
incomplete name 3, col: 9807 row: []
col: 9813 similar rows:  [9813]
11111111111111111111
incomplete name 3, col: 9813 row: []
col: 9815 similar rows:  [9815]
11111111111111111111
incomplete name 3, col: 9815 row: []
col: 9818 similar rows:  [9818, 9901]
incomplete name 3, col: 9818 row: []
col: 9820 similar rows:  [9820]
11111111111111111111
incomplete name 3, col: 9820 row: []
col: 9821 similar rows:  [9821]
11111111111111111111
incomplete name 3, col: 9821 row: []
col: 9822 similar rows:  [9822]
11111111111111111111
incomplete name 3, col: 9822 row: []
col: 9823 similar rows:  [9823]
11111111111111111111
incomplete name 3, col: 9823 row: []
col: 9825 similar rows:  [9825]
11111111111111111111
incomplete name 3, col: 9825 row: []
col: 9828 similar rows:  [9828]
11111111111111111111
incomplete name 3, col: 9828 row: []
col: 9829 similar rows:  [9829]
11111111111111111111
incomplete name 3, col: 9829 row: []
col: 9830 similar rows:  [9830]
11111111111111111111
incomplete name 3, col: 9830 row: []
col: 9832 similar rows:  [9832]
11111111111111111111
hotelname2 [9832]
incomplete name 3, col: 9832 row: [9832]
col: 9834 similar rows:  [9834]
11111111111111111111
incomplete name 3, col: 9834 row: []
col: 9837 similar rows:  [9837]
11111111111111111111
hotelname2 [9837]
incomplete name 3, col: 9837 row: [9837]
col: 9838 similar rows:  [9838]
11111111111111111111
incomplete name 3, col: 9838 row: []
col: 9839 similar rows:  [9839]
11111111111111111111
hotelname2 [9839]
incomplete name 3, col: 9839 row: [9839]
col: 9843 similar rows:  [9843]
11111111111111111111
incomplete name 3, col: 9843 row: []
col: 9845 similar rows:  [9845]
11111111111111111111
hotelname2 [9845]
incomplete name 3, col: 9845 row: [9845]
col: 9849 similar rows:  [9849]
11111111111111111111
hotelname2 [9849]
incomplete name 3, col: 9849 row: [9849]
col: 9850 similar rows:  [9850]
11111111111111111111
hotelname2 [9850]
incomplete name 3, col: 9850 row: []

col: 9858 similar rows:  [9858]
11111111111111111111
hotelname2 [9858]
incomplete name 3, col: 9858 row: []
col: 9859 similar rows:  [9859]
11111111111111111111
incomplete name 3, col: 9859 row: []
col: 9860 similar rows:  [9860]
11111111111111111111
hotelname2 [9860]
incomplete name 3, col: 9860 row: [9860]
col: 9861 similar rows:  [9861]
11111111111111111111
hotelname2 [9861]
incomplete name 3, col: 9861 row: [9861]
col: 9862 similar rows:  [9862, 10013]
incomplete name 3, col: 9862 row: []
col: 9869 similar rows:  [9869]
11111111111111111111
incomplete name 3, col: 9869 row: []
col: 9874 similar rows:  [9874]
11111111111111111111
incomplete name 3, col: 9874 row: []
col: 9886 similar rows:  [9886]
11111111111111111111
incomplete name 3, col: 9886 row: []
col: 9887 similar rows:  [9887]
11111111111111111111
hotelname2 [9887]
incomplete name 3, col: 9887 row: [9887]
col: 9888 similar rows:  [9888]
11111111111111111111
incomplete name 3, col: 9888 row: []
col: 9897 similar rows:  [9897]
11111111111111111111
incomplete name 3, col: 9897 row: []
col: 9898 similar rows:  [9898]
11111111111111111111
incomplete name 3, col: 9898 row: []
col: 9899 similar rows:  [9899]
11111111111111111111
incomplete name 3, col: 9899 row: []
col: 9902 similar rows:  [9902]
11111111111111111111
incomplete name 3, col: 9902 row: []
col: 9903 similar rows:  [9903, 10216]
incomplete name 3, col: 9903 row: []
col: 9905 similar rows:  [9905]
11111111111111111111
incomplete name 3, col: 9905 row: []
col: 9906 similar rows:  [9906]
11111111111111111111
incomplete name 3, col: 9906 row: []
col: 9908 similar rows:  [9908, 10178]
incomplete name 3, col: 9908 row: []
col: 9916 similar rows:  [9916]
11111111111111111111
hotelname2 [9916]
incomplete name 3, col: 9916 row: [9916]
col: 9919 similar rows:  [9919]
11111111111111111111
incomplete name 3, col: 9919 row: []
col: 9922 similar rows:  [9922]
11111111111111111111
incomplete name 3, col: 9922 row: []
col: 9923 similar rows:  [9923, 9990]
incomplete name 3, col: 9923 row: []
col: 9926 similar rows:  [9926]
11111111111111111111
incomplete name 3, col: 9926 row: []
col: 9927 similar rows:  [9927]
11111111111111111111
incomplete name 3, col: 9927 row: []
col: 9928 similar rows:  [9928, 10181]
incomplete name 3, col: 9928 row: []
col: 9929 similar rows:  [9929]
11111111111111111111
incomplete name 3, col: 9929 row: []
col: 9931 similar rows:  [9931]
11111111111111111111
incomplete name 3, col: 9931 row: []
col: 9932 similar rows:  [9932]
11111111111111111111
incomplete name 3, col: 9932 row: []
col: 9934 similar rows:  [9934]
11111111111111111111
incomplete name 3, col: 9934 row: []
col: 9935 similar rows:  [9935]
11111111111111111111
incomplete name 3, col: 9935 row: []
col: 9936 similar rows:  [9936, 9937]
incomplete name 3, col: 9936 row: []
col: 9938 similar rows:  [9938]
11111111111111111111
incomplete name 3, col: 9938 row: []
col: 9939 similar rows:  [9939]
11111111111111111111
incomplete name 3, col: 9939 row: []
col: 9943 similar rows:  [9943]
11111111111111111111
incomplete name 3, col: 9943 row: []
col: 9944 similar rows:  [9944]
11111111111111111111
incomplete name 3, col: 9944 row: []
col: 9951 similar rows:  [9951]
11111111111111111111
hotelname2 [9951]
incomplete name 3, col: 9951 row: [9951]
col: 9952 similar rows:  [9952]
11111111111111111111
incomplete name 3, col: 9952 row: []
col: 9954 similar rows:  [9954]
11111111111111111111
incomplete name 3, col: 9954 row: []
col: 9955 similar rows:  [9955]
11111111111111111111
incomplete name 3, col: 9955 row: []
col: 9959 similar rows:  [9959]
11111111111111111111
incomplete name 3, col: 9959 row: []
col: 9965 similar rows:  [9965]
11111111111111111111
incomplete name 3, col: 9965 row: []
col: 9970 similar rows:  [9970]
11111111111111111111
incomplete name 3, col: 9970 row: []
col: 9972 similar rows:  [9972]
11111111111111111111
incomplete name 3, col: 9972 row: []
col: 9976 similar rows:  [9976]
11111111111111111111
incomplete name 3, col: 9976 row: []
col: 9978 similar rows:  [9978]
11111111111111111111
incomplete name 3, col: 9978 row: []
col: 9979 similar rows:  [9979]
11111111111111111111
hotelname2 [9979]
incomplete name 3, col: 9979 row: [9979]
col: 9980 similar rows:  [9980]
11111111111111111111
incomplete name 3, col: 9980 row: []
col: 9981 similar rows:  [9981]
11111111111111111111
hotelname2 [9981]
incomplete name 3, col: 9981 row: [9981]
col: 9982 similar rows:  [9982]
11111111111111111111
incomplete name 3, col: 9982 row: []
col: 9983 similar rows:  [9983]
11111111111111111111
hotelname2 [9983]
incomplete name 3, col: 9983 row: [9983]
col: 9984 similar rows:  [9984]
11111111111111111111
hotelname2 [9984]
incomplete name 3, col: 9984 row: []
col: 9985 similar rows:  [9985]
11111111111111111111
incomplete name 3, col: 9985 row: []
col: 9986 similar rows:  [9986]
11111111111111111111
incomplete name 3, col: 9986 row: []
col: 9987 similar rows:  [9987, 10060]
incomplete name 3, col: 9987 row: []
col: 9989 similar rows:  [9989]
11111111111111111111
incomplete name 3, col: 9989 row: []
col: 9998 similar rows:  [9998]
11111111111111111111
incomplete name 3, col: 9998 row: []
col: 10009 similar rows:  [10009]
11111111111111111111
hotelname2 [10009]
incomplete name 3, col: 10009 row: [10009]
col: 10019 similar rows:  [10019]
11111111111111111111
incomplete name 3, col: 10019 row: []
col: 10024 similar rows:  [10024]
11111111111111111111
incomplete name 3, col: 10024 row: []
col: 10026 similar rows:  [10026]
11111111111111111111
incomplete name 3, col: 10026 row: []
col: 10028 similar rows:  [10028]
11111111111111111111
incomplete name 3, col: 10028 row: []
col: 10029 similar rows:  [10029]
11111111111111111111
incomplete name 3, col: 10029 row: []
col: 10030 similar rows:  [10030]
11111111111111111111
hotelname2 [10030]
incomplete name 3, col: 10030 row: [10030]
col: 10033 similar rows:  [10033]
11111111111111111111
incomplete name 3, col: 10033 row: []
col: 10035 similar rows:  [10035]
11111111111111111111
incomplete name 3, col: 10035 row: []
col: 10036 similar rows:  [10036]
11111111111111111111
incomplete name 3, col: 10036 row: []
col: 10038 similar rows:  [10038]
11111111111111111111
incomplete name 3, col: 10038 row: []
col: 10044 similar rows:  [10044]
11111111111111111111
incomplete name 3, col: 10044 row: []
col: 10046 similar rows:  [10046]
11111111111111111111
incomplete name 3, col: 10046 row: []
col: 10047 similar rows:  [10047]
11111111111111111111
incomplete name 3, col: 10047 row: []
col: 10056 similar rows:  [10056]
11111111111111111111
incomplete name 3, col: 10056 row: []
col: 10057 similar rows:  [10057]
11111111111111111111
incomplete name 3, col: 10057 row: []
col: 10058 similar rows:  [10058]
11111111111111111111
incomplete name 3, col: 10058 row: []
col: 10059 similar rows:  [10059]
11111111111111111111
incomplete name 3, col: 10059 row: []
col: 10064 similar rows:  [10064]
11111111111111111111
incomplete name 3, col: 10064 row: []
col: 10069 similar rows:  [10069]
11111111111111111111
hotelname2 [10069]
incomplete name 3, col: 10069 row: []
col: 10071 similar rows:  [10071]
11111111111111111111
incomplete name 3, col: 10071 row: []
col: 10075 similar rows:  [10075]
11111111111111111111
incomplete name 3, col: 10075 row: []
col: 10079 similar rows:  [10079]
11111111111111111111
incomplete name 3, col: 10079 row: []
col: 10080 similar rows:  [10080]
11111111111111111111
incomplete name 3, col: 10080 row: []
col: 10083 similar rows:  [10083, 10160]
incomplete name 3, col: 10083 row: []
col: 10087 similar rows:  [10087]
11111111111111111111
incomplete name 3, col: 10087 row: []
col: 10089 similar rows:  [10089]
11111111111111111111
hotelname2 [10089]
incomplete name 3, col: 10089 row: [10089]
col: 10091 similar rows:  [10091]
11111111111111111111
incomplete name 3, col: 10091 row: []
col: 10093 similar rows:  [10093, 10099]
incomplete name 3, col: 10093 row: []
col: 10096 similar rows:  [10096]
11111111111111111111
incomplete name 3, col: 10096 row: []
col: 10100 similar rows:  [10100]
11111111111111111111
incomplete name 3, col: 10100 row: []
col: 10101 similar rows:  [10101]
11111111111111111111
hotelname2 [10101]
wrong name!!!!
incomplete name 3, col: 10101 row: [10101]

col: 10105 similar rows:  [10105]
11111111111111111111
incomplete name 3, col: 10105 row: []
col: 10106 similar rows:  [10106]
11111111111111111111
incomplete name 3, col: 10106 row: []
col: 10112 similar rows:  [10112]
11111111111111111111
incomplete name 3, col: 10112 row: []
col: 10117 similar rows:  [10117]
11111111111111111111
incomplete name 3, col: 10117 row: []
col: 10125 similar rows:  [10125]
11111111111111111111
incomplete name 3, col: 10125 row: []
col: 10126 similar rows:  [10126]
11111111111111111111
incomplete name 3, col: 10126 row: []
col: 10127 similar rows:  [10127]
11111111111111111111
incomplete name 3, col: 10127 row: []
col: 10129 similar rows:  [10129]
11111111111111111111
hotelname2 [10129]
incomplete name 3, col: 10129 row: []
col: 10135 similar rows:  [10135]
11111111111111111111
incomplete name 3, col: 10135 row: []
col: 10137 similar rows:  [10137]
11111111111111111111
incomplete name 3, col: 10137 row: []
col: 10139 similar rows:  [10139]
11111111111111111111
incomplete name 3, col: 10139 row: []
col: 10140 similar rows:  [10140]
11111111111111111111
incomplete name 3, col: 10140 row: []
col: 10141 similar rows:  [10141]
11111111111111111111
incomplete name 3, col: 10141 row: []
col: 10142 similar rows:  [10142]
11111111111111111111
incomplete name 3, col: 10142 row: []
col: 10148 similar rows:  [10148]
11111111111111111111
incomplete name 3, col: 10148 row: []
col: 10150 similar rows:  [10150]
11111111111111111111
hotelname2 [10150]
incomplete name 3, col: 10150 row: []
col: 10155 similar rows:  [10155, 10156]
incomplete name 3, col: 10155 row: []
col: 10161 similar rows:  [10161]
11111111111111111111
incomplete name 3, col: 10161 row: []
col: 10163 similar rows:  [10163]
11111111111111111111
incomplete name 3, col: 10163 row: []
col: 10164 similar rows:  [10164]
11111111111111111111
hotelname2 [10164]
wrong name!!!!
incomplete name 3, col: 10164 row: [10164]
col: 10166 similar rows:  [10166]
11111111111111111111
hotelname2 [10166]
incomplete name 3, col: 10166 row: [10166]
col: 10167 similar rows:  [10167]
11111111111111111111
incomplete name 3, col: 10167 row: []
col: 10168 similar rows:  [10168]
11111111111111111111
incomplete name 3, col: 10168 row: []
col: 10173 similar rows:  [10173]
11111111111111111111
hotelname2 [10173]
incomplete name 3, col: 10173 row: []
col: 10174 similar rows:  [10174]
11111111111111111111
incomplete name 3, col: 10174 row: []
col: 10180 similar rows:  [10180]
11111111111111111111
hotelname2 [10180]
incomplete name 3, col: 10180 row: [10180]
col: 10183 similar rows:  [10183]
11111111111111111111
incomplete name 3, col: 10183 row: []
col: 10184 similar rows:  [10184]
11111111111111111111
hotelname2 [10184]
incomplete name 3, col: 10184 row: [10184]
col: 10198 similar rows:  [10198]
11111111111111111111
incomplete name 3, col: 10198 row: []
col: 10199 similar rows:  [10199]
11111111111111111111
incomplete name 3, col: 10199 row: []
col: 10206 similar rows:  [10206]
11111111111111111111
incomplete name 3, col: 10206 row: []
col: 10209 similar rows:  [10209]
11111111111111111111
incomplete name 3, col: 10209 row: []
col: 10210 similar rows:  [10210]
11111111111111111111
incomplete name 3, col: 10210 row: []
col: 10213 similar rows:  [10213]
11111111111111111111
incomplete name 3, col: 10213 row: []
col: 10218 similar rows:  [10218]
11111111111111111111
incomplete name 3, col: 10218 row: []
col: 10221 similar rows:  [10221]
11111111111111111111
incomplete name 3, col: 10221 row: []
col: 10222 similar rows:  [10222]
11111111111111111111
incomplete name 3, col: 10222 row: []
col: 10224 similar rows:  [10224]
11111111111111111111
incomplete name 3, col: 10224 row: []
col: 10225 similar rows:  [10225]
11111111111111111111
incomplete name 3, col: 10225 row: []
col: 10226 similar rows:  [10226]
11111111111111111111
incomplete name 3, col: 10226 row: []
end
col: 10228 similar rows:  [10228, 10658, 11289, 12159, 12818, 12841, 13078]
incomplete name 3, col: 10228 row: []
col: 10229 similar rows:  [10229, 11204, 11285, 12546, 12775, 12782, 13197]
incomplete name 3, col: 10229 row: []
col: 10230 similar rows:  [10230, 10325]
incomplete name 3, col: 10230 row: []
col: 10231 similar rows:  [10231]
11111111111111111111
incomplete name 3, col: 10231 row: []
col: 10232 similar rows:  [10232, 13008]
incomplete name 3, col: 10232 row: []
col: 10233 similar rows:  [10233, 10624, 11763, 12487, 12592]
incomplete name 3, col: 10233 row: []
col: 10234 similar rows:  [10234, 11579]
incomplete name 3, col: 10234 row: []
col: 10235 similar rows:  [10235, 10310, 10433, 10780, 10883, 11006, 11231, 11332, 11345, 11514, 11614, 11714, 11806, 11833, 11859, 11865, 11895, 12046, 12310, 12334, 12946, 12986]
incomplete name 3, col: 10235 row: []
col: 10236 similar rows:  [10236, 11239, 11481, 11515, 11588, 11907, 11908, 11915, 12045, 12281, 12317, 12458, 12470, 12536, 13107, 13218]
incomplete name 3, col: 10236 row: []
col: 10237 similar rows:  [10237, 11595, 11603]
incomplete name 3, col: 10237 row: []
col: 10238 similar rows:  [10238, 11489, 11490, 11491, 12237]
incomplete name 3, col: 10238 row: []
col: 10239 similar rows:  [10239, 10247, 10866, 11184, 11468, 12251, 12449, 12734, 12954]
incomplete name 3, col: 10239 row: []
col: 10240 similar rows:  [10240, 12249]
incomplete name 3, col: 10240 row: []
col: 10241 similar rows:  [10241]
11111111111111111111
incomplete name 3, col: 10241 row: []
col: 10242 similar rows:  [10242]
11111111111111111111
incomplete name 3, col: 10242 row: []
col: 10243 similar rows:  [10243]
11111111111111111111
incomplete name 3, col: 10243 row: []
col: 10244 similar rows:  [10244]
11111111111111111111
incomplete name 3, col: 10244 row: []
col: 10245 similar rows:  [10245, 12406, 12711]
incomplete name 3, col: 10245 row: []
col: 10246 similar rows:  [10246, 11150, 11349, 12664, 13162]
incomplete name 3, col: 10246 row: []
col: 10248 similar rows:  [10248, 11352, 13161]
incomplete name 3, col: 10248 row: []
col: 10249 similar rows:  [10249, 11101, 12534]
incomplete name 3, col: 10249 row: []
col: 10250 similar rows:  [10250, 10251, 10261, 10266, 10268, 10411, 10422, 10713, 11267, 11389, 12489]
incomplete name 3, col: 10250 row: []
col: 10252 similar rows:  [10252, 10308, 10450, 10563, 10595, 11125, 11740, 11793, 11924, 11960, 11968, 12160, 12655, 12683, 12759, 12963, 13087]
incomplete name 3, col: 10252 row: []
col: 10253 similar rows:  [10253, 11463]
incomplete name 3, col: 10253 row: []
col: 10254 similar rows:  [10254, 10567]
incomplete name 3, col: 10254 row: []
col: 10255 similar rows:  [10255, 11606, 12933, 13072]
incomplete name 3, col: 10255 row: []
col: 10256 similar rows:  [10256, 10267, 10868, 10869, 12013, 12153]
incomplete name 3, col: 10256 row: []
col: 10257 similar rows:  [10257, 12806]
incomplete name 3, col: 10257 row: []
col: 10258 similar rows:  [10258, 10564, 11695]
incomplete name 3, col: 10258 row: []
col: 10259 similar rows:  [10259]
11111111111111111111
incomplete name 3, col: 10259 row: []
col: 10260 similar rows:  [10260]
11111111111111111111
incomplete name 3, col: 10260 row: []
col: 10262 similar rows:  [10262, 10688, 11283, 12192, 12327]
incomplete name 3, col: 10262 row: []
col: 10263 similar rows:  [10263, 12233]
incomplete name 3, col: 10263 row: []
col: 10264 similar rows:  [10264, 11770]
incomplete name 3, col: 10264 row: []
col: 10265 similar rows:  [10265, 10380, 10657, 10755, 10832, 10840, 10847, 10860, 11616, 12615, 12617, 12779, 13023, 13027, 13106, 13142, 13189]
incomplete name 3, col: 10265 row: []
col: 10269 similar rows:  [10269, 11771, 12106, 12632, 12676, 12925]
incomplete name 3, col: 10269 row: []
col: 10270 similar rows:  [10270]
11111111111111111111
incomplete name 3, col: 10270 row: []
col: 10271 similar rows:  [10271, 10709, 11525, 12678, 12896, 12910, 13139]
incomplete name 3, col: 10271 row: []
col: 10272 similar rows:  [10272, 13132]
incomplete name 3, col: 10272 row: []
col: 10273 similar rows:  [10273]
11111111111111111111
incomplete name 3, col: 10273 row: []
col: 10274 similar rows:  [10274, 12846]
incomplete name 3, col: 10274 row: []
col: 10275 similar rows:  [10275, 12124]
incomplete name 3, col: 10275 row: []
col: 10276 similar rows:  [10276]
11111111111111111111
incomplete name 3, col: 10276 row: []
col: 10277 similar rows:  [10277]
11111111111111111111
incomplete name 3, col: 10277 row: []
col: 10278 similar rows:  [10278, 10965, 11022, 12943]
incomplete name 3, col: 10278 row: []
col: 10279 similar rows:  [10279]
11111111111111111111
incomplete name 3, col: 10279 row: []
col: 10280 similar rows:  [10280, 10281, 12903]
incomplete name 3, col: 10280 row: []
col: 10282 similar rows:  [10282]
11111111111111111111
incomplete name 3, col: 10282 row: []

col: 10283 similar rows:  [10283, 10417, 10913, 10994, 11665]
incomplete name 3, col: 10283 row: []
col: 10284 similar rows:  [10284, 10318, 11064, 11227, 11792, 11794, 11797, 11807, 11979, 12059, 12694, 12699, 13028]
incomplete name 3, col: 10284 row: []
col: 10285 similar rows:  [10285, 12528]
incomplete name 3, col: 10285 row: []
col: 10286 similar rows:  [10286, 11678]
incomplete name 3, col: 10286 row: []
col: 10287 similar rows:  [10287]
11111111111111111111
incomplete name 3, col: 10287 row: []
col: 10288 similar rows:  [10288, 10922, 11767]
incomplete name 3, col: 10288 row: []
col: 10289 similar rows:  [10289, 10438, 10578, 10676, 10937, 11989, 12295, 12837]
incomplete name 3, col: 10289 row: []
col: 10290 similar rows:  [10290]
11111111111111111111
incomplete name 3, col: 10290 row: []
col: 10291 similar rows:  [10291, 10405, 10469, 10896, 10898, 11650, 11978, 12301, 12749]
incomplete name 3, col: 10291 row: []
col: 10292 similar rows:  [10292, 11542, 12270, 12297, 12308, 12346, 12501, 12687, 12688]
incomplete name 3, col: 10292 row: []
col: 10293 similar rows:  [10293]
11111111111111111111
incomplete name 3, col: 10293 row: []
col: 10294 similar rows:  [10294]
11111111111111111111
incomplete name 3, col: 10294 row: []
col: 10295 similar rows:  [10295, 11020, 11038, 11803, 11829, 11831, 11910, 11982, 12012, 12352, 12393, 12832]
incomplete name 3, col: 10295 row: []
col: 10296 similar rows:  [10296]
11111111111111111111
incomplete name 3, col: 10296 row: []
col: 10297 similar rows:  [10297, 10845]
incomplete name 3, col: 10297 row: []
col: 10298 similar rows:  [10298]
11111111111111111111
incomplete name 3, col: 10298 row: []
col: 10299 similar rows:  [10299, 10712]
incomplete name 3, col: 10299 row: []
col: 10300 similar rows:  [10300]
11111111111111111111
incomplete name 3, col: 10300 row: []
col: 10301 similar rows:  [10301, 12477]
incomplete name 3, col: 10301 row: []
col: 10302 similar rows:  [10302, 10439, 10638, 11118, 11131, 11203, 11684, 12014, 13031, 13158, 13205, 13225]
incomplete name 3, col: 10302 row: []
col: 10303 similar rows:  [10303]
11111111111111111111
incomplete name 3, col: 10303 row: []
col: 10304 similar rows:  [10304, 10523, 10527, 10612, 10969, 11152, 11223, 11269, 11406, 11697, 12029, 12056, 12058, 12629, 12787]
incomplete name 3, col: 10304 row: []
col: 10305 similar rows:  [10305]
11111111111111111111
incomplete name 3, col: 10305 row: []
col: 10306 similar rows:  [10306, 10353, 11344, 12370, 12472, 12725, 13046, 13061, 13067]
incomplete name 3, col: 10306 row: []
col: 10307 similar rows:  [10307, 10454, 10475, 10870, 10905, 10966, 11010, 11035, 11054, 11111, 11420, 11530, 11587, 11715, 11796, 11848, 11917, 12294, 12455, 12491, 12492, 12647, 12883, 12906, 12982, 12984, 13086, 13207]
incomplete name 3, col: 10307 row: []
col: 10309 similar rows:  [10309]
11111111111111111111
incomplete name 3, col: 10309 row: []
col: 10311 similar rows:  [10311, 11286]
incomplete name 3, col: 10311 row: []
col: 10312 similar rows:  [10312, 13130]
incomplete name 3, col: 10312 row: []
col: 10313 similar rows:  [10313]
11111111111111111111
incomplete name 3, col: 10313 row: []
col: 10314 similar rows:  [10314, 13066]
incomplete name 3, col: 10314 row: []
col: 10315 similar rows:  [10315, 10600, 11259, 11412]
incomplete name 3, col: 10315 row: []
col: 10316 similar rows:  [10316, 10402, 10560, 10574, 10945, 10958, 10964, 11212, 11664, 11967, 11997, 12077, 12125, 12173, 12631, 12636, 12729]
incomplete name 3, col: 10316 row: []
col: 10317 similar rows:  [10317, 11070, 11415, 11446]
incomplete name 3, col: 10317 row: []
col: 10319 similar rows:  [10319]
11111111111111111111
incomplete name 3, col: 10319 row: []
col: 10320 similar rows:  [10320]
11111111111111111111
hotelname2 [10320]
wrong name!!!!
incomplete name 3, col: 10320 row: [10320]
col: 10321 similar rows:  [10321, 11971]
incomplete name 3, col: 10321 row: []
col: 10322 similar rows:  [10322]
11111111111111111111
incomplete name 3, col: 10322 row: []
col: 10323 similar rows:  [10323, 10440, 11329, 12296, 12331, 12333, 12977, 13211]
incomplete name 3, col: 10323 row: []
col: 10324 similar rows:  [10324, 11579]
incomplete name 3, col: 10324 row: []
col: 10326 similar rows:  [10326, 10766, 12057]
incomplete name 3, col: 10326 row: []
col: 10327 similar rows:  [10327, 10361, 10810, 10978]
incomplete name 3, col: 10327 row: []
col: 10328 similar rows:  [10328, 11347]
incomplete name 3, col: 10328 row: []
col: 10329 similar rows:  [10329]
11111111111111111111
incomplete name 3, col: 10329 row: []
col: 10330 similar rows:  [10330]
11111111111111111111
incomplete name 3, col: 10330 row: []
col: 10331 similar rows:  [10331, 10956]
incomplete name 3, col: 10331 row: []
col: 10332 similar rows:  [10332, 10754, 10983, 11306, 11316, 11320, 11443, 11586, 11602, 11608, 11996, 13054, 13090, 13095]
incomplete name 3, col: 10332 row: []
col: 10333 similar rows:  [10333]
11111111111111111111
incomplete name 3, col: 10333 row: []
col: 10334 similar rows:  [10334, 10552, 10786, 12238, 12517]
incomplete name 3, col: 10334 row: []
col: 10335 similar rows:  [10335]
11111111111111111111
incomplete name 3, col: 10335 row: []
col: 10336 similar rows:  [10336, 10557, 10696, 10795, 10797, 10877, 11133, 11307, 11371, 11457, 11520, 11550, 11703, 12266, 12300, 12302, 12320, 12342, 12343, 12643, 12713, 12741, 12823, 12886, 12908, 12973, 13045, 13074, 13075, 13157]
incomplete name 3, col: 10336 row: []
col: 10337 similar rows:  [10337, 11881, 12385]
incomplete name 3, col: 10337 row: []
col: 10338 similar rows:  [10338, 11718]
incomplete name 3, col: 10338 row: []
col: 10339 similar rows:  [10339, 10662, 11452, 12277, 12304, 12847]
incomplete name 3, col: 10339 row: []
col: 10340 similar rows:  [10340]
11111111111111111111
incomplete name 3, col: 10340 row: []
col: 10341 similar rows:  [10341]
11111111111111111111
incomplete name 3, col: 10341 row: []
col: 10342 similar rows:  [10342, 11321, 11524, 12052, 12635, 12693, 13091]
incomplete name 3, col: 10342 row: []
col: 10343 similar rows:  [10343]
11111111111111111111
incomplete name 3, col: 10343 row: []
col: 10344 similar rows:  [10344, 10656, 11617, 12757]
incomplete name 3, col: 10344 row: []
col: 10345 similar rows:  [10345, 11018, 12117, 12293, 12674, 12723]
incomplete name 3, col: 10345 row: []
col: 10346 similar rows:  [10346, 11677, 11783, 12710, 12726]
incomplete name 3, col: 10346 row: []
col: 10347 similar rows:  [10347, 10354, 10879, 12312, 12860]
incomplete name 3, col: 10347 row: []
col: 10348 similar rows:  [10348]
11111111111111111111
incomplete name 3, col: 10348 row: []
col: 10349 similar rows:  [10349, 12071, 12521]
incomplete name 3, col: 10349 row: []
col: 10350 similar rows:  [10350]
11111111111111111111
hotelname2 [10350]
incomplete name 3, col: 10350 row: [10350]
col: 10351 similar rows:  [10351, 10549, 10645]
incomplete name 3, col: 10351 row: []
col: 10352 similar rows:  [10352, 11913]
incomplete name 3, col: 10352 row: []
col: 10355 similar rows:  [10355, 10597, 10622, 10752, 10971, 11292, 11526, 11558, 11638, 11647, 11834, 11961, 12269, 12314, 12505, 12555, 12817]
incomplete name 3, col: 10355 row: []
col: 10356 similar rows:  [10356]
11111111111111111111
incomplete name 3, col: 10356 row: []
col: 10357 similar rows:  [10357, 12243, 12665]
incomplete name 3, col: 10357 row: []
col: 10358 similar rows:  [10358]
11111111111111111111
incomplete name 3, col: 10358 row: []
col: 10359 similar rows:  [10359, 10625, 11313]
incomplete name 3, col: 10359 row: []
col: 10360 similar rows:  [10360, 11114, 11912]
incomplete name 3, col: 10360 row: []
col: 10362 similar rows:  [10362]
11111111111111111111
incomplete name 3, col: 10362 row: []
col: 10363 similar rows:  [10363, 13115]
incomplete name 3, col: 10363 row: []
col: 10364 similar rows:  [10364, 12696, 12857]
incomplete name 3, col: 10364 row: []
col: 10365 similar rows:  [10365, 11454]
incomplete name 3, col: 10365 row: []
col: 10366 similar rows:  [10366]
11111111111111111111
incomplete name 3, col: 10366 row: []
col: 10367 similar rows:  [10367]
11111111111111111111
incomplete name 3, col: 10367 row: []
col: 10368 similar rows:  [10368, 11260, 11418, 11929, 12526]
incomplete name 3, col: 10368 row: []
col: 10369 similar rows:  [10369]
11111111111111111111
incomplete name 3, col: 10369 row: []
col: 10370 similar rows:  [10370]
11111111111111111111
hotelname2 [10370]
incomplete name 3, col: 10370 row: [10370]
col: 10371 similar rows:  [10371, 11069, 11370, 11402, 11408, 11501, 11950, 12146, 12162, 12282, 12329, 12341, 12365, 12524, 12622, 12894, 12952, 13144, 13160, 13182]
incomplete name 3, col: 10371 row: []

col: 10372 similar rows:  [10372, 10429, 10471, 10555, 10900, 11014, 11037, 11105, 11789, 11837, 11876, 12453, 12706]
incomplete name 3, col: 10372 row: []
col: 10373 similar rows:  [10373, 10395, 10499, 11655, 12614, 12618]
incomplete name 3, col: 10373 row: []
col: 10374 similar rows:  [10374, 10384, 11639]
incomplete name 3, col: 10374 row: []
col: 10375 similar rows:  [10375, 10376, 11818]
incomplete name 3, col: 10375 row: []
col: 10377 similar rows:  [10377, 10718, 10816, 10930, 11738, 11790, 11844, 11902, 12032, 12309, 12452, 12850, 13000, 13041]
incomplete name 3, col: 10377 row: []
col: 10378 similar rows:  [10378, 10436, 12623, 12651, 12844, 13040]
incomplete name 3, col: 10378 row: []
col: 10379 similar rows:  [10379, 12625]
incomplete name 3, col: 10379 row: []
col: 10381 similar rows:  [10381, 10382, 10400, 10458, 10505, 10547, 10652, 10683, 10904, 11008, 11045, 11046, 11068, 11082, 11175, 11387, 11480, 11610, 11630, 11973, 12321, 12478, 12498, 12507, 12744, 12902, 12915, 13143]
incomplete name 3, col: 10381 row: []
col: 10383 similar rows:  [10383, 10444, 10917, 11985, 12375, 12446, 12525, 12549, 12971, 13171, 13204]
incomplete name 3, col: 10383 row: []
col: 10385 similar rows:  [10385, 10862, 10968, 11122, 11194, 12001, 12380, 12835, 12942]
incomplete name 3, col: 10385 row: []
col: 10386 similar rows:  [10386, 10461, 10660, 10722, 10859, 10897, 11538, 11570, 11584, 11628, 11799, 11811, 11826, 11839, 11854, 11855, 11869, 11914, 12396, 12465, 12531, 12645, 12824, 12827, 12830, 12853, 12876, 12922, 12938]
incomplete name 3, col: 10386 row: []
col: 10387 similar rows:  [10387, 11379, 11444, 12454, 12931]
incomplete name 3, col: 10387 row: []
col: 10388 similar rows:  [10388, 10943, 11146, 12438, 13190]
incomplete name 3, col: 10388 row: []
col: 10389 similar rows:  [10389, 10577, 10745, 11710, 12010, 12037, 12113]
incomplete name 3, col: 10389 row: []
col: 10390 similar rows:  [10390, 10392, 11774]
incomplete name 3, col: 10390 row: []
col: 10391 similar rows:  [10391, 11056, 12105, 12115]
incomplete name 3, col: 10391 row: []
col: 10393 similar rows:  [10393, 10462, 10802, 11327, 11868, 11922, 11951, 12224]
incomplete name 3, col: 10393 row: []
col: 10394 similar rows:  [10394, 10584, 11423, 11643, 11675, 11680, 11757, 12377, 12715, 12795, 12945, 12988, 13124]
incomplete name 3, col: 10394 row: []
col: 10396 similar rows:  [10396, 12195]
incomplete name 3, col: 10396 row: []
col: 10397 similar rows:  [10397]
11111111111111111111
hotelname2 [10397]
incomplete name 3, col: 10397 row: [10397]
col: 10398 similar rows:  [10398]
11111111111111111111
incomplete name 3, col: 10398 row: []
col: 10399 similar rows:  [10399, 10437, 11281, 11521, 12291, 12855]
incomplete name 3, col: 10399 row: []
col: 10401 similar rows:  [10401, 10414, 10833, 10854, 10861, 10985, 10996, 11003, 11028, 11155, 11288, 11433, 11739, 12459, 12471, 12904, 12958, 13024]
incomplete name 3, col: 10401 row: []
col: 10403 similar rows:  [10403, 12055]
incomplete name 3, col: 10403 row: []
col: 10404 similar rows:  [10404, 10933]
incomplete name 3, col: 10404 row: []
col: 10406 similar rows:  [10406, 10514, 11001, 11791]
incomplete name 3, col: 10406 row: []
col: 10407 similar rows:  [10407, 10465, 10467, 10473, 10474, 10495, 10666, 10998, 11200, 11354, 11551, 11668, 11842, 11992, 12008, 12275, 12804]
incomplete name 3, col: 10407 row: []
col: 10408 similar rows:  [10408, 10583, 11634, 11659, 12127]
incomplete name 3, col: 10408 row: []
col: 10409 similar rows:  [10409]
11111111111111111111
incomplete name 3, col: 10409 row: []
col: 10410 similar rows:  [10410, 12313]
incomplete name 3, col: 10410 row: []
col: 10412 similar rows:  [10412]
11111111111111111111
incomplete name 3, col: 10412 row: []
col: 10413 similar rows:  [10413, 10477, 10498, 10675, 10841, 10929, 11095, 11334, 11641, 11778, 12027, 12120, 12389, 12882, 13209]
incomplete name 3, col: 10413 row: []
col: 10415 similar rows:  [10415, 10573, 10707, 10761, 11429, 11533, 11536, 11548, 11824, 12213, 12298, 12338, 12347, 12576, 12854, 12928, 13159]
incomplete name 3, col: 10415 row: []
col: 10416 similar rows:  [10416, 10857, 11002, 11120, 11151, 11290, 11669, 12701, 12940]
incomplete name 3, col: 10416 row: []
col: 10418 similar rows:  [10418, 10677, 10990, 11258, 11637, 11685, 12171, 12731, 13153, 13188]
incomplete name 3, col: 10418 row: []
col: 10419 similar rows:  [10419, 12802]
incomplete name 3, col: 10419 row: []
col: 10420 similar rows:  [10420]
11111111111111111111
incomplete name 3, col: 10420 row: []
col: 10421 similar rows:  [10421]
11111111111111111111
incomplete name 3, col: 10421 row: []
col: 10423 similar rows:  [10423, 10909, 12773]
incomplete name 3, col: 10423 row: []
col: 10424 similar rows:  [10424, 11365]
incomplete name 3, col: 10424 row: []
col: 10425 similar rows:  [10425]
11111111111111111111
incomplete name 3, col: 10425 row: []
col: 10426 similar rows:  [10426, 10619, 12905, 12936]
incomplete name 3, col: 10426 row: []
col: 10427 similar rows:  [10427, 10808, 10849, 11044, 11075, 11390, 11449, 12152, 12247, 12250, 12345, 12523, 12559, 12662, 12668, 12842, 12858]
incomplete name 3, col: 10427 row: []
col: 10428 similar rows:  [10428, 10692, 10728, 10888, 10916, 10959, 11136, 11167, 11272, 11303, 11574, 13145]
incomplete name 3, col: 10428 row: []
col: 10430 similar rows:  [10430, 10512, 10671, 10901, 13129]
incomplete name 3, col: 10430 row: []
col: 10431 similar rows:  [10431, 10589, 10921, 11012, 11964, 12670, 12681, 12961]
incomplete name 3, col: 10431 row: []
col: 10432 similar rows:  [10432, 11543, 12780, 13215]
incomplete name 3, col: 10432 row: []
col: 10434 similar rows:  [10434, 10954, 12123]
incomplete name 3, col: 10434 row: []
col: 10435 similar rows:  [10435, 11034, 11129, 11670]
incomplete name 3, col: 10435 row: []
col: 10441 similar rows:  [10441, 10938, 11280]
incomplete name 3, col: 10441 row: []
col: 10442 similar rows:  [10442]
11111111111111111111
hotelname2 [10442]
incomplete name 3, col: 10442 row: [10442]
col: 10443 similar rows:  [10443, 11017, 12372, 12897]
incomplete name 3, col: 10443 row: []
col: 10445 similar rows:  [10445, 12803]
incomplete name 3, col: 10445 row: []
col: 10446 similar rows:  [10446, 10453, 11140, 12000, 12007, 12268, 12355, 12414]
incomplete name 3, col: 10446 row: []
col: 10447 similar rows:  [10447]
11111111111111111111
incomplete name 3, col: 10447 row: []
col: 10448 similar rows:  [10448, 12424]
incomplete name 3, col: 10448 row: []
col: 10449 similar rows:  [10449]
11111111111111111111
incomplete name 3, col: 10449 row: []
col: 10451 similar rows:  [10451, 11236, 11310]
incomplete name 3, col: 10451 row: []
col: 10452 similar rows:  [10452, 12075]
incomplete name 3, col: 10452 row: []
col: 10455 similar rows:  [10455, 10817, 10924, 10947, 11988]
incomplete name 3, col: 10455 row: []
col: 10456 similar rows:  [10456, 11531, 12939]
incomplete name 3, col: 10456 row: []
col: 10457 similar rows:  [10457, 11315, 11325, 11657]
incomplete name 3, col: 10457 row: []
col: 10459 similar rows:  [10459, 10492, 11107]
incomplete name 3, col: 10459 row: []
col: 10460 similar rows:  [10460, 10485, 10926, 12004, 12707, 12956]
incomplete name 3, col: 10460 row: []
col: 10463 similar rows:  [10463]
11111111111111111111
incomplete name 3, col: 10463 row: []
col: 10464 similar rows:  [10464, 10497, 11015, 11190, 11262, 11662, 12157, 12405, 12496, 13187]
incomplete name 3, col: 10464 row: []
col: 10466 similar rows:  [10466, 11106, 11777, 12724]
incomplete name 3, col: 10466 row: []
col: 10468 similar rows:  [10468, 10490, 10493, 10575, 10976, 11013, 11088, 11660, 12646]
incomplete name 3, col: 10468 row: []
col: 10470 similar rows:  [10470, 11086, 11093, 11147, 11544, 11696, 11940, 12129, 12288, 12768]
incomplete name 3, col: 10470 row: []
col: 10472 similar rows:  [10472, 10766, 11009, 12057]
incomplete name 3, col: 10472 row: []
col: 10476 similar rows:  [10476, 10520, 10548, 10682, 10767, 10835, 11252, 11986, 12428, 12763, 12871, 13030]
incomplete name 3, col: 10476 row: []
col: 10478 similar rows:  [10478, 10503, 10908, 10939, 10983, 11036, 11532, 11823, 12373, 12672, 12833, 13048]
incomplete name 3, col: 10478 row: []
col: 10479 similar rows:  [10479]
11111111111111111111
incomplete name 3, col: 10479 row: []
col: 10480 similar rows:  [10480, 11138, 11688, 12419, 13104]
incomplete name 3, col: 10480 row: []

col: 10481 similar rows:  [10481, 10891, 12161, 12633]
incomplete name 3, col: 10481 row: []
col: 10482 similar rows:  [10482, 11177, 11216, 11841, 12065, 12148, 12513, 12791, 12923]
incomplete name 3, col: 10482 row: []
col: 10483 similar rows:  [10483, 10826, 10872, 11025, 11376, 11469, 11728, 11735, 11802, 12461, 12831, 12862, 13137]
incomplete name 3, col: 10483 row: []
col: 10484 similar rows:  [10484]
11111111111111111111
incomplete name 3, col: 10484 row: []
col: 10486 similar rows:  [10486, 12440]
incomplete name 3, col: 10486 row: []
col: 10487 similar rows:  [10487, 10582, 10876, 10906, 11109, 11142, 13039]
incomplete name 3, col: 10487 row: []
col: 10488 similar rows:  [10488]
11111111111111111111
incomplete name 3, col: 10488 row: []
col: 10489 similar rows:  [10489]
11111111111111111111
incomplete name 3, col: 10489 row: []
col: 10491 similar rows:  [10491, 11979]
incomplete name 3, col: 10491 row: []
col: 10494 similar rows:  [10494]
11111111111111111111
incomplete name 3, col: 10494 row: []
col: 10496 similar rows:  [10496]
11111111111111111111
incomplete name 3, col: 10496 row: []
col: 10500 similar rows:  [10500]
11111111111111111111
incomplete name 3, col: 10500 row: []
col: 10501 similar rows:  [10501]
11111111111111111111
incomplete name 3, col: 10501 row: []
col: 10502 similar rows:  [10502]
11111111111111111111
incomplete name 3, col: 10502 row: []
col: 10504 similar rows:  [10504, 10510, 11103, 11255]
incomplete name 3, col: 10504 row: []
col: 10506 similar rows:  [10506, 12303]
incomplete name 3, col: 10506 row: []
col: 10507 similar rows:  [10507, 10700, 10957, 11832, 12248, 13105, 13117]
incomplete name 3, col: 10507 row: []
col: 10508 similar rows:  [10508]
11111111111111111111
incomplete name 3, col: 10508 row: []
col: 10509 similar rows:  [10509]
11111111111111111111
incomplete name 3, col: 10509 row: []
col: 10511 similar rows:  [10511, 10664, 10668, 13043, 13057]
incomplete name 3, col: 10511 row: []
col: 10513 similar rows:  [10513]
11111111111111111111
incomplete name 3, col: 10513 row: []
col: 10515 similar rows:  [10515, 11938]
incomplete name 3, col: 10515 row: []
col: 10516 similar rows:  [10516, 11178, 11424, 11549, 12921]
incomplete name 3, col: 10516 row: []
col: 10517 similar rows:  [10517]
11111111111111111111
incomplete name 3, col: 10517 row: []
col: 10518 similar rows:  [10518, 11027, 12064, 12640, 12691]
incomplete name 3, col: 10518 row: []
col: 10519 similar rows:  [10519]
11111111111111111111
incomplete name 3, col: 10519 row: []
col: 10521 similar rows:  [10521, 10853, 11126, 11165, 11355, 11356, 12727]
incomplete name 3, col: 10521 row: []
col: 10522 similar rows:  [10522]
11111111111111111111
incomplete name 3, col: 10522 row: []
col: 10524 similar rows:  [10524, 12102]
incomplete name 3, col: 10524 row: []
col: 10525 similar rows:  [10525]
11111111111111111111
incomplete name 3, col: 10525 row: []
col: 10526 similar rows:  [10526]
11111111111111111111
incomplete name 3, col: 10526 row: []
col: 10528 similar rows:  [10528, 11674]
incomplete name 3, col: 10528 row: []
col: 10529 similar rows:  [10529]
11111111111111111111
incomplete name 3, col: 10529 row: []
col: 10530 similar rows:  [10530, 11631, 11815, 11958]
incomplete name 3, col: 10530 row: []
col: 10531 similar rows:  [10531]
11111111111111111111
incomplete name 3, col: 10531 row: []
col: 10532 similar rows:  [10532, 10590]
incomplete name 3, col: 10532 row: []
col: 10533 similar rows:  [10533]
11111111111111111111
incomplete name 3, col: 10533 row: []
col: 10534 similar rows:  [10534, 10991, 11207, 11357, 11627, 12349]
incomplete name 3, col: 10534 row: []
col: 10535 similar rows:  [10535, 10542, 10608, 11185, 11896, 12172, 12420]
incomplete name 3, col: 10535 row: []
col: 10536 similar rows:  [10536, 10993, 12926]
incomplete name 3, col: 10536 row: []
col: 10537 similar rows:  [10537]
11111111111111111111
incomplete name 3, col: 10537 row: []
col: 10538 similar rows:  [10538, 11644, 11901]
incomplete name 3, col: 10538 row: []
col: 10539 similar rows:  [10539, 11058]
incomplete name 3, col: 10539 row: []
col: 10540 similar rows:  [10540]
11111111111111111111
incomplete name 3, col: 10540 row: []
col: 10541 similar rows:  [10541, 11261, 11308, 11434]
incomplete name 3, col: 10541 row: []
col: 10543 similar rows:  [10543, 11423, 11757, 12988, 13124]
incomplete name 3, col: 10543 row: []
col: 10544 similar rows:  [10544]
11111111111111111111
hotelname2 [10544]
incomplete name 3, col: 10544 row: [10544]
col: 10545 similar rows:  [10545, 12025, 12752]
incomplete name 3, col: 10545 row: []
col: 10546 similar rows:  [10546, 12490]
incomplete name 3, col: 10546 row: []
col: 10550 similar rows:  [10550, 10606, 11465, 11580, 11699]
incomplete name 3, col: 10550 row: []
col: 10551 similar rows:  [10551, 10596, 11363, 11977, 12053, 12163, 12394, 12608]
incomplete name 3, col: 10551 row: []
col: 10553 similar rows:  [10553]
11111111111111111111
incomplete name 3, col: 10553 row: []
col: 10554 similar rows:  [10554]
11111111111111111111
incomplete name 3, col: 10554 row: []
col: 10556 similar rows:  [10556, 10706, 11143, 11661, 12139, 12774, 12888]
incomplete name 3, col: 10556 row: []
col: 10558 similar rows:  [10558, 11517, 12630]
incomplete name 3, col: 10558 row: []
col: 10559 similar rows:  [10559]
11111111111111111111
hotelname2 [10559]
incomplete name 3, col: 10559 row: []
col: 10561 similar rows:  [10561]
11111111111111111111
incomplete name 3, col: 10561 row: []
col: 10562 similar rows:  [10562]
11111111111111111111
incomplete name 3, col: 10562 row: []
col: 10565 similar rows:  [10565, 11241]
incomplete name 3, col: 10565 row: []
col: 10566 similar rows:  [10566, 11672, 11965, 12962, 13169]
incomplete name 3, col: 10566 row: []
col: 10568 similar rows:  [10568, 10747, 11019, 11081, 12028, 12245, 12332, 12722, 13020, 13220]
incomplete name 3, col: 10568 row: []
col: 10569 similar rows:  [10569, 12656, 12720]
incomplete name 3, col: 10569 row: []
col: 10570 similar rows:  [10570]
11111111111111111111
hotelname2 [10570]
incomplete name 3, col: 10570 row: [10570]
col: 10571 similar rows:  [10571]
11111111111111111111
incomplete name 3, col: 10571 row: []
col: 10572 similar rows:  [10572, 12475]
incomplete name 3, col: 10572 row: []
col: 10576 similar rows:  [10576, 10726]
incomplete name 3, col: 10576 row: []
col: 10579 similar rows:  [10579]
11111111111111111111
incomplete name 3, col: 10579 row: []
col: 10580 similar rows:  [10580, 10683, 11046, 11175, 11387, 12744]
incomplete name 3, col: 10580 row: []
col: 10581 similar rows:  [10581]
11111111111111111111
incomplete name 3, col: 10581 row: []
col: 10585 similar rows:  [10585]
11111111111111111111
incomplete name 3, col: 10585 row: []
col: 10586 similar rows:  [10586]
11111111111111111111
incomplete name 3, col: 10586 row: []
col: 10587 similar rows:  [10587]
11111111111111111111
incomplete name 3, col: 10587 row: []
col: 10588 similar rows:  [10588]
11111111111111111111
incomplete name 3, col: 10588 row: []
col: 10591 similar rows:  [10591]
11111111111111111111
hotelname2 [10591]
incomplete name 3, col: 10591 row: [10591]
col: 10592 similar rows:  [10592]
11111111111111111111
incomplete name 3, col: 10592 row: []
col: 10593 similar rows:  [10593]
11111111111111111111
incomplete name 3, col: 10593 row: []
col: 10594 similar rows:  [10594]
11111111111111111111
incomplete name 3, col: 10594 row: []
col: 10598 similar rows:  [10598, 11555]
incomplete name 3, col: 10598 row: []
col: 10599 similar rows:  [10599]
11111111111111111111
incomplete name 3, col: 10599 row: []
col: 10601 similar rows:  [10601]
11111111111111111111
incomplete name 3, col: 10601 row: []
col: 10602 similar rows:  [10602]
11111111111111111111
hotelname2 [10602]
incomplete name 3, col: 10602 row: [10602]
col: 10603 similar rows:  [10603]
11111111111111111111
hotelname2 [10603]
incomplete name 3, col: 10603 row: []
col: 10604 similar rows:  [10604, 11141, 11593]
incomplete name 3, col: 10604 row: []
col: 10605 similar rows:  [10605, 12503]
incomplete name 3, col: 10605 row: []
col: 10607 similar rows:  [10607]
11111111111111111111
incomplete name 3, col: 10607 row: []
col: 10609 similar rows:  [10609]
11111111111111111111
incomplete name 3, col: 10609 row: []
col: 10610 similar rows:  [10610, 11210, 11392, 12080, 12793]
incomplete name 3, col: 10610 row: []
col: 10611 similar rows:  [10611]
11111111111111111111
incomplete name 3, col: 10611 row: []
col: 10613 similar rows:  [10613, 10701, 10710, 10762, 11726, 12036, 12042, 12435, 12485, 12499, 12776, 13080, 13196]
incomplete name 3, col: 10613 row: []
col: 10614 similar rows:  [10614]
11111111111111111111
incomplete name 3, col: 10614 row: []

col: 10615 similar rows:  [10615, 10638, 11118, 11131, 11684, 12014, 13031, 13158, 13205, 13225]
incomplete name 3, col: 10615 row: []
col: 10616 similar rows:  [10616, 11743, 11945, 12597, 13116]
incomplete name 3, col: 10616 row: []
col: 10617 similar rows:  [10617]
11111111111111111111
incomplete name 3, col: 10617 row: []
col: 10618 similar rows:  [10618]
11111111111111111111
hotelname2 [10618]
incomplete name 3, col: 10618 row: [10618]
col: 10620 similar rows:  [10620, 10643, 12562, 12570, 13195]
incomplete name 3, col: 10620 row: []
col: 10621 similar rows:  [10621, 11436, 12184]
incomplete name 3, col: 10621 row: []
col: 10623 similar rows:  [10623]
11111111111111111111
hotelname2 [10623]
incomplete name 3, col: 10623 row: [10623]
col: 10626 similar rows:  [10626]
11111111111111111111
incomplete name 3, col: 10626 row: []
col: 10627 similar rows:  [10627, 10779, 12171, 12395]
incomplete name 3, col: 10627 row: []
col: 10628 similar rows:  [10628]
11111111111111111111
incomplete name 3, col: 10628 row: []
col: 10629 similar rows:  [10629, 10685, 11094, 11112, 11431, 11787, 11970, 12307, 12401, 12624, 12702, 12738, 12819, 12839, 13037]
incomplete name 3, col: 10629 row: []
col: 10630 similar rows:  [10630, 11065, 11077, 11744, 12168]
incomplete name 3, col: 10630 row: []
col: 10631 similar rows:  [10631]
11111111111111111111
incomplete name 3, col: 10631 row: []
col: 10632 similar rows:  [10632]
11111111111111111111
incomplete name 3, col: 10632 row: []
col: 10633 similar rows:  [10633, 10777, 11043, 11720, 12290, 12439, 12880, 13004, 13141, 13147, 13149]
incomplete name 3, col: 10633 row: []
col: 10634 similar rows:  [10634]
11111111111111111111
incomplete name 3, col: 10634 row: []
col: 10635 similar rows:  [10635]
11111111111111111111
incomplete name 3, col: 10635 row: []
col: 10636 similar rows:  [10636]
11111111111111111111
hotelname2 [10636]
incomplete name 3, col: 10636 row: [10636]
col: 10637 similar rows:  [10637]
11111111111111111111
incomplete name 3, col: 10637 row: []
col: 10639 similar rows:  [10639, 11159, 11224, 11943, 11946, 12540, 13191]
incomplete name 3, col: 10639 row: []
col: 10640 similar rows:  [10640]
11111111111111111111
incomplete name 3, col: 10640 row: []
col: 10641 similar rows:  [10641]
11111111111111111111
incomplete name 3, col: 10641 row: []
col: 10642 similar rows:  [10642]
11111111111111111111
incomplete name 3, col: 10642 row: []
col: 10644 similar rows:  [10644]
11111111111111111111
incomplete name 3, col: 10644 row: []
col: 10646 similar rows:  [10646, 10647]
incomplete name 3, col: 10646 row: []
col: 10648 similar rows:  [10648]
11111111111111111111
incomplete name 3, col: 10648 row: []
col: 10649 similar rows:  [10649, 10958, 12173]
incomplete name 3, col: 10649 row: []
col: 10650 similar rows:  [10650]
11111111111111111111
hotelname2 [10650]
incomplete name 3, col: 10650 row: []
col: 10651 similar rows:  [10651]
11111111111111111111
incomplete name 3, col: 10651 row: []
col: 10653 similar rows:  [10653, 11585, 11731, 11898, 12283, 12708]
incomplete name 3, col: 10653 row: []
col: 10654 similar rows:  [10654]
11111111111111111111
incomplete name 3, col: 10654 row: []
col: 10655 similar rows:  [10655, 10814, 10989, 11079, 11242, 11656, 12002, 12354]
incomplete name 3, col: 10655 row: []
col: 10659 similar rows:  [10659]
11111111111111111111
incomplete name 3, col: 10659 row: []
col: 10661 similar rows:  [10661, 10759, 11270, 11286, 12361]
incomplete name 3, col: 10661 row: []
col: 10663 similar rows:  [10663]
11111111111111111111
incomplete name 3, col: 10663 row: []
col: 10665 similar rows:  [10665]
11111111111111111111
incomplete name 3, col: 10665 row: []
col: 10667 similar rows:  [10667, 11260, 11418, 11781, 11929, 12526]
incomplete name 3, col: 10667 row: []
col: 10669 similar rows:  [10669]
11111111111111111111
hotelname2 [10669]
incomplete name 3, col: 10669 row: [10669]
col: 10670 similar rows:  [10670]
11111111111111111111
incomplete name 3, col: 10670 row: []
col: 10672 similar rows:  [10672]
11111111111111111111
hotelname2 [10672]
incomplete name 3, col: 10672 row: [10672]
col: 10673 similar rows:  [10673]
11111111111111111111
incomplete name 3, col: 10673 row: []
col: 10674 similar rows:  [10674]
11111111111111111111
hotelname2 [10674]
incomplete name 3, col: 10674 row: [10674]
col: 10678 similar rows:  [10678, 12764]
incomplete name 3, col: 10678 row: []
col: 10679 similar rows:  [10679]
11111111111111111111
incomplete name 3, col: 10679 row: []
col: 10680 similar rows:  [10680]
11111111111111111111
incomplete name 3, col: 10680 row: []
col: 10681 similar rows:  [10681]
11111111111111111111
hotelname2 [10681]
wrong name!!!!
incomplete name 3, col: 10681 row: [10681]
col: 10684 similar rows:  [10684, 11085, 12866]
incomplete name 3, col: 10684 row: []
col: 10686 similar rows:  [10686, 10694, 10715, 10741, 10838, 10856, 11033, 11071, 11384, 11583, 11846, 11882, 11944, 11999, 12807, 12809, 12815, 12826, 12913, 12950, 13029, 13052, 13056, 13082, 13113]
incomplete name 3, col: 10686 row: []
col: 10687 similar rows:  [10687, 12861]
incomplete name 3, col: 10687 row: []
col: 10689 similar rows:  [10689]
11111111111111111111
hotelname2 [10689]
incomplete name 3, col: 10689 row: [10689]
col: 10690 similar rows:  [10690]
11111111111111111111
incomplete name 3, col: 10690 row: []
col: 10691 similar rows:  [10691, 12462, 12532]
incomplete name 3, col: 10691 row: []
col: 10693 similar rows:  [10693, 11055, 12417]
incomplete name 3, col: 10693 row: []
col: 10695 similar rows:  [10695]
11111111111111111111
incomplete name 3, col: 10695 row: []
col: 10697 similar rows:  [10697, 11886, 12296, 12331, 12333]
incomplete name 3, col: 10697 row: []
col: 10698 similar rows:  [10698, 10836, 12339]
incomplete name 3, col: 10698 row: []
col: 10699 similar rows:  [10699]
11111111111111111111
incomplete name 3, col: 10699 row: []
col: 10702 similar rows:  [10702]
11111111111111111111
hotelname2 [10702]
incomplete name 3, col: 10702 row: [10702]
col: 10703 similar rows:  [10703, 11401]
incomplete name 3, col: 10703 row: []
col: 10704 similar rows:  [10704]
11111111111111111111
incomplete name 3, col: 10704 row: []
col: 10705 similar rows:  [10705]
11111111111111111111
incomplete name 3, col: 10705 row: []
col: 10708 similar rows:  [10708, 11195]
incomplete name 3, col: 10708 row: []
col: 10711 similar rows:  [10711, 11775]
incomplete name 3, col: 10711 row: []
col: 10714 similar rows:  [10714, 11295, 12834]
incomplete name 3, col: 10714 row: []
col: 10716 similar rows:  [10716, 11284]
incomplete name 3, col: 10716 row: []
col: 10717 similar rows:  [10717]
11111111111111111111
incomplete name 3, col: 10717 row: []
col: 10719 similar rows:  [10719, 13036]
incomplete name 3, col: 10719 row: []
col: 10720 similar rows:  [10720]
11111111111111111111
incomplete name 3, col: 10720 row: []
col: 10721 similar rows:  [10721, 12469, 12767]
incomplete name 3, col: 10721 row: []
col: 10723 similar rows:  [10723]
11111111111111111111
incomplete name 3, col: 10723 row: []
col: 10724 similar rows:  [10724]
11111111111111111111
incomplete name 3, col: 10724 row: []
col: 10725 similar rows:  [10725, 12013, 12030]
incomplete name 3, col: 10725 row: []
col: 10727 similar rows:  [10727]
11111111111111111111
hotelname2 [10727]
incomplete name 3, col: 10727 row: [10727]
col: 10729 similar rows:  [10729]
11111111111111111111
incomplete name 3, col: 10729 row: []
col: 10730 similar rows:  [10730, 10960, 11052, 11326, 11847, 12150, 12278, 12340, 12358, 12448, 12554, 12612, 12649, 12777, 12849, 12877, 12995]
incomplete name 3, col: 10730 row: []
col: 10731 similar rows:  [10731]
11111111111111111111
hotelname2 [10731]
incomplete name 3, col: 10731 row: []
col: 10732 similar rows:  [10732, 10854, 10884, 10996, 11028, 11061, 11288, 11433, 11734, 12459, 12904]
incomplete name 3, col: 10732 row: []
col: 10733 similar rows:  [10733]
11111111111111111111
incomplete name 3, col: 10733 row: []
col: 10734 similar rows:  [10734]
11111111111111111111
incomplete name 3, col: 10734 row: []
col: 10735 similar rows:  [10735]
11111111111111111111
hotelname2 [10735]
incomplete name 3, col: 10735 row: [10735]
col: 10736 similar rows:  [10736]
11111111111111111111
hotelname2 [10736]
incomplete name 3, col: 10736 row: [10736]
col: 10737 similar rows:  [10737]
11111111111111111111
incomplete name 3, col: 10737 row: []
col: 10738 similar rows:  [10738]
11111111111111111111
incomplete name 3, col: 10738 row: []

col: 10739 similar rows:  [10739, 12828]
incomplete name 3, col: 10739 row: []
col: 10740 similar rows:  [10740, 13122]
incomplete name 3, col: 10740 row: []
col: 10742 similar rows:  [10742, 11476, 12495, 12557, 12610, 12736]
incomplete name 3, col: 10742 row: []
col: 10743 similar rows:  [10743, 10911, 11053, 11527, 11534, 12035, 12820, 12879, 12912, 12981, 13224]
incomplete name 3, col: 10743 row: []
col: 10744 similar rows:  [10744]
11111111111111111111
incomplete name 3, col: 10744 row: []
col: 10746 similar rows:  [10746, 11135, 11296, 11918, 12335, 12814]
incomplete name 3, col: 10746 row: []
col: 10748 similar rows:  [10748]
11111111111111111111
incomplete name 3, col: 10748 row: []
col: 10749 similar rows:  [10749, 10761, 11429, 12213, 12576]
incomplete name 3, col: 10749 row: []
col: 10750 similar rows:  [10750]
11111111111111111111
hotelname2 [10750]
incomplete name 3, col: 10750 row: [10750]
col: 10751 similar rows:  [10751, 10804, 11594, 11722, 12359, 12733]
incomplete name 3, col: 10751 row: []
col: 10753 similar rows:  [10753, 11171, 11702, 11719, 11725, 11948, 12041, 12138, 12856]
incomplete name 3, col: 10753 row: []
col: 10756 similar rows:  [10756]
11111111111111111111
incomplete name 3, col: 10756 row: []
col: 10757 similar rows:  [10757]
11111111111111111111
hotelname2 [10757]
incomplete name 3, col: 10757 row: [10757]
col: 10758 similar rows:  [10758, 11923]
incomplete name 3, col: 10758 row: []
col: 10760 similar rows:  [10760]
11111111111111111111
incomplete name 3, col: 10760 row: []
col: 10763 similar rows:  [10763, 11402, 12146, 12162, 12511]
incomplete name 3, col: 10763 row: []
col: 10764 similar rows:  [10764, 10878]
incomplete name 3, col: 10764 row: []
col: 10765 similar rows:  [10765]
11111111111111111111
incomplete name 3, col: 10765 row: []
col: 10768 similar rows:  [10768, 11040, 11709]
incomplete name 3, col: 10768 row: []
col: 10769 similar rows:  [10769, 13178]
incomplete name 3, col: 10769 row: []
col: 10770 similar rows:  [10770, 10865, 11421, 11563, 12970, 13035, 13222]
incomplete name 3, col: 10770 row: []
col: 10771 similar rows:  [10771]
11111111111111111111
hotelname2 [10771]
incomplete name 3, col: 10771 row: []
col: 10772 similar rows:  [10772, 11919, 11953, 12279, 12721, 13022, 13096]
incomplete name 3, col: 10772 row: []
col: 10773 similar rows:  [10773, 11328, 11475, 12208, 12506]
incomplete name 3, col: 10773 row: []
col: 10774 similar rows:  [10774, 12088]
incomplete name 3, col: 10774 row: []
col: 10775 similar rows:  [10775]
11111111111111111111
hotelname2 [10775]
incomplete name 3, col: 10775 row: [10775]
col: 10776 similar rows:  [10776, 11130, 11132, 12151]
incomplete name 3, col: 10776 row: []
col: 10778 similar rows:  [10778]
11111111111111111111
incomplete name 3, col: 10778 row: []
col: 10781 similar rows:  [10781]
11111111111111111111
incomplete name 3, col: 10781 row: []
col: 10782 similar rows:  [10782]
11111111111111111111
incomplete name 3, col: 10782 row: []
col: 10783 similar rows:  [10783]
11111111111111111111
incomplete name 3, col: 10783 row: []
col: 10784 similar rows:  [10784]
11111111111111111111
incomplete name 3, col: 10784 row: []
col: 10785 similar rows:  [10785, 11305]
incomplete name 3, col: 10785 row: []
col: 10787 similar rows:  [10787]
11111111111111111111
incomplete name 3, col: 10787 row: []
col: 10788 similar rows:  [10788]
11111111111111111111
incomplete name 3, col: 10788 row: []
col: 10789 similar rows:  [10789, 12547]
incomplete name 3, col: 10789 row: []
col: 10790 similar rows:  [10790]
11111111111111111111
incomplete name 3, col: 10790 row: []
col: 10791 similar rows:  [10791, 11590, 12353, 12438, 13190]
incomplete name 3, col: 10791 row: []
col: 10792 similar rows:  [10792, 12176, 12388, 13084]
incomplete name 3, col: 10792 row: []
col: 10793 similar rows:  [10793, 10960, 11052, 11326, 11847, 12150, 12278, 12340, 12358, 12448, 12554, 12612, 12649, 12777, 12849, 12877]
incomplete name 3, col: 10793 row: []
col: 10794 similar rows:  [10794]
11111111111111111111
incomplete name 3, col: 10794 row: []
col: 10796 similar rows:  [10796, 11256]
incomplete name 3, col: 10796 row: []
col: 10798 similar rows:  [10798, 11547, 11581, 12156, 12801]
incomplete name 3, col: 10798 row: []
col: 10799 similar rows:  [10799]
11111111111111111111
incomplete name 3, col: 10799 row: []
col: 10800 similar rows:  [10800]
11111111111111111111
incomplete name 3, col: 10800 row: []
col: 10801 similar rows:  [10801]
11111111111111111111
incomplete name 3, col: 10801 row: []
col: 10803 similar rows:  [10803]
11111111111111111111
incomplete name 3, col: 10803 row: []
col: 10805 similar rows:  [10805, 12565]
incomplete name 3, col: 10805 row: []
col: 10806 similar rows:  [10806]
11111111111111111111
hotelname2 [10806]
incomplete name 3, col: 10806 row: []
col: 10807 similar rows:  [10807]
11111111111111111111
incomplete name 3, col: 10807 row: []
col: 10809 similar rows:  [10809, 12066, 12167]
incomplete name 3, col: 10809 row: []
col: 10811 similar rows:  [10811]
11111111111111111111
incomplete name 3, col: 10811 row: []
col: 10812 similar rows:  [10812]
11111111111111111111
incomplete name 3, col: 10812 row: []
col: 10813 similar rows:  [10813]
11111111111111111111
incomplete name 3, col: 10813 row: []
col: 10815 similar rows:  [10815, 11121, 12644, 12663]
incomplete name 3, col: 10815 row: []
col: 10818 similar rows:  [10818, 10962]
incomplete name 3, col: 10818 row: []
col: 10819 similar rows:  [10819]
11111111111111111111
hotelname2 [10819]
wrong name!!!!
incomplete name 3, col: 10819 row: [10819]
col: 10820 similar rows:  [10820, 10918, 11139, 12203]
incomplete name 3, col: 10820 row: []
col: 10821 similar rows:  [10821, 13216]
incomplete name 3, col: 10821 row: []
col: 10822 similar rows:  [10822]
11111111111111111111
hotelname2 [10822]
wrong name!!!!
incomplete name 3, col: 10822 row: [10822]
col: 10823 similar rows:  [10823]
11111111111111111111
hotelname2 [10823]
incomplete name 3, col: 10823 row: [10823]
col: 10824 similar rows:  [10824]
11111111111111111111
incomplete name 3, col: 10824 row: []
col: 10825 similar rows:  [10825]
11111111111111111111
incomplete name 3, col: 10825 row: []
col: 10827 similar rows:  [10827]
11111111111111111111
incomplete name 3, col: 10827 row: []
col: 10828 similar rows:  [10828, 13026, 13080, 13196]
incomplete name 3, col: 10828 row: []
col: 10829 similar rows:  [10829, 11785]
incomplete name 3, col: 10829 row: []
col: 10830 similar rows:  [10830, 10889, 10914, 11271, 11552, 11925, 12211, 12851, 12869, 12878, 12899, 12918, 13155]
incomplete name 3, col: 10830 row: []
col: 10831 similar rows:  [10831, 10842, 11282, 11742, 13103]
incomplete name 3, col: 10831 row: []
col: 10834 similar rows:  [10834, 11275, 11576, 11640, 11861, 11983, 12190, 12794, 12873, 12884, 13123]
incomplete name 3, col: 10834 row: []
col: 10837 similar rows:  [10837, 11287]
incomplete name 3, col: 10837 row: []
col: 10839 similar rows:  [10839, 11515, 11588, 11872, 12281, 12317, 12442, 12458, 12470, 12536]
incomplete name 3, col: 10839 row: []
col: 10843 similar rows:  [10843, 11729, 11745, 11817, 12114, 12642, 12875, 13128]
incomplete name 3, col: 10843 row: []
col: 10844 similar rows:  [10844, 11969, 12369]
incomplete name 3, col: 10844 row: []
col: 10846 similar rows:  [10846, 11432, 13042]
incomplete name 3, col: 10846 row: []
col: 10848 similar rows:  [10848, 11273, 12518, 13154]
incomplete name 3, col: 10848 row: []
col: 10850 similar rows:  [10850]
11111111111111111111
hotelname2 [10850]
incomplete name 3, col: 10850 row: [10850]
col: 10851 similar rows:  [10851]
11111111111111111111
incomplete name 3, col: 10851 row: []
col: 10852 similar rows:  [10852]
11111111111111111111
incomplete name 3, col: 10852 row: []
col: 10855 similar rows:  [10855]
11111111111111111111
hotelname2 [10855]
incomplete name 3, col: 10855 row: [10855]
col: 10858 similar rows:  [10858, 12979, 13181]
incomplete name 3, col: 10858 row: []
col: 10863 similar rows:  [10863, 13085]
incomplete name 3, col: 10863 row: []
col: 10864 similar rows:  [10864, 12039]
incomplete name 3, col: 10864 row: []
col: 10867 similar rows:  [10867, 10941]
incomplete name 3, col: 10867 row: []
col: 10871 similar rows:  [10871]
11111111111111111111
hotelname2 [10871]
incomplete name 3, col: 10871 row: [10871]
col: 10873 similar rows:  [10873]
11111111111111111111
incomplete name 3, col: 10873 row: []
col: 10874 similar rows:  [10874]
11111111111111111111
hotelname2 [10874]
incomplete name 3, col: 10874 row: [10874]
col: 10875 similar rows:  [10875, 12348, 13044, 13088]
incomplete name 3, col: 10875 row: []

col: 10880 similar rows:  [10880]
11111111111111111111
hotelname2 [10880]
incomplete name 3, col: 10880 row: []
col: 10881 similar rows:  [10881, 11178, 12921]
incomplete name 3, col: 10881 row: []
col: 10882 similar rows:  [10882]
11111111111111111111
incomplete name 3, col: 10882 row: []
col: 10885 similar rows:  [10885]
11111111111111111111
incomplete name 3, col: 10885 row: []
col: 10886 similar rows:  [10886]
11111111111111111111
incomplete name 3, col: 10886 row: []
col: 10887 similar rows:  [10887]
11111111111111111111
incomplete name 3, col: 10887 row: []
col: 10890 similar rows:  [10890]
11111111111111111111
hotelname2 [10890]
incomplete name 3, col: 10890 row: [10890]
col: 10892 similar rows:  [10892, 12890]
incomplete name 3, col: 10892 row: []
col: 10893 similar rows:  [10893, 11039, 11981, 12571]
incomplete name 3, col: 10893 row: []
col: 10894 similar rows:  [10894, 12098]
incomplete name 3, col: 10894 row: []
col: 10895 similar rows:  [10895, 11375, 11377, 12085, 12800]
incomplete name 3, col: 10895 row: []
col: 10899 similar rows:  [10899, 11651, 11658]
incomplete name 3, col: 10899 row: []
col: 10902 similar rows:  [10902]
11111111111111111111
incomplete name 3, col: 10902 row: []
col: 10903 similar rows:  [10903]
11111111111111111111
incomplete name 3, col: 10903 row: []
col: 10907 similar rows:  [10907]
11111111111111111111
incomplete name 3, col: 10907 row: []
col: 10910 similar rows:  [10910, 11562, 12141, 12868]
incomplete name 3, col: 10910 row: []
col: 10912 similar rows:  [10912, 12464]
incomplete name 3, col: 10912 row: []
col: 10915 similar rows:  [10915]
11111111111111111111
incomplete name 3, col: 10915 row: []
col: 10919 similar rows:  [10919, 11382]
incomplete name 3, col: 10919 row: []
col: 10920 similar rows:  [10920, 11066]
incomplete name 3, col: 10920 row: []
col: 10923 similar rows:  [10923, 11810]
incomplete name 3, col: 10923 row: []
col: 10925 similar rows:  [10925, 11540, 12949]
incomplete name 3, col: 10925 row: []
col: 10927 similar rows:  [10927, 12260]
incomplete name 3, col: 10927 row: []
col: 10928 similar rows:  [10928]
11111111111111111111
hotelname2 [10928]
incomplete name 3, col: 10928 row: [10928]
col: 10931 similar rows:  [10931, 11179, 11348, 11730, 11736, 12863]
incomplete name 3, col: 10931 row: []
col: 10932 similar rows:  [10932, 11980]
incomplete name 3, col: 10932 row: []
col: 10934 similar rows:  [10934]
11111111111111111111
incomplete name 3, col: 10934 row: []
col: 10935 similar rows:  [10935]
11111111111111111111
hotelname2 [10935]
incomplete name 3, col: 10935 row: [10935]
col: 10936 similar rows:  [10936, 11481, 12045]
incomplete name 3, col: 10936 row: []
col: 10940 similar rows:  [10940, 11756]
incomplete name 3, col: 10940 row: []
col: 10942 similar rows:  [10942, 11127, 11243, 11571, 13165]
incomplete name 3, col: 10942 row: []
col: 10944 similar rows:  [10944]
11111111111111111111
incomplete name 3, col: 10944 row: []
col: 10946 similar rows:  [10946]
11111111111111111111
incomplete name 3, col: 10946 row: []
col: 10948 similar rows:  [10948, 11130, 11132]
incomplete name 3, col: 10948 row: []
col: 10949 similar rows:  [10949, 12964]
incomplete name 3, col: 10949 row: []
col: 10950 similar rows:  [10950, 12966, 13168, 13185]
incomplete name 3, col: 10950 row: []
col: 10951 similar rows:  [10951]
11111111111111111111
incomplete name 3, col: 10951 row: []
col: 10952 similar rows:  [10952]
11111111111111111111
incomplete name 3, col: 10952 row: []
col: 10953 similar rows:  [10953]
11111111111111111111
incomplete name 3, col: 10953 row: []
col: 10955 similar rows:  [10955]
11111111111111111111
incomplete name 3, col: 10955 row: []
col: 10961 similar rows:  [10961, 11158, 11279, 11873, 11874, 12161, 12468, 12633]
incomplete name 3, col: 10961 row: []
col: 10963 similar rows:  [10963, 12790]
incomplete name 3, col: 10963 row: []
col: 10967 similar rows:  [10967, 11263, 11939, 12175, 12522]
incomplete name 3, col: 10967 row: []
col: 10970 similar rows:  [10970, 11762]
incomplete name 3, col: 10970 row: []
col: 10972 similar rows:  [10972, 10973]
incomplete name 3, col: 10972 row: []
col: 10974 similar rows:  [10974]
11111111111111111111
incomplete name 3, col: 10974 row: []
col: 10975 similar rows:  [10975]
11111111111111111111
hotelname2 [10975]
incomplete name 3, col: 10975 row: [10975]
col: 10977 similar rows:  [10977, 11899]
incomplete name 3, col: 10977 row: []
col: 10979 similar rows:  [10979]
11111111111111111111
hotelname2 [10979]
incomplete name 3, col: 10979 row: [10979]
col: 10980 similar rows:  [10980, 11931]
incomplete name 3, col: 10980 row: []
col: 10981 similar rows:  [10981]
11111111111111111111
incomplete name 3, col: 10981 row: []
col: 10982 similar rows:  [10982]
11111111111111111111
incomplete name 3, col: 10982 row: []
col: 10984 similar rows:  [10984]
11111111111111111111
incomplete name 3, col: 10984 row: []
col: 10986 similar rows:  [10986, 11023]
incomplete name 3, col: 10986 row: []
col: 10987 similar rows:  [10987]
11111111111111111111
incomplete name 3, col: 10987 row: []
col: 10988 similar rows:  [10988]
11111111111111111111
hotelname2 [10988]
incomplete name 3, col: 10988 row: [10988]
col: 10992 similar rows:  [10992, 12292, 12627]
incomplete name 3, col: 10992 row: []
col: 10995 similar rows:  [10995]
11111111111111111111
incomplete name 3, col: 10995 row: []
col: 10997 similar rows:  [10997]
11111111111111111111
incomplete name 3, col: 10997 row: []
col: 10999 similar rows:  [10999]
11111111111111111111
incomplete name 3, col: 10999 row: []
col: 11000 similar rows:  [11000, 11128, 11214, 12072, 12118, 12476, 12539, 12654]
incomplete name 3, col: 11000 row: []
col: 11004 similar rows:  [11004]
11111111111111111111
hotelname2 [11004]
incomplete name 3, col: 11004 row: []
col: 11005 similar rows:  [11005]
11111111111111111111
incomplete name 3, col: 11005 row: []
col: 11007 similar rows:  [11007]
11111111111111111111
incomplete name 3, col: 11007 row: []
col: 11011 similar rows:  [11011, 11927, 12095, 12659, 12704]
incomplete name 3, col: 11011 row: []
col: 11016 similar rows:  [11016]
11111111111111111111
incomplete name 3, col: 11016 row: []
col: 11021 similar rows:  [11021]
11111111111111111111
incomplete name 3, col: 11021 row: []
col: 11024 similar rows:  [11024]
11111111111111111111
hotelname2 [11024]
incomplete name 3, col: 11024 row: []
col: 11026 similar rows:  [11026]
11111111111111111111
incomplete name 3, col: 11026 row: []
col: 11029 similar rows:  [11029]
11111111111111111111
hotelname2 [11029]
incomplete name 3, col: 11029 row: [11029]
col: 11030 similar rows:  [11030, 11623, 11717, 12044, 12386]
incomplete name 3, col: 11030 row: []
col: 11031 similar rows:  [11031]
11111111111111111111
incomplete name 3, col: 11031 row: []
col: 11032 similar rows:  [11032]
11111111111111111111
incomplete name 3, col: 11032 row: []
col: 11041 similar rows:  [11041, 12021]
incomplete name 3, col: 11041 row: []
col: 11042 similar rows:  [11042, 12144]
incomplete name 3, col: 11042 row: []
col: 11047 similar rows:  [11047, 11519, 11541, 12821]
incomplete name 3, col: 11047 row: []
col: 11048 similar rows:  [11048]
11111111111111111111
incomplete name 3, col: 11048 row: []
col: 11049 similar rows:  [11049, 12760]
incomplete name 3, col: 11049 row: []
col: 11050 similar rows:  [11050, 12382, 12728, 12840]
incomplete name 3, col: 11050 row: []
col: 11051 similar rows:  [11051, 11609]
incomplete name 3, col: 11051 row: []
col: 11057 similar rows:  [11057]
11111111111111111111
hotelname2 [11057]
incomplete name 3, col: 11057 row: [11057]
col: 11059 similar rows:  [11059]
11111111111111111111
hotelname2 [11059]
incomplete name 3, col: 11059 row: [11059]
col: 11060 similar rows:  [11060]
11111111111111111111
incomplete name 3, col: 11060 row: []
col: 11062 similar rows:  [11062]
11111111111111111111
incomplete name 3, col: 11062 row: []
col: 11063 similar rows:  [11063]
11111111111111111111
hotelname2 [11063]
incomplete name 3, col: 11063 row: [11063]
col: 11067 similar rows:  [11067]
11111111111111111111
incomplete name 3, col: 11067 row: []
col: 11072 similar rows:  [11072, 11621]
incomplete name 3, col: 11072 row: []
col: 11073 similar rows:  [11073, 12926]
incomplete name 3, col: 11073 row: []
col: 11074 similar rows:  [11074, 11863, 11904, 12186]
incomplete name 3, col: 11074 row: []
col: 11076 similar rows:  [11076, 12604]
incomplete name 3, col: 11076 row: []
col: 11078 similar rows:  [11078]
11111111111111111111
incomplete name 3, col: 11078 row: []

col: 11080 similar rows:  [11080]
11111111111111111111
incomplete name 3, col: 11080 row: []
col: 11083 similar rows:  [11083, 13208]
incomplete name 3, col: 11083 row: []
col: 11084 similar rows:  [11084, 11091, 11607, 12556]
incomplete name 3, col: 11084 row: []
col: 11087 similar rows:  [11087]
11111111111111111111
incomplete name 3, col: 11087 row: []
col: 11089 similar rows:  [11089, 11754, 11891]
incomplete name 3, col: 11089 row: []
col: 11090 similar rows:  [11090, 11804]
incomplete name 3, col: 11090 row: []
col: 11092 similar rows:  [11092]
11111111111111111111
incomplete name 3, col: 11092 row: []
col: 11096 similar rows:  [11096]
11111111111111111111
incomplete name 3, col: 11096 row: []
col: 11097 similar rows:  [11097]
11111111111111111111
hotelname2 [11097]
wrong name!!!!
incomplete name 3, col: 11097 row: [11097]
col: 11098 similar rows:  [11098]
11111111111111111111
incomplete name 3, col: 11098 row: []
col: 11099 similar rows:  [11099, 11276, 11601, 11816, 12174, 13111]
incomplete name 3, col: 11099 row: []
col: 11100 similar rows:  [11100]
11111111111111111111
hotelname2 [11100]
incomplete name 3, col: 11100 row: [11100]
col: 11102 similar rows:  [11102]
11111111111111111111
incomplete name 3, col: 11102 row: []
col: 11104 similar rows:  [11104]
11111111111111111111
hotelname2 [11104]
incomplete name 3, col: 11104 row: []
col: 11108 similar rows:  [11108]
11111111111111111111
incomplete name 3, col: 11108 row: []
col: 11110 similar rows:  [11110, 12344, 12512]
incomplete name 3, col: 11110 row: []
col: 11113 similar rows:  [11113]
11111111111111111111
hotelname2 [11113]
incomplete name 3, col: 11113 row: [11113]
col: 11115 similar rows:  [11115, 11169]
incomplete name 3, col: 11115 row: []
col: 11116 similar rows:  [11116, 13001]
incomplete name 3, col: 11116 row: []
col: 11117 similar rows:  [11117]
11111111111111111111
incomplete name 3, col: 11117 row: []
col: 11119 similar rows:  [11119]
11111111111111111111
incomplete name 3, col: 11119 row: []
col: 11123 similar rows:  [11123, 11428, 13166]
incomplete name 3, col: 11123 row: []
col: 11124 similar rows:  [11124, 12447]
incomplete name 3, col: 11124 row: []
col: 11134 similar rows:  [11134]
11111111111111111111
incomplete name 3, col: 11134 row: []
col: 11137 similar rows:  [11137, 11567, 11642, 12287, 12467]
incomplete name 3, col: 11137 row: []
col: 11144 similar rows:  [11144, 11213, 12018, 12133, 13156]
incomplete name 3, col: 11144 row: []
col: 11145 similar rows:  [11145]
11111111111111111111
hotelname2 [11145]
incomplete name 3, col: 11145 row: [11145]
col: 11148 similar rows:  [11148, 12071, 12521]
incomplete name 3, col: 11148 row: []
col: 11149 similar rows:  [11149]
11111111111111111111
incomplete name 3, col: 11149 row: []
col: 11153 similar rows:  [11153]
11111111111111111111
incomplete name 3, col: 11153 row: []
col: 11154 similar rows:  [11154]
11111111111111111111
incomplete name 3, col: 11154 row: []
col: 11156 similar rows:  [11156]
11111111111111111111
incomplete name 3, col: 11156 row: []
col: 11157 similar rows:  [11157, 12145]
incomplete name 3, col: 11157 row: []
col: 11160 similar rows:  [11160, 12380]
incomplete name 3, col: 11160 row: []
col: 11161 similar rows:  [11161]
11111111111111111111
incomplete name 3, col: 11161 row: []
col: 11162 similar rows:  [11162]
11111111111111111111
incomplete name 3, col: 11162 row: []
col: 11163 similar rows:  [11163, 11344, 12370, 12472, 12725, 13061]
incomplete name 3, col: 11163 row: []
col: 11164 similar rows:  [11164, 11645, 12100, 12360]
incomplete name 3, col: 11164 row: []
col: 11166 similar rows:  [11166]
11111111111111111111
incomplete name 3, col: 11166 row: []
col: 11168 similar rows:  [11168]
11111111111111111111
incomplete name 3, col: 11168 row: []
col: 11170 similar rows:  [11170]
11111111111111111111
incomplete name 3, col: 11170 row: []
col: 11172 similar rows:  [11172]
11111111111111111111
incomplete name 3, col: 11172 row: []
col: 11173 similar rows:  [11173]
11111111111111111111
incomplete name 3, col: 11173 row: []
col: 11174 similar rows:  [11174]
11111111111111111111
incomplete name 3, col: 11174 row: []
col: 11176 similar rows:  [11176]
11111111111111111111
incomplete name 3, col: 11176 row: []
col: 11180 similar rows:  [11180]
11111111111111111111
incomplete name 3, col: 11180 row: []
col: 11181 similar rows:  [11181]
11111111111111111111
incomplete name 3, col: 11181 row: []
col: 11182 similar rows:  [11182, 11721]
incomplete name 3, col: 11182 row: []
col: 11183 similar rows:  [11183]
11111111111111111111
incomplete name 3, col: 11183 row: []
col: 11186 similar rows:  [11186, 12410]
incomplete name 3, col: 11186 row: []
col: 11187 similar rows:  [11187, 11220, 12078, 12402, 12551]
incomplete name 3, col: 11187 row: []
col: 11188 similar rows:  [11188]
11111111111111111111
incomplete name 3, col: 11188 row: []
col: 11189 similar rows:  [11189]
11111111111111111111
incomplete name 3, col: 11189 row: []
col: 11191 similar rows:  [11191, 12637, 12667, 12697, 12718, 12732, 13136]
incomplete name 3, col: 11191 row: []
col: 11192 similar rows:  [11192]
11111111111111111111
incomplete name 3, col: 11192 row: []
col: 11193 similar rows:  [11193]
11111111111111111111
incomplete name 3, col: 11193 row: []
col: 11196 similar rows:  [11196]
11111111111111111111
hotelname2 [11196]
incomplete name 3, col: 11196 row: [11196]
col: 11197 similar rows:  [11197, 11416, 12944]
incomplete name 3, col: 11197 row: []
col: 11198 similar rows:  [11198]
11111111111111111111
incomplete name 3, col: 11198 row: []
col: 11199 similar rows:  [11199]
11111111111111111111
incomplete name 3, col: 11199 row: []
col: 11201 similar rows:  [11201]
11111111111111111111
incomplete name 3, col: 11201 row: []
col: 11202 similar rows:  [11202, 11687, 12479]
incomplete name 3, col: 11202 row: []
col: 11205 similar rows:  [11205]
11111111111111111111
incomplete name 3, col: 11205 row: []
col: 11206 similar rows:  [11206, 11539]
incomplete name 3, col: 11206 row: []
col: 11208 similar rows:  [11208, 12758]
incomplete name 3, col: 11208 row: []
col: 11209 similar rows:  [11209]
11111111111111111111
incomplete name 3, col: 11209 row: []
col: 11211 similar rows:  [11211]
11111111111111111111
incomplete name 3, col: 11211 row: []
col: 11215 similar rows:  [11215]
11111111111111111111
hotelname2 [11215]
wrong name!!!!
incomplete name 3, col: 11215 row: [11215]
col: 11217 similar rows:  [11217]
11111111111111111111
hotelname2 [11217]
wrong name!!!!
incomplete name 3, col: 11217 row: [11217]
col: 11218 similar rows:  [11218, 11819, 12383]
incomplete name 3, col: 11218 row: []
col: 11219 similar rows:  [11219]
11111111111111111111
incomplete name 3, col: 11219 row: []
col: 11221 similar rows:  [11221]
11111111111111111111
incomplete name 3, col: 11221 row: []
col: 11222 similar rows:  [11222, 11312, 11856, 12675, 13033]
incomplete name 3, col: 11222 row: []
col: 11225 similar rows:  [11225]
11111111111111111111
incomplete name 3, col: 11225 row: []
col: 11226 similar rows:  [11226]
11111111111111111111
incomplete name 3, col: 11226 row: []
col: 11228 similar rows:  [11228]
11111111111111111111
incomplete name 3, col: 11228 row: []
col: 11229 similar rows:  [11229]
11111111111111111111
incomplete name 3, col: 11229 row: []
col: 11230 similar rows:  [11230]
11111111111111111111
incomplete name 3, col: 11230 row: []
col: 11232 similar rows:  [11232]
11111111111111111111
incomplete name 3, col: 11232 row: []
col: 11233 similar rows:  [11233]
11111111111111111111
incomplete name 3, col: 11233 row: []
col: 11234 similar rows:  [11234]
11111111111111111111
incomplete name 3, col: 11234 row: []
col: 11235 similar rows:  [11235]
11111111111111111111
incomplete name 3, col: 11235 row: []
col: 11237 similar rows:  [11237]
11111111111111111111
incomplete name 3, col: 11237 row: []
col: 11238 similar rows:  [11238]
11111111111111111111
incomplete name 3, col: 11238 row: []
col: 11240 similar rows:  [11240]
11111111111111111111
hotelname2 [11240]
incomplete name 3, col: 11240 row: []
col: 11244 similar rows:  [11244, 12094]
incomplete name 3, col: 11244 row: []
col: 11245 similar rows:  [11245]
11111111111111111111
hotelname2 [11245]
incomplete name 3, col: 11245 row: [11245]

col: 11246 similar rows:  [11246]
11111111111111111111
incomplete name 3, col: 11246 row: []
col: 11247 similar rows:  [11247]
11111111111111111111
incomplete name 3, col: 11247 row: []
col: 11248 similar rows:  [11248]
11111111111111111111
incomplete name 3, col: 11248 row: []
col: 11249 similar rows:  [11249]
11111111111111111111
hotelname2 [11249]
incomplete name 3, col: 11249 row: [11249]
col: 11250 similar rows:  [11250]
11111111111111111111
incomplete name 3, col: 11250 row: []
col: 11251 similar rows:  [11251]
11111111111111111111
incomplete name 3, col: 11251 row: []
col: 11253 similar rows:  [11253, 11254]
incomplete name 3, col: 11253 row: []
col: 11257 similar rows:  [11257]
11111111111111111111
incomplete name 3, col: 11257 row: []
col: 11264 similar rows:  [11264]
11111111111111111111
hotelname2 [11264]
wrong name!!!!
incomplete name 3, col: 11264 row: [11264]
col: 11265 similar rows:  [11265]
11111111111111111111
incomplete name 3, col: 11265 row: []
col: 11266 similar rows:  [11266, 12432, 12434]
incomplete name 3, col: 11266 row: []
col: 11268 similar rows:  [11268, 11484]
incomplete name 3, col: 11268 row: []
col: 11274 similar rows:  [11274, 12038]
incomplete name 3, col: 11274 row: []
col: 11277 similar rows:  [11277]
11111111111111111111
incomplete name 3, col: 11277 row: []
col: 11278 similar rows:  [11278]
11111111111111111111
incomplete name 3, col: 11278 row: []
col: 11291 similar rows:  [11291, 11909, 13194]
incomplete name 3, col: 11291 row: []
col: 11293 similar rows:  [11293]
11111111111111111111
incomplete name 3, col: 11293 row: []
col: 11294 similar rows:  [11294]
11111111111111111111
incomplete name 3, col: 11294 row: []
col: 11297 similar rows:  [11297]
11111111111111111111
hotelname2 [11297]
incomplete name 3, col: 11297 row: [11297]
col: 11298 similar rows:  [11298]
11111111111111111111
incomplete name 3, col: 11298 row: []
col: 11299 similar rows:  [11299]
11111111111111111111
incomplete name 3, col: 11299 row: []
col: 11300 similar rows:  [11300]
11111111111111111111
hotelname2 [11300]
incomplete name 3, col: 11300 row: [11300]
col: 11301 similar rows:  [11301]
11111111111111111111
incomplete name 3, col: 11301 row: []
col: 11302 similar rows:  [11302, 12068, 12578]
incomplete name 3, col: 11302 row: []
col: 11304 similar rows:  [11304]
11111111111111111111
incomplete name 3, col: 11304 row: []
col: 11309 similar rows:  [11309]
11111111111111111111
hotelname2 [11309]
incomplete name 3, col: 11309 row: [11309]
col: 11311 similar rows:  [11311]
11111111111111111111
hotelname2 [11311]
incomplete name 3, col: 11311 row: [11311]
col: 11314 similar rows:  [11314]
11111111111111111111
hotelname2 [11314]
incomplete name 3, col: 11314 row: [11314]
col: 11317 similar rows:  [11317, 13106, 13189, 13213]
incomplete name 3, col: 11317 row: []
col: 11318 similar rows:  [11318]
11111111111111111111
incomplete name 3, col: 11318 row: []
col: 11319 similar rows:  [11319, 11506, 11782, 12408, 12997]
incomplete name 3, col: 11319 row: []
col: 11322 similar rows:  [11322, 11323]
incomplete name 3, col: 11322 row: []
col: 11324 similar rows:  [11324]
11111111111111111111
hotelname2 [11324]
incomplete name 3, col: 11324 row: [11324]
col: 11330 similar rows:  [11330]
11111111111111111111
hotelname2 [11330]
wrong name!!!!
incomplete name 3, col: 11330 row: [11330]
col: 11331 similar rows:  [11331, 13150]
incomplete name 3, col: 11331 row: []
col: 11333 similar rows:  [11333]
11111111111111111111
incomplete name 3, col: 11333 row: []
col: 11335 similar rows:  [11335]
11111111111111111111
incomplete name 3, col: 11335 row: []
col: 11336 similar rows:  [11336]
11111111111111111111
incomplete name 3, col: 11336 row: []
col: 11337 similar rows:  [11337]
11111111111111111111
hotelname2 [11337]
incomplete name 3, col: 11337 row: []
col: 11338 similar rows:  [11338]
11111111111111111111
hotelname2 [11338]
incomplete name 3, col: 11338 row: []
col: 11339 similar rows:  [11339, 12397]
incomplete name 3, col: 11339 row: []
col: 11340 similar rows:  [11340]
11111111111111111111
incomplete name 3, col: 11340 row: []
col: 11341 similar rows:  [11341, 12033, 12267]
incomplete name 3, col: 11341 row: []
col: 11342 similar rows:  [11342]
11111111111111111111
hotelname2 [11342]
incomplete name 3, col: 11342 row: [11342]
col: 11343 similar rows:  [11343, 12112, 12932]
incomplete name 3, col: 11343 row: []
col: 11346 similar rows:  [11346]
11111111111111111111
hotelname2 [11346]
incomplete name 3, col: 11346 row: [11346]
col: 11350 similar rows:  [11350, 11351]
incomplete name 3, col: 11350 row: []
col: 11353 similar rows:  [11353]
11111111111111111111
incomplete name 3, col: 11353 row: []
col: 11358 similar rows:  [11358]
11111111111111111111
incomplete name 3, col: 11358 row: []
col: 11359 similar rows:  [11359]
11111111111111111111
incomplete name 3, col: 11359 row: []
col: 11360 similar rows:  [11360]
11111111111111111111
hotelname2 [11360]
incomplete name 3, col: 11360 row: [11360]
col: 11361 similar rows:  [11361, 11398, 12445]
incomplete name 3, col: 11361 row: []
col: 11362 similar rows:  [11362]
11111111111111111111
incomplete name 3, col: 11362 row: []
col: 11364 similar rows:  [11364]
11111111111111111111
hotelname2 [11364]
incomplete name 3, col: 11364 row: [11364]
col: 11366 similar rows:  [11366, 11667]
incomplete name 3, col: 11366 row: []
col: 11367 similar rows:  [11367]
11111111111111111111
hotelname2 [11367]
incomplete name 3, col: 11367 row: [11367]
col: 11368 similar rows:  [11368, 12889, 13202]
incomplete name 3, col: 11368 row: []
col: 11369 similar rows:  [11369, 11400, 11879, 12746]
incomplete name 3, col: 11369 row: []
col: 11372 similar rows:  [11372, 11867, 12116, 13133]
incomplete name 3, col: 11372 row: []
col: 11373 similar rows:  [11373]
11111111111111111111
incomplete name 3, col: 11373 row: []
col: 11374 similar rows:  [11374]
11111111111111111111
hotelname2 [11374]
incomplete name 3, col: 11374 row: [11374]
col: 11378 similar rows:  [11378]
11111111111111111111
incomplete name 3, col: 11378 row: []
col: 11380 similar rows:  [11380]
11111111111111111111
incomplete name 3, col: 11380 row: []
col: 11381 similar rows:  [11381]
11111111111111111111
hotelname2 [11381]
incomplete name 3, col: 11381 row: [11381]
col: 11383 similar rows:  [11383]
11111111111111111111
hotelname2 [11383]
wrong name!!!!
incomplete name 3, col: 11383 row: [11383]
col: 11385 similar rows:  [11385]
11111111111111111111
incomplete name 3, col: 11385 row: []
col: 11386 similar rows:  [11386]
11111111111111111111
incomplete name 3, col: 11386 row: []
col: 11388 similar rows:  [11388]
11111111111111111111
incomplete name 3, col: 11388 row: []
col: 11391 similar rows:  [11391, 12480]
incomplete name 3, col: 11391 row: []
col: 11393 similar rows:  [11393]
11111111111111111111
hotelname2 [11393]
incomplete name 3, col: 11393 row: [11393]
col: 11394 similar rows:  [11394]
11111111111111111111
incomplete name 3, col: 11394 row: []
col: 11395 similar rows:  [11395, 13177]
incomplete name 3, col: 11395 row: []
col: 11396 similar rows:  [11396]
11111111111111111111
incomplete name 3, col: 11396 row: []
col: 11397 similar rows:  [11397]
11111111111111111111
incomplete name 3, col: 11397 row: []
col: 11399 similar rows:  [11399, 11621, 11875, 13080, 13183, 13196]
incomplete name 3, col: 11399 row: []
col: 11403 similar rows:  [11403]
11111111111111111111
incomplete name 3, col: 11403 row: []
col: 11404 similar rows:  [11404]
11111111111111111111
incomplete name 3, col: 11404 row: []
col: 11405 similar rows:  [11405]
11111111111111111111
incomplete name 3, col: 11405 row: []
col: 11407 similar rows:  [11407, 12204]
incomplete name 3, col: 11407 row: []
col: 11409 similar rows:  [11409]
11111111111111111111
incomplete name 3, col: 11409 row: []
col: 11410 similar rows:  [11410]
11111111111111111111
incomplete name 3, col: 11410 row: []
col: 11411 similar rows:  [11411]
11111111111111111111
incomplete name 3, col: 11411 row: []
col: 11413 similar rows:  [11413, 12759, 12963]
incomplete name 3, col: 11413 row: []
col: 11414 similar rows:  [11414]
11111111111111111111
incomplete name 3, col: 11414 row: []
col: 11417 similar rows:  [11417]
11111111111111111111
incomplete name 3, col: 11417 row: []
col: 11419 similar rows:  [11419]
11111111111111111111
incomplete name 3, col: 11419 row: []
col: 11422 similar rows:  [11422]
11111111111111111111
incomplete name 3, col: 11422 row: []
col: 11425 similar rows:  [11425, 11453, 12214]
incomplete name 3, col: 11425 row: []
col: 11426 similar rows:  [11426, 13135]
incomplete name 3, col: 11426 row: []

col: 11427 similar rows:  [11427]
11111111111111111111
incomplete name 3, col: 11427 row: []
col: 11430 similar rows:  [11430]
11111111111111111111
hotelname2 [11430]
incomplete name 3, col: 11430 row: []
col: 11435 similar rows:  [11435, 12987]
incomplete name 3, col: 11435 row: []
col: 11437 similar rows:  [11437]
11111111111111111111
incomplete name 3, col: 11437 row: []
col: 11438 similar rows:  [11438]
11111111111111111111
incomplete name 3, col: 11438 row: []
col: 11439 similar rows:  [11439, 12789]
incomplete name 3, col: 11439 row: []
col: 11440 similar rows:  [11440]
11111111111111111111
hotelname2 [11440]
incomplete name 3, col: 11440 row: []
col: 11441 similar rows:  [11441, 11904]
incomplete name 3, col: 11441 row: []
col: 11442 similar rows:  [11442]
11111111111111111111
incomplete name 3, col: 11442 row: []
col: 11445 similar rows:  [11445]
11111111111111111111
incomplete name 3, col: 11445 row: []
col: 11447 similar rows:  [11447]
11111111111111111111
incomplete name 3, col: 11447 row: []
col: 11448 similar rows:  [11448]
11111111111111111111
hotelname2 [11448]
incomplete name 3, col: 11448 row: []
col: 11450 similar rows:  [11450]
11111111111111111111
incomplete name 3, col: 11450 row: []
col: 11451 similar rows:  [11451]
11111111111111111111
hotelname2 [11451]
incomplete name 3, col: 11451 row: []
col: 11455 similar rows:  [11455, 12541]
incomplete name 3, col: 11455 row: []
col: 11456 similar rows:  [11456, 11618, 11900, 11919, 11953, 12279, 12721, 13022]
incomplete name 3, col: 11456 row: []
col: 11458 similar rows:  [11458]
11111111111111111111
incomplete name 3, col: 11458 row: []
col: 11459 similar rows:  [11459]
11111111111111111111
incomplete name 3, col: 11459 row: []
col: 11460 similar rows:  [11460]
11111111111111111111
hotelname2 [11460]
incomplete name 3, col: 11460 row: [11460]
col: 11461 similar rows:  [11461, 11536, 11548, 12213, 12576, 13159]
incomplete name 3, col: 11461 row: []
col: 11462 similar rows:  [11462, 13121]
incomplete name 3, col: 11462 row: []
col: 11464 similar rows:  [11464]
11111111111111111111
incomplete name 3, col: 11464 row: []
col: 11466 similar rows:  [11466]
11111111111111111111
incomplete name 3, col: 11466 row: []
col: 11467 similar rows:  [11467]
11111111111111111111
incomplete name 3, col: 11467 row: []
col: 11470 similar rows:  [11470]
11111111111111111111
incomplete name 3, col: 11470 row: []
col: 11471 similar rows:  [11471]
11111111111111111111
incomplete name 3, col: 11471 row: []
col: 11472 similar rows:  [11472, 13212]
incomplete name 3, col: 11472 row: []
col: 11473 similar rows:  [11473]
11111111111111111111
incomplete name 3, col: 11473 row: []
col: 11474 similar rows:  [11474]
11111111111111111111
incomplete name 3, col: 11474 row: []
col: 11477 similar rows:  [11477, 11568, 13070]
incomplete name 3, col: 11477 row: []
col: 11478 similar rows:  [11478]
11111111111111111111
hotelname2 [11478]
incomplete name 3, col: 11478 row: [11478]
col: 11479 similar rows:  [11479]
11111111111111111111
incomplete name 3, col: 11479 row: []
col: 11482 similar rows:  [11482]
11111111111111111111
incomplete name 3, col: 11482 row: []
col: 11483 similar rows:  [11483]
11111111111111111111
incomplete name 3, col: 11483 row: []
col: 11485 similar rows:  [11485, 11748]
incomplete name 3, col: 11485 row: []
col: 11486 similar rows:  [11486]
11111111111111111111
incomplete name 3, col: 11486 row: []
col: 11487 similar rows:  [11487, 13066]
incomplete name 3, col: 11487 row: []
col: 11488 similar rows:  [11488]
11111111111111111111
incomplete name 3, col: 11488 row: []
col: 11492 similar rows:  [11492]
11111111111111111111
incomplete name 3, col: 11492 row: []
col: 11493 similar rows:  [11493]
11111111111111111111
incomplete name 3, col: 11493 row: []
col: 11494 similar rows:  [11494]
11111111111111111111
incomplete name 3, col: 11494 row: []
col: 11495 similar rows:  [11495]
11111111111111111111
incomplete name 3, col: 11495 row: []
col: 11496 similar rows:  [11496]
11111111111111111111
incomplete name 3, col: 11496 row: []
col: 11497 similar rows:  [11497]
11111111111111111111
incomplete name 3, col: 11497 row: []
col: 11498 similar rows:  [11498, 11622]
incomplete name 3, col: 11498 row: []
col: 11499 similar rows:  [11499]
11111111111111111111
incomplete name 3, col: 11499 row: []
col: 11500 similar rows:  [11500]
11111111111111111111
hotelname2 [11500]
incomplete name 3, col: 11500 row: []
col: 11502 similar rows:  [11502]
11111111111111111111
incomplete name 3, col: 11502 row: []
col: 11503 similar rows:  [11503]
11111111111111111111
incomplete name 3, col: 11503 row: []
col: 11504 similar rows:  [11504]
11111111111111111111
incomplete name 3, col: 11504 row: []
col: 11505 similar rows:  [11505]
11111111111111111111
hotelname2 [11505]
incomplete name 3, col: 11505 row: []
col: 11507 similar rows:  [11507]
11111111111111111111
incomplete name 3, col: 11507 row: []
col: 11508 similar rows:  [11508]
11111111111111111111
incomplete name 3, col: 11508 row: []
col: 11509 similar rows:  [11509]
11111111111111111111
incomplete name 3, col: 11509 row: []
col: 11510 similar rows:  [11510]
11111111111111111111
incomplete name 3, col: 11510 row: []
col: 11511 similar rows:  [11511]
11111111111111111111
incomplete name 3, col: 11511 row: []
col: 11512 similar rows:  [11512]
11111111111111111111
incomplete name 3, col: 11512 row: []
col: 11513 similar rows:  [11513]
11111111111111111111
incomplete name 3, col: 11513 row: []
col: 11516 similar rows:  [11516, 11633, 11653, 12280, 12336, 12881, 13063]
incomplete name 3, col: 11516 row: []
col: 11518 similar rows:  [11518]
11111111111111111111
incomplete name 3, col: 11518 row: []
col: 11522 similar rows:  [11522]
11111111111111111111
incomplete name 3, col: 11522 row: []
col: 11523 similar rows:  [11523]
11111111111111111111
incomplete name 3, col: 11523 row: []
col: 11528 similar rows:  [11528]
11111111111111111111
incomplete name 3, col: 11528 row: []
col: 11529 similar rows:  [11529]
11111111111111111111
hotelname2 [11529]
incomplete name 3, col: 11529 row: [11529]
col: 11535 similar rows:  [11535]
11111111111111111111
incomplete name 3, col: 11535 row: []
col: 11537 similar rows:  [11537, 12648, 12859, 12907]
incomplete name 3, col: 11537 row: []
col: 11545 similar rows:  [11545]
11111111111111111111
incomplete name 3, col: 11545 row: []
col: 11546 similar rows:  [11546, 11996, 12500, 13090]
incomplete name 3, col: 11546 row: []
col: 11553 similar rows:  [11553, 12283, 12708]
incomplete name 3, col: 11553 row: []
col: 11554 similar rows:  [11554]
11111111111111111111
incomplete name 3, col: 11554 row: []
col: 11556 similar rows:  [11556]
11111111111111111111
incomplete name 3, col: 11556 row: []
col: 11557 similar rows:  [11557]
11111111111111111111
incomplete name 3, col: 11557 row: []
col: 11559 similar rows:  [11559]
11111111111111111111
incomplete name 3, col: 11559 row: []
col: 11560 similar rows:  [11560]
11111111111111111111
hotelname2 [11560]
wrong name!!!!
incomplete name 3, col: 11560 row: [11560]
col: 11561 similar rows:  [11561, 11572]
incomplete name 3, col: 11561 row: []
col: 11564 similar rows:  [11564, 12016, 12920, 12948, 13062, 13125]
incomplete name 3, col: 11564 row: []
col: 11565 similar rows:  [11565]
11111111111111111111
incomplete name 3, col: 11565 row: []
col: 11566 similar rows:  [11566, 11869, 11870, 12465, 12739, 13047]
incomplete name 3, col: 11566 row: []
col: 11569 similar rows:  [11569]
11111111111111111111
incomplete name 3, col: 11569 row: []
col: 11573 similar rows:  [11573]
11111111111111111111
incomplete name 3, col: 11573 row: []
col: 11575 similar rows:  [11575]
11111111111111111111
incomplete name 3, col: 11575 row: []
col: 11577 similar rows:  [11577]
11111111111111111111
incomplete name 3, col: 11577 row: []
col: 11578 similar rows:  [11578, 12759, 12963]
incomplete name 3, col: 11578 row: []
col: 11582 similar rows:  [11582]
11111111111111111111
incomplete name 3, col: 11582 row: []
col: 11589 similar rows:  [11589]
11111111111111111111
incomplete name 3, col: 11589 row: []
col: 11591 similar rows:  [11591, 11857, 11906]
incomplete name 3, col: 11591 row: []
col: 11592 similar rows:  [11592]
11111111111111111111
incomplete name 3, col: 11592 row: []
col: 11596 similar rows:  [11596, 12378, 12955]
incomplete name 3, col: 11596 row: []

col: 11597 similar rows:  [11597]
11111111111111111111
hotelname2 [11597]
incomplete name 3, col: 11597 row: [11597]
col: 11598 similar rows:  [11598]
11111111111111111111
incomplete name 3, col: 11598 row: []
col: 11599 similar rows:  [11599]
11111111111111111111
incomplete name 3, col: 11599 row: []
col: 11600 similar rows:  [11600]
11111111111111111111
incomplete name 3, col: 11600 row: []
col: 11604 similar rows:  [11604, 11684, 12014, 13031, 13158, 13205, 13225]
incomplete name 3, col: 11604 row: []
col: 11605 similar rows:  [11605]
11111111111111111111
incomplete name 3, col: 11605 row: []
col: 11611 similar rows:  [11611, 12596, 12936]
hotelname2 [12936]
incomplete name 3, col: 11611 row: []
col: 11612 similar rows:  [11612]
11111111111111111111
incomplete name 3, col: 11612 row: []
col: 11613 similar rows:  [11613]
11111111111111111111
incomplete name 3, col: 11613 row: []
col: 11615 similar rows:  [11615]
11111111111111111111
incomplete name 3, col: 11615 row: []
col: 11619 similar rows:  [11619]
11111111111111111111
incomplete name 3, col: 11619 row: []
col: 11620 similar rows:  [11620]
11111111111111111111
hotelname2 [11620]
incomplete name 3, col: 11620 row: []
col: 11624 similar rows:  [11624, 12153, 13058]
incomplete name 3, col: 11624 row: []
col: 11625 similar rows:  [11625]
11111111111111111111
incomplete name 3, col: 11625 row: []
col: 11626 similar rows:  [11626]
11111111111111111111
incomplete name 3, col: 11626 row: []
col: 11629 similar rows:  [11629, 11757, 12319, 12988, 13124]
incomplete name 3, col: 11629 row: []
col: 11632 similar rows:  [11632]
11111111111111111111
hotelname2 [11632]
incomplete name 3, col: 11632 row: [11632]
col: 11635 similar rows:  [11635]
11111111111111111111
incomplete name 3, col: 11635 row: []
col: 11636 similar rows:  [11636, 12639, 12653, 12825, 13021, 13170]
incomplete name 3, col: 11636 row: []
col: 11646 similar rows:  [11646, 13093]
incomplete name 3, col: 11646 row: []
col: 11648 similar rows:  [11648]
11111111111111111111
incomplete name 3, col: 11648 row: []
col: 11649 similar rows:  [11649, 12657]
incomplete name 3, col: 11649 row: []
col: 11652 similar rows:  [11652, 12951, 13032]
incomplete name 3, col: 11652 row: []
col: 11654 similar rows:  [11654]
11111111111111111111
incomplete name 3, col: 11654 row: []
col: 11663 similar rows:  [11663]
11111111111111111111
incomplete name 3, col: 11663 row: []
col: 11666 similar rows:  [11666]
11111111111111111111
incomplete name 3, col: 11666 row: []
col: 11671 similar rows:  [11671]
11111111111111111111
incomplete name 3, col: 11671 row: []
col: 11673 similar rows:  [11673]
11111111111111111111
incomplete name 3, col: 11673 row: []
col: 11676 similar rows:  [11676, 12323, 12479, 12891, 12909, 12937]
incomplete name 3, col: 11676 row: []
col: 11679 similar rows:  [11679]
11111111111111111111
incomplete name 3, col: 11679 row: []
col: 11681 similar rows:  [11681, 11893, 12673]
incomplete name 3, col: 11681 row: []
col: 11682 similar rows:  [11682]
11111111111111111111
incomplete name 3, col: 11682 row: []
col: 11683 similar rows:  [11683, 12079]
incomplete name 3, col: 11683 row: []
col: 11686 similar rows:  [11686, 11712]
incomplete name 3, col: 11686 row: []
col: 11689 similar rows:  [11689]
11111111111111111111
incomplete name 3, col: 11689 row: []
col: 11690 similar rows:  [11690]
11111111111111111111
incomplete name 3, col: 11690 row: []
col: 11691 similar rows:  [11691]
11111111111111111111
incomplete name 3, col: 11691 row: []
col: 11692 similar rows:  [11692, 12474, 12895]
incomplete name 3, col: 11692 row: []
col: 11693 similar rows:  [11693]
11111111111111111111
incomplete name 3, col: 11693 row: []
col: 11694 similar rows:  [11694]
11111111111111111111
incomplete name 3, col: 11694 row: []
col: 11698 similar rows:  [11698]
11111111111111111111
incomplete name 3, col: 11698 row: []
col: 11700 similar rows:  [11700]
11111111111111111111
incomplete name 3, col: 11700 row: []
col: 11701 similar rows:  [11701]
11111111111111111111
incomplete name 3, col: 11701 row: []
col: 11704 similar rows:  [11704]
11111111111111111111
incomplete name 3, col: 11704 row: []
col: 11705 similar rows:  [11705]
11111111111111111111
incomplete name 3, col: 11705 row: []
col: 11706 similar rows:  [11706]
11111111111111111111
incomplete name 3, col: 11706 row: []
col: 11707 similar rows:  [11707]
11111111111111111111
incomplete name 3, col: 11707 row: []
col: 11708 similar rows:  [11708]
11111111111111111111
incomplete name 3, col: 11708 row: []
col: 11711 similar rows:  [11711]
11111111111111111111
incomplete name 3, col: 11711 row: []
col: 11713 similar rows:  [11713, 11884, 12326, 12493, 13005, 13019, 13131]
incomplete name 3, col: 11713 row: []
col: 11716 similar rows:  [11716]
11111111111111111111
hotelname2 [11716]
incomplete name 3, col: 11716 row: [11716]
col: 11723 similar rows:  [11723]
11111111111111111111
incomplete name 3, col: 11723 row: []
col: 11724 similar rows:  [11724, 12573]
incomplete name 3, col: 11724 row: []
col: 11727 similar rows:  [11727]
11111111111111111111
incomplete name 3, col: 11727 row: []
col: 11732 similar rows:  [11732]
11111111111111111111
hotelname2 [11732]
incomplete name 3, col: 11732 row: [11732]
col: 11733 similar rows:  [11733]
11111111111111111111
hotelname2 [11733]
incomplete name 3, col: 11733 row: [11733]
col: 11737 similar rows:  [11737, 12917]
incomplete name 3, col: 11737 row: []
col: 11741 similar rows:  [11741]
11111111111111111111
incomplete name 3, col: 11741 row: []
col: 11746 similar rows:  [11746]
11111111111111111111
incomplete name 3, col: 11746 row: []
col: 11747 similar rows:  [11747, 13128]
incomplete name 3, col: 11747 row: []
col: 11749 similar rows:  [11749]
11111111111111111111
incomplete name 3, col: 11749 row: []
col: 11750 similar rows:  [11750]
11111111111111111111
incomplete name 3, col: 11750 row: []
col: 11751 similar rows:  [11751]
11111111111111111111
incomplete name 3, col: 11751 row: []
col: 11752 similar rows:  [11752]
11111111111111111111
hotelname2 [11752]
incomplete name 3, col: 11752 row: [11752]
col: 11753 similar rows:  [11753]
11111111111111111111
incomplete name 3, col: 11753 row: []
col: 11755 similar rows:  [11755]
11111111111111111111
hotelname2 [11755]
wrong name!!!!
incomplete name 3, col: 11755 row: [11755]
col: 11758 similar rows:  [11758]
11111111111111111111
hotelname2 [11758]
incomplete name 3, col: 11758 row: []
col: 11759 similar rows:  [11759]
11111111111111111111
hotelname2 [11759]
incomplete name 3, col: 11759 row: [11759]
col: 11760 similar rows:  [11760]
11111111111111111111
incomplete name 3, col: 11760 row: []
col: 11761 similar rows:  [11761]
11111111111111111111
incomplete name 3, col: 11761 row: []
col: 11764 similar rows:  [11764]
11111111111111111111
incomplete name 3, col: 11764 row: []
col: 11765 similar rows:  [11765]
11111111111111111111
incomplete name 3, col: 11765 row: []
col: 11766 similar rows:  [11766, 13208]
incomplete name 3, col: 11766 row: []
col: 11768 similar rows:  [11768, 12790]
incomplete name 3, col: 11768 row: []
col: 11769 similar rows:  [11769]
11111111111111111111
hotelname2 [11769]
incomplete name 3, col: 11769 row: [11769]
col: 11772 similar rows:  [11772]
11111111111111111111
incomplete name 3, col: 11772 row: []
col: 11773 similar rows:  [11773, 11822, 11975, 11976, 12103, 12797, 12885]
incomplete name 3, col: 11773 row: []
col: 11776 similar rows:  [11776]
11111111111111111111
hotelname2 [11776]
incomplete name 3, col: 11776 row: [11776]
col: 11779 similar rows:  [11779]
11111111111111111111
hotelname2 [11779]
incomplete name 3, col: 11779 row: [11779]
col: 11780 similar rows:  [11780, 12641]
incomplete name 3, col: 11780 row: []
col: 11784 similar rows:  [11784]
11111111111111111111
incomplete name 3, col: 11784 row: []
col: 11786 similar rows:  [11786]
11111111111111111111
incomplete name 3, col: 11786 row: []
col: 11788 similar rows:  [11788]
11111111111111111111
hotelname2 [11788]
incomplete name 3, col: 11788 row: [11788]
col: 11795 similar rows:  [11795]
11111111111111111111
incomplete name 3, col: 11795 row: []
col: 11798 similar rows:  [11798]
11111111111111111111
hotelname2 [11798]
incomplete name 3, col: 11798 row: [11798]
col: 11800 similar rows:  [11800]
11111111111111111111
incomplete name 3, col: 11800 row: []
col: 11801 similar rows:  [11801]
11111111111111111111
hotelname2 [11801]
incomplete name 3, col: 11801 row: [11801]

col: 11805 similar rows:  [11805]
11111111111111111111
incomplete name 3, col: 11805 row: []
col: 11808 similar rows:  [11808]
11111111111111111111
incomplete name 3, col: 11808 row: []
col: 11809 similar rows:  [11809, 11974, 12357]
incomplete name 3, col: 11809 row: []
col: 11812 similar rows:  [11812]
11111111111111111111
incomplete name 3, col: 11812 row: []
col: 11813 similar rows:  [11813, 11814]
incomplete name 3, col: 11813 row: []
col: 11820 similar rows:  [11820]
11111111111111111111
incomplete name 3, col: 11820 row: []
col: 11821 similar rows:  [11821]
11111111111111111111
incomplete name 3, col: 11821 row: []
col: 11825 similar rows:  [11825]
11111111111111111111
incomplete name 3, col: 11825 row: []
col: 11827 similar rows:  [11827]
11111111111111111111
hotelname2 [11827]
incomplete name 3, col: 11827 row: [11827]
col: 11828 similar rows:  [11828, 12374]
incomplete name 3, col: 11828 row: []
col: 11830 similar rows:  [11830, 11860]
incomplete name 3, col: 11830 row: []
col: 11835 similar rows:  [11835]
11111111111111111111
incomplete name 3, col: 11835 row: []
col: 11836 similar rows:  [11836]
11111111111111111111
incomplete name 3, col: 11836 row: []
col: 11838 similar rows:  [11838, 11904, 12316, 12400]
incomplete name 3, col: 11838 row: []
col: 11840 similar rows:  [11840]
11111111111111111111
incomplete name 3, col: 11840 row: []
col: 11843 similar rows:  [11843, 11891]
incomplete name 3, col: 11843 row: []
col: 11845 similar rows:  [11845]
11111111111111111111
incomplete name 3, col: 11845 row: []
col: 11849 similar rows:  [11849, 11852, 12457]
incomplete name 3, col: 11849 row: []
col: 11850 similar rows:  [11850]
11111111111111111111
hotelname2 [11850]
incomplete name 3, col: 11850 row: [11850]
col: 11851 similar rows:  [11851]
11111111111111111111
hotelname2 [11851]
incomplete name 3, col: 11851 row: [11851]
col: 11853 similar rows:  [11853, 12845]
incomplete name 3, col: 11853 row: []
col: 11858 similar rows:  [11858]
11111111111111111111
incomplete name 3, col: 11858 row: []
col: 11862 similar rows:  [11862]
11111111111111111111
incomplete name 3, col: 11862 row: []
col: 11864 similar rows:  [11864]
11111111111111111111
incomplete name 3, col: 11864 row: []
col: 11866 similar rows:  [11866, 11895, 12046]
incomplete name 3, col: 11866 row: []
col: 11871 similar rows:  [11871]
11111111111111111111
hotelname2 [11871]
incomplete name 3, col: 11871 row: [11871]
col: 11877 similar rows:  [11877, 12022]
incomplete name 3, col: 11877 row: []
col: 11878 similar rows:  [11878]
11111111111111111111
incomplete name 3, col: 11878 row: []
col: 11880 similar rows:  [11880]
11111111111111111111
incomplete name 3, col: 11880 row: []
col: 11883 similar rows:  [11883]
11111111111111111111
incomplete name 3, col: 11883 row: []
col: 11885 similar rows:  [11885, 11928]
incomplete name 3, col: 11885 row: []
col: 11887 similar rows:  [11887]
11111111111111111111
incomplete name 3, col: 11887 row: []
col: 11888 similar rows:  [11888, 11916]
incomplete name 3, col: 11888 row: []
col: 11889 similar rows:  [11889]
11111111111111111111
incomplete name 3, col: 11889 row: []
col: 11890 similar rows:  [11890]
11111111111111111111
incomplete name 3, col: 11890 row: []
col: 11892 similar rows:  [11892, 13065, 13172]
incomplete name 3, col: 11892 row: []
col: 11894 similar rows:  [11894]
11111111111111111111
hotelname2 [11894]
incomplete name 3, col: 11894 row: [11894]
col: 11897 similar rows:  [11897]
11111111111111111111
incomplete name 3, col: 11897 row: []
col: 11903 similar rows:  [11903, 12815, 12826]
incomplete name 3, col: 11903 row: []
col: 11905 similar rows:  [11905]
11111111111111111111
incomplete name 3, col: 11905 row: []
col: 11911 similar rows:  [11911]
11111111111111111111
incomplete name 3, col: 11911 row: []
col: 11920 similar rows:  [11920]
11111111111111111111
hotelname2 [11920]
incomplete name 3, col: 11920 row: []
col: 11921 similar rows:  [11921]
11111111111111111111
hotelname2 [11921]
incomplete name 3, col: 11921 row: [11921]
col: 11926 similar rows:  [11926]
11111111111111111111
incomplete name 3, col: 11926 row: []
col: 11930 similar rows:  [11930]
11111111111111111111
incomplete name 3, col: 11930 row: []
col: 11932 similar rows:  [11932]
11111111111111111111
incomplete name 3, col: 11932 row: []
col: 11933 similar rows:  [11933]
11111111111111111111
hotelname2 [11933]
incomplete name 3, col: 11933 row: [11933]
col: 11934 similar rows:  [11934]
11111111111111111111
incomplete name 3, col: 11934 row: []
col: 11935 similar rows:  [11935]
11111111111111111111
incomplete name 3, col: 11935 row: []
col: 11936 similar rows:  [11936]
11111111111111111111
incomplete name 3, col: 11936 row: []
col: 11937 similar rows:  [11937]
11111111111111111111
incomplete name 3, col: 11937 row: []
col: 11941 similar rows:  [11941]
11111111111111111111
incomplete name 3, col: 11941 row: []
col: 11942 similar rows:  [11942]
11111111111111111111
incomplete name 3, col: 11942 row: []
col: 11947 similar rows:  [11947]
11111111111111111111
incomplete name 3, col: 11947 row: []
col: 11949 similar rows:  [11949]
11111111111111111111
incomplete name 3, col: 11949 row: []
col: 11952 similar rows:  [11952, 12043]
incomplete name 3, col: 11952 row: []
col: 11954 similar rows:  [11954]
11111111111111111111
incomplete name 3, col: 11954 row: []
col: 11955 similar rows:  [11955, 13098]
incomplete name 3, col: 11955 row: []
col: 11956 similar rows:  [11956]
11111111111111111111
incomplete name 3, col: 11956 row: []
col: 11957 similar rows:  [11957]
11111111111111111111
hotelname2 [11957]
incomplete name 3, col: 11957 row: [11957]
col: 11959 similar rows:  [11959, 12703]
incomplete name 3, col: 11959 row: []
col: 11962 similar rows:  [11962]
11111111111111111111
incomplete name 3, col: 11962 row: []
col: 11963 similar rows:  [11963]
11111111111111111111
incomplete name 3, col: 11963 row: []
col: 11966 similar rows:  [11966, 12689, 12692, 12865, 12874]
incomplete name 3, col: 11966 row: []
col: 11972 similar rows:  [11972]
11111111111111111111
hotelname2 [11972]
incomplete name 3, col: 11972 row: []
col: 11984 similar rows:  [11984]
11111111111111111111
incomplete name 3, col: 11984 row: []
col: 11987 similar rows:  [11987]
11111111111111111111
incomplete name 3, col: 11987 row: []
col: 11990 similar rows:  [11990]
11111111111111111111
incomplete name 3, col: 11990 row: []
col: 11991 similar rows:  [11991]
11111111111111111111
incomplete name 3, col: 11991 row: []
col: 11993 similar rows:  [11993]
11111111111111111111
incomplete name 3, col: 11993 row: []
col: 11994 similar rows:  [11994]
11111111111111111111
incomplete name 3, col: 11994 row: []
col: 11995 similar rows:  [11995]
11111111111111111111
incomplete name 3, col: 11995 row: []
col: 11998 similar rows:  [11998]
11111111111111111111
incomplete name 3, col: 11998 row: []
col: 12003 similar rows:  [12003]
11111111111111111111
incomplete name 3, col: 12003 row: []
col: 12005 similar rows:  [12005]
11111111111111111111
incomplete name 3, col: 12005 row: []
col: 12006 similar rows:  [12006]
11111111111111111111
incomplete name 3, col: 12006 row: []
col: 12009 similar rows:  [12009]
11111111111111111111
incomplete name 3, col: 12009 row: []
col: 12011 similar rows:  [12011]
11111111111111111111
incomplete name 3, col: 12011 row: []
col: 12015 similar rows:  [12015]
11111111111111111111
incomplete name 3, col: 12015 row: []
col: 12017 similar rows:  [12017]
11111111111111111111
incomplete name 3, col: 12017 row: []
col: 12019 similar rows:  [12019]
11111111111111111111
incomplete name 3, col: 12019 row: []
col: 12020 similar rows:  [12020]
11111111111111111111
incomplete name 3, col: 12020 row: []
col: 12023 similar rows:  [12023]
11111111111111111111
incomplete name 3, col: 12023 row: []
col: 12024 similar rows:  [12024]
11111111111111111111
incomplete name 3, col: 12024 row: []
col: 12026 similar rows:  [12026]
11111111111111111111
hotelname2 [12026]
incomplete name 3, col: 12026 row: []
col: 12031 similar rows:  [12031, 12975]
incomplete name 3, col: 12031 row: []
col: 12034 similar rows:  [12034]
11111111111111111111
incomplete name 3, col: 12034 row: []
col: 12040 similar rows:  [12040]
11111111111111111111
hotelname2 [12040]
incomplete name 3, col: 12040 row: []

col: 12047 similar rows:  [12047]
11111111111111111111
incomplete name 3, col: 12047 row: []
col: 12048 similar rows:  [12048]
11111111111111111111
hotelname2 [12048]
wrong name!!!!
incomplete name 3, col: 12048 row: [12048]
col: 12049 similar rows:  [12049, 12069, 12099, 12705, 12852]
incomplete name 3, col: 12049 row: []
col: 12050 similar rows:  [12050]
11111111111111111111
hotelname2 [12050]
incomplete name 3, col: 12050 row: []
col: 12051 similar rows:  [12051]
11111111111111111111
incomplete name 3, col: 12051 row: []
col: 12054 similar rows:  [12054, 12419, 13104]
incomplete name 3, col: 12054 row: []
col: 12060 similar rows:  [12060]
11111111111111111111
incomplete name 3, col: 12060 row: []
col: 12061 similar rows:  [12061]
11111111111111111111
hotelname2 [12061]
incomplete name 3, col: 12061 row: [12061]
col: 12062 similar rows:  [12062]
11111111111111111111
incomplete name 3, col: 12062 row: []
col: 12063 similar rows:  [12063]
11111111111111111111
incomplete name 3, col: 12063 row: []
col: 12067 similar rows:  [12067]
11111111111111111111
hotelname2 [12067]
incomplete name 3, col: 12067 row: [12067]
col: 12070 similar rows:  [12070, 12170, 13016]
incomplete name 3, col: 12070 row: []
col: 12073 similar rows:  [12073]
11111111111111111111
hotelname2 [12073]
incomplete name 3, col: 12073 row: []
col: 12074 similar rows:  [12074]
11111111111111111111
hotelname2 [12074]
incomplete name 3, col: 12074 row: []
col: 12076 similar rows:  [12076]
11111111111111111111
incomplete name 3, col: 12076 row: []
col: 12081 similar rows:  [12081]
11111111111111111111
incomplete name 3, col: 12081 row: []
col: 12082 similar rows:  [12082]
11111111111111111111
incomplete name 3, col: 12082 row: []
col: 12083 similar rows:  [12083]
11111111111111111111
incomplete name 3, col: 12083 row: []
col: 12084 similar rows:  [12084]
11111111111111111111
incomplete name 3, col: 12084 row: []
col: 12086 similar rows:  [12086, 12444]
incomplete name 3, col: 12086 row: []
col: 12087 similar rows:  [12087]
11111111111111111111
incomplete name 3, col: 12087 row: []
col: 12089 similar rows:  [12089, 12092]
incomplete name 3, col: 12089 row: []
col: 12090 similar rows:  [12090]
11111111111111111111
incomplete name 3, col: 12090 row: []
col: 12091 similar rows:  [12091]
11111111111111111111
incomplete name 3, col: 12091 row: []
col: 12093 similar rows:  [12093, 12561]
incomplete name 3, col: 12093 row: []
col: 12096 similar rows:  [12096]
11111111111111111111
hotelname2 [12096]
incomplete name 3, col: 12096 row: []
col: 12097 similar rows:  [12097]
11111111111111111111
incomplete name 3, col: 12097 row: []
col: 12101 similar rows:  [12101]
11111111111111111111
incomplete name 3, col: 12101 row: []
col: 12104 similar rows:  [12104]
11111111111111111111
incomplete name 3, col: 12104 row: []
col: 12107 similar rows:  [12107]
11111111111111111111
incomplete name 3, col: 12107 row: []
col: 12108 similar rows:  [12108]
11111111111111111111
incomplete name 3, col: 12108 row: []
col: 12109 similar rows:  [12109, 12685, 12690, 12771]
incomplete name 3, col: 12109 row: []
col: 12110 similar rows:  [12110]
11111111111111111111
incomplete name 3, col: 12110 row: []
col: 12111 similar rows:  [12111]
11111111111111111111
hotelname2 [12111]
incomplete name 3, col: 12111 row: [12111]
col: 12119 similar rows:  [12119]
11111111111111111111
incomplete name 3, col: 12119 row: []
col: 12121 similar rows:  [12121]
11111111111111111111
hotelname2 [12121]
incomplete name 3, col: 12121 row: []
col: 12122 similar rows:  [12122, 12322]
incomplete name 3, col: 12122 row: []
col: 12126 similar rows:  [12126]
11111111111111111111
incomplete name 3, col: 12126 row: []
col: 12128 similar rows:  [12128]
11111111111111111111
incomplete name 3, col: 12128 row: []
col: 12130 similar rows:  [12130]
11111111111111111111
incomplete name 3, col: 12130 row: []
col: 12131 similar rows:  [12131]
11111111111111111111
incomplete name 3, col: 12131 row: []
col: 12132 similar rows:  [12132]
11111111111111111111
incomplete name 3, col: 12132 row: []
col: 12134 similar rows:  [12134]
11111111111111111111
incomplete name 3, col: 12134 row: []
col: 12135 similar rows:  [12135]
11111111111111111111
hotelname2 [12135]
incomplete name 3, col: 12135 row: [12135]
col: 12136 similar rows:  [12136]
11111111111111111111
incomplete name 3, col: 12136 row: []
col: 12137 similar rows:  [12137]
11111111111111111111
incomplete name 3, col: 12137 row: []
col: 12140 similar rows:  [12140]
11111111111111111111
incomplete name 3, col: 12140 row: []
col: 12142 similar rows:  [12142]
11111111111111111111
incomplete name 3, col: 12142 row: []
col: 12143 similar rows:  [12143]
11111111111111111111
incomplete name 3, col: 12143 row: []
col: 12147 similar rows:  [12147]
11111111111111111111
incomplete name 3, col: 12147 row: []
col: 12149 similar rows:  [12149]
11111111111111111111
incomplete name 3, col: 12149 row: []
col: 12154 similar rows:  [12154]
11111111111111111111
incomplete name 3, col: 12154 row: []
col: 12155 similar rows:  [12155]
11111111111111111111
hotelname2 [12155]
incomplete name 3, col: 12155 row: []
col: 12158 similar rows:  [12158]
11111111111111111111
incomplete name 3, col: 12158 row: []
col: 12164 similar rows:  [12164]
11111111111111111111
hotelname2 [12164]
incomplete name 3, col: 12164 row: [12164]
col: 12165 similar rows:  [12165, 12974]
incomplete name 3, col: 12165 row: []
col: 12166 similar rows:  [12166]
11111111111111111111
incomplete name 3, col: 12166 row: []
col: 12169 similar rows:  [12169]
11111111111111111111
incomplete name 3, col: 12169 row: []
col: 12177 similar rows:  [12177]
11111111111111111111
incomplete name 3, col: 12177 row: []
col: 12178 similar rows:  [12178]
11111111111111111111
incomplete name 3, col: 12178 row: []
col: 12179 similar rows:  [12179, 12180, 12182, 12183, 12215, 12226, 12228, 12230]
incomplete name 3, col: 12179 row: []
col: 12181 similar rows:  [12181]
11111111111111111111
incomplete name 3, col: 12181 row: []
col: 12185 similar rows:  [12185, 12441]
incomplete name 3, col: 12185 row: []
col: 12187 similar rows:  [12187]
11111111111111111111
hotelname2 [12187]
incomplete name 3, col: 12187 row: []
col: 12188 similar rows:  [12188]
11111111111111111111
incomplete name 3, col: 12188 row: []
col: 12189 similar rows:  [12189]
11111111111111111111
incomplete name 3, col: 12189 row: []
col: 12191 similar rows:  [12191]
11111111111111111111
incomplete name 3, col: 12191 row: []
col: 12193 similar rows:  [12193]
11111111111111111111
incomplete name 3, col: 12193 row: []
col: 12194 similar rows:  [12194]
11111111111111111111
incomplete name 3, col: 12194 row: []
col: 12196 similar rows:  [12196]
11111111111111111111
incomplete name 3, col: 12196 row: []
col: 12197 similar rows:  [12197]
11111111111111111111
incomplete name 3, col: 12197 row: []
col: 12198 similar rows:  [12198]
11111111111111111111
incomplete name 3, col: 12198 row: []
col: 12199 similar rows:  [12199]
11111111111111111111
incomplete name 3, col: 12199 row: []
col: 12200 similar rows:  [12200]
11111111111111111111
incomplete name 3, col: 12200 row: []
col: 12201 similar rows:  [12201]
11111111111111111111
incomplete name 3, col: 12201 row: []
col: 12202 similar rows:  [12202]
11111111111111111111
incomplete name 3, col: 12202 row: []
col: 12205 similar rows:  [12205]
11111111111111111111
incomplete name 3, col: 12205 row: []
col: 12206 similar rows:  [12206]
11111111111111111111
incomplete name 3, col: 12206 row: []
col: 12207 similar rows:  [12207]
11111111111111111111
incomplete name 3, col: 12207 row: []
col: 12209 similar rows:  [12209]
11111111111111111111
incomplete name 3, col: 12209 row: []
col: 12210 similar rows:  [12210, 12263, 13101]
incomplete name 3, col: 12210 row: []
col: 12212 similar rows:  [12212]
11111111111111111111
hotelname2 [12212]
incomplete name 3, col: 12212 row: [12212]
col: 12216 similar rows:  [12216]
11111111111111111111
incomplete name 3, col: 12216 row: []
col: 12217 similar rows:  [12217]
11111111111111111111
incomplete name 3, col: 12217 row: []
col: 12218 similar rows:  [12218]
11111111111111111111
incomplete name 3, col: 12218 row: []
col: 12219 similar rows:  [12219]
11111111111111111111
incomplete name 3, col: 12219 row: []
col: 12220 similar rows:  [12220]
11111111111111111111
incomplete name 3, col: 12220 row: []

col: 12221 similar rows:  [12221]
11111111111111111111
incomplete name 3, col: 12221 row: []
col: 12222 similar rows:  [12222]
11111111111111111111
incomplete name 3, col: 12222 row: []
col: 12223 similar rows:  [12223]
11111111111111111111
incomplete name 3, col: 12223 row: []
col: 12225 similar rows:  [12225]
11111111111111111111
incomplete name 3, col: 12225 row: []
col: 12227 similar rows:  [12227]
11111111111111111111
incomplete name 3, col: 12227 row: []
col: 12229 similar rows:  [12229]
11111111111111111111
incomplete name 3, col: 12229 row: []
col: 12231 similar rows:  [12231]
11111111111111111111
incomplete name 3, col: 12231 row: []
col: 12232 similar rows:  [12232, 12929]
incomplete name 3, col: 12232 row: []
col: 12234 similar rows:  [12234]
11111111111111111111
incomplete name 3, col: 12234 row: []
col: 12235 similar rows:  [12235]
11111111111111111111
hotelname2 [12235]
incomplete name 3, col: 12235 row: [12235]
col: 12236 similar rows:  [12236]
11111111111111111111
incomplete name 3, col: 12236 row: []
col: 12239 similar rows:  [12239]
11111111111111111111
hotelname2 [12239]
incomplete name 3, col: 12239 row: [12239]
col: 12240 similar rows:  [12240]
11111111111111111111
hotelname2 [12240]
incomplete name 3, col: 12240 row: []
col: 12241 similar rows:  [12241]
11111111111111111111
incomplete name 3, col: 12241 row: []
col: 12242 similar rows:  [12242]
11111111111111111111
incomplete name 3, col: 12242 row: []
col: 12244 similar rows:  [12244]
11111111111111111111
incomplete name 3, col: 12244 row: []
col: 12246 similar rows:  [12246]
11111111111111111111
incomplete name 3, col: 12246 row: []
col: 12252 similar rows:  [12252]
11111111111111111111
incomplete name 3, col: 12252 row: []
col: 12253 similar rows:  [12253]
11111111111111111111
incomplete name 3, col: 12253 row: []
col: 12254 similar rows:  [12254]
11111111111111111111
incomplete name 3, col: 12254 row: []
col: 12255 similar rows:  [12255, 12988, 13124]
incomplete name 3, col: 12255 row: []
col: 12256 similar rows:  [12256]
11111111111111111111
incomplete name 3, col: 12256 row: []
col: 12257 similar rows:  [12257]
11111111111111111111
incomplete name 3, col: 12257 row: []
col: 12258 similar rows:  [12258]
11111111111111111111
incomplete name 3, col: 12258 row: []
col: 12259 similar rows:  [12259, 12968, 13051]
incomplete name 3, col: 12259 row: []
col: 12261 similar rows:  [12261]
11111111111111111111
incomplete name 3, col: 12261 row: []
col: 12262 similar rows:  [12262]
11111111111111111111
incomplete name 3, col: 12262 row: []
col: 12264 similar rows:  [12264]
11111111111111111111
incomplete name 3, col: 12264 row: []
col: 12265 similar rows:  [12265]
11111111111111111111
incomplete name 3, col: 12265 row: []
col: 12271 similar rows:  [12271, 12829]
incomplete name 3, col: 12271 row: []
col: 12272 similar rows:  [12272]
11111111111111111111
incomplete name 3, col: 12272 row: []
col: 12273 similar rows:  [12273]
11111111111111111111
incomplete name 3, col: 12273 row: []
col: 12274 similar rows:  [12274, 12916]
incomplete name 3, col: 12274 row: []
col: 12276 similar rows:  [12276]
11111111111111111111
incomplete name 3, col: 12276 row: []
col: 12284 similar rows:  [12284]
11111111111111111111
incomplete name 3, col: 12284 row: []
col: 12285 similar rows:  [12285, 13203]
incomplete name 3, col: 12285 row: []
col: 12286 similar rows:  [12286]
11111111111111111111
incomplete name 3, col: 12286 row: []
col: 12289 similar rows:  [12289]
11111111111111111111
incomplete name 3, col: 12289 row: []
col: 12299 similar rows:  [12299]
11111111111111111111
hotelname2 [12299]
incomplete name 3, col: 12299 row: [12299]
col: 12305 similar rows:  [12305]
11111111111111111111
incomplete name 3, col: 12305 row: []
col: 12306 similar rows:  [12306, 12620]
incomplete name 3, col: 12306 row: []
col: 12311 similar rows:  [12311]
11111111111111111111
hotelname2 [12311]
incomplete name 3, col: 12311 row: [12311]
col: 12315 similar rows:  [12315, 12356, 12978]
incomplete name 3, col: 12315 row: []
col: 12318 similar rows:  [12318]
11111111111111111111
incomplete name 3, col: 12318 row: []
col: 12324 similar rows:  [12324]
11111111111111111111
hotelname2 [12324]
incomplete name 3, col: 12324 row: [12324]
col: 12325 similar rows:  [12325]
11111111111111111111
incomplete name 3, col: 12325 row: []
col: 12328 similar rows:  [12328]
11111111111111111111
incomplete name 3, col: 12328 row: []
col: 12330 similar rows:  [12330]
11111111111111111111
incomplete name 3, col: 12330 row: []
col: 12337 similar rows:  [12337, 12660]
incomplete name 3, col: 12337 row: []
col: 12350 similar rows:  [12350]
11111111111111111111
hotelname2 [12350]
incomplete name 3, col: 12350 row: [12350]
col: 12351 similar rows:  [12351]
11111111111111111111
incomplete name 3, col: 12351 row: []
col: 12362 similar rows:  [12362]
11111111111111111111
incomplete name 3, col: 12362 row: []
col: 12363 similar rows:  [12363]
11111111111111111111
incomplete name 3, col: 12363 row: []
col: 12364 similar rows:  [12364]
11111111111111111111
incomplete name 3, col: 12364 row: []
col: 12366 similar rows:  [12366]
11111111111111111111
incomplete name 3, col: 12366 row: []
col: 12367 similar rows:  [12367]
11111111111111111111
incomplete name 3, col: 12367 row: []
col: 12368 similar rows:  [12368]
11111111111111111111
incomplete name 3, col: 12368 row: []
col: 12371 similar rows:  [12371]
11111111111111111111
incomplete name 3, col: 12371 row: []
col: 12376 similar rows:  [12376]
11111111111111111111
hotelname2 [12376]
incomplete name 3, col: 12376 row: [12376]
col: 12379 similar rows:  [12379]
11111111111111111111
hotelname2 [12379]
incomplete name 3, col: 12379 row: [12379]
col: 12381 similar rows:  [12381]
11111111111111111111
incomplete name 3, col: 12381 row: []
col: 12384 similar rows:  [12384]
11111111111111111111
incomplete name 3, col: 12384 row: []
col: 12387 similar rows:  [12387, 12580]
incomplete name 3, col: 12387 row: []
col: 12390 similar rows:  [12390]
11111111111111111111
incomplete name 3, col: 12390 row: []
col: 12391 similar rows:  [12391]
11111111111111111111
hotelname2 [12391]
incomplete name 3, col: 12391 row: []
col: 12392 similar rows:  [12392]
11111111111111111111
incomplete name 3, col: 12392 row: []
col: 12398 similar rows:  [12398]
11111111111111111111
incomplete name 3, col: 12398 row: []
col: 12399 similar rows:  [12399]
11111111111111111111
incomplete name 3, col: 12399 row: []
col: 12403 similar rows:  [12403]
11111111111111111111
incomplete name 3, col: 12403 row: []
col: 12404 similar rows:  [12404, 12870, 12994]
incomplete name 3, col: 12404 row: []
col: 12407 similar rows:  [12407]
11111111111111111111
incomplete name 3, col: 12407 row: []
col: 12409 similar rows:  [12409]
11111111111111111111
incomplete name 3, col: 12409 row: []
col: 12411 similar rows:  [12411]
11111111111111111111
incomplete name 3, col: 12411 row: []
col: 12412 similar rows:  [12412]
11111111111111111111
incomplete name 3, col: 12412 row: []
col: 12413 similar rows:  [12413]
11111111111111111111
incomplete name 3, col: 12413 row: []
col: 12415 similar rows:  [12415]
11111111111111111111
incomplete name 3, col: 12415 row: []
col: 12416 similar rows:  [12416]
11111111111111111111
incomplete name 3, col: 12416 row: []
col: 12418 similar rows:  [12418]
11111111111111111111
incomplete name 3, col: 12418 row: []
col: 12421 similar rows:  [12421, 12422]
incomplete name 3, col: 12421 row: []
col: 12423 similar rows:  [12423]
11111111111111111111
incomplete name 3, col: 12423 row: []
col: 12425 similar rows:  [12425]
11111111111111111111
hotelname2 [12425]
wrong name!!!!
incomplete name 3, col: 12425 row: [12425]
col: 12426 similar rows:  [12426]
11111111111111111111
incomplete name 3, col: 12426 row: []
col: 12427 similar rows:  [12427]
11111111111111111111
incomplete name 3, col: 12427 row: []
col: 12429 similar rows:  [12429, 12988, 13124]
incomplete name 3, col: 12429 row: []
col: 12430 similar rows:  [12430]
11111111111111111111
hotelname2 [12430]
incomplete name 3, col: 12430 row: []
col: 12431 similar rows:  [12431]
11111111111111111111
incomplete name 3, col: 12431 row: []
col: 12433 similar rows:  [12433]
11111111111111111111
incomplete name 3, col: 12433 row: []

col: 12436 similar rows:  [12436]
11111111111111111111
hotelname2 [12436]
incomplete name 3, col: 12436 row: [12436]
col: 12437 similar rows:  [12437]
11111111111111111111
incomplete name 3, col: 12437 row: []
col: 12443 similar rows:  [12443]
11111111111111111111
hotelname2 [12443]
incomplete name 3, col: 12443 row: [12443]
col: 12450 similar rows:  [12450, 13003]
incomplete name 3, col: 12450 row: []
col: 12451 similar rows:  [12451]
11111111111111111111
hotelname2 [12451]
incomplete name 3, col: 12451 row: []
col: 12456 similar rows:  [12456]
11111111111111111111
hotelname2 [12456]
incomplete name 3, col: 12456 row: [12456]
col: 12460 similar rows:  [12460]
11111111111111111111
incomplete name 3, col: 12460 row: []
col: 12463 similar rows:  [12463]
11111111111111111111
incomplete name 3, col: 12463 row: []
col: 12466 similar rows:  [12466, 12621]
incomplete name 3, col: 12466 row: []
col: 12473 similar rows:  [12473, 12638]
incomplete name 3, col: 12473 row: []
col: 12481 similar rows:  [12481]
11111111111111111111
incomplete name 3, col: 12481 row: []
col: 12482 similar rows:  [12482]
11111111111111111111
incomplete name 3, col: 12482 row: []
col: 12483 similar rows:  [12483]
11111111111111111111
incomplete name 3, col: 12483 row: []
col: 12484 similar rows:  [12484]
11111111111111111111
incomplete name 3, col: 12484 row: []
col: 12486 similar rows:  [12486]
11111111111111111111
incomplete name 3, col: 12486 row: []
col: 12488 similar rows:  [12488]
11111111111111111111
incomplete name 3, col: 12488 row: []
col: 12494 similar rows:  [12494]
11111111111111111111
incomplete name 3, col: 12494 row: []
col: 12497 similar rows:  [12497]
11111111111111111111
incomplete name 3, col: 12497 row: []
col: 12502 similar rows:  [12502]
11111111111111111111
incomplete name 3, col: 12502 row: []
col: 12504 similar rows:  [12504]
11111111111111111111
incomplete name 3, col: 12504 row: []
col: 12508 similar rows:  [12508]
11111111111111111111
incomplete name 3, col: 12508 row: []
col: 12509 similar rows:  [12509, 13119]
incomplete name 3, col: 12509 row: []
col: 12510 similar rows:  [12510]
11111111111111111111
hotelname2 [12510]
incomplete name 3, col: 12510 row: [12510]
col: 12514 similar rows:  [12514]
11111111111111111111
incomplete name 3, col: 12514 row: []
col: 12515 similar rows:  [12515]
11111111111111111111
incomplete name 3, col: 12515 row: []
col: 12516 similar rows:  [12516]
11111111111111111111
incomplete name 3, col: 12516 row: []
col: 12519 similar rows:  [12519]
11111111111111111111
incomplete name 3, col: 12519 row: []
col: 12520 similar rows:  [12520]
11111111111111111111
incomplete name 3, col: 12520 row: []
col: 12527 similar rows:  [12527, 12545, 12569]
incomplete name 3, col: 12527 row: []
col: 12529 similar rows:  [12529]
11111111111111111111
hotelname2 [12529]
incomplete name 3, col: 12529 row: []
col: 12530 similar rows:  [12530]
11111111111111111111
incomplete name 3, col: 12530 row: []
col: 12533 similar rows:  [12533]
11111111111111111111
incomplete name 3, col: 12533 row: []
col: 12535 similar rows:  [12535]
11111111111111111111
incomplete name 3, col: 12535 row: []
col: 12537 similar rows:  [12537]
11111111111111111111
incomplete name 3, col: 12537 row: []
col: 12538 similar rows:  [12538]
11111111111111111111
incomplete name 3, col: 12538 row: []
col: 12542 similar rows:  [12542]
11111111111111111111
hotelname2 [12542]
incomplete name 3, col: 12542 row: [12542]
col: 12543 similar rows:  [12543]
11111111111111111111
incomplete name 3, col: 12543 row: []
col: 12544 similar rows:  [12544]
11111111111111111111
incomplete name 3, col: 12544 row: []
col: 12548 similar rows:  [12548]
11111111111111111111
incomplete name 3, col: 12548 row: []
col: 12550 similar rows:  [12550]
11111111111111111111
incomplete name 3, col: 12550 row: []
col: 12552 similar rows:  [12552]
11111111111111111111
incomplete name 3, col: 12552 row: []
col: 12553 similar rows:  [12553, 12557]
incomplete name 3, col: 12553 row: []
col: 12558 similar rows:  [12558]
11111111111111111111
hotelname2 [12558]
incomplete name 3, col: 12558 row: [12558]
col: 12560 similar rows:  [12560]
11111111111111111111
hotelname2 [12560]
incomplete name 3, col: 12560 row: [12560]
col: 12563 similar rows:  [12563]
11111111111111111111
incomplete name 3, col: 12563 row: []
col: 12564 similar rows:  [12564, 12577]
incomplete name 3, col: 12564 row: []
col: 12566 similar rows:  [12566]
11111111111111111111
incomplete name 3, col: 12566 row: []
col: 12567 similar rows:  [12567]
11111111111111111111
hotelname2 [12567]
wrong name!!!!
incomplete name 3, col: 12567 row: [12567]
col: 12568 similar rows:  [12568]
11111111111111111111
incomplete name 3, col: 12568 row: []
col: 12572 similar rows:  [12572]
11111111111111111111
incomplete name 3, col: 12572 row: []
col: 12574 similar rows:  [12574]
11111111111111111111
incomplete name 3, col: 12574 row: []
col: 12575 similar rows:  [12575]
11111111111111111111
hotelname2 [12575]
incomplete name 3, col: 12575 row: [12575]
col: 12579 similar rows:  [12579]
11111111111111111111
incomplete name 3, col: 12579 row: []
col: 12581 similar rows:  [12581]
11111111111111111111
incomplete name 3, col: 12581 row: []
col: 12582 similar rows:  [12582]
11111111111111111111
incomplete name 3, col: 12582 row: []
col: 12583 similar rows:  [12583]
11111111111111111111
incomplete name 3, col: 12583 row: []
col: 12584 similar rows:  [12584]
11111111111111111111
incomplete name 3, col: 12584 row: []
col: 12585 similar rows:  [12585]
11111111111111111111
incomplete name 3, col: 12585 row: []
col: 12586 similar rows:  [12586]
11111111111111111111
incomplete name 3, col: 12586 row: []
col: 12587 similar rows:  [12587]
11111111111111111111
incomplete name 3, col: 12587 row: []
col: 12588 similar rows:  [12588]
11111111111111111111
incomplete name 3, col: 12588 row: []
col: 12589 similar rows:  [12589]
11111111111111111111
incomplete name 3, col: 12589 row: []
col: 12590 similar rows:  [12590]
11111111111111111111
incomplete name 3, col: 12590 row: []
col: 12591 similar rows:  [12591]
11111111111111111111
incomplete name 3, col: 12591 row: []
col: 12593 similar rows:  [12593]
11111111111111111111
incomplete name 3, col: 12593 row: []
col: 12594 similar rows:  [12594]
11111111111111111111
incomplete name 3, col: 12594 row: []
col: 12595 similar rows:  [12595]
11111111111111111111
incomplete name 3, col: 12595 row: []
col: 12598 similar rows:  [12598]
11111111111111111111
incomplete name 3, col: 12598 row: []
col: 12599 similar rows:  [12599]
11111111111111111111
incomplete name 3, col: 12599 row: []
col: 12600 similar rows:  [12600]
11111111111111111111
incomplete name 3, col: 12600 row: []
col: 12601 similar rows:  [12601]
11111111111111111111
incomplete name 3, col: 12601 row: []
col: 12602 similar rows:  [12602]
11111111111111111111
incomplete name 3, col: 12602 row: []
col: 12603 similar rows:  [12603]
11111111111111111111
hotelname2 [12603]
incomplete name 3, col: 12603 row: [12603]
col: 12605 similar rows:  [12605]
11111111111111111111
incomplete name 3, col: 12605 row: []
col: 12606 similar rows:  [12606]
11111111111111111111
incomplete name 3, col: 12606 row: []
col: 12607 similar rows:  [12607]
11111111111111111111
incomplete name 3, col: 12607 row: []
col: 12609 similar rows:  [12609]
11111111111111111111
incomplete name 3, col: 12609 row: []
col: 12611 similar rows:  [12611]
11111111111111111111
incomplete name 3, col: 12611 row: []
col: 12613 similar rows:  [12613]
11111111111111111111
incomplete name 3, col: 12613 row: []
col: 12616 similar rows:  [12616, 13018]
incomplete name 3, col: 12616 row: []
col: 12619 similar rows:  [12619, 12812]
incomplete name 3, col: 12619 row: []
col: 12626 similar rows:  [12626]
11111111111111111111
incomplete name 3, col: 12626 row: []
col: 12628 similar rows:  [12628, 12735]
incomplete name 3, col: 12628 row: []
col: 12634 similar rows:  [12634]
11111111111111111111
hotelname2 [12634]
incomplete name 3, col: 12634 row: [12634]
col: 12650 similar rows:  [12650]
11111111111111111111
incomplete name 3, col: 12650 row: []
col: 12652 similar rows:  [12652]
11111111111111111111
hotelname2 [12652]
incomplete name 3, col: 12652 row: [12652]

col: 12658 similar rows:  [12658]
11111111111111111111
hotelname2 [12658]
incomplete name 3, col: 12658 row: [12658]
col: 12661 similar rows:  [12661, 12719]
incomplete name 3, col: 12661 row: []
col: 12666 similar rows:  [12666]
11111111111111111111
incomplete name 3, col: 12666 row: []
col: 12669 similar rows:  [12669]
11111111111111111111
hotelname2 [12669]
wrong name!!!!
incomplete name 3, col: 12669 row: [12669]
col: 12671 similar rows:  [12671]
11111111111111111111
incomplete name 3, col: 12671 row: []
col: 12677 similar rows:  [12677]
11111111111111111111
hotelname2 [12677]
incomplete name 3, col: 12677 row: []
col: 12679 similar rows:  [12679]
11111111111111111111
incomplete name 3, col: 12679 row: []
col: 12680 similar rows:  [12680]
11111111111111111111
incomplete name 3, col: 12680 row: []
col: 12682 similar rows:  [12682, 13007]
incomplete name 3, col: 12682 row: []
col: 12684 similar rows:  [12684]
11111111111111111111
incomplete name 3, col: 12684 row: []
col: 12686 similar rows:  [12686]
11111111111111111111
hotelname2 [12686]
incomplete name 3, col: 12686 row: [12686]
col: 12695 similar rows:  [12695]
11111111111111111111
incomplete name 3, col: 12695 row: []
col: 12698 similar rows:  [12698]
11111111111111111111
incomplete name 3, col: 12698 row: []
col: 12700 similar rows:  [12700]
11111111111111111111
incomplete name 3, col: 12700 row: []
col: 12709 similar rows:  [12709]
11111111111111111111
hotelname2 [12709]
incomplete name 3, col: 12709 row: [12709]
col: 12712 similar rows:  [12712]
11111111111111111111
incomplete name 3, col: 12712 row: []
col: 12714 similar rows:  [12714]
11111111111111111111
hotelname2 [12714]
incomplete name 3, col: 12714 row: [12714]
col: 12716 similar rows:  [12716]
11111111111111111111
incomplete name 3, col: 12716 row: []
col: 12717 similar rows:  [12717]
11111111111111111111
incomplete name 3, col: 12717 row: []
col: 12730 similar rows:  [12730]
11111111111111111111
hotelname2 [12730]
incomplete name 3, col: 12730 row: [12730]
col: 12737 similar rows:  [12737]
11111111111111111111
incomplete name 3, col: 12737 row: []
col: 12740 similar rows:  [12740]
11111111111111111111
hotelname2 [12740]
incomplete name 3, col: 12740 row: [12740]
col: 12742 similar rows:  [12742]
11111111111111111111
hotelname2 [12742]
incomplete name 3, col: 12742 row: []
col: 12743 similar rows:  [12743]
11111111111111111111
incomplete name 3, col: 12743 row: []
col: 12745 similar rows:  [12745]
11111111111111111111
incomplete name 3, col: 12745 row: []
col: 12747 similar rows:  [12747]
11111111111111111111
incomplete name 3, col: 12747 row: []
col: 12748 similar rows:  [12748]
11111111111111111111
incomplete name 3, col: 12748 row: []
col: 12750 similar rows:  [12750]
11111111111111111111
incomplete name 3, col: 12750 row: []
col: 12751 similar rows:  [12751]
11111111111111111111
hotelname2 [12751]
incomplete name 3, col: 12751 row: [12751]
col: 12753 similar rows:  [12753]
11111111111111111111
incomplete name 3, col: 12753 row: []
col: 12754 similar rows:  [12754]
11111111111111111111
incomplete name 3, col: 12754 row: []
col: 12755 similar rows:  [12755]
11111111111111111111
incomplete name 3, col: 12755 row: []
col: 12756 similar rows:  [12756]
11111111111111111111
incomplete name 3, col: 12756 row: []
col: 12761 similar rows:  [12761]
11111111111111111111
incomplete name 3, col: 12761 row: []
col: 12762 similar rows:  [12762]
11111111111111111111
incomplete name 3, col: 12762 row: []
col: 12765 similar rows:  [12765]
11111111111111111111
hotelname2 [12765]
incomplete name 3, col: 12765 row: []
col: 12766 similar rows:  [12766]
11111111111111111111
hotelname2 [12766]
incomplete name 3, col: 12766 row: [12766]
col: 12769 similar rows:  [12769, 13071, 13128]
incomplete name 3, col: 12769 row: []
col: 12770 similar rows:  [12770]
11111111111111111111
incomplete name 3, col: 12770 row: []
col: 12772 similar rows:  [12772]
11111111111111111111
incomplete name 3, col: 12772 row: []
col: 12778 similar rows:  [12778]
11111111111111111111
hotelname2 [12778]
incomplete name 3, col: 12778 row: []
col: 12781 similar rows:  [12781]
11111111111111111111
hotelname2 [12781]
incomplete name 3, col: 12781 row: []
col: 12783 similar rows:  [12783]
11111111111111111111
incomplete name 3, col: 12783 row: []
col: 12784 similar rows:  [12784]
11111111111111111111
hotelname2 [12784]
incomplete name 3, col: 12784 row: [12784]
col: 12785 similar rows:  [12785]
11111111111111111111
incomplete name 3, col: 12785 row: []
col: 12786 similar rows:  [12786]
11111111111111111111
hotelname2 [12786]
incomplete name 3, col: 12786 row: [12786]
col: 12788 similar rows:  [12788]
11111111111111111111
hotelname2 [12788]
incomplete name 3, col: 12788 row: [12788]
col: 12792 similar rows:  [12792]
11111111111111111111
incomplete name 3, col: 12792 row: []
col: 12796 similar rows:  [12796]
11111111111111111111
incomplete name 3, col: 12796 row: []
col: 12798 similar rows:  [12798]
11111111111111111111
incomplete name 3, col: 12798 row: []
col: 12799 similar rows:  [12799]
11111111111111111111
incomplete name 3, col: 12799 row: []
col: 12805 similar rows:  [12805]
11111111111111111111
incomplete name 3, col: 12805 row: []
col: 12808 similar rows:  [12808]
11111111111111111111
incomplete name 3, col: 12808 row: []
col: 12810 similar rows:  [12810]
11111111111111111111
incomplete name 3, col: 12810 row: []
col: 12811 similar rows:  [12811]
11111111111111111111
incomplete name 3, col: 12811 row: []
col: 12813 similar rows:  [12813]
11111111111111111111
incomplete name 3, col: 12813 row: []
col: 12816 similar rows:  [12816]
11111111111111111111
incomplete name 3, col: 12816 row: []
col: 12822 similar rows:  [12822]
11111111111111111111
hotelname2 [12822]
incomplete name 3, col: 12822 row: []
col: 12836 similar rows:  [12836]
11111111111111111111
hotelname2 [12836]
incomplete name 3, col: 12836 row: [12836]
col: 12838 similar rows:  [12838]
11111111111111111111
incomplete name 3, col: 12838 row: []
col: 12843 similar rows:  [12843]
11111111111111111111
incomplete name 3, col: 12843 row: []
col: 12848 similar rows:  [12848]
11111111111111111111
incomplete name 3, col: 12848 row: []
col: 12864 similar rows:  [12864]
11111111111111111111
incomplete name 3, col: 12864 row: []
col: 12867 similar rows:  [12867]
11111111111111111111
incomplete name 3, col: 12867 row: []
col: 12872 similar rows:  [12872]
11111111111111111111
incomplete name 3, col: 12872 row: []
col: 12887 similar rows:  [12887]
11111111111111111111
incomplete name 3, col: 12887 row: []
col: 12892 similar rows:  [12892]
11111111111111111111
incomplete name 3, col: 12892 row: []
col: 12893 similar rows:  [12893, 12901]
incomplete name 3, col: 12893 row: []
col: 12898 similar rows:  [12898]
11111111111111111111
incomplete name 3, col: 12898 row: []
col: 12900 similar rows:  [12900]
11111111111111111111
hotelname2 [12900]
incomplete name 3, col: 12900 row: [12900]
col: 12911 similar rows:  [12911]
11111111111111111111
incomplete name 3, col: 12911 row: []
col: 12914 similar rows:  [12914]
11111111111111111111
incomplete name 3, col: 12914 row: []
col: 12919 similar rows:  [12919]
11111111111111111111
incomplete name 3, col: 12919 row: []
col: 12924 similar rows:  [12924]
11111111111111111111
incomplete name 3, col: 12924 row: []
col: 12927 similar rows:  [12927]
11111111111111111111
incomplete name 3, col: 12927 row: []
col: 12930 similar rows:  [12930]
11111111111111111111
hotelname2 [12930]
incomplete name 3, col: 12930 row: [12930]
col: 12934 similar rows:  [12934]
11111111111111111111
hotelname2 [12934]
incomplete name 3, col: 12934 row: []
col: 12935 similar rows:  [12935]
11111111111111111111
incomplete name 3, col: 12935 row: []
col: 12941 similar rows:  [12941]
11111111111111111111
incomplete name 3, col: 12941 row: []
col: 12947 similar rows:  [12947]
11111111111111111111
hotelname2 [12947]
incomplete name 3, col: 12947 row: []
col: 12953 similar rows:  [12953]
11111111111111111111
incomplete name 3, col: 12953 row: []
col: 12957 similar rows:  [12957]
11111111111111111111
incomplete name 3, col: 12957 row: []
col: 12959 similar rows:  [12959]
11111111111111111111
incomplete name 3, col: 12959 row: []
col: 12960 similar rows:  [12960]
11111111111111111111
incomplete name 3, col: 12960 row: []

col: 12965 similar rows:  [12965]
11111111111111111111
incomplete name 3, col: 12965 row: []
col: 12967 similar rows:  [12967]
11111111111111111111
incomplete name 3, col: 12967 row: []
col: 12969 similar rows:  [12969]
11111111111111111111
incomplete name 3, col: 12969 row: []
col: 12972 similar rows:  [12972]
11111111111111111111
incomplete name 3, col: 12972 row: []
col: 12976 similar rows:  [12976]
11111111111111111111
incomplete name 3, col: 12976 row: []
col: 12980 similar rows:  [12980]
11111111111111111111
incomplete name 3, col: 12980 row: []
col: 12983 similar rows:  [12983]
11111111111111111111
hotelname2 [12983]
wrong name!!!!
incomplete name 3, col: 12983 row: [12983]
col: 12985 similar rows:  [12985]
11111111111111111111
incomplete name 3, col: 12985 row: []
col: 12989 similar rows:  [12989]
11111111111111111111
incomplete name 3, col: 12989 row: []
col: 12990 similar rows:  [12990, 13060]
incomplete name 3, col: 12990 row: []
col: 12991 similar rows:  [12991]
11111111111111111111
incomplete name 3, col: 12991 row: []
col: 12992 similar rows:  [12992]
11111111111111111111
incomplete name 3, col: 12992 row: []
col: 12993 similar rows:  [12993]
11111111111111111111
incomplete name 3, col: 12993 row: []
col: 12996 similar rows:  [12996]
11111111111111111111
incomplete name 3, col: 12996 row: []
col: 12998 similar rows:  [12998]
11111111111111111111
incomplete name 3, col: 12998 row: []
col: 12999 similar rows:  [12999]
11111111111111111111
incomplete name 3, col: 12999 row: []
col: 13002 similar rows:  [13002]
11111111111111111111
incomplete name 3, col: 13002 row: []
col: 13006 similar rows:  [13006, 13217]
incomplete name 3, col: 13006 row: []
col: 13009 similar rows:  [13009]
11111111111111111111
incomplete name 3, col: 13009 row: []
col: 13010 similar rows:  [13010]
11111111111111111111
incomplete name 3, col: 13010 row: []
col: 13011 similar rows:  [13011]
11111111111111111111
incomplete name 3, col: 13011 row: []
col: 13012 similar rows:  [13012]
11111111111111111111
incomplete name 3, col: 13012 row: []
col: 13013 similar rows:  [13013]
11111111111111111111
incomplete name 3, col: 13013 row: []
col: 13014 similar rows:  [13014]
11111111111111111111
incomplete name 3, col: 13014 row: []
col: 13015 similar rows:  [13015]
11111111111111111111
incomplete name 3, col: 13015 row: []
col: 13017 similar rows:  [13017]
11111111111111111111
hotelname2 [13017]
incomplete name 3, col: 13017 row: [13017]
col: 13025 similar rows:  [13025, 13080, 13183, 13196]
incomplete name 3, col: 13025 row: []
col: 13034 similar rows:  [13034]
11111111111111111111
incomplete name 3, col: 13034 row: []
col: 13038 similar rows:  [13038]
11111111111111111111
hotelname2 [13038]
incomplete name 3, col: 13038 row: [13038]
col: 13049 similar rows:  [13049]
11111111111111111111
incomplete name 3, col: 13049 row: []
col: 13050 similar rows:  [13050]
11111111111111111111
hotelname2 [13050]
wrong name!!!!
incomplete name 3, col: 13050 row: [13050]
col: 13053 similar rows:  [13053]
11111111111111111111
incomplete name 3, col: 13053 row: []
col: 13055 similar rows:  [13055]
11111111111111111111
incomplete name 3, col: 13055 row: []
col: 13059 similar rows:  [13059]
11111111111111111111
hotelname2 [13059]
incomplete name 3, col: 13059 row: [13059]
col: 13064 similar rows:  [13064]
11111111111111111111
hotelname2 [13064]
wrong name!!!!
incomplete name 3, col: 13064 row: [13064]
col: 13068 similar rows:  [13068]
11111111111111111111
hotelname2 [13068]
incomplete name 3, col: 13068 row: [13068]
col: 13069 similar rows:  [13069]
11111111111111111111
hotelname2 [13069]
wrong name!!!!
incomplete name 3, col: 13069 row: [13069]
col: 13073 similar rows:  [13073]
11111111111111111111
hotelname2 [13073]
incomplete name 3, col: 13073 row: [13073]
col: 13076 similar rows:  [13076]
11111111111111111111
hotelname2 [13076]
wrong name!!!!
incomplete name 3, col: 13076 row: [13076]
col: 13077 similar rows:  [13077]
11111111111111111111
incomplete name 3, col: 13077 row: []
col: 13079 similar rows:  [13079]
11111111111111111111
incomplete name 3, col: 13079 row: []
col: 13081 similar rows:  [13081, 13109]
incomplete name 3, col: 13081 row: []
col: 13083 similar rows:  [13083]
11111111111111111111
hotelname2 [13083]
wrong name!!!!
incomplete name 3, col: 13083 row: [13083]
col: 13089 similar rows:  [13089]
11111111111111111111
incomplete name 3, col: 13089 row: []
col: 13092 similar rows:  [13092]
11111111111111111111
incomplete name 3, col: 13092 row: []
col: 13094 similar rows:  [13094]
11111111111111111111
incomplete name 3, col: 13094 row: []
col: 13097 similar rows:  [13097]
11111111111111111111
hotelname2 [13097]
incomplete name 3, col: 13097 row: []
col: 13099 similar rows:  [13099]
11111111111111111111
incomplete name 3, col: 13099 row: []
col: 13100 similar rows:  [13100]
11111111111111111111
incomplete name 3, col: 13100 row: []
col: 13102 similar rows:  [13102]
11111111111111111111
incomplete name 3, col: 13102 row: []
col: 13108 similar rows:  [13108]
11111111111111111111
hotelname2 [13108]
incomplete name 3, col: 13108 row: []
col: 13110 similar rows:  [13110]
11111111111111111111
incomplete name 3, col: 13110 row: []
col: 13112 similar rows:  [13112]
11111111111111111111
incomplete name 3, col: 13112 row: []
col: 13114 similar rows:  [13114]
11111111111111111111
hotelname2 [13114]
incomplete name 3, col: 13114 row: [13114]
col: 13118 similar rows:  [13118]
11111111111111111111
hotelname2 [13118]
incomplete name 3, col: 13118 row: []
col: 13120 similar rows:  [13120]
11111111111111111111
incomplete name 3, col: 13120 row: []
col: 13126 similar rows:  [13126]
11111111111111111111
incomplete name 3, col: 13126 row: []
col: 13127 similar rows:  [13127]
11111111111111111111
incomplete name 3, col: 13127 row: []
col: 13134 similar rows:  [13134]
11111111111111111111
hotelname2 [13134]
incomplete name 3, col: 13134 row: [13134]
col: 13138 similar rows:  [13138]
11111111111111111111
hotelname2 [13138]
incomplete name 3, col: 13138 row: []
col: 13140 similar rows:  [13140]
11111111111111111111
incomplete name 3, col: 13140 row: []
col: 13146 similar rows:  [13146]
11111111111111111111
incomplete name 3, col: 13146 row: []
col: 13148 similar rows:  [13148]
11111111111111111111
hotelname2 [13148]
incomplete name 3, col: 13148 row: [13148]
col: 13151 similar rows:  [13151]
11111111111111111111
incomplete name 3, col: 13151 row: []
col: 13152 similar rows:  [13152]
11111111111111111111
incomplete name 3, col: 13152 row: []
col: 13163 similar rows:  [13163]
11111111111111111111
hotelname2 [13163]
incomplete name 3, col: 13163 row: [13163]
col: 13164 similar rows:  [13164]
11111111111111111111
incomplete name 3, col: 13164 row: []
col: 13167 similar rows:  [13167]
11111111111111111111
incomplete name 3, col: 13167 row: []
col: 13173 similar rows:  [13173]
11111111111111111111
incomplete name 3, col: 13173 row: []
col: 13174 similar rows:  [13174]
11111111111111111111
incomplete name 3, col: 13174 row: []
col: 13175 similar rows:  [13175]
11111111111111111111
incomplete name 3, col: 13175 row: []
col: 13176 similar rows:  [13176]
11111111111111111111
incomplete name 3, col: 13176 row: []
col: 13179 similar rows:  [13179]
11111111111111111111
incomplete name 3, col: 13179 row: []
col: 13180 similar rows:  [13180]
11111111111111111111
hotelname2 [13180]
incomplete name 3, col: 13180 row: []
col: 13184 similar rows:  [13184]
11111111111111111111
incomplete name 3, col: 13184 row: []
col: 13186 similar rows:  [13186]
11111111111111111111
incomplete name 3, col: 13186 row: []
col: 13192 similar rows:  [13192]
11111111111111111111
incomplete name 3, col: 13192 row: []
col: 13193 similar rows:  [13193]
11111111111111111111
incomplete name 3, col: 13193 row: []
col: 13198 similar rows:  [13198]
11111111111111111111
hotelname2 [13198]
incomplete name 3, col: 13198 row: [13198]
col: 13199 similar rows:  [13199]
11111111111111111111
incomplete name 3, col: 13199 row: []
col: 13200 similar rows:  [13200]
11111111111111111111
hotelname2 [13200]
incomplete name 3, col: 13200 row: []
col: 13201 similar rows:  [13201]
11111111111111111111
hotelname2 [13201]
incomplete name 3, col: 13201 row: [13201]
col: 13206 similar rows:  [13206]
11111111111111111111
incomplete name 3, col: 13206 row: []
col: 13210 similar rows:  [13210]
11111111111111111111
hotelname2 [13210]
incomplete name 3, col: 13210 row: [13210]
col: 13214 similar rows:  [13214]
11111111111111111111
incomplete name 3, col: 13214 row: []
col: 13219 similar rows:  [13219]
11111111111111111111
incomplete name 3, col: 13219 row: []

col: 13221 similar rows:  [13221]
11111111111111111111
incomplete name 3, col: 13221 row: []
col: 13223 similar rows:  [13223]
11111111111111111111
incomplete name 3, col: 13223 row: []
col: 13226 similar rows:  [13226]
11111111111111111111
incomplete name 3, col: 13226 row: []
col: 13227 similar rows:  [13227]
11111111111111111111
hotelname2 [13227]
incomplete name 3, col: 13227 row: []
end
col: 13228 similar rows:  [13228, 13280, 15933]
incomplete name 3, col: 13228 row: []
col: 13229 similar rows:  [13229]
11111111111111111111
hotelname2 [13229]
incomplete name 3, col: 13229 row: [13229]
col: 13230 similar rows:  [13230]
11111111111111111111
incomplete name 3, col: 13230 row: []
col: 13231 similar rows:  [13231]
11111111111111111111
incomplete name 3, col: 13231 row: []
col: 13232 similar rows:  [13232]
11111111111111111111
incomplete name 3, col: 13232 row: []
col: 13233 similar rows:  [13233, 13317, 15508, 15702]
incomplete name 3, col: 13233 row: []
col: 13234 similar rows:  [13234]
11111111111111111111
incomplete name 3, col: 13234 row: []
col: 13235 similar rows:  [13235]
11111111111111111111
incomplete name 3, col: 13235 row: []
col: 13236 similar rows:  [13236]
11111111111111111111
incomplete name 3, col: 13236 row: []
col: 13237 similar rows:  [13237, 13310, 15983]
incomplete name 3, col: 13237 row: []
col: 13238 similar rows:  [13238]
11111111111111111111
incomplete name 3, col: 13238 row: []
col: 13239 similar rows:  [13239, 15271, 15334, 15550, 16101, 16216, 16392, 16573, 17025]
incomplete name 3, col: 13239 row: []
col: 13240 similar rows:  [13240, 16091]
incomplete name 3, col: 13240 row: []
col: 13241 similar rows:  [13241, 15347, 15643, 15953, 16081, 16550, 16872]
incomplete name 3, col: 13241 row: []
col: 13242 similar rows:  [13242]
11111111111111111111
incomplete name 3, col: 13242 row: []
col: 13243 similar rows:  [13243, 15597, 16748, 17155]
incomplete name 3, col: 13243 row: []
col: 13244 similar rows:  [13244, 13245]
incomplete name 3, col: 13244 row: []
col: 13246 similar rows:  [13246, 16118]
incomplete name 3, col: 13246 row: []
col: 13247 similar rows:  [13247, 16847]
incomplete name 3, col: 13247 row: []
col: 13248 similar rows:  [13248]
11111111111111111111
incomplete name 3, col: 13248 row: []
col: 13249 similar rows:  [13249]
11111111111111111111
incomplete name 3, col: 13249 row: []
col: 13250 similar rows:  [13250]
11111111111111111111
incomplete name 3, col: 13250 row: []
col: 13251 similar rows:  [13251]
11111111111111111111
incomplete name 3, col: 13251 row: []
col: 13252 similar rows:  [13252]
11111111111111111111
hotelname2 [13252]
incomplete name 3, col: 13252 row: []
col: 13253 similar rows:  [13253]
11111111111111111111
incomplete name 3, col: 13253 row: []
col: 13254 similar rows:  [13254]
11111111111111111111
incomplete name 3, col: 13254 row: []
col: 13255 similar rows:  [13255]
11111111111111111111
hotelname2 [13255]
incomplete name 3, col: 13255 row: []
col: 13256 similar rows:  [13256, 15362, 15888]
incomplete name 3, col: 13256 row: []
col: 13257 similar rows:  [13257]
11111111111111111111
incomplete name 3, col: 13257 row: []
col: 13258 similar rows:  [13258, 15840, 15845, 15991, 15992, 16332, 16704, 17145, 17146]
incomplete name 3, col: 13258 row: []
col: 13259 similar rows:  [13259]
11111111111111111111
incomplete name 3, col: 13259 row: []
col: 13260 similar rows:  [13260, 15788, 15949, 16320, 16585]
incomplete name 3, col: 13260 row: []
col: 13261 similar rows:  [13261, 16465, 16974]
incomplete name 3, col: 13261 row: []
col: 13262 similar rows:  [13262, 17206, 17215]
incomplete name 3, col: 13262 row: []
col: 13263 similar rows:  [13263, 17213]
incomplete name 3, col: 13263 row: []
col: 13264 similar rows:  [13264, 15341, 15847, 16301, 16364, 16684, 17216]
incomplete name 3, col: 13264 row: []
col: 13265 similar rows:  [13265, 13271, 16088, 16207, 16228, 16373, 16374, 16375, 16377, 16543, 16958, 16985, 17020, 17193]
incomplete name 3, col: 13265 row: []
col: 13266 similar rows:  [13266, 13284, 15406, 15658, 15945, 16176, 16607, 16742]
incomplete name 3, col: 13266 row: []
col: 13267 similar rows:  [13267]
11111111111111111111
hotelname2 [13267]
incomplete name 3, col: 13267 row: [13267]
col: 13268 similar rows:  [13268, 15288, 15586, 15664, 15879, 15935, 15959, 16166, 16183, 16289, 16910, 16939]
incomplete name 3, col: 13268 row: []
col: 13269 similar rows:  [13269]
11111111111111111111
incomplete name 3, col: 13269 row: []
col: 13270 similar rows:  [13270]
11111111111111111111
incomplete name 3, col: 13270 row: []
col: 13272 similar rows:  [13272]
11111111111111111111
incomplete name 3, col: 13272 row: []
col: 13273 similar rows:  [13273, 15413, 16288]
incomplete name 3, col: 13273 row: []
col: 13274 similar rows:  [13274]
11111111111111111111
hotelname2 [13274]
incomplete name 3, col: 13274 row: [13274]
col: 13275 similar rows:  [13275]
11111111111111111111
incomplete name 3, col: 13275 row: []
col: 13276 similar rows:  [13276, 15350, 16020, 16204]
incomplete name 3, col: 13276 row: []
col: 13277 similar rows:  [13277, 16390]
incomplete name 3, col: 13277 row: []
col: 13278 similar rows:  [13278, 16863]
incomplete name 3, col: 13278 row: []
col: 13279 similar rows:  [13279, 15318, 16201, 16440, 16507, 16845]
incomplete name 3, col: 13279 row: []
col: 13281 similar rows:  [13281, 17014, 17021]
incomplete name 3, col: 13281 row: []
col: 13282 similar rows:  [13282]
11111111111111111111
incomplete name 3, col: 13282 row: []
col: 13283 similar rows:  [13283, 13293]
incomplete name 3, col: 13283 row: []
col: 13285 similar rows:  [13285]
11111111111111111111
incomplete name 3, col: 13285 row: []
col: 13286 similar rows:  [13286]
11111111111111111111
incomplete name 3, col: 13286 row: []
col: 13287 similar rows:  [13287, 15303, 16712]
incomplete name 3, col: 13287 row: []
col: 13288 similar rows:  [13288]
11111111111111111111
incomplete name 3, col: 13288 row: []
col: 13289 similar rows:  [13289, 15470, 16255, 16635, 16883]
incomplete name 3, col: 13289 row: []
col: 13290 similar rows:  [13290]
11111111111111111111
incomplete name 3, col: 13290 row: []
col: 13291 similar rows:  [13291, 16475]
incomplete name 3, col: 13291 row: []
col: 13292 similar rows:  [13292]
11111111111111111111
incomplete name 3, col: 13292 row: []
col: 13294 similar rows:  [13294]
11111111111111111111
incomplete name 3, col: 13294 row: []
col: 13295 similar rows:  [13295]
11111111111111111111
incomplete name 3, col: 13295 row: []
col: 13296 similar rows:  [13296, 15724, 15917, 16422, 16866]
incomplete name 3, col: 13296 row: []
col: 13297 similar rows:  [13297]
11111111111111111111
incomplete name 3, col: 13297 row: []
col: 13298 similar rows:  [13298]
11111111111111111111
incomplete name 3, col: 13298 row: []
col: 13299 similar rows:  [13299, 15306, 15346, 15352, 15449, 15577, 15579, 15601, 15749, 15750, 16076, 16083, 16086, 16197, 16198, 16437, 16580]
incomplete name 3, col: 13299 row: []
col: 13300 similar rows:  [13300]
11111111111111111111
incomplete name 3, col: 13300 row: []
col: 13301 similar rows:  [13301, 17207]
incomplete name 3, col: 13301 row: []
col: 13302 similar rows:  [13302, 16730, 16741]
incomplete name 3, col: 13302 row: []
col: 13303 similar rows:  [13303]
11111111111111111111
incomplete name 3, col: 13303 row: []
col: 13304 similar rows:  [13304]
11111111111111111111
hotelname2 [13304]
incomplete name 3, col: 13304 row: [13304]
col: 13305 similar rows:  [13305, 15630]
incomplete name 3, col: 13305 row: []
col: 13306 similar rows:  [13306, 15558, 16030, 17208]
incomplete name 3, col: 13306 row: []
col: 13307 similar rows:  [13307]
11111111111111111111
incomplete name 3, col: 13307 row: []
col: 13308 similar rows:  [13308, 15871, 16006, 16131, 16424, 16653, 16657, 17081, 17106]
incomplete name 3, col: 13308 row: []
col: 13309 similar rows:  [13309, 16489]
incomplete name 3, col: 13309 row: []
col: 13311 similar rows:  [13311]
11111111111111111111
incomplete name 3, col: 13311 row: []
col: 13312 similar rows:  [13312]
11111111111111111111
incomplete name 3, col: 13312 row: []
col: 13313 similar rows:  [13313, 15987, 15999]
incomplete name 3, col: 13313 row: []
col: 13314 similar rows:  [13314]
11111111111111111111
hotelname2 [13314]
incomplete name 3, col: 13314 row: [13314]
col: 13315 similar rows:  [13315, 16859]
incomplete name 3, col: 13315 row: []

col: 13316 similar rows:  [13316, 15663, 16163, 16169, 16182, 16606, 16896, 16986]
incomplete name 3, col: 13316 row: []
col: 13318 similar rows:  [13318, 15619, 16065, 16314]
incomplete name 3, col: 13318 row: []
col: 13319 similar rows:  [13319, 15668, 15699, 15894, 16286, 16333]
incomplete name 3, col: 13319 row: []
col: 13320 similar rows:  [13320, 15365, 17035]
incomplete name 3, col: 13320 row: []
col: 13321 similar rows:  [13321]
11111111111111111111
incomplete name 3, col: 13321 row: []
col: 13322 similar rows:  [13322, 15487, 15517, 15857, 16090, 16711, 16907]
incomplete name 3, col: 13322 row: []
col: 13323 similar rows:  [13323]
11111111111111111111
hotelname2 [13323]
incomplete name 3, col: 13323 row: [13323]
col: 13324 similar rows:  [13324, 15295, 15452, 16061, 16082, 16380, 16466, 16963, 17163]
incomplete name 3, col: 13324 row: []
col: 13325 similar rows:  [13325, 15469, 15736, 15822, 15929, 15993, 16277, 16319, 16408, 16415, 16976]
incomplete name 3, col: 13325 row: []
col: 13326 similar rows:  [13326]
11111111111111111111
incomplete name 3, col: 13326 row: []
col: 13327 similar rows:  [13327, 15260]
incomplete name 3, col: 13327 row: []
col: 13328 similar rows:  [13328, 15320, 15408]
incomplete name 3, col: 13328 row: []
col: 13329 similar rows:  [13329, 15512]
incomplete name 3, col: 13329 row: []
col: 13330 similar rows:  [13330, 15785, 15786]
incomplete name 3, col: 13330 row: []
col: 13331 similar rows:  [13331, 15982, 16202]
incomplete name 3, col: 13331 row: []
col: 13332 similar rows:  [13332, 15389, 16272, 16296, 16943]
incomplete name 3, col: 13332 row: []
col: 13333 similar rows:  [13333, 16864]
incomplete name 3, col: 13333 row: []
col: 13334 similar rows:  [13334]
11111111111111111111
incomplete name 3, col: 13334 row: []
col: 13335 similar rows:  [13335, 15606, 16073]
incomplete name 3, col: 13335 row: []
col: 13336 similar rows:  [13336]
11111111111111111111
hotelname2 [13336]
incomplete name 3, col: 13336 row: [13336]
col: 13337 similar rows:  [13337, 15332, 16717]
incomplete name 3, col: 13337 row: []
col: 13338 similar rows:  [13338]
11111111111111111111
incomplete name 3, col: 13338 row: []
col: 13339 similar rows:  [13339, 17096]
incomplete name 3, col: 13339 row: []
col: 13340 similar rows:  [13340, 15874]
incomplete name 3, col: 13340 row: []
col: 13341 similar rows:  [13341, 16226]
incomplete name 3, col: 13341 row: []
col: 13342 similar rows:  [13342, 15338, 15506, 16362, 16480, 16575]
incomplete name 3, col: 13342 row: []
col: 13343 similar rows:  [13343]
11111111111111111111
hotelname2 [13343]
incomplete name 3, col: 13343 row: []
col: 13344 similar rows:  [13344]
11111111111111111111
incomplete name 3, col: 13344 row: []
col: 13345 similar rows:  [13345, 16969]
incomplete name 3, col: 13345 row: []
col: 13346 similar rows:  [13346]
11111111111111111111
incomplete name 3, col: 13346 row: []
col: 13347 similar rows:  [13347, 17084, 17198]
incomplete name 3, col: 13347 row: []
col: 15261 similar rows:  [15261, 16211, 16933, 17223]
incomplete name 3, col: 15261 row: []
col: 15262 similar rows:  [15262, 15488, 17101]
incomplete name 3, col: 15262 row: []
col: 15263 similar rows:  [15263]
11111111111111111111
incomplete name 3, col: 15263 row: []
col: 15264 similar rows:  [15264, 15532, 15609, 15850, 16098, 16509, 16681]
incomplete name 3, col: 15264 row: []
col: 15265 similar rows:  [15265]
11111111111111111111
incomplete name 3, col: 15265 row: []
col: 15266 similar rows:  [15266]
11111111111111111111
incomplete name 3, col: 15266 row: []
col: 15267 similar rows:  [15267]
11111111111111111111
incomplete name 3, col: 15267 row: []
col: 15268 similar rows:  [15268]
11111111111111111111
incomplete name 3, col: 15268 row: []
col: 15269 similar rows:  [15269, 15473, 15589]
incomplete name 3, col: 15269 row: []
col: 15270 similar rows:  [15270]
11111111111111111111
incomplete name 3, col: 15270 row: []
col: 15272 similar rows:  [15272, 15747, 15868]
incomplete name 3, col: 15272 row: []
col: 15273 similar rows:  [15273]
11111111111111111111
incomplete name 3, col: 15273 row: []
col: 15274 similar rows:  [15274, 16409, 16740, 17008]
incomplete name 3, col: 15274 row: []
col: 15275 similar rows:  [15275]
11111111111111111111
incomplete name 3, col: 15275 row: []
col: 15276 similar rows:  [15276]
11111111111111111111
incomplete name 3, col: 15276 row: []
col: 15277 similar rows:  [15277]
11111111111111111111
incomplete name 3, col: 15277 row: []
col: 15278 similar rows:  [15278, 16300, 16957]
incomplete name 3, col: 15278 row: []
col: 15279 similar rows:  [15279]
11111111111111111111
incomplete name 3, col: 15279 row: []
col: 15280 similar rows:  [15280]
11111111111111111111
incomplete name 3, col: 15280 row: []
col: 15281 similar rows:  [15281]
11111111111111111111
incomplete name 3, col: 15281 row: []
col: 15282 similar rows:  [15282]
11111111111111111111
incomplete name 3, col: 15282 row: []
col: 15283 similar rows:  [15283, 15633, 16052, 16274, 16275, 16290, 16516, 16576, 16584]
incomplete name 3, col: 15283 row: []
col: 15284 similar rows:  [15284]
11111111111111111111
hotelname2 [15284]
incomplete name 3, col: 15284 row: [15284]
col: 15285 similar rows:  [15285, 17182]
incomplete name 3, col: 15285 row: []
col: 15286 similar rows:  [15286]
11111111111111111111
incomplete name 3, col: 15286 row: []
col: 15287 similar rows:  [15287]
11111111111111111111
incomplete name 3, col: 15287 row: []
col: 15289 similar rows:  [15289, 16670, 17054]
incomplete name 3, col: 15289 row: []
col: 15290 similar rows:  [15290]
11111111111111111111
incomplete name 3, col: 15290 row: []
col: 15291 similar rows:  [15291, 15476, 15832, 15932, 16524]
incomplete name 3, col: 15291 row: []
col: 15292 similar rows:  [15292]
11111111111111111111
hotelname2 [15292]
incomplete name 3, col: 15292 row: [15292]
col: 15293 similar rows:  [15293, 15667, 15968, 16104, 16120, 16658, 16678]
incomplete name 3, col: 15293 row: []
col: 15294 similar rows:  [15294]
11111111111111111111
hotelname2 [15294]
wrong name!!!!
incomplete name 3, col: 15294 row: [15294]
col: 15296 similar rows:  [15296, 16099, 17133]
incomplete name 3, col: 15296 row: []
col: 15297 similar rows:  [15297]
11111111111111111111
hotelname2 [15297]
incomplete name 3, col: 15297 row: [15297]
col: 15298 similar rows:  [15298]
11111111111111111111
hotelname2 [15298]
wrong name!!!!
incomplete name 3, col: 15298 row: [15298]
col: 15299 similar rows:  [15299, 15390, 15877, 16530, 16537]
incomplete name 3, col: 15299 row: []
col: 15300 similar rows:  [15300]
11111111111111111111
hotelname2 [15300]
wrong name!!!!
incomplete name 3, col: 15300 row: [15300]
col: 15301 similar rows:  [15301, 16174]
incomplete name 3, col: 15301 row: []
col: 15302 similar rows:  [15302, 16113, 17104]
incomplete name 3, col: 15302 row: []
col: 15304 similar rows:  [15304, 15424, 15762]
incomplete name 3, col: 15304 row: []
col: 15305 similar rows:  [15305, 15360, 15375, 16504, 16526, 17181]
incomplete name 3, col: 15305 row: []
col: 15307 similar rows:  [15307, 16557]
incomplete name 3, col: 15307 row: []
col: 15308 similar rows:  [15308]
11111111111111111111
incomplete name 3, col: 15308 row: []
col: 15309 similar rows:  [15309]
11111111111111111111
incomplete name 3, col: 15309 row: []
col: 15310 similar rows:  [15310]
11111111111111111111
incomplete name 3, col: 15310 row: []
col: 15311 similar rows:  [15311, 16835, 16894, 17042]
incomplete name 3, col: 15311 row: []
col: 15312 similar rows:  [15312, 15909, 16192, 16234, 16712]
incomplete name 3, col: 15312 row: []
col: 15313 similar rows:  [15313]
11111111111111111111
incomplete name 3, col: 15313 row: []
col: 15314 similar rows:  [15314]
11111111111111111111
hotelname2 [15314]
incomplete name 3, col: 15314 row: [15314]
col: 15315 similar rows:  [15315]
11111111111111111111
incomplete name 3, col: 15315 row: []
col: 15316 similar rows:  [15316]
11111111111111111111
hotelname2 [15316]
incomplete name 3, col: 15316 row: [15316]
col: 15317 similar rows:  [15317]
11111111111111111111
incomplete name 3, col: 15317 row: []
col: 15319 similar rows:  [15319]
11111111111111111111
incomplete name 3, col: 15319 row: []
col: 15321 similar rows:  [15321, 16973]
incomplete name 3, col: 15321 row: []
col: 15322 similar rows:  [15322]
11111111111111111111
incomplete name 3, col: 15322 row: []
col: 15323 similar rows:  [15323]
11111111111111111111
hotelname2 [15323]
wrong name!!!!
incomplete name 3, col: 15323 row: [15323]
col: 15324 similar rows:  [15324, 15798, 15813, 15859, 16031, 16237, 16432, 16813, 16868, 17050]
incomplete name 3, col: 15324 row: []
col: 15325 similar rows:  [15325]
11111111111111111111
incomplete name 3, col: 15325 row: []
col: 15326 similar rows:  [15326]
11111111111111111111
incomplete name 3, col: 15326 row: []
col: 15327 similar rows:  [15327, 15400]
incomplete name 3, col: 15327 row: []

col: 15328 similar rows:  [15328, 15967, 16215, 16540]
incomplete name 3, col: 15328 row: []
col: 15329 similar rows:  [15329]
11111111111111111111
incomplete name 3, col: 15329 row: []
col: 15330 similar rows:  [15330]
11111111111111111111
incomplete name 3, col: 15330 row: []
col: 15331 similar rows:  [15331]
11111111111111111111
incomplete name 3, col: 15331 row: []
col: 15333 similar rows:  [15333, 17197]
incomplete name 3, col: 15333 row: []
col: 15335 similar rows:  [15335]
11111111111111111111
incomplete name 3, col: 15335 row: []
col: 15336 similar rows:  [15336]
11111111111111111111
incomplete name 3, col: 15336 row: []
col: 15337 similar rows:  [15337]
11111111111111111111
incomplete name 3, col: 15337 row: []
col: 15339 similar rows:  [15339]
11111111111111111111
incomplete name 3, col: 15339 row: []
col: 15340 similar rows:  [15340, 16841]
incomplete name 3, col: 15340 row: []
col: 15342 similar rows:  [15342]
11111111111111111111
incomplete name 3, col: 15342 row: []
col: 15343 similar rows:  [15343]
11111111111111111111
incomplete name 3, col: 15343 row: []
col: 15344 similar rows:  [15344]
11111111111111111111
incomplete name 3, col: 15344 row: []
col: 15345 similar rows:  [15345]
11111111111111111111
incomplete name 3, col: 15345 row: []
col: 15348 similar rows:  [15348]
11111111111111111111
hotelname2 [15348]
incomplete name 3, col: 15348 row: []
col: 15349 similar rows:  [15349]
11111111111111111111
incomplete name 3, col: 15349 row: []
col: 15351 similar rows:  [15351]
11111111111111111111
incomplete name 3, col: 15351 row: []
col: 15353 similar rows:  [15353, 15867, 15886, 16263, 16977]
incomplete name 3, col: 15353 row: []
col: 15354 similar rows:  [15354, 15588, 16438]
incomplete name 3, col: 15354 row: []
col: 15355 similar rows:  [15355]
11111111111111111111
incomplete name 3, col: 15355 row: []
col: 15356 similar rows:  [15356]
11111111111111111111
hotelname2 [15356]
incomplete name 3, col: 15356 row: [15356]
col: 15357 similar rows:  [15357, 15485, 15594, 16327, 16353, 16367, 16733]
incomplete name 3, col: 15357 row: []
col: 15358 similar rows:  [15358]
11111111111111111111
incomplete name 3, col: 15358 row: []
col: 15359 similar rows:  [15359]
11111111111111111111
incomplete name 3, col: 15359 row: []
col: 15361 similar rows:  [15361, 15447, 15665, 16010, 16276]
incomplete name 3, col: 15361 row: []
col: 15363 similar rows:  [15363, 15406, 15658, 15945, 16425, 16607]
incomplete name 3, col: 15363 row: []
col: 15364 similar rows:  [15364, 16861]
incomplete name 3, col: 15364 row: []
col: 15366 similar rows:  [15366]
11111111111111111111
hotelname2 [15366]
incomplete name 3, col: 15366 row: [15366]
col: 15367 similar rows:  [15367, 16927]
incomplete name 3, col: 15367 row: []
col: 15368 similar rows:  [15368, 15970]
incomplete name 3, col: 15368 row: []
col: 15369 similar rows:  [15369]
11111111111111111111
hotelname2 [15369]
incomplete name 3, col: 15369 row: [15369]
col: 15370 similar rows:  [15370, 15531, 16154, 16673, 16677, 16687, 17103]
incomplete name 3, col: 15370 row: []
col: 15371 similar rows:  [15371]
11111111111111111111
incomplete name 3, col: 15371 row: []
col: 15372 similar rows:  [15372, 15846, 15874]
incomplete name 3, col: 15372 row: []
col: 15373 similar rows:  [15373, 15961]
incomplete name 3, col: 15373 row: []
col: 15374 similar rows:  [15374]
11111111111111111111
hotelname2 [15374]
incomplete name 3, col: 15374 row: [15374]
col: 15376 similar rows:  [15376, 15678, 16746]
incomplete name 3, col: 15376 row: []
col: 15377 similar rows:  [15377]
11111111111111111111
incomplete name 3, col: 15377 row: []
col: 15378 similar rows:  [15378]
11111111111111111111
incomplete name 3, col: 15378 row: []
col: 15379 similar rows:  [15379, 15475, 16401, 16436, 16880]
incomplete name 3, col: 15379 row: []
col: 15380 similar rows:  [15380]
11111111111111111111
incomplete name 3, col: 15380 row: []
col: 15381 similar rows:  [15381]
11111111111111111111
incomplete name 3, col: 15381 row: []
col: 15382 similar rows:  [15382]
11111111111111111111
incomplete name 3, col: 15382 row: []
col: 15383 similar rows:  [15383, 15649, 15789, 15905, 16042, 16786, 17052, 17175]
incomplete name 3, col: 15383 row: []
col: 15384 similar rows:  [15384]
11111111111111111111
incomplete name 3, col: 15384 row: []
col: 15385 similar rows:  [15385]
11111111111111111111
incomplete name 3, col: 15385 row: []
col: 15386 similar rows:  [15386, 15507]
incomplete name 3, col: 15386 row: []
col: 15387 similar rows:  [15387, 16656]
incomplete name 3, col: 15387 row: []
col: 15388 similar rows:  [15388, 16416]
incomplete name 3, col: 15388 row: []
col: 15391 similar rows:  [15391]
11111111111111111111
hotelname2 [15391]
incomplete name 3, col: 15391 row: []
col: 15392 similar rows:  [15392]
11111111111111111111
incomplete name 3, col: 15392 row: []
col: 15393 similar rows:  [15393]
11111111111111111111
incomplete name 3, col: 15393 row: []
col: 15394 similar rows:  [15394]
11111111111111111111
incomplete name 3, col: 15394 row: []
col: 15395 similar rows:  [15395, 16451, 16565]
incomplete name 3, col: 15395 row: []
col: 15396 similar rows:  [15396, 16502, 16997]
incomplete name 3, col: 15396 row: []
col: 15397 similar rows:  [15397]
11111111111111111111
hotelname2 [15397]
incomplete name 3, col: 15397 row: [15397]
col: 15398 similar rows:  [15398, 15869, 16256]
incomplete name 3, col: 15398 row: []
col: 15399 similar rows:  [15399]
11111111111111111111
incomplete name 3, col: 15399 row: []
col: 15401 similar rows:  [15401, 16047, 16490, 16518, 16592, 16739, 16874, 17192]
incomplete name 3, col: 15401 row: []
col: 15402 similar rows:  [15402, 15486, 15833, 16232, 16350, 16435, 16555, 16686]
incomplete name 3, col: 15402 row: []
col: 15403 similar rows:  [15403, 15882, 16070, 16690]
incomplete name 3, col: 15403 row: []
col: 15404 similar rows:  [15404, 16665, 16824]
incomplete name 3, col: 15404 row: []
col: 15405 similar rows:  [15405]
11111111111111111111
hotelname2 [15405]
incomplete name 3, col: 15405 row: [15405]
col: 15407 similar rows:  [15407, 16243]
incomplete name 3, col: 15407 row: []
col: 15409 similar rows:  [15409, 16063]
incomplete name 3, col: 15409 row: []
col: 15410 similar rows:  [15410, 15902, 16059, 16151, 16450, 16601, 16988, 17028]
incomplete name 3, col: 15410 row: []
col: 15411 similar rows:  [15411, 16672]
incomplete name 3, col: 15411 row: []
col: 15412 similar rows:  [15412]
11111111111111111111
incomplete name 3, col: 15412 row: []
col: 15414 similar rows:  [15414]
11111111111111111111
incomplete name 3, col: 15414 row: []
col: 15415 similar rows:  [15415]
11111111111111111111
incomplete name 3, col: 15415 row: []
col: 15416 similar rows:  [15416]
11111111111111111111
incomplete name 3, col: 15416 row: []
col: 15417 similar rows:  [15417]
11111111111111111111
incomplete name 3, col: 15417 row: []
col: 15418 similar rows:  [15418]
11111111111111111111
incomplete name 3, col: 15418 row: []
col: 15419 similar rows:  [15419]
11111111111111111111
incomplete name 3, col: 15419 row: []
col: 15420 similar rows:  [15420]
11111111111111111111
incomplete name 3, col: 15420 row: []
col: 15421 similar rows:  [15421]
11111111111111111111
hotelname2 [15421]
incomplete name 3, col: 15421 row: [15421]
col: 15422 similar rows:  [15422]
11111111111111111111
incomplete name 3, col: 15422 row: []
col: 15423 similar rows:  [15423]
11111111111111111111
incomplete name 3, col: 15423 row: []
col: 15425 similar rows:  [15425, 16245, 16396]
incomplete name 3, col: 15425 row: []
col: 15426 similar rows:  [15426, 16139]
incomplete name 3, col: 15426 row: []
col: 15427 similar rows:  [15427]
11111111111111111111
incomplete name 3, col: 15427 row: []
col: 15428 similar rows:  [15428]
11111111111111111111
incomplete name 3, col: 15428 row: []
col: 15429 similar rows:  [15429]
11111111111111111111
incomplete name 3, col: 15429 row: []
col: 15430 similar rows:  [15430]
11111111111111111111
incomplete name 3, col: 15430 row: []
col: 15431 similar rows:  [15431]
11111111111111111111
hotelname2 [15431]
incomplete name 3, col: 15431 row: []
col: 15432 similar rows:  [15432]
11111111111111111111
incomplete name 3, col: 15432 row: []
col: 15433 similar rows:  [15433]
11111111111111111111
incomplete name 3, col: 15433 row: []
col: 15434 similar rows:  [15434]
11111111111111111111
incomplete name 3, col: 15434 row: []
col: 15435 similar rows:  [15435]
11111111111111111111
incomplete name 3, col: 15435 row: []
col: 15436 similar rows:  [15436, 15437, 15856, 17214]
incomplete name 3, col: 15436 row: []
col: 15438 similar rows:  [15438, 16246, 16712, 16924]
incomplete name 3, col: 15438 row: []

col: 15439 similar rows:  [15439]
11111111111111111111
incomplete name 3, col: 15439 row: []
col: 15440 similar rows:  [15440]
11111111111111111111
incomplete name 3, col: 15440 row: []
col: 15441 similar rows:  [15441]
11111111111111111111
incomplete name 3, col: 15441 row: []
col: 15442 similar rows:  [15442]
11111111111111111111
incomplete name 3, col: 15442 row: []
col: 15443 similar rows:  [15443]
11111111111111111111
incomplete name 3, col: 15443 row: []
col: 15444 similar rows:  [15444, 15866, 16642, 16652, 16654, 16667, 16682, 16805, 17147, 17187]
incomplete name 3, col: 15444 row: []
col: 15445 similar rows:  [15445, 17071]
incomplete name 3, col: 15445 row: []
col: 15446 similar rows:  [15446, 15801, 16018, 16719, 16934, 17092]
incomplete name 3, col: 15446 row: []
col: 15448 similar rows:  [15448]
11111111111111111111
incomplete name 3, col: 15448 row: []
col: 15450 similar rows:  [15450, 16536]
incomplete name 3, col: 15450 row: []
col: 15451 similar rows:  [15451]
11111111111111111111
incomplete name 3, col: 15451 row: []
col: 15453 similar rows:  [15453]
11111111111111111111
incomplete name 3, col: 15453 row: []
col: 15454 similar rows:  [15454, 17126]
incomplete name 3, col: 15454 row: []
col: 15455 similar rows:  [15455, 15934, 15960, 16060, 16561]
incomplete name 3, col: 15455 row: []
col: 15456 similar rows:  [15456, 16718]
incomplete name 3, col: 15456 row: []
col: 15457 similar rows:  [15457, 16707]
incomplete name 3, col: 15457 row: []
col: 15458 similar rows:  [15458]
11111111111111111111
hotelname2 [15458]
incomplete name 3, col: 15458 row: [15458]
col: 15459 similar rows:  [15459, 15603, 16285]
incomplete name 3, col: 15459 row: []
col: 15460 similar rows:  [15460, 17025]
incomplete name 3, col: 15460 row: []
col: 15461 similar rows:  [15461, 16128, 16981]
incomplete name 3, col: 15461 row: []
col: 15462 similar rows:  [15462]
11111111111111111111
hotelname2 [15462]
incomplete name 3, col: 15462 row: [15462]
col: 15463 similar rows:  [15463, 15645, 15704, 16218]
incomplete name 3, col: 15463 row: []
col: 15464 similar rows:  [15464]
11111111111111111111
hotelname2 [15464]
incomplete name 3, col: 15464 row: [15464]
col: 15465 similar rows:  [15465]
11111111111111111111
incomplete name 3, col: 15465 row: []
col: 15466 similar rows:  [15466]
11111111111111111111
incomplete name 3, col: 15466 row: []
col: 15467 similar rows:  [15467]
11111111111111111111
incomplete name 3, col: 15467 row: []
col: 15468 similar rows:  [15468]
11111111111111111111
hotelname2 [15468]
incomplete name 3, col: 15468 row: [15468]
col: 15471 similar rows:  [15471]
11111111111111111111
incomplete name 3, col: 15471 row: []
col: 15472 similar rows:  [15472]
11111111111111111111
incomplete name 3, col: 15472 row: []
col: 15474 similar rows:  [15474]
11111111111111111111
incomplete name 3, col: 15474 row: []
col: 15477 similar rows:  [15477]
11111111111111111111
incomplete name 3, col: 15477 row: []
col: 15478 similar rows:  [15478, 15907, 15927, 16026, 16259, 16371, 16484]
incomplete name 3, col: 15478 row: []
col: 15479 similar rows:  [15479]
11111111111111111111
incomplete name 3, col: 15479 row: []
col: 15480 similar rows:  [15480]
11111111111111111111
hotelname2 [15480]
incomplete name 3, col: 15480 row: [15480]
col: 15481 similar rows:  [15481]
11111111111111111111
incomplete name 3, col: 15481 row: []
col: 15482 similar rows:  [15482]
11111111111111111111
incomplete name 3, col: 15482 row: []
col: 15483 similar rows:  [15483, 16014]
incomplete name 3, col: 15483 row: []
col: 15484 similar rows:  [15484]
11111111111111111111
incomplete name 3, col: 15484 row: []
col: 15489 similar rows:  [15489]
11111111111111111111
incomplete name 3, col: 15489 row: []
col: 15490 similar rows:  [15490]
11111111111111111111
hotelname2 [15490]
incomplete name 3, col: 15490 row: [15490]
col: 15491 similar rows:  [15491]
11111111111111111111
incomplete name 3, col: 15491 row: []
col: 15492 similar rows:  [15492, 15872]
incomplete name 3, col: 15492 row: []
col: 15493 similar rows:  [15493, 15774, 15903, 16115]
incomplete name 3, col: 15493 row: []
col: 15494 similar rows:  [15494]
11111111111111111111
hotelname2 [15494]
incomplete name 3, col: 15494 row: []
col: 15495 similar rows:  [15495]
11111111111111111111
incomplete name 3, col: 15495 row: []
col: 15496 similar rows:  [15496]
11111111111111111111
hotelname2 [15496]
incomplete name 3, col: 15496 row: [15496]
col: 15497 similar rows:  [15497]
11111111111111111111
incomplete name 3, col: 15497 row: []
col: 15498 similar rows:  [15498]
11111111111111111111
incomplete name 3, col: 15498 row: []
col: 15499 similar rows:  [15499]
11111111111111111111
incomplete name 3, col: 15499 row: []
col: 15500 similar rows:  [15500]
11111111111111111111
incomplete name 3, col: 15500 row: []
col: 15501 similar rows:  [15501]
11111111111111111111
incomplete name 3, col: 15501 row: []
col: 15502 similar rows:  [15502, 15938, 16488, 16875, 16900, 17180, 17202]
incomplete name 3, col: 15502 row: []
col: 15503 similar rows:  [15503]
11111111111111111111
incomplete name 3, col: 15503 row: []
col: 15504 similar rows:  [15504, 16153, 16361, 16417, 16455, 16809, 17173]
incomplete name 3, col: 15504 row: []
col: 15505 similar rows:  [15505, 15543, 17170, 17190]
incomplete name 3, col: 15505 row: []
col: 15509 similar rows:  [15509]
11111111111111111111
incomplete name 3, col: 15509 row: []
col: 15510 similar rows:  [15510]
11111111111111111111
incomplete name 3, col: 15510 row: []
col: 15511 similar rows:  [15511]
11111111111111111111
incomplete name 3, col: 15511 row: []
col: 15513 similar rows:  [15513, 15816, 16056, 16410, 16574, 16625, 16902, 16904]
incomplete name 3, col: 15513 row: []
col: 15514 similar rows:  [15514, 15530]
incomplete name 3, col: 15514 row: []
col: 15515 similar rows:  [15515]
11111111111111111111
incomplete name 3, col: 15515 row: []
col: 15516 similar rows:  [15516, 15613]
incomplete name 3, col: 15516 row: []
col: 15518 similar rows:  [15518]
11111111111111111111
incomplete name 3, col: 15518 row: []
col: 15519 similar rows:  [15519]
11111111111111111111
incomplete name 3, col: 15519 row: []
col: 15520 similar rows:  [15520]
11111111111111111111
incomplete name 3, col: 15520 row: []
col: 15521 similar rows:  [15521]
11111111111111111111
incomplete name 3, col: 15521 row: []
col: 15522 similar rows:  [15522, 17229]
incomplete name 3, col: 15522 row: []
col: 15523 similar rows:  [15523]
11111111111111111111
hotelname2 [15523]
incomplete name 3, col: 15523 row: [15523]
col: 15524 similar rows:  [15524]
11111111111111111111
hotelname2 [15524]
incomplete name 3, col: 15524 row: []
col: 15525 similar rows:  [15525]
11111111111111111111
incomplete name 3, col: 15525 row: []
col: 15526 similar rows:  [15526, 15527]
incomplete name 3, col: 15526 row: []
col: 15528 similar rows:  [15528]
11111111111111111111
hotelname2 [15528]
incomplete name 3, col: 15528 row: [15528]
col: 15529 similar rows:  [15529, 15866, 16642, 16652, 16805]
incomplete name 3, col: 15529 row: []
col: 15533 similar rows:  [15533, 16895]
incomplete name 3, col: 15533 row: []
col: 15534 similar rows:  [15534]
11111111111111111111
incomplete name 3, col: 15534 row: []
col: 15535 similar rows:  [15535, 15675, 15677, 15952, 16043, 16889]
incomplete name 3, col: 15535 row: []
col: 15536 similar rows:  [15536]
11111111111111111111
hotelname2 [15536]
incomplete name 3, col: 15536 row: []
col: 15537 similar rows:  [15537]
11111111111111111111
hotelname2 [15537]
incomplete name 3, col: 15537 row: [15537]
col: 15538 similar rows:  [15538, 15779]
incomplete name 3, col: 15538 row: []
col: 15539 similar rows:  [15539, 16928]
incomplete name 3, col: 15539 row: []
col: 15540 similar rows:  [15540, 15564, 16119, 16382, 16674, 17076]
incomplete name 3, col: 15540 row: []
col: 15541 similar rows:  [15541]
11111111111111111111
incomplete name 3, col: 15541 row: []
col: 15542 similar rows:  [15542, 16703]
incomplete name 3, col: 15542 row: []
col: 15544 similar rows:  [15544, 15807]
incomplete name 3, col: 15544 row: []
col: 15545 similar rows:  [15545]
11111111111111111111
incomplete name 3, col: 15545 row: []
col: 15546 similar rows:  [15546]
11111111111111111111
incomplete name 3, col: 15546 row: []
col: 15547 similar rows:  [15547]
11111111111111111111
incomplete name 3, col: 15547 row: []
col: 15548 similar rows:  [15548]
11111111111111111111
incomplete name 3, col: 15548 row: []
col: 15549 similar rows:  [15549]
11111111111111111111
incomplete name 3, col: 15549 row: []
col: 15551 similar rows:  [15551]
11111111111111111111
incomplete name 3, col: 15551 row: []
col: 15552 similar rows:  [15552, 16837]
incomplete name 3, col: 15552 row: []

col: 15553 similar rows:  [15553]
11111111111111111111
incomplete name 3, col: 15553 row: []
col: 15554 similar rows:  [15554]
11111111111111111111
incomplete name 3, col: 15554 row: []
col: 15555 similar rows:  [15555, 15650, 16991, 17177]
incomplete name 3, col: 15555 row: []
col: 15556 similar rows:  [15556]
11111111111111111111
hotelname2 [15556]
incomplete name 3, col: 15556 row: [15556]
col: 15557 similar rows:  [15557]
11111111111111111111
incomplete name 3, col: 15557 row: []
col: 15559 similar rows:  [15559]
11111111111111111111
incomplete name 3, col: 15559 row: []
col: 15560 similar rows:  [15560]
11111111111111111111
incomplete name 3, col: 15560 row: []
col: 15561 similar rows:  [15561]
11111111111111111111
incomplete name 3, col: 15561 row: []
col: 15562 similar rows:  [15562]
11111111111111111111
incomplete name 3, col: 15562 row: []
col: 15563 similar rows:  [15563]
11111111111111111111
hotelname2 [15563]
incomplete name 3, col: 15563 row: [15563]
col: 15565 similar rows:  [15565]
11111111111111111111
incomplete name 3, col: 15565 row: []
col: 15566 similar rows:  [15566, 16129]
incomplete name 3, col: 15566 row: []
col: 15567 similar rows:  [15567]
11111111111111111111
incomplete name 3, col: 15567 row: []
col: 15568 similar rows:  [15568]
11111111111111111111
incomplete name 3, col: 15568 row: []
col: 15569 similar rows:  [15569, 15612, 15638]
incomplete name 3, col: 15569 row: []
col: 15570 similar rows:  [15570]
11111111111111111111
incomplete name 3, col: 15570 row: []
col: 15571 similar rows:  [15571]
11111111111111111111
incomplete name 3, col: 15571 row: []
col: 15572 similar rows:  [15572]
11111111111111111111
hotelname2 [15572]
incomplete name 3, col: 15572 row: [15572]
col: 15573 similar rows:  [15573, 15657, 16181, 16224, 17068, 17217]
incomplete name 3, col: 15573 row: []
col: 15574 similar rows:  [15574]
11111111111111111111
incomplete name 3, col: 15574 row: []
col: 15575 similar rows:  [15575]
11111111111111111111
incomplete name 3, col: 15575 row: []
col: 15576 similar rows:  [15576, 15713]
incomplete name 3, col: 15576 row: []
col: 15578 similar rows:  [15578, 16478]
incomplete name 3, col: 15578 row: []
col: 15580 similar rows:  [15580]
11111111111111111111
incomplete name 3, col: 15580 row: []
col: 15581 similar rows:  [15581, 15669]
incomplete name 3, col: 15581 row: []
col: 15582 similar rows:  [15582, 15841]
incomplete name 3, col: 15582 row: []
col: 15583 similar rows:  [15583, 15647, 15856, 17214]
incomplete name 3, col: 15583 row: []
col: 15584 similar rows:  [15584]
11111111111111111111
incomplete name 3, col: 15584 row: []
col: 15585 similar rows:  [15585]
11111111111111111111
incomplete name 3, col: 15585 row: []
col: 15587 similar rows:  [15587]
11111111111111111111
incomplete name 3, col: 15587 row: []
col: 15590 similar rows:  [15590]
11111111111111111111
hotelname2 [15590]
incomplete name 3, col: 15590 row: []
col: 15591 similar rows:  [15591]
11111111111111111111
incomplete name 3, col: 15591 row: []
col: 15592 similar rows:  [15592, 15740]
incomplete name 3, col: 15592 row: []
col: 15593 similar rows:  [15593]
11111111111111111111
hotelname2 [15593]
incomplete name 3, col: 15593 row: [15593]
col: 15595 similar rows:  [15595, 15973, 16087]
incomplete name 3, col: 15595 row: []
col: 15596 similar rows:  [15596]
11111111111111111111
incomplete name 3, col: 15596 row: []
col: 15598 similar rows:  [15598, 15864]
incomplete name 3, col: 15598 row: []
col: 15599 similar rows:  [15599]
11111111111111111111
hotelname2 [15599]
incomplete name 3, col: 15599 row: [15599]
col: 15600 similar rows:  [15600]
11111111111111111111
incomplete name 3, col: 15600 row: []
col: 15602 similar rows:  [15602]
11111111111111111111
incomplete name 3, col: 15602 row: []
col: 15604 similar rows:  [15604, 15950, 15962, 16471, 17102]
incomplete name 3, col: 15604 row: []
col: 15605 similar rows:  [15605]
11111111111111111111
hotelname2 [15605]
incomplete name 3, col: 15605 row: [15605]
col: 15607 similar rows:  [15607, 15624, 16138, 17073]
hotelname2 [15624]
incomplete name 3, col: 15607 row: []
col: 15608 similar rows:  [15608]
11111111111111111111
incomplete name 3, col: 15608 row: []
col: 15610 similar rows:  [15610]
11111111111111111111
incomplete name 3, col: 15610 row: []
col: 15611 similar rows:  [15611, 16865, 16886]
incomplete name 3, col: 15611 row: []
col: 15614 similar rows:  [15614, 16834]
incomplete name 3, col: 15614 row: []
col: 15615 similar rows:  [15615]
11111111111111111111
incomplete name 3, col: 15615 row: []
col: 15616 similar rows:  [15616, 15995]
incomplete name 3, col: 15616 row: []
col: 15617 similar rows:  [15617, 16932]
incomplete name 3, col: 15617 row: []
col: 15618 similar rows:  [15618]
11111111111111111111
incomplete name 3, col: 15618 row: []
col: 15620 similar rows:  [15620]
11111111111111111111
incomplete name 3, col: 15620 row: []
col: 15621 similar rows:  [15621]
11111111111111111111
incomplete name 3, col: 15621 row: []
col: 15622 similar rows:  [15622]
11111111111111111111
incomplete name 3, col: 15622 row: []
col: 15623 similar rows:  [15623]
11111111111111111111
incomplete name 3, col: 15623 row: []
col: 15625 similar rows:  [15625]
11111111111111111111
incomplete name 3, col: 15625 row: []
col: 15626 similar rows:  [15626, 16293, 16472, 16541, 16627, 16819, 16873, 16989]
incomplete name 3, col: 15626 row: []
col: 15627 similar rows:  [15627]
11111111111111111111
incomplete name 3, col: 15627 row: []
col: 15628 similar rows:  [15628]
11111111111111111111
incomplete name 3, col: 15628 row: []
col: 15629 similar rows:  [15629, 16381, 17067]
incomplete name 3, col: 15629 row: []
col: 15631 similar rows:  [15631]
11111111111111111111
incomplete name 3, col: 15631 row: []
col: 15632 similar rows:  [15632]
11111111111111111111
incomplete name 3, col: 15632 row: []
col: 15634 similar rows:  [15634]
11111111111111111111
incomplete name 3, col: 15634 row: []
col: 15635 similar rows:  [15635]
11111111111111111111
incomplete name 3, col: 15635 row: []
col: 15636 similar rows:  [15636]
11111111111111111111
incomplete name 3, col: 15636 row: []
col: 15637 similar rows:  [15637, 16036]
incomplete name 3, col: 15637 row: []
col: 15639 similar rows:  [15639]
11111111111111111111
incomplete name 3, col: 15639 row: []
col: 15640 similar rows:  [15640]
11111111111111111111
incomplete name 3, col: 15640 row: []
col: 15641 similar rows:  [15641]
11111111111111111111
incomplete name 3, col: 15641 row: []
col: 15642 similar rows:  [15642, 16646]
incomplete name 3, col: 15642 row: []
col: 15644 similar rows:  [15644]
11111111111111111111
hotelname2 [15644]
incomplete name 3, col: 15644 row: []
col: 15646 similar rows:  [15646, 16560]
incomplete name 3, col: 15646 row: []
col: 15648 similar rows:  [15648, 17212]
incomplete name 3, col: 15648 row: []
col: 15651 similar rows:  [15651]
11111111111111111111
incomplete name 3, col: 15651 row: []
col: 15652 similar rows:  [15652]
11111111111111111111
incomplete name 3, col: 15652 row: []
col: 15653 similar rows:  [15653]
11111111111111111111
incomplete name 3, col: 15653 row: []
col: 15654 similar rows:  [15654, 16047, 16074, 16518, 16592, 16962]
incomplete name 3, col: 15654 row: []
col: 15655 similar rows:  [15655]
11111111111111111111
hotelname2 [15655]
incomplete name 3, col: 15655 row: [15655]
col: 15656 similar rows:  [15656]
11111111111111111111
hotelname2 [15656]
incomplete name 3, col: 15656 row: [15656]
col: 15659 similar rows:  [15659]
11111111111111111111
hotelname2 [15659]
incomplete name 3, col: 15659 row: [15659]
col: 15660 similar rows:  [15660]
11111111111111111111
incomplete name 3, col: 15660 row: []
col: 15661 similar rows:  [15661]
11111111111111111111
incomplete name 3, col: 15661 row: []
col: 15662 similar rows:  [15662, 16870, 17143]
incomplete name 3, col: 15662 row: []
col: 15666 similar rows:  [15666, 15693]
incomplete name 3, col: 15666 row: []
col: 15670 similar rows:  [15670]
11111111111111111111
incomplete name 3, col: 15670 row: []
col: 15671 similar rows:  [15671]
11111111111111111111
incomplete name 3, col: 15671 row: []
col: 15672 similar rows:  [15672]
11111111111111111111
incomplete name 3, col: 15672 row: []
col: 15673 similar rows:  [15673]
11111111111111111111
incomplete name 3, col: 15673 row: []
col: 15674 similar rows:  [15674]
11111111111111111111
incomplete name 3, col: 15674 row: []
col: 15676 similar rows:  [15676]
11111111111111111111
hotelname2 [15676]
incomplete name 3, col: 15676 row: []
col: 15679 similar rows:  [15679, 16085]
incomplete name 3, col: 15679 row: []
col: 15680 similar rows:  [15680]
11111111111111111111
incomplete name 3, col: 15680 row: []

col: 15681 similar rows:  [15681]
11111111111111111111
incomplete name 3, col: 15681 row: []
col: 15682 similar rows:  [15682]
11111111111111111111
incomplete name 3, col: 15682 row: []
col: 15683 similar rows:  [15683]
11111111111111111111
incomplete name 3, col: 15683 row: []
col: 15684 similar rows:  [15684]
11111111111111111111
hotelname2 [15684]
incomplete name 3, col: 15684 row: [15684]
col: 15685 similar rows:  [15685, 15835]
incomplete name 3, col: 15685 row: []
col: 15686 similar rows:  [15686, 16411, 16588]
incomplete name 3, col: 15686 row: []
col: 15687 similar rows:  [15687, 17049]
incomplete name 3, col: 15687 row: []
col: 15688 similar rows:  [15688, 16252, 16935]
incomplete name 3, col: 15688 row: []
col: 15689 similar rows:  [15689]
11111111111111111111
incomplete name 3, col: 15689 row: []
col: 15690 similar rows:  [15690]
11111111111111111111
incomplete name 3, col: 15690 row: []
col: 15691 similar rows:  [15691, 16257]
incomplete name 3, col: 15691 row: []
col: 15692 similar rows:  [15692]
11111111111111111111
incomplete name 3, col: 15692 row: []
col: 15694 similar rows:  [15694, 16570]
incomplete name 3, col: 15694 row: []
col: 15695 similar rows:  [15695, 16068, 16749, 16823]
incomplete name 3, col: 15695 row: []
col: 15696 similar rows:  [15696]
11111111111111111111
hotelname2 [15696]
incomplete name 3, col: 15696 row: [15696]
col: 15697 similar rows:  [15697]
11111111111111111111
incomplete name 3, col: 15697 row: []
col: 15698 similar rows:  [15698, 17209]
incomplete name 3, col: 15698 row: []
col: 15700 similar rows:  [15700]
11111111111111111111
incomplete name 3, col: 15700 row: []
col: 15701 similar rows:  [15701]
11111111111111111111
incomplete name 3, col: 15701 row: []
col: 15703 similar rows:  [15703]
11111111111111111111
incomplete name 3, col: 15703 row: []
col: 15705 similar rows:  [15705]
11111111111111111111
incomplete name 3, col: 15705 row: []
col: 15706 similar rows:  [15706]
11111111111111111111
incomplete name 3, col: 15706 row: []
col: 15707 similar rows:  [15707, 15997, 16011, 16393, 16532, 16582, 16753]
incomplete name 3, col: 15707 row: []
col: 15708 similar rows:  [15708]
11111111111111111111
incomplete name 3, col: 15708 row: []
col: 15709 similar rows:  [15709]
11111111111111111111
incomplete name 3, col: 15709 row: []
col: 15710 similar rows:  [15710]
11111111111111111111
incomplete name 3, col: 15710 row: []
col: 15711 similar rows:  [15711, 16168]
incomplete name 3, col: 15711 row: []
col: 15712 similar rows:  [15712, 15739, 15863]
incomplete name 3, col: 15712 row: []
col: 15714 similar rows:  [15714]
11111111111111111111
hotelname2 [15714]
incomplete name 3, col: 15714 row: [15714]
col: 15715 similar rows:  [15715, 16726, 17075]
incomplete name 3, col: 15715 row: []
col: 15716 similar rows:  [15716]
11111111111111111111
incomplete name 3, col: 15716 row: []
col: 15717 similar rows:  [15717, 15896, 16066, 16602, 16698]
incomplete name 3, col: 15717 row: []
col: 15718 similar rows:  [15718]
11111111111111111111
incomplete name 3, col: 15718 row: []
col: 15719 similar rows:  [15719, 16694]
incomplete name 3, col: 15719 row: []
col: 15720 similar rows:  [15720]
11111111111111111111
hotelname2 [15720]
incomplete name 3, col: 15720 row: [15720]
col: 15721 similar rows:  [15721, 15854]
incomplete name 3, col: 15721 row: []
col: 15722 similar rows:  [15722]
11111111111111111111
hotelname2 [15722]
incomplete name 3, col: 15722 row: [15722]
col: 15723 similar rows:  [15723, 15757, 15799]
incomplete name 3, col: 15723 row: []
col: 15725 similar rows:  [15725, 15796]
incomplete name 3, col: 15725 row: []
col: 15726 similar rows:  [15726]
11111111111111111111
incomplete name 3, col: 15726 row: []
col: 15727 similar rows:  [15727]
11111111111111111111
incomplete name 3, col: 15727 row: []
col: 15728 similar rows:  [15728]
11111111111111111111
hotelname2 [15728]
wrong name!!!!
incomplete name 3, col: 15728 row: [15728]
col: 15729 similar rows:  [15729, 16363]
incomplete name 3, col: 15729 row: []
col: 15730 similar rows:  [15730, 16668]
incomplete name 3, col: 15730 row: []
col: 15731 similar rows:  [15731]
11111111111111111111
hotelname2 [15731]
incomplete name 3, col: 15731 row: [15731]
col: 15732 similar rows:  [15732]
11111111111111111111
incomplete name 3, col: 15732 row: []
col: 15733 similar rows:  [15733, 16605]
incomplete name 3, col: 15733 row: []
col: 15734 similar rows:  [15734]
11111111111111111111
incomplete name 3, col: 15734 row: []
col: 15735 similar rows:  [15735]
11111111111111111111
hotelname2 [15735]
incomplete name 3, col: 15735 row: [15735]
col: 15737 similar rows:  [15737]
11111111111111111111
hotelname2 [15737]
incomplete name 3, col: 15737 row: [15737]
col: 15738 similar rows:  [15738]
11111111111111111111
incomplete name 3, col: 15738 row: []
col: 15741 similar rows:  [15741]
11111111111111111111
hotelname2 [15741]
wrong name!!!!
incomplete name 3, col: 15741 row: [15741]
col: 15742 similar rows:  [15742, 16942]
incomplete name 3, col: 15742 row: []
col: 15743 similar rows:  [15743]
11111111111111111111
incomplete name 3, col: 15743 row: []
col: 15744 similar rows:  [15744]
11111111111111111111
incomplete name 3, col: 15744 row: []
col: 15745 similar rows:  [15745]
11111111111111111111
incomplete name 3, col: 15745 row: []
col: 15746 similar rows:  [15746]
11111111111111111111
incomplete name 3, col: 15746 row: []
col: 15748 similar rows:  [15748]
11111111111111111111
incomplete name 3, col: 15748 row: []
col: 15751 similar rows:  [15751, 15808, 15900, 16318, 17097]
hotelname2 [16318]
incomplete name 3, col: 15751 row: [16318]
col: 15752 similar rows:  [15752, 15796]
incomplete name 3, col: 15752 row: []
col: 15753 similar rows:  [15753, 16184]
incomplete name 3, col: 15753 row: []
col: 15754 similar rows:  [15754]
11111111111111111111
incomplete name 3, col: 15754 row: []
col: 15755 similar rows:  [15755, 17093]
incomplete name 3, col: 15755 row: []
col: 15756 similar rows:  [15756]
11111111111111111111
incomplete name 3, col: 15756 row: []
col: 15758 similar rows:  [15758]
11111111111111111111
incomplete name 3, col: 15758 row: []
col: 15759 similar rows:  [15759, 15784, 16780]
incomplete name 3, col: 15759 row: []
col: 15760 similar rows:  [15760, 15808, 15900, 17097]
incomplete name 3, col: 15760 row: []
col: 15761 similar rows:  [15761]
11111111111111111111
incomplete name 3, col: 15761 row: []
col: 15763 similar rows:  [15763]
11111111111111111111
incomplete name 3, col: 15763 row: []
col: 15764 similar rows:  [15764]
11111111111111111111
incomplete name 3, col: 15764 row: []
col: 15765 similar rows:  [15765, 16162, 16325, 17125]
incomplete name 3, col: 15765 row: []
col: 15766 similar rows:  [15766]
11111111111111111111
incomplete name 3, col: 15766 row: []
col: 15767 similar rows:  [15767]
11111111111111111111
incomplete name 3, col: 15767 row: []
col: 15768 similar rows:  [15768, 16365, 16777]
incomplete name 3, col: 15768 row: []
col: 15769 similar rows:  [15769]
11111111111111111111
hotelname2 [15769]
wrong name!!!!
incomplete name 3, col: 15769 row: [15769]
col: 15770 similar rows:  [15770, 16258, 16443, 17149]
incomplete name 3, col: 15770 row: []
col: 15771 similar rows:  [15771]
11111111111111111111
incomplete name 3, col: 15771 row: []
col: 15772 similar rows:  [15772, 16268]
incomplete name 3, col: 15772 row: []
col: 15773 similar rows:  [15773]
11111111111111111111
incomplete name 3, col: 15773 row: []
col: 15775 similar rows:  [15775]
11111111111111111111
incomplete name 3, col: 15775 row: []
col: 15776 similar rows:  [15776]
11111111111111111111
incomplete name 3, col: 15776 row: []
col: 15777 similar rows:  [15777]
11111111111111111111
incomplete name 3, col: 15777 row: []
col: 15778 similar rows:  [15778]
11111111111111111111
incomplete name 3, col: 15778 row: []
col: 15780 similar rows:  [15780]
11111111111111111111
incomplete name 3, col: 15780 row: []
col: 15781 similar rows:  [15781]
11111111111111111111
hotelname2 [15781]
incomplete name 3, col: 15781 row: [15781]
col: 15782 similar rows:  [15782, 16216]
incomplete name 3, col: 15782 row: []
col: 15783 similar rows:  [15783]
11111111111111111111
incomplete name 3, col: 15783 row: []
col: 15787 similar rows:  [15787]
11111111111111111111
incomplete name 3, col: 15787 row: []
col: 15790 similar rows:  [15790]
11111111111111111111
hotelname2 [15790]
incomplete name 3, col: 15790 row: [15790]
col: 15791 similar rows:  [15791]
11111111111111111111
incomplete name 3, col: 15791 row: []
col: 15792 similar rows:  [15792, 16581]
incomplete name 3, col: 15792 row: []
col: 15793 similar rows:  [15793, 15838, 16156, 16919]
incomplete name 3, col: 15793 row: []

col: 15794 similar rows:  [15794]
11111111111111111111
incomplete name 3, col: 15794 row: []
col: 15795 similar rows:  [15795]
11111111111111111111
incomplete name 3, col: 15795 row: []
col: 15797 similar rows:  [15797, 16123]
incomplete name 3, col: 15797 row: []
col: 15800 similar rows:  [15800]
11111111111111111111
incomplete name 3, col: 15800 row: []
col: 15802 similar rows:  [15802]
11111111111111111111
incomplete name 3, col: 15802 row: []
col: 15803 similar rows:  [15803]
11111111111111111111
incomplete name 3, col: 15803 row: []
col: 15804 similar rows:  [15804]
11111111111111111111
incomplete name 3, col: 15804 row: []
col: 15805 similar rows:  [15805]
11111111111111111111
hotelname2 [15805]
incomplete name 3, col: 15805 row: []
col: 15806 similar rows:  [15806]
11111111111111111111
incomplete name 3, col: 15806 row: []
col: 15809 similar rows:  [15809, 16092, 16106, 16317, 16528]
incomplete name 3, col: 15809 row: []
col: 15810 similar rows:  [15810]
11111111111111111111
incomplete name 3, col: 15810 row: []
col: 15811 similar rows:  [15811, 16869]
incomplete name 3, col: 15811 row: []
col: 15812 similar rows:  [15812, 15819]
incomplete name 3, col: 15812 row: []
col: 15814 similar rows:  [15814, 16647]
incomplete name 3, col: 15814 row: []
col: 15815 similar rows:  [15815]
11111111111111111111
incomplete name 3, col: 15815 row: []
col: 15817 similar rows:  [15817, 15818]
incomplete name 3, col: 15817 row: []
col: 15820 similar rows:  [15820]
11111111111111111111
incomplete name 3, col: 15820 row: []
col: 15821 similar rows:  [15821]
11111111111111111111
incomplete name 3, col: 15821 row: []
col: 15823 similar rows:  [15823]
11111111111111111111
incomplete name 3, col: 15823 row: []
col: 15824 similar rows:  [15824]
11111111111111111111
incomplete name 3, col: 15824 row: []
col: 15825 similar rows:  [15825]
11111111111111111111
incomplete name 3, col: 15825 row: []
col: 15826 similar rows:  [15826]
11111111111111111111
incomplete name 3, col: 15826 row: []
col: 15827 similar rows:  [15827]
11111111111111111111
incomplete name 3, col: 15827 row: []
col: 15828 similar rows:  [15828]
11111111111111111111
incomplete name 3, col: 15828 row: []
col: 15829 similar rows:  [15829]
11111111111111111111
hotelname2 [15829]
incomplete name 3, col: 15829 row: [15829]
col: 15830 similar rows:  [15830]
11111111111111111111
incomplete name 3, col: 15830 row: []
col: 15831 similar rows:  [15831]
11111111111111111111
incomplete name 3, col: 15831 row: []
col: 15834 similar rows:  [15834]
11111111111111111111
incomplete name 3, col: 15834 row: []
col: 15836 similar rows:  [15836]
11111111111111111111
incomplete name 3, col: 15836 row: []
col: 15837 similar rows:  [15837, 16725]
incomplete name 3, col: 15837 row: []
col: 15839 similar rows:  [15839]
11111111111111111111
incomplete name 3, col: 15839 row: []
col: 15842 similar rows:  [15842, 16109, 16249, 16308, 17200]
incomplete name 3, col: 15842 row: []
col: 15843 similar rows:  [15843]
11111111111111111111
hotelname2 [15843]
incomplete name 3, col: 15843 row: []
col: 15844 similar rows:  [15844]
11111111111111111111
incomplete name 3, col: 15844 row: []
col: 15848 similar rows:  [15848]
11111111111111111111
incomplete name 3, col: 15848 row: []
col: 15849 similar rows:  [15849, 15878, 16346, 17070]
incomplete name 3, col: 15849 row: []
col: 15851 similar rows:  [15851]
11111111111111111111
incomplete name 3, col: 15851 row: []
col: 15852 similar rows:  [15852]
11111111111111111111
incomplete name 3, col: 15852 row: []
col: 15853 similar rows:  [15853, 15931, 16028, 16044, 17164]
incomplete name 3, col: 15853 row: []
col: 15855 similar rows:  [15855, 16483]
incomplete name 3, col: 15855 row: []
col: 15858 similar rows:  [15858]
11111111111111111111
hotelname2 [15858]
wrong name!!!!
incomplete name 3, col: 15858 row: [15858]
col: 15860 similar rows:  [15860]
11111111111111111111
incomplete name 3, col: 15860 row: []
col: 15861 similar rows:  [15861]
11111111111111111111
incomplete name 3, col: 15861 row: []
col: 15862 similar rows:  [15862]
11111111111111111111
hotelname2 [15862]
incomplete name 3, col: 15862 row: [15862]
col: 15865 similar rows:  [15865, 16041]
incomplete name 3, col: 15865 row: []
col: 15870 similar rows:  [15870, 15887, 16839]
incomplete name 3, col: 15870 row: []
col: 15873 similar rows:  [15873]
11111111111111111111
hotelname2 [15873]
incomplete name 3, col: 15873 row: [15873]
col: 15875 similar rows:  [15875]
11111111111111111111
incomplete name 3, col: 15875 row: []
col: 15876 similar rows:  [15876]
11111111111111111111
incomplete name 3, col: 15876 row: []
col: 15880 similar rows:  [15880]
11111111111111111111
incomplete name 3, col: 15880 row: []
col: 15881 similar rows:  [15881, 16877]
incomplete name 3, col: 15881 row: []
col: 15883 similar rows:  [15883, 15936]
incomplete name 3, col: 15883 row: []
col: 15884 similar rows:  [15884, 16004]
incomplete name 3, col: 15884 row: []
col: 15885 similar rows:  [15885, 16373, 16374, 16375, 16377]
incomplete name 3, col: 15885 row: []
col: 15889 similar rows:  [15889, 16860, 16929]
incomplete name 3, col: 15889 row: []
col: 15890 similar rows:  [15890]
11111111111111111111
incomplete name 3, col: 15890 row: []
col: 15891 similar rows:  [15891]
11111111111111111111
incomplete name 3, col: 15891 row: []
col: 15892 similar rows:  [15892]
11111111111111111111
incomplete name 3, col: 15892 row: []
col: 15893 similar rows:  [15893]
11111111111111111111
incomplete name 3, col: 15893 row: []
col: 15895 similar rows:  [15895, 16316, 16922, 16971]
incomplete name 3, col: 15895 row: []
col: 15897 similar rows:  [15897]
11111111111111111111
incomplete name 3, col: 15897 row: []
col: 15898 similar rows:  [15898]
11111111111111111111
incomplete name 3, col: 15898 row: []
col: 15899 similar rows:  [15899]
11111111111111111111
incomplete name 3, col: 15899 row: []
col: 15901 similar rows:  [15901, 16661]
incomplete name 3, col: 15901 row: []
col: 15904 similar rows:  [15904, 16588]
incomplete name 3, col: 15904 row: []
col: 15906 similar rows:  [15906]
11111111111111111111
incomplete name 3, col: 15906 row: []
col: 15908 similar rows:  [15908]
11111111111111111111
incomplete name 3, col: 15908 row: []
col: 15910 similar rows:  [15910]
11111111111111111111
incomplete name 3, col: 15910 row: []
col: 15911 similar rows:  [15911]
11111111111111111111
incomplete name 3, col: 15911 row: []
col: 15912 similar rows:  [15912]
11111111111111111111
hotelname2 [15912]
incomplete name 3, col: 15912 row: [15912]
col: 15913 similar rows:  [15913]
11111111111111111111
incomplete name 3, col: 15913 row: []
col: 15914 similar rows:  [15914]
11111111111111111111
incomplete name 3, col: 15914 row: []
col: 15915 similar rows:  [15915]
11111111111111111111
incomplete name 3, col: 15915 row: []
col: 15916 similar rows:  [15916]
11111111111111111111
incomplete name 3, col: 15916 row: []
col: 15918 similar rows:  [15918]
11111111111111111111
incomplete name 3, col: 15918 row: []
col: 15919 similar rows:  [15919]
11111111111111111111
incomplete name 3, col: 15919 row: []
col: 15920 similar rows:  [15920, 16165, 16474, 17002]
incomplete name 3, col: 15920 row: []
col: 15921 similar rows:  [15921, 16784]
incomplete name 3, col: 15921 row: []
col: 15922 similar rows:  [15922, 16710]
incomplete name 3, col: 15922 row: []
col: 15923 similar rows:  [15923]
11111111111111111111
incomplete name 3, col: 15923 row: []
col: 15924 similar rows:  [15924]
11111111111111111111
incomplete name 3, col: 15924 row: []
col: 15925 similar rows:  [15925]
11111111111111111111
hotelname2 [15925]
incomplete name 3, col: 15925 row: []
col: 15926 similar rows:  [15926]
11111111111111111111
incomplete name 3, col: 15926 row: []
col: 15928 similar rows:  [15928, 15970]
incomplete name 3, col: 15928 row: []
col: 15930 similar rows:  [15930, 16743, 16757, 16890, 16926, 17026]
incomplete name 3, col: 15930 row: []
col: 15937 similar rows:  [15937]
11111111111111111111
hotelname2 [15937]
wrong name!!!!
incomplete name 3, col: 15937 row: [15937]
col: 15939 similar rows:  [15939]
11111111111111111111
incomplete name 3, col: 15939 row: []
col: 15940 similar rows:  [15940]
11111111111111111111
incomplete name 3, col: 15940 row: []
col: 15941 similar rows:  [15941]
11111111111111111111
incomplete name 3, col: 15941 row: []
col: 15942 similar rows:  [15942]
11111111111111111111
incomplete name 3, col: 15942 row: []
col: 15943 similar rows:  [15943]
11111111111111111111
incomplete name 3, col: 15943 row: []

col: 15944 similar rows:  [15944]
11111111111111111111
hotelname2 [15944]
incomplete name 3, col: 15944 row: [15944]
col: 15946 similar rows:  [15946, 16125, 16759, 16885, 16899]
incomplete name 3, col: 15946 row: []
col: 15947 similar rows:  [15947]
11111111111111111111
incomplete name 3, col: 15947 row: []
col: 15948 similar rows:  [15948, 16904]
incomplete name 3, col: 15948 row: []
col: 15951 similar rows:  [15951]
11111111111111111111
incomplete name 3, col: 15951 row: []
col: 15954 similar rows:  [15954]
11111111111111111111
incomplete name 3, col: 15954 row: []
col: 15955 similar rows:  [15955, 16254, 16963, 17161, 17163]
incomplete name 3, col: 15955 row: []
col: 15956 similar rows:  [15956]
11111111111111111111
incomplete name 3, col: 15956 row: []
col: 15957 similar rows:  [15957]
11111111111111111111
incomplete name 3, col: 15957 row: []
col: 15958 similar rows:  [15958]
11111111111111111111
incomplete name 3, col: 15958 row: []
col: 15963 similar rows:  [15963]
11111111111111111111
incomplete name 3, col: 15963 row: []
col: 15964 similar rows:  [15964]
11111111111111111111
incomplete name 3, col: 15964 row: []
col: 15965 similar rows:  [15965]
11111111111111111111
incomplete name 3, col: 15965 row: []
col: 15966 similar rows:  [15966]
11111111111111111111
hotelname2 [15966]
incomplete name 3, col: 15966 row: [15966]
col: 15969 similar rows:  [15969]
11111111111111111111
incomplete name 3, col: 15969 row: []
col: 15971 similar rows:  [15971]
11111111111111111111
incomplete name 3, col: 15971 row: []
col: 15972 similar rows:  [15972]
11111111111111111111
hotelname2 [15972]
incomplete name 3, col: 15972 row: [15972]
col: 15974 similar rows:  [15974]
11111111111111111111
incomplete name 3, col: 15974 row: []
col: 15975 similar rows:  [15975]
11111111111111111111
incomplete name 3, col: 15975 row: []
col: 15976 similar rows:  [15976]
11111111111111111111
hotelname2 [15976]
incomplete name 3, col: 15976 row: [15976]
col: 15977 similar rows:  [15977]
11111111111111111111
incomplete name 3, col: 15977 row: []
col: 15978 similar rows:  [15978]
11111111111111111111
incomplete name 3, col: 15978 row: []
col: 15979 similar rows:  [15979]
11111111111111111111
incomplete name 3, col: 15979 row: []
col: 15980 similar rows:  [15980, 16200, 16238, 16578, 16828, 16990]
incomplete name 3, col: 15980 row: []
col: 15981 similar rows:  [15981]
11111111111111111111
incomplete name 3, col: 15981 row: []
col: 15984 similar rows:  [15984]
11111111111111111111
incomplete name 3, col: 15984 row: []
col: 15985 similar rows:  [15985]
11111111111111111111
incomplete name 3, col: 15985 row: []
col: 15986 similar rows:  [15986, 16026, 16259, 16371, 16484, 16972, 17228]
incomplete name 3, col: 15986 row: []
col: 15988 similar rows:  [15988]
11111111111111111111
incomplete name 3, col: 15988 row: []
col: 15989 similar rows:  [15989, 16379]
incomplete name 3, col: 15989 row: []
col: 15990 similar rows:  [15990]
11111111111111111111
incomplete name 3, col: 15990 row: []
col: 15994 similar rows:  [15994, 16135]
incomplete name 3, col: 15994 row: []
col: 15996 similar rows:  [15996, 16208]
incomplete name 3, col: 15996 row: []
col: 15998 similar rows:  [15998]
11111111111111111111
incomplete name 3, col: 15998 row: []
col: 16000 similar rows:  [16000]
11111111111111111111
incomplete name 3, col: 16000 row: []
col: 16001 similar rows:  [16001]
11111111111111111111
hotelname2 [16001]
incomplete name 3, col: 16001 row: [16001]
col: 16002 similar rows:  [16002]
11111111111111111111
hotelname2 [16002]
incomplete name 3, col: 16002 row: []
col: 16003 similar rows:  [16003, 16715]
incomplete name 3, col: 16003 row: []
col: 16005 similar rows:  [16005]
11111111111111111111
incomplete name 3, col: 16005 row: []
col: 16007 similar rows:  [16007]
11111111111111111111
hotelname2 [16007]
incomplete name 3, col: 16007 row: [16007]
col: 16008 similar rows:  [16008]
11111111111111111111
incomplete name 3, col: 16008 row: []
col: 16009 similar rows:  [16009]
11111111111111111111
incomplete name 3, col: 16009 row: []
col: 16012 similar rows:  [16012]
11111111111111111111
incomplete name 3, col: 16012 row: []
col: 16013 similar rows:  [16013]
11111111111111111111
incomplete name 3, col: 16013 row: []
col: 16015 similar rows:  [16015]
11111111111111111111
incomplete name 3, col: 16015 row: []
col: 16016 similar rows:  [16016, 16407]
incomplete name 3, col: 16016 row: []
col: 16017 similar rows:  [16017, 16402, 16513]
incomplete name 3, col: 16017 row: []
col: 16019 similar rows:  [16019]
11111111111111111111
incomplete name 3, col: 16019 row: []
col: 16021 similar rows:  [16021]
11111111111111111111
incomplete name 3, col: 16021 row: []
col: 16022 similar rows:  [16022, 17060]
incomplete name 3, col: 16022 row: []
col: 16023 similar rows:  [16023]
11111111111111111111
incomplete name 3, col: 16023 row: []
col: 16024 similar rows:  [16024]
11111111111111111111
incomplete name 3, col: 16024 row: []
col: 16025 similar rows:  [16025]
11111111111111111111
incomplete name 3, col: 16025 row: []
col: 16027 similar rows:  [16027]
11111111111111111111
incomplete name 3, col: 16027 row: []
col: 16029 similar rows:  [16029, 16500]
incomplete name 3, col: 16029 row: []
col: 16032 similar rows:  [16032, 16067, 16510, 17085, 17113]
incomplete name 3, col: 16032 row: []
col: 16033 similar rows:  [16033]
11111111111111111111
incomplete name 3, col: 16033 row: []
col: 16034 similar rows:  [16034]
11111111111111111111
incomplete name 3, col: 16034 row: []
col: 16035 similar rows:  [16035]
11111111111111111111
hotelname2 [16035]
wrong name!!!!
incomplete name 3, col: 16035 row: [16035]
col: 16037 similar rows:  [16037]
11111111111111111111
incomplete name 3, col: 16037 row: []
col: 16038 similar rows:  [16038]
11111111111111111111
hotelname2 [16038]
incomplete name 3, col: 16038 row: [16038]
col: 16039 similar rows:  [16039, 16054]
incomplete name 3, col: 16039 row: []
col: 16040 similar rows:  [16040, 17221]
incomplete name 3, col: 16040 row: []
col: 16045 similar rows:  [16045, 16270]
incomplete name 3, col: 16045 row: []
col: 16046 similar rows:  [16046]
11111111111111111111
incomplete name 3, col: 16046 row: []
col: 16048 similar rows:  [16048]
11111111111111111111
incomplete name 3, col: 16048 row: []
col: 16049 similar rows:  [16049]
11111111111111111111
incomplete name 3, col: 16049 row: []
col: 16050 similar rows:  [16050]
11111111111111111111
incomplete name 3, col: 16050 row: []
col: 16051 similar rows:  [16051]
11111111111111111111
incomplete name 3, col: 16051 row: []
col: 16053 similar rows:  [16053, 16921]
incomplete name 3, col: 16053 row: []
col: 16055 similar rows:  [16055, 16445, 16922]
incomplete name 3, col: 16055 row: []
col: 16057 similar rows:  [16057, 16210, 16464, 16512]
incomplete name 3, col: 16057 row: []
col: 16058 similar rows:  [16058, 16338, 16545, 16663, 16887, 17130]
incomplete name 3, col: 16058 row: []
col: 16062 similar rows:  [16062]
11111111111111111111
incomplete name 3, col: 16062 row: []
col: 16064 similar rows:  [16064]
11111111111111111111
incomplete name 3, col: 16064 row: []
col: 16069 similar rows:  [16069]
11111111111111111111
incomplete name 3, col: 16069 row: []
col: 16071 similar rows:  [16071]
11111111111111111111
incomplete name 3, col: 16071 row: []
col: 16072 similar rows:  [16072]
11111111111111111111
hotelname2 [16072]
incomplete name 3, col: 16072 row: [16072]
col: 16075 similar rows:  [16075]
11111111111111111111
incomplete name 3, col: 16075 row: []
col: 16077 similar rows:  [16077]
11111111111111111111
incomplete name 3, col: 16077 row: []
col: 16078 similar rows:  [16078]
11111111111111111111
incomplete name 3, col: 16078 row: []
col: 16079 similar rows:  [16079, 16080]
incomplete name 3, col: 16079 row: []
col: 16084 similar rows:  [16084, 16128, 16981]
incomplete name 3, col: 16084 row: []
col: 16089 similar rows:  [16089]
11111111111111111111
incomplete name 3, col: 16089 row: []
col: 16093 similar rows:  [16093]
11111111111111111111
hotelname2 [16093]
incomplete name 3, col: 16093 row: [16093]
col: 16094 similar rows:  [16094]
11111111111111111111
incomplete name 3, col: 16094 row: []
col: 16095 similar rows:  [16095]
11111111111111111111
hotelname2 [16095]
incomplete name 3, col: 16095 row: [16095]
col: 16096 similar rows:  [16096, 17080]
incomplete name 3, col: 16096 row: []
col: 16097 similar rows:  [16097]
11111111111111111111
incomplete name 3, col: 16097 row: []
col: 16100 similar rows:  [16100, 16164, 16796]
incomplete name 3, col: 16100 row: []
col: 16102 similar rows:  [16102]
11111111111111111111
hotelname2 [16102]
incomplete name 3, col: 16102 row: []

col: 16103 similar rows:  [16103]
11111111111111111111
incomplete name 3, col: 16103 row: []
col: 16105 similar rows:  [16105, 16624, 16696]
incomplete name 3, col: 16105 row: []
col: 16107 similar rows:  [16107]
11111111111111111111
hotelname2 [16107]
wrong name!!!!
incomplete name 3, col: 16107 row: [16107]
col: 16108 similar rows:  [16108, 16339]
incomplete name 3, col: 16108 row: []
col: 16110 similar rows:  [16110]
11111111111111111111
incomplete name 3, col: 16110 row: []
col: 16111 similar rows:  [16111]
11111111111111111111
incomplete name 3, col: 16111 row: []
col: 16112 similar rows:  [16112, 16567, 17219, 17226]
incomplete name 3, col: 16112 row: []
col: 16114 similar rows:  [16114]
11111111111111111111
incomplete name 3, col: 16114 row: []
col: 16116 similar rows:  [16116, 16117, 17211]
incomplete name 3, col: 16116 row: []
col: 16121 similar rows:  [16121, 16772]
incomplete name 3, col: 16121 row: []
col: 16122 similar rows:  [16122]
11111111111111111111
incomplete name 3, col: 16122 row: []
col: 16124 similar rows:  [16124]
11111111111111111111
incomplete name 3, col: 16124 row: []
col: 16126 similar rows:  [16126]
11111111111111111111
incomplete name 3, col: 16126 row: []
col: 16127 similar rows:  [16127, 16324]
incomplete name 3, col: 16127 row: []
col: 16130 similar rows:  [16130, 17104]
incomplete name 3, col: 16130 row: []
col: 16132 similar rows:  [16132]
11111111111111111111
incomplete name 3, col: 16132 row: []
col: 16133 similar rows:  [16133]
11111111111111111111
incomplete name 3, col: 16133 row: []
col: 16134 similar rows:  [16134]
11111111111111111111
incomplete name 3, col: 16134 row: []
col: 16136 similar rows:  [16136]
11111111111111111111
incomplete name 3, col: 16136 row: []
col: 16137 similar rows:  [16137, 16261]
incomplete name 3, col: 16137 row: []
col: 16140 similar rows:  [16140]
11111111111111111111
hotelname2 [16140]
incomplete name 3, col: 16140 row: [16140]
col: 16141 similar rows:  [16141]
11111111111111111111
incomplete name 3, col: 16141 row: []
col: 16142 similar rows:  [16142]
11111111111111111111
incomplete name 3, col: 16142 row: []
col: 16143 similar rows:  [16143, 16965]
incomplete name 3, col: 16143 row: []
col: 16144 similar rows:  [16144]
11111111111111111111
incomplete name 3, col: 16144 row: []
col: 16145 similar rows:  [16145]
11111111111111111111
incomplete name 3, col: 16145 row: []
col: 16146 similar rows:  [16146]
11111111111111111111
incomplete name 3, col: 16146 row: []
col: 16147 similar rows:  [16147]
11111111111111111111
incomplete name 3, col: 16147 row: []
col: 16148 similar rows:  [16148, 16623, 17063]
incomplete name 3, col: 16148 row: []
col: 16149 similar rows:  [16149]
11111111111111111111
incomplete name 3, col: 16149 row: []
col: 16150 similar rows:  [16150, 16839]
incomplete name 3, col: 16150 row: []
col: 16152 similar rows:  [16152, 16802]
incomplete name 3, col: 16152 row: []
col: 16155 similar rows:  [16155]
11111111111111111111
incomplete name 3, col: 16155 row: []
col: 16157 similar rows:  [16157, 16160]
incomplete name 3, col: 16157 row: []
col: 16158 similar rows:  [16158]
11111111111111111111
incomplete name 3, col: 16158 row: []
col: 16159 similar rows:  [16159]
11111111111111111111
hotelname2 [16159]
incomplete name 3, col: 16159 row: [16159]
col: 16161 similar rows:  [16161, 16229, 17009]
incomplete name 3, col: 16161 row: []
col: 16167 similar rows:  [16167]
11111111111111111111
incomplete name 3, col: 16167 row: []
col: 16170 similar rows:  [16170]
11111111111111111111
incomplete name 3, col: 16170 row: []
col: 16171 similar rows:  [16171]
11111111111111111111
incomplete name 3, col: 16171 row: []
col: 16172 similar rows:  [16172]
11111111111111111111
hotelname2 [16172]
incomplete name 3, col: 16172 row: []
col: 16173 similar rows:  [16173, 17104]
incomplete name 3, col: 16173 row: []
col: 16175 similar rows:  [16175]
11111111111111111111
incomplete name 3, col: 16175 row: []
col: 16177 similar rows:  [16177]
11111111111111111111
incomplete name 3, col: 16177 row: []
col: 16178 similar rows:  [16178]
11111111111111111111
incomplete name 3, col: 16178 row: []
col: 16179 similar rows:  [16179]
11111111111111111111
incomplete name 3, col: 16179 row: []
col: 16180 similar rows:  [16180]
11111111111111111111
incomplete name 3, col: 16180 row: []
col: 16185 similar rows:  [16185]
11111111111111111111
incomplete name 3, col: 16185 row: []
col: 16186 similar rows:  [16186]
11111111111111111111
hotelname2 [16186]
incomplete name 3, col: 16186 row: [16186]
col: 16187 similar rows:  [16187]
11111111111111111111
incomplete name 3, col: 16187 row: []
col: 16188 similar rows:  [16188]
11111111111111111111
hotelname2 [16188]
wrong name!!!!
incomplete name 3, col: 16188 row: [16188]
col: 16189 similar rows:  [16189]
11111111111111111111
incomplete name 3, col: 16189 row: []
col: 16190 similar rows:  [16190]
11111111111111111111
incomplete name 3, col: 16190 row: []
col: 16191 similar rows:  [16191]
11111111111111111111
incomplete name 3, col: 16191 row: []
col: 16193 similar rows:  [16193]
11111111111111111111
incomplete name 3, col: 16193 row: []
col: 16194 similar rows:  [16194]
11111111111111111111
incomplete name 3, col: 16194 row: []
col: 16195 similar rows:  [16195, 16292, 16519]
incomplete name 3, col: 16195 row: []
col: 16196 similar rows:  [16196, 16487]
incomplete name 3, col: 16196 row: []
col: 16199 similar rows:  [16199]
11111111111111111111
incomplete name 3, col: 16199 row: []
col: 16203 similar rows:  [16203]
11111111111111111111
incomplete name 3, col: 16203 row: []
col: 16205 similar rows:  [16205]
11111111111111111111
incomplete name 3, col: 16205 row: []
col: 16206 similar rows:  [16206]
11111111111111111111
incomplete name 3, col: 16206 row: []
col: 16209 similar rows:  [16209]
11111111111111111111
incomplete name 3, col: 16209 row: []
col: 16212 similar rows:  [16212]
11111111111111111111
incomplete name 3, col: 16212 row: []
col: 16213 similar rows:  [16213]
11111111111111111111
incomplete name 3, col: 16213 row: []
col: 16214 similar rows:  [16214]
11111111111111111111
incomplete name 3, col: 16214 row: []
col: 16217 similar rows:  [16217]
11111111111111111111
incomplete name 3, col: 16217 row: []
col: 16219 similar rows:  [16219]
11111111111111111111
incomplete name 3, col: 16219 row: []
col: 16220 similar rows:  [16220]
11111111111111111111
hotelname2 [16220]
incomplete name 3, col: 16220 row: []
col: 16221 similar rows:  [16221]
11111111111111111111
incomplete name 3, col: 16221 row: []
col: 16222 similar rows:  [16222]
11111111111111111111
incomplete name 3, col: 16222 row: []
col: 16223 similar rows:  [16223]
11111111111111111111
incomplete name 3, col: 16223 row: []
col: 16225 similar rows:  [16225]
11111111111111111111
incomplete name 3, col: 16225 row: []
col: 16227 similar rows:  [16227, 16807]
incomplete name 3, col: 16227 row: []
col: 16230 similar rows:  [16230]
11111111111111111111
incomplete name 3, col: 16230 row: []
col: 16231 similar rows:  [16231]
11111111111111111111
hotelname2 [16231]
incomplete name 3, col: 16231 row: []
col: 16233 similar rows:  [16233]
11111111111111111111
incomplete name 3, col: 16233 row: []
col: 16235 similar rows:  [16235]
11111111111111111111
incomplete name 3, col: 16235 row: []
col: 16236 similar rows:  [16236]
11111111111111111111
hotelname2 [16236]
incomplete name 3, col: 16236 row: [16236]
col: 16239 similar rows:  [16239]
11111111111111111111
incomplete name 3, col: 16239 row: []
col: 16240 similar rows:  [16240, 16702, 16811]
incomplete name 3, col: 16240 row: []
col: 16241 similar rows:  [16241]
11111111111111111111
incomplete name 3, col: 16241 row: []
col: 16242 similar rows:  [16242]
11111111111111111111
incomplete name 3, col: 16242 row: []
col: 16244 similar rows:  [16244]
11111111111111111111
incomplete name 3, col: 16244 row: []
col: 16247 similar rows:  [16247]
11111111111111111111
incomplete name 3, col: 16247 row: []
col: 16248 similar rows:  [16248]
11111111111111111111
incomplete name 3, col: 16248 row: []
col: 16250 similar rows:  [16250]
11111111111111111111
hotelname2 [16250]
incomplete name 3, col: 16250 row: [16250]
col: 16251 similar rows:  [16251]
11111111111111111111
incomplete name 3, col: 16251 row: []
col: 16253 similar rows:  [16253]
11111111111111111111
incomplete name 3, col: 16253 row: []
col: 16260 similar rows:  [16260]
11111111111111111111
incomplete name 3, col: 16260 row: []
col: 16262 similar rows:  [16262]
11111111111111111111
incomplete name 3, col: 16262 row: []
col: 16264 similar rows:  [16264, 16834, 17093]
incomplete name 3, col: 16264 row: []

col: 16265 similar rows:  [16265]
11111111111111111111
incomplete name 3, col: 16265 row: []
col: 16266 similar rows:  [16266]
11111111111111111111
hotelname2 [16266]
incomplete name 3, col: 16266 row: []
col: 16267 similar rows:  [16267]
11111111111111111111
incomplete name 3, col: 16267 row: []
col: 16269 similar rows:  [16269]
11111111111111111111
hotelname2 [16269]
incomplete name 3, col: 16269 row: [16269]
col: 16271 similar rows:  [16271]
11111111111111111111
incomplete name 3, col: 16271 row: []
col: 16273 similar rows:  [16273]
11111111111111111111
incomplete name 3, col: 16273 row: []
col: 16278 similar rows:  [16278]
11111111111111111111
hotelname2 [16278]
incomplete name 3, col: 16278 row: []
col: 16279 similar rows:  [16279]
11111111111111111111
incomplete name 3, col: 16279 row: []
col: 16280 similar rows:  [16280]
11111111111111111111
hotelname2 [16280]
incomplete name 3, col: 16280 row: [16280]
col: 16281 similar rows:  [16281, 16360]
incomplete name 3, col: 16281 row: []
col: 16282 similar rows:  [16282]
11111111111111111111
incomplete name 3, col: 16282 row: []
col: 16283 similar rows:  [16283]
11111111111111111111
incomplete name 3, col: 16283 row: []
col: 16284 similar rows:  [16284]
11111111111111111111
incomplete name 3, col: 16284 row: []
col: 16287 similar rows:  [16287]
11111111111111111111
incomplete name 3, col: 16287 row: []
col: 16291 similar rows:  [16291, 17088, 17121]
incomplete name 3, col: 16291 row: []
col: 16294 similar rows:  [16294]
11111111111111111111
hotelname2 [16294]
incomplete name 3, col: 16294 row: []
col: 16295 similar rows:  [16295]
11111111111111111111
incomplete name 3, col: 16295 row: []
col: 16297 similar rows:  [16297]
11111111111111111111
incomplete name 3, col: 16297 row: []
col: 16298 similar rows:  [16298]
11111111111111111111
hotelname2 [16298]
incomplete name 3, col: 16298 row: [16298]
col: 16299 similar rows:  [16299]
11111111111111111111
incomplete name 3, col: 16299 row: []
col: 16302 similar rows:  [16302]
11111111111111111111
hotelname2 [16302]
incomplete name 3, col: 16302 row: []
col: 16303 similar rows:  [16303]
11111111111111111111
incomplete name 3, col: 16303 row: []
col: 16304 similar rows:  [16304]
11111111111111111111
incomplete name 3, col: 16304 row: []
col: 16305 similar rows:  [16305]
11111111111111111111
incomplete name 3, col: 16305 row: []
col: 16306 similar rows:  [16306]
11111111111111111111
incomplete name 3, col: 16306 row: []
col: 16307 similar rows:  [16307]
11111111111111111111
incomplete name 3, col: 16307 row: []
col: 16309 similar rows:  [16309]
11111111111111111111
incomplete name 3, col: 16309 row: []
col: 16310 similar rows:  [16310]
11111111111111111111
hotelname2 [16310]
incomplete name 3, col: 16310 row: []
col: 16311 similar rows:  [16311]
11111111111111111111
incomplete name 3, col: 16311 row: []
col: 16312 similar rows:  [16312, 16879]
incomplete name 3, col: 16312 row: []
col: 16313 similar rows:  [16313, 16428, 16559, 16628]
incomplete name 3, col: 16313 row: []
col: 16315 similar rows:  [16315]
11111111111111111111
incomplete name 3, col: 16315 row: []
col: 16321 similar rows:  [16321]
11111111111111111111
hotelname2 [16321]
incomplete name 3, col: 16321 row: [16321]
col: 16322 similar rows:  [16322]
11111111111111111111
incomplete name 3, col: 16322 row: []
col: 16323 similar rows:  [16323, 16937, 17135]
incomplete name 3, col: 16323 row: []
col: 16326 similar rows:  [16326]
11111111111111111111
incomplete name 3, col: 16326 row: []
col: 16328 similar rows:  [16328]
11111111111111111111
incomplete name 3, col: 16328 row: []
col: 16329 similar rows:  [16329]
11111111111111111111
incomplete name 3, col: 16329 row: []
col: 16330 similar rows:  [16330]
11111111111111111111
incomplete name 3, col: 16330 row: []
col: 16331 similar rows:  [16331]
11111111111111111111
incomplete name 3, col: 16331 row: []
col: 16334 similar rows:  [16334]
11111111111111111111
incomplete name 3, col: 16334 row: []
col: 16335 similar rows:  [16335]
11111111111111111111
incomplete name 3, col: 16335 row: []
col: 16336 similar rows:  [16336]
11111111111111111111
incomplete name 3, col: 16336 row: []
col: 16337 similar rows:  [16337, 16446, 17200]
incomplete name 3, col: 16337 row: []
col: 16340 similar rows:  [16340]
11111111111111111111
incomplete name 3, col: 16340 row: []
col: 16341 similar rows:  [16341]
11111111111111111111
incomplete name 3, col: 16341 row: []
col: 16342 similar rows:  [16342]
11111111111111111111
incomplete name 3, col: 16342 row: []
col: 16343 similar rows:  [16343]
11111111111111111111
incomplete name 3, col: 16343 row: []
col: 16344 similar rows:  [16344, 16744]
incomplete name 3, col: 16344 row: []
col: 16345 similar rows:  [16345]
11111111111111111111
hotelname2 [16345]
wrong name!!!!
incomplete name 3, col: 16345 row: [16345]
col: 16347 similar rows:  [16347]
11111111111111111111
incomplete name 3, col: 16347 row: []
col: 16348 similar rows:  [16348]
11111111111111111111
incomplete name 3, col: 16348 row: []
col: 16349 similar rows:  [16349]
11111111111111111111
incomplete name 3, col: 16349 row: []
col: 16351 similar rows:  [16351]
11111111111111111111
incomplete name 3, col: 16351 row: []
col: 16352 similar rows:  [16352]
11111111111111111111
incomplete name 3, col: 16352 row: []
col: 16354 similar rows:  [16354]
11111111111111111111
hotelname2 [16354]
incomplete name 3, col: 16354 row: [16354]
col: 16355 similar rows:  [16355]
11111111111111111111
incomplete name 3, col: 16355 row: []
col: 16356 similar rows:  [16356]
11111111111111111111
incomplete name 3, col: 16356 row: []
col: 16357 similar rows:  [16357]
11111111111111111111
incomplete name 3, col: 16357 row: []
col: 16358 similar rows:  [16358, 17169]
incomplete name 3, col: 16358 row: []
col: 16359 similar rows:  [16359]
11111111111111111111
hotelname2 [16359]
wrong name!!!!
incomplete name 3, col: 16359 row: [16359]
col: 16366 similar rows:  [16366]
11111111111111111111
incomplete name 3, col: 16366 row: []
col: 16368 similar rows:  [16368, 16369]
incomplete name 3, col: 16368 row: []
col: 16370 similar rows:  [16370]
11111111111111111111
incomplete name 3, col: 16370 row: []
col: 16372 similar rows:  [16372]
11111111111111111111
incomplete name 3, col: 16372 row: []
col: 16376 similar rows:  [16376, 16423, 16544, 16546, 17141, 17151]
incomplete name 3, col: 16376 row: []
col: 16378 similar rows:  [16378]
11111111111111111111
hotelname2 [16378]
incomplete name 3, col: 16378 row: []
col: 16383 similar rows:  [16383]
11111111111111111111
incomplete name 3, col: 16383 row: []
col: 16384 similar rows:  [16384]
11111111111111111111
incomplete name 3, col: 16384 row: []
col: 16385 similar rows:  [16385]
11111111111111111111
incomplete name 3, col: 16385 row: []
col: 16386 similar rows:  [16386]
11111111111111111111
incomplete name 3, col: 16386 row: []
col: 16387 similar rows:  [16387]
11111111111111111111
incomplete name 3, col: 16387 row: []
col: 16388 similar rows:  [16388]
11111111111111111111
incomplete name 3, col: 16388 row: []
col: 16389 similar rows:  [16389]
11111111111111111111
incomplete name 3, col: 16389 row: []
col: 16391 similar rows:  [16391]
11111111111111111111
incomplete name 3, col: 16391 row: []
col: 16394 similar rows:  [16394]
11111111111111111111
incomplete name 3, col: 16394 row: []
col: 16395 similar rows:  [16395]
11111111111111111111
incomplete name 3, col: 16395 row: []
col: 16397 similar rows:  [16397]
11111111111111111111
incomplete name 3, col: 16397 row: []
col: 16398 similar rows:  [16398]
11111111111111111111
incomplete name 3, col: 16398 row: []
col: 16399 similar rows:  [16399]
11111111111111111111
hotelname2 [16399]
wrong name!!!!
incomplete name 3, col: 16399 row: [16399]
col: 16400 similar rows:  [16400]
11111111111111111111
incomplete name 3, col: 16400 row: []
col: 16403 similar rows:  [16403]
11111111111111111111
incomplete name 3, col: 16403 row: []
col: 16404 similar rows:  [16404]
11111111111111111111
incomplete name 3, col: 16404 row: []
col: 16405 similar rows:  [16405, 16889]
incomplete name 3, col: 16405 row: []
col: 16406 similar rows:  [16406]
11111111111111111111
incomplete name 3, col: 16406 row: []
col: 16412 similar rows:  [16412]
11111111111111111111
hotelname2 [16412]
wrong name!!!!
incomplete name 3, col: 16412 row: [16412]
col: 16413 similar rows:  [16413]
11111111111111111111
hotelname2 [16413]
incomplete name 3, col: 16413 row: [16413]
col: 16414 similar rows:  [16414]
11111111111111111111
incomplete name 3, col: 16414 row: []
col: 16418 similar rows:  [16418]
11111111111111111111
incomplete name 3, col: 16418 row: []
col: 16419 similar rows:  [16419]
11111111111111111111
incomplete name 3, col: 16419 row: []
col: 16420 similar rows:  [16420]
11111111111111111111
incomplete name 3, col: 16420 row: []

col: 16421 similar rows:  [16421, 16631, 17159]
incomplete name 3, col: 16421 row: []
col: 16426 similar rows:  [16426]
11111111111111111111
hotelname2 [16426]
incomplete name 3, col: 16426 row: [16426]
col: 16427 similar rows:  [16427, 16458]
incomplete name 3, col: 16427 row: []
col: 16429 similar rows:  [16429, 16519]
incomplete name 3, col: 16429 row: []
col: 16430 similar rows:  [16430]
11111111111111111111
incomplete name 3, col: 16430 row: []
col: 16431 similar rows:  [16431]
11111111111111111111
hotelname2 [16431]
incomplete name 3, col: 16431 row: [16431]
col: 16433 similar rows:  [16433, 16597]
incomplete name 3, col: 16433 row: []
col: 16434 similar rows:  [16434]
11111111111111111111
incomplete name 3, col: 16434 row: []
col: 16439 similar rows:  [16439]
11111111111111111111
incomplete name 3, col: 16439 row: []
col: 16441 similar rows:  [16441]
11111111111111111111
incomplete name 3, col: 16441 row: []
col: 16442 similar rows:  [16442]
11111111111111111111
incomplete name 3, col: 16442 row: []
col: 16444 similar rows:  [16444]
11111111111111111111
incomplete name 3, col: 16444 row: []
col: 16447 similar rows:  [16447]
11111111111111111111
incomplete name 3, col: 16447 row: []
col: 16448 similar rows:  [16448]
11111111111111111111
incomplete name 3, col: 16448 row: []
col: 16449 similar rows:  [16449]
11111111111111111111
incomplete name 3, col: 16449 row: []
col: 16452 similar rows:  [16452, 16540]
incomplete name 3, col: 16452 row: []
col: 16453 similar rows:  [16453]
11111111111111111111
incomplete name 3, col: 16453 row: []
col: 16454 similar rows:  [16454]
11111111111111111111
incomplete name 3, col: 16454 row: []
col: 16456 similar rows:  [16456]
11111111111111111111
incomplete name 3, col: 16456 row: []
col: 16457 similar rows:  [16457]
11111111111111111111
incomplete name 3, col: 16457 row: []
col: 16459 similar rows:  [16459]
11111111111111111111
incomplete name 3, col: 16459 row: []
col: 16460 similar rows:  [16460]
11111111111111111111
incomplete name 3, col: 16460 row: []
col: 16461 similar rows:  [16461]
11111111111111111111
incomplete name 3, col: 16461 row: []
col: 16462 similar rows:  [16462]
11111111111111111111
incomplete name 3, col: 16462 row: []
col: 16463 similar rows:  [16463, 16618]
incomplete name 3, col: 16463 row: []
col: 16467 similar rows:  [16467, 16812]
incomplete name 3, col: 16467 row: []
col: 16468 similar rows:  [16468, 16711, 16907]
incomplete name 3, col: 16468 row: []
col: 16469 similar rows:  [16469]
11111111111111111111
incomplete name 3, col: 16469 row: []
col: 16470 similar rows:  [16470]
11111111111111111111
hotelname2 [16470]
incomplete name 3, col: 16470 row: [16470]
col: 16473 similar rows:  [16473, 16689]
incomplete name 3, col: 16473 row: []
col: 16476 similar rows:  [16476]
11111111111111111111
hotelname2 [16476]
incomplete name 3, col: 16476 row: [16476]
col: 16477 similar rows:  [16477]
11111111111111111111
incomplete name 3, col: 16477 row: []
col: 16479 similar rows:  [16479]
11111111111111111111
incomplete name 3, col: 16479 row: []
col: 16481 similar rows:  [16481]
11111111111111111111
incomplete name 3, col: 16481 row: []
col: 16482 similar rows:  [16482]
11111111111111111111
incomplete name 3, col: 16482 row: []
col: 16485 similar rows:  [16485]
11111111111111111111
incomplete name 3, col: 16485 row: []
col: 16486 similar rows:  [16486]
11111111111111111111
incomplete name 3, col: 16486 row: []
col: 16491 similar rows:  [16491]
11111111111111111111
incomplete name 3, col: 16491 row: []
col: 16492 similar rows:  [16492]
11111111111111111111
incomplete name 3, col: 16492 row: []
col: 16493 similar rows:  [16493]
11111111111111111111
incomplete name 3, col: 16493 row: []
col: 16494 similar rows:  [16494]
11111111111111111111
incomplete name 3, col: 16494 row: []
col: 16495 similar rows:  [16495]
11111111111111111111
incomplete name 3, col: 16495 row: []
col: 16496 similar rows:  [16496, 16886]
incomplete name 3, col: 16496 row: []
col: 16497 similar rows:  [16497]
11111111111111111111
incomplete name 3, col: 16497 row: []
col: 16498 similar rows:  [16498]
11111111111111111111
incomplete name 3, col: 16498 row: []
col: 16499 similar rows:  [16499]
11111111111111111111
incomplete name 3, col: 16499 row: []
col: 16501 similar rows:  [16501]
11111111111111111111
incomplete name 3, col: 16501 row: []
col: 16503 similar rows:  [16503]
11111111111111111111
incomplete name 3, col: 16503 row: []
col: 16505 similar rows:  [16505]
11111111111111111111
hotelname2 [16505]
incomplete name 3, col: 16505 row: [16505]
col: 16506 similar rows:  [16506]
11111111111111111111
incomplete name 3, col: 16506 row: []
col: 16508 similar rows:  [16508]
11111111111111111111
hotelname2 [16508]
incomplete name 3, col: 16508 row: [16508]
col: 16511 similar rows:  [16511]
11111111111111111111
incomplete name 3, col: 16511 row: []
col: 16514 similar rows:  [16514, 16562]
incomplete name 3, col: 16514 row: []
col: 16515 similar rows:  [16515]
11111111111111111111
incomplete name 3, col: 16515 row: []
col: 16517 similar rows:  [16517]
11111111111111111111
incomplete name 3, col: 16517 row: []
col: 16520 similar rows:  [16520]
11111111111111111111
incomplete name 3, col: 16520 row: []
col: 16521 similar rows:  [16521]
11111111111111111111
incomplete name 3, col: 16521 row: []
col: 16522 similar rows:  [16522]
11111111111111111111
hotelname2 [16522]
incomplete name 3, col: 16522 row: [16522]
col: 16523 similar rows:  [16523, 16610, 16936, 17142]
incomplete name 3, col: 16523 row: []
col: 16525 similar rows:  [16525]
11111111111111111111
incomplete name 3, col: 16525 row: []
col: 16527 similar rows:  [16527]
11111111111111111111
incomplete name 3, col: 16527 row: []
col: 16529 similar rows:  [16529]
11111111111111111111
incomplete name 3, col: 16529 row: []
col: 16531 similar rows:  [16531]
11111111111111111111
incomplete name 3, col: 16531 row: []
col: 16533 similar rows:  [16533]
11111111111111111111
hotelname2 [16533]
incomplete name 3, col: 16533 row: [16533]
col: 16534 similar rows:  [16534]
11111111111111111111
incomplete name 3, col: 16534 row: []
col: 16535 similar rows:  [16535, 16621, 16731, 17010, 17184]
incomplete name 3, col: 16535 row: []
col: 16538 similar rows:  [16538, 17168]
incomplete name 3, col: 16538 row: []
col: 16539 similar rows:  [16539]
11111111111111111111
incomplete name 3, col: 16539 row: []
col: 16542 similar rows:  [16542]
11111111111111111111
incomplete name 3, col: 16542 row: []
col: 16547 similar rows:  [16547]
11111111111111111111
incomplete name 3, col: 16547 row: []
col: 16548 similar rows:  [16548]
11111111111111111111
incomplete name 3, col: 16548 row: []
col: 16549 similar rows:  [16549]
11111111111111111111
incomplete name 3, col: 16549 row: []
col: 16551 similar rows:  [16551]
11111111111111111111
incomplete name 3, col: 16551 row: []
col: 16552 similar rows:  [16552]
11111111111111111111
incomplete name 3, col: 16552 row: []
col: 16553 similar rows:  [16553]
11111111111111111111
incomplete name 3, col: 16553 row: []
col: 16554 similar rows:  [16554]
11111111111111111111
incomplete name 3, col: 16554 row: []
col: 16556 similar rows:  [16556, 17009]
incomplete name 3, col: 16556 row: []
col: 16558 similar rows:  [16558, 16831]
incomplete name 3, col: 16558 row: []
col: 16563 similar rows:  [16563, 17189]
incomplete name 3, col: 16563 row: []
col: 16564 similar rows:  [16564]
11111111111111111111
incomplete name 3, col: 16564 row: []
col: 16566 similar rows:  [16566, 16938, 17047]
incomplete name 3, col: 16566 row: []
col: 16568 similar rows:  [16568]
11111111111111111111
incomplete name 3, col: 16568 row: []
col: 16569 similar rows:  [16569]
11111111111111111111
incomplete name 3, col: 16569 row: []
col: 16571 similar rows:  [16571]
11111111111111111111
hotelname2 [16571]
wrong name!!!!
incomplete name 3, col: 16571 row: [16571]
col: 16572 similar rows:  [16572]
11111111111111111111
hotelname2 [16572]
incomplete name 3, col: 16572 row: [16572]
col: 16577 similar rows:  [16577]
11111111111111111111
incomplete name 3, col: 16577 row: []
col: 16579 similar rows:  [16579]
11111111111111111111
hotelname2 [16579]
incomplete name 3, col: 16579 row: []
col: 16583 similar rows:  [16583]
11111111111111111111
incomplete name 3, col: 16583 row: []
col: 16586 similar rows:  [16586]
11111111111111111111
incomplete name 3, col: 16586 row: []
col: 16587 similar rows:  [16587]
11111111111111111111
incomplete name 3, col: 16587 row: []
col: 16589 similar rows:  [16589]
11111111111111111111
incomplete name 3, col: 16589 row: []

col: 16590 similar rows:  [16590]
11111111111111111111
incomplete name 3, col: 16590 row: []
col: 16591 similar rows:  [16591]
11111111111111111111
incomplete name 3, col: 16591 row: []
col: 16593 similar rows:  [16593]
11111111111111111111
incomplete name 3, col: 16593 row: []
col: 16594 similar rows:  [16594]
11111111111111111111
incomplete name 3, col: 16594 row: []
col: 16595 similar rows:  [16595]
11111111111111111111
incomplete name 3, col: 16595 row: []
col: 16596 similar rows:  [16596]
11111111111111111111
hotelname2 [16596]
wrong name!!!!
incomplete name 3, col: 16596 row: [16596]
col: 16598 similar rows:  [16598]
11111111111111111111
incomplete name 3, col: 16598 row: []
col: 16599 similar rows:  [16599]
11111111111111111111
hotelname2 [16599]
incomplete name 3, col: 16599 row: [16599]
col: 16600 similar rows:  [16600]
11111111111111111111
incomplete name 3, col: 16600 row: []
col: 16603 similar rows:  [16603]
11111111111111111111
incomplete name 3, col: 16603 row: []
col: 16604 similar rows:  [16604]
11111111111111111111
incomplete name 3, col: 16604 row: []
col: 16608 similar rows:  [16608]
11111111111111111111
hotelname2 [16608]
incomplete name 3, col: 16608 row: [16608]
col: 16609 similar rows:  [16609]
11111111111111111111
incomplete name 3, col: 16609 row: []
col: 16611 similar rows:  [16611]
11111111111111111111
incomplete name 3, col: 16611 row: []
col: 16612 similar rows:  [16612]
11111111111111111111
incomplete name 3, col: 16612 row: []
col: 16613 similar rows:  [16613]
11111111111111111111
incomplete name 3, col: 16613 row: []
col: 16614 similar rows:  [16614, 17055]
incomplete name 3, col: 16614 row: []
col: 16615 similar rows:  [16615]
11111111111111111111
incomplete name 3, col: 16615 row: []
col: 16616 similar rows:  [16616]
11111111111111111111
incomplete name 3, col: 16616 row: []
col: 16617 similar rows:  [16617]
11111111111111111111
incomplete name 3, col: 16617 row: []
col: 16619 similar rows:  [16619]
11111111111111111111
incomplete name 3, col: 16619 row: []
col: 16620 similar rows:  [16620]
11111111111111111111
incomplete name 3, col: 16620 row: []
col: 16622 similar rows:  [16622]
11111111111111111111
incomplete name 3, col: 16622 row: []
col: 16626 similar rows:  [16626, 17079, 17090, 17109]
incomplete name 3, col: 16626 row: []
col: 16629 similar rows:  [16629]
11111111111111111111
incomplete name 3, col: 16629 row: []
col: 16630 similar rows:  [16630]
11111111111111111111
incomplete name 3, col: 16630 row: []
col: 16632 similar rows:  [16632]
11111111111111111111
incomplete name 3, col: 16632 row: []
col: 16633 similar rows:  [16633]
11111111111111111111
incomplete name 3, col: 16633 row: []
col: 16634 similar rows:  [16634]
11111111111111111111
incomplete name 3, col: 16634 row: []
col: 16636 similar rows:  [16636, 16850]
incomplete name 3, col: 16636 row: []
col: 16637 similar rows:  [16637, 16653, 16657, 17081, 17106]
incomplete name 3, col: 16637 row: []
col: 16638 similar rows:  [16638, 16724]
incomplete name 3, col: 16638 row: []
col: 16639 similar rows:  [16639, 16640, 16855]
incomplete name 3, col: 16639 row: []
col: 16641 similar rows:  [16641]
11111111111111111111
incomplete name 3, col: 16641 row: []
col: 16643 similar rows:  [16643]
11111111111111111111
incomplete name 3, col: 16643 row: []
col: 16644 similar rows:  [16644]
11111111111111111111
incomplete name 3, col: 16644 row: []
col: 16645 similar rows:  [16645]
11111111111111111111
incomplete name 3, col: 16645 row: []
col: 16648 similar rows:  [16648]
11111111111111111111
incomplete name 3, col: 16648 row: []
col: 16649 similar rows:  [16649]
11111111111111111111
incomplete name 3, col: 16649 row: []
col: 16650 similar rows:  [16650]
11111111111111111111
incomplete name 3, col: 16650 row: []
col: 16651 similar rows:  [16651]
11111111111111111111
hotelname2 [16651]
incomplete name 3, col: 16651 row: []
col: 16655 similar rows:  [16655]
11111111111111111111
incomplete name 3, col: 16655 row: []
col: 16659 similar rows:  [16659]
11111111111111111111
incomplete name 3, col: 16659 row: []
col: 16660 similar rows:  [16660, 17122]
incomplete name 3, col: 16660 row: []
col: 16662 similar rows:  [16662]
11111111111111111111
incomplete name 3, col: 16662 row: []
col: 16664 similar rows:  [16664, 16787]
incomplete name 3, col: 16664 row: []
col: 16666 similar rows:  [16666]
11111111111111111111
incomplete name 3, col: 16666 row: []
col: 16669 similar rows:  [16669]
11111111111111111111
incomplete name 3, col: 16669 row: []
col: 16671 similar rows:  [16671, 16691]
incomplete name 3, col: 16671 row: []
col: 16675 similar rows:  [16675]
11111111111111111111
incomplete name 3, col: 16675 row: []
col: 16676 similar rows:  [16676, 16867]
incomplete name 3, col: 16676 row: []
col: 16679 similar rows:  [16679]
11111111111111111111
incomplete name 3, col: 16679 row: []
col: 16680 similar rows:  [16680]
11111111111111111111
incomplete name 3, col: 16680 row: []
col: 16683 similar rows:  [16683]
11111111111111111111
incomplete name 3, col: 16683 row: []
col: 16685 similar rows:  [16685]
11111111111111111111
hotelname2 [16685]
incomplete name 3, col: 16685 row: [16685]
col: 16688 similar rows:  [16688]
11111111111111111111
incomplete name 3, col: 16688 row: []
col: 16692 similar rows:  [16692]
11111111111111111111
hotelname2 [16692]
incomplete name 3, col: 16692 row: [16692]
col: 16693 similar rows:  [16693, 16917, 16978, 17104, 17166]
incomplete name 3, col: 16693 row: []
col: 16695 similar rows:  [16695, 16716]
incomplete name 3, col: 16695 row: []
col: 16697 similar rows:  [16697]
11111111111111111111
incomplete name 3, col: 16697 row: []
col: 16699 similar rows:  [16699, 16700]
incomplete name 3, col: 16699 row: []
col: 16701 similar rows:  [16701]
11111111111111111111
incomplete name 3, col: 16701 row: []
col: 16705 similar rows:  [16705]
11111111111111111111
incomplete name 3, col: 16705 row: []
col: 16706 similar rows:  [16706]
11111111111111111111
incomplete name 3, col: 16706 row: []
col: 16708 similar rows:  [16708]
11111111111111111111
incomplete name 3, col: 16708 row: []
col: 16709 similar rows:  [16709]
11111111111111111111
incomplete name 3, col: 16709 row: []
col: 16713 similar rows:  [16713]
11111111111111111111
incomplete name 3, col: 16713 row: []
col: 16714 similar rows:  [16714]
11111111111111111111
hotelname2 [16714]
incomplete name 3, col: 16714 row: []
col: 16720 similar rows:  [16720]
11111111111111111111
incomplete name 3, col: 16720 row: []
col: 16721 similar rows:  [16721]
11111111111111111111
incomplete name 3, col: 16721 row: []
col: 16722 similar rows:  [16722]
11111111111111111111
incomplete name 3, col: 16722 row: []
col: 16723 similar rows:  [16723]
11111111111111111111
hotelname2 [16723]
incomplete name 3, col: 16723 row: []
col: 16727 similar rows:  [16727]
11111111111111111111
incomplete name 3, col: 16727 row: []
col: 16728 similar rows:  [16728]
11111111111111111111
incomplete name 3, col: 16728 row: []
col: 16729 similar rows:  [16729]
11111111111111111111
incomplete name 3, col: 16729 row: []
col: 16732 similar rows:  [16732]
11111111111111111111
incomplete name 3, col: 16732 row: []
col: 16734 similar rows:  [16734]
11111111111111111111
incomplete name 3, col: 16734 row: []
col: 16735 similar rows:  [16735]
11111111111111111111
incomplete name 3, col: 16735 row: []
col: 16736 similar rows:  [16736]
11111111111111111111
incomplete name 3, col: 16736 row: []
col: 16737 similar rows:  [16737]
11111111111111111111
hotelname2 [16737]
incomplete name 3, col: 16737 row: [16737]
col: 16738 similar rows:  [16738, 16905, 16979]
incomplete name 3, col: 16738 row: []
col: 16745 similar rows:  [16745]
11111111111111111111
incomplete name 3, col: 16745 row: []
col: 16747 similar rows:  [16747]
11111111111111111111
incomplete name 3, col: 16747 row: []
col: 16750 similar rows:  [16750]
11111111111111111111
hotelname2 [16750]
incomplete name 3, col: 16750 row: [16750]
col: 16751 similar rows:  [16751]
11111111111111111111
hotelname2 [16751]
wrong name!!!!
incomplete name 3, col: 16751 row: [16751]
col: 16752 similar rows:  [16752]
11111111111111111111
incomplete name 3, col: 16752 row: []
col: 16754 similar rows:  [16754]
11111111111111111111
incomplete name 3, col: 16754 row: []
col: 16755 similar rows:  [16755]
11111111111111111111
incomplete name 3, col: 16755 row: []
col: 16756 similar rows:  [16756]
11111111111111111111
incomplete name 3, col: 16756 row: []
col: 16758 similar rows:  [16758]
11111111111111111111
incomplete name 3, col: 16758 row: []
col: 16760 similar rows:  [16760]
11111111111111111111
hotelname2 [16760]
incomplete name 3, col: 16760 row: [16760]
col: 16761 similar rows:  [16761]
11111111111111111111
hotelname2 [16761]
incomplete name 3, col: 16761 row: [16761]

col: 16762 similar rows:  [16762]
11111111111111111111
incomplete name 3, col: 16762 row: []
col: 16763 similar rows:  [16763]
11111111111111111111
incomplete name 3, col: 16763 row: []
col: 16764 similar rows:  [16764]
11111111111111111111
incomplete name 3, col: 16764 row: []
col: 16765 similar rows:  [16765]
11111111111111111111
incomplete name 3, col: 16765 row: []
col: 16766 similar rows:  [16766]
11111111111111111111
incomplete name 3, col: 16766 row: []
col: 16767 similar rows:  [16767]
11111111111111111111
incomplete name 3, col: 16767 row: []
col: 16768 similar rows:  [16768]
11111111111111111111
incomplete name 3, col: 16768 row: []
col: 16769 similar rows:  [16769]
11111111111111111111
incomplete name 3, col: 16769 row: []
col: 16770 similar rows:  [16770]
11111111111111111111
incomplete name 3, col: 16770 row: []
col: 16771 similar rows:  [16771]
11111111111111111111
incomplete name 3, col: 16771 row: []
col: 16773 similar rows:  [16773]
11111111111111111111
incomplete name 3, col: 16773 row: []
col: 16774 similar rows:  [16774]
11111111111111111111
incomplete name 3, col: 16774 row: []
col: 16775 similar rows:  [16775]
11111111111111111111
incomplete name 3, col: 16775 row: []
col: 16776 similar rows:  [16776]
11111111111111111111
incomplete name 3, col: 16776 row: []
col: 16778 similar rows:  [16778]
11111111111111111111
hotelname2 [16778]
incomplete name 3, col: 16778 row: []
col: 16779 similar rows:  [16779]
11111111111111111111
incomplete name 3, col: 16779 row: []
col: 16781 similar rows:  [16781]
11111111111111111111
incomplete name 3, col: 16781 row: []
col: 16782 similar rows:  [16782]
11111111111111111111
incomplete name 3, col: 16782 row: []
col: 16783 similar rows:  [16783]
11111111111111111111
incomplete name 3, col: 16783 row: []
col: 16785 similar rows:  [16785]
11111111111111111111
incomplete name 3, col: 16785 row: []
col: 16788 similar rows:  [16788, 16947]
incomplete name 3, col: 16788 row: []
col: 16789 similar rows:  [16789]
11111111111111111111
incomplete name 3, col: 16789 row: []
col: 16790 similar rows:  [16790]
11111111111111111111
incomplete name 3, col: 16790 row: []
col: 16791 similar rows:  [16791]
11111111111111111111
incomplete name 3, col: 16791 row: []
col: 16792 similar rows:  [16792]
11111111111111111111
incomplete name 3, col: 16792 row: []
col: 16793 similar rows:  [16793]
11111111111111111111
incomplete name 3, col: 16793 row: []
col: 16794 similar rows:  [16794]
11111111111111111111
incomplete name 3, col: 16794 row: []
col: 16795 similar rows:  [16795]
11111111111111111111
incomplete name 3, col: 16795 row: []
col: 16797 similar rows:  [16797]
11111111111111111111
incomplete name 3, col: 16797 row: []
col: 16798 similar rows:  [16798]
11111111111111111111
incomplete name 3, col: 16798 row: []
col: 16799 similar rows:  [16799]
11111111111111111111
hotelname2 [16799]
incomplete name 3, col: 16799 row: [16799]
col: 16800 similar rows:  [16800]
11111111111111111111
incomplete name 3, col: 16800 row: []
col: 16801 similar rows:  [16801]
11111111111111111111
incomplete name 3, col: 16801 row: []
col: 16803 similar rows:  [16803]
11111111111111111111
incomplete name 3, col: 16803 row: []
col: 16804 similar rows:  [16804, 16849]
incomplete name 3, col: 16804 row: []
col: 16806 similar rows:  [16806]
11111111111111111111
incomplete name 3, col: 16806 row: []
col: 16808 similar rows:  [16808]
11111111111111111111
incomplete name 3, col: 16808 row: []
col: 16810 similar rows:  [16810]
11111111111111111111
incomplete name 3, col: 16810 row: []
col: 16814 similar rows:  [16814]
11111111111111111111
incomplete name 3, col: 16814 row: []
col: 16815 similar rows:  [16815]
11111111111111111111
incomplete name 3, col: 16815 row: []
col: 16816 similar rows:  [16816]
11111111111111111111
incomplete name 3, col: 16816 row: []
col: 16817 similar rows:  [16817]
11111111111111111111
incomplete name 3, col: 16817 row: []
col: 16818 similar rows:  [16818]
11111111111111111111
incomplete name 3, col: 16818 row: []
col: 16820 similar rows:  [16820]
11111111111111111111
incomplete name 3, col: 16820 row: []
col: 16821 similar rows:  [16821]
11111111111111111111
incomplete name 3, col: 16821 row: []
col: 16822 similar rows:  [16822]
11111111111111111111
incomplete name 3, col: 16822 row: []
col: 16825 similar rows:  [16825]
11111111111111111111
incomplete name 3, col: 16825 row: []
col: 16826 similar rows:  [16826]
11111111111111111111
incomplete name 3, col: 16826 row: []
col: 16827 similar rows:  [16827]
11111111111111111111
incomplete name 3, col: 16827 row: []
col: 16829 similar rows:  [16829]
11111111111111111111
incomplete name 3, col: 16829 row: []
col: 16830 similar rows:  [16830]
11111111111111111111
incomplete name 3, col: 16830 row: []
col: 16832 similar rows:  [16832]
11111111111111111111
incomplete name 3, col: 16832 row: []
col: 16833 similar rows:  [16833]
11111111111111111111
incomplete name 3, col: 16833 row: []
col: 16836 similar rows:  [16836]
11111111111111111111
incomplete name 3, col: 16836 row: []
col: 16838 similar rows:  [16838]
11111111111111111111
incomplete name 3, col: 16838 row: []
col: 16840 similar rows:  [16840, 16892]
incomplete name 3, col: 16840 row: []
col: 16842 similar rows:  [16842]
11111111111111111111
incomplete name 3, col: 16842 row: []
col: 16843 similar rows:  [16843]
11111111111111111111
incomplete name 3, col: 16843 row: []
col: 16844 similar rows:  [16844]
11111111111111111111
incomplete name 3, col: 16844 row: []
col: 16846 similar rows:  [16846]
11111111111111111111
incomplete name 3, col: 16846 row: []
col: 16848 similar rows:  [16848]
11111111111111111111
incomplete name 3, col: 16848 row: []
col: 16851 similar rows:  [16851]
11111111111111111111
incomplete name 3, col: 16851 row: []
col: 16852 similar rows:  [16852]
11111111111111111111
incomplete name 3, col: 16852 row: []
col: 16853 similar rows:  [16853]
11111111111111111111
incomplete name 3, col: 16853 row: []
col: 16854 similar rows:  [16854]
11111111111111111111
incomplete name 3, col: 16854 row: []
col: 16856 similar rows:  [16856]
11111111111111111111
incomplete name 3, col: 16856 row: []
col: 16857 similar rows:  [16857]
11111111111111111111
hotelname2 [16857]
incomplete name 3, col: 16857 row: []
col: 16858 similar rows:  [16858]
11111111111111111111
incomplete name 3, col: 16858 row: []
col: 16862 similar rows:  [16862]
11111111111111111111
incomplete name 3, col: 16862 row: []
col: 16871 similar rows:  [16871]
11111111111111111111
hotelname2 [16871]
wrong name!!!!
incomplete name 3, col: 16871 row: [16871]
col: 16876 similar rows:  [16876]
11111111111111111111
incomplete name 3, col: 16876 row: []
col: 16878 similar rows:  [16878]
11111111111111111111
incomplete name 3, col: 16878 row: []
col: 16881 similar rows:  [16881]
11111111111111111111
incomplete name 3, col: 16881 row: []
col: 16882 similar rows:  [16882]
11111111111111111111
incomplete name 3, col: 16882 row: []
col: 16884 similar rows:  [16884]
11111111111111111111
hotelname2 [16884]
incomplete name 3, col: 16884 row: [16884]
col: 16888 similar rows:  [16888]
11111111111111111111
hotelname2 [16888]
incomplete name 3, col: 16888 row: [16888]
col: 16891 similar rows:  [16891]
11111111111111111111
incomplete name 3, col: 16891 row: []
col: 16893 similar rows:  [16893]
11111111111111111111
hotelname2 [16893]
incomplete name 3, col: 16893 row: []
col: 16897 similar rows:  [16897]
11111111111111111111
incomplete name 3, col: 16897 row: []
col: 16898 similar rows:  [16898]
11111111111111111111
hotelname2 [16898]
incomplete name 3, col: 16898 row: []
col: 16901 similar rows:  [16901]
11111111111111111111
incomplete name 3, col: 16901 row: []
col: 16903 similar rows:  [16903]
11111111111111111111
hotelname2 [16903]
incomplete name 3, col: 16903 row: [16903]
col: 16906 similar rows:  [16906]
11111111111111111111
incomplete name 3, col: 16906 row: []
col: 16908 similar rows:  [16908]
11111111111111111111
incomplete name 3, col: 16908 row: []
col: 16909 similar rows:  [16909, 17188]
incomplete name 3, col: 16909 row: []
col: 16911 similar rows:  [16911]
11111111111111111111
incomplete name 3, col: 16911 row: []
col: 16912 similar rows:  [16912]
11111111111111111111
incomplete name 3, col: 16912 row: []
col: 16913 similar rows:  [16913]
11111111111111111111
incomplete name 3, col: 16913 row: []
col: 16914 similar rows:  [16914]
11111111111111111111
incomplete name 3, col: 16914 row: []
col: 16915 similar rows:  [16915]
11111111111111111111
incomplete name 3, col: 16915 row: []

col: 16916 similar rows:  [16916]
11111111111111111111
incomplete name 3, col: 16916 row: []
col: 16918 similar rows:  [16918]
11111111111111111111
incomplete name 3, col: 16918 row: []
col: 16920 similar rows:  [16920]
11111111111111111111
incomplete name 3, col: 16920 row: []
col: 16923 similar rows:  [16923]
11111111111111111111
incomplete name 3, col: 16923 row: []
col: 16925 similar rows:  [16925]
11111111111111111111
incomplete name 3, col: 16925 row: []
col: 16930 similar rows:  [16930]
11111111111111111111
incomplete name 3, col: 16930 row: []
col: 16931 similar rows:  [16931]
11111111111111111111
incomplete name 3, col: 16931 row: []
col: 16940 similar rows:  [16940]
11111111111111111111
incomplete name 3, col: 16940 row: []
col: 16941 similar rows:  [16941]
11111111111111111111
incomplete name 3, col: 16941 row: []
col: 16944 similar rows:  [16944]
11111111111111111111
incomplete name 3, col: 16944 row: []
col: 16945 similar rows:  [16945]
11111111111111111111
incomplete name 3, col: 16945 row: []
col: 16946 similar rows:  [16946]
11111111111111111111
incomplete name 3, col: 16946 row: []
col: 16948 similar rows:  [16948]
11111111111111111111
incomplete name 3, col: 16948 row: []
col: 16949 similar rows:  [16949]
11111111111111111111
incomplete name 3, col: 16949 row: []
col: 16950 similar rows:  [16950]
11111111111111111111
incomplete name 3, col: 16950 row: []
col: 16951 similar rows:  [16951]
11111111111111111111
incomplete name 3, col: 16951 row: []
col: 16952 similar rows:  [16952]
11111111111111111111
hotelname2 [16952]
incomplete name 3, col: 16952 row: [16952]
col: 16953 similar rows:  [16953]
11111111111111111111
incomplete name 3, col: 16953 row: []
col: 16954 similar rows:  [16954]
11111111111111111111
incomplete name 3, col: 16954 row: []
col: 16955 similar rows:  [16955]
11111111111111111111
incomplete name 3, col: 16955 row: []
col: 16956 similar rows:  [16956]
11111111111111111111
incomplete name 3, col: 16956 row: []
col: 16959 similar rows:  [16959]
11111111111111111111
incomplete name 3, col: 16959 row: []
col: 16960 similar rows:  [16960]
11111111111111111111
incomplete name 3, col: 16960 row: []
col: 16961 similar rows:  [16961]
11111111111111111111
incomplete name 3, col: 16961 row: []
col: 16964 similar rows:  [16964]
11111111111111111111
incomplete name 3, col: 16964 row: []
col: 16966 similar rows:  [16966]
11111111111111111111
hotelname2 [16966]
incomplete name 3, col: 16966 row: [16966]
col: 16967 similar rows:  [16967]
11111111111111111111
hotelname2 [16967]
incomplete name 3, col: 16967 row: [16967]
col: 16968 similar rows:  [16968]
11111111111111111111
incomplete name 3, col: 16968 row: []
col: 16970 similar rows:  [16970]
11111111111111111111
incomplete name 3, col: 16970 row: []
col: 16975 similar rows:  [16975]
11111111111111111111
incomplete name 3, col: 16975 row: []
col: 16980 similar rows:  [16980, 16984, 16999, 17179]
incomplete name 3, col: 16980 row: []
col: 16982 similar rows:  [16982]
11111111111111111111
incomplete name 3, col: 16982 row: []
col: 16983 similar rows:  [16983]
11111111111111111111
incomplete name 3, col: 16983 row: []
col: 16987 similar rows:  [16987]
11111111111111111111
incomplete name 3, col: 16987 row: []
col: 16992 similar rows:  [16992]
11111111111111111111
incomplete name 3, col: 16992 row: []
col: 16993 similar rows:  [16993, 16994]
incomplete name 3, col: 16993 row: []
col: 16995 similar rows:  [16995]
11111111111111111111
incomplete name 3, col: 16995 row: []
col: 16996 similar rows:  [16996]
11111111111111111111
incomplete name 3, col: 16996 row: []
col: 16998 similar rows:  [16998]
11111111111111111111
incomplete name 3, col: 16998 row: []
col: 17000 similar rows:  [17000]
11111111111111111111
incomplete name 3, col: 17000 row: []
col: 17001 similar rows:  [17001]
11111111111111111111
incomplete name 3, col: 17001 row: []
col: 17003 similar rows:  [17003]
11111111111111111111
hotelname2 [17003]
incomplete name 3, col: 17003 row: [17003]
col: 17004 similar rows:  [17004]
11111111111111111111
incomplete name 3, col: 17004 row: []
col: 17005 similar rows:  [17005]
11111111111111111111
incomplete name 3, col: 17005 row: []
col: 17006 similar rows:  [17006]
11111111111111111111
hotelname2 [17006]
incomplete name 3, col: 17006 row: [17006]
col: 17007 similar rows:  [17007]
11111111111111111111
incomplete name 3, col: 17007 row: []
col: 17011 similar rows:  [17011]
11111111111111111111
incomplete name 3, col: 17011 row: []
col: 17012 similar rows:  [17012]
11111111111111111111
incomplete name 3, col: 17012 row: []
col: 17013 similar rows:  [17013]
11111111111111111111
incomplete name 3, col: 17013 row: []
col: 17015 similar rows:  [17015]
11111111111111111111
hotelname2 [17015]
incomplete name 3, col: 17015 row: [17015]
col: 17016 similar rows:  [17016]
11111111111111111111
incomplete name 3, col: 17016 row: []
col: 17017 similar rows:  [17017]
11111111111111111111
incomplete name 3, col: 17017 row: []
col: 17018 similar rows:  [17018]
11111111111111111111
incomplete name 3, col: 17018 row: []
col: 17019 similar rows:  [17019]
11111111111111111111
incomplete name 3, col: 17019 row: []
col: 17022 similar rows:  [17022]
11111111111111111111
incomplete name 3, col: 17022 row: []
col: 17023 similar rows:  [17023]
11111111111111111111
incomplete name 3, col: 17023 row: []
col: 17024 similar rows:  [17024]
11111111111111111111
incomplete name 3, col: 17024 row: []
col: 17027 similar rows:  [17027]
11111111111111111111
incomplete name 3, col: 17027 row: []
col: 17029 similar rows:  [17029]
11111111111111111111
incomplete name 3, col: 17029 row: []
col: 17030 similar rows:  [17030]
11111111111111111111
incomplete name 3, col: 17030 row: []
col: 17031 similar rows:  [17031]
11111111111111111111
incomplete name 3, col: 17031 row: []
col: 17032 similar rows:  [17032]
11111111111111111111
incomplete name 3, col: 17032 row: []
col: 17033 similar rows:  [17033]
11111111111111111111
incomplete name 3, col: 17033 row: []
col: 17034 similar rows:  [17034]
11111111111111111111
incomplete name 3, col: 17034 row: []
col: 17036 similar rows:  [17036]
11111111111111111111
incomplete name 3, col: 17036 row: []
col: 17037 similar rows:  [17037]
11111111111111111111
incomplete name 3, col: 17037 row: []
col: 17038 similar rows:  [17038]
11111111111111111111
incomplete name 3, col: 17038 row: []
col: 17039 similar rows:  [17039]
11111111111111111111
incomplete name 3, col: 17039 row: []
col: 17040 similar rows:  [17040]
11111111111111111111
incomplete name 3, col: 17040 row: []
col: 17041 similar rows:  [17041]
11111111111111111111
incomplete name 3, col: 17041 row: []
col: 17043 similar rows:  [17043]
11111111111111111111
incomplete name 3, col: 17043 row: []
col: 17044 similar rows:  [17044]
11111111111111111111
incomplete name 3, col: 17044 row: []
col: 17045 similar rows:  [17045]
11111111111111111111
incomplete name 3, col: 17045 row: []
col: 17046 similar rows:  [17046]
11111111111111111111
incomplete name 3, col: 17046 row: []
col: 17048 similar rows:  [17048]
11111111111111111111
incomplete name 3, col: 17048 row: []
col: 17051 similar rows:  [17051]
11111111111111111111
hotelname2 [17051]
incomplete name 3, col: 17051 row: [17051]
col: 17053 similar rows:  [17053]
11111111111111111111
incomplete name 3, col: 17053 row: []
col: 17056 similar rows:  [17056]
11111111111111111111
incomplete name 3, col: 17056 row: []
col: 17057 similar rows:  [17057]
11111111111111111111
incomplete name 3, col: 17057 row: []
col: 17058 similar rows:  [17058, 17104, 17166]
incomplete name 3, col: 17058 row: []
col: 17059 similar rows:  [17059, 17070]
incomplete name 3, col: 17059 row: []
col: 17061 similar rows:  [17061]
11111111111111111111
hotelname2 [17061]
incomplete name 3, col: 17061 row: []
col: 17062 similar rows:  [17062]
11111111111111111111
incomplete name 3, col: 17062 row: []
col: 17064 similar rows:  [17064]
11111111111111111111
incomplete name 3, col: 17064 row: []
col: 17065 similar rows:  [17065, 17082]
incomplete name 3, col: 17065 row: []
col: 17066 similar rows:  [17066]
11111111111111111111
incomplete name 3, col: 17066 row: []
col: 17069 similar rows:  [17069]
11111111111111111111
hotelname2 [17069]
incomplete name 3, col: 17069 row: [17069]
col: 17072 similar rows:  [17072]
11111111111111111111
incomplete name 3, col: 17072 row: []
col: 17074 similar rows:  [17074]
11111111111111111111
hotelname2 [17074]
wrong name!!!!
incomplete name 3, col: 17074 row: [17074]
col: 17077 similar rows:  [17077]
11111111111111111111
hotelname2 [17077]
incomplete name 3, col: 17077 row: [17077]
col: 17078 similar rows:  [17078]
11111111111111111111
incomplete name 3, col: 17078 row: []

col: 17083 similar rows:  [17083]
11111111111111111111
incomplete name 3, col: 17083 row: []
col: 17086 similar rows:  [17086]
11111111111111111111
incomplete name 3, col: 17086 row: []
col: 17087 similar rows:  [17087]
11111111111111111111
incomplete name 3, col: 17087 row: []
col: 17089 similar rows:  [17089]
11111111111111111111
hotelname2 [17089]
incomplete name 3, col: 17089 row: [17089]
col: 17091 similar rows:  [17091]
11111111111111111111
incomplete name 3, col: 17091 row: []
col: 17094 similar rows:  [17094]
11111111111111111111
hotelname2 [17094]
incomplete name 3, col: 17094 row: [17094]
col: 17095 similar rows:  [17095, 17116]
incomplete name 3, col: 17095 row: []
col: 17098 similar rows:  [17098, 17140, 17148]
incomplete name 3, col: 17098 row: []
col: 17099 similar rows:  [17099]
11111111111111111111
hotelname2 [17099]
incomplete name 3, col: 17099 row: [17099]
col: 17100 similar rows:  [17100]
11111111111111111111
incomplete name 3, col: 17100 row: []
col: 17105 similar rows:  [17105]
11111111111111111111
incomplete name 3, col: 17105 row: []
col: 17107 similar rows:  [17107]
11111111111111111111
incomplete name 3, col: 17107 row: []
col: 17108 similar rows:  [17108]
11111111111111111111
hotelname2 [17108]
incomplete name 3, col: 17108 row: [17108]
col: 17110 similar rows:  [17110]
11111111111111111111
incomplete name 3, col: 17110 row: []
col: 17111 similar rows:  [17111]
11111111111111111111
hotelname2 [17111]
incomplete name 3, col: 17111 row: [17111]
col: 17112 similar rows:  [17112]
11111111111111111111
incomplete name 3, col: 17112 row: []
col: 17114 similar rows:  [17114, 17115, 17118]
incomplete name 3, col: 17114 row: []
col: 17117 similar rows:  [17117]
11111111111111111111
incomplete name 3, col: 17117 row: []
col: 17119 similar rows:  [17119]
11111111111111111111
incomplete name 3, col: 17119 row: []
col: 17120 similar rows:  [17120]
11111111111111111111
incomplete name 3, col: 17120 row: []
col: 17123 similar rows:  [17123]
11111111111111111111
incomplete name 3, col: 17123 row: []
col: 17124 similar rows:  [17124]
11111111111111111111
incomplete name 3, col: 17124 row: []
col: 17127 similar rows:  [17127]
11111111111111111111
incomplete name 3, col: 17127 row: []
col: 17128 similar rows:  [17128]
11111111111111111111
incomplete name 3, col: 17128 row: []
col: 17129 similar rows:  [17129]
11111111111111111111
incomplete name 3, col: 17129 row: []
col: 17131 similar rows:  [17131]
11111111111111111111
incomplete name 3, col: 17131 row: []
col: 17132 similar rows:  [17132]
11111111111111111111
incomplete name 3, col: 17132 row: []
col: 17134 similar rows:  [17134]
11111111111111111111
incomplete name 3, col: 17134 row: []
col: 17136 similar rows:  [17136]
11111111111111111111
incomplete name 3, col: 17136 row: []
col: 17137 similar rows:  [17137]
11111111111111111111
hotelname2 [17137]
incomplete name 3, col: 17137 row: [17137]
col: 17138 similar rows:  [17138]
11111111111111111111
incomplete name 3, col: 17138 row: []
col: 17139 similar rows:  [17139]
11111111111111111111
incomplete name 3, col: 17139 row: []
col: 17144 similar rows:  [17144, 17183, 17185]
incomplete name 3, col: 17144 row: []
col: 17150 similar rows:  [17150]
11111111111111111111
incomplete name 3, col: 17150 row: []
col: 17152 similar rows:  [17152]
11111111111111111111
incomplete name 3, col: 17152 row: []
col: 17153 similar rows:  [17153]
11111111111111111111
incomplete name 3, col: 17153 row: []
col: 17154 similar rows:  [17154]
11111111111111111111
incomplete name 3, col: 17154 row: []
col: 17156 similar rows:  [17156]
11111111111111111111
incomplete name 3, col: 17156 row: []
col: 17157 similar rows:  [17157]
11111111111111111111
incomplete name 3, col: 17157 row: []
col: 17158 similar rows:  [17158]
11111111111111111111
incomplete name 3, col: 17158 row: []
col: 17160 similar rows:  [17160]
11111111111111111111
incomplete name 3, col: 17160 row: []
col: 17162 similar rows:  [17162]
11111111111111111111
incomplete name 3, col: 17162 row: []
col: 17165 similar rows:  [17165]
11111111111111111111
incomplete name 3, col: 17165 row: []
col: 17167 similar rows:  [17167]
11111111111111111111
incomplete name 3, col: 17167 row: []
col: 17171 similar rows:  [17171]
11111111111111111111
incomplete name 3, col: 17171 row: []
col: 17172 similar rows:  [17172]
11111111111111111111
incomplete name 3, col: 17172 row: []
col: 17174 similar rows:  [17174]
11111111111111111111
incomplete name 3, col: 17174 row: []
col: 17176 similar rows:  [17176]
11111111111111111111
incomplete name 3, col: 17176 row: []
col: 17178 similar rows:  [17178]
11111111111111111111
incomplete name 3, col: 17178 row: []
col: 17186 similar rows:  [17186]
11111111111111111111
incomplete name 3, col: 17186 row: []
col: 17191 similar rows:  [17191]
11111111111111111111
incomplete name 3, col: 17191 row: []
col: 17194 similar rows:  [17194]
11111111111111111111
incomplete name 3, col: 17194 row: []
col: 17195 similar rows:  [17195]
11111111111111111111
incomplete name 3, col: 17195 row: []
col: 17196 similar rows:  [17196]
11111111111111111111
incomplete name 3, col: 17196 row: []
col: 17199 similar rows:  [17199]
11111111111111111111
incomplete name 3, col: 17199 row: []
col: 17201 similar rows:  [17201]
11111111111111111111
incomplete name 3, col: 17201 row: []
col: 17203 similar rows:  [17203]
11111111111111111111
incomplete name 3, col: 17203 row: []
col: 17204 similar rows:  [17204]
11111111111111111111
incomplete name 3, col: 17204 row: []
col: 17205 similar rows:  [17205]
11111111111111111111
incomplete name 3, col: 17205 row: []
col: 17210 similar rows:  [17210]
11111111111111111111
incomplete name 3, col: 17210 row: []
col: 17218 similar rows:  [17218]
11111111111111111111
incomplete name 3, col: 17218 row: []
col: 17220 similar rows:  [17220]
11111111111111111111
incomplete name 3, col: 17220 row: []
col: 17222 similar rows:  [17222]
11111111111111111111
incomplete name 3, col: 17222 row: []
col: 17224 similar rows:  [17224]
11111111111111111111
incomplete name 3, col: 17224 row: []
col: 17225 similar rows:  [17225, 17232]
incomplete name 3, col: 17225 row: []
col: 17227 similar rows:  [17227]
11111111111111111111
incomplete name 3, col: 17227 row: []
col: 17230 similar rows:  [17230]
11111111111111111111
incomplete name 3, col: 17230 row: []
col: 17231 similar rows:  [17231]
11111111111111111111
incomplete name 3, col: 17231 row: []
end
col: 13348 similar rows:  [13348]
11111111111111111111
incomplete name 3, col: 13348 row: []
end